/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot

/**
 * Object that manages a registry of all available languages.
 *
 * Provides functions to retrieve languages by their code and to get a list of all defined languages.
 */
object LanguageRegistry {
  /**
   * List of all available languages.
   */
  private val allLanguages: List<Language> = listOf(
    Language.Afrikaans,
    Language.Aghem,
    Language.Akan,
    Language.Albanian,
    Language.Amharic,
    Language.Arabic,
    Language.Armenian,
    Language.Assamese,
    Language.Asturian,
    Language.Asu,
    Language.Azerbaijani,
    Language.Bafia,
    Language.Bambara,
    Language.Bangla,
    Language.Basaa,
    Language.Basque,
    Language.Belarusian,
    Language.Bemba,
    Language.Bena,
    Language.Bodo,
    Language.Bosnian,
    Language.Breton,
    Language.Bulgarian,
    Language.Burmese,
    Language.Cantonese,
    Language.Catalan,
    Language.CentralAtlasTamazight,
    Language.CentralKurdish,
    Language.Chakma,
    Language.Chechen,
    Language.Cherokee,
    Language.Chiga,
    Language.Chinese,
    Language.ChurchSlavic,
    Language.Colognian,
    Language.Cornish,
    Language.Croatian,
    Language.Czech,
    Language.Danish,
    Language.Duala,
    Language.Dutch,
    Language.Dzongkha,
    Language.Embu,
    Language.English,
    Language.Esperanto,
    Language.Estonian,
    Language.Ewe,
    Language.Ewondo,
    Language.Faroese,
    Language.Filipino,
    Language.Finnish,
    Language.French,
    Language.Friulian,
    Language.Fulah,
    Language.Galician,
    Language.Ganda,
    Language.Georgian,
    Language.German,
    Language.Greek,
    Language.Gujarati,
    Language.Gusii,
    Language.Hausa,
    Language.Hawaiian,
    Language.Hebrew,
    Language.Hindi,
    Language.Hungarian,
    Language.Icelandic,
    Language.Igbo,
    Language.InariSami,
    Language.Indonesian,
    Language.Irish,
    Language.Italian,
    Language.Japanese,
    Language.JolaFonyi,
    Language.Kabuverdianu,
    Language.Kabyle,
    Language.Kako,
    Language.Kalaallisut,
    Language.Kalenjin,
    Language.Kamba,
    Language.Kannada,
    Language.Kashmiri,
    Language.Kazakh,
    Language.Khmer,
    Language.Kikuyu,
    Language.Kinyarwanda,
    Language.Konkani,
    Language.Korean,
    Language.KoyraChiini,
    Language.KoyraboroSenni,
    Language.Kwasio,
    Language.Kyrgyz,
    Language.Lakota,
    Language.Langi,
    Language.Lao,
    Language.Latvian,
    Language.Lingala,
    Language.Lithuanian,
    Language.LowGerman,
    Language.LowerSorbian,
    Language.LubaKatanga,
    Language.Luo,
    Language.Luxembourgish,
    Language.Luyia,
    Language.Macedonian,
    Language.Machame,
    Language.MakhuwaMeetto,
    Language.Makonde,
    Language.Malagasy,
    Language.Malay,
    Language.Malayalam,
    Language.Maltese,
    Language.Manx,
    Language.Marathi,
    Language.Masai,
    Language.Mazanderani,
    Language.Meru,
    Language.Meta,
    Language.Mongolian,
    Language.Morisyen,
    Language.Mundang,
    Language.Nama,
    Language.Nepali,
    Language.Ngiemboon,
    Language.Ngomba,
    Language.NorthNdebele,
    Language.NorthernLuri,
    Language.NorthernSami,
    Language.Norwegian,
    Language.NorwegianBokmal,
    Language.NorwegianNynorsk,
    Language.Nuer,
    Language.Nyankole,
    Language.Odia,
    Language.Oromo,
    Language.Ossetic,
    Language.Pashto,
    Language.Persian,
    Language.Polish,
    Language.Portuguese,
    Language.Prussian,
    Language.Punjabi,
    Language.Quechua,
    Language.Romanian,
    Language.Romansh,
    Language.Rombo,
    Language.Rundi,
    Language.Russian,
    Language.Rwa,
    Language.Sakha,
    Language.Samburu,
    Language.Sango,
    Language.Sangu,
    Language.ScottishGaelic,
    Language.Sena,
    Language.Serbian,
    Language.Shambala,
    Language.Shona,
    Language.SichuanYi,
    Language.Sindhi,
    Language.Sinhala,
    Language.Slovak,
    Language.Slovenian,
    Language.Soga,
    Language.Somali,
    Language.Spanish,
    Language.StandardMoroccanTamazight,
    Language.Swahili,
    Language.Swedish,
    Language.SwissGerman,
    Language.Tachelhit,
    Language.Taita,
    Language.Tajik,
    Language.Tamil,
    Language.Tasawaq,
    Language.Tatar,
    Language.Telugu,
    Language.Teso,
    Language.Thai,
    Language.Tibetan,
    Language.Tigrinya,
    Language.Tongan,
    Language.Turkish,
    Language.Turkmen,
    Language.Ukrainian,
    Language.UpperSorbian,
    Language.Urdu,
    Language.Uyghur,
    Language.Uzbek,
    Language.Vai,
    Language.Vietnamese,
    Language.Volapuk,
    Language.Vunjo,
    Language.Walser,
    Language.Welsh,
    Language.WesternFrisian,
    Language.Wolof,
    Language.Yangben,
    Language.Yiddish,
    Language.Yoruba,
    Language.Zarma,
    Language.Zulu,
  )

  /**
   * Retrieves a language by its code.
   *
   * @param code The language code to search for.
   * @return The language object corresponding to the code, or `null` if not found.
   */
  fun getByCode(code: String): Language? {
    return allLanguages.firstOrNull { it.code == code }
  }

  /**
   * Retrieves all defined languages.
   *
   * @return A list of all language objects.
   */
  fun getAllLanguages(): List<Language> {
    return allLanguages
  }
}
