/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot.atlas.extended

import dev.teogor.xenoglot.atlas.CountryLocalization
import kotlin.collections.List

/**
 * Holds the internal list of country-language mappings used for lookups within the package for
 * language code ko.
 *
 * This property contains a hardcoded list of [CountryLocalization] objects, each representing
 * a country and its associated official languages. This list is used by [CountryLanguageRegistry]
 * to provide access to country-language data and should not be modified directly.
 *
 * @see CountryLocalization
 * @see CountryLanguageRegistry
 */
internal val _countryLanguageMappings_ko: List<CountryLocalization> = listOf(
  CountryLocalization("af", "페르시아어", "아프가니스탄"),
  CountryLocalization("al", "알바니아어", "알바니아"),
  CountryLocalization("dz", "프랑스어", "알제리"),
  CountryLocalization("as", "영어", "아메리칸 사모아"),
  CountryLocalization("ad", "카탈로니아어", "안도라"),
  CountryLocalization("ao", "링갈라어", "앙골라"),
  CountryLocalization("ai", "영어", "앵귈라"),
  CountryLocalization("ag", "영어", "앤티가 바부다"),
  CountryLocalization("ar", "스페인어", "아르헨티나"),
  CountryLocalization("am", "아르메니아어", "아르메니아"),
  CountryLocalization("aw", "네덜란드어", "아루바"),
  CountryLocalization("au", "영어", "오스트레일리아"),
  CountryLocalization("at", "영어", "오스트리아"),
  CountryLocalization("az", "아제르바이잔어", "아제르바이잔"),
  CountryLocalization("bs", "영어", "바하마"),
  CountryLocalization("bh", "아랍어", "바레인"),
  CountryLocalization("bd", "벵골어", "방글라데시"),
  CountryLocalization("bb", "영어", "바베이도스"),
  CountryLocalization("by", "벨라루스어", "벨라루스"),
  CountryLocalization("be", "프랑스어", "벨기에"),
  CountryLocalization("bz", "영어", "벨리즈"),
  CountryLocalization("bj", "프랑스어", "베냉"),
  CountryLocalization("bm", "영어", "버뮤다"),
  CountryLocalization("bt", "종카어", "부탄"),
  CountryLocalization("bo", "스페인어", "볼리비아"),
  CountryLocalization("ba", "보스니아어", "보스니아 헤르체고비나"),
  CountryLocalization("bw", "영어", "보츠와나"),
  CountryLocalization("br", "포르투갈어", "브라질"),
  CountryLocalization("io", "영어", "영국령 인도양 식민지"),
  CountryLocalization("vg", "영어", "영국령 버진아일랜드"),
  CountryLocalization("bn", "말레이어", "브루나이"),
  CountryLocalization("bg", "불가리아어", "불가리아"),
  CountryLocalization("bf", "프랑스어", "부르키나파소"),
  CountryLocalization("bi", "프랑스어", "부룬디"),
  CountryLocalization("kh", "크메르어", "캄보디아"),
  CountryLocalization("cm", "바사어", "카메룬"),
  CountryLocalization("ca", "프랑스어", "캐나다"),
  CountryLocalization("ic", "스페인어", "카나리아 제도"),
  CountryLocalization("cv", "크리올어", "카보베르데"),
  CountryLocalization("bq", "네덜란드어", "네덜란드령 카리브"),
  CountryLocalization("ky", "영어", "케이맨 제도"),
  CountryLocalization("cf", "링갈라어", "중앙 아프리카 공화국"),
  CountryLocalization("ea", "스페인어", "세우타 및 멜리야"),
  CountryLocalization("td", "아랍어", "차드"),
  CountryLocalization("cl", "스페인어", "칠레"),
  CountryLocalization("cn", "티베트어", "중국"),
  CountryLocalization("cx", "영어", "크리스마스섬"),
  CountryLocalization("cc", "영어", "코코스 제도"),
  CountryLocalization("co", "스페인어", "콜롬비아"),
  CountryLocalization("km", "아랍어", "코모로"),
  CountryLocalization("cg", "링갈라어", "콩고-브라자빌"),
  CountryLocalization("cd", "스와힐리어", "콩고-킨샤사"),
  CountryLocalization("ck", "영어", "쿡 제도"),
  CountryLocalization("cr", "스페인어", "코스타리카"),
  CountryLocalization("hr", "크로아티아어", "크로아티아"),
  CountryLocalization("cu", "스페인어", "쿠바"),
  CountryLocalization("cw", "네덜란드어", "퀴라소"),
  CountryLocalization("cy", "영어", "키프로스"),
  CountryLocalization("cz", "체코어", "체코"),
  CountryLocalization("ci", "프랑스어", "코트디부아르"),
  CountryLocalization("dk", "영어", "덴마크"),
  CountryLocalization("dg", "영어", "디에고 가르시아"),
  CountryLocalization("dj", "프랑스어", "지부티"),
  CountryLocalization("dm", "영어", "도미니카"),
  CountryLocalization("do", "스페인어", "도미니카 공화국"),
  CountryLocalization("ec", "케추아어", "에콰도르"),
  CountryLocalization("eg", "아랍어", "이집트"),
  CountryLocalization("sv", "스페인어", "엘살바도르"),
  CountryLocalization("gq", "스페인어", "적도 기니"),
  CountryLocalization("er", "티그리냐어", "에리트리아"),
  CountryLocalization("ee", "에스토니아어", "에스토니아"),
  CountryLocalization("et", "암하라어", "에티오피아"),
  CountryLocalization("fk", "영어", "포클랜드 제도"),
  CountryLocalization("fo", "페로어", "페로 제도"),
  CountryLocalization("fj", "영어", "피지"),
  CountryLocalization("fi", "스웨덴어", "핀란드"),
  CountryLocalization("fr", "독일어(스위스)", "프랑스"),
  CountryLocalization("gf", "프랑스어", "프랑스령 기아나"),
  CountryLocalization("pf", "프랑스어", "프랑스령 폴리네시아"),
  CountryLocalization("ga", "프랑스어", "가봉"),
  CountryLocalization("gm", "영어", "감비아"),
  CountryLocalization("ge", "오세트어", "조지아"),
  CountryLocalization("de", "저지 소르비아어", "독일"),
  CountryLocalization("gh", "영어", "가나"),
  CountryLocalization("gi", "영어", "지브롤터"),
  CountryLocalization("gr", "그리스어", "그리스"),
  CountryLocalization("gl", "그린란드어", "그린란드"),
  CountryLocalization("gd", "영어", "그레나다"),
  CountryLocalization("gp", "프랑스어", "과들루프"),
  CountryLocalization("gu", "영어", "괌"),
  CountryLocalization("gt", "스페인어", "과테말라"),
  CountryLocalization("gg", "영어", "건지"),
  CountryLocalization("gn", "프랑스어", "기니"),
  CountryLocalization("gw", "포르투갈어", "기니비사우"),
  CountryLocalization("gy", "영어", "가이아나"),
  CountryLocalization("ht", "프랑스어", "아이티"),
  CountryLocalization("hn", "스페인어", "온두라스"),
  CountryLocalization("hk", "중국어", "홍콩(중국 특별행정구)"),
  CountryLocalization("hu", "헝가리어", "헝가리"),
  CountryLocalization("is", "아이슬란드어", "아이슬란드"),
  CountryLocalization("in", "네팔어", "인도"),
  CountryLocalization("id", "인도네시아어", "인도네시아"),
  CountryLocalization("ir", "페르시아어", "이란"),
  CountryLocalization("iq", "북부 루리어", "이라크"),
  CountryLocalization("ie", "영어", "아일랜드"),
  CountryLocalization("im", "맹크스어", "맨 섬"),
  CountryLocalization("il", "영어", "이스라엘"),
  CountryLocalization("it", "독일어", "이탈리아"),
  CountryLocalization("jm", "영어", "자메이카"),
  CountryLocalization("jp", "일본어", "일본"),
  CountryLocalization("je", "영어", "저지"),
  CountryLocalization("jo", "아랍어", "요르단"),
  CountryLocalization("kz", "카자흐어", "카자흐스탄"),
  CountryLocalization("ke", "소말리아어", "케냐"),
  CountryLocalization("ki", "영어", "키리바시"),
  CountryLocalization("xk", "세르비아어", "코소보"),
  CountryLocalization("kw", "아랍어", "쿠웨이트"),
  CountryLocalization("kg", "러시아어", "키르기스스탄"),
  CountryLocalization("la", "라오어", "라오스"),
  CountryLocalization("lv", "라트비아어", "라트비아"),
  CountryLocalization("lb", "아랍어", "레바논"),
  CountryLocalization("ls", "영어", "레소토"),
  CountryLocalization("lr", "영어", "라이베리아"),
  CountryLocalization("ly", "아랍어", "리비아"),
  CountryLocalization("li", "독일어(스위스)", "리히텐슈타인"),
  CountryLocalization("lt", "리투아니아어", "리투아니아"),
  CountryLocalization("lu", "룩셈부르크어", "룩셈부르크"),
  CountryLocalization("mo", "포르투갈어", "마카오(중국 특별행정구)"),
  CountryLocalization("mk", "알바니아어", "마케도니아"),
  CountryLocalization("mg", "프랑스어", "마다가스카르"),
  CountryLocalization("mw", "영어", "말라위"),
  CountryLocalization("my", "타밀어", "말레이시아"),
  CountryLocalization("ml", "프랑스어", "말리"),
  CountryLocalization("mt", "영어", "몰타"),
  CountryLocalization("mh", "영어", "마셜 제도"),
  CountryLocalization("mq", "프랑스어", "마르티니크"),
  CountryLocalization("mr", "아랍어", "모리타니"),
  CountryLocalization("mu", "모리스얀어", "모리셔스"),
  CountryLocalization("yt", "프랑스어", "마요트"),
  CountryLocalization("mx", "스페인어", "멕시코"),
  CountryLocalization("fm", "영어", "미크로네시아"),
  CountryLocalization("md", "러시아어", "몰도바"),
  CountryLocalization("mc", "프랑스어", "모나코"),
  CountryLocalization("mn", "몽골어", "몽골"),
  CountryLocalization("me", "세르비아어", "몬테네그로"),
  CountryLocalization("ms", "영어", "몬트세라트"),
  CountryLocalization("ma", "중앙 모로코 타마지트어", "모로코"),
  CountryLocalization("mz", "마크후와-메토어", "모잠비크"),
  CountryLocalization("mm", "버마어", "미얀마"),
  CountryLocalization("na", "영어", "나미비아"),
  CountryLocalization("nr", "영어", "나우루"),
  CountryLocalization("np", "네팔어", "네팔"),
  CountryLocalization("nl", "영어", "네덜란드"),
  CountryLocalization("nc", "프랑스어", "뉴칼레도니아"),
  CountryLocalization("nz", "영어", "뉴질랜드"),
  CountryLocalization("ni", "스페인어", "니카라과"),
  CountryLocalization("ne", "하우사어", "니제르"),
  CountryLocalization("ng", "하우사어", "나이지리아"),
  CountryLocalization("nu", "영어", "니우에"),
  CountryLocalization("nf", "영어", "노퍽섬"),
  CountryLocalization("kp", "한국어", "조선민주주의인민공화국"),
  CountryLocalization("mp", "영어", "북마리아나제도"),
  CountryLocalization("no", "북부 사미어", "노르웨이"),
  CountryLocalization("om", "아랍어", "오만"),
  CountryLocalization("pk", "영어", "파키스탄"),
  CountryLocalization("pw", "영어", "팔라우"),
  CountryLocalization("ps", "아랍어", "팔레스타인 지구"),
  CountryLocalization("pa", "스페인어", "파나마"),
  CountryLocalization("pg", "영어", "파푸아뉴기니"),
  CountryLocalization("py", "스페인어", "파라과이"),
  CountryLocalization("pe", "스페인어", "페루"),
  CountryLocalization("ph", "필리핀어", "필리핀"),
  CountryLocalization("pn", "영어", "핏케언 섬"),
  CountryLocalization("pl", "폴란드어", "폴란드"),
  CountryLocalization("pt", "포르투갈어", "포르투갈"),
  CountryLocalization("pr", "영어", "푸에르토리코"),
  CountryLocalization("qa", "아랍어", "카타르"),
  CountryLocalization("ro", "루마니아어", "루마니아"),
  CountryLocalization("ru", "타타르어", "러시아"),
  CountryLocalization("rw", "영어", "르완다"),
  CountryLocalization("re", "프랑스어", "리유니온"),
  CountryLocalization("ws", "영어", "사모아"),
  CountryLocalization("sm", "이탈리아어", "산마리노"),
  CountryLocalization("sa", "아랍어", "사우디아라비아"),
  CountryLocalization("sn", "프랑스어", "세네갈"),
  CountryLocalization("rs", "세르비아어", "세르비아"),
  CountryLocalization("cs", "세르비아어", "세르비아 몬테네그로(유고슬라비아)"),
  CountryLocalization("sc", "프랑스어", "세이셸"),
  CountryLocalization("sl", "영어", "시에라리온"),
  CountryLocalization("sg", "타밀어", "싱가포르"),
  CountryLocalization("sx", "영어", "신트마르턴"),
  CountryLocalization("sk", "슬로바키아어", "슬로바키아"),
  CountryLocalization("si", "슬로베니아어", "슬로베니아"),
  CountryLocalization("sb", "영어", "솔로몬 제도"),
  CountryLocalization("so", "아랍어", "소말리아"),
  CountryLocalization("za", "영어", "남아프리카"),
  CountryLocalization("kr", "한국어", "대한민국"),
  CountryLocalization("ss", "누에르어", "남수단"),
  CountryLocalization("es", "스페인어", "스페인"),
  CountryLocalization("lk", "타밀어", "스리랑카"),
  CountryLocalization("bl", "프랑스어", "생바르텔레미"),
  CountryLocalization("sh", "영어", "세인트헬레나"),
  CountryLocalization("kn", "영어", "세인트키츠 네비스"),
  CountryLocalization("lc", "영어", "세인트루시아"),
  CountryLocalization("mf", "프랑스어", "생마르탱"),
  CountryLocalization("pm", "프랑스어", "생피에르 미클롱"),
  CountryLocalization("vc", "영어", "세인트빈센트그레나딘"),
  CountryLocalization("sd", "아랍어", "수단"),
  CountryLocalization("sr", "네덜란드어", "수리남"),
  CountryLocalization("sj", "노르웨이어(보크말)", "스발바르제도-얀마웬섬"),
  CountryLocalization("sz", "영어", "스와질란드"),
  CountryLocalization("se", "스웨덴어", "스웨덴"),
  CountryLocalization("ch", "독일어(스위스)", "스위스"),
  CountryLocalization("sy", "아랍어", "시리아"),
  CountryLocalization("st", "포르투갈어", "상투메 프린시페"),
  CountryLocalization("tw", "중국어", "대만"),
  CountryLocalization("tj", "타지크어", "타지키스탄"),
  CountryLocalization("tz", "마콘데어", "탄자니아"),
  CountryLocalization("th", "태국어", "태국"),
  CountryLocalization("tl", "포르투갈어", "동티모르"),
  CountryLocalization("tg", "프랑스어", "토고"),
  CountryLocalization("tk", "영어", "토켈라우"),
  CountryLocalization("to", "통가어", "통가"),
  CountryLocalization("tt", "영어", "트리니다드 토바고"),
  CountryLocalization("tn", "프랑스어", "튀니지"),
  CountryLocalization("tr", "터키어", "터키"),
  CountryLocalization("tm", "투르크멘어", "투르크메니스탄"),
  CountryLocalization("tc", "영어", "터크스 케이커스 제도"),
  CountryLocalization("tv", "영어", "투발루"),
  CountryLocalization("um", "영어", "미국령 해외 제도"),
  CountryLocalization("vi", "영어", "미국령 버진아일랜드"),
  CountryLocalization("ug", "스와힐리어", "우간다"),
  CountryLocalization("ua", "우크라이나어", "우크라이나"),
  CountryLocalization("ae", "아랍어", "아랍에미리트"),
  CountryLocalization("gb", "영어", "영국"),
  CountryLocalization("us", "라코타어", "미국"),
  CountryLocalization("uy", "스페인어", "우루과이"),
  CountryLocalization("uz", "우즈베크어", "우즈베키스탄"),
  CountryLocalization("vu", "프랑스어", "바누아투"),
  CountryLocalization("va", "이탈리아어", "바티칸 시국"),
  CountryLocalization("ve", "스페인어", "베네수엘라"),
  CountryLocalization("vn", "베트남어", "베트남"),
  CountryLocalization("wf", "프랑스어", "왈리스-푸투나 제도"),
  CountryLocalization("eh", "아랍어", "서사하라"),
  CountryLocalization("ye", "아랍어", "예멘"),
  CountryLocalization("zm", "영어", "잠비아"),
  CountryLocalization("zw", "북부 은데벨레어", "짐바브웨"),
  CountryLocalization("ax", "스웨덴어", "올란드 제도"),
)
