/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot.atlas.extended

import dev.teogor.xenoglot.atlas.CountryLocalization
import kotlin.collections.List

/**
 * Holds the internal list of country-language mappings used for lookups within the package for
 * language code de.
 *
 * This property contains a hardcoded list of [CountryLocalization] objects, each representing
 * a country and its associated official languages. This list is used by [CountryLanguageRegistry]
 * to provide access to country-language data and should not be modified directly.
 *
 * @see CountryLocalization
 * @see CountryLanguageRegistry
 */
internal val _countryLanguageMappings_de: List<CountryLocalization> = listOf(
  CountryLocalization("af", "Persisch", "Afghanistan"),
  CountryLocalization("al", "Albanisch", "Albanien"),
  CountryLocalization("dz", "Französisch", "Algerien"),
  CountryLocalization("as", "Englisch", "Amerikanisch-Samoa"),
  CountryLocalization("ad", "Katalanisch", "Andorra"),
  CountryLocalization("ao", "Lingala", "Angola"),
  CountryLocalization("ai", "Englisch", "Anguilla"),
  CountryLocalization("ag", "Englisch", "Antigua und Barbuda"),
  CountryLocalization("ar", "Spanisch", "Argentinien"),
  CountryLocalization("am", "Armenisch", "Armenien"),
  CountryLocalization("aw", "Niederländisch", "Aruba"),
  CountryLocalization("au", "Englisch", "Australien"),
  CountryLocalization("at", "Englisch", "Österreich"),
  CountryLocalization("az", "Aserbaidschanisch", "Aserbaidschan"),
  CountryLocalization("bs", "Englisch", "Bahamas"),
  CountryLocalization("bh", "Arabisch", "Bahrain"),
  CountryLocalization("bd", "Bengalisch", "Bangladesch"),
  CountryLocalization("bb", "Englisch", "Barbados"),
  CountryLocalization("by", "Weißrussisch", "Belarus"),
  CountryLocalization("be", "Französisch", "Belgien"),
  CountryLocalization("bz", "Englisch", "Belize"),
  CountryLocalization("bj", "Französisch", "Benin"),
  CountryLocalization("bm", "Englisch", "Bermuda"),
  CountryLocalization("bt", "Dzongkha", "Bhutan"),
  CountryLocalization("bo", "Spanisch", "Bolivien"),
  CountryLocalization("ba", "Bosnisch", "Bosnien und Herzegowina"),
  CountryLocalization("bw", "Englisch", "Botsuana"),
  CountryLocalization("br", "Portugiesisch", "Brasilien"),
  CountryLocalization("io", "Englisch", "Britisches Territorium im Indischen Ozean"),
  CountryLocalization("vg", "Englisch", "Britische Jungferninseln"),
  CountryLocalization("bn", "Malaiisch", "Brunei Darussalam"),
  CountryLocalization("bg", "Bulgarisch", "Bulgarien"),
  CountryLocalization("bf", "Französisch", "Burkina Faso"),
  CountryLocalization("bi", "Französisch", "Burundi"),
  CountryLocalization("kh", "Khmer", "Kambodscha"),
  CountryLocalization("cm", "Basaa", "Kamerun"),
  CountryLocalization("ca", "Französisch", "Kanada"),
  CountryLocalization("ic", "Spanisch", "Kanarische Inseln"),
  CountryLocalization("cv", "Kabuverdianu", "Cabo Verde"),
  CountryLocalization("bq", "Niederländisch", "Bonaire, Sint Eustatius und Saba"),
  CountryLocalization("ky", "Englisch", "Kaimaninseln"),
  CountryLocalization("cf", "Lingala", "Zentralafrikanische Republik"),
  CountryLocalization("ea", "Spanisch", "Ceuta und Melilla"),
  CountryLocalization("td", "Arabisch", "Tschad"),
  CountryLocalization("cl", "Spanisch", "Chile"),
  CountryLocalization("cn", "Tibetisch", "China"),
  CountryLocalization("cx", "Englisch", "Weihnachtsinsel"),
  CountryLocalization("cc", "Englisch", "Kokosinseln"),
  CountryLocalization("co", "Spanisch", "Kolumbien"),
  CountryLocalization("km", "Arabisch", "Komoren"),
  CountryLocalization("cg", "Lingala", "Kongo-Brazzaville"),
  CountryLocalization("cd", "Suaheli", "Kongo-Kinshasa"),
  CountryLocalization("ck", "Englisch", "Cookinseln"),
  CountryLocalization("cr", "Spanisch", "Costa Rica"),
  CountryLocalization("hr", "Kroatisch", "Kroatien"),
  CountryLocalization("cu", "Spanisch", "Kuba"),
  CountryLocalization("cw", "Niederländisch", "Curaçao"),
  CountryLocalization("cy", "Englisch", "Zypern"),
  CountryLocalization("cz", "Tschechisch", "Tschechien"),
  CountryLocalization("ci", "Französisch", "Côte d’Ivoire"),
  CountryLocalization("dk", "Englisch", "Dänemark"),
  CountryLocalization("dg", "Englisch", "Diego Garcia"),
  CountryLocalization("dj", "Französisch", "Dschibuti"),
  CountryLocalization("dm", "Englisch", "Dominica"),
  CountryLocalization("do", "Spanisch", "Dominikanische Republik"),
  CountryLocalization("ec", "Quechua", "Ecuador"),
  CountryLocalization("eg", "Arabisch", "Ägypten"),
  CountryLocalization("sv", "Spanisch", "El Salvador"),
  CountryLocalization("gq", "Spanisch", "Äquatorialguinea"),
  CountryLocalization("er", "Tigrinya", "Eritrea"),
  CountryLocalization("ee", "Estnisch", "Estland"),
  CountryLocalization("et", "Amharisch", "Äthiopien"),
  CountryLocalization("fk", "Englisch", "Falklandinseln"),
  CountryLocalization("fo", "Färöisch", "Färöer"),
  CountryLocalization("fj", "Englisch", "Fidschi"),
  CountryLocalization("fi", "Schwedisch", "Finnland"),
  CountryLocalization("fr", "Schweizerdeutsch", "Frankreich"),
  CountryLocalization("gf", "Französisch", "Französisch-Guayana"),
  CountryLocalization("pf", "Französisch", "Französisch-Polynesien"),
  CountryLocalization("ga", "Französisch", "Gabun"),
  CountryLocalization("gm", "Englisch", "Gambia"),
  CountryLocalization("ge", "Ossetisch", "Georgien"),
  CountryLocalization("de", "Niedersorbisch", "Deutschland"),
  CountryLocalization("gh", "Englisch", "Ghana"),
  CountryLocalization("gi", "Englisch", "Gibraltar"),
  CountryLocalization("gr", "Griechisch", "Griechenland"),
  CountryLocalization("gl", "Grönländisch", "Grönland"),
  CountryLocalization("gd", "Englisch", "Grenada"),
  CountryLocalization("gp", "Französisch", "Guadeloupe"),
  CountryLocalization("gu", "Englisch", "Guam"),
  CountryLocalization("gt", "Spanisch", "Guatemala"),
  CountryLocalization("gg", "Englisch", "Guernsey"),
  CountryLocalization("gn", "Französisch", "Guinea"),
  CountryLocalization("gw", "Portugiesisch", "Guinea-Bissau"),
  CountryLocalization("gy", "Englisch", "Guyana"),
  CountryLocalization("ht", "Französisch", "Haiti"),
  CountryLocalization("hn", "Spanisch", "Honduras"),
  CountryLocalization("hk", "Chinesisch", "Sonderverwaltungsregion Hongkong"),
  CountryLocalization("hu", "Ungarisch", "Ungarn"),
  CountryLocalization("is", "Isländisch", "Island"),
  CountryLocalization("in", "Nepalesisch", "Indien"),
  CountryLocalization("id", "Indonesisch", "Indonesien"),
  CountryLocalization("ir", "Persisch", "Iran"),
  CountryLocalization("iq", "Nördliches Luri", "Irak"),
  CountryLocalization("ie", "Englisch", "Irland"),
  CountryLocalization("im", "Manx", "Isle of Man"),
  CountryLocalization("il", "Englisch", "Israel"),
  CountryLocalization("it", "Deutsch", "Italien"),
  CountryLocalization("jm", "Englisch", "Jamaika"),
  CountryLocalization("jp", "Japanisch", "Japan"),
  CountryLocalization("je", "Englisch", "Jersey"),
  CountryLocalization("jo", "Arabisch", "Jordanien"),
  CountryLocalization("kz", "Kasachisch", "Kasachstan"),
  CountryLocalization("ke", "Somali", "Kenia"),
  CountryLocalization("ki", "Englisch", "Kiribati"),
  CountryLocalization("xk", "Serbisch", "Kosovo"),
  CountryLocalization("kw", "Arabisch", "Kuwait"),
  CountryLocalization("kg", "Russisch", "Kirgisistan"),
  CountryLocalization("la", "Laotisch", "Laos"),
  CountryLocalization("lv", "Lettisch", "Lettland"),
  CountryLocalization("lb", "Arabisch", "Libanon"),
  CountryLocalization("ls", "Englisch", "Lesotho"),
  CountryLocalization("lr", "Englisch", "Liberia"),
  CountryLocalization("ly", "Arabisch", "Libyen"),
  CountryLocalization("li", "Schweizerdeutsch", "Liechtenstein"),
  CountryLocalization("lt", "Litauisch", "Litauen"),
  CountryLocalization("lu", "Luxemburgisch", "Luxemburg"),
  CountryLocalization("mo", "Portugiesisch", "Sonderverwaltungsregion Macau"),
  CountryLocalization("mk", "Albanisch", "Mazedonien"),
  CountryLocalization("mg", "Französisch", "Madagaskar"),
  CountryLocalization("mw", "Englisch", "Malawi"),
  CountryLocalization("my", "Tamil", "Malaysia"),
  CountryLocalization("ml", "Französisch", "Mali"),
  CountryLocalization("mt", "Englisch", "Malta"),
  CountryLocalization("mh", "Englisch", "Marshallinseln"),
  CountryLocalization("mq", "Französisch", "Martinique"),
  CountryLocalization("mr", "Arabisch", "Mauretanien"),
  CountryLocalization("mu", "Morisyen", "Mauritius"),
  CountryLocalization("yt", "Französisch", "Mayotte"),
  CountryLocalization("mx", "Spanisch", "Mexiko"),
  CountryLocalization("fm", "Englisch", "Mikronesien"),
  CountryLocalization("md", "Russisch", "Republik Moldau"),
  CountryLocalization("mc", "Französisch", "Monaco"),
  CountryLocalization("mn", "Mongolisch", "Mongolei"),
  CountryLocalization("me", "Serbisch", "Montenegro"),
  CountryLocalization("ms", "Englisch", "Montserrat"),
  CountryLocalization("ma", "Zentralatlas-Tamazight", "Marokko"),
  CountryLocalization("mz", "Makhuwa-Meetto", "Mosambik"),
  CountryLocalization("mm", "Birmanisch", "Myanmar"),
  CountryLocalization("na", "Englisch", "Namibia"),
  CountryLocalization("nr", "Englisch", "Nauru"),
  CountryLocalization("np", "Nepalesisch", "Nepal"),
  CountryLocalization("nl", "Englisch", "Niederlande"),
  CountryLocalization("nc", "Französisch", "Neukaledonien"),
  CountryLocalization("nz", "Englisch", "Neuseeland"),
  CountryLocalization("ni", "Spanisch", "Nicaragua"),
  CountryLocalization("ne", "Haussa", "Niger"),
  CountryLocalization("ng", "Haussa", "Nigeria"),
  CountryLocalization("nu", "Englisch", "Niue"),
  CountryLocalization("nf", "Englisch", "Norfolkinsel"),
  CountryLocalization("kp", "Koreanisch", "Nordkorea"),
  CountryLocalization("mp", "Englisch", "Nördliche Marianen"),
  CountryLocalization("no", "Nordsamisch", "Norwegen"),
  CountryLocalization("om", "Arabisch", "Oman"),
  CountryLocalization("pk", "Englisch", "Pakistan"),
  CountryLocalization("pw", "Englisch", "Palau"),
  CountryLocalization("ps", "Arabisch", "Palästinensische Autonomiegebiete"),
  CountryLocalization("pa", "Spanisch", "Panama"),
  CountryLocalization("pg", "Englisch", "Papua-Neuguinea"),
  CountryLocalization("py", "Spanisch", "Paraguay"),
  CountryLocalization("pe", "Spanisch", "Peru"),
  CountryLocalization("ph", "Filipino", "Philippinen"),
  CountryLocalization("pn", "Englisch", "Pitcairninseln"),
  CountryLocalization("pl", "Polnisch", "Polen"),
  CountryLocalization("pt", "Portugiesisch", "Portugal"),
  CountryLocalization("pr", "Englisch", "Puerto Rico"),
  CountryLocalization("qa", "Arabisch", "Katar"),
  CountryLocalization("ro", "Rumänisch", "Rumänien"),
  CountryLocalization("ru", "Tatarisch", "Russland"),
  CountryLocalization("rw", "Englisch", "Ruanda"),
  CountryLocalization("re", "Französisch", "Réunion"),
  CountryLocalization("ws", "Englisch", "Samoa"),
  CountryLocalization("sm", "Italienisch", "San Marino"),
  CountryLocalization("sa", "Arabisch", "Saudi-Arabien"),
  CountryLocalization("sn", "Französisch", "Senegal"),
  CountryLocalization("rs", "Serbisch", "Serbien"),
  CountryLocalization("cs", "Serbisch", "Serbien und Montenegro"),
  CountryLocalization("sc", "Französisch", "Seychellen"),
  CountryLocalization("sl", "Englisch", "Sierra Leone"),
  CountryLocalization("sg", "Tamil", "Singapur"),
  CountryLocalization("sx", "Englisch", "Sint Maarten"),
  CountryLocalization("sk", "Slowakisch", "Slowakei"),
  CountryLocalization("si", "Slowenisch", "Slowenien"),
  CountryLocalization("sb", "Englisch", "Salomonen"),
  CountryLocalization("so", "Arabisch", "Somalia"),
  CountryLocalization("za", "Englisch", "Südafrika"),
  CountryLocalization("kr", "Koreanisch", "Südkorea"),
  CountryLocalization("ss", "Nuer", "Südsudan"),
  CountryLocalization("es", "Spanisch", "Spanien"),
  CountryLocalization("lk", "Tamil", "Sri Lanka"),
  CountryLocalization("bl", "Französisch", "St. Barthélemy"),
  CountryLocalization("sh", "Englisch", "St. Helena"),
  CountryLocalization("kn", "Englisch", "St. Kitts und Nevis"),
  CountryLocalization("lc", "Englisch", "St. Lucia"),
  CountryLocalization("mf", "Französisch", "St. Martin"),
  CountryLocalization("pm", "Französisch", "St. Pierre und Miquelon"),
  CountryLocalization("vc", "Englisch", "St. Vincent und die Grenadinen"),
  CountryLocalization("sd", "Arabisch", "Sudan"),
  CountryLocalization("sr", "Niederländisch", "Suriname"),
  CountryLocalization("sj", "Norwegisch Bokmål", "Spitzbergen und Jan Mayen"),
  CountryLocalization("sz", "Englisch", "Swasiland"),
  CountryLocalization("se", "Schwedisch", "Schweden"),
  CountryLocalization("ch", "Schweizerdeutsch", "Schweiz"),
  CountryLocalization("sy", "Arabisch", "Syrien"),
  CountryLocalization("st", "Portugiesisch", "São Tomé und Príncipe"),
  CountryLocalization("tw", "Chinesisch", "Taiwan"),
  CountryLocalization("tj", "Tadschikisch", "Tadschikistan"),
  CountryLocalization("tz", "Makonde", "Tansania"),
  CountryLocalization("th", "Thailändisch", "Thailand"),
  CountryLocalization("tl", "Portugiesisch", "Timor-Leste"),
  CountryLocalization("tg", "Französisch", "Togo"),
  CountryLocalization("tk", "Englisch", "Tokelau"),
  CountryLocalization("to", "Tongaisch", "Tonga"),
  CountryLocalization("tt", "Englisch", "Trinidad und Tobago"),
  CountryLocalization("tn", "Französisch", "Tunesien"),
  CountryLocalization("tr", "Türkisch", "Türkei"),
  CountryLocalization("tm", "Turkmenisch", "Turkmenistan"),
  CountryLocalization("tc", "Englisch", "Turks- und Caicosinseln"),
  CountryLocalization("tv", "Englisch", "Tuvalu"),
  CountryLocalization("um", "Englisch", "Amerikanische Überseeinseln"),
  CountryLocalization("vi", "Englisch", "Amerikanische Jungferninseln"),
  CountryLocalization("ug", "Suaheli", "Uganda"),
  CountryLocalization("ua", "Ukrainisch", "Ukraine"),
  CountryLocalization("ae", "Arabisch", "Vereinigte Arabische Emirate"),
  CountryLocalization("gb", "Englisch", "Vereinigtes Königreich"),
  CountryLocalization("us", "Lakota", "Vereinigte Staaten"),
  CountryLocalization("uy", "Spanisch", "Uruguay"),
  CountryLocalization("uz", "Usbekisch", "Usbekistan"),
  CountryLocalization("vu", "Französisch", "Vanuatu"),
  CountryLocalization("va", "Italienisch", "Vatikanstadt"),
  CountryLocalization("ve", "Spanisch", "Venezuela"),
  CountryLocalization("vn", "Vietnamesisch", "Vietnam"),
  CountryLocalization("wf", "Französisch", "Wallis und Futuna"),
  CountryLocalization("eh", "Arabisch", "Westsahara"),
  CountryLocalization("ye", "Arabisch", "Jemen"),
  CountryLocalization("zm", "Englisch", "Sambia"),
  CountryLocalization("zw", "Nord-Ndebele", "Simbabwe"),
  CountryLocalization("ax", "Schwedisch", "Ålandinseln"),
)
