/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot.atlas.extended

import dev.teogor.xenoglot.atlas.CountryLocalization
import kotlin.collections.List

/**
 * Holds the internal list of country-language mappings used for lookups within the package for
 * language code dz.
 *
 * This property contains a hardcoded list of [CountryLocalization] objects, each representing
 * a country and its associated official languages. This list is used by [CountryLanguageRegistry]
 * to provide access to country-language data and should not be modified directly.
 *
 * @see CountryLocalization
 * @see CountryLanguageRegistry
 */
internal val _countryLanguageMappings_dz: List<CountryLocalization> = listOf(
  CountryLocalization("af", "པར་ཤི་ཡཱན་ཁ", "ཨཕ་གྷ་ནི་སཏཱན"),
  CountryLocalization("al", "ཨཱལ་བེ་ནི་ཡཱན་ཁ", "ཨཱལ་བེ་ནི་ཡ"),
  CountryLocalization("dz", "ཕྲནཅ་ཁ", "ཨཱལ་ཇི་རི་ཡ"),
  CountryLocalization("as", "ཨིང་ལིཤ་ཁ", "ས་མོ་ཨ་ཡུ་ཨེས་ཨེ་མངའ་ཁོངས"),
  CountryLocalization("ad", "ཀེ་ཊ་ལཱན་ཁ", "ཨཱན་དོ་ར"),
  CountryLocalization("ao", "Lingala", "ཨང་གྷོ་ལ"),
  CountryLocalization("ai", "ཨིང་ལིཤ་ཁ", "ཨང་གི་ལ"),
  CountryLocalization("ag", "ཨིང་ལིཤ་ཁ", "ཨན་ཊི་གུ་ཝ་ ཨེནཌ་ བྷར་བྷུ་ཌ"),
  CountryLocalization("ar", "ཨིས་པེ་ནིཤ་ཁ", "ཨར་ཇེན་ཊི་ན"),
  CountryLocalization("am", "ཨར་མི་ནི་ཡཱན་ཁ", "ཨར་མི་ནི་ཡ"),
  CountryLocalization("aw", "ཌཆ་ཁ", "ཨ་རུ་བཱ"),
  CountryLocalization("au", "ཨིང་ལིཤ་ཁ", "ཨཱོས་ཊྲེལ་ལི་ཡ"),
  CountryLocalization("at", "ཨིང་ལིཤ་ཁ", "ཨཱོས་ཊྲི་ཡ"),
  CountryLocalization("az", "ཨ་ཛར་བྷའི་ཇཱན་ཁ", "ཨ་ཛར་བྷའི་ཇཱན"),
  CountryLocalization("bs", "ཨིང་ལིཤ་ཁ", "བྷ་ཧ་མས྄"),
  CountryLocalization("bh", "ཨེ་ར་བིཀ་ཁ", "བྷ་རེན"),
  CountryLocalization("bd", "བངྒ་ལ་ཁ", "བངྒ་ལ་དེཤ"),
  CountryLocalization("bb", "ཨིང་ལིཤ་ཁ", "བྷར་བེ་ཌོས"),
  CountryLocalization("by", "བེལ་ཨ་རུས་ཁ", "བེལ་ཨ་རུ་སུ"),
  CountryLocalization("be", "ཕྲནཅ་ཁ", "བྷེལ་ཇམ"),
  CountryLocalization("bz", "ཨིང་ལིཤ་ཁ", "བྷེ་ལིཛ"),
  CountryLocalization("bj", "ཕྲནཅ་ཁ", "བྷེ་ནིན"),
  CountryLocalization("bm", "ཨིང་ལིཤ་ཁ", "བར་མུ་ཌ"),
  CountryLocalization("bt", "རྫོང་ཁ", "འབྲུག"),
  CountryLocalization("bo", "ཨིས་པེ་ནིཤ་ཁ", "བྷེ་ལི་བི་ཡ"),
  CountryLocalization("ba", "བྷོས་ནི་ཡཱན་ཁ", "བྷོས་ནི་ཡ་ ཨེནཌ་ ཧར་ཛི་གྷོ་བི་ན"),
  CountryLocalization("bw", "ཨིང་ལིཤ་ཁ", "བྷོཙ་ཝ་ན"),
  CountryLocalization("br", "པོར་ཅུ་གིས་ཁ", "བྲ་ཛིལ"),
  CountryLocalization("io", "ཨིང་ལིཤ་ཁ", "བྲི་ཊིཤ་རྒྱ་གར་གྱི་རྒྱ་མཚོ་ས་ཁོངས"),
  CountryLocalization("vg", "ཨིང་ལིཤ་ཁ", "ཝརཇིན་གླིང་ཚོམ་ བྲཱི་ཊིཤ་མངའ་ཁོངས"),
  CountryLocalization("bn", "མ་ལེ་ཁ", "བྷྲུ་ནའི"),
  CountryLocalization("bg", "བཱལ་གེ་རི་ཡཱན་ཁ", "བུལ་ག་རི་ཡ"),
  CountryLocalization("bf", "ཕྲནཅ་ཁ", "བྷར་ཀི་ན་ ཕེ་སོ"),
  CountryLocalization("bi", "ཕྲནཅ་ཁ", "བྷུ་རུན་ཌི"),
  CountryLocalization("kh", "ཁེ་མེར་ཁ", "ཀམ་བྷོ་ཌི་ཡ"),
  CountryLocalization("cm", "Basaa", "ཀེ་མ་རུན"),
  CountryLocalization("ca", "ཕྲནཅ་ཁ", "ཀེ་ན་ཌ"),
  CountryLocalization("ic", "ཨིས་པེ་ནིཤ་ཁ", "ཀ་ནེ་རི་གླིང་ཚོམ"),
  CountryLocalization("cv", "kea", "ཀེཔ་བཱཌ"),
  CountryLocalization("bq", "ཌཆ་ཁ", "ཀེ་རི་བི་ཡེན་ནེ་དར་ལནཌས྄"),
  CountryLocalization("ky", "ཨིང་ལིཤ་ཁ", "ཁེ་མེན་གླིང་ཚོམ"),
  CountryLocalization("cf", "Lingala", "སེན་ཊལ་ ཨཕ་རི་ཀཱན་ རི་པབ་ལིཀ"),
  CountryLocalization("ea", "ཨིས་པེ་ནིཤ་ཁ", "སེ་ཨུ་ཏ་ ཨེནཌ་ མེལ་ལི་ལ"),
  CountryLocalization("td", "ཨེ་ར་བིཀ་ཁ", "ཅཱཌ"),
  CountryLocalization("cl", "ཨིས་པེ་ནིཤ་ཁ", "ཅི་ལི"),
  CountryLocalization("cn", "བོད་ཁ", "རྒྱ་ནག"),
  CountryLocalization("cx", "ཨིང་ལིཤ་ཁ", "ཁི་རིསྟ་མེས་མཚོ་གླིང"),
  CountryLocalization("cc", "ཨིང་ལིཤ་ཁ", "ཀོ་ཀོས་གླིང་ཚོམ"),
  CountryLocalization("co", "ཨིས་པེ་ནིཤ་ཁ", "ཀོ་ལོམ་བྷི་ཡ"),
  CountryLocalization("km", "ཨེ་ར་བིཀ་ཁ", "ཀོ་མོ་རོས"),
  CountryLocalization("cg", "Lingala", "ཀོང་གྷོ བྷྲ་ཛ་བིལ"),
  CountryLocalization("cd", "སྭཱ་ཧི་ལི་ཁ", "ཀོང་གྷོ ཀིན་ཤ་ས"),
  CountryLocalization("ck", "ཨིང་ལིཤ་ཁ", "ཀུག་གླིང་ཚོམ"),
  CountryLocalization("cr", "ཨིས་པེ་ནིཤ་ཁ", "ཀོས་ཊ་རི་ཀ"),
  CountryLocalization("hr", "ཀྲོ་ཨེ་ཤི་ཡཱན་ཁ", "ཀྲོ་ཨེ་ཤ"),
  CountryLocalization("cu", "ཨིས་པེ་ནིཤ་ཁ", "ཀིའུ་བྷ"),
  CountryLocalization("cw", "ཌཆ་ཁ", "ཀྱཱུར་ར་ཀོ"),
  CountryLocalization("cy", "ཨིང་ལིཤ་ཁ", "སཱའི་པྲས"),
  CountryLocalization("cz", "ཅེཀ་ཁ", "ཅེཀ་ རི་པབ་ལིཀ"),
  CountryLocalization("ci", "ཕྲནཅ་ཁ", "ཀོ་ཊེ་ ཌི་ཨི་ཝོ་རེ"),
  CountryLocalization("dk", "ཨིང་ལིཤ་ཁ", "ཌེན་མཱཀ"),
  CountryLocalization("dg", "ཨིང་ལིཤ་ཁ", "ཌི་ཡེ་གོ་གར་སིའོ"),
  CountryLocalization("dj", "ཕྲནཅ་ཁ", "ཇི་བྷུ་ཊི"),
  CountryLocalization("dm", "ཨིང་ལིཤ་ཁ", "ཌོ་མི་ནི་ཀ"),
  CountryLocalization("do", "ཨིས་པེ་ནིཤ་ཁ", "ཌོ་མི་ནི་ཀཱན་ རི་པབ་ལིཀ"),
  CountryLocalization("ec", "ཀྭེ་ཆུ་ཨ་ཁ", "ཨེ་ཁྭ་ཌོར"),
  CountryLocalization("eg", "ཨེ་ར་བིཀ་ཁ", "ཨི་ཇིབཊ"),
  CountryLocalization("sv", "ཨིས་པེ་ནིཤ་ཁ", "ཨེལ་སལ་བ་ཌོར"),
  CountryLocalization("gq", "ཨིས་པེ་ནིཤ་ཁ", "ཨེ་ཀུ་ཊོ་རེལ་ གི་ནི"),
  CountryLocalization("er", "ཏིག་རི་ཉ་ཁ", "ཨེ་རི་ཊྲེ་ཡ"),
  CountryLocalization("ee", "ཨེས་ཊོ་ནི་ཡཱན་ཁ", "ཨེས་ཊོ་ནི་ཡ"),
  CountryLocalization("et", "ཨམ་ཧ་རིཀ་ཁ", "ཨི་ཐི་ཡོ་པི་ཡ"),
  CountryLocalization("fk", "ཨིང་ལིཤ་ཁ", "ཕལྐ་ལནྜ་གླིང་ཚོམ"),
  CountryLocalization("fo", "ཕཱ་རོ་ཨིས་ཁ", "ཕཱའེ་རོ་གླིང་ཚོམ"),
  CountryLocalization("fj", "ཨིང་ལིཤ་ཁ", "ཕི་ཇི"),
  CountryLocalization("fi", "སུའི་ཌིཤ་ཁ", "ཕིན་ལེནཌ"),
  CountryLocalization("fr", "སུ་ཡིས་ཇཱར་མཱན་ཁ", "ཕྲཱནས"),
  CountryLocalization("gf", "ཕྲནཅ་ཁ", "གུའི་ཡ་ན་ ཕྲནས྄་མངའ་ཁོངས"),
  CountryLocalization("pf", "ཕྲནཅ་ཁ", "ཕྲཱནས྄་ཀྱི་པོ་ལི་ནི་ཤི་ཡ"),
  CountryLocalization("ga", "ཕྲནཅ་ཁ", "གྷ་བྷོན"),
  CountryLocalization("gm", "ཨིང་ལིཤ་ཁ", "གྷེམ་བི་ཡ"),
  CountryLocalization("ge", "Ossetic", "ཇཽར་ཇཱ"),
  CountryLocalization("de", "Lower Sorbian", "ཇཱར་མ་ནི"),
  CountryLocalization("gh", "ཨིང་ལིཤ་ཁ", "གྷ་ན"),
  CountryLocalization("gi", "ཨིང་ལིཤ་ཁ", "ཇིབ་རཱལ་ཊར"),
  CountryLocalization("gr", "གྲིཀ་ཁ", "གིརིས྄"),
  CountryLocalization("gl", "Kalaallisut", "གིརཱིན་ལནཌ྄"),
  CountryLocalization("gd", "ཨིང་ལིཤ་ཁ", "གྲྀ་ན་ཌ"),
  CountryLocalization("gp", "ཕྲནཅ་ཁ", "གོ་ཌེ་ལུ་པེ"),
  CountryLocalization("gu", "ཨིང་ལིཤ་ཁ", "གུ་འམ་ མཚོ་གླིང"),
  CountryLocalization("gt", "ཨིས་པེ་ནིཤ་ཁ", "གྷོ་ཊ་མ་ལ"),
  CountryLocalization("gg", "ཨིང་ལིཤ་ཁ", "གུ་ཨེརྣ་སི"),
  CountryLocalization("gn", "ཕྲནཅ་ཁ", "གྷི་ནི"),
  CountryLocalization("gw", "པོར་ཅུ་གིས་ཁ", "གྷི་ནི་ བྷི་སཱའུ"),
  CountryLocalization("gy", "ཨིང་ལིཤ་ཁ", "གྷ་ཡ་ན"),
  CountryLocalization("ht", "ཕྲནཅ་ཁ", "ཧེ་ཊི"),
  CountryLocalization("hn", "ཨིས་པེ་ནིཤ་ཁ", "ཧཱན་ཌུ་རཱས྄"),
  CountryLocalization("hk", "རྒྱ་མི་ཁ", "ཧོང་ཀོང་ཅཱའི་ན"),
  CountryLocalization("hu", "ཧཱང་གྷ་རི་ཡཱན་ཁ", "ཧཱང་གྷ་རི"),
  CountryLocalization("is", "ཨ་ཡིས་ལེན་ཌིཀ་ཁ", "ཨཱའིས་ལེནཌ"),
  CountryLocalization("in", "ནེ་པཱལི་ཁ", "རྒྱ་གར"),
  CountryLocalization("id", "Indonesian", "ཨིན་ཌོ་ནེ་ཤི་ཡ"),
  CountryLocalization("ir", "པར་ཤི་ཡཱན་ཁ", "ཨི་རཱན"),
  CountryLocalization("iq", "lrc", "ཨི་རཱཀ"),
  CountryLocalization("ie", "ཨིང་ལིཤ་ཁ", "ཨཱ་ཡ་ལེནཌ"),
  CountryLocalization("im", "Manx", "ཨ་ཡུལ་ ཨོཕ་ མཱན"),
  CountryLocalization("il", "ཨིང་ལིཤ་ཁ", "ཨིས་ར་ཡེལ"),
  CountryLocalization("it", "ཇཱར་མཱན་ཁ", "ཨི་ཊ་ལི"),
  CountryLocalization("jm", "ཨིང་ལིཤ་ཁ", "ཇཱ་མཻ་ཀ"),
  CountryLocalization("jp", "ཇཱ་པཱ་ནིས་ཁ", "ཇ་པཱན"),
  CountryLocalization("je", "ཨིང་ལིཤ་ཁ", "ཇེར་སི"),
  CountryLocalization("jo", "ཨེ་ར་བིཀ་ཁ", "ཇོར་ཌན"),
  CountryLocalization("kz", "ཀ་ཛགས་ཁ", "ཀ་ཛགས་སཏཱན"),
  CountryLocalization("ke", "སོ་མ་ལི་ཁ", "ཀེན་ཡ"),
  CountryLocalization("ki", "ཨིང་ལིཤ་ཁ", "ཀི་རི་བ་ཏི་མཚོ་གླིང"),
  CountryLocalization("xk", "སཱར་བྷི་ཡཱན་ཁ", "XK"),
  CountryLocalization("kw", "ཨེ་ར་བིཀ་ཁ", "ཀུ་ཝེཊ"),
  CountryLocalization("kg", "ཨུ་རུ་སུའི་ཁ", "ཀིར་གིས་སཏཱན"),
  CountryLocalization("la", "ལཱ་ཝོས་ཁ", "ལཱ་ཝོས"),
  CountryLocalization("lv", "ལཊ་བི་ཡཱན་ཁ", "ལཊ་བི་ཡ"),
  CountryLocalization("lb", "ཨེ་ར་བིཀ་ཁ", "ལེ་བ་ནོན"),
  CountryLocalization("ls", "ཨིང་ལིཤ་ཁ", "ལཻ་སོ་ཐོ"),
  CountryLocalization("lr", "ཨིང་ལིཤ་ཁ", "ལཱའི་བེ་རི་ཡ"),
  CountryLocalization("ly", "ཨེ་ར་བིཀ་ཁ", "ལི་བི་ཡ"),
  CountryLocalization("li", "སུ་ཡིས་ཇཱར་མཱན་ཁ", "ལིཀ་ཏནས་ཏ་ཡིན"),
  CountryLocalization("lt", "ལི་ཐུ་ཝེ་ནི་ཡཱན་ཁ", "ལི་ཐུ་ཝེ་ནི་ཡ"),
  CountryLocalization("lu", "ལག་ཛམ་བོརྒ་ཁ", "ལག་ཛམ་བོརྒ"),
  CountryLocalization("mo", "པོར་ཅུ་གིས་ཁ", "མཀ་ཨའུ་ཅཱའི་ན"),
  CountryLocalization("mk", "ཨཱལ་བེ་ནི་ཡཱན་ཁ", "མ་སེ་ཌོ་ནི་ཡ"),
  CountryLocalization("mg", "ཕྲནཅ་ཁ", "མ་དཱ་གེས་ཀར"),
  CountryLocalization("mw", "ཨིང་ལིཤ་ཁ", "མ་ལ་ཝི"),
  CountryLocalization("my", "ཏ་མིལ་ཁ", "མ་ལེ་ཤི་ཡ"),
  CountryLocalization("ml", "ཕྲནཅ་ཁ", "མཱ་ལི"),
  CountryLocalization("mt", "ཨིང་ལིཤ་ཁ", "མཱལ་ཊ"),
  CountryLocalization("mh", "ཨིང་ལིཤ་ཁ", "མར་ཤེལ་གླིང་ཚོམ"),
  CountryLocalization("mq", "ཕྲནཅ་ཁ", "མཱར་ཊི་ནིཀ"),
  CountryLocalization("mr", "ཨེ་ར་བིཀ་ཁ", "མོ་རི་ཊེ་ནི་ཡ"),
  CountryLocalization("mu", "mfe", "མོ་རི་ཤཱས"),
  CountryLocalization("yt", "ཕྲནཅ་ཁ", "མེ་ཡོཊ"),
  CountryLocalization("mx", "ཨིས་པེ་ནིཤ་ཁ", "མེཀ་སི་ཀོ"),
  CountryLocalization("fm", "ཨིང་ལིཤ་ཁ", "མའི་ཀྲོ་ནི་ཤི་ཡ"),
  CountryLocalization("md", "ཨུ་རུ་སུའི་ཁ", "མོལ་དོ་བཱ"),
  CountryLocalization("mc", "ཕྲནཅ་ཁ", "མོ་ན་ཀོ"),
  CountryLocalization("mn", "Mongolian", "སོག་པོ་ཡུལ"),
  CountryLocalization("me", "སཱར་བྷི་ཡཱན་ཁ", "མོན་ཊི་ནེག་རོ"),
  CountryLocalization("ms", "ཨིང་ལིཤ་ཁ", "མོན་ས་རཊ"),
  CountryLocalization("ma", "tzm", "མོ་རོ་ཀོ"),
  CountryLocalization("mz", "mgh", "མོ་ཛམ་བྷིཀ"),
  CountryLocalization("mm", "བར་མིས་ཁ", "མི་ཡཱན་མར་ (བྷར་མ)"),
  CountryLocalization("na", "ཨིང་ལིཤ་ཁ", "ན་མི་བི་ཡ"),
  CountryLocalization("nr", "ཨིང་ལིཤ་ཁ", "ནའུ་རུ་"),
  CountryLocalization("np", "ནེ་པཱལི་ཁ", "བལ་ཡུལ"),
  CountryLocalization("nl", "ཨིང་ལིཤ་ཁ", "ནེ་དར་ལནཌས྄"),
  CountryLocalization("nc", "ཕྲནཅ་ཁ", "ནིའུ་ཀ་ལི་དོ་ནི་ཡ"),
  CountryLocalization("nz", "ཨིང་ལིཤ་ཁ", "ནིའུ་ཛི་ལེནཌ"),
  CountryLocalization("ni", "ཨིས་པེ་ནིཤ་ཁ", "ནི་ཀྲ་ཝ་ག"),
  CountryLocalization("ne", "ཧཝ་ས་ཁ", "ནཱའི་ཇཱ"),
  CountryLocalization("ng", "ཧཝ་ས་ཁ", "ནཱའི་ཇི་རི་ཡ"),
  CountryLocalization("nu", "ཨིང་ལིཤ་ཁ", "ནི་ཨུ་ཨཻ"),
  CountryLocalization("nf", "ཨིང་ལིཤ་ཁ", "ནོར་ཕོལཀ་མཚོ་གླིང༌"),
  CountryLocalization("kp", "ཀོ་རི་ཡཱན་ཁ", "བྱང་ ཀོ་རི་ཡ"),
  CountryLocalization("mp", "ཨིང་ལིཤ་ཁ", "བྱང་ཕྱོགས་ཀྱི་མ་ར་ཡ་ན་གླིང་ཚོམ"),
  CountryLocalization("no", "Northern Sami", "ནོར་ཝེ"),
  CountryLocalization("om", "ཨེ་ར་བིཀ་ཁ", "ཨོ་མཱན"),
  CountryLocalization("pk", "ཨིང་ལིཤ་ཁ", "པ་ཀི་སཏཱན"),
  CountryLocalization("pw", "ཨིང་ལིཤ་ཁ", "པ་ལའུ"),
  CountryLocalization("ps", "ཨེ་ར་བིཀ་ཁ", "པེ་ལིསི་ཊི་ནི་ཡན་ཊེ་རི་ཐོ་རི"),
  CountryLocalization("pa", "ཨིས་པེ་ནིཤ་ཁ", "པ་ན་མ"),
  CountryLocalization("pg", "ཨིང་ལིཤ་ཁ", "པ་པུ་ ནིའུ་གི་ནི"),
  CountryLocalization("py", "ཨིས་པེ་ནིཤ་ཁ", "པ་ར་གུ་ཝའི"),
  CountryLocalization("pe", "ཨིས་པེ་ནིཤ་ཁ", "པེ་རུ"),
  CountryLocalization("ph", "ཕི་ལི་པི་ནོ་ཁ", "ཕི་ལི་པིནས"),
  CountryLocalization("pn", "ཨིང་ལིཤ་ཁ", "པིཊ་ཀེ་ཡེརན་གླིང་ཚོམ"),
  CountryLocalization("pl", "པོ་ལིཤ་ཁ", "པོ་ལེནཌ"),
  CountryLocalization("pt", "པོར་ཅུ་གིས་ཁ", "པོར་ཅུ་གཱལ"),
  CountryLocalization("pr", "ཨིང་ལིཤ་ཁ", "པུ་འེར་ཊོ་རི་ཁོ"),
  CountryLocalization("qa", "ཨེ་ར་བིཀ་ཁ", "ཀ་ཊར"),
  CountryLocalization("ro", "རོ་མེ་ནི་ཡཱན་ཁ", "རོ་མེ་ནི་ཡ"),
  CountryLocalization("ru", "ཊ་ཊར་ཁ", "ཨུ་རུ་སུ"),
  CountryLocalization("rw", "ཨིང་ལིཤ་ཁ", "རུ་ཝན་ཌ"),
  CountryLocalization("re", "ཕྲནཅ་ཁ", "རེ་ཡུ་ནི་ཡོན"),
  CountryLocalization("ws", "ཨིང་ལིཤ་ཁ", "ས་མོ་ཨ"),
  CountryLocalization("sm", "ཨི་ཊ་ལི་ཡཱན་ཁ", "སཱན་མ་རི་ནོ"),
  CountryLocalization("sa", "ཨེ་ར་བིཀ་ཁ", "སཱཝ་དི་ ཨ་རེ་བྷི་ཡ"),
  CountryLocalization("sn", "ཕྲནཅ་ཁ", "སེ་ནི་གྷལ"),
  CountryLocalization("rs", "སཱར་བྷི་ཡཱན་ཁ", "སཱར་བྷི་ཡ"),
  CountryLocalization("cs", "སཱར་བྷི་ཡཱན་ཁ", "Serbia and Montenegro"),
  CountryLocalization("sc", "ཕྲནཅ་ཁ", "སེ་ཤཱལས"),
  CountryLocalization("sl", "ཨིང་ལིཤ་ཁ", "སི་ར་ ལི་འོན"),
  CountryLocalization("sg", "ཏ་མིལ་ཁ", "སིང་ག་པོར"),
  CountryLocalization("sx", "ཨིང་ལིཤ་ཁ", "སིནཊ་ མཱར་ཊེན"),
  CountryLocalization("sk", "སུ་ལོ་བཱཀ་ཁ", "སུ་ལོ་བཱ་ཀི་ཡ"),
  CountryLocalization("si", "སུ་ལོ་བི་ནི་ཡཱན་ཁ", "སུ་ལོ་བི་ནི་ཡ"),
  CountryLocalization("sb", "ཨིང་ལིཤ་ཁ", "སོ་ལོ་མོན་ གླིང་ཚོམ"),
  CountryLocalization("so", "ཨེ་ར་བིཀ་ཁ", "སོ་མ་ལི་ཡ"),
  CountryLocalization("za", "ཨིང་ལིཤ་ཁ", "སཱའུཐ་ ཨཕ་རི་ཀ"),
  CountryLocalization("kr", "ཀོ་རི་ཡཱན་ཁ", "ལྷོ་ ཀོ་རི་ཡ"),
  CountryLocalization("ss", "nus", "སཱའུཐ་ སུ་ཌཱན"),
  CountryLocalization("es", "ཨིས་པེ་ནིཤ་ཁ", "ཨིས་པེན"),
  CountryLocalization("lk", "ཏ་མིལ་ཁ", "ཤྲཱི་ལང་ཀ"),
  CountryLocalization("bl", "ཕྲནཅ་ཁ", "སེནཊ་ བར་ཐོ་ལོམ་མིའུ"),
  CountryLocalization("sh", "ཨིང་ལིཤ་ཁ", "སེནཊ་ ཧེ་ལི་ན"),
  CountryLocalization("kn", "ཨིང་ལིཤ་ཁ", "སེནཊ་ ཀིཊས་ དང་ ནེ་བིས"),
  CountryLocalization("lc", "ཨིང་ལིཤ་ཁ", "སེནཊ་ ལུ་སི་ཡ"),
  CountryLocalization("mf", "ཕྲནཅ་ཁ", "སེནཊ་ མཱར་ཊིན"),
  CountryLocalization("pm", "ཕྲནཅ་ཁ", "སིནཊ་པི་ཡེར་ ཨེནཌ་ མིཀོ་ལེན"),
  CountryLocalization("vc", "ཨིང་ལིཤ་ཁ", "སེནཊ་ཝིན་སེནཌ྄ ཨེནཌ་ གི་རེ་ན་དིནས྄"),
  CountryLocalization("sd", "ཨེ་ར་བིཀ་ཁ", "སུ་ཌཱན"),
  CountryLocalization("sr", "ཌཆ་ཁ", "སུ་རི་ནཱམ"),
  CountryLocalization("sj", "ནོར་ཝེ་ཇི་ཡཱན་བོཀ་མཱལ་ཁ", "སྭཱལ་བྷརྡ་ ཨེནཌ་ ཇཱན་མ་ཡེན"),
  CountryLocalization("sz", "ཨིང་ལིཤ་ཁ", "སུ་ཝ་ཛི་ལེནཌ"),
  CountryLocalization("se", "སུའི་ཌིཤ་ཁ", "སུའི་ཌེན"),
  CountryLocalization("ch", "སུ་ཡིས་ཇཱར་མཱན་ཁ", "སུ་ཝིཊ་ཛར་ལེནཌ"),
  CountryLocalization("sy", "ཨེ་ར་བིཀ་ཁ", "སི་རི་ཡ"),
  CountryLocalization("st", "པོར་ཅུ་གིས་ཁ", "སཝ་ ཊོ་མེ་ ཨེནཌ་ པྲྀན་སི་པེ"),
  CountryLocalization("tw", "རྒྱ་མི་ཁ", "ཊཱའི་ཝཱན"),
  CountryLocalization("tj", "ཏ་ཇིཀ་ཁ", "ཏ་ཇིག་གི་སཏཱན"),
  CountryLocalization("tz", "kde", "ཊཱན་ཛཱ་ནི་ཡ"),
  CountryLocalization("th", "ཐཱའི་ཁ", "ཐཱའི་ལེནཌ"),
  CountryLocalization("tl", "པོར་ཅུ་གིས་ཁ", "ཏི་་མོར་ལེ་ཨེསཊ"),
  CountryLocalization("tg", "ཕྲནཅ་ཁ", "ཊོ་གྷོ"),
  CountryLocalization("tk", "ཨིང་ལིཤ་ཁ", "ཏོ་ཀེ་ལའུ་ མཚོ་གླིང"),
  CountryLocalization("to", "ཊོང་གྷན་ཁ", "ཊོང་གྷ"),
  CountryLocalization("tt", "ཨིང་ལིཤ་ཁ", "ཊི་ནི་ཌཱཌ་ ཨེནཌ་ ཊོ་བྷེ་གྷོ"),
  CountryLocalization("tn", "ཕྲནཅ་ཁ", "ཊུ་ནི་ཤི་ཡ"),
  CountryLocalization("tr", "ཊཱར་ཀིཤ་ཁ", "ཊཱར་ཀི"),
  CountryLocalization("tm", "ཊཱརཀ་མེན་ཁ", "ཊཱརཀ་མེནའི་སཏཱན"),
  CountryLocalization("tc", "ཨིང་ལིཤ་ཁ", "ཏུརྐས྄་ ཨེནཌ་ ཀ་ཀོས་གླིང་ཚོམ"),
  CountryLocalization("tv", "ཨིང་ལིཤ་ཁ", "ཏུ་ཝ་ལུ"),
  CountryLocalization("um", "ཨིང་ལིཤ་ཁ", "ཡུ་ཨེས་གྱི་མཐའ་མཚམས་མཚོ་གླིང་"),
  CountryLocalization("vi", "ཨིང་ལིཤ་ཁ", "ཝརཇིན་གླིང་ཚོམ་ ཡུ་ཨེས་ཨེ་མངའ་ཁོངས"),
  CountryLocalization("ug", "སྭཱ་ཧི་ལི་ཁ", "ཡུ་གྷན་ཌ"),
  CountryLocalization("ua", "ཡུ་ཀེ་རེ་ནི་ཡཱན་ཁ", "ཡུ་ཀརེན"),
  CountryLocalization("ae", "ཨེ་ར་བིཀ་ཁ", "ཡུ་ནཱའི་ཊེཌ་ ཨ་རབ་ ཨེ་མེ་རེཊས"),
  CountryLocalization("gb", "ཨིང་ལིཤ་ཁ", "ཡུ་ནཱའི་ཊེཌ་ ཀིང་ཌམ"),
  CountryLocalization("us", "lkt", "ཡུ་ཨེས་ཨེ"),
  CountryLocalization("uy", "ཨིས་པེ་ནིཤ་ཁ", "ཡུ་རུ་གུ་ཝའི"),
  CountryLocalization("uz", "ཨུས་བེཀ་ཁ", "ཨུས་བེག་གི་སཏཱན"),
  CountryLocalization("vu", "ཕྲནཅ་ཁ", "ཝ་ནུ་ཨ་ཏུ"),
  CountryLocalization("va", "ཨི་ཊ་ལི་ཡཱན་ཁ", "བ་ཊི་ཀཱན་ སི་ཊི"),
  CountryLocalization("ve", "ཨིས་པེ་ནིཤ་ཁ", "བེ་ནི་ཛུ་ཝེ་ལ"),
  CountryLocalization("vn", "བེཊ་ནཱ་མིས་ཁ", "བེཊ་ནཱམ"),
  CountryLocalization("wf", "ཕྲནཅ་ཁ", "ཝལ་ལིས྄་ ཨེནཌ་ ཕུ་ཏུ་ན་"),
  CountryLocalization("eh", "ཨེ་ར་བིཀ་ཁ", "ནུབ་ཕྱོགས་ ས་ཧཱ་ར"),
  CountryLocalization("ye", "ཨེ་ར་བིཀ་ཁ", "ཡེ་མེན"),
  CountryLocalization("zm", "ཨིང་ལིཤ་ཁ", "ཛམ་བྷི་ཡ"),
  CountryLocalization("zw", "North Ndebele", "ཛིམ་བྷབ་ཝེ"),
  CountryLocalization("ax", "སུའི་ཌིཤ་ཁ", "ཨ་ལནཌ་གླིང་ཚོམ"),
)
