/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot.atlas.extended

import dev.teogor.xenoglot.atlas.CountryLocalization
import kotlin.collections.List

/**
 * Holds the internal list of country-language mappings used for lookups within the package for
 * language code mfe.
 *
 * This property contains a hardcoded list of [CountryLocalization] objects, each representing
 * a country and its associated official languages. This list is used by [CountryLanguageRegistry]
 * to provide access to country-language data and should not be modified directly.
 *
 * @see CountryLocalization
 * @see CountryLanguageRegistry
 */
internal val _countryLanguageMappings_mfe: List<CountryLocalization> = listOf(
  CountryLocalization("af", "persan", "Afganistan"),
  CountryLocalization("al", "Albanian", "Albani"),
  CountryLocalization("dz", "franse", "Alzeri"),
  CountryLocalization("as", "angle", "Samoa amerikin"),
  CountryLocalization("ad", "Catalan", "Andor"),
  CountryLocalization("ao", "Lingala", "Angola"),
  CountryLocalization("ai", "angle", "Anguilla"),
  CountryLocalization("ag", "angle", "Antigua-ek-Barbuda"),
  CountryLocalization("ar", "espagnol", "Larzantinn"),
  CountryLocalization("am", "Armenian", "Armeni"),
  CountryLocalization("aw", "olande", "Aruba"),
  CountryLocalization("au", "angle", "Lostrali"),
  CountryLocalization("at", "angle", "Lostris"),
  CountryLocalization("az", "Azerbaijani", "Azerbaïdjan"),
  CountryLocalization("bs", "angle", "Bahamas"),
  CountryLocalization("bh", "arab", "Bahreïn"),
  CountryLocalization("bd", "bengali", "Banglades"),
  CountryLocalization("bb", "angle", "Barbad"),
  CountryLocalization("by", "bieloris", "Belaris"),
  CountryLocalization("be", "franse", "Belzik"),
  CountryLocalization("bz", "angle", "Beliz"),
  CountryLocalization("bj", "franse", "Benin"),
  CountryLocalization("bm", "angle", "Bermid"),
  CountryLocalization("bt", "Dzongkha", "Boutan"),
  CountryLocalization("bo", "espagnol", "Bolivi"),
  CountryLocalization("ba", "Bosnian", "Bosni-Herzegovinn"),
  CountryLocalization("bw", "angle", "Botswana"),
  CountryLocalization("br", "portige", "Brezil"),
  CountryLocalization("io", "angle", "Teritwar Britanik Losean Indien"),
  CountryLocalization("vg", "angle", "Zil vierz britanik"),
  CountryLocalization("bn", "male", "Brunei"),
  CountryLocalization("bg", "bilgar", "Bilgari"),
  CountryLocalization("bf", "franse", "Burkina Faso"),
  CountryLocalization("bi", "franse", "Burundi"),
  CountryLocalization("kh", "khmer, santral", "Kambodj"),
  CountryLocalization("cm", "Basaa", "Kamerounn"),
  CountryLocalization("ca", "franse", "Kanada"),
  CountryLocalization("ic", "espagnol", "IC"),
  CountryLocalization("cv", "kea", "Kap-Ver"),
  CountryLocalization("bq", "olande", "Caribbean Netherlands"),
  CountryLocalization("ky", "angle", "Zil Kayman"),
  CountryLocalization("cf", "Lingala", "Repiblik Lafrik Santral"),
  CountryLocalization("ea", "espagnol", "EA"),
  CountryLocalization("td", "arab", "Tchad"),
  CountryLocalization("cl", "espagnol", "Shili"),
  CountryLocalization("cn", "Tibetan", "Lasinn"),
  CountryLocalization("cx", "angle", "Christmas Island"),
  CountryLocalization("cc", "angle", "Cocos (Keeling) Islands"),
  CountryLocalization("co", "espagnol", "Kolonbi"),
  CountryLocalization("km", "arab", "Komor"),
  CountryLocalization("cg", "Lingala", "Kongo"),
  CountryLocalization("cd", "Swahili", "Repiblik demokratik Kongo"),
  CountryLocalization("ck", "angle", "Zil Cook"),
  CountryLocalization("cr", "espagnol", "Costa Rica"),
  CountryLocalization("hr", "Croatian", "Kroasi"),
  CountryLocalization("cu", "espagnol", "Cuba"),
  CountryLocalization("cw", "olande", "Curaçao"),
  CountryLocalization("cy", "angle", "Cyprus"),
  CountryLocalization("cz", "tchek", "Repiblik Chek"),
  CountryLocalization("ci", "franse", "Côte d’Ivoire"),
  CountryLocalization("dk", "angle", "Dannmark"),
  CountryLocalization("dg", "angle", "DG"),
  CountryLocalization("dj", "franse", "Djibouti"),
  CountryLocalization("dm", "angle", "Dominik"),
  CountryLocalization("do", "espagnol", "Repiblik dominikin"),
  CountryLocalization("ec", "Quechua", "Ekwater"),
  CountryLocalization("eg", "arab", "Lezipt"),
  CountryLocalization("sv", "espagnol", "Salvador"),
  CountryLocalization("gq", "espagnol", "Gine ekwatoryal"),
  CountryLocalization("er", "Tigrinya", "Erythre"),
  CountryLocalization("ee", "Estonian", "Estoni"),
  CountryLocalization("et", "amarik", "Letiopi"),
  CountryLocalization("fk", "angle", "Zil malwinn"),
  CountryLocalization("fo", "Faroese", "Faroe Islands"),
  CountryLocalization("fj", "angle", "Fidji"),
  CountryLocalization("fi", "swedwa", "Finland"),
  CountryLocalization("fr", "Swiss German", "Lafrans"),
  CountryLocalization("gf", "franse", "Gwiyann franse"),
  CountryLocalization("pf", "franse", "Polinezi franse"),
  CountryLocalization("ga", "franse", "Gabon"),
  CountryLocalization("gm", "angle", "Gambi"),
  CountryLocalization("ge", "Ossetic", "Zeorzi"),
  CountryLocalization("de", "Lower Sorbian", "Almagn"),
  CountryLocalization("gh", "angle", "Ghana"),
  CountryLocalization("gi", "angle", "Zibraltar"),
  CountryLocalization("gr", "grek", "Gres"),
  CountryLocalization("gl", "Kalaallisut", "Greenland"),
  CountryLocalization("gd", "angle", "Grenad"),
  CountryLocalization("gp", "franse", "Guadloup"),
  CountryLocalization("gu", "angle", "Guam"),
  CountryLocalization("gt", "espagnol", "Guatemala"),
  CountryLocalization("gg", "angle", "Guernsey"),
  CountryLocalization("gn", "franse", "Gine"),
  CountryLocalization("gw", "portige", "Gine-Bisau"),
  CountryLocalization("gy", "angle", "Guyana"),
  CountryLocalization("ht", "franse", "Ayti"),
  CountryLocalization("hn", "espagnol", "Honduras"),
  CountryLocalization("hk", "sinwa, mandarin", "Hong Kong SAR China"),
  CountryLocalization("hu", "hongrwa", "Ongri"),
  CountryLocalization("is", "Icelandic", "Island"),
  CountryLocalization("in", "nepale", "Lenn"),
  CountryLocalization("id", "Indonesian", "Indonezi"),
  CountryLocalization("ir", "persan", "Iran"),
  CountryLocalization("iq", "lrc", "Irak"),
  CountryLocalization("ie", "angle", "Irland"),
  CountryLocalization("im", "Manx", "Isle of Man"),
  CountryLocalization("il", "angle", "Izrael"),
  CountryLocalization("it", "alman", "Itali"),
  CountryLocalization("jm", "angle", "Zamaik"),
  CountryLocalization("jp", "zapone", "Zapon"),
  CountryLocalization("je", "angle", "Jersey"),
  CountryLocalization("jo", "arab", "Zordani"),
  CountryLocalization("kz", "Kazakh", "Kazakstan"),
  CountryLocalization("ke", "somali", "Kenya"),
  CountryLocalization("ki", "angle", "Kiribati"),
  CountryLocalization("xk", "Serbian", "XK"),
  CountryLocalization("kw", "arab", "Koweit"),
  CountryLocalization("kg", "ris", "Kirghizistan"),
  CountryLocalization("la", "Lao", "Laos"),
  CountryLocalization("lv", "Latvian", "Letoni"),
  CountryLocalization("lb", "arab", "Liban"),
  CountryLocalization("ls", "angle", "Lezoto"),
  CountryLocalization("lr", "angle", "Liberia"),
  CountryLocalization("ly", "arab", "Libi"),
  CountryLocalization("li", "Swiss German", "Liechtenstein"),
  CountryLocalization("lt", "Lithuanian", "Lituani"),
  CountryLocalization("lu", "Luxembourgish", "Luxembourg"),
  CountryLocalization("mo", "portige", "Macao SAR China"),
  CountryLocalization("mk", "Albanian", "Masedwann"),
  CountryLocalization("mg", "franse", "Madagaskar"),
  CountryLocalization("mw", "angle", "Malawi"),
  CountryLocalization("my", "tamoul", "Malezi"),
  CountryLocalization("ml", "franse", "Mali"),
  CountryLocalization("mt", "angle", "Malt"),
  CountryLocalization("mh", "angle", "Zil Marshall"),
  CountryLocalization("mq", "franse", "Martinik"),
  CountryLocalization("mr", "arab", "Moritani"),
  CountryLocalization("mu", "kreol morisien", "Moris"),
  CountryLocalization("yt", "franse", "Mayot"),
  CountryLocalization("mx", "espagnol", "Mexik"),
  CountryLocalization("fm", "angle", "Mikronezi"),
  CountryLocalization("md", "ris", "Moldavi"),
  CountryLocalization("mc", "franse", "Monako"),
  CountryLocalization("mn", "Mongolian", "Mongoli"),
  CountryLocalization("me", "Serbian", "Montenegro"),
  CountryLocalization("ms", "angle", "Montsera"),
  CountryLocalization("ma", "tzm", "Marok"),
  CountryLocalization("mz", "mgh", "Mozambik"),
  CountryLocalization("mm", "birman", "Myanmar"),
  CountryLocalization("na", "angle", "Namibi"),
  CountryLocalization("nr", "angle", "Nauru"),
  CountryLocalization("np", "nepale", "Nepal"),
  CountryLocalization("nl", "angle", "Oland"),
  CountryLocalization("nc", "franse", "Nouvel-Kaledoni"),
  CountryLocalization("nz", "angle", "Nouvel Zeland"),
  CountryLocalization("ni", "espagnol", "Nicaragua"),
  CountryLocalization("ne", "haoussa", "Nizer"),
  CountryLocalization("ng", "haoussa", "Nizeria"),
  CountryLocalization("nu", "angle", "Niowe"),
  CountryLocalization("nf", "angle", "Lil Norfolk"),
  CountryLocalization("kp", "koreen", "Lakore-dinor"),
  CountryLocalization("mp", "angle", "Zil Maryann dinor"),
  CountryLocalization("no", "Northern Sami", "Norvez"),
  CountryLocalization("om", "arab", "Oman"),
  CountryLocalization("pk", "angle", "Pakistan"),
  CountryLocalization("pw", "angle", "Palau"),
  CountryLocalization("ps", "arab", "Teritwar Palestinn"),
  CountryLocalization("pa", "espagnol", "Panama"),
  CountryLocalization("pg", "angle", "Papouazi-Nouvel-Gine"),
  CountryLocalization("py", "espagnol", "Paraguay"),
  CountryLocalization("pe", "espagnol", "Perou"),
  CountryLocalization("ph", "Filipino", "Filipinn"),
  CountryLocalization("pn", "angle", "Pitcairn"),
  CountryLocalization("pl", "polone", "Pologn"),
  CountryLocalization("pt", "portige", "Portigal"),
  CountryLocalization("pr", "angle", "Porto Rico"),
  CountryLocalization("qa", "arab", "Katar"),
  CountryLocalization("ro", "roumin", "Roumani"),
  CountryLocalization("ru", "Tatar", "Larisi"),
  CountryLocalization("rw", "angle", "Rwanda"),
  CountryLocalization("re", "franse", "Larenion"),
  CountryLocalization("ws", "angle", "Samoa"),
  CountryLocalization("sm", "italien", "Saint-Marin"),
  CountryLocalization("sa", "arab", "Larabi Saoudit"),
  CountryLocalization("sn", "franse", "Senegal"),
  CountryLocalization("rs", "Serbian", "Serbia"),
  CountryLocalization("cs", "Serbian", "Serbia and Montenegro"),
  CountryLocalization("sc", "franse", "Sesel"),
  CountryLocalization("sl", "angle", "Sierra Leone"),
  CountryLocalization("sg", "tamoul", "Singapour"),
  CountryLocalization("sx", "angle", "Sint Maarten"),
  CountryLocalization("sk", "Slovak", "Slovaki"),
  CountryLocalization("si", "Slovenian", "Sloveni"),
  CountryLocalization("sb", "angle", "Zil Salomon"),
  CountryLocalization("so", "arab", "Somali"),
  CountryLocalization("za", "angle", "Sid-Afrik"),
  CountryLocalization("kr", "koreen", "Lakore-disid"),
  CountryLocalization("ss", "nus", "South Sudan"),
  CountryLocalization("es", "espagnol", "Lespagn"),
  CountryLocalization("lk", "tamoul", "Sri Lanka"),
  CountryLocalization("bl", "franse", "St. Barthélemy"),
  CountryLocalization("sh", "angle", "Sainte-Hélène"),
  CountryLocalization("kn", "angle", "Saint-Christophe-ek-Niévès"),
  CountryLocalization("lc", "angle", "Sainte-Lucie"),
  CountryLocalization("mf", "franse", "St. Martin"),
  CountryLocalization("pm", "franse", "Saint-Pierre-ek-Miquelon"),
  CountryLocalization("vc", "angle", "Saint-Vincent-ek-Grenadines"),
  CountryLocalization("sd", "arab", "Soudan"),
  CountryLocalization("sr", "olande", "Surinam"),
  CountryLocalization("sj", "Norwegian Bokmål", "Svalbard & Jan Mayen"),
  CountryLocalization("sz", "angle", "Swaziland"),
  CountryLocalization("se", "swedwa", "Laswed"),
  CountryLocalization("ch", "Swiss German", "Laswis"),
  CountryLocalization("sy", "arab", "Lasiri"),
  CountryLocalization("st", "portige", "São Tome-ek-Prínsip"),
  CountryLocalization("tw", "sinwa, mandarin", "Taiwan"),
  CountryLocalization("tj", "Tajik", "Tadjikistan"),
  CountryLocalization("tz", "kde", "Tanzani"),
  CountryLocalization("th", "thaï", "Thayland"),
  CountryLocalization("tl", "portige", "Timor oriantal"),
  CountryLocalization("tg", "franse", "Togo"),
  CountryLocalization("tk", "angle", "Tokelau"),
  CountryLocalization("to", "Tongan", "Tonga"),
  CountryLocalization("tt", "angle", "Trinite-ek-Tobago"),
  CountryLocalization("tn", "franse", "Tinizi"),
  CountryLocalization("tr", "tirk", "Tirki"),
  CountryLocalization("tm", "Turkmen", "Turkmenistan"),
  CountryLocalization("tc", "angle", "Zil Tirk ek Caïcos"),
  CountryLocalization("tv", "angle", "Tuvalu"),
  CountryLocalization("um", "angle", "U.S. Outlying Islands"),
  CountryLocalization("vi", "angle", "Zil Vierz Lamerik"),
  CountryLocalization("ug", "Swahili", "Ouganda"),
  CountryLocalization("ua", "ikrenien", "Ikrenn"),
  CountryLocalization("ae", "arab", "Emira arab ini"),
  CountryLocalization("gb", "angle", "United Kingdom"),
  CountryLocalization("us", "lkt", "Lamerik"),
  CountryLocalization("uy", "espagnol", "Uruguay"),
  CountryLocalization("uz", "Uzbek", "Ouzbekistan"),
  CountryLocalization("vu", "franse", "Vanuatu"),
  CountryLocalization("va", "italien", "Lata Vatikan"),
  CountryLocalization("ve", "espagnol", "Venezuela"),
  CountryLocalization("vn", "vietnamien", "Vietnam"),
  CountryLocalization("wf", "franse", "Wallis-ek-Futuna"),
  CountryLocalization("eh", "arab", "Western Sahara"),
  CountryLocalization("ye", "arab", "Yemenn"),
  CountryLocalization("zm", "angle", "Zambi"),
  CountryLocalization("zw", "North Ndebele", "Zimbabwe"),
  CountryLocalization("ax", "swedwa", "Åland Islands"),
)
