/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot.atlas.extended

import dev.teogor.xenoglot.atlas.CountryLocalization
import kotlin.collections.List

/**
 * Holds the internal list of country-language mappings used for lookups within the package for
 * language code mgh.
 *
 * This property contains a hardcoded list of [CountryLocalization] objects, each representing
 * a country and its associated official languages. This list is used by [CountryLanguageRegistry]
 * to provide access to country-language data and should not be modified directly.
 *
 * @see CountryLocalization
 * @see CountryLanguageRegistry
 */
internal val _countryLanguageMappings_mgh: List<CountryLocalization> = listOf(
  CountryLocalization("af", "Iajemi", "Ufugustani"),
  CountryLocalization("al", "Albanian", "Ualbania"),
  CountryLocalization("dz", "Ifaransa", "Alujeria"),
  CountryLocalization("as", "Ingilishi", "Usamoa ya Marekani"),
  CountryLocalization("ad", "Catalan", "Uandora"),
  CountryLocalization("ao", "Lingala", "Angola"),
  CountryLocalization("ai", "Ingilishi", "Anguilla"),
  CountryLocalization("ag", "Ingilishi", "Antigua & Barbuda"),
  CountryLocalization("ar", "Ihispaniola", "Argentina"),
  CountryLocalization("am", "Armenian", "Armenia"),
  CountryLocalization("aw", "Iholanzi", "Aruba"),
  CountryLocalization("au", "Ingilishi", "Australia"),
  CountryLocalization("at", "Ingilishi", "Austria"),
  CountryLocalization("az", "Azerbaijani", "Uazabajani"),
  CountryLocalization("bs", "Ingilishi", "Bahamas"),
  CountryLocalization("bh", "Iarabu", "Bahrain"),
  CountryLocalization("bd", "Ibangla", "Bangladesh"),
  CountryLocalization("bb", "Ingilishi", "Barbados"),
  CountryLocalization("by", "Ibelausi", "Belarus"),
  CountryLocalization("be", "Ifaransa", "Belgium"),
  CountryLocalization("bz", "Ingilishi", "Belize"),
  CountryLocalization("bj", "Ifaransa", "Ubelin"),
  CountryLocalization("bm", "Ingilishi", "Bermuda"),
  CountryLocalization("bt", "Dzongkha", "Bhutan"),
  CountryLocalization("bo", "Ihispaniola", "Bolivia"),
  CountryLocalization("ba", "Bosnian", "Bosnia & Herzegovina"),
  CountryLocalization("bw", "Ingilishi", "Botswana"),
  CountryLocalization("br", "Nreno", "Brazil"),
  CountryLocalization("io", "Ingilishi", "British Indian Ocean Territory"),
  CountryLocalization("vg", "Ingilishi", "British Virgin Islands"),
  CountryLocalization("bn", "Imalesia", "Brunei"),
  CountryLocalization("bg", "Ibulgaria", "Bulgaria"),
  CountryLocalization("bf", "Ifaransa", "Burkina Faso"),
  CountryLocalization("bi", "Ifaransa", "Urundi"),
  CountryLocalization("kh", "Ikambodia", "Ukambodia"),
  CountryLocalization("cm", "Basaa", "Cameroon"),
  CountryLocalization("ca", "Ifaransa", "Ukanada"),
  CountryLocalization("ic", "Ihispaniola", "IC"),
  CountryLocalization("cv", "kea", "Cape Verde"),
  CountryLocalization("bq", "Iholanzi", "Caribbean Netherlands"),
  CountryLocalization("ky", "Ingilishi", "Cayman Islands"),
  CountryLocalization("cf", "Lingala", "Central African Republic"),
  CountryLocalization("ea", "Ihispaniola", "EA"),
  CountryLocalization("td", "Iarabu", "Uchadi"),
  CountryLocalization("cl", "Ihispaniola", "Uchile"),
  CountryLocalization("cn", "Tibetan", "Uchina"),
  CountryLocalization("cx", "Ingilishi", "Christmas Island"),
  CountryLocalization("cc", "Ingilishi", "Cocos (Keeling) Islands"),
  CountryLocalization("co", "Ihispaniola", "Ukolombia"),
  CountryLocalization("km", "Iarabu", "Ukomoro"),
  CountryLocalization("cg", "Lingala", "Ukongo"),
  CountryLocalization("cd", "Swahili", "Congo - Kinshasa"),
  CountryLocalization("ck", "Ingilishi", "Cook Islands"),
  CountryLocalization("cr", "Ihispaniola", "Costa Rica"),
  CountryLocalization("hr", "Croatian", "Ukorasia"),
  CountryLocalization("cu", "Ihispaniola", "Ukuba"),
  CountryLocalization("cw", "Iholanzi", "Curaçao"),
  CountryLocalization("cy", "Ingilishi", "Ukuprosi"),
  CountryLocalization("cz", "Icheki", "Ucheki"),
  CountryLocalization("ci", "Ifaransa", "Ukodiva"),
  CountryLocalization("dk", "Ingilishi", "Udenimaka"),
  CountryLocalization("dg", "Ingilishi", "DG"),
  CountryLocalization("dj", "Ifaransa", "Ujibuti"),
  CountryLocalization("dm", "Ingilishi", "Udominika"),
  CountryLocalization("do", "Ihispaniola", "Dominican Republic"),
  CountryLocalization("ec", "Quechua", "Ecuador"),
  CountryLocalization("eg", "Iarabu", "Umisiri"),
  CountryLocalization("sv", "Ihispaniola", "Usalavado"),
  CountryLocalization("gq", "Ihispaniola", "Equatorial Guinea"),
  CountryLocalization("er", "Tigrinya", "Uriterea"),
  CountryLocalization("ee", "Estonian", "Estonia"),
  CountryLocalization("et", "Imhari", "Uhabeshi"),
  CountryLocalization("fk", "Ingilishi", "Falkland Islands"),
  CountryLocalization("fo", "Faroese", "Faroe Islands"),
  CountryLocalization("fj", "Ingilishi", "Ufiji"),
  CountryLocalization("fi", "Iswidi", "Ufini"),
  CountryLocalization("fr", "Swiss German", "Ufaransa"),
  CountryLocalization("gf", "Ifaransa", "Ufaransa yo Gwaya"),
  CountryLocalization("pf", "Ifaransa", "Ufaransa yo Potina"),
  CountryLocalization("ga", "Ifaransa", "Ugaboni"),
  CountryLocalization("gm", "Ingilishi", "Ugambia"),
  CountryLocalization("ge", "Ossetic", "Ujojia"),
  CountryLocalization("de", "Lower Sorbian", "Germany"),
  CountryLocalization("gh", "Ingilishi", "Ugana"),
  CountryLocalization("gi", "Ingilishi", "Ujibralta"),
  CountryLocalization("gr", "Igiriki", "Greece"),
  CountryLocalization("gl", "Kalaallisut", "Ugrinlandi"),
  CountryLocalization("gd", "Ingilishi", "Ugrenada"),
  CountryLocalization("gp", "Ifaransa", "Ugwadelupe"),
  CountryLocalization("gu", "Ingilishi", "Ugwam"),
  CountryLocalization("gt", "Ihispaniola", "Ugwatemala"),
  CountryLocalization("gg", "Ingilishi", "Guernsey"),
  CountryLocalization("gn", "Ifaransa", "Ugine"),
  CountryLocalization("gw", "Nreno", "Uginebisau"),
  CountryLocalization("gy", "Ingilishi", "Uguyana"),
  CountryLocalization("ht", "Ifaransa", "Uhaiti"),
  CountryLocalization("hn", "Ihispaniola", "Uhondurasi"),
  CountryLocalization("hk", "Ichina", "Hong Kong SAR China"),
  CountryLocalization("hu", "Ihungari", "Uhungaria"),
  CountryLocalization("is", "Icelandic", "Iceland"),
  CountryLocalization("in", "Inepali", "Uhindini"),
  CountryLocalization("id", "Indonesian", "Undonesia"),
  CountryLocalization("ir", "Iajemi", "Iran"),
  CountryLocalization("iq", "lrc", "Wiraki"),
  CountryLocalization("ie", "Ingilishi", "Uayalandi"),
  CountryLocalization("im", "Manx", "Isle of Man"),
  CountryLocalization("il", "Ingilishi", "Uisraeli"),
  CountryLocalization("it", "Ijerimani", "Italia"),
  CountryLocalization("jm", "Ingilishi", "Ujamaika"),
  CountryLocalization("jp", "Ijapani", "Ujapani"),
  CountryLocalization("je", "Ingilishi", "Jersey"),
  CountryLocalization("jo", "Iarabu", "Uyordani"),
  CountryLocalization("kz", "Kazakh", "Ukazakistani"),
  CountryLocalization("ke", "Isomali", "Ukenya"),
  CountryLocalization("ki", "Ingilishi", "Kiribati"),
  CountryLocalization("xk", "Serbian", "XK"),
  CountryLocalization("kw", "Iarabu", "Kuwait"),
  CountryLocalization("kg", "Irisi", "Kyrgyzstan"),
  CountryLocalization("la", "Lao", "Laos"),
  CountryLocalization("lv", "Latvian", "Ulativia"),
  CountryLocalization("lb", "Iarabu", "Ulebanoni"),
  CountryLocalization("ls", "Ingilishi", "Ulesoto"),
  CountryLocalization("lr", "Ingilishi", "Uliberia"),
  CountryLocalization("ly", "Iarabu", "Ulibya"),
  CountryLocalization("li", "Swiss German", "Ushenteni"),
  CountryLocalization("lt", "Lithuanian", "Utwania"),
  CountryLocalization("lu", "Luxembourgish", "Usembaji"),
  CountryLocalization("mo", "Nreno", "Macao SAR China"),
  CountryLocalization("mk", "Albanian", "Umasedonia"),
  CountryLocalization("mg", "Ifaransa", "Ubukini"),
  CountryLocalization("mw", "Ingilishi", "Umalawi"),
  CountryLocalization("my", "Itamil", "Malaysia"),
  CountryLocalization("ml", "Ifaransa", "Mali"),
  CountryLocalization("mt", "Ingilishi", "Malta"),
  CountryLocalization("mh", "Ingilishi", "Marshall Islands"),
  CountryLocalization("mq", "Ifaransa", "Martinique"),
  CountryLocalization("mr", "Iarabu", "Mauritania"),
  CountryLocalization("mu", "mfe", "Mauritius"),
  CountryLocalization("yt", "Ifaransa", "Mayotte"),
  CountryLocalization("mx", "Ihispaniola", "Mexico"),
  CountryLocalization("fm", "Ingilishi", "Micronesia"),
  CountryLocalization("md", "Irisi", "Moldova"),
  CountryLocalization("mc", "Ifaransa", "Monaco"),
  CountryLocalization("mn", "Mongolian", "Mongolia"),
  CountryLocalization("me", "Serbian", "Umantegro"),
  CountryLocalization("ms", "Ingilishi", "Montserrat"),
  CountryLocalization("ma", "tzm", "Morocco"),
  CountryLocalization("mz", "Makua", "Umozambiki"),
  CountryLocalization("mm", "Iburma", "Myanmar (Burma)"),
  CountryLocalization("na", "Ingilishi", "Namibia"),
  CountryLocalization("nr", "Ingilishi", "Nauru"),
  CountryLocalization("np", "Inepali", "Nepal"),
  CountryLocalization("nl", "Ingilishi", "Netherlands"),
  CountryLocalization("nc", "Ifaransa", "New Caledonia"),
  CountryLocalization("nz", "Ingilishi", "New Zealand"),
  CountryLocalization("ni", "Ihispaniola", "Nicaragua"),
  CountryLocalization("ne", "Ihausa", "Unijeri"),
  CountryLocalization("ng", "Ihausa", "Unijeria"),
  CountryLocalization("nu", "Ingilishi", "Niue"),
  CountryLocalization("nf", "Ingilishi", "Norfolk Island"),
  CountryLocalization("kp", "Ikorea", "Ukorea Kaskazini"),
  CountryLocalization("mp", "Ingilishi", "Northern Mariana Islands"),
  CountryLocalization("no", "Northern Sami", "Unorwe"),
  CountryLocalization("om", "Iarabu", "Uomani"),
  CountryLocalization("pk", "Ingilishi", "Upakistani"),
  CountryLocalization("pw", "Ingilishi", "Palau"),
  CountryLocalization("ps", "Iarabu", "Palestinian Territories"),
  CountryLocalization("pa", "Ihispaniola", "Upanama"),
  CountryLocalization("pg", "Ingilishi", "Upapua"),
  CountryLocalization("py", "Ihispaniola", "Paragwai"),
  CountryLocalization("pe", "Ihispaniola", "Uperuu"),
  CountryLocalization("ph", "Filipino", "Ufilipino"),
  CountryLocalization("pn", "Ingilishi", "Upitkairni"),
  CountryLocalization("pl", "Ipolandi", "Upolandi"),
  CountryLocalization("pt", "Nreno", "Portugal"),
  CountryLocalization("pr", "Ingilishi", "Upwetoriko"),
  CountryLocalization("qa", "Iarabu", "Ukatari"),
  CountryLocalization("ro", "Iromania", "Uromania"),
  CountryLocalization("ru", "Tatar", "Russia"),
  CountryLocalization("rw", "Ingilishi", "Urwanda"),
  CountryLocalization("re", "Ifaransa", "Uriyunioni"),
  CountryLocalization("ws", "Ingilishi", "Usamoa"),
  CountryLocalization("sm", "Italiano", "Usamarino"),
  CountryLocalization("sa", "Iarabu", "Usaudi"),
  CountryLocalization("sn", "Ifaransa", "Usenegali"),
  CountryLocalization("rs", "Serbian", "Serbia"),
  CountryLocalization("cs", "Serbian", "Serbia and Montenegro"),
  CountryLocalization("sc", "Ifaransa", "Ushelisheli"),
  CountryLocalization("sl", "Ingilishi", "Sierra Leone"),
  CountryLocalization("sg", "Itamil", "Usingapoo"),
  CountryLocalization("sx", "Ingilishi", "Sint Maarten"),
  CountryLocalization("sk", "Slovak", "Uslovakia"),
  CountryLocalization("si", "Slovenian", "Uslovenia"),
  CountryLocalization("sb", "Ingilishi", "Solomon Islands"),
  CountryLocalization("so", "Iarabu", "Usomalia"),
  CountryLocalization("za", "Ingilishi", "Afrika du Sulu"),
  CountryLocalization("kr", "Ikorea", "Ukorea Kusini"),
  CountryLocalization("ss", "nus", "South Sudan"),
  CountryLocalization("es", "Ihispaniola", "Uhispania"),
  CountryLocalization("lk", "Itamil", "Usirilanka"),
  CountryLocalization("bl", "Ifaransa", "St. Barthélemy"),
  CountryLocalization("sh", "Ingilishi", "Usantahelena"),
  CountryLocalization("kn", "Ingilishi", "Usantakitzi na Nevis"),
  CountryLocalization("lc", "Ingilishi", "Usantalusia"),
  CountryLocalization("mf", "Ifaransa", "St. Martin"),
  CountryLocalization("pm", "Ifaransa", "Usantapieri na Mikeloni"),
  CountryLocalization("vc", "Ingilishi", "Usantavisenti na Grenadini"),
  CountryLocalization("sd", "Iarabu", "Usudani"),
  CountryLocalization("sr", "Iholanzi", "Usurinamu"),
  CountryLocalization("sj", "Norwegian Bokmål", "Svalbard & Jan Mayen"),
  CountryLocalization("sz", "Ingilishi", "Uswazi"),
  CountryLocalization("se", "Iswidi", "Uswidi"),
  CountryLocalization("ch", "Swiss German", "Uswisi"),
  CountryLocalization("sy", "Iarabu", "Usiria"),
  CountryLocalization("st", "Nreno", "Usao Tome na Principe"),
  CountryLocalization("tw", "Ichina", "Taiwan"),
  CountryLocalization("tj", "Tajik", "Ujikistani"),
  CountryLocalization("tz", "kde", "Utanzania"),
  CountryLocalization("th", "Itailandi", "Utailandi"),
  CountryLocalization("tl", "Nreno", "Utimo Mashariki"),
  CountryLocalization("tg", "Ifaransa", "Utogo"),
  CountryLocalization("tk", "Ingilishi", "Utokelau"),
  CountryLocalization("to", "Tongan", "Utonga"),
  CountryLocalization("tt", "Ingilishi", "Utrinidad na Tobago"),
  CountryLocalization("tn", "Ifaransa", "Utunisia"),
  CountryLocalization("tr", "Ituruki", "Utuki"),
  CountryLocalization("tm", "Turkmen", "Uturukimenistani"),
  CountryLocalization("tc", "Ingilishi", "Turks & Caicos Islands"),
  CountryLocalization("tv", "Ingilishi", "Utuvalu"),
  CountryLocalization("um", "Ingilishi", "U.S. Outlying Islands"),
  CountryLocalization("vi", "Ingilishi", "U.S. Virgin Islands"),
  CountryLocalization("ug", "Swahili", "Uganda"),
  CountryLocalization("ua", "Iukran", "Ukraine"),
  CountryLocalization("ae", "Iarabu", "United Arab Emirates"),
  CountryLocalization("gb", "Ingilishi", "United Kingdom"),
  CountryLocalization("us", "lkt", "Umarekani"),
  CountryLocalization("uy", "Ihispaniola", "Uruguay"),
  CountryLocalization("uz", "Uzbek", "Uzbekistan"),
  CountryLocalization("vu", "Ifaransa", "Uvanuatu"),
  CountryLocalization("va", "Italiano", "Uvatikani"),
  CountryLocalization("ve", "Ihispaniola", "Uvenezuela"),
  CountryLocalization("vn", "Ivyetinamu", "Uvietinamu"),
  CountryLocalization("wf", "Ifaransa", "Uwalis na Futuna"),
  CountryLocalization("eh", "Iarabu", "Western Sahara"),
  CountryLocalization("ye", "Iarabu", "Uyemeni"),
  CountryLocalization("zm", "Ingilishi", "Uzambia"),
  CountryLocalization("zw", "North Ndebele", "Uzimbabwe"),
  CountryLocalization("ax", "Iswidi", "Åland Islands"),
)
