/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot.atlas.extended

import dev.teogor.xenoglot.atlas.CountryLocalization
import kotlin.collections.List

/**
 * Holds the internal list of country-language mappings used for lookups within the package for
 * language code sl.
 *
 * This property contains a hardcoded list of [CountryLocalization] objects, each representing
 * a country and its associated official languages. This list is used by [CountryLanguageRegistry]
 * to provide access to country-language data and should not be modified directly.
 *
 * @see CountryLocalization
 * @see CountryLanguageRegistry
 */
internal val _countryLanguageMappings_sl: List<CountryLocalization> = listOf(
  CountryLocalization("af", "perzijščina", "Afganistan"),
  CountryLocalization("al", "albanščina", "Albanija"),
  CountryLocalization("dz", "francoščina", "Alžirija"),
  CountryLocalization("as", "angleščina", "Ameriška Samoa"),
  CountryLocalization("ad", "katalonščina", "Andora"),
  CountryLocalization("ao", "lingala", "Angola"),
  CountryLocalization("ai", "angleščina", "Angvila"),
  CountryLocalization("ag", "angleščina", "Antigva in Barbuda"),
  CountryLocalization("ar", "španščina", "Argentina"),
  CountryLocalization("am", "armenščina", "Armenija"),
  CountryLocalization("aw", "nizozemščina", "Aruba"),
  CountryLocalization("au", "angleščina", "Avstralija"),
  CountryLocalization("at", "angleščina", "Avstrija"),
  CountryLocalization("az", "azerbajdžanščina", "Azerbajdžan"),
  CountryLocalization("bs", "angleščina", "Bahami"),
  CountryLocalization("bh", "arabščina", "Bahrajn"),
  CountryLocalization("bd", "bengalščina", "Bangladeš"),
  CountryLocalization("bb", "angleščina", "Barbados"),
  CountryLocalization("by", "beloruščina", "Belorusija"),
  CountryLocalization("be", "francoščina", "Belgija"),
  CountryLocalization("bz", "angleščina", "Belize"),
  CountryLocalization("bj", "francoščina", "Benin"),
  CountryLocalization("bm", "angleščina", "Bermudi"),
  CountryLocalization("bt", "dzonka", "Butan"),
  CountryLocalization("bo", "španščina", "Bolivija"),
  CountryLocalization("ba", "bosanščina", "Bosna in Hercegovina"),
  CountryLocalization("bw", "angleščina", "Bocvana"),
  CountryLocalization("br", "portugalščina", "Brazilija"),
  CountryLocalization("io", "angleščina", "Britansko ozemlje v Indijskem oceanu"),
  CountryLocalization("vg", "angleščina", "Britanski Deviški otoki"),
  CountryLocalization("bn", "malajščina", "Brunej"),
  CountryLocalization("bg", "bolgarščina", "Bolgarija"),
  CountryLocalization("bf", "francoščina", "Burkina Faso"),
  CountryLocalization("bi", "francoščina", "Burundi"),
  CountryLocalization("kh", "kmerščina", "Kambodža"),
  CountryLocalization("cm", "basa", "Kamerun"),
  CountryLocalization("ca", "francoščina", "Kanada"),
  CountryLocalization("ic", "španščina", "Kanarski otoki"),
  CountryLocalization("cv", "zelenortskootoška kreolščina", "Zelenortski otoki"),
  CountryLocalization("bq", "nizozemščina", "Nizozemski Karibi"),
  CountryLocalization("ky", "angleščina", "Kajmanski otoki"),
  CountryLocalization("cf", "lingala", "Centralnoafriška republika"),
  CountryLocalization("ea", "španščina", "Ceuta in Melilla"),
  CountryLocalization("td", "arabščina", "Čad"),
  CountryLocalization("cl", "španščina", "Čile"),
  CountryLocalization("cn", "tibetanščina", "Kitajska"),
  CountryLocalization("cx", "angleščina", "Božični otok"),
  CountryLocalization("cc", "angleščina", "Kokosovi otoki"),
  CountryLocalization("co", "španščina", "Kolumbija"),
  CountryLocalization("km", "arabščina", "Komori"),
  CountryLocalization("cg", "lingala", "Kongo - Brazzaville"),
  CountryLocalization("cd", "svahili", "Demokratična republika Kongo"),
  CountryLocalization("ck", "angleščina", "Cookovi otoki"),
  CountryLocalization("cr", "španščina", "Kostarika"),
  CountryLocalization("hr", "hrvaščina", "Hrvaška"),
  CountryLocalization("cu", "španščina", "Kuba"),
  CountryLocalization("cw", "nizozemščina", "Curaçao"),
  CountryLocalization("cy", "angleščina", "Ciper"),
  CountryLocalization("cz", "češčina", "Češka"),
  CountryLocalization("ci", "francoščina", "Slonokoščena obala"),
  CountryLocalization("dk", "angleščina", "Danska"),
  CountryLocalization("dg", "angleščina", "Diego Garcia"),
  CountryLocalization("dj", "francoščina", "Džibuti"),
  CountryLocalization("dm", "angleščina", "Dominika"),
  CountryLocalization("do", "španščina", "Dominikanska republika"),
  CountryLocalization("ec", "kečuanščina", "Ekvador"),
  CountryLocalization("eg", "arabščina", "Egipt"),
  CountryLocalization("sv", "španščina", "Salvador"),
  CountryLocalization("gq", "španščina", "Ekvatorialna Gvineja"),
  CountryLocalization("er", "tigrajščina", "Eritreja"),
  CountryLocalization("ee", "estonščina", "Estonija"),
  CountryLocalization("et", "amharščina", "Etiopija"),
  CountryLocalization("fk", "angleščina", "Falklandski otoki"),
  CountryLocalization("fo", "ferščina", "Ferski otoki"),
  CountryLocalization("fj", "angleščina", "Fidži"),
  CountryLocalization("fi", "švedščina", "Finska"),
  CountryLocalization("fr", "nemščina (Švica)", "Francija"),
  CountryLocalization("gf", "francoščina", "Francoska Gvajana"),
  CountryLocalization("pf", "francoščina", "Francoska Polinezija"),
  CountryLocalization("ga", "francoščina", "Gabon"),
  CountryLocalization("gm", "angleščina", "Gambija"),
  CountryLocalization("ge", "osetinščina", "Gruzija"),
  CountryLocalization("de", "dolnja lužiška srbščina", "Nemčija"),
  CountryLocalization("gh", "angleščina", "Gana"),
  CountryLocalization("gi", "angleščina", "Gibraltar"),
  CountryLocalization("gr", "grščina", "Grčija"),
  CountryLocalization("gl", "grenlandščina", "Grenlandija"),
  CountryLocalization("gd", "angleščina", "Grenada"),
  CountryLocalization("gp", "francoščina", "Guadeloupe"),
  CountryLocalization("gu", "angleščina", "Guam"),
  CountryLocalization("gt", "španščina", "Gvatemala"),
  CountryLocalization("gg", "angleščina", "Guernsey"),
  CountryLocalization("gn", "francoščina", "Gvineja"),
  CountryLocalization("gw", "portugalščina", "Gvineja Bissau"),
  CountryLocalization("gy", "angleščina", "Gvajana"),
  CountryLocalization("ht", "francoščina", "Haiti"),
  CountryLocalization("hn", "španščina", "Honduras"),
  CountryLocalization("hk", "kitajščina", "Posebno administrativno območje LR Kitajske Hongkong"),
  CountryLocalization("hu", "madžarščina", "Madžarska"),
  CountryLocalization("is", "islandščina", "Islandija"),
  CountryLocalization("in", "nepalščina", "Indija"),
  CountryLocalization("id", "Indonesian", "Indonezija"),
  CountryLocalization("ir", "perzijščina", "Iran"),
  CountryLocalization("iq", "severna lurijščina", "Irak"),
  CountryLocalization("ie", "angleščina", "Irska"),
  CountryLocalization("im", "manščina", "Otok Man"),
  CountryLocalization("il", "angleščina", "Izrael"),
  CountryLocalization("it", "nemščina", "Italija"),
  CountryLocalization("jm", "angleščina", "Jamajka"),
  CountryLocalization("jp", "japonščina", "Japonska"),
  CountryLocalization("je", "angleščina", "Jersey"),
  CountryLocalization("jo", "arabščina", "Jordanija"),
  CountryLocalization("kz", "kazaščina", "Kazahstan"),
  CountryLocalization("ke", "somalščina", "Kenija"),
  CountryLocalization("ki", "angleščina", "Kiribati"),
  CountryLocalization("xk", "srbščina", "Kosovo"),
  CountryLocalization("kw", "arabščina", "Kuvajt"),
  CountryLocalization("kg", "ruščina", "Kirgizistan"),
  CountryLocalization("la", "laoščina", "Laos"),
  CountryLocalization("lv", "latvijščina", "Latvija"),
  CountryLocalization("lb", "arabščina", "Libanon"),
  CountryLocalization("ls", "angleščina", "Lesoto"),
  CountryLocalization("lr", "angleščina", "Liberija"),
  CountryLocalization("ly", "arabščina", "Libija"),
  CountryLocalization("li", "nemščina (Švica)", "Lihtenštajn"),
  CountryLocalization("lt", "litovščina", "Litva"),
  CountryLocalization("lu", "luksemburščina", "Luksemburg"),
  CountryLocalization("mo", "portugalščina", "Posebno administrativno območje LR Kitajske Macao"),
  CountryLocalization("mk", "albanščina", "Makedonija"),
  CountryLocalization("mg", "francoščina", "Madagaskar"),
  CountryLocalization("mw", "angleščina", "Malavi"),
  CountryLocalization("my", "tamilščina", "Malezija"),
  CountryLocalization("ml", "francoščina", "Mali"),
  CountryLocalization("mt", "angleščina", "Malta"),
  CountryLocalization("mh", "angleščina", "Marshallovi otoki"),
  CountryLocalization("mq", "francoščina", "Martinik"),
  CountryLocalization("mr", "arabščina", "Mavretanija"),
  CountryLocalization("mu", "morisjenščina", "Mauritius"),
  CountryLocalization("yt", "francoščina", "Mayotte"),
  CountryLocalization("mx", "španščina", "Mehika"),
  CountryLocalization("fm", "angleščina", "Mikronezija"),
  CountryLocalization("md", "ruščina", "Moldavija"),
  CountryLocalization("mc", "francoščina", "Monako"),
  CountryLocalization("mn", "mongolščina", "Mongolija"),
  CountryLocalization("me", "srbščina", "Črna gora"),
  CountryLocalization("ms", "angleščina", "Montserrat"),
  CountryLocalization("ma", "tamašek (srednji atlas)", "Maroko"),
  CountryLocalization("mz", "makuva-meto", "Mozambik"),
  CountryLocalization("mm", "burmanščina", "Mjanmar (Burma)"),
  CountryLocalization("na", "angleščina", "Namibija"),
  CountryLocalization("nr", "angleščina", "Nauru"),
  CountryLocalization("np", "nepalščina", "Nepal"),
  CountryLocalization("nl", "angleščina", "Nizozemska"),
  CountryLocalization("nc", "francoščina", "Nova Kaledonija"),
  CountryLocalization("nz", "angleščina", "Nova Zelandija"),
  CountryLocalization("ni", "španščina", "Nikaragva"),
  CountryLocalization("ne", "havščina", "Niger"),
  CountryLocalization("ng", "havščina", "Nigerija"),
  CountryLocalization("nu", "angleščina", "Niue"),
  CountryLocalization("nf", "angleščina", "Norfolški otok"),
  CountryLocalization("kp", "korejščina", "Severna Koreja"),
  CountryLocalization("mp", "angleščina", "Severni Marianski otoki"),
  CountryLocalization("no", "severna samijščina", "Norveška"),
  CountryLocalization("om", "arabščina", "Oman"),
  CountryLocalization("pk", "angleščina", "Pakistan"),
  CountryLocalization("pw", "angleščina", "Palau"),
  CountryLocalization("ps", "arabščina", "Palestinsko ozemlje"),
  CountryLocalization("pa", "španščina", "Panama"),
  CountryLocalization("pg", "angleščina", "Papua Nova Gvineja"),
  CountryLocalization("py", "španščina", "Paragvaj"),
  CountryLocalization("pe", "španščina", "Peru"),
  CountryLocalization("ph", "filipinščina", "Filipini"),
  CountryLocalization("pn", "angleščina", "Pitcairn"),
  CountryLocalization("pl", "poljščina", "Poljska"),
  CountryLocalization("pt", "portugalščina", "Portugalska"),
  CountryLocalization("pr", "angleščina", "Portoriko"),
  CountryLocalization("qa", "arabščina", "Katar"),
  CountryLocalization("ro", "romunščina", "Romunija"),
  CountryLocalization("ru", "tatarščina", "Rusija"),
  CountryLocalization("rw", "angleščina", "Ruanda"),
  CountryLocalization("re", "francoščina", "Reunion"),
  CountryLocalization("ws", "angleščina", "Samoa"),
  CountryLocalization("sm", "italijanščina", "San Marino"),
  CountryLocalization("sa", "arabščina", "Saudova Arabija"),
  CountryLocalization("sn", "francoščina", "Senegal"),
  CountryLocalization("rs", "srbščina", "Srbija"),
  CountryLocalization("cs", "srbščina", "Serbia and Montenegro"),
  CountryLocalization("sc", "francoščina", "Sejšeli"),
  CountryLocalization("sl", "angleščina", "Sierra Leone"),
  CountryLocalization("sg", "tamilščina", "Singapur"),
  CountryLocalization("sx", "angleščina", "Sint Maarten"),
  CountryLocalization("sk", "slovaščina", "Slovaška"),
  CountryLocalization("si", "slovenščina", "Slovenija"),
  CountryLocalization("sb", "angleščina", "Salomonovi otoki"),
  CountryLocalization("so", "arabščina", "Somalija"),
  CountryLocalization("za", "angleščina", "Južnoafriška republika"),
  CountryLocalization("kr", "korejščina", "Južna Koreja"),
  CountryLocalization("ss", "nuerščina", "Južni Sudan"),
  CountryLocalization("es", "španščina", "Španija"),
  CountryLocalization("lk", "tamilščina", "Šrilanka"),
  CountryLocalization("bl", "francoščina", "Saint Barthélemy"),
  CountryLocalization("sh", "angleščina", "Sveta Helena"),
  CountryLocalization("kn", "angleščina", "Saint Kitts in Nevis"),
  CountryLocalization("lc", "angleščina", "Saint Lucia"),
  CountryLocalization("mf", "francoščina", "Saint Martin"),
  CountryLocalization("pm", "francoščina", "Saint Pierre in Miquelon"),
  CountryLocalization("vc", "angleščina", "Saint Vincent in Grenadine"),
  CountryLocalization("sd", "arabščina", "Sudan"),
  CountryLocalization("sr", "nizozemščina", "Surinam"),
  CountryLocalization("sj", "knjižna norveščina", "Svalbard in Jan Mayen"),
  CountryLocalization("sz", "angleščina", "Svazi"),
  CountryLocalization("se", "švedščina", "Švedska"),
  CountryLocalization("ch", "nemščina (Švica)", "Švica"),
  CountryLocalization("sy", "arabščina", "Sirija"),
  CountryLocalization("st", "portugalščina", "Sao Tome in Principe"),
  CountryLocalization("tw", "kitajščina", "Tajvan"),
  CountryLocalization("tj", "tadžiščina", "Tadžikistan"),
  CountryLocalization("tz", "makondščina", "Tanzanija"),
  CountryLocalization("th", "tajščina", "Tajska"),
  CountryLocalization("tl", "portugalščina", "Timor-Leste"),
  CountryLocalization("tg", "francoščina", "Togo"),
  CountryLocalization("tk", "angleščina", "Tokelau"),
  CountryLocalization("to", "tongščina", "Tonga"),
  CountryLocalization("tt", "angleščina", "Trinidad in Tobago"),
  CountryLocalization("tn", "francoščina", "Tunizija"),
  CountryLocalization("tr", "turščina", "Turčija"),
  CountryLocalization("tm", "turkmenščina", "Turkmenistan"),
  CountryLocalization("tc", "angleščina", "Otoki Turks in Caicos"),
  CountryLocalization("tv", "angleščina", "Tuvalu"),
  CountryLocalization("um", "angleščina", "Stranski zunanji otoki Združenih držav"),
  CountryLocalization("vi", "angleščina", "Ameriški Deviški otoki"),
  CountryLocalization("ug", "svahili", "Uganda"),
  CountryLocalization("ua", "ukrajinščina", "Ukrajina"),
  CountryLocalization("ae", "arabščina", "Združeni arabski emirati"),
  CountryLocalization("gb", "angleščina", "Združeno kraljestvo"),
  CountryLocalization("us", "lakotščina", "Združene države Amerike"),
  CountryLocalization("uy", "španščina", "Urugvaj"),
  CountryLocalization("uz", "uzbeščina", "Uzbekistan"),
  CountryLocalization("vu", "francoščina", "Vanuatu"),
  CountryLocalization("va", "italijanščina", "Vatikan"),
  CountryLocalization("ve", "španščina", "Venezuela"),
  CountryLocalization("vn", "vietnamščina", "Vietnam"),
  CountryLocalization("wf", "francoščina", "Wallis in Futuna"),
  CountryLocalization("eh", "arabščina", "Zahodna Sahara"),
  CountryLocalization("ye", "arabščina", "Jemen"),
  CountryLocalization("zm", "angleščina", "Zambija"),
  CountryLocalization("zw", "severna ndebelščina", "Zimbabve"),
  CountryLocalization("ax", "švedščina", "Ålandski otoki"),
)
