/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot.atlas.extended

import dev.teogor.xenoglot.atlas.CountryLocalization
import kotlin.collections.List

/**
 * Holds the internal list of country-language mappings used for lookups within the package for
 * language code zh.
 *
 * This property contains a hardcoded list of [CountryLocalization] objects, each representing
 * a country and its associated official languages. This list is used by [CountryLanguageRegistry]
 * to provide access to country-language data and should not be modified directly.
 *
 * @see CountryLocalization
 * @see CountryLanguageRegistry
 */
internal val _countryLanguageMappings_zh: List<CountryLocalization> = listOf(
  CountryLocalization("af", "波斯文", "阿富汗"),
  CountryLocalization("al", "阿爾巴尼亞文", "阿爾巴尼亞"),
  CountryLocalization("dz", "法文", "阿爾及利亞"),
  CountryLocalization("as", "英文", "美屬薩摩亞"),
  CountryLocalization("ad", "加泰隆尼亞文", "安道爾"),
  CountryLocalization("ao", "林加拉文", "安哥拉"),
  CountryLocalization("ai", "英文", "安奎拉"),
  CountryLocalization("ag", "英文", "安提瓜和巴布達"),
  CountryLocalization("ar", "西班牙文", "阿根廷"),
  CountryLocalization("am", "亞美尼亞文", "亞美尼亞"),
  CountryLocalization("aw", "荷蘭文", "阿魯巴"),
  CountryLocalization("au", "英文", "澳洲"),
  CountryLocalization("at", "英文", "奧地利"),
  CountryLocalization("az", "阿塞拜疆文", "阿塞拜疆"),
  CountryLocalization("bs", "英文", "巴哈馬"),
  CountryLocalization("bh", "阿拉伯文", "巴林"),
  CountryLocalization("bd", "孟加拉文", "孟加拉"),
  CountryLocalization("bb", "英文", "巴巴多斯"),
  CountryLocalization("by", "白俄羅斯文", "白俄羅斯"),
  CountryLocalization("be", "法文", "比利時"),
  CountryLocalization("bz", "英文", "伯利茲"),
  CountryLocalization("bj", "法文", "貝寧"),
  CountryLocalization("bm", "英文", "百慕達"),
  CountryLocalization("bt", "宗卡文", "不丹"),
  CountryLocalization("bo", "西班牙文", "玻利維亞"),
  CountryLocalization("ba", "波斯尼亞文", "波斯尼亞和黑塞哥維那"),
  CountryLocalization("bw", "英文", "博茨瓦納"),
  CountryLocalization("br", "葡萄牙文", "巴西"),
  CountryLocalization("io", "英文", "英屬印度洋領地"),
  CountryLocalization("vg", "英文", "英屬維爾京群島"),
  CountryLocalization("bn", "馬來文", "汶萊"),
  CountryLocalization("bg", "保加利亞文", "保加利亞"),
  CountryLocalization("bf", "法文", "布基納法索"),
  CountryLocalization("bi", "法文", "布隆迪"),
  CountryLocalization("kh", "高棉文", "柬埔寨"),
  CountryLocalization("cm", "巴薩文", "喀麥隆"),
  CountryLocalization("ca", "法文", "加拿大"),
  CountryLocalization("ic", "西班牙文", "加那利群島"),
  CountryLocalization("cv", "卡布威爾第文", "佛得角"),
  CountryLocalization("bq", "荷蘭文", "荷蘭加勒比區"),
  CountryLocalization("ky", "英文", "開曼群島"),
  CountryLocalization("cf", "林加拉文", "中非共和國"),
  CountryLocalization("ea", "西班牙文", "休達與梅利利亞"),
  CountryLocalization("td", "阿拉伯文", "乍得"),
  CountryLocalization("cl", "西班牙文", "智利"),
  CountryLocalization("cn", "藏文", "中國"),
  CountryLocalization("cx", "英文", "聖誕島"),
  CountryLocalization("cc", "英文", "可可斯群島"),
  CountryLocalization("co", "西班牙文", "哥倫比亞"),
  CountryLocalization("km", "阿拉伯文", "科摩羅"),
  CountryLocalization("cg", "林加拉文", "剛果（布拉薩）"),
  CountryLocalization("cd", "史瓦希里文", "剛果（金夏沙）"),
  CountryLocalization("ck", "英文", "庫克群島"),
  CountryLocalization("cr", "西班牙文", "哥斯達黎加"),
  CountryLocalization("hr", "克羅地亞文", "克羅地亞"),
  CountryLocalization("cu", "西班牙文", "古巴"),
  CountryLocalization("cw", "荷蘭文", "庫拉索"),
  CountryLocalization("cy", "英文", "塞浦路斯"),
  CountryLocalization("cz", "捷克文", "捷克"),
  CountryLocalization("ci", "法文", "科特迪瓦"),
  CountryLocalization("dk", "英文", "丹麥"),
  CountryLocalization("dg", "英文", "迪亞哥加西亞島"),
  CountryLocalization("dj", "法文", "吉布提"),
  CountryLocalization("dm", "英文", "多米尼克"),
  CountryLocalization("do", "西班牙文", "多明尼加共和國"),
  CountryLocalization("ec", "蓋楚瓦文", "厄瓜多爾"),
  CountryLocalization("eg", "阿拉伯文", "埃及"),
  CountryLocalization("sv", "西班牙文", "薩爾瓦多"),
  CountryLocalization("gq", "西班牙文", "赤道幾內亞"),
  CountryLocalization("er", "提格利尼亞文", "厄立特里亞"),
  CountryLocalization("ee", "愛沙尼亞文", "愛沙尼亞"),
  CountryLocalization("et", "阿姆哈拉文", "埃塞俄比亞"),
  CountryLocalization("fk", "英文", "福克蘭群島"),
  CountryLocalization("fo", "法羅文", "法羅群島"),
  CountryLocalization("fj", "英文", "斐濟"),
  CountryLocalization("fi", "瑞典文", "芬蘭"),
  CountryLocalization("fr", "瑞士德文", "法國"),
  CountryLocalization("gf", "法文", "法屬圭亞那"),
  CountryLocalization("pf", "法文", "法屬波利尼西亞"),
  CountryLocalization("ga", "法文", "加蓬"),
  CountryLocalization("gm", "英文", "岡比亞"),
  CountryLocalization("ge", "奧塞提文", "格魯吉亞"),
  CountryLocalization("de", "下索布文", "德國"),
  CountryLocalization("gh", "英文", "加納"),
  CountryLocalization("gi", "英文", "直布羅陀"),
  CountryLocalization("gr", "希臘文", "希臘"),
  CountryLocalization("gl", "格陵蘭文", "格陵蘭"),
  CountryLocalization("gd", "英文", "格林納達"),
  CountryLocalization("gp", "法文", "瓜地洛普"),
  CountryLocalization("gu", "英文", "關島"),
  CountryLocalization("gt", "西班牙文", "危地馬拉"),
  CountryLocalization("gg", "英文", "根息"),
  CountryLocalization("gn", "法文", "幾內亞"),
  CountryLocalization("gw", "葡萄牙文", "幾內亞比紹"),
  CountryLocalization("gy", "英文", "圭亞那"),
  CountryLocalization("ht", "法文", "海地"),
  CountryLocalization("hn", "西班牙文", "洪都拉斯"),
  CountryLocalization("hk", "中文", "中國香港特別行政區"),
  CountryLocalization("hu", "匈牙利文", "匈牙利"),
  CountryLocalization("is", "冰島文", "冰島"),
  CountryLocalization("in", "尼泊爾文", "印度"),
  CountryLocalization("id", "印尼文", "印尼"),
  CountryLocalization("ir", "波斯文", "伊朗"),
  CountryLocalization("iq", "北盧爾文", "伊拉克"),
  CountryLocalization("ie", "英文", "愛爾蘭"),
  CountryLocalization("im", "曼島文", "馬恩島"),
  CountryLocalization("il", "英文", "以色列"),
  CountryLocalization("it", "德文", "意大利"),
  CountryLocalization("jm", "英文", "牙買加"),
  CountryLocalization("jp", "日文", "日本"),
  CountryLocalization("je", "英文", "澤西島"),
  CountryLocalization("jo", "阿拉伯文", "約旦"),
  CountryLocalization("kz", "哈薩克文", "哈薩克"),
  CountryLocalization("ke", "索馬里文", "肯雅"),
  CountryLocalization("ki", "英文", "吉里巴斯"),
  CountryLocalization("xk", "塞爾維亞文", "科索沃"),
  CountryLocalization("kw", "阿拉伯文", "科威特"),
  CountryLocalization("kg", "俄文", "吉爾吉斯"),
  CountryLocalization("la", "老撾文", "老撾"),
  CountryLocalization("lv", "拉脫維亞文", "拉脱維亞"),
  CountryLocalization("lb", "阿拉伯文", "黎巴嫩"),
  CountryLocalization("ls", "英文", "賴索托"),
  CountryLocalization("lr", "英文", "利比里亞"),
  CountryLocalization("ly", "阿拉伯文", "利比亞"),
  CountryLocalization("li", "瑞士德文", "列支敦士登"),
  CountryLocalization("lt", "立陶宛文", "立陶宛"),
  CountryLocalization("lu", "盧森堡文", "盧森堡"),
  CountryLocalization("mo", "葡萄牙文", "中國澳門特別行政區"),
  CountryLocalization("mk", "阿爾巴尼亞文", "馬其頓"),
  CountryLocalization("mg", "法文", "馬達加斯加"),
  CountryLocalization("mw", "英文", "馬拉維"),
  CountryLocalization("my", "泰米爾文", "馬來西亞"),
  CountryLocalization("ml", "法文", "馬里"),
  CountryLocalization("mt", "英文", "馬耳他"),
  CountryLocalization("mh", "英文", "馬紹爾群島"),
  CountryLocalization("mq", "法文", "馬丁尼克"),
  CountryLocalization("mr", "阿拉伯文", "毛里塔尼亞"),
  CountryLocalization("mu", "毛里裘斯克里奧爾文", "毛里裘斯"),
  CountryLocalization("yt", "法文", "馬約特"),
  CountryLocalization("mx", "西班牙文", "墨西哥"),
  CountryLocalization("fm", "英文", "密克羅尼西亞"),
  CountryLocalization("md", "俄文", "摩爾多瓦"),
  CountryLocalization("mc", "法文", "摩納哥"),
  CountryLocalization("mn", "蒙古文", "蒙古"),
  CountryLocalization("me", "塞爾維亞文", "黑山"),
  CountryLocalization("ms", "英文", "蒙特塞拉特"),
  CountryLocalization("ma", "中阿特拉斯塔馬塞特文", "摩洛哥"),
  CountryLocalization("mz", "馬夸文", "莫桑比克"),
  CountryLocalization("mm", "緬甸文", "緬甸"),
  CountryLocalization("na", "英文", "納米比亞"),
  CountryLocalization("nr", "英文", "瑙魯"),
  CountryLocalization("np", "尼泊爾文", "尼泊爾"),
  CountryLocalization("nl", "英文", "荷蘭"),
  CountryLocalization("nc", "法文", "新喀里多尼亞"),
  CountryLocalization("nz", "英文", "紐西蘭"),
  CountryLocalization("ni", "西班牙文", "尼加拉瓜"),
  CountryLocalization("ne", "豪撒文", "尼日爾"),
  CountryLocalization("ng", "豪撒文", "尼日利亞"),
  CountryLocalization("nu", "英文", "紐埃島"),
  CountryLocalization("nf", "英文", "諾福克島"),
  CountryLocalization("kp", "韓文", "北韓"),
  CountryLocalization("mp", "英文", "北馬利安納群島"),
  CountryLocalization("no", "北薩米文", "挪威"),
  CountryLocalization("om", "阿拉伯文", "阿曼"),
  CountryLocalization("pk", "英文", "巴基斯坦"),
  CountryLocalization("pw", "英文", "帛琉"),
  CountryLocalization("ps", "阿拉伯文", "巴勒斯坦領土"),
  CountryLocalization("pa", "西班牙文", "巴拿馬"),
  CountryLocalization("pg", "英文", "巴布亞新幾內亞"),
  CountryLocalization("py", "西班牙文", "巴拉圭"),
  CountryLocalization("pe", "西班牙文", "秘魯"),
  CountryLocalization("ph", "菲律賓文", "菲律賓"),
  CountryLocalization("pn", "英文", "皮特凱恩島"),
  CountryLocalization("pl", "波蘭文", "波蘭"),
  CountryLocalization("pt", "葡萄牙文", "葡萄牙"),
  CountryLocalization("pr", "英文", "波多黎各"),
  CountryLocalization("qa", "阿拉伯文", "卡塔爾"),
  CountryLocalization("ro", "羅馬尼亞文", "羅馬尼亞"),
  CountryLocalization("ru", "韃靼文", "俄羅斯"),
  CountryLocalization("rw", "英文", "盧旺達"),
  CountryLocalization("re", "法文", "留尼旺"),
  CountryLocalization("ws", "英文", "薩摩亞"),
  CountryLocalization("sm", "意大利文", "聖馬利諾"),
  CountryLocalization("sa", "阿拉伯文", "沙地阿拉伯"),
  CountryLocalization("sn", "法文", "塞內加爾"),
  CountryLocalization("rs", "塞爾維亞文", "塞爾維亞"),
  CountryLocalization("cs", "塞爾維亞文", "塞爾維亞及蒙特尼哥羅"),
  CountryLocalization("sc", "法文", "塞舌爾"),
  CountryLocalization("sl", "英文", "塞拉利昂"),
  CountryLocalization("sg", "泰米爾文", "新加坡"),
  CountryLocalization("sx", "英文", "荷屬聖馬丁"),
  CountryLocalization("sk", "斯洛伐克文", "斯洛伐克"),
  CountryLocalization("si", "斯洛文尼亞文", "斯洛文尼亞"),
  CountryLocalization("sb", "英文", "所羅門群島"),
  CountryLocalization("so", "阿拉伯文", "索馬里"),
  CountryLocalization("za", "英文", "南非"),
  CountryLocalization("kr", "韓文", "南韓"),
  CountryLocalization("ss", "努埃爾文", "南蘇丹"),
  CountryLocalization("es", "西班牙文", "西班牙"),
  CountryLocalization("lk", "泰米爾文", "斯里蘭卡"),
  CountryLocalization("bl", "法文", "聖巴泰勒米"),
  CountryLocalization("sh", "英文", "聖赫勒拿島"),
  CountryLocalization("kn", "英文", "聖基茨和尼維斯"),
  CountryLocalization("lc", "英文", "聖盧西亞"),
  CountryLocalization("mf", "法文", "法屬聖馬丁"),
  CountryLocalization("pm", "法文", "聖皮埃與密克隆群島"),
  CountryLocalization("vc", "英文", "聖文森特和格林納丁斯"),
  CountryLocalization("sd", "阿拉伯文", "蘇丹"),
  CountryLocalization("sr", "荷蘭文", "蘇里南"),
  CountryLocalization("sj", "巴克摩挪威文", "斯瓦爾巴特群島及揚馬延島"),
  CountryLocalization("sz", "英文", "斯威士蘭"),
  CountryLocalization("se", "瑞典文", "瑞典"),
  CountryLocalization("ch", "瑞士德文", "瑞士"),
  CountryLocalization("sy", "阿拉伯文", "敘利亞"),
  CountryLocalization("st", "葡萄牙文", "聖多美和普林西比"),
  CountryLocalization("tw", "中文", "台灣"),
  CountryLocalization("tj", "塔吉克文", "塔吉克"),
  CountryLocalization("tz", "馬孔德文", "坦桑尼亞"),
  CountryLocalization("th", "泰文", "泰國"),
  CountryLocalization("tl", "葡萄牙文", "東帝汶"),
  CountryLocalization("tg", "法文", "多哥共和國"),
  CountryLocalization("tk", "英文", "托克勞群島"),
  CountryLocalization("to", "湯加文", "湯加"),
  CountryLocalization("tt", "英文", "千里達和多巴哥"),
  CountryLocalization("tn", "法文", "突尼西亞"),
  CountryLocalization("tr", "土耳其文", "土耳其"),
  CountryLocalization("tm", "土庫曼文", "土庫曼"),
  CountryLocalization("tc", "英文", "特克斯和凱科斯群島"),
  CountryLocalization("tv", "英文", "圖瓦盧"),
  CountryLocalization("um", "英文", "美國本土外小島嶼"),
  CountryLocalization("vi", "英文", "美屬維爾京群島"),
  CountryLocalization("ug", "史瓦希里文", "烏干達"),
  CountryLocalization("ua", "烏克蘭文", "烏克蘭"),
  CountryLocalization("ae", "阿拉伯文", "阿拉伯聯合酋長國"),
  CountryLocalization("gb", "英文", "英國"),
  CountryLocalization("us", "拉科塔文", "美國"),
  CountryLocalization("uy", "西班牙文", "烏拉圭"),
  CountryLocalization("uz", "烏茲別克文", "烏茲別克"),
  CountryLocalization("vu", "法文", "瓦努阿圖"),
  CountryLocalization("va", "意大利文", "梵蒂岡"),
  CountryLocalization("ve", "西班牙文", "委內瑞拉"),
  CountryLocalization("vn", "越南文", "越南"),
  CountryLocalization("wf", "法文", "瓦利斯群島和富圖那群島"),
  CountryLocalization("eh", "阿拉伯文", "西撒哈拉"),
  CountryLocalization("ye", "阿拉伯文", "也門"),
  CountryLocalization("zm", "英文", "贊比亞"),
  CountryLocalization("zw", "北地畢列文", "津巴布韋"),
  CountryLocalization("ax", "瑞典文", "奧蘭群島"),
)
