/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot.atlas.extended

import dev.teogor.xenoglot.atlas.CountryLocalization
import kotlin.collections.List

/**
 * Holds the internal list of country-language mappings used for lookups within the package for
 * language code se.
 *
 * This property contains a hardcoded list of [CountryLocalization] objects, each representing
 * a country and its associated official languages. This list is used by [CountryLanguageRegistry]
 * to provide access to country-language data and should not be modified directly.
 *
 * @see CountryLocalization
 * @see CountryLanguageRegistry
 */
internal val _countryLanguageMappings_se: List<CountryLocalization> = listOf(
  CountryLocalization("af", "persijagiella", "Afghanistan"),
  CountryLocalization("al", "albánagiella", "Albánia"),
  CountryLocalization("dz", "fránskkagiella", "Algeria"),
  CountryLocalization("as", "eaŋgalsgiella", "Amerihká Samoa"),
  CountryLocalization("ad", "katalánagiella", "Andorra"),
  CountryLocalization("ao", "Lingala", "Angola"),
  CountryLocalization("ai", "eaŋgalsgiella", "Anguilla"),
  CountryLocalization("ag", "eaŋgalsgiella", "Antigua ja Barbuda"),
  CountryLocalization("ar", "spánskkagiella", "Argentina"),
  CountryLocalization("am", "armeenagiella", "Armenia"),
  CountryLocalization("aw", "hollánddagiella", "Aruba"),
  CountryLocalization("au", "eaŋgalsgiella", "Austrália"),
  CountryLocalization("at", "eaŋgalsgiella", "Nuortariika"),
  CountryLocalization("az", "Azerbaijani", "Aserbaižan"),
  CountryLocalization("bs", "eaŋgalsgiella", "Bahamas"),
  CountryLocalization("bh", "arábagiella", "Bahrain"),
  CountryLocalization("bd", "bengalgiella", "Bangladesh"),
  CountryLocalization("bb", "eaŋgalsgiella", "Barbados"),
  CountryLocalization("by", "vilges-ruoššagiella", "Vilges-Ruošša"),
  CountryLocalization("be", "fránskkagiella", "Belgia"),
  CountryLocalization("bz", "eaŋgalsgiella", "Belize"),
  CountryLocalization("bj", "fránskkagiella", "Benin"),
  CountryLocalization("bm", "eaŋgalsgiella", "Bermuda"),
  CountryLocalization("bt", "dzongkhagiella", "Bhutan"),
  CountryLocalization("bo", "spánskkagiella", "Bolivia"),
  CountryLocalization("ba", "bosniagiella", "Bosnia-Hercegovina"),
  CountryLocalization("bw", "eaŋgalsgiella", "Botswana"),
  CountryLocalization("br", "portugálagiella", "Brasil"),
  CountryLocalization("io", "eaŋgalsgiella", "British Indian Ocean Territory"),
  CountryLocalization("vg", "eaŋgalsgiella", "Brittania Virgin-sullot"),
  CountryLocalization("bn", "Malay", "Brunei"),
  CountryLocalization("bg", "bulgáriagiella", "Bulgária"),
  CountryLocalization("bf", "fránskkagiella", "Burkina Faso"),
  CountryLocalization("bi", "fránskkagiella", "Burundi"),
  CountryLocalization("kh", "kambodiagiella", "Kambodža"),
  CountryLocalization("cm", "Basaa", "Kamerun"),
  CountryLocalization("ca", "fránskkagiella", "Kanáda"),
  CountryLocalization("ic", "spánskkagiella", "Kanáriasullot"),
  CountryLocalization("cv", "kea", "Kap Verde"),
  CountryLocalization("bq", "hollánddagiella", "Caribbean Netherlands"),
  CountryLocalization("ky", "eaŋgalsgiella", "Cayman-sullot"),
  CountryLocalization("cf", "Lingala", "Gaska-Afrihká dásseváldi"),
  CountryLocalization("ea", "spánskkagiella", "Ceuta ja Melilla"),
  CountryLocalization("td", "arábagiella", "Tčad"),
  CountryLocalization("cl", "spánskkagiella", "Čiile"),
  CountryLocalization("cn", "tibetagiella", "Kiinná"),
  CountryLocalization("cx", "eaŋgalsgiella", "Juovllat-sullot"),
  CountryLocalization("cc", "eaŋgalsgiella", "Cocos-sullot"),
  CountryLocalization("co", "spánskkagiella", "Kolombia"),
  CountryLocalization("km", "arábagiella", "Komoros"),
  CountryLocalization("cg", "Lingala", "Kongo-Brazzaville"),
  CountryLocalization("cd", "Swahili", "Kongo-Kinshasa"),
  CountryLocalization("ck", "eaŋgalsgiella", "Cook-sullot"),
  CountryLocalization("cr", "spánskkagiella", "Costa Rica"),
  CountryLocalization("hr", "kroátiagiella", "Kroátia"),
  CountryLocalization("cu", "spánskkagiella", "Kuba"),
  CountryLocalization("cw", "hollánddagiella", "Curaçao"),
  CountryLocalization("cy", "eaŋgalsgiella", "Kypros"),
  CountryLocalization("cz", "čeahkagiella", "Čeahkka"),
  CountryLocalization("ci", "fránskkagiella", "Elfenbenariddu"),
  CountryLocalization("dk", "eaŋgalsgiella", "Dánmárku"),
  CountryLocalization("dg", "eaŋgalsgiella", "Diego Garcia"),
  CountryLocalization("dj", "fránskkagiella", "Djibouti"),
  CountryLocalization("dm", "eaŋgalsgiella", "Dominica"),
  CountryLocalization("do", "spánskkagiella", "Dominikána dásseváldi"),
  CountryLocalization("ec", "Quechua", "Ecuador"),
  CountryLocalization("eg", "arábagiella", "Egypta"),
  CountryLocalization("sv", "spánskkagiella", "El Salvador"),
  CountryLocalization("gq", "spánskkagiella", "Ekvatoriála Guinea"),
  CountryLocalization("er", "Tigrinya", "Eritrea"),
  CountryLocalization("ee", "esttegiella", "Estlánda"),
  CountryLocalization("et", "Amharic", "Etiopia"),
  CountryLocalization("fk", "eaŋgalsgiella", "Falklandsullot"),
  CountryLocalization("fo", "fearagiella", "Fearsullot"),
  CountryLocalization("fj", "eaŋgalsgiella", "Fijisullot"),
  CountryLocalization("fi", "ruoŧagiella", "Suopma"),
  CountryLocalization("fr", "Swiss German", "Frankriika"),
  CountryLocalization("gf", "fránskkagiella", "Frankriikka Guayana"),
  CountryLocalization("pf", "fránskkagiella", "Frankriikka Polynesia"),
  CountryLocalization("ga", "fránskkagiella", "Gabon"),
  CountryLocalization("gm", "eaŋgalsgiella", "Gámbia"),
  CountryLocalization("ge", "Ossetic", "Georgia"),
  CountryLocalization("de", "Lower Sorbian", "Duiska"),
  CountryLocalization("gh", "eaŋgalsgiella", "Ghana"),
  CountryLocalization("gi", "eaŋgalsgiella", "Gibraltar"),
  CountryLocalization("gr", "greikkagiella", "Greika"),
  CountryLocalization("gl", "Kalaallisut", "Kalaallit Nunaat"),
  CountryLocalization("gd", "eaŋgalsgiella", "Grenada"),
  CountryLocalization("gp", "fránskkagiella", "Guadeloupe"),
  CountryLocalization("gu", "eaŋgalsgiella", "Guam"),
  CountryLocalization("gt", "spánskkagiella", "Guatemala"),
  CountryLocalization("gg", "eaŋgalsgiella", "Guernsey"),
  CountryLocalization("gn", "fránskkagiella", "Guinea"),
  CountryLocalization("gw", "portugálagiella", "Guinea-Bissau"),
  CountryLocalization("gy", "eaŋgalsgiella", "Guyana"),
  CountryLocalization("ht", "fránskkagiella", "Haiti"),
  CountryLocalization("hn", "spánskkagiella", "Honduras"),
  CountryLocalization("hk", "kiinnágiella", "Hongkong"),
  CountryLocalization("hu", "ungárgiella", "Ungár"),
  CountryLocalization("is", "islánddagiella", "Islánda"),
  CountryLocalization("in", "nepaligiella", "India"),
  CountryLocalization("id", "Indonesian", "Indonesia"),
  CountryLocalization("ir", "persijagiella", "Iran"),
  CountryLocalization("iq", "lrc", "Irak"),
  CountryLocalization("ie", "eaŋgalsgiella", "Irlánda"),
  CountryLocalization("im", "manksgiella", "Mann-sullot"),
  CountryLocalization("il", "eaŋgalsgiella", "Israel"),
  CountryLocalization("it", "duiskkagiella", "Itália"),
  CountryLocalization("jm", "eaŋgalsgiella", "Jamaica"),
  CountryLocalization("jp", "japánagiella", "Japána"),
  CountryLocalization("je", "eaŋgalsgiella", "Jersey"),
  CountryLocalization("jo", "arábagiella", "Jordánia"),
  CountryLocalization("kz", "kazakgiella", "Kasakstan"),
  CountryLocalization("ke", "Somali", "Kenia"),
  CountryLocalization("ki", "eaŋgalsgiella", "Kiribati"),
  CountryLocalization("xk", "serbiagiella", "Kosovo"),
  CountryLocalization("kw", "arábagiella", "Kuwait"),
  CountryLocalization("kg", "ruoššagiella", "Kirgisistan"),
  CountryLocalization("la", "laogiella", "Laos"),
  CountryLocalization("lv", "látviagiella", "Látvia"),
  CountryLocalization("lb", "arábagiella", "Libanon"),
  CountryLocalization("ls", "eaŋgalsgiella", "Lesotho"),
  CountryLocalization("lr", "eaŋgalsgiella", "Liberia"),
  CountryLocalization("ly", "arábagiella", "Libya"),
  CountryLocalization("li", "Swiss German", "Liechtenstein"),
  CountryLocalization("lt", "liettuvagiella", "Lietuva"),
  CountryLocalization("lu", "luxemburggagiella", "Luxembourg"),
  CountryLocalization("mo", "portugálagiella", "Makáo"),
  CountryLocalization("mk", "albánagiella", "Makedonia"),
  CountryLocalization("mg", "fránskkagiella", "Madagaskar"),
  CountryLocalization("mw", "eaŋgalsgiella", "Malawi"),
  CountryLocalization("my", "Tamil", "Malesia"),
  CountryLocalization("ml", "fránskkagiella", "Mali"),
  CountryLocalization("mt", "eaŋgalsgiella", "Málta"),
  CountryLocalization("mh", "eaŋgalsgiella", "Marshallsullot"),
  CountryLocalization("mq", "fránskkagiella", "Martinique"),
  CountryLocalization("mr", "arábagiella", "Mauretánia"),
  CountryLocalization("mu", "mfe", "Mauritius"),
  CountryLocalization("yt", "fránskkagiella", "Mayotte"),
  CountryLocalization("mx", "spánskkagiella", "Meksiko"),
  CountryLocalization("fm", "eaŋgalsgiella", "Mikronesia"),
  CountryLocalization("md", "ruoššagiella", "Moldávia"),
  CountryLocalization("mc", "fránskkagiella", "Monaco"),
  CountryLocalization("mn", "mongoliagiella", "Mongolia"),
  CountryLocalization("me", "serbiagiella", "Montenegro"),
  CountryLocalization("ms", "eaŋgalsgiella", "Montserrat"),
  CountryLocalization("ma", "tzm", "Marokko"),
  CountryLocalization("mz", "mgh", "Mosambik"),
  CountryLocalization("mm", "burmagiella", "Burma"),
  CountryLocalization("na", "eaŋgalsgiella", "Namibia"),
  CountryLocalization("nr", "eaŋgalsgiella", "Nauru"),
  CountryLocalization("np", "nepaligiella", "Nepal"),
  CountryLocalization("nl", "eaŋgalsgiella", "Vuolleeatnamat"),
  CountryLocalization("nc", "fránskkagiella", "Ođđa-Kaledonia"),
  CountryLocalization("nz", "eaŋgalsgiella", "Ođđa-Selánda"),
  CountryLocalization("ni", "spánskkagiella", "Nicaragua"),
  CountryLocalization("ne", "haussagiella", "Niger"),
  CountryLocalization("ng", "haussagiella", "Nigeria"),
  CountryLocalization("nu", "eaŋgalsgiella", "Niue"),
  CountryLocalization("nf", "eaŋgalsgiella", "Norfolksullot"),
  CountryLocalization("kp", "koreagiella", "Davvi-Korea"),
  CountryLocalization("mp", "eaŋgalsgiella", "Davvi-Mariánat"),
  CountryLocalization("no", "davvisámegiella", "Norga"),
  CountryLocalization("om", "arábagiella", "Oman"),
  CountryLocalization("pk", "eaŋgalsgiella", "Pakistan"),
  CountryLocalization("pw", "eaŋgalsgiella", "Palau"),
  CountryLocalization("ps", "arábagiella", "Palestina"),
  CountryLocalization("pa", "spánskkagiella", "Panama"),
  CountryLocalization("pg", "eaŋgalsgiella", "Papua-Ođđa-Guinea"),
  CountryLocalization("py", "spánskkagiella", "Paraguay"),
  CountryLocalization("pe", "spánskkagiella", "Peru"),
  CountryLocalization("ph", "filippiinnagiella", "Filippiinnat"),
  CountryLocalization("pn", "eaŋgalsgiella", "Pitcairn"),
  CountryLocalization("pl", "polskkagiella", "Polen"),
  CountryLocalization("pt", "portugálagiella", "Portugála"),
  CountryLocalization("pr", "eaŋgalsgiella", "Puerto Rico"),
  CountryLocalization("qa", "arábagiella", "Qatar"),
  CountryLocalization("ro", "romániagiella", "Románia"),
  CountryLocalization("ru", "Tatar", "Ruošša"),
  CountryLocalization("rw", "eaŋgalsgiella", "Rwanda"),
  CountryLocalization("re", "fránskkagiella", "Réunion"),
  CountryLocalization("ws", "eaŋgalsgiella", "Samoa"),
  CountryLocalization("sm", "itáliagiella", "San Marino"),
  CountryLocalization("sa", "arábagiella", "Saudi-Arábia"),
  CountryLocalization("sn", "fránskkagiella", "Senegal"),
  CountryLocalization("rs", "serbiagiella", "Serbia"),
  CountryLocalization("cs", "serbiagiella", "Serbia and Montenegro"),
  CountryLocalization("sc", "fránskkagiella", "Seychellsullot"),
  CountryLocalization("sl", "eaŋgalsgiella", "Sierra Leone"),
  CountryLocalization("sg", "Tamil", "Singapore"),
  CountryLocalization("sx", "eaŋgalsgiella", "Vuolleeatnamat Saint Martin"),
  CountryLocalization("sk", "slovákiagiella", "Slovákia"),
  CountryLocalization("si", "slovenagiella", "Slovenia"),
  CountryLocalization("sb", "eaŋgalsgiella", "Salomon-sullot"),
  CountryLocalization("so", "arábagiella", "Somália"),
  CountryLocalization("za", "eaŋgalsgiella", "Mátta-Afrihká"),
  CountryLocalization("kr", "koreagiella", "Mátta-Korea"),
  CountryLocalization("ss", "nus", "Máttasudan"),
  CountryLocalization("es", "spánskkagiella", "Spánia"),
  CountryLocalization("lk", "Tamil", "Sri Lanka"),
  CountryLocalization("bl", "fránskkagiella", "Saint Barthélemy"),
  CountryLocalization("sh", "eaŋgalsgiella", "Saint Helena"),
  CountryLocalization("kn", "eaŋgalsgiella", "Saint Kitts ja Nevis"),
  CountryLocalization("lc", "eaŋgalsgiella", "Saint Lucia"),
  CountryLocalization("mf", "fránskkagiella", "Frankriikka Saint Martin"),
  CountryLocalization("pm", "fránskkagiella", "Saint Pierre ja Miquelon"),
  CountryLocalization("vc", "eaŋgalsgiella", "Saint Vincent ja Grenadine"),
  CountryLocalization("sd", "arábagiella", "Davvisudan"),
  CountryLocalization("sr", "hollánddagiella", "Surinam"),
  CountryLocalization("sj", "girjedárogiella", "Svalbárda ja Jan Mayen"),
  CountryLocalization("sz", "eaŋgalsgiella", "Svazieana"),
  CountryLocalization("se", "ruoŧagiella", "Ruoŧŧa"),
  CountryLocalization("ch", "Swiss German", "Šveica"),
  CountryLocalization("sy", "arábagiella", "Syria"),
  CountryLocalization("st", "portugálagiella", "São Tomé ja Príncipe"),
  CountryLocalization("tw", "kiinnágiella", "Taiwan"),
  CountryLocalization("tj", "Tajik", "Tažikistan"),
  CountryLocalization("tz", "kde", "Tanzánia"),
  CountryLocalization("th", "ŧaigiella", "Thaieana"),
  CountryLocalization("tl", "portugálagiella", "Nuorta-Timor"),
  CountryLocalization("tg", "fránskkagiella", "Togo"),
  CountryLocalization("tk", "eaŋgalsgiella", "Tokelau"),
  CountryLocalization("to", "Tongan", "Tonga"),
  CountryLocalization("tt", "eaŋgalsgiella", "Trinidad ja Tobago"),
  CountryLocalization("tn", "fránskkagiella", "Tunisia"),
  CountryLocalization("tr", "durkagiella", "Durka"),
  CountryLocalization("tm", "Turkmen", "Turkmenistan"),
  CountryLocalization("tc", "eaŋgalsgiella", "Turks ja Caicos-sullot"),
  CountryLocalization("tv", "eaŋgalsgiella", "Tuvalu"),
  CountryLocalization("um", "eaŋgalsgiella", "U.S. Outlying Islands"),
  CountryLocalization("vi", "eaŋgalsgiella", "AOS Virgin-sullot"),
  CountryLocalization("ug", "Swahili", "Uganda"),
  CountryLocalization("ua", "ukrainagiella", "Ukraina"),
  CountryLocalization("ae", "arábagiella", "Ovttastuvvan Arábaemiráhtat"),
  CountryLocalization("gb", "eaŋgalsgiella", "Stuorra-Británnia"),
  CountryLocalization("us", "lkt", "Amerihká ovttastuvvan stáhtat"),
  CountryLocalization("uy", "spánskkagiella", "Uruguay"),
  CountryLocalization("uz", "Uzbek", "Usbekistan"),
  CountryLocalization("vu", "fránskkagiella", "Vanuatu"),
  CountryLocalization("va", "itáliagiella", "Vatikána"),
  CountryLocalization("ve", "spánskkagiella", "Venezuela"),
  CountryLocalization("vn", "vietnamgiella", "Vietnam"),
  CountryLocalization("wf", "fránskkagiella", "Wallis ja Futuna"),
  CountryLocalization("eh", "arábagiella", "Oarje-Sahára"),
  CountryLocalization("ye", "arábagiella", "Jemen"),
  CountryLocalization("zm", "eaŋgalsgiella", "Zambia"),
  CountryLocalization("zw", "North Ndebele", "Zimbabwe"),
  CountryLocalization("ax", "ruoŧagiella", "Ålánda"),
)
