/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot.atlas.extended

import dev.teogor.xenoglot.atlas.CountryLocalization
import kotlin.collections.List

/**
 * Holds the internal list of country-language mappings used for lookups within the package for
 * language code az.
 *
 * This property contains a hardcoded list of [CountryLocalization] objects, each representing
 * a country and its associated official languages. This list is used by [CountryLanguageRegistry]
 * to provide access to country-language data and should not be modified directly.
 *
 * @see CountryLocalization
 * @see CountryLanguageRegistry
 */
internal val _countryLanguageMappings_az: List<CountryLocalization> = listOf(
  CountryLocalization("af", "фарс", "Әфганыстан"),
  CountryLocalization("al", "албан", "Албанија"),
  CountryLocalization("dz", "франсыз", "Әлҹәзаир"),
  CountryLocalization("as", "инҝилис", "Америка Самоасы"),
  CountryLocalization("ad", "каталан", "Андорра"),
  CountryLocalization("ao", "лингала", "Ангола"),
  CountryLocalization("ai", "инҝилис", "Анҝилја"),
  CountryLocalization("ag", "инҝилис", "Антигуа вә Барбуда"),
  CountryLocalization("ar", "испан", "Арҝентина"),
  CountryLocalization("am", "ермәни", "Ермәнистан"),
  CountryLocalization("aw", "һолланд", "Аруба"),
  CountryLocalization("au", "инҝилис", "Австралија"),
  CountryLocalization("at", "инҝилис", "Австрија"),
  CountryLocalization("az", "азәрбајҹан", "Азәрбајҹан"),
  CountryLocalization("bs", "инҝилис", "Баһам адалары"),
  CountryLocalization("bh", "әрәб", "Бәһрејн"),
  CountryLocalization("bd", "бенгал", "Бангладеш"),
  CountryLocalization("bb", "инҝилис", "Барбадос"),
  CountryLocalization("by", "беларус", "Беларус"),
  CountryLocalization("be", "франсыз", "Белчика"),
  CountryLocalization("bz", "инҝилис", "Белиз"),
  CountryLocalization("bj", "франсыз", "Бенин"),
  CountryLocalization("bm", "инҝилис", "Бермуд адалары"),
  CountryLocalization("bt", "дзонга", "Бутан"),
  CountryLocalization("bo", "испан", "Боливија"),
  CountryLocalization("ba", "босниак", "Боснија вә Һерсеговина"),
  CountryLocalization("bw", "инҝилис", "Ботсвана"),
  CountryLocalization("br", "португал", "Бразилија"),
  CountryLocalization("io", "инҝилис", "Британтјанын Һинд Океаны Әразиси"),
  CountryLocalization("vg", "инҝилис", "Британијанын Вирҝин адалары"),
  CountryLocalization("bn", "малај", "Брунеј"),
  CountryLocalization("bg", "булгар", "Болгарыстан"),
  CountryLocalization("bf", "франсыз", "Буркина Фасо"),
  CountryLocalization("bi", "франсыз", "Бурунди"),
  CountryLocalization("kh", "кхмер", "Камбоҹа"),
  CountryLocalization("cm", "баса", "Камерун"),
  CountryLocalization("ca", "франсыз", "Канада"),
  CountryLocalization("ic", "испан", "Канар адалары"),
  CountryLocalization("cv", "кабувердиан", "Кабо-Верде"),
  CountryLocalization("bq", "һолланд", "Caribbean Netherlands"),
  CountryLocalization("ky", "инҝилис", "Кајман адалары"),
  CountryLocalization("cf", "лингала", "Мәркәзи Африка Республикасы"),
  CountryLocalization("ea", "испан", "Сеута вә Мелилја"),
  CountryLocalization("td", "әрәб", "Чад"),
  CountryLocalization("cl", "испан", "Чили"),
  CountryLocalization("cn", "тибет", "Чин"),
  CountryLocalization("cx", "инҝилис", "Милад адасы"),
  CountryLocalization("cc", "инҝилис", "Кокос (Килинг) адалары"),
  CountryLocalization("co", "испан", "Колумбија"),
  CountryLocalization("km", "әрәб", "Комор адалары"),
  CountryLocalization("cg", "лингала", "Конго-Браззавил"),
  CountryLocalization("cd", "суаһили", "Конго-Киншаса"),
  CountryLocalization("ck", "инҝилис", "Кук адалары"),
  CountryLocalization("cr", "испан", "Коста Рика"),
  CountryLocalization("hr", "хорват", "Хорватија"),
  CountryLocalization("cu", "испан", "Куба"),
  CountryLocalization("cw", "һолланд", "Курасао"),
  CountryLocalization("cy", "инҝилис", "Кипр"),
  CountryLocalization("cz", "чех", "Чехија"),
  CountryLocalization("ci", "франсыз", "Kотд’ивуар"),
  CountryLocalization("dk", "инҝилис", "Данимарка"),
  CountryLocalization("dg", "инҝилис", "Диего Гарсија"),
  CountryLocalization("dj", "франсыз", "Ҹибути"),
  CountryLocalization("dm", "инҝилис", "Доминика"),
  CountryLocalization("do", "испан", "Доминикан Республикасы"),
  CountryLocalization("ec", "кечуа", "Еквадор"),
  CountryLocalization("eg", "әрәб", "Мисир"),
  CountryLocalization("sv", "испан", "Салвадор"),
  CountryLocalization("gq", "испан", "Екваториал Гвинеја"),
  CountryLocalization("er", "тигрин", "Еритреја"),
  CountryLocalization("ee", "естон", "Естонија"),
  CountryLocalization("et", "амһар", "Ефиопија"),
  CountryLocalization("fk", "инҝилис", "Фолкленд адалары"),
  CountryLocalization("fo", "фарер", "Фарер адалары"),
  CountryLocalization("fj", "инҝилис", "Фиҹи"),
  CountryLocalization("fi", "исвеч", "Финландија"),
  CountryLocalization("fr", "Исвечрә алманҹасы", "Франса"),
  CountryLocalization("gf", "франсыз", "Франса Гвианасы"),
  CountryLocalization("pf", "франсыз", "Франса Полинезијасы"),
  CountryLocalization("ga", "франсыз", "Габон"),
  CountryLocalization("gm", "инҝилис", "Гамбија"),
  CountryLocalization("ge", "осетин", "Ҝүрҹүстан"),
  CountryLocalization("de", "ашағы сорб", "Алманија"),
  CountryLocalization("gh", "инҝилис", "Гана"),
  CountryLocalization("gi", "инҝилис", "Ҹәбәллүтариг"),
  CountryLocalization("gr", "јунан", "Јунаныстан"),
  CountryLocalization("gl", "калааллисут", "Гренландија"),
  CountryLocalization("gd", "инҝилис", "Гренада"),
  CountryLocalization("gp", "франсыз", "Гваделупа"),
  CountryLocalization("gu", "инҝилис", "Гуам"),
  CountryLocalization("gt", "испан", "Гватемала"),
  CountryLocalization("gg", "инҝилис", "Ҝернси"),
  CountryLocalization("gn", "франсыз", "Гвинеја"),
  CountryLocalization("gw", "португал", "Гвинеја-Бисау"),
  CountryLocalization("gy", "инҝилис", "Гајана"),
  CountryLocalization("ht", "франсыз", "Һаити"),
  CountryLocalization("hn", "испан", "Һондурас"),
  CountryLocalization("hk", "чин", "Һонк Конг Хүсуси Инзибати Әрази Чин"),
  CountryLocalization("hu", "маҹар", "Маҹарыстан"),
  CountryLocalization("is", "исланд", "Исландија"),
  CountryLocalization("in", "непал", "Һиндистан"),
  CountryLocalization("id", "Indonesian", "Индонезија"),
  CountryLocalization("ir", "фарс", "Иран"),
  CountryLocalization("iq", "шимали лури", "Ираг"),
  CountryLocalization("ie", "инҝилис", "Ирландија"),
  CountryLocalization("im", "манкс", "Мен адасы"),
  CountryLocalization("il", "инҝилис", "Исраил"),
  CountryLocalization("it", "алман", "Италија"),
  CountryLocalization("jm", "инҝилис", "Јамајка"),
  CountryLocalization("jp", "јапон", "Јапонија"),
  CountryLocalization("je", "инҝилис", "Ҹерси"),
  CountryLocalization("jo", "әрәб", "Иорданија"),
  CountryLocalization("kz", "газах", "Газахыстан"),
  CountryLocalization("ke", "сомали", "Кенија"),
  CountryLocalization("ki", "инҝилис", "Кирибати"),
  CountryLocalization("xk", "серб", "Косово"),
  CountryLocalization("kw", "әрәб", "Күвејт"),
  CountryLocalization("kg", "рус", "Гырғызыстан"),
  CountryLocalization("la", "лаос", "Лаос"),
  CountryLocalization("lv", "латыш", "Латвија"),
  CountryLocalization("lb", "әрәб", "Ливан"),
  CountryLocalization("ls", "инҝилис", "Лесото"),
  CountryLocalization("lr", "инҝилис", "Либерија"),
  CountryLocalization("ly", "әрәб", "Ливија"),
  CountryLocalization("li", "Исвечрә алманҹасы", "Лихтенштејн"),
  CountryLocalization("lt", "литва", "Литва"),
  CountryLocalization("lu", "лүксембург", "Лүксембург"),
  CountryLocalization("mo", "португал", "Макао Хүсуси Инзибати Әрази Чин"),
  CountryLocalization("mk", "албан", "North Macedonia"),
  CountryLocalization("mg", "франсыз", "Мадагаскар"),
  CountryLocalization("mw", "инҝилис", "Малави"),
  CountryLocalization("my", "тамил", "Малајзија"),
  CountryLocalization("ml", "франсыз", "Мали"),
  CountryLocalization("mt", "инҝилис", "Малта"),
  CountryLocalization("mh", "инҝилис", "Маршал адалары"),
  CountryLocalization("mq", "франсыз", "Мартиник"),
  CountryLocalization("mr", "әрәб", "Мавританија"),
  CountryLocalization("mu", "морисиен", "Маврики"),
  CountryLocalization("yt", "франсыз", "Мајот"),
  CountryLocalization("mx", "испан", "Мексика"),
  CountryLocalization("fm", "инҝилис", "Микронезија"),
  CountryLocalization("md", "рус", "Молдова"),
  CountryLocalization("mc", "франсыз", "Монако"),
  CountryLocalization("mn", "монгол", "Монголустан"),
  CountryLocalization("me", "серб", "Монтенегро"),
  CountryLocalization("ms", "инҝилис", "Монсерат"),
  CountryLocalization("ma", "Мәркәзи Атлас тамазиҹәси", "Мәракеш"),
  CountryLocalization("mz", "махува-меетто", "Мозамбик"),
  CountryLocalization("mm", "бирман", "Мјанма"),
  CountryLocalization("na", "инҝилис", "Намибија"),
  CountryLocalization("nr", "инҝилис", "Науру"),
  CountryLocalization("np", "непал", "Непал"),
  CountryLocalization("nl", "инҝилис", "Нидерланд"),
  CountryLocalization("nc", "франсыз", "Јени Каледонија"),
  CountryLocalization("nz", "инҝилис", "Јени Зеландија"),
  CountryLocalization("ni", "испан", "Никарагуа"),
  CountryLocalization("ne", "һауса", "Ниҝер"),
  CountryLocalization("ng", "һауса", "Ниҝерија"),
  CountryLocalization("nu", "инҝилис", "Ниуе"),
  CountryLocalization("nf", "инҝилис", "Норфолк адасы"),
  CountryLocalization("kp", "кореја", "Шимали Кореја"),
  CountryLocalization("mp", "инҝилис", "Шимали Мариан адалары"),
  CountryLocalization("no", "шимали сами", "Норвеч"),
  CountryLocalization("om", "әрәб", "Оман"),
  CountryLocalization("pk", "инҝилис", "Пакистан"),
  CountryLocalization("pw", "инҝилис", "Палау"),
  CountryLocalization("ps", "әрәб", "Palestinian Territories"),
  CountryLocalization("pa", "испан", "Панама"),
  CountryLocalization("pg", "инҝилис", "Папуа-Јени Гвинеја"),
  CountryLocalization("py", "испан", "Парагвај"),
  CountryLocalization("pe", "испан", "Перу"),
  CountryLocalization("ph", "филиппин", "Филиппин"),
  CountryLocalization("pn", "инҝилис", "Питкерн адалары"),
  CountryLocalization("pl", "полјак", "Полша"),
  CountryLocalization("pt", "португал", "Португалија"),
  CountryLocalization("pr", "инҝилис", "Пуерто Рико"),
  CountryLocalization("qa", "әрәб", "Гәтәр"),
  CountryLocalization("ro", "румын", "Румынија"),
  CountryLocalization("ru", "татар", "Русија"),
  CountryLocalization("rw", "инҝилис", "Руанда"),
  CountryLocalization("re", "франсыз", "Рејунјон"),
  CountryLocalization("ws", "инҝилис", "Самоа"),
  CountryLocalization("sm", "италјан", "Сан-Марино"),
  CountryLocalization("sa", "әрәб", "Сәудијјә Әрәбистаны"),
  CountryLocalization("sn", "франсыз", "Сенегал"),
  CountryLocalization("rs", "серб", "Сербија"),
  CountryLocalization("cs", "серб", "Serbia and Montenegro"),
  CountryLocalization("sc", "франсыз", "Сејшел адалары"),
  CountryLocalization("sl", "инҝилис", "Сјерра-Леоне"),
  CountryLocalization("sg", "тамил", "Сингапур"),
  CountryLocalization("sx", "инҝилис", "Синт-Мартен"),
  CountryLocalization("sk", "словак", "Словакија"),
  CountryLocalization("si", "словен", "Словенија"),
  CountryLocalization("sb", "инҝилис", "Соломон адалары"),
  CountryLocalization("so", "әрәб", "Сомали"),
  CountryLocalization("za", "инҝилис", "Ҹәнуб Африка"),
  CountryLocalization("kr", "кореја", "Ҹәнуби Кореја"),
  CountryLocalization("ss", "нуер", "Ҹәнуби Судан"),
  CountryLocalization("es", "испан", "Испанија"),
  CountryLocalization("lk", "тамил", "Шри-Ланка"),
  CountryLocalization("bl", "франсыз", "Сент-Бартелеми"),
  CountryLocalization("sh", "инҝилис", "Мүгәддәс Јелена"),
  CountryLocalization("kn", "инҝилис", "Сент-Китс вә Невис"),
  CountryLocalization("lc", "инҝилис", "Сент-Лусија"),
  CountryLocalization("mf", "франсыз", "Сент Мартин"),
  CountryLocalization("pm", "франсыз", "Мүгәддәс Пјер вә Микелон"),
  CountryLocalization("vc", "инҝилис", "Сент-Винсент вә Гренадинләр"),
  CountryLocalization("sd", "әрәб", "Судан"),
  CountryLocalization("sr", "һолланд", "Суринам"),
  CountryLocalization("sj", "бокмал норвеч", "Свалбард вә Јан-Мајен"),
  CountryLocalization("sz", "инҝилис", "Свазиленд"),
  CountryLocalization("se", "исвеч", "Исвеч"),
  CountryLocalization("ch", "Исвечрә алманҹасы", "Исвечрә"),
  CountryLocalization("sy", "әрәб", "Сурија"),
  CountryLocalization("st", "португал", "Сан-Томе вә Принсипи"),
  CountryLocalization("tw", "чин", "Тајван"),
  CountryLocalization("tj", "таҹик", "Таҹикистан"),
  CountryLocalization("tz", "маконде", "Танзанија"),
  CountryLocalization("th", "тај", "Таиланд"),
  CountryLocalization("tl", "португал", "Шәрги Тимор"),
  CountryLocalization("tg", "франсыз", "Того"),
  CountryLocalization("tk", "инҝилис", "Токелау"),
  CountryLocalization("to", "тонган", "Тонга"),
  CountryLocalization("tt", "инҝилис", "Тринидад вә Тобаго"),
  CountryLocalization("tn", "франсыз", "Тунис"),
  CountryLocalization("tr", "түрк", "Түркијә"),
  CountryLocalization("tm", "түркмән", "Түркмәнистан"),
  CountryLocalization("tc", "инҝилис", "Төркс вә Кајкос адалары"),
  CountryLocalization("tv", "инҝилис", "Тувалу"),
  CountryLocalization("um", "инҝилис", "АБШ-а бағлы кичик адаҹыглар"),
  CountryLocalization("vi", "инҝилис", "АБШ Вирҝин адалары"),
  CountryLocalization("ug", "суаһили", "Уганда"),
  CountryLocalization("ua", "украјна", "Украјна"),
  CountryLocalization("ae", "әрәб", "Бирләшмиш Әрәб Әмирликләри"),
  CountryLocalization("gb", "инҝилис", "Бирләшмиш Краллыг"),
  CountryLocalization("us", "лакота", "Америка Бирләшмиш Штатлары"),
  CountryLocalization("uy", "испан", "Уругвај"),
  CountryLocalization("uz", "өзбәк", "Өзбәкистан"),
  CountryLocalization("vu", "франсыз", "Вануату"),
  CountryLocalization("va", "италјан", "Ватикан"),
  CountryLocalization("ve", "испан", "Венесуела"),
  CountryLocalization("vn", "вјетнам", "Вјетнам"),
  CountryLocalization("wf", "франсыз", "Уоллис вә Футуна"),
  CountryLocalization("eh", "әрәб", "Western Sahara"),
  CountryLocalization("ye", "әрәб", "Јәмән"),
  CountryLocalization("zm", "инҝилис", "Замбија"),
  CountryLocalization("zw", "шимали ндебеле", "Зимбабве"),
  CountryLocalization("ax", "исвеч", "Аланд адалары"),
)
