/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot.atlas.extended

import dev.teogor.xenoglot.atlas.CountryLocalization
import kotlin.collections.List

/**
 * Holds the internal list of country-language mappings used for lookups within the package for
 * language code ro.
 *
 * This property contains a hardcoded list of [CountryLocalization] objects, each representing
 * a country and its associated official languages. This list is used by [CountryLanguageRegistry]
 * to provide access to country-language data and should not be modified directly.
 *
 * @see CountryLocalization
 * @see CountryLanguageRegistry
 */
internal val _countryLanguageMappings_ro: List<CountryLocalization> = listOf(
  CountryLocalization("af", "persană", "Afganistan"),
  CountryLocalization("al", "albaneză", "Albania"),
  CountryLocalization("dz", "franceză", "Algeria"),
  CountryLocalization("as", "engleză", "Samoa Americană"),
  CountryLocalization("ad", "catalană", "Andorra"),
  CountryLocalization("ao", "lingala", "Angola"),
  CountryLocalization("ai", "engleză", "Anguilla"),
  CountryLocalization("ag", "engleză", "Antigua și Barbuda"),
  CountryLocalization("ar", "spaniolă", "Argentina"),
  CountryLocalization("am", "armeană", "Armenia"),
  CountryLocalization("aw", "neerlandeză", "Aruba"),
  CountryLocalization("au", "engleză", "Australia"),
  CountryLocalization("at", "engleză", "Austria"),
  CountryLocalization("az", "azeră", "Azerbaidjan"),
  CountryLocalization("bs", "engleză", "Bahamas"),
  CountryLocalization("bh", "arabă", "Bahrain"),
  CountryLocalization("bd", "bengaleză", "Bangladesh"),
  CountryLocalization("bb", "engleză", "Barbados"),
  CountryLocalization("by", "bielorusă", "Belarus"),
  CountryLocalization("be", "franceză", "Belgia"),
  CountryLocalization("bz", "engleză", "Belize"),
  CountryLocalization("bj", "franceză", "Benin"),
  CountryLocalization("bm", "engleză", "Bermuda"),
  CountryLocalization("bt", "dzongkha", "Bhutan"),
  CountryLocalization("bo", "spaniolă", "Bolivia"),
  CountryLocalization("ba", "bosniacă", "Bosnia și Herțegovina"),
  CountryLocalization("bw", "engleză", "Botswana"),
  CountryLocalization("br", "portugheză", "Brazilia"),
  CountryLocalization("io", "engleză", "Teritoriul Britanic din Oceanul Indian"),
  CountryLocalization("vg", "engleză", "Insulele Virgine Britanice"),
  CountryLocalization("bn", "malaeză", "Brunei"),
  CountryLocalization("bg", "bulgară", "Bulgaria"),
  CountryLocalization("bf", "franceză", "Burkina Faso"),
  CountryLocalization("bi", "franceză", "Burundi"),
  CountryLocalization("kh", "khmeră", "Cambodgia"),
  CountryLocalization("cm", "basaa", "Camerun"),
  CountryLocalization("ca", "franceză", "Canada"),
  CountryLocalization("ic", "spaniolă", "Insulele Canare"),
  CountryLocalization("cv", "kabuverdianu", "Capul Verde"),
  CountryLocalization("bq", "neerlandeză", "Insulele Caraibe Olandeze"),
  CountryLocalization("ky", "engleză", "Insulele Cayman"),
  CountryLocalization("cf", "lingala", "Republica Centrafricană"),
  CountryLocalization("ea", "spaniolă", "Ceuta și Melilla"),
  CountryLocalization("td", "arabă", "Ciad"),
  CountryLocalization("cl", "spaniolă", "Chile"),
  CountryLocalization("cn", "tibetană", "China"),
  CountryLocalization("cx", "engleză", "Insula Christmas"),
  CountryLocalization("cc", "engleză", "Insulele Cocos (Keeling)"),
  CountryLocalization("co", "spaniolă", "Columbia"),
  CountryLocalization("km", "arabă", "Comore"),
  CountryLocalization("cg", "lingala", "Congo - Brazzaville"),
  CountryLocalization("cd", "swahili", "Congo - Kinshasa"),
  CountryLocalization("ck", "engleză", "Insulele Cook"),
  CountryLocalization("cr", "spaniolă", "Costa Rica"),
  CountryLocalization("hr", "croată", "Croația"),
  CountryLocalization("cu", "spaniolă", "Cuba"),
  CountryLocalization("cw", "neerlandeză", "Curaçao"),
  CountryLocalization("cy", "engleză", "Cipru"),
  CountryLocalization("cz", "cehă", "Cehia"),
  CountryLocalization("ci", "franceză", "Côte d’Ivoire"),
  CountryLocalization("dk", "engleză", "Danemarca"),
  CountryLocalization("dg", "engleză", "Diego Garcia"),
  CountryLocalization("dj", "franceză", "Djibouti"),
  CountryLocalization("dm", "engleză", "Dominica"),
  CountryLocalization("do", "spaniolă", "Republica Dominicană"),
  CountryLocalization("ec", "quechua", "Ecuador"),
  CountryLocalization("eg", "arabă", "Egipt"),
  CountryLocalization("sv", "spaniolă", "El Salvador"),
  CountryLocalization("gq", "spaniolă", "Guineea Ecuatorială"),
  CountryLocalization("er", "tigrină", "Eritreea"),
  CountryLocalization("ee", "estonă", "Estonia"),
  CountryLocalization("et", "amharică", "Etiopia"),
  CountryLocalization("fk", "engleză", "Insulele Falkland"),
  CountryLocalization("fo", "faroeză", "Insulele Feroe"),
  CountryLocalization("fj", "engleză", "Fiji"),
  CountryLocalization("fi", "suedeză", "Finlanda"),
  CountryLocalization("fr", "germană (Elveția)", "Franța"),
  CountryLocalization("gf", "franceză", "Guyana Franceză"),
  CountryLocalization("pf", "franceză", "Polinezia Franceză"),
  CountryLocalization("ga", "franceză", "Gabon"),
  CountryLocalization("gm", "engleză", "Gambia"),
  CountryLocalization("ge", "osetă", "Georgia"),
  CountryLocalization("de", "sorabă de jos", "Germania"),
  CountryLocalization("gh", "engleză", "Ghana"),
  CountryLocalization("gi", "engleză", "Gibraltar"),
  CountryLocalization("gr", "greacă", "Grecia"),
  CountryLocalization("gl", "kalaallisut", "Groenlanda"),
  CountryLocalization("gd", "engleză", "Grenada"),
  CountryLocalization("gp", "franceză", "Guadelupa"),
  CountryLocalization("gu", "engleză", "Guam"),
  CountryLocalization("gt", "spaniolă", "Guatemala"),
  CountryLocalization("gg", "engleză", "Guernsey"),
  CountryLocalization("gn", "franceză", "Guineea"),
  CountryLocalization("gw", "portugheză", "Guineea-Bissau"),
  CountryLocalization("gy", "engleză", "Guyana"),
  CountryLocalization("ht", "franceză", "Haiti"),
  CountryLocalization("hn", "spaniolă", "Honduras"),
  CountryLocalization("hk", "chineză", "R.A.S. Hong Kong a Chinei"),
  CountryLocalization("hu", "maghiară", "Ungaria"),
  CountryLocalization("is", "islandeză", "Islanda"),
  CountryLocalization("in", "nepaleză", "India"),
  CountryLocalization("id", "Indonesian", "Indonezia"),
  CountryLocalization("ir", "persană", "Iran"),
  CountryLocalization("iq", "luri de nord", "Irak"),
  CountryLocalization("ie", "engleză", "Irlanda"),
  CountryLocalization("im", "manx", "Insula Man"),
  CountryLocalization("il", "engleză", "Israel"),
  CountryLocalization("it", "germană", "Italia"),
  CountryLocalization("jm", "engleză", "Jamaica"),
  CountryLocalization("jp", "japoneză", "Japonia"),
  CountryLocalization("je", "engleză", "Jersey"),
  CountryLocalization("jo", "arabă", "Iordania"),
  CountryLocalization("kz", "kazahă", "Kazahstan"),
  CountryLocalization("ke", "somaleză", "Kenya"),
  CountryLocalization("ki", "engleză", "Kiribati"),
  CountryLocalization("xk", "sârbă", "Kosovo"),
  CountryLocalization("kw", "arabă", "Kuweit"),
  CountryLocalization("kg", "rusă", "Kârgâzstan"),
  CountryLocalization("la", "laoțiană", "Laos"),
  CountryLocalization("lv", "letonă", "Letonia"),
  CountryLocalization("lb", "arabă", "Liban"),
  CountryLocalization("ls", "engleză", "Lesotho"),
  CountryLocalization("lr", "engleză", "Liberia"),
  CountryLocalization("ly", "arabă", "Libia"),
  CountryLocalization("li", "germană (Elveția)", "Liechtenstein"),
  CountryLocalization("lt", "lituaniană", "Lituania"),
  CountryLocalization("lu", "luxemburgheză", "Luxemburg"),
  CountryLocalization("mo", "portugheză", "R.A.S. Macao a Chinei"),
  CountryLocalization("mk", "albaneză", "Republica Macedonia"),
  CountryLocalization("mg", "franceză", "Madagascar"),
  CountryLocalization("mw", "engleză", "Malawi"),
  CountryLocalization("my", "tamilă", "Malaysia"),
  CountryLocalization("ml", "franceză", "Mali"),
  CountryLocalization("mt", "engleză", "Malta"),
  CountryLocalization("mh", "engleză", "Insulele Marshall"),
  CountryLocalization("mq", "franceză", "Martinica"),
  CountryLocalization("mr", "arabă", "Mauritania"),
  CountryLocalization("mu", "morisyen", "Mauritius"),
  CountryLocalization("yt", "franceză", "Mayotte"),
  CountryLocalization("mx", "spaniolă", "Mexic"),
  CountryLocalization("fm", "engleză", "Micronezia"),
  CountryLocalization("md", "rusă", "Republica Moldova"),
  CountryLocalization("mc", "franceză", "Monaco"),
  CountryLocalization("mn", "mongolă", "Mongolia"),
  CountryLocalization("me", "sârbă", "Muntenegru"),
  CountryLocalization("ms", "engleză", "Montserrat"),
  CountryLocalization("ma", "tamazight central marocană", "Maroc"),
  CountryLocalization("mz", "makhuwa-meetto", "Mozambic"),
  CountryLocalization("mm", "birmană", "Myanmar (Birmania)"),
  CountryLocalization("na", "engleză", "Namibia"),
  CountryLocalization("nr", "engleză", "Nauru"),
  CountryLocalization("np", "nepaleză", "Nepal"),
  CountryLocalization("nl", "engleză", "Țările de Jos"),
  CountryLocalization("nc", "franceză", "Noua Caledonie"),
  CountryLocalization("nz", "engleză", "Noua Zeelandă"),
  CountryLocalization("ni", "spaniolă", "Nicaragua"),
  CountryLocalization("ne", "hausa", "Niger"),
  CountryLocalization("ng", "hausa", "Nigeria"),
  CountryLocalization("nu", "engleză", "Niue"),
  CountryLocalization("nf", "engleză", "Insula Norfolk"),
  CountryLocalization("kp", "coreeană", "Coreea de Nord"),
  CountryLocalization("mp", "engleză", "Insulele Mariane de Nord"),
  CountryLocalization("no", "sami de nord", "Norvegia"),
  CountryLocalization("om", "arabă", "Oman"),
  CountryLocalization("pk", "engleză", "Pakistan"),
  CountryLocalization("pw", "engleză", "Palau"),
  CountryLocalization("ps", "arabă", "Teritoriile Palestiniene"),
  CountryLocalization("pa", "spaniolă", "Panama"),
  CountryLocalization("pg", "engleză", "Papua-Noua Guinee"),
  CountryLocalization("py", "spaniolă", "Paraguay"),
  CountryLocalization("pe", "spaniolă", "Peru"),
  CountryLocalization("ph", "filipineză", "Filipine"),
  CountryLocalization("pn", "engleză", "Insulele Pitcairn"),
  CountryLocalization("pl", "poloneză", "Polonia"),
  CountryLocalization("pt", "portugheză", "Portugalia"),
  CountryLocalization("pr", "engleză", "Puerto Rico"),
  CountryLocalization("qa", "arabă", "Qatar"),
  CountryLocalization("ro", "română", "România"),
  CountryLocalization("ru", "tătară", "Rusia"),
  CountryLocalization("rw", "engleză", "Rwanda"),
  CountryLocalization("re", "franceză", "Réunion"),
  CountryLocalization("ws", "engleză", "Samoa"),
  CountryLocalization("sm", "italiană", "San Marino"),
  CountryLocalization("sa", "arabă", "Arabia Saudită"),
  CountryLocalization("sn", "franceză", "Senegal"),
  CountryLocalization("rs", "sârbă", "Serbia"),
  CountryLocalization("cs", "sârbă", "Serbia and Montenegro"),
  CountryLocalization("sc", "franceză", "Seychelles"),
  CountryLocalization("sl", "engleză", "Sierra Leone"),
  CountryLocalization("sg", "tamilă", "Singapore"),
  CountryLocalization("sx", "engleză", "Sint-Maarten"),
  CountryLocalization("sk", "slovacă", "Slovacia"),
  CountryLocalization("si", "slovenă", "Slovenia"),
  CountryLocalization("sb", "engleză", "Insulele Solomon"),
  CountryLocalization("so", "arabă", "Somalia"),
  CountryLocalization("za", "engleză", "Africa de Sud"),
  CountryLocalization("kr", "coreeană", "Coreea de Sud"),
  CountryLocalization("ss", "nuer", "Sudanul de Sud"),
  CountryLocalization("es", "spaniolă", "Spania"),
  CountryLocalization("lk", "tamilă", "Sri Lanka"),
  CountryLocalization("bl", "franceză", "Saint-Barthélemy"),
  CountryLocalization("sh", "engleză", "Sfânta Elena"),
  CountryLocalization("kn", "engleză", "Saint Kitts și Nevis"),
  CountryLocalization("lc", "engleză", "Sfânta Lucia"),
  CountryLocalization("mf", "franceză", "Sfântul Martin"),
  CountryLocalization("pm", "franceză", "Saint-Pierre și Miquelon"),
  CountryLocalization("vc", "engleză", "Saint Vincent și Grenadinele"),
  CountryLocalization("sd", "arabă", "Sudan"),
  CountryLocalization("sr", "neerlandeză", "Suriname"),
  CountryLocalization("sj", "norvegiană bokmål", "Svalbard și Jan Mayen"),
  CountryLocalization("sz", "engleză", "Swaziland"),
  CountryLocalization("se", "suedeză", "Suedia"),
  CountryLocalization("ch", "germană (Elveția)", "Elveția"),
  CountryLocalization("sy", "arabă", "Siria"),
  CountryLocalization("st", "portugheză", "Sao Tome și Principe"),
  CountryLocalization("tw", "chineză", "Taiwan"),
  CountryLocalization("tj", "tadjică", "Tadjikistan"),
  CountryLocalization("tz", "makonde", "Tanzania"),
  CountryLocalization("th", "thailandeză", "Thailanda"),
  CountryLocalization("tl", "portugheză", "Timorul de Est"),
  CountryLocalization("tg", "franceză", "Togo"),
  CountryLocalization("tk", "engleză", "Tokelau"),
  CountryLocalization("to", "tongană", "Tonga"),
  CountryLocalization("tt", "engleză", "Trinidad și Tobago"),
  CountryLocalization("tn", "franceză", "Tunisia"),
  CountryLocalization("tr", "turcă", "Turcia"),
  CountryLocalization("tm", "turkmenă", "Turkmenistan"),
  CountryLocalization("tc", "engleză", "Insulele Turks și Caicos"),
  CountryLocalization("tv", "engleză", "Tuvalu"),
  CountryLocalization("um", "engleză", "Insulele Îndepărtate ale S.U.A."),
  CountryLocalization("vi", "engleză", "Insulele Virgine Americane"),
  CountryLocalization("ug", "swahili", "Uganda"),
  CountryLocalization("ua", "ucraineană", "Ucraina"),
  CountryLocalization("ae", "arabă", "Emiratele Arabe Unite"),
  CountryLocalization("gb", "engleză", "Regatul Unit"),
  CountryLocalization("us", "lakota", "Statele Unite ale Americii"),
  CountryLocalization("uy", "spaniolă", "Uruguay"),
  CountryLocalization("uz", "uzbecă", "Uzbekistan"),
  CountryLocalization("vu", "franceză", "Vanuatu"),
  CountryLocalization("va", "italiană", "Statul Cetății Vaticanului"),
  CountryLocalization("ve", "spaniolă", "Venezuela"),
  CountryLocalization("vn", "vietnameză", "Vietnam"),
  CountryLocalization("wf", "franceză", "Wallis și Futuna"),
  CountryLocalization("eh", "arabă", "Sahara Occidentală"),
  CountryLocalization("ye", "arabă", "Yemen"),
  CountryLocalization("zm", "engleză", "Zambia"),
  CountryLocalization("zw", "ndebele de nord", "Zimbabwe"),
  CountryLocalization("ax", "suedeză", "Insulele Åland"),
)
