/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot.atlas.extended

import dev.teogor.xenoglot.atlas.CountryLocalization
import kotlin.collections.List

/**
 * Holds the internal list of country-language mappings used for lookups within the package for
 * language code cs.
 *
 * This property contains a hardcoded list of [CountryLocalization] objects, each representing
 * a country and its associated official languages. This list is used by [CountryLanguageRegistry]
 * to provide access to country-language data and should not be modified directly.
 *
 * @see CountryLocalization
 * @see CountryLanguageRegistry
 */
internal val _countryLanguageMappings_cs: List<CountryLocalization> = listOf(
  CountryLocalization("af", "perština", "Afghánistán"),
  CountryLocalization("al", "albánština", "Albánie"),
  CountryLocalization("dz", "francouzština", "Alžírsko"),
  CountryLocalization("as", "angličtina", "Americká Samoa"),
  CountryLocalization("ad", "katalánština", "Andorra"),
  CountryLocalization("ao", "lingalština", "Angola"),
  CountryLocalization("ai", "angličtina", "Anguilla"),
  CountryLocalization("ag", "angličtina", "Antigua a Barbuda"),
  CountryLocalization("ar", "španělština", "Argentina"),
  CountryLocalization("am", "arménština", "Arménie"),
  CountryLocalization("aw", "nizozemština", "Aruba"),
  CountryLocalization("au", "angličtina", "Austrálie"),
  CountryLocalization("at", "angličtina", "Rakousko"),
  CountryLocalization("az", "ázerbájdžánština", "Ázerbájdžán"),
  CountryLocalization("bs", "angličtina", "Bahamy"),
  CountryLocalization("bh", "arabština", "Bahrajn"),
  CountryLocalization("bd", "bengálština", "Bangladéš"),
  CountryLocalization("bb", "angličtina", "Barbados"),
  CountryLocalization("by", "běloruština", "Bělorusko"),
  CountryLocalization("be", "francouzština", "Belgie"),
  CountryLocalization("bz", "angličtina", "Belize"),
  CountryLocalization("bj", "francouzština", "Benin"),
  CountryLocalization("bm", "angličtina", "Bermudy"),
  CountryLocalization("bt", "dzongkä", "Bhútán"),
  CountryLocalization("bo", "španělština", "Bolívie"),
  CountryLocalization("ba", "bosenština", "Bosna a Hercegovina"),
  CountryLocalization("bw", "angličtina", "Botswana"),
  CountryLocalization("br", "portugalština", "Brazílie"),
  CountryLocalization("io", "angličtina", "Britské indickooceánské území"),
  CountryLocalization("vg", "angličtina", "Britské Panenské ostrovy"),
  CountryLocalization("bn", "malajština", "Brunej"),
  CountryLocalization("bg", "bulharština", "Bulharsko"),
  CountryLocalization("bf", "francouzština", "Burkina Faso"),
  CountryLocalization("bi", "francouzština", "Burundi"),
  CountryLocalization("kh", "khmérština", "Kambodža"),
  CountryLocalization("cm", "basa", "Kamerun"),
  CountryLocalization("ca", "francouzština", "Kanada"),
  CountryLocalization("ic", "španělština", "Kanárské ostrovy"),
  CountryLocalization("cv", "kapverdština", "Kapverdy"),
  CountryLocalization("bq", "nizozemština", "Karibské Nizozemsko"),
  CountryLocalization("ky", "angličtina", "Kajmanské ostrovy"),
  CountryLocalization("cf", "lingalština", "Středoafrická republika"),
  CountryLocalization("ea", "španělština", "Ceuta a Melilla"),
  CountryLocalization("td", "arabština", "Čad"),
  CountryLocalization("cl", "španělština", "Chile"),
  CountryLocalization("cn", "tibetština", "Čína"),
  CountryLocalization("cx", "angličtina", "Vánoční ostrov"),
  CountryLocalization("cc", "angličtina", "Kokosové ostrovy"),
  CountryLocalization("co", "španělština", "Kolumbie"),
  CountryLocalization("km", "arabština", "Komory"),
  CountryLocalization("cg", "lingalština", "Kongo – Brazzaville"),
  CountryLocalization("cd", "svahilština", "Kongo – Kinshasa"),
  CountryLocalization("ck", "angličtina", "Cookovy ostrovy"),
  CountryLocalization("cr", "španělština", "Kostarika"),
  CountryLocalization("hr", "chorvatština", "Chorvatsko"),
  CountryLocalization("cu", "španělština", "Kuba"),
  CountryLocalization("cw", "nizozemština", "Curaçao"),
  CountryLocalization("cy", "angličtina", "Kypr"),
  CountryLocalization("cz", "čeština", "Česko"),
  CountryLocalization("ci", "francouzština", "Pobřeží slonoviny"),
  CountryLocalization("dk", "angličtina", "Dánsko"),
  CountryLocalization("dg", "angličtina", "Diego García"),
  CountryLocalization("dj", "francouzština", "Džibutsko"),
  CountryLocalization("dm", "angličtina", "Dominika"),
  CountryLocalization("do", "španělština", "Dominikánská republika"),
  CountryLocalization("ec", "kečuánština", "Ekvádor"),
  CountryLocalization("eg", "arabština", "Egypt"),
  CountryLocalization("sv", "španělština", "Salvador"),
  CountryLocalization("gq", "španělština", "Rovníková Guinea"),
  CountryLocalization("er", "tigrinijština", "Eritrea"),
  CountryLocalization("ee", "estonština", "Estonsko"),
  CountryLocalization("et", "amharština", "Etiopie"),
  CountryLocalization("fk", "angličtina", "Falklandské ostrovy"),
  CountryLocalization("fo", "faerština", "Faerské ostrovy"),
  CountryLocalization("fj", "angličtina", "Fidži"),
  CountryLocalization("fi", "švédština", "Finsko"),
  CountryLocalization("fr", "němčina (Švýcarsko)", "Francie"),
  CountryLocalization("gf", "francouzština", "Francouzská Guyana"),
  CountryLocalization("pf", "francouzština", "Francouzská Polynésie"),
  CountryLocalization("ga", "francouzština", "Gabon"),
  CountryLocalization("gm", "angličtina", "Gambie"),
  CountryLocalization("ge", "osetština", "Gruzie"),
  CountryLocalization("de", "dolnolužická srbština", "Německo"),
  CountryLocalization("gh", "angličtina", "Ghana"),
  CountryLocalization("gi", "angličtina", "Gibraltar"),
  CountryLocalization("gr", "řečtina", "Řecko"),
  CountryLocalization("gl", "grónština", "Grónsko"),
  CountryLocalization("gd", "angličtina", "Grenada"),
  CountryLocalization("gp", "francouzština", "Guadeloupe"),
  CountryLocalization("gu", "angličtina", "Guam"),
  CountryLocalization("gt", "španělština", "Guatemala"),
  CountryLocalization("gg", "angličtina", "Guernsey"),
  CountryLocalization("gn", "francouzština", "Guinea"),
  CountryLocalization("gw", "portugalština", "Guinea-Bissau"),
  CountryLocalization("gy", "angličtina", "Guyana"),
  CountryLocalization("ht", "francouzština", "Haiti"),
  CountryLocalization("hn", "španělština", "Honduras"),
  CountryLocalization("hk", "čínština", "Hongkong – ZAO Číny"),
  CountryLocalization("hu", "maďarština", "Maďarsko"),
  CountryLocalization("is", "islandština", "Island"),
  CountryLocalization("in", "nepálština", "Indie"),
  CountryLocalization("id", "Indonesian", "Indonésie"),
  CountryLocalization("ir", "perština", "Írán"),
  CountryLocalization("iq", "lúrština (severní)", "Irák"),
  CountryLocalization("ie", "angličtina", "Irsko"),
  CountryLocalization("im", "manština", "Ostrov Man"),
  CountryLocalization("il", "angličtina", "Izrael"),
  CountryLocalization("it", "němčina", "Itálie"),
  CountryLocalization("jm", "angličtina", "Jamajka"),
  CountryLocalization("jp", "japonština", "Japonsko"),
  CountryLocalization("je", "angličtina", "Jersey"),
  CountryLocalization("jo", "arabština", "Jordánsko"),
  CountryLocalization("kz", "kazaština", "Kazachstán"),
  CountryLocalization("ke", "somálština", "Keňa"),
  CountryLocalization("ki", "angličtina", "Kiribati"),
  CountryLocalization("xk", "srbština", "Kosovo"),
  CountryLocalization("kw", "arabština", "Kuvajt"),
  CountryLocalization("kg", "ruština", "Kyrgyzstán"),
  CountryLocalization("la", "laoština", "Laos"),
  CountryLocalization("lv", "lotyština", "Lotyšsko"),
  CountryLocalization("lb", "arabština", "Libanon"),
  CountryLocalization("ls", "angličtina", "Lesotho"),
  CountryLocalization("lr", "angličtina", "Libérie"),
  CountryLocalization("ly", "arabština", "Libye"),
  CountryLocalization("li", "němčina (Švýcarsko)", "Lichtenštejnsko"),
  CountryLocalization("lt", "litevština", "Litva"),
  CountryLocalization("lu", "lucemburština", "Lucembursko"),
  CountryLocalization("mo", "portugalština", "Macao – ZAO Číny"),
  CountryLocalization("mk", "albánština", "Makedonie"),
  CountryLocalization("mg", "francouzština", "Madagaskar"),
  CountryLocalization("mw", "angličtina", "Malawi"),
  CountryLocalization("my", "tamilština", "Malajsie"),
  CountryLocalization("ml", "francouzština", "Mali"),
  CountryLocalization("mt", "angličtina", "Malta"),
  CountryLocalization("mh", "angličtina", "Marshallovy ostrovy"),
  CountryLocalization("mq", "francouzština", "Martinik"),
  CountryLocalization("mr", "arabština", "Mauritánie"),
  CountryLocalization("mu", "mauricijská kreolština", "Mauricius"),
  CountryLocalization("yt", "francouzština", "Mayotte"),
  CountryLocalization("mx", "španělština", "Mexiko"),
  CountryLocalization("fm", "angličtina", "Mikronésie"),
  CountryLocalization("md", "ruština", "Moldavsko"),
  CountryLocalization("mc", "francouzština", "Monako"),
  CountryLocalization("mn", "mongolština", "Mongolsko"),
  CountryLocalization("me", "srbština", "Černá Hora"),
  CountryLocalization("ms", "angličtina", "Montserrat"),
  CountryLocalization("ma", "tamazight (střední Maroko)", "Maroko"),
  CountryLocalization("mz", "makhuwa-meetto", "Mosambik"),
  CountryLocalization("mm", "barmština", "Myanmar (Barma)"),
  CountryLocalization("na", "angličtina", "Namibie"),
  CountryLocalization("nr", "angličtina", "Nauru"),
  CountryLocalization("np", "nepálština", "Nepál"),
  CountryLocalization("nl", "angličtina", "Nizozemsko"),
  CountryLocalization("nc", "francouzština", "Nová Kaledonie"),
  CountryLocalization("nz", "angličtina", "Nový Zéland"),
  CountryLocalization("ni", "španělština", "Nikaragua"),
  CountryLocalization("ne", "hauština", "Niger"),
  CountryLocalization("ng", "hauština", "Nigérie"),
  CountryLocalization("nu", "angličtina", "Niue"),
  CountryLocalization("nf", "angličtina", "Norfolk"),
  CountryLocalization("kp", "korejština", "Severní Korea"),
  CountryLocalization("mp", "angličtina", "Severní Mariany"),
  CountryLocalization("no", "sámština (severní)", "Norsko"),
  CountryLocalization("om", "arabština", "Omán"),
  CountryLocalization("pk", "angličtina", "Pákistán"),
  CountryLocalization("pw", "angličtina", "Palau"),
  CountryLocalization("ps", "arabština", "Palestinská území"),
  CountryLocalization("pa", "španělština", "Panama"),
  CountryLocalization("pg", "angličtina", "Papua-Nová Guinea"),
  CountryLocalization("py", "španělština", "Paraguay"),
  CountryLocalization("pe", "španělština", "Peru"),
  CountryLocalization("ph", "filipínština", "Filipíny"),
  CountryLocalization("pn", "angličtina", "Pitcairnovy ostrovy"),
  CountryLocalization("pl", "polština", "Polsko"),
  CountryLocalization("pt", "portugalština", "Portugalsko"),
  CountryLocalization("pr", "angličtina", "Portoriko"),
  CountryLocalization("qa", "arabština", "Katar"),
  CountryLocalization("ro", "rumunština", "Rumunsko"),
  CountryLocalization("ru", "tatarština", "Rusko"),
  CountryLocalization("rw", "angličtina", "Rwanda"),
  CountryLocalization("re", "francouzština", "Réunion"),
  CountryLocalization("ws", "angličtina", "Samoa"),
  CountryLocalization("sm", "italština", "San Marino"),
  CountryLocalization("sa", "arabština", "Saúdská Arábie"),
  CountryLocalization("sn", "francouzština", "Senegal"),
  CountryLocalization("rs", "srbština", "Srbsko"),
  CountryLocalization("cs", "srbština", "Serbia and Montenegro"),
  CountryLocalization("sc", "francouzština", "Seychely"),
  CountryLocalization("sl", "angličtina", "Sierra Leone"),
  CountryLocalization("sg", "tamilština", "Singapur"),
  CountryLocalization("sx", "angličtina", "Svatý Martin (Nizozemsko)"),
  CountryLocalization("sk", "slovenština", "Slovensko"),
  CountryLocalization("si", "slovinština", "Slovinsko"),
  CountryLocalization("sb", "angličtina", "Šalamounovy ostrovy"),
  CountryLocalization("so", "arabština", "Somálsko"),
  CountryLocalization("za", "angličtina", "Jihoafrická republika"),
  CountryLocalization("kr", "korejština", "Jižní Korea"),
  CountryLocalization("ss", "nuerština", "Jižní Súdán"),
  CountryLocalization("es", "španělština", "Španělsko"),
  CountryLocalization("lk", "tamilština", "Srí Lanka"),
  CountryLocalization("bl", "francouzština", "Svatý Bartoloměj"),
  CountryLocalization("sh", "angličtina", "Svatá Helena"),
  CountryLocalization("kn", "angličtina", "Svatý Kryštof a Nevis"),
  CountryLocalization("lc", "angličtina", "Svatá Lucie"),
  CountryLocalization("mf", "francouzština", "Svatý Martin (Francie)"),
  CountryLocalization("pm", "francouzština", "Saint-Pierre a Miquelon"),
  CountryLocalization("vc", "angličtina", "Svatý Vincenc a Grenadiny"),
  CountryLocalization("sd", "arabština", "Súdán"),
  CountryLocalization("sr", "nizozemština", "Surinam"),
  CountryLocalization("sj", "norština (bokmål)", "Špicberky a Jan Mayen"),
  CountryLocalization("sz", "angličtina", "Svazijsko"),
  CountryLocalization("se", "švédština", "Švédsko"),
  CountryLocalization("ch", "němčina (Švýcarsko)", "Švýcarsko"),
  CountryLocalization("sy", "arabština", "Sýrie"),
  CountryLocalization("st", "portugalština", "Svatý Tomáš a Princův ostrov"),
  CountryLocalization("tw", "čínština", "Tchaj-wan"),
  CountryLocalization("tj", "tádžičtina", "Tádžikistán"),
  CountryLocalization("tz", "makonde", "Tanzanie"),
  CountryLocalization("th", "thajština", "Thajsko"),
  CountryLocalization("tl", "portugalština", "Východní Timor"),
  CountryLocalization("tg", "francouzština", "Togo"),
  CountryLocalization("tk", "angličtina", "Tokelau"),
  CountryLocalization("to", "tongánština", "Tonga"),
  CountryLocalization("tt", "angličtina", "Trinidad a Tobago"),
  CountryLocalization("tn", "francouzština", "Tunisko"),
  CountryLocalization("tr", "turečtina", "Turecko"),
  CountryLocalization("tm", "turkmenština", "Turkmenistán"),
  CountryLocalization("tc", "angličtina", "Turks a Caicos"),
  CountryLocalization("tv", "angličtina", "Tuvalu"),
  CountryLocalization("um", "angličtina", "Menší odlehlé ostrovy USA"),
  CountryLocalization("vi", "angličtina", "Americké Panenské ostrovy"),
  CountryLocalization("ug", "svahilština", "Uganda"),
  CountryLocalization("ua", "ukrajinština", "Ukrajina"),
  CountryLocalization("ae", "arabština", "Spojené arabské emiráty"),
  CountryLocalization("gb", "angličtina", "Spojené království"),
  CountryLocalization("us", "lakotština", "Spojené státy"),
  CountryLocalization("uy", "španělština", "Uruguay"),
  CountryLocalization("uz", "uzbečtina", "Uzbekistán"),
  CountryLocalization("vu", "francouzština", "Vanuatu"),
  CountryLocalization("va", "italština", "Vatikán"),
  CountryLocalization("ve", "španělština", "Venezuela"),
  CountryLocalization("vn", "vietnamština", "Vietnam"),
  CountryLocalization("wf", "francouzština", "Wallis a Futuna"),
  CountryLocalization("eh", "arabština", "Západní Sahara"),
  CountryLocalization("ye", "arabština", "Jemen"),
  CountryLocalization("zm", "angličtina", "Zambie"),
  CountryLocalization("zw", "ndebele (Zimbabwe)", "Zimbabwe"),
  CountryLocalization("ax", "švédština", "Ålandy"),
)
