/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot.atlas.extended

import dev.teogor.xenoglot.atlas.CountryLocalization
import kotlin.collections.List

/**
 * Holds the internal list of country-language mappings used for lookups within the package for
 * language code in.
 *
 * This property contains a hardcoded list of [CountryLocalization] objects, each representing
 * a country and its associated official languages. This list is used by [CountryLanguageRegistry]
 * to provide access to country-language data and should not be modified directly.
 *
 * @see CountryLocalization
 * @see CountryLanguageRegistry
 */
internal val _countryLanguageMappings_in: List<CountryLocalization> = listOf(
  CountryLocalization("af", "Persia", "Afganistan"),
  CountryLocalization("al", "Albania", "Albania"),
  CountryLocalization("dz", "Prancis", "Aljazair"),
  CountryLocalization("as", "Inggris", "Samoa Amerika"),
  CountryLocalization("ad", "Katalan", "Andorra"),
  CountryLocalization("ao", "Lingala", "Angola"),
  CountryLocalization("ai", "Inggris", "Anguilla"),
  CountryLocalization("ag", "Inggris", "Antigua dan Barbuda"),
  CountryLocalization("ar", "Spanyol", "Argentina"),
  CountryLocalization("am", "Armenia", "Armenia"),
  CountryLocalization("aw", "Belanda", "Aruba"),
  CountryLocalization("au", "Inggris", "Australia"),
  CountryLocalization("at", "Inggris", "Austria"),
  CountryLocalization("az", "Azerbaijani", "Azerbaijan"),
  CountryLocalization("bs", "Inggris", "Bahama"),
  CountryLocalization("bh", "Arab", "Bahrain"),
  CountryLocalization("bd", "Bengali", "Bangladesh"),
  CountryLocalization("bb", "Inggris", "Barbados"),
  CountryLocalization("by", "Belarusia", "Belarus"),
  CountryLocalization("be", "Prancis", "Belgia"),
  CountryLocalization("bz", "Inggris", "Belize"),
  CountryLocalization("bj", "Prancis", "Benin"),
  CountryLocalization("bm", "Inggris", "Bermuda"),
  CountryLocalization("bt", "Dzongkha", "Bhutan"),
  CountryLocalization("bo", "Spanyol", "Bolivia"),
  CountryLocalization("ba", "Bosnia", "Bosnia dan Herzegovina"),
  CountryLocalization("bw", "Inggris", "Botswana"),
  CountryLocalization("br", "Portugis", "Brasil"),
  CountryLocalization("io", "Inggris", "Wilayah Inggris di Samudra Hindia"),
  CountryLocalization("vg", "Inggris", "Kepulauan Virgin Inggris"),
  CountryLocalization("bn", "Melayu", "Brunei"),
  CountryLocalization("bg", "Bulgaria", "Bulgaria"),
  CountryLocalization("bf", "Prancis", "Burkina Faso"),
  CountryLocalization("bi", "Prancis", "Burundi"),
  CountryLocalization("kh", "Khmer", "Kamboja"),
  CountryLocalization("cm", "Basa", "Kamerun"),
  CountryLocalization("ca", "Prancis", "Kanada"),
  CountryLocalization("ic", "Spanyol", "Kepulauan Canary"),
  CountryLocalization("cv", "Kabuverdianu", "Tanjung Verde"),
  CountryLocalization("bq", "Belanda", "Belanda Karibia"),
  CountryLocalization("ky", "Inggris", "Kepulauan Cayman"),
  CountryLocalization("cf", "Lingala", "Republik Afrika Tengah"),
  CountryLocalization("ea", "Spanyol", "Ceuta dan Melilla"),
  CountryLocalization("td", "Arab", "Cad"),
  CountryLocalization("cl", "Spanyol", "Cile"),
  CountryLocalization("cn", "Tibet", "Tiongkok"),
  CountryLocalization("cx", "Inggris", "Pulau Christmas"),
  CountryLocalization("cc", "Inggris", "Kepulauan Cocos (Keeling)"),
  CountryLocalization("co", "Spanyol", "Kolombia"),
  CountryLocalization("km", "Arab", "Komoro"),
  CountryLocalization("cg", "Lingala", "Kongo - Brazzaville"),
  CountryLocalization("cd", "Swahili", "Kongo - Kinshasa"),
  CountryLocalization("ck", "Inggris", "Kepulauan Cook"),
  CountryLocalization("cr", "Spanyol", "Kosta Rika"),
  CountryLocalization("hr", "Kroasia", "Kroasia"),
  CountryLocalization("cu", "Spanyol", "Kuba"),
  CountryLocalization("cw", "Belanda", "Curaçao"),
  CountryLocalization("cy", "Inggris", "Siprus"),
  CountryLocalization("cz", "Cheska", "Ceko"),
  CountryLocalization("ci", "Prancis", "Pantai Gading"),
  CountryLocalization("dk", "Inggris", "Denmark"),
  CountryLocalization("dg", "Inggris", "Diego Garcia"),
  CountryLocalization("dj", "Prancis", "Jibuti"),
  CountryLocalization("dm", "Inggris", "Dominika"),
  CountryLocalization("do", "Spanyol", "Republik Dominika"),
  CountryLocalization("ec", "Quechua", "Ekuador"),
  CountryLocalization("eg", "Arab", "Mesir"),
  CountryLocalization("sv", "Spanyol", "El Salvador"),
  CountryLocalization("gq", "Spanyol", "Guinea Ekuatorial"),
  CountryLocalization("er", "Tigrinya", "Eritrea"),
  CountryLocalization("ee", "Esti", "Estonia"),
  CountryLocalization("et", "Amharik", "Etiopia"),
  CountryLocalization("fk", "Inggris", "Kepulauan Malvinas"),
  CountryLocalization("fo", "Faroe", "Kepulauan Faroe"),
  CountryLocalization("fj", "Inggris", "Fiji"),
  CountryLocalization("fi", "Swedia", "Finlandia"),
  CountryLocalization("fr", "Jerman (Swiss)", "Prancis"),
  CountryLocalization("gf", "Prancis", "Guyana Prancis"),
  CountryLocalization("pf", "Prancis", "Polinesia Prancis"),
  CountryLocalization("ga", "Prancis", "Gabon"),
  CountryLocalization("gm", "Inggris", "Gambia"),
  CountryLocalization("ge", "Ossetia", "Georgia"),
  CountryLocalization("de", "Sorbia Hilir", "Jerman"),
  CountryLocalization("gh", "Inggris", "Ghana"),
  CountryLocalization("gi", "Inggris", "Gibraltar"),
  CountryLocalization("gr", "Yunani", "Yunani"),
  CountryLocalization("gl", "Kalaallisut", "Grinlandia"),
  CountryLocalization("gd", "Inggris", "Grenada"),
  CountryLocalization("gp", "Prancis", "Guadeloupe"),
  CountryLocalization("gu", "Inggris", "Guam"),
  CountryLocalization("gt", "Spanyol", "Guatemala"),
  CountryLocalization("gg", "Inggris", "Guernsey"),
  CountryLocalization("gn", "Prancis", "Guinea"),
  CountryLocalization("gw", "Portugis", "Guinea-Bissau"),
  CountryLocalization("gy", "Inggris", "Guyana"),
  CountryLocalization("ht", "Prancis", "Haiti"),
  CountryLocalization("hn", "Spanyol", "Honduras"),
  CountryLocalization("hk", "Tionghoa", "Hong Kong SAR Tiongkok"),
  CountryLocalization("hu", "Hungaria", "Hungaria"),
  CountryLocalization("is", "Islandia", "Islandia"),
  CountryLocalization("in", "Nepali", "India"),
  CountryLocalization("id", "Bahasa Indonesia", "Indonesia"),
  CountryLocalization("ir", "Persia", "Iran"),
  CountryLocalization("iq", "Luri Utara", "Irak"),
  CountryLocalization("ie", "Inggris", "Irlandia"),
  CountryLocalization("im", "Manx", "Pulau Man"),
  CountryLocalization("il", "Inggris", "Israel"),
  CountryLocalization("it", "Jerman", "Italia"),
  CountryLocalization("jm", "Inggris", "Jamaika"),
  CountryLocalization("jp", "Jepang", "Jepang"),
  CountryLocalization("je", "Inggris", "Jersey"),
  CountryLocalization("jo", "Arab", "Yordania"),
  CountryLocalization("kz", "Kazakh", "Kazakstan"),
  CountryLocalization("ke", "Somalia", "Kenya"),
  CountryLocalization("ki", "Inggris", "Kiribati"),
  CountryLocalization("xk", "Serbia", "Kosovo"),
  CountryLocalization("kw", "Arab", "Kuwait"),
  CountryLocalization("kg", "Rusia", "Kirgistan"),
  CountryLocalization("la", "Lao", "Laos"),
  CountryLocalization("lv", "Latvi", "Latvia"),
  CountryLocalization("lb", "Arab", "Lebanon"),
  CountryLocalization("ls", "Inggris", "Lesotho"),
  CountryLocalization("lr", "Inggris", "Liberia"),
  CountryLocalization("ly", "Arab", "Libia"),
  CountryLocalization("li", "Jerman (Swiss)", "Liechtenstein"),
  CountryLocalization("lt", "Lituavi", "Lituania"),
  CountryLocalization("lu", "Luksemburg", "Luksemburg"),
  CountryLocalization("mo", "Portugis", "Makau SAR Tiongkok"),
  CountryLocalization("mk", "Albania", "Makedonia"),
  CountryLocalization("mg", "Prancis", "Madagaskar"),
  CountryLocalization("mw", "Inggris", "Malawi"),
  CountryLocalization("my", "Tamil", "Malaysia"),
  CountryLocalization("ml", "Prancis", "Mali"),
  CountryLocalization("mt", "Inggris", "Malta"),
  CountryLocalization("mh", "Inggris", "Kepulauan Marshall"),
  CountryLocalization("mq", "Prancis", "Martinik"),
  CountryLocalization("mr", "Arab", "Mauritania"),
  CountryLocalization("mu", "Morisien", "Mauritius"),
  CountryLocalization("yt", "Prancis", "Mayotte"),
  CountryLocalization("mx", "Spanyol", "Meksiko"),
  CountryLocalization("fm", "Inggris", "Mikronesia"),
  CountryLocalization("md", "Rusia", "Moldova"),
  CountryLocalization("mc", "Prancis", "Monako"),
  CountryLocalization("mn", "Mongolia", "Mongolia"),
  CountryLocalization("me", "Serbia", "Montenegro"),
  CountryLocalization("ms", "Inggris", "Montserrat"),
  CountryLocalization("ma", "Tamazight Maroko Tengah", "Maroko"),
  CountryLocalization("mz", "Makhuwa-Meetto", "Mozambik"),
  CountryLocalization("mm", "Burma", "Myanmar (Burma)"),
  CountryLocalization("na", "Inggris", "Namibia"),
  CountryLocalization("nr", "Inggris", "Nauru"),
  CountryLocalization("np", "Nepali", "Nepal"),
  CountryLocalization("nl", "Inggris", "Belanda"),
  CountryLocalization("nc", "Prancis", "Kaledonia Baru"),
  CountryLocalization("nz", "Inggris", "Selandia Baru"),
  CountryLocalization("ni", "Spanyol", "Nikaragua"),
  CountryLocalization("ne", "Hausa", "Niger"),
  CountryLocalization("ng", "Hausa", "Nigeria"),
  CountryLocalization("nu", "Inggris", "Niue"),
  CountryLocalization("nf", "Inggris", "Kepulauan Norfolk"),
  CountryLocalization("kp", "Korea", "Korea Utara"),
  CountryLocalization("mp", "Inggris", "Kepulauan Mariana Utara"),
  CountryLocalization("no", "Sami Utara", "Norwegia"),
  CountryLocalization("om", "Arab", "Oman"),
  CountryLocalization("pk", "Inggris", "Pakistan"),
  CountryLocalization("pw", "Inggris", "Palau"),
  CountryLocalization("ps", "Arab", "Wilayah Palestina"),
  CountryLocalization("pa", "Spanyol", "Panama"),
  CountryLocalization("pg", "Inggris", "Papua Nugini"),
  CountryLocalization("py", "Spanyol", "Paraguay"),
  CountryLocalization("pe", "Spanyol", "Peru"),
  CountryLocalization("ph", "Filipino", "Filipina"),
  CountryLocalization("pn", "Inggris", "Kepulauan Pitcairn"),
  CountryLocalization("pl", "Polski", "Polandia"),
  CountryLocalization("pt", "Portugis", "Portugal"),
  CountryLocalization("pr", "Inggris", "Puerto Riko"),
  CountryLocalization("qa", "Arab", "Qatar"),
  CountryLocalization("ro", "Rumania", "Rumania"),
  CountryLocalization("ru", "Tatar", "Rusia"),
  CountryLocalization("rw", "Inggris", "Rwanda"),
  CountryLocalization("re", "Prancis", "Réunion"),
  CountryLocalization("ws", "Inggris", "Samoa"),
  CountryLocalization("sm", "Italia", "San Marino"),
  CountryLocalization("sa", "Arab", "Arab Saudi"),
  CountryLocalization("sn", "Prancis", "Senegal"),
  CountryLocalization("rs", "Serbia", "Serbia"),
  CountryLocalization("cs", "Serbia", "Serbia and Montenegro"),
  CountryLocalization("sc", "Prancis", "Seychelles"),
  CountryLocalization("sl", "Inggris", "Sierra Leone"),
  CountryLocalization("sg", "Tamil", "Singapura"),
  CountryLocalization("sx", "Inggris", "Sint Maarten"),
  CountryLocalization("sk", "Slovak", "Slovakia"),
  CountryLocalization("si", "Sloven", "Slovenia"),
  CountryLocalization("sb", "Inggris", "Kepulauan Solomon"),
  CountryLocalization("so", "Arab", "Somalia"),
  CountryLocalization("za", "Inggris", "Afrika Selatan"),
  CountryLocalization("kr", "Korea", "Korea Selatan"),
  CountryLocalization("ss", "Nuer", "Sudan Selatan"),
  CountryLocalization("es", "Spanyol", "Spanyol"),
  CountryLocalization("lk", "Tamil", "Sri Lanka"),
  CountryLocalization("bl", "Prancis", "Saint Barthélemy"),
  CountryLocalization("sh", "Inggris", "Saint Helena"),
  CountryLocalization("kn", "Inggris", "Saint Kitts dan Nevis"),
  CountryLocalization("lc", "Inggris", "Saint Lucia"),
  CountryLocalization("mf", "Prancis", "Saint Martin"),
  CountryLocalization("pm", "Prancis", "Saint Pierre dan Miquelon"),
  CountryLocalization("vc", "Inggris", "Saint Vincent dan Grenadines"),
  CountryLocalization("sd", "Arab", "Sudan"),
  CountryLocalization("sr", "Belanda", "Suriname"),
  CountryLocalization("sj", "Bokmål Norwegia", "Kepulauan Svalbard dan Jan Mayen"),
  CountryLocalization("sz", "Inggris", "Swaziland"),
  CountryLocalization("se", "Swedia", "Swedia"),
  CountryLocalization("ch", "Jerman (Swiss)", "Swiss"),
  CountryLocalization("sy", "Arab", "Suriah"),
  CountryLocalization("st", "Portugis", "Sao Tome dan Principe"),
  CountryLocalization("tw", "Tionghoa", "Taiwan"),
  CountryLocalization("tj", "Tajik", "Tajikistan"),
  CountryLocalization("tz", "Makonde", "Tanzania"),
  CountryLocalization("th", "Thai", "Thailand"),
  CountryLocalization("tl", "Portugis", "Timor Leste"),
  CountryLocalization("tg", "Prancis", "Togo"),
  CountryLocalization("tk", "Inggris", "Tokelau"),
  CountryLocalization("to", "Tonga", "Tonga"),
  CountryLocalization("tt", "Inggris", "Trinidad dan Tobago"),
  CountryLocalization("tn", "Prancis", "Tunisia"),
  CountryLocalization("tr", "Turki", "Turki"),
  CountryLocalization("tm", "Turkmen", "Turkimenistan"),
  CountryLocalization("tc", "Inggris", "Kepulauan Turks dan Caicos"),
  CountryLocalization("tv", "Inggris", "Tuvalu"),
  CountryLocalization("um", "Inggris", "Kepulauan Terluar A.S."),
  CountryLocalization("vi", "Inggris", "Kepulauan Virgin A.S."),
  CountryLocalization("ug", "Swahili", "Uganda"),
  CountryLocalization("ua", "Ukraina", "Ukraina"),
  CountryLocalization("ae", "Arab", "Uni Emirat Arab"),
  CountryLocalization("gb", "Inggris", "Inggris Raya"),
  CountryLocalization("us", "Lakota", "Amerika Serikat"),
  CountryLocalization("uy", "Spanyol", "Uruguay"),
  CountryLocalization("uz", "Uzbek", "Uzbekistan"),
  CountryLocalization("vu", "Prancis", "Vanuatu"),
  CountryLocalization("va", "Italia", "Vatikan"),
  CountryLocalization("ve", "Spanyol", "Venezuela"),
  CountryLocalization("vn", "Vietnam", "Vietnam"),
  CountryLocalization("wf", "Prancis", "Kepulauan Wallis dan Futuna"),
  CountryLocalization("eh", "Arab", "Sahara Barat"),
  CountryLocalization("ye", "Arab", "Yaman"),
  CountryLocalization("zm", "Inggris", "Zambia"),
  CountryLocalization("zw", "Ndebele Utara", "Zimbabwe"),
  CountryLocalization("ax", "Swedia", "Kepulauan Aland"),
)
