/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot.atlas.extended

import dev.teogor.xenoglot.atlas.CountryLocalization
import kotlin.collections.List

/**
 * Holds the internal list of country-language mappings used for lookups within the package for
 * language code el.
 *
 * This property contains a hardcoded list of [CountryLocalization] objects, each representing
 * a country and its associated official languages. This list is used by [CountryLanguageRegistry]
 * to provide access to country-language data and should not be modified directly.
 *
 * @see CountryLocalization
 * @see CountryLanguageRegistry
 */
internal val _countryLanguageMappings_el: List<CountryLocalization> = listOf(
  CountryLocalization("af", "Περσικά", "Αφγανιστάν"),
  CountryLocalization("al", "Αλβανικά", "Αλβανία"),
  CountryLocalization("dz", "Γαλλικά", "Αλγερία"),
  CountryLocalization("as", "Αγγλικά", "Αμερικανική Σαμόα"),
  CountryLocalization("ad", "Καταλανικά", "Ανδόρα"),
  CountryLocalization("ao", "Λινγκάλα", "Αγκόλα"),
  CountryLocalization("ai", "Αγγλικά", "Ανγκουίλα"),
  CountryLocalization("ag", "Αγγλικά", "Αντίγκουα και Μπαρμπούντα"),
  CountryLocalization("ar", "Ισπανικά", "Αργεντινή"),
  CountryLocalization("am", "Αρμενικά", "Αρμενία"),
  CountryLocalization("aw", "Ολλανδικά", "Αρούμπα"),
  CountryLocalization("au", "Αγγλικά", "Αυστραλία"),
  CountryLocalization("at", "Αγγλικά", "Αυστρία"),
  CountryLocalization("az", "Αζερμπαϊτζανικά", "Αζερμπαϊτζάν"),
  CountryLocalization("bs", "Αγγλικά", "Μπαχάμες"),
  CountryLocalization("bh", "Αραβικά", "Μπαχρέιν"),
  CountryLocalization("bd", "Βεγγαλικά", "Μπανγκλαντές"),
  CountryLocalization("bb", "Αγγλικά", "Μπαρμπέιντος"),
  CountryLocalization("by", "Λευκορωσικά", "Λευκορωσία"),
  CountryLocalization("be", "Γαλλικά", "Βέλγιο"),
  CountryLocalization("bz", "Αγγλικά", "Μπελίζ"),
  CountryLocalization("bj", "Γαλλικά", "Μπενίν"),
  CountryLocalization("bm", "Αγγλικά", "Βερμούδες"),
  CountryLocalization("bt", "Ντζόνγκχα", "Μπουτάν"),
  CountryLocalization("bo", "Ισπανικά", "Βολιβία"),
  CountryLocalization("ba", "Βοσνιακά", "Βοσνία - Ερζεγοβίνη"),
  CountryLocalization("bw", "Αγγλικά", "Μποτσουάνα"),
  CountryLocalization("br", "Πορτογαλικά", "Βραζιλία"),
  CountryLocalization("io", "Αγγλικά", "Βρετανικά Εδάφη Ινδικού Ωκεανού"),
  CountryLocalization("vg", "Αγγλικά", "Βρετανικές Παρθένες Νήσοι"),
  CountryLocalization("bn", "Μαλαισιανά", "Μπρουνέι"),
  CountryLocalization("bg", "Βουλγαρικά", "Βουλγαρία"),
  CountryLocalization("bf", "Γαλλικά", "Μπουρκίνα Φάσο"),
  CountryLocalization("bi", "Γαλλικά", "Μπουρούντι"),
  CountryLocalization("kh", "Χμερ", "Καμπότζη"),
  CountryLocalization("cm", "Μπάσα", "Καμερούν"),
  CountryLocalization("ca", "Γαλλικά", "Καναδάς"),
  CountryLocalization("ic", "Ισπανικά", "Κανάριοι Νήσοι"),
  CountryLocalization("cv", "Γλώσσα του Πράσινου Ακρωτηρίου", "Πράσινο Ακρωτήριο"),
  CountryLocalization("bq", "Ολλανδικά", "Ολλανδία Καραϊβικής"),
  CountryLocalization("ky", "Αγγλικά", "Νήσοι Κέιμαν"),
  CountryLocalization("cf", "Λινγκάλα", "Κεντροαφρικανική Δημοκρατία"),
  CountryLocalization("ea", "Ισπανικά", "Θέουτα και Μελίγια"),
  CountryLocalization("td", "Αραβικά", "Τσαντ"),
  CountryLocalization("cl", "Ισπανικά", "Χιλή"),
  CountryLocalization("cn", "Θιβετιανά", "Κίνα"),
  CountryLocalization("cx", "Αγγλικά", "Νήσος των Χριστουγέννων"),
  CountryLocalization("cc", "Αγγλικά", "Νήσοι Κόκος (Κίλινγκ)"),
  CountryLocalization("co", "Ισπανικά", "Κολομβία"),
  CountryLocalization("km", "Αραβικά", "Κομόρες"),
  CountryLocalization("cg", "Λινγκάλα", "Κονγκό - Μπραζαβίλ"),
  CountryLocalization("cd", "Σουαχίλι", "Κονγκό - Κινσάσα"),
  CountryLocalization("ck", "Αγγλικά", "Νήσοι Κουκ"),
  CountryLocalization("cr", "Ισπανικά", "Κόστα Ρίκα"),
  CountryLocalization("hr", "Κροατικά", "Κροατία"),
  CountryLocalization("cu", "Ισπανικά", "Κούβα"),
  CountryLocalization("cw", "Ολλανδικά", "Κουρασάο"),
  CountryLocalization("cy", "Αγγλικά", "Κύπρος"),
  CountryLocalization("cz", "Τσεχικά", "Τσεχία"),
  CountryLocalization("ci", "Γαλλικά", "Ακτή Ελεφαντοστού"),
  CountryLocalization("dk", "Αγγλικά", "Δανία"),
  CountryLocalization("dg", "Αγγλικά", "Ντιέγκο Γκαρσία"),
  CountryLocalization("dj", "Γαλλικά", "Τζιμπουτί"),
  CountryLocalization("dm", "Αγγλικά", "Ντομίνικα"),
  CountryLocalization("do", "Ισπανικά", "Δομινικανή Δημοκρατία"),
  CountryLocalization("ec", "Κέτσουα", "Ισημερινός"),
  CountryLocalization("eg", "Αραβικά", "Αίγυπτος"),
  CountryLocalization("sv", "Ισπανικά", "Ελ Σαλβαδόρ"),
  CountryLocalization("gq", "Ισπανικά", "Ισημερινή Γουινέα"),
  CountryLocalization("er", "Τιγκρινικά", "Ερυθραία"),
  CountryLocalization("ee", "Εσθονικά", "Εσθονία"),
  CountryLocalization("et", "Αμχαρικά", "Αιθιοπία"),
  CountryLocalization("fk", "Αγγλικά", "Νήσοι Φόκλαντ"),
  CountryLocalization("fo", "Φεροϊκά", "Νήσοι Φερόες"),
  CountryLocalization("fj", "Αγγλικά", "Φίτζι"),
  CountryLocalization("fi", "Σουηδικά", "Φινλανδία"),
  CountryLocalization("fr", "Γερμανικά Ελβετίας", "Γαλλία"),
  CountryLocalization("gf", "Γαλλικά", "Γαλλική Γουιάνα"),
  CountryLocalization("pf", "Γαλλικά", "Γαλλική Πολυνησία"),
  CountryLocalization("ga", "Γαλλικά", "Γκαμπόν"),
  CountryLocalization("gm", "Αγγλικά", "Γκάμπια"),
  CountryLocalization("ge", "Οσετικά", "Γεωργία"),
  CountryLocalization("de", "Κάτω Σορβικά", "Γερμανία"),
  CountryLocalization("gh", "Αγγλικά", "Γκάνα"),
  CountryLocalization("gi", "Αγγλικά", "Γιβραλτάρ"),
  CountryLocalization("gr", "Ελληνικά", "Ελλάδα"),
  CountryLocalization("gl", "Καλαάλισουτ", "Γροιλανδία"),
  CountryLocalization("gd", "Αγγλικά", "Γρενάδα"),
  CountryLocalization("gp", "Γαλλικά", "Γουαδελούπη"),
  CountryLocalization("gu", "Αγγλικά", "Γκουάμ"),
  CountryLocalization("gt", "Ισπανικά", "Γουατεμάλα"),
  CountryLocalization("gg", "Αγγλικά", "Γκέρνζι"),
  CountryLocalization("gn", "Γαλλικά", "Γουινέα"),
  CountryLocalization("gw", "Πορτογαλικά", "Γουινέα Μπισάου"),
  CountryLocalization("gy", "Αγγλικά", "Γουιάνα"),
  CountryLocalization("ht", "Γαλλικά", "Αϊτή"),
  CountryLocalization("hn", "Ισπανικά", "Ονδούρα"),
  CountryLocalization("hk", "Κινεζικά", "Χονγκ Κονγκ ΕΔΠ Κίνας"),
  CountryLocalization("hu", "Ουγγρικά", "Ουγγαρία"),
  CountryLocalization("is", "Ισλανδικά", "Ισλανδία"),
  CountryLocalization("in", "Νεπαλικά", "Ινδία"),
  CountryLocalization("id", "Ινδονησιακά", "Ινδονησία"),
  CountryLocalization("ir", "Περσικά", "Ιράν"),
  CountryLocalization("iq", "Βόρεια Λούρι", "Ιράκ"),
  CountryLocalization("ie", "Αγγλικά", "Ιρλανδία"),
  CountryLocalization("im", "Μανξ", "Νήσος του Μαν"),
  CountryLocalization("il", "Αγγλικά", "Ισραήλ"),
  CountryLocalization("it", "Γερμανικά", "Ιταλία"),
  CountryLocalization("jm", "Αγγλικά", "Τζαμάικα"),
  CountryLocalization("jp", "Ιαπωνικά", "Ιαπωνία"),
  CountryLocalization("je", "Αγγλικά", "Τζέρζι"),
  CountryLocalization("jo", "Αραβικά", "Ιορδανία"),
  CountryLocalization("kz", "Καζακικά", "Καζακστάν"),
  CountryLocalization("ke", "Σομαλικά", "Κένυα"),
  CountryLocalization("ki", "Αγγλικά", "Κιριμπάτι"),
  CountryLocalization("xk", "Σερβικά", "Κοσσυφοπέδιο"),
  CountryLocalization("kw", "Αραβικά", "Κουβέιτ"),
  CountryLocalization("kg", "Ρωσικά", "Κιργιστάν"),
  CountryLocalization("la", "Λαοτινά", "Λάος"),
  CountryLocalization("lv", "Λετονικά", "Λετονία"),
  CountryLocalization("lb", "Αραβικά", "Λίβανος"),
  CountryLocalization("ls", "Αγγλικά", "Λεσότο"),
  CountryLocalization("lr", "Αγγλικά", "Λιβερία"),
  CountryLocalization("ly", "Αραβικά", "Λιβύη"),
  CountryLocalization("li", "Γερμανικά Ελβετίας", "Λιχτενστάιν"),
  CountryLocalization("lt", "Λιθουανικά", "Λιθουανία"),
  CountryLocalization("lu", "Λουξεμβουργιανά", "Λουξεμβούργο"),
  CountryLocalization("mo", "Πορτογαλικά", "Μακάο ΕΔΠ Κίνας"),
  CountryLocalization("mk", "Αλβανικά", "Πρώην Γιουγκοσλαβική Δημοκρατία της Μακεδονίας"),
  CountryLocalization("mg", "Γαλλικά", "Μαδαγασκάρη"),
  CountryLocalization("mw", "Αγγλικά", "Μαλάουι"),
  CountryLocalization("my", "Ταμιλικά", "Μαλαισία"),
  CountryLocalization("ml", "Γαλλικά", "Μάλι"),
  CountryLocalization("mt", "Αγγλικά", "Μάλτα"),
  CountryLocalization("mh", "Αγγλικά", "Νήσοι Μάρσαλ"),
  CountryLocalization("mq", "Γαλλικά", "Μαρτινίκα"),
  CountryLocalization("mr", "Αραβικά", "Μαυριτανία"),
  CountryLocalization("mu", "Μορισιέν", "Μαυρίκιος"),
  CountryLocalization("yt", "Γαλλικά", "Μαγιότ"),
  CountryLocalization("mx", "Ισπανικά", "Μεξικό"),
  CountryLocalization("fm", "Αγγλικά", "Μικρονησία"),
  CountryLocalization("md", "Ρωσικά", "Μολδαβία"),
  CountryLocalization("mc", "Γαλλικά", "Μονακό"),
  CountryLocalization("mn", "Μογγολικά", "Μογγολία"),
  CountryLocalization("me", "Σερβικά", "Μαυροβούνιο"),
  CountryLocalization("ms", "Αγγλικά", "Μονσεράτ"),
  CountryLocalization("ma", "Ταμαζίτ Κεντρικού Μαρόκο", "Μαρόκο"),
  CountryLocalization("mz", "Μακούβα-Μέτο", "Μοζαμβίκη"),
  CountryLocalization("mm", "Βιρμανικά", "Μιανμάρ (Βιρμανία)"),
  CountryLocalization("na", "Αγγλικά", "Ναμίμπια"),
  CountryLocalization("nr", "Αγγλικά", "Ναουρού"),
  CountryLocalization("np", "Νεπαλικά", "Νεπάλ"),
  CountryLocalization("nl", "Αγγλικά", "Ολλανδία"),
  CountryLocalization("nc", "Γαλλικά", "Νέα Καληδονία"),
  CountryLocalization("nz", "Αγγλικά", "Νέα Ζηλανδία"),
  CountryLocalization("ni", "Ισπανικά", "Νικαράγουα"),
  CountryLocalization("ne", "Χάουσα", "Νίγηρας"),
  CountryLocalization("ng", "Χάουσα", "Νιγηρία"),
  CountryLocalization("nu", "Αγγλικά", "Νιούε"),
  CountryLocalization("nf", "Αγγλικά", "Νήσος Νόρφολκ"),
  CountryLocalization("kp", "Κορεατικά", "Βόρεια Κορέα"),
  CountryLocalization("mp", "Αγγλικά", "Νήσοι Βόρειες Μαριάνες"),
  CountryLocalization("no", "Βόρεια Σάμι", "Νορβηγία"),
  CountryLocalization("om", "Αραβικά", "Ομάν"),
  CountryLocalization("pk", "Αγγλικά", "Πακιστάν"),
  CountryLocalization("pw", "Αγγλικά", "Παλάου"),
  CountryLocalization("ps", "Αραβικά", "Παλαιστινιακά Εδάφη"),
  CountryLocalization("pa", "Ισπανικά", "Παναμάς"),
  CountryLocalization("pg", "Αγγλικά", "Παπούα Νέα Γουινέα"),
  CountryLocalization("py", "Ισπανικά", "Παραγουάη"),
  CountryLocalization("pe", "Ισπανικά", "Περού"),
  CountryLocalization("ph", "Φιλιππινικά", "Φιλιππίνες"),
  CountryLocalization("pn", "Αγγλικά", "Νήσοι Πίτκερν"),
  CountryLocalization("pl", "Πολωνικά", "Πολωνία"),
  CountryLocalization("pt", "Πορτογαλικά", "Πορτογαλία"),
  CountryLocalization("pr", "Αγγλικά", "Πουέρτο Ρίκο"),
  CountryLocalization("qa", "Αραβικά", "Κατάρ"),
  CountryLocalization("ro", "Ρουμανικά", "Ρουμανία"),
  CountryLocalization("ru", "Ταταρικά", "Ρωσία"),
  CountryLocalization("rw", "Αγγλικά", "Ρουάντα"),
  CountryLocalization("re", "Γαλλικά", "Ρεϊνιόν"),
  CountryLocalization("ws", "Αγγλικά", "Σαμόα"),
  CountryLocalization("sm", "Ιταλικά", "Άγιος Μαρίνος"),
  CountryLocalization("sa", "Αραβικά", "Σαουδική Αραβία"),
  CountryLocalization("sn", "Γαλλικά", "Σενεγάλη"),
  CountryLocalization("rs", "Σερβικά", "Σερβία"),
  CountryLocalization("cs", "Σερβικά", "Σερβία και Μαυροβούνιο"),
  CountryLocalization("sc", "Γαλλικά", "Σεϋχέλλες"),
  CountryLocalization("sl", "Αγγλικά", "Σιέρα Λεόνε"),
  CountryLocalization("sg", "Ταμιλικά", "Σιγκαπούρη"),
  CountryLocalization("sx", "Αγγλικά", "Άγιος Μαρτίνος (Ολλανδικό τμήμα)"),
  CountryLocalization("sk", "Σλοβακικά", "Σλοβακία"),
  CountryLocalization("si", "Σλοβενικά", "Σλοβενία"),
  CountryLocalization("sb", "Αγγλικά", "Νήσοι Σολομώντος"),
  CountryLocalization("so", "Αραβικά", "Σομαλία"),
  CountryLocalization("za", "Αγγλικά", "Νότια Αφρική"),
  CountryLocalization("kr", "Κορεατικά", "Νότια Κορέα"),
  CountryLocalization("ss", "Νούερ", "Νότιο Σουδάν"),
  CountryLocalization("es", "Ισπανικά", "Ισπανία"),
  CountryLocalization("lk", "Ταμιλικά", "Σρι Λάνκα"),
  CountryLocalization("bl", "Γαλλικά", "Άγιος Βαρθολομαίος"),
  CountryLocalization("sh", "Αγγλικά", "Αγία Ελένη"),
  CountryLocalization("kn", "Αγγλικά", "Σεν Κιτς και Νέβις"),
  CountryLocalization("lc", "Αγγλικά", "Αγία Λουκία"),
  CountryLocalization("mf", "Γαλλικά", "Άγιος Μαρτίνος (Γαλλικό τμήμα)"),
  CountryLocalization("pm", "Γαλλικά", "Σεν Πιερ και Μικελόν"),
  CountryLocalization("vc", "Αγγλικά", "Άγιος Βικέντιος και Γρεναδίνες"),
  CountryLocalization("sd", "Αραβικά", "Σουδάν"),
  CountryLocalization("sr", "Ολλανδικά", "Σουρινάμ"),
  CountryLocalization("sj", "Νορβηγικά Μποκμάλ", "Σβάλμπαρντ και Γιαν Μαγιέν"),
  CountryLocalization("sz", "Αγγλικά", "Σουαζιλάνδη"),
  CountryLocalization("se", "Σουηδικά", "Σουηδία"),
  CountryLocalization("ch", "Γερμανικά Ελβετίας", "Ελβετία"),
  CountryLocalization("sy", "Αραβικά", "Συρία"),
  CountryLocalization("st", "Πορτογαλικά", "Σάο Τομέ και Πρίνσιπε"),
  CountryLocalization("tw", "Κινεζικά", "Ταϊβάν"),
  CountryLocalization("tj", "Τατζικικά", "Τατζικιστάν"),
  CountryLocalization("tz", "Μακόντε", "Τανζανία"),
  CountryLocalization("th", "Ταϊλανδικά", "Ταϊλάνδη"),
  CountryLocalization("tl", "Πορτογαλικά", "Τιμόρ-Λέστε"),
  CountryLocalization("tg", "Γαλλικά", "Τόγκο"),
  CountryLocalization("tk", "Αγγλικά", "Τοκελάου"),
  CountryLocalization("to", "Τονγκανικά", "Τόνγκα"),
  CountryLocalization("tt", "Αγγλικά", "Τρινιντάντ και Τομπάγκο"),
  CountryLocalization("tn", "Γαλλικά", "Τυνησία"),
  CountryLocalization("tr", "Τουρκικά", "Τουρκία"),
  CountryLocalization("tm", "Τουρκμενικά", "Τουρκμενιστάν"),
  CountryLocalization("tc", "Αγγλικά", "Νήσοι Τερκς και Κάικος"),
  CountryLocalization("tv", "Αγγλικά", "Τουβαλού"),
  CountryLocalization("um", "Αγγλικά", "Απομακρυσμένες Νησίδες ΗΠΑ"),
  CountryLocalization("vi", "Αγγλικά", "Αμερικανικές Παρθένες Νήσοι"),
  CountryLocalization("ug", "Σουαχίλι", "Ουγκάντα"),
  CountryLocalization("ua", "Ουκρανικά", "Ουκρανία"),
  CountryLocalization("ae", "Αραβικά", "Ηνωμένα Αραβικά Εμιράτα"),
  CountryLocalization("gb", "Αγγλικά", "Ηνωμένο Βασίλειο"),
  CountryLocalization("us", "Λακότα", "Ηνωμένες Πολιτείες"),
  CountryLocalization("uy", "Ισπανικά", "Ουρουγουάη"),
  CountryLocalization("uz", "Ουζμπεκικά", "Ουζμπεκιστάν"),
  CountryLocalization("vu", "Γαλλικά", "Βανουάτου"),
  CountryLocalization("va", "Ιταλικά", "Βατικανό"),
  CountryLocalization("ve", "Ισπανικά", "Βενεζουέλα"),
  CountryLocalization("vn", "Βιετναμικά", "Βιετνάμ"),
  CountryLocalization("wf", "Γαλλικά", "Ουάλις και Φουτούνα"),
  CountryLocalization("eh", "Αραβικά", "Δυτική Σαχάρα"),
  CountryLocalization("ye", "Αραβικά", "Υεμένη"),
  CountryLocalization("zm", "Αγγλικά", "Ζάμπια"),
  CountryLocalization("zw", "Βόρεια Ντεμπέλε", "Ζιμπάμπουε"),
  CountryLocalization("ax", "Σουηδικά", "Νήσοι Όλαντ"),
)
