/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot.atlas.extended

import dev.teogor.xenoglot.atlas.CountryLocalization
import kotlin.collections.List

/**
 * Holds the internal list of country-language mappings used for lookups within the package for
 * language code hy.
 *
 * This property contains a hardcoded list of [CountryLocalization] objects, each representing
 * a country and its associated official languages. This list is used by [CountryLanguageRegistry]
 * to provide access to country-language data and should not be modified directly.
 *
 * @see CountryLocalization
 * @see CountryLanguageRegistry
 */
internal val _countryLanguageMappings_hy: List<CountryLocalization> = listOf(
  CountryLocalization("af", "պարսկերեն", "Աֆղանստան"),
  CountryLocalization("al", "ալբաներեն", "Ալբանիա"),
  CountryLocalization("dz", "ֆրանսերեն", "Ալժիր"),
  CountryLocalization("as", "անգլերեն", "Ամերիկյան Սամոա"),
  CountryLocalization("ad", "կատալաներեն", "Անդորրա"),
  CountryLocalization("ao", "լինգալա", "Անգոլա"),
  CountryLocalization("ai", "անգլերեն", "Անգուիլա"),
  CountryLocalization("ag", "անգլերեն", "Անտիգուա և Բարբուդա"),
  CountryLocalization("ar", "իսպաներեն", "Արգենտինա"),
  CountryLocalization("am", "հայերեն", "Հայաստան"),
  CountryLocalization("aw", "հոլանդերեն", "Արուբա"),
  CountryLocalization("au", "անգլերեն", "Ավստրալիա"),
  CountryLocalization("at", "անգլերեն", "Ավստրիա"),
  CountryLocalization("az", "ադրբեջաներեն", "Ադրբեջան"),
  CountryLocalization("bs", "անգլերեն", "Բահամաներ"),
  CountryLocalization("bh", "արաբերեն", "Բահրեյն"),
  CountryLocalization("bd", "բենգալերեն", "Բանգլադեշ"),
  CountryLocalization("bb", "անգլերեն", "Բարբադոս"),
  CountryLocalization("by", "բելառուսերեն", "Բելառուս"),
  CountryLocalization("be", "ֆրանսերեն", "Բելգիա"),
  CountryLocalization("bz", "անգլերեն", "Բելիզ"),
  CountryLocalization("bj", "ֆրանսերեն", "Բենին"),
  CountryLocalization("bm", "անգլերեն", "Բերմուդներ"),
  CountryLocalization("bt", "ջոնգքհա", "Բութան"),
  CountryLocalization("bo", "իսպաներեն", "Բոլիվիա"),
  CountryLocalization("ba", "բոսնիերեն", "Բոսնիա և Հերցեգովինա"),
  CountryLocalization("bw", "անգլերեն", "Բոթսվանա"),
  CountryLocalization("br", "պորտուգալերեն", "Բրազիլիա"),
  CountryLocalization("io", "անգլերեն", "Բրիտանական Տարածք Հնդկական Օվկիանոսում"),
  CountryLocalization("vg", "անգլերեն", "Բրիտանական Վիրջինյան կղզիներ"),
  CountryLocalization("bn", "մալայերեն", "Բրունեյ"),
  CountryLocalization("bg", "բուլղարերեն", "Բուլղարիա"),
  CountryLocalization("bf", "ֆրանսերեն", "Բուրկինա Ֆասո"),
  CountryLocalization("bi", "ֆրանսերեն", "Բուրունդի"),
  CountryLocalization("kh", "քմերերեն", "Կամբոջա"),
  CountryLocalization("cm", "բասաա", "Կամերուն"),
  CountryLocalization("ca", "ֆրանսերեն", "Կանադա"),
  CountryLocalization("ic", "իսպաներեն", "Կանարյան կղզիներ"),
  CountryLocalization("cv", "կաբուվերդերեն", "Կաբո Վերդե"),
  CountryLocalization("bq", "հոլանդերեն", "Կարիբյան Նիդեռլանդներ"),
  CountryLocalization("ky", "անգլերեն", "Կայման կղզիներ"),
  CountryLocalization("cf", "լինգալա", "Կենտրոնական Աֆրիկյան Հանրապետություն"),
  CountryLocalization("ea", "իսպաներեն", "Սեուտա և Մելիլյա"),
  CountryLocalization("td", "արաբերեն", "Չադ"),
  CountryLocalization("cl", "իսպաներեն", "Չիլի"),
  CountryLocalization("cn", "տիբեթերեն", "Չինաստան"),
  CountryLocalization("cx", "անգլերեն", "Սուրբ Ծննդյան կղզի"),
  CountryLocalization("cc", "անգլերեն", "Կոկոսյան (Քիլինգ) կղզիներ"),
  CountryLocalization("co", "իսպաներեն", "Կոլումբիա"),
  CountryLocalization("km", "արաբերեն", "Կոմորյան կղզիներ"),
  CountryLocalization("cg", "լինգալա", "Կոնգո - Բրազավիլ"),
  CountryLocalization("cd", "սուահիլի", "Կոնգո - Կինշասա"),
  CountryLocalization("ck", "անգլերեն", "Կուկի կղզիներ"),
  CountryLocalization("cr", "իսպաներեն", "Կոստա Ռիկա"),
  CountryLocalization("hr", "խորվաթերեն", "Խորվաթիա"),
  CountryLocalization("cu", "իսպաներեն", "Կուբա"),
  CountryLocalization("cw", "հոլանդերեն", "Կյուրասաո"),
  CountryLocalization("cy", "անգլերեն", "Կիպրոս"),
  CountryLocalization("cz", "չեխերեն", "Չեխիա"),
  CountryLocalization("ci", "ֆրանսերեն", "Կոտ դ’Իվուար"),
  CountryLocalization("dk", "անգլերեն", "Դանիա"),
  CountryLocalization("dg", "անգլերեն", "Դիեգո Գարսիա"),
  CountryLocalization("dj", "ֆրանսերեն", "Ջիբութի"),
  CountryLocalization("dm", "անգլերեն", "Դոմինիկա"),
  CountryLocalization("do", "իսպաներեն", "Դոմինիկյան Հանրապետություն"),
  CountryLocalization("ec", "կեչուա", "Էկվադոր"),
  CountryLocalization("eg", "արաբերեն", "Եգիպտոս"),
  CountryLocalization("sv", "իսպաներեն", "Սալվադոր"),
  CountryLocalization("gq", "իսպաներեն", "Հասարակածային Գվինեա"),
  CountryLocalization("er", "տիգրինյա", "Էրիթրեա"),
  CountryLocalization("ee", "էստոներեն", "Էստոնիա"),
  CountryLocalization("et", "ամհարերեն", "Եթովպիա"),
  CountryLocalization("fk", "անգլերեն", "Ֆոլքլենդյան կղզիներ"),
  CountryLocalization("fo", "ֆարյորերեն", "Ֆարերյան կղզիներ"),
  CountryLocalization("fj", "անգլերեն", "Ֆիջի"),
  CountryLocalization("fi", "շվեդերեն", "Ֆինլանդիա"),
  CountryLocalization("fr", "շվեյցարական գերմաներեն", "Ֆրանսիա"),
  CountryLocalization("gf", "ֆրանսերեն", "Ֆրանսիական Գվիանա"),
  CountryLocalization("pf", "ֆրանսերեն", "Ֆրանսիական Պոլինեզիա"),
  CountryLocalization("ga", "ֆրանսերեն", "Գաբոն"),
  CountryLocalization("gm", "անգլերեն", "Գամբիա"),
  CountryLocalization("ge", "օսերեն", "Վրաստան"),
  CountryLocalization("de", "ստորին սորբերեն", "Գերմանիա"),
  CountryLocalization("gh", "անգլերեն", "Գանա"),
  CountryLocalization("gi", "անգլերեն", "Ջիբրալթար"),
  CountryLocalization("gr", "հունարեն", "Հունաստան"),
  CountryLocalization("gl", "կալաալիսուտ", "Գրենլանդիա"),
  CountryLocalization("gd", "անգլերեն", "Գրենադա"),
  CountryLocalization("gp", "ֆրանսերեն", "Գվադելուպա"),
  CountryLocalization("gu", "անգլերեն", "Գուամ"),
  CountryLocalization("gt", "իսպաներեն", "Գվատեմալա"),
  CountryLocalization("gg", "անգլերեն", "Գերնսի"),
  CountryLocalization("gn", "ֆրանսերեն", "Գվինեա"),
  CountryLocalization("gw", "պորտուգալերեն", "Գվինեա-Բիսաու"),
  CountryLocalization("gy", "անգլերեն", "Գայանա"),
  CountryLocalization("ht", "ֆրանսերեն", "Հայիթի"),
  CountryLocalization("hn", "իսպաներեն", "Հոնդուրաս"),
  CountryLocalization("hk", "չինարեն", "Հոնկոնգի ՀՎՇ"),
  CountryLocalization("hu", "հունգարերեն", "Հունգարիա"),
  CountryLocalization("is", "իսլանդերեն", "Իսլանդիա"),
  CountryLocalization("in", "նեպալերեն", "Հնդկաստան"),
  CountryLocalization("id", "Indonesian", "Ինդոնեզիա"),
  CountryLocalization("ir", "պարսկերեն", "Իրան"),
  CountryLocalization("iq", "հյուսիսային լուրիերեն", "Իրաք"),
  CountryLocalization("ie", "անգլերեն", "Իռլանդիա"),
  CountryLocalization("im", "մեներեն", "Մեն կղզի"),
  CountryLocalization("il", "անգլերեն", "Իսրայել"),
  CountryLocalization("it", "գերմաներեն", "Իտալիա"),
  CountryLocalization("jm", "անգլերեն", "Ճամայկա"),
  CountryLocalization("jp", "ճապոներեն", "Ճապոնիա"),
  CountryLocalization("je", "անգլերեն", "Ջերսի"),
  CountryLocalization("jo", "արաբերեն", "Հորդանան"),
  CountryLocalization("kz", "ղազախերեն", "Ղազախստան"),
  CountryLocalization("ke", "սոմալիերեն", "Քենիա"),
  CountryLocalization("ki", "անգլերեն", "Կիրիբատի"),
  CountryLocalization("xk", "սերբերեն", "Կոսովո"),
  CountryLocalization("kw", "արաբերեն", "Քուվեյթ"),
  CountryLocalization("kg", "ռուսերեն", "Ղրղզստան"),
  CountryLocalization("la", "լաոսերեն", "Լաոս"),
  CountryLocalization("lv", "լատվիերեն", "Լատվիա"),
  CountryLocalization("lb", "արաբերեն", "Լիբանան"),
  CountryLocalization("ls", "անգլերեն", "Լեսոտո"),
  CountryLocalization("lr", "անգլերեն", "Լիբերիա"),
  CountryLocalization("ly", "արաբերեն", "Լիբիա"),
  CountryLocalization("li", "շվեյցարական գերմաներեն", "Լիխտենշտեյն"),
  CountryLocalization("lt", "լիտվերեն", "Լիտվա"),
  CountryLocalization("lu", "լյուքսեմբուրգերեն", "Լյուքսեմբուրգ"),
  CountryLocalization("mo", "պորտուգալերեն", "Չինաստանի Մակաո ՀՎՇ"),
  CountryLocalization("mk", "ալբաներեն", "Մակեդոնիա"),
  CountryLocalization("mg", "ֆրանսերեն", "Մադագասկար"),
  CountryLocalization("mw", "անգլերեն", "Մալավի"),
  CountryLocalization("my", "թամիլերեն", "Մալայզիա"),
  CountryLocalization("ml", "ֆրանսերեն", "Մալի"),
  CountryLocalization("mt", "անգլերեն", "Մալթա"),
  CountryLocalization("mh", "անգլերեն", "Մարշալյան կղզիներ"),
  CountryLocalization("mq", "ֆրանսերեն", "Մարտինիկա"),
  CountryLocalization("mr", "արաբերեն", "Մավրիտանիա"),
  CountryLocalization("mu", "մորիսյեն", "Մավրիկիոս"),
  CountryLocalization("yt", "ֆրանսերեն", "Մայոտ"),
  CountryLocalization("mx", "իսպաներեն", "Մեքսիկա"),
  CountryLocalization("fm", "անգլերեն", "Միկրոնեզիա"),
  CountryLocalization("md", "ռուսերեն", "Մոլդովա"),
  CountryLocalization("mc", "ֆրանսերեն", "Մոնակո"),
  CountryLocalization("mn", "մոնղոլերեն", "Մոնղոլիա"),
  CountryLocalization("me", "սերբերեն", "Չեռնոգորիա"),
  CountryLocalization("ms", "անգլերեն", "Մոնսեռատ"),
  CountryLocalization("ma", "կենտրոնատլասյան թամազիղտ", "Մարոկկո"),
  CountryLocalization("mz", "մաքուա-մետտո", "Մոզամբիկ"),
  CountryLocalization("mm", "բիրմայերեն", "Մյանմա (Բիրմա)"),
  CountryLocalization("na", "անգլերեն", "Նամիբիա"),
  CountryLocalization("nr", "անգլերեն", "Նաուրու"),
  CountryLocalization("np", "նեպալերեն", "Նեպալ"),
  CountryLocalization("nl", "անգլերեն", "Նիդեռլանդներ"),
  CountryLocalization("nc", "ֆրանսերեն", "Նոր Կալեդոնիա"),
  CountryLocalization("nz", "անգլերեն", "Նոր Զելանդիա"),
  CountryLocalization("ni", "իսպաներեն", "Նիկարագուա"),
  CountryLocalization("ne", "հաուսա", "Նիգեր"),
  CountryLocalization("ng", "հաուսա", "Նիգերիա"),
  CountryLocalization("nu", "անգլերեն", "Նիուե"),
  CountryLocalization("nf", "անգլերեն", "Նորֆոլկ կղզի"),
  CountryLocalization("kp", "կորեերեն", "Հյուսիսային Կորեա"),
  CountryLocalization("mp", "անգլերեն", "Հյուսիսային Մարիանյան կղզիներ"),
  CountryLocalization("no", "հյուսիսային սաամի", "Նորվեգիա"),
  CountryLocalization("om", "արաբերեն", "Օման"),
  CountryLocalization("pk", "անգլերեն", "Պակիստան"),
  CountryLocalization("pw", "անգլերեն", "Պալաու"),
  CountryLocalization("ps", "արաբերեն", "Պաղեստինյան տարածքներ"),
  CountryLocalization("pa", "իսպաներեն", "Պանամա"),
  CountryLocalization("pg", "անգլերեն", "Պապուա Նոր Գվինեա"),
  CountryLocalization("py", "իսպաներեն", "Պարագվայ"),
  CountryLocalization("pe", "իսպաներեն", "Պերու"),
  CountryLocalization("ph", "ֆիլիպիներեն", "Ֆիլիպիններ"),
  CountryLocalization("pn", "անգլերեն", "Պիտկեռն կղզիներ"),
  CountryLocalization("pl", "լեհերեն", "Լեհաստան"),
  CountryLocalization("pt", "պորտուգալերեն", "Պորտուգալիա"),
  CountryLocalization("pr", "անգլերեն", "Պուերտո Ռիկո"),
  CountryLocalization("qa", "արաբերեն", "Կատար"),
  CountryLocalization("ro", "ռումիներեն", "Ռումինիա"),
  CountryLocalization("ru", "թաթարերեն", "Ռուսաստան"),
  CountryLocalization("rw", "անգլերեն", "Ռուանդա"),
  CountryLocalization("re", "ֆրանսերեն", "Ռեյունիոն"),
  CountryLocalization("ws", "անգլերեն", "Սամոա"),
  CountryLocalization("sm", "իտալերեն", "Սան Մարինո"),
  CountryLocalization("sa", "արաբերեն", "Սաուդյան Արաբիա"),
  CountryLocalization("sn", "ֆրանսերեն", "Սենեգալ"),
  CountryLocalization("rs", "սերբերեն", "Սերբիա"),
  CountryLocalization("cs", "սերբերեն", "Serbia and Montenegro"),
  CountryLocalization("sc", "ֆրանսերեն", "Սեյշելներ"),
  CountryLocalization("sl", "անգլերեն", "Սիեռա Լեոնե"),
  CountryLocalization("sg", "թամիլերեն", "Սինգապուր"),
  CountryLocalization("sx", "անգլերեն", "Սինտ Մարտեն"),
  CountryLocalization("sk", "սլովակերեն", "Սլովակիա"),
  CountryLocalization("si", "սլովեներեն", "Սլովենիա"),
  CountryLocalization("sb", "անգլերեն", "Սողոմոնյան կղզիներ"),
  CountryLocalization("so", "արաբերեն", "Սոմալի"),
  CountryLocalization("za", "անգլերեն", "Հարավաֆրիկյան Հանրապետություն"),
  CountryLocalization("kr", "կորեերեն", "Հարավային Կորեա"),
  CountryLocalization("ss", "նուեր", "Հարավային Սուդան"),
  CountryLocalization("es", "իսպաներեն", "Իսպանիա"),
  CountryLocalization("lk", "թամիլերեն", "Շրի Լանկա"),
  CountryLocalization("bl", "ֆրանսերեն", "Սուրբ Բարդուղիմեոս"),
  CountryLocalization("sh", "անգլերեն", "Սուրբ Հեղինեի կղզի"),
  CountryLocalization("kn", "անգլերեն", "Սենթ Քիտս և Նևիս"),
  CountryLocalization("lc", "անգլերեն", "Սենթ Լյուսիա"),
  CountryLocalization("mf", "ֆրանսերեն", "Սեն Մարտեն"),
  CountryLocalization("pm", "ֆրանսերեն", "Սեն Պիեռ և Միքելոն"),
  CountryLocalization("vc", "անգլերեն", "Սենթ Վինսենթ և Գրենադիններ"),
  CountryLocalization("sd", "արաբերեն", "Սուդան"),
  CountryLocalization("sr", "հոլանդերեն", "Սուրինամ"),
  CountryLocalization("sj", "գրքային նորվեգերեն", "Սվալբարդ և Յան Մայեն"),
  CountryLocalization("sz", "անգլերեն", "Սվազիլենդ"),
  CountryLocalization("se", "շվեդերեն", "Շվեդիա"),
  CountryLocalization("ch", "շվեյցարական գերմաներեն", "Շվեյցարիա"),
  CountryLocalization("sy", "արաբերեն", "Սիրիա"),
  CountryLocalization("st", "պորտուգալերեն", "Սան Տոմե և Փրինսիպի"),
  CountryLocalization("tw", "չինարեն", "Թայվան"),
  CountryLocalization("tj", "տաջիկերեն", "Տաջիկստան"),
  CountryLocalization("tz", "մակոնդե", "Տանզանիա"),
  CountryLocalization("th", "թայերեն", "Թայլանդ"),
  CountryLocalization("tl", "պորտուգալերեն", "Թիմոր Լեշտի"),
  CountryLocalization("tg", "ֆրանսերեն", "Տոգո"),
  CountryLocalization("tk", "անգլերեն", "Տոկելաու"),
  CountryLocalization("to", "տոնգերեն", "Տոնգա"),
  CountryLocalization("tt", "անգլերեն", "Տրինիդադ և Տոբագո"),
  CountryLocalization("tn", "ֆրանսերեն", "Թունիս"),
  CountryLocalization("tr", "թուրքերեն", "Թուրքիա"),
  CountryLocalization("tm", "թուրքմեներեն", "Թուրքմենստան"),
  CountryLocalization("tc", "անգլերեն", "Թըրքս և Կայկոս կղզիներ"),
  CountryLocalization("tv", "անգլերեն", "Տուվալու"),
  CountryLocalization("um", "անգլերեն", "Արտաքին կղզիներ (ԱՄՆ)"),
  CountryLocalization("vi", "անգլերեն", "ԱՄՆ Վիրջինյան կղզիներ"),
  CountryLocalization("ug", "սուահիլի", "Ուգանդա"),
  CountryLocalization("ua", "ուկրաիներեն", "Ուկրաինա"),
  CountryLocalization("ae", "արաբերեն", "Արաբական Միացյալ Էմիրություններ"),
  CountryLocalization("gb", "անգլերեն", "Միացյալ Թագավորություն"),
  CountryLocalization("us", "լակոտա", "Միացյալ Նահանգներ"),
  CountryLocalization("uy", "իսպաներեն", "Ուրուգվայ"),
  CountryLocalization("uz", "ուզբեկերեն", "Ուզբեկստան"),
  CountryLocalization("vu", "ֆրանսերեն", "Վանուատու"),
  CountryLocalization("va", "իտալերեն", "Վատիկան"),
  CountryLocalization("ve", "իսպաներեն", "Վենեսուելա"),
  CountryLocalization("vn", "վիետնամերեն", "Վիետնամ"),
  CountryLocalization("wf", "ֆրանսերեն", "Ուոլիս և Ֆուտունա"),
  CountryLocalization("eh", "արաբերեն", "Արևմտյան Սահարա"),
  CountryLocalization("ye", "արաբերեն", "Եմեն"),
  CountryLocalization("zm", "անգլերեն", "Զամբիա"),
  CountryLocalization("zw", "հյուսիսային նդեբելե", "Զիմբաբվե"),
  CountryLocalization("ax", "շվեդերեն", "Ալանդյան կղզիներ"),
)
