/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot.atlas.extended

import dev.teogor.xenoglot.atlas.CountryLocalization
import kotlin.collections.List

/**
 * Holds the internal list of country-language mappings used for lookups within the package for
 * language code nus.
 *
 * This property contains a hardcoded list of [CountryLocalization] objects, each representing
 * a country and its associated official languages. This list is used by [CountryLanguageRegistry]
 * to provide access to country-language data and should not be modified directly.
 *
 * @see CountryLocalization
 * @see CountryLanguageRegistry
 */
internal val _countryLanguageMappings_nus: List<CountryLocalization> = listOf(
  CountryLocalization("af", "Thok perthiani", "Abganithtan"),
  CountryLocalization("al", "Albanian", "Albänia"),
  CountryLocalization("dz", "Thok pɔrɔthani", "Algeria"),
  CountryLocalization("as", "Thok liŋli̱thni", "Amerika thamow"),
  CountryLocalization("ad", "Catalan", "Andora"),
  CountryLocalization("ao", "Lingala", "Aŋgola"),
  CountryLocalization("ai", "Thok liŋli̱thni", "Aŋguɛla"),
  CountryLocalization("ag", "Thok liŋli̱thni", "Antiguaa kɛnɛ Barbuda"),
  CountryLocalization("ar", "Thok i̱thpaaniani", "Aɛrgentin"),
  CountryLocalization("am", "Armenian", "Aɛrmänia"),
  CountryLocalization("aw", "Thok da̱c", "Aruba"),
  CountryLocalization("au", "Thok liŋli̱thni", "Athɔra̱lia"),
  CountryLocalization("at", "Thok liŋli̱thni", "Athtɛria"),
  CountryLocalization("az", "Azerbaijani", "Adhe̱rbe̱ja̱n"),
  CountryLocalization("bs", "Thok liŋli̱thni", "Bämuɔth"),
  CountryLocalization("bh", "Thok Jalabni", "Ba̱reen"),
  CountryLocalization("bd", "Thok bängali", "Bengeladiec"),
  CountryLocalization("bb", "Thok liŋli̱thni", "Bärbadoth"),
  CountryLocalization("by", "Thok bälärutha", "Be̱lɛruth"),
  CountryLocalization("be", "Thok pɔrɔthani", "Be̱lgim"),
  CountryLocalization("bz", "Thok liŋli̱thni", "Bilidha"),
  CountryLocalization("bj", "Thok pɔrɔthani", "Be̱ni̱n"),
  CountryLocalization("bm", "Thok liŋli̱thni", "Be̱rmudaa"),
  CountryLocalization("bt", "Dzongkha", "Buta̱n"),
  CountryLocalization("bo", "Thok i̱thpaaniani", "Bulibia"),
  CountryLocalization("ba", "Bosnian", "Bothnia kɛnɛ ɣärgobinia"),
  CountryLocalization("bw", "Thok liŋli̱thni", "Bothiwaana"),
  CountryLocalization("br", "Thok puɔtigali", "Bäraadhiil"),
  CountryLocalization("io", "Thok liŋli̱thni", "Burutic ɣe̱ndian oce̱n"),
  CountryLocalization("vg", "Thok liŋli̱thni", "Burutic dhuɔ̱ɔ̱l be̱rgin"),
  CountryLocalization("bn", "Thok mayɛyni", "Burunɛy"),
  CountryLocalization("bg", "Thok bälga̱a̱riani", "Bulga̱a̱ria"),
  CountryLocalization("bf", "Thok pɔrɔthani", "Burkinɛ pa̱thu"),
  CountryLocalization("bi", "Thok pɔrɔthani", "Burundi"),
  CountryLocalization("kh", "Thok kameeri", "Kombodia"),
  CountryLocalization("cm", "Basaa", "Kɛmɛrun"),
  CountryLocalization("ca", "Thok pɔrɔthani", "Känɛda"),
  CountryLocalization("ic", "Thok i̱thpaaniani", "IC"),
  CountryLocalization("cv", "kea", "Kɛp bedi ɣa̱ylɛn"),
  CountryLocalization("bq", "Thok da̱c", "Caribbean Netherlands"),
  CountryLocalization("ky", "Thok liŋli̱thni", "Kaymɛn ɣa̱ylɛn"),
  CountryLocalization("cf", "Lingala", "Cɛntrɔl aprika repuɔblic"),
  CountryLocalization("ea", "Thok i̱thpaaniani", "EA"),
  CountryLocalization("td", "Thok Jalabni", "Ca̱d"),
  CountryLocalization("cl", "Thok i̱thpaaniani", "Cili̱"),
  CountryLocalization("cn", "Tibetan", "Cayna"),
  CountryLocalization("cx", "Thok liŋli̱thni", "Christmas Island"),
  CountryLocalization("cc", "Thok liŋli̱thni", "Cocos (Keeling) Islands"),
  CountryLocalization("co", "Thok i̱thpaaniani", "Kolombia"),
  CountryLocalization("km", "Thok Jalabni", "Komruth"),
  CountryLocalization("cg", "Lingala", "Kɔŋgɔ"),
  CountryLocalization("cd", "Swahili", "Congo - Kinshasa"),
  CountryLocalization("ck", "Thok liŋli̱thni", "Kuk ɣa̱ylɛn"),
  CountryLocalization("cr", "Thok i̱thpaaniani", "Kothtirika"),
  CountryLocalization("hr", "Croatian", "Korwaatia"),
  CountryLocalization("cu", "Thok i̱thpaaniani", "Cuba"),
  CountryLocalization("cw", "Thok da̱c", "Curaçao"),
  CountryLocalization("cy", "Thok liŋli̱thni", "Cyprus"),
  CountryLocalization("cz", "Thok cik", "Czechia"),
  CountryLocalization("ci", "Thok pɔrɔthani", "Kodibo̱o̱"),
  CountryLocalization("dk", "Thok liŋli̱thni", "Denmark"),
  CountryLocalization("dg", "Thok liŋli̱thni", "DG"),
  CountryLocalization("dj", "Thok pɔrɔthani", "Djibouti"),
  CountryLocalization("dm", "Thok liŋli̱thni", "Dominica"),
  CountryLocalization("do", "Thok i̱thpaaniani", "Dominican Republic"),
  CountryLocalization("ec", "Quechua", "Ecuador"),
  CountryLocalization("eg", "Thok Jalabni", "Egypt"),
  CountryLocalization("sv", "Thok i̱thpaaniani", "El Salvador"),
  CountryLocalization("gq", "Thok i̱thpaaniani", "Equatorial Guinea"),
  CountryLocalization("er", "Tigrinya", "Eritrea"),
  CountryLocalization("ee", "Estonian", "Estonia"),
  CountryLocalization("et", "Thok bunyni", "Ethiopia"),
  CountryLocalization("fk", "Thok liŋli̱thni", "Falkland Islands"),
  CountryLocalization("fo", "Faroese", "Faroe Islands"),
  CountryLocalization("fj", "Thok liŋli̱thni", "Fiji"),
  CountryLocalization("fi", "Thok i̱thwidicni", "Finland"),
  CountryLocalization("fr", "Swiss German", "France"),
  CountryLocalization("gf", "Thok pɔrɔthani", "French Guiana"),
  CountryLocalization("pf", "Thok pɔrɔthani", "French Polynesia"),
  CountryLocalization("ga", "Thok pɔrɔthani", "Gabon"),
  CountryLocalization("gm", "Thok liŋli̱thni", "Gambia"),
  CountryLocalization("ge", "Ossetic", "Georgia"),
  CountryLocalization("de", "Lower Sorbian", "Germany"),
  CountryLocalization("gh", "Thok liŋli̱thni", "Ghana"),
  CountryLocalization("gi", "Thok liŋli̱thni", "Gibraltar"),
  CountryLocalization("gr", "Thok girikni", "Greece"),
  CountryLocalization("gl", "Kalaallisut", "Greenland"),
  CountryLocalization("gd", "Thok liŋli̱thni", "Grenada"),
  CountryLocalization("gp", "Thok pɔrɔthani", "Guadeloupe"),
  CountryLocalization("gu", "Thok liŋli̱thni", "Guam"),
  CountryLocalization("gt", "Thok i̱thpaaniani", "Guatemala"),
  CountryLocalization("gg", "Thok liŋli̱thni", "Guernsey"),
  CountryLocalization("gn", "Thok pɔrɔthani", "Guinea"),
  CountryLocalization("gw", "Thok puɔtigali", "Guinea-Bissau"),
  CountryLocalization("gy", "Thok liŋli̱thni", "Guyana"),
  CountryLocalization("ht", "Thok pɔrɔthani", "Haiti"),
  CountryLocalization("hn", "Thok i̱thpaaniani", "Honduras"),
  CountryLocalization("hk", "Thok cayna", "Hong Kong SAR China"),
  CountryLocalization("hu", "Thok ɣänga̱a̱riɛni", "Hungary"),
  CountryLocalization("is", "Icelandic", "Iceland"),
  CountryLocalization("in", "Thok napalni", "India"),
  CountryLocalization("id", "Indonesian", "Indonesia"),
  CountryLocalization("ir", "Thok perthiani", "Iran"),
  CountryLocalization("iq", "lrc", "Iraq"),
  CountryLocalization("ie", "Thok liŋli̱thni", "Ireland"),
  CountryLocalization("im", "Manx", "Isle of Man"),
  CountryLocalization("il", "Thok liŋli̱thni", "Israel"),
  CountryLocalization("it", "Thok jarmani", "Italy"),
  CountryLocalization("jm", "Thok liŋli̱thni", "Jamaica"),
  CountryLocalization("jp", "Thok japanni", "Japan"),
  CountryLocalization("je", "Thok liŋli̱thni", "Jersey"),
  CountryLocalization("jo", "Thok Jalabni", "Jordan"),
  CountryLocalization("kz", "Kazakh", "Kazakhstan"),
  CountryLocalization("ke", "Thok thomaaliani", "Kenya"),
  CountryLocalization("ki", "Thok liŋli̱thni", "Kiribati"),
  CountryLocalization("xk", "Serbian", "XK"),
  CountryLocalization("kw", "Thok Jalabni", "Kuwait"),
  CountryLocalization("kg", "Thok ra̱ciaani", "Kyrgyzstan"),
  CountryLocalization("la", "Lao", "Laos"),
  CountryLocalization("lv", "Latvian", "Latvia"),
  CountryLocalization("lb", "Thok Jalabni", "Lebanon"),
  CountryLocalization("ls", "Thok liŋli̱thni", "Lesotho"),
  CountryLocalization("lr", "Thok liŋli̱thni", "Liberia"),
  CountryLocalization("ly", "Thok Jalabni", "Libya"),
  CountryLocalization("li", "Swiss German", "Liechtenstein"),
  CountryLocalization("lt", "Lithuanian", "Lithuania"),
  CountryLocalization("lu", "Luxembourgish", "Luxembourg"),
  CountryLocalization("mo", "Thok puɔtigali", "Macao SAR China"),
  CountryLocalization("mk", "Albanian", "North Macedonia"),
  CountryLocalization("mg", "Thok pɔrɔthani", "Madagascar"),
  CountryLocalization("mw", "Thok liŋli̱thni", "Malawi"),
  CountryLocalization("my", "Thok tamilni", "Malaysia"),
  CountryLocalization("ml", "Thok pɔrɔthani", "Mali"),
  CountryLocalization("mt", "Thok liŋli̱thni", "Malta"),
  CountryLocalization("mh", "Thok liŋli̱thni", "Marshall Islands"),
  CountryLocalization("mq", "Thok pɔrɔthani", "Martinique"),
  CountryLocalization("mr", "Thok Jalabni", "Mauritania"),
  CountryLocalization("mu", "mfe", "Mauritius"),
  CountryLocalization("yt", "Thok pɔrɔthani", "Mayotte"),
  CountryLocalization("mx", "Thok i̱thpaaniani", "Mexico"),
  CountryLocalization("fm", "Thok liŋli̱thni", "Micronesia"),
  CountryLocalization("md", "Thok ra̱ciaani", "Moldova"),
  CountryLocalization("mc", "Thok pɔrɔthani", "Monaco"),
  CountryLocalization("mn", "Mongolian", "Mongolia"),
  CountryLocalization("me", "Serbian", "Montenegro"),
  CountryLocalization("ms", "Thok liŋli̱thni", "Montserrat"),
  CountryLocalization("ma", "tzm", "Morocco"),
  CountryLocalization("mz", "mgh", "Mozambique"),
  CountryLocalization("mm", "Thok bormi̱thni", "Myanmar (Burma)"),
  CountryLocalization("na", "Thok liŋli̱thni", "Namibia"),
  CountryLocalization("nr", "Thok liŋli̱thni", "Nauru"),
  CountryLocalization("np", "Thok napalni", "Nepal"),
  CountryLocalization("nl", "Thok liŋli̱thni", "Netherlands"),
  CountryLocalization("nc", "Thok pɔrɔthani", "New Caledonia"),
  CountryLocalization("nz", "Thok liŋli̱thni", "New Zealand"),
  CountryLocalization("ni", "Thok i̱thpaaniani", "Nicaragua"),
  CountryLocalization("ne", "Thok ɣowthani", "Niger"),
  CountryLocalization("ng", "Thok ɣowthani", "Nigeria"),
  CountryLocalization("nu", "Thok liŋli̱thni", "Niue"),
  CountryLocalization("nf", "Thok liŋli̱thni", "Norfolk Island"),
  CountryLocalization("kp", "Thok kuriani", "North Korea"),
  CountryLocalization("mp", "Thok liŋli̱thni", "Northern Mariana Islands"),
  CountryLocalization("no", "Northern Sami", "Norway"),
  CountryLocalization("om", "Thok Jalabni", "Oman"),
  CountryLocalization("pk", "Thok liŋli̱thni", "Pakistan"),
  CountryLocalization("pw", "Thok liŋli̱thni", "Palau"),
  CountryLocalization("ps", "Thok Jalabni", "Palestinian Territories"),
  CountryLocalization("pa", "Thok i̱thpaaniani", "Panama"),
  CountryLocalization("pg", "Thok liŋli̱thni", "Papua New Guinea"),
  CountryLocalization("py", "Thok i̱thpaaniani", "Paraguay"),
  CountryLocalization("pe", "Thok i̱thpaaniani", "Peru"),
  CountryLocalization("ph", "Filipino", "Philippines"),
  CountryLocalization("pn", "Thok liŋli̱thni", "Pitcairn Islands"),
  CountryLocalization("pl", "Thok pölicni", "Poland"),
  CountryLocalization("pt", "Thok puɔtigali", "Portugal"),
  CountryLocalization("pr", "Thok liŋli̱thni", "Puerto Rico"),
  CountryLocalization("qa", "Thok Jalabni", "Qatar"),
  CountryLocalization("ro", "Thok ji̱ röm", "Romania"),
  CountryLocalization("ru", "Tatar", "Russia"),
  CountryLocalization("rw", "Thok liŋli̱thni", "Rwanda"),
  CountryLocalization("re", "Thok pɔrɔthani", "Réunion"),
  CountryLocalization("ws", "Thok liŋli̱thni", "Samoa"),
  CountryLocalization("sm", "Thok i̱taliani", "San Marino"),
  CountryLocalization("sa", "Thok Jalabni", "Saudi Arabia"),
  CountryLocalization("sn", "Thok pɔrɔthani", "Senegal"),
  CountryLocalization("rs", "Serbian", "Serbia"),
  CountryLocalization("cs", "Serbian", "Serbia and Montenegro"),
  CountryLocalization("sc", "Thok pɔrɔthani", "Seychelles"),
  CountryLocalization("sl", "Thok liŋli̱thni", "Sierra Leone"),
  CountryLocalization("sg", "Thok tamilni", "Singapore"),
  CountryLocalization("sx", "Thok liŋli̱thni", "Sint Maarten"),
  CountryLocalization("sk", "Slovak", "Slovakia"),
  CountryLocalization("si", "Slovenian", "Slovenia"),
  CountryLocalization("sb", "Thok liŋli̱thni", "Solomon Islands"),
  CountryLocalization("so", "Thok Jalabni", "Somalia"),
  CountryLocalization("za", "Thok liŋli̱thni", "South Africa"),
  CountryLocalization("kr", "Thok kuriani", "South Korea"),
  CountryLocalization("ss", "Thok Nath", "South Sudan"),
  CountryLocalization("es", "Thok i̱thpaaniani", "Spain"),
  CountryLocalization("lk", "Thok tamilni", "Sri Lanka"),
  CountryLocalization("bl", "Thok pɔrɔthani", "St. Barthélemy"),
  CountryLocalization("sh", "Thok liŋli̱thni", "St. Helena"),
  CountryLocalization("kn", "Thok liŋli̱thni", "St. Kitts & Nevis"),
  CountryLocalization("lc", "Thok liŋli̱thni", "St. Lucia"),
  CountryLocalization("mf", "Thok pɔrɔthani", "St. Martin"),
  CountryLocalization("pm", "Thok pɔrɔthani", "St. Pierre & Miquelon"),
  CountryLocalization("vc", "Thok liŋli̱thni", "St. Vincent & Grenadines"),
  CountryLocalization("sd", "Thok Jalabni", "Sudan"),
  CountryLocalization("sr", "Thok da̱c", "Suriname"),
  CountryLocalization("sj", "Norwegian Bokmål", "Svalbard & Jan Mayen"),
  CountryLocalization("sz", "Thok liŋli̱thni", "Eswatini"),
  CountryLocalization("se", "Thok i̱thwidicni", "Sweden"),
  CountryLocalization("ch", "Swiss German", "Switzerland"),
  CountryLocalization("sy", "Thok Jalabni", "Syria"),
  CountryLocalization("st", "Thok puɔtigali", "São Tomé & Príncipe"),
  CountryLocalization("tw", "Thok cayna", "Taiwan"),
  CountryLocalization("tj", "Tajik", "Tajikistan"),
  CountryLocalization("tz", "kde", "Tanzania"),
  CountryLocalization("th", "Thok tayni", "Thailand"),
  CountryLocalization("tl", "Thok puɔtigali", "Timor-Leste"),
  CountryLocalization("tg", "Thok pɔrɔthani", "Togo"),
  CountryLocalization("tk", "Thok liŋli̱thni", "Tokelau"),
  CountryLocalization("to", "Tongan", "Tonga"),
  CountryLocalization("tt", "Thok liŋli̱thni", "Trinidad & Tobago"),
  CountryLocalization("tn", "Thok pɔrɔthani", "Tunisia"),
  CountryLocalization("tr", "Thok turkicni", "Turkey"),
  CountryLocalization("tm", "Turkmen", "Turkmenistan"),
  CountryLocalization("tc", "Thok liŋli̱thni", "Turks & Caicos Islands"),
  CountryLocalization("tv", "Thok liŋli̱thni", "Tuvalu"),
  CountryLocalization("um", "Thok liŋli̱thni", "U.S. Outlying Islands"),
  CountryLocalization("vi", "Thok liŋli̱thni", "U.S. Virgin Islands"),
  CountryLocalization("ug", "Swahili", "Uganda"),
  CountryLocalization("ua", "Thok ukeraanini", "Ukraine"),
  CountryLocalization("ae", "Thok Jalabni", "United Arab Emirates"),
  CountryLocalization("gb", "Thok liŋli̱thni", "United Kingdom"),
  CountryLocalization("us", "lkt", "United States"),
  CountryLocalization("uy", "Thok i̱thpaaniani", "Uruguay"),
  CountryLocalization("uz", "Uzbek", "Uzbekistan"),
  CountryLocalization("vu", "Thok pɔrɔthani", "Vanuatu"),
  CountryLocalization("va", "Thok i̱taliani", "Vatican City"),
  CountryLocalization("ve", "Thok i̱thpaaniani", "Venezuela"),
  CountryLocalization("vn", "Thok betnaamni", "Vietnam"),
  CountryLocalization("wf", "Thok pɔrɔthani", "Wallis & Futuna"),
  CountryLocalization("eh", "Thok Jalabni", "Western Sahara"),
  CountryLocalization("ye", "Thok Jalabni", "Yemen"),
  CountryLocalization("zm", "Thok liŋli̱thni", "Zambia"),
  CountryLocalization("zw", "North Ndebele", "Zimbabwe"),
  CountryLocalization("ax", "Thok i̱thwidicni", "Åland Islands"),
)
