/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot.atlas.extended

import dev.teogor.xenoglot.atlas.CountryLocalization
import kotlin.collections.List

/**
 * Holds the internal list of country-language mappings used for lookups within the package for
 * language code nb.
 *
 * This property contains a hardcoded list of [CountryLocalization] objects, each representing
 * a country and its associated official languages. This list is used by [CountryLanguageRegistry]
 * to provide access to country-language data and should not be modified directly.
 *
 * @see CountryLocalization
 * @see CountryLanguageRegistry
 */
internal val _countryLanguageMappings_nb: List<CountryLocalization> = listOf(
  CountryLocalization("af", "persisk", "Afghanistan"),
  CountryLocalization("al", "albansk", "Albania"),
  CountryLocalization("dz", "fransk", "Algerie"),
  CountryLocalization("as", "engelsk", "Amerikansk Samoa"),
  CountryLocalization("ad", "katalansk", "Andorra"),
  CountryLocalization("ao", "lingala", "Angola"),
  CountryLocalization("ai", "engelsk", "Anguilla"),
  CountryLocalization("ag", "engelsk", "Antigua og Barbuda"),
  CountryLocalization("ar", "spansk", "Argentina"),
  CountryLocalization("am", "armensk", "Armenia"),
  CountryLocalization("aw", "nederlandsk", "Aruba"),
  CountryLocalization("au", "engelsk", "Australia"),
  CountryLocalization("at", "engelsk", "Østerrike"),
  CountryLocalization("az", "aserbajdsjansk", "Aserbajdsjan"),
  CountryLocalization("bs", "engelsk", "Bahamas"),
  CountryLocalization("bh", "arabisk", "Bahrain"),
  CountryLocalization("bd", "bengali", "Bangladesh"),
  CountryLocalization("bb", "engelsk", "Barbados"),
  CountryLocalization("by", "hviterussisk", "Hviterussland"),
  CountryLocalization("be", "fransk", "Belgia"),
  CountryLocalization("bz", "engelsk", "Belize"),
  CountryLocalization("bj", "fransk", "Benin"),
  CountryLocalization("bm", "engelsk", "Bermuda"),
  CountryLocalization("bt", "dzongkha", "Bhutan"),
  CountryLocalization("bo", "spansk", "Bolivia"),
  CountryLocalization("ba", "bosnisk", "Bosnia-Hercegovina"),
  CountryLocalization("bw", "engelsk", "Botswana"),
  CountryLocalization("br", "portugisisk", "Brasil"),
  CountryLocalization("io", "engelsk", "Det britiske territoriet i Indiahavet"),
  CountryLocalization("vg", "engelsk", "De britiske jomfruøyene"),
  CountryLocalization("bn", "malayisk", "Brunei"),
  CountryLocalization("bg", "bulgarsk", "Bulgaria"),
  CountryLocalization("bf", "fransk", "Burkina Faso"),
  CountryLocalization("bi", "fransk", "Burundi"),
  CountryLocalization("kh", "khmer", "Kambodsja"),
  CountryLocalization("cm", "basaa", "Kamerun"),
  CountryLocalization("ca", "fransk", "Canada"),
  CountryLocalization("ic", "spansk", "Kanariøyene"),
  CountryLocalization("cv", "kappverdisk", "Kapp Verde"),
  CountryLocalization("bq", "nederlandsk", "Karibisk Nederland"),
  CountryLocalization("ky", "engelsk", "Caymanøyene"),
  CountryLocalization("cf", "lingala", "Den sentralafrikanske republikk"),
  CountryLocalization("ea", "spansk", "Ceuta og Melilla"),
  CountryLocalization("td", "arabisk", "Tsjad"),
  CountryLocalization("cl", "spansk", "Chile"),
  CountryLocalization("cn", "tibetansk", "Kina"),
  CountryLocalization("cx", "engelsk", "Christmasøya"),
  CountryLocalization("cc", "engelsk", "Kokosøyene"),
  CountryLocalization("co", "spansk", "Colombia"),
  CountryLocalization("km", "arabisk", "Komorene"),
  CountryLocalization("cg", "lingala", "Kongo-Brazzaville"),
  CountryLocalization("cd", "swahili", "Kongo-Kinshasa"),
  CountryLocalization("ck", "engelsk", "Cookøyene"),
  CountryLocalization("cr", "spansk", "Costa Rica"),
  CountryLocalization("hr", "kroatisk", "Kroatia"),
  CountryLocalization("cu", "spansk", "Cuba"),
  CountryLocalization("cw", "nederlandsk", "Curaçao"),
  CountryLocalization("cy", "engelsk", "Kypros"),
  CountryLocalization("cz", "tsjekkisk", "Tsjekkia"),
  CountryLocalization("ci", "fransk", "Elfenbenskysten"),
  CountryLocalization("dk", "engelsk", "Danmark"),
  CountryLocalization("dg", "engelsk", "Diego Garcia"),
  CountryLocalization("dj", "fransk", "Djibouti"),
  CountryLocalization("dm", "engelsk", "Dominica"),
  CountryLocalization("do", "spansk", "Den dominikanske republikk"),
  CountryLocalization("ec", "quechua", "Ecuador"),
  CountryLocalization("eg", "arabisk", "Egypt"),
  CountryLocalization("sv", "spansk", "El Salvador"),
  CountryLocalization("gq", "spansk", "Ekvatorial-Guinea"),
  CountryLocalization("er", "tigrinja", "Eritrea"),
  CountryLocalization("ee", "estisk", "Estland"),
  CountryLocalization("et", "amharisk", "Etiopia"),
  CountryLocalization("fk", "engelsk", "Falklandsøyene"),
  CountryLocalization("fo", "færøysk", "Færøyene"),
  CountryLocalization("fj", "engelsk", "Fiji"),
  CountryLocalization("fi", "svensk", "Finland"),
  CountryLocalization("fr", "sveitsertysk", "Frankrike"),
  CountryLocalization("gf", "fransk", "Fransk Guyana"),
  CountryLocalization("pf", "fransk", "Fransk Polynesia"),
  CountryLocalization("ga", "fransk", "Gabon"),
  CountryLocalization("gm", "engelsk", "Gambia"),
  CountryLocalization("ge", "ossetisk", "Georgia"),
  CountryLocalization("de", "lavsorbisk", "Tyskland"),
  CountryLocalization("gh", "engelsk", "Ghana"),
  CountryLocalization("gi", "engelsk", "Gibraltar"),
  CountryLocalization("gr", "gresk", "Hellas"),
  CountryLocalization("gl", "grønlandsk", "Grønland"),
  CountryLocalization("gd", "engelsk", "Grenada"),
  CountryLocalization("gp", "fransk", "Guadeloupe"),
  CountryLocalization("gu", "engelsk", "Guam"),
  CountryLocalization("gt", "spansk", "Guatemala"),
  CountryLocalization("gg", "engelsk", "Guernsey"),
  CountryLocalization("gn", "fransk", "Guinea"),
  CountryLocalization("gw", "portugisisk", "Guinea-Bissau"),
  CountryLocalization("gy", "engelsk", "Guyana"),
  CountryLocalization("ht", "fransk", "Haiti"),
  CountryLocalization("hn", "spansk", "Honduras"),
  CountryLocalization("hk", "kinesisk", "Hongkong S.A.R. Kina"),
  CountryLocalization("hu", "ungarsk", "Ungarn"),
  CountryLocalization("is", "islandsk", "Island"),
  CountryLocalization("in", "nepali", "India"),
  CountryLocalization("id", "Indonesian", "Indonesia"),
  CountryLocalization("ir", "persisk", "Iran"),
  CountryLocalization("iq", "nord-luri", "Irak"),
  CountryLocalization("ie", "engelsk", "Irland"),
  CountryLocalization("im", "mansk", "Man"),
  CountryLocalization("il", "engelsk", "Israel"),
  CountryLocalization("it", "tysk", "Italia"),
  CountryLocalization("jm", "engelsk", "Jamaica"),
  CountryLocalization("jp", "japansk", "Japan"),
  CountryLocalization("je", "engelsk", "Jersey"),
  CountryLocalization("jo", "arabisk", "Jordan"),
  CountryLocalization("kz", "kasakhisk", "Kasakhstan"),
  CountryLocalization("ke", "somali", "Kenya"),
  CountryLocalization("ki", "engelsk", "Kiribati"),
  CountryLocalization("xk", "serbisk", "Kosovo"),
  CountryLocalization("kw", "arabisk", "Kuwait"),
  CountryLocalization("kg", "russisk", "Kirgisistan"),
  CountryLocalization("la", "laotisk", "Laos"),
  CountryLocalization("lv", "latvisk", "Latvia"),
  CountryLocalization("lb", "arabisk", "Libanon"),
  CountryLocalization("ls", "engelsk", "Lesotho"),
  CountryLocalization("lr", "engelsk", "Liberia"),
  CountryLocalization("ly", "arabisk", "Libya"),
  CountryLocalization("li", "sveitsertysk", "Liechtenstein"),
  CountryLocalization("lt", "litauisk", "Litauen"),
  CountryLocalization("lu", "luxemburgsk", "Luxemburg"),
  CountryLocalization("mo", "portugisisk", "Macao S.A.R. Kina"),
  CountryLocalization("mk", "albansk", "Makedonia"),
  CountryLocalization("mg", "fransk", "Madagaskar"),
  CountryLocalization("mw", "engelsk", "Malawi"),
  CountryLocalization("my", "tamil", "Malaysia"),
  CountryLocalization("ml", "fransk", "Mali"),
  CountryLocalization("mt", "engelsk", "Malta"),
  CountryLocalization("mh", "engelsk", "Marshalløyene"),
  CountryLocalization("mq", "fransk", "Martinique"),
  CountryLocalization("mr", "arabisk", "Mauritania"),
  CountryLocalization("mu", "mauritisk-kreolsk", "Mauritius"),
  CountryLocalization("yt", "fransk", "Mayotte"),
  CountryLocalization("mx", "spansk", "Mexico"),
  CountryLocalization("fm", "engelsk", "Mikronesiaføderasjonen"),
  CountryLocalization("md", "russisk", "Moldova"),
  CountryLocalization("mc", "fransk", "Monaco"),
  CountryLocalization("mn", "mongolsk", "Mongolia"),
  CountryLocalization("me", "serbisk", "Montenegro"),
  CountryLocalization("ms", "engelsk", "Montserrat"),
  CountryLocalization("ma", "sentralmarokkansk tamazight", "Marokko"),
  CountryLocalization("mz", "makhuwa-meetto", "Mosambik"),
  CountryLocalization("mm", "burmesisk", "Myanmar (Burma)"),
  CountryLocalization("na", "engelsk", "Namibia"),
  CountryLocalization("nr", "engelsk", "Nauru"),
  CountryLocalization("np", "nepali", "Nepal"),
  CountryLocalization("nl", "engelsk", "Nederland"),
  CountryLocalization("nc", "fransk", "Ny-Caledonia"),
  CountryLocalization("nz", "engelsk", "New Zealand"),
  CountryLocalization("ni", "spansk", "Nicaragua"),
  CountryLocalization("ne", "hausa", "Niger"),
  CountryLocalization("ng", "hausa", "Nigeria"),
  CountryLocalization("nu", "engelsk", "Niue"),
  CountryLocalization("nf", "engelsk", "Norfolkøya"),
  CountryLocalization("kp", "koreansk", "Nord-Korea"),
  CountryLocalization("mp", "engelsk", "Nord-Marianene"),
  CountryLocalization("no", "nordsamisk", "Norge"),
  CountryLocalization("om", "arabisk", "Oman"),
  CountryLocalization("pk", "engelsk", "Pakistan"),
  CountryLocalization("pw", "engelsk", "Palau"),
  CountryLocalization("ps", "arabisk", "Det palestinske området"),
  CountryLocalization("pa", "spansk", "Panama"),
  CountryLocalization("pg", "engelsk", "Papua Ny-Guinea"),
  CountryLocalization("py", "spansk", "Paraguay"),
  CountryLocalization("pe", "spansk", "Peru"),
  CountryLocalization("ph", "filipino", "Filippinene"),
  CountryLocalization("pn", "engelsk", "Pitcairn"),
  CountryLocalization("pl", "polsk", "Polen"),
  CountryLocalization("pt", "portugisisk", "Portugal"),
  CountryLocalization("pr", "engelsk", "Puerto Rico"),
  CountryLocalization("qa", "arabisk", "Qatar"),
  CountryLocalization("ro", "rumensk", "Romania"),
  CountryLocalization("ru", "tatarisk", "Russland"),
  CountryLocalization("rw", "engelsk", "Rwanda"),
  CountryLocalization("re", "fransk", "Réunion"),
  CountryLocalization("ws", "engelsk", "Samoa"),
  CountryLocalization("sm", "italiensk", "San Marino"),
  CountryLocalization("sa", "arabisk", "Saudi-Arabia"),
  CountryLocalization("sn", "fransk", "Senegal"),
  CountryLocalization("rs", "serbisk", "Serbia"),
  CountryLocalization("cs", "serbisk", "Serbia and Montenegro"),
  CountryLocalization("sc", "fransk", "Seychellene"),
  CountryLocalization("sl", "engelsk", "Sierra Leone"),
  CountryLocalization("sg", "tamil", "Singapore"),
  CountryLocalization("sx", "engelsk", "Sint Maarten"),
  CountryLocalization("sk", "slovakisk", "Slovakia"),
  CountryLocalization("si", "slovensk", "Slovenia"),
  CountryLocalization("sb", "engelsk", "Salomonøyene"),
  CountryLocalization("so", "arabisk", "Somalia"),
  CountryLocalization("za", "engelsk", "Sør-Afrika"),
  CountryLocalization("kr", "koreansk", "Sør-Korea"),
  CountryLocalization("ss", "nuer", "Sør-Sudan"),
  CountryLocalization("es", "spansk", "Spania"),
  CountryLocalization("lk", "tamil", "Sri Lanka"),
  CountryLocalization("bl", "fransk", "Saint-Barthélemy"),
  CountryLocalization("sh", "engelsk", "St. Helena"),
  CountryLocalization("kn", "engelsk", "Saint Kitts og Nevis"),
  CountryLocalization("lc", "engelsk", "St. Lucia"),
  CountryLocalization("mf", "fransk", "Saint-Martin"),
  CountryLocalization("pm", "fransk", "Saint-Pierre-et-Miquelon"),
  CountryLocalization("vc", "engelsk", "St. Vincent og Grenadinene"),
  CountryLocalization("sd", "arabisk", "Sudan"),
  CountryLocalization("sr", "nederlandsk", "Surinam"),
  CountryLocalization("sj", "norsk bokmål", "Svalbard og Jan Mayen"),
  CountryLocalization("sz", "engelsk", "Swaziland"),
  CountryLocalization("se", "svensk", "Sverige"),
  CountryLocalization("ch", "sveitsertysk", "Sveits"),
  CountryLocalization("sy", "arabisk", "Syria"),
  CountryLocalization("st", "portugisisk", "São Tomé og Príncipe"),
  CountryLocalization("tw", "kinesisk", "Taiwan"),
  CountryLocalization("tj", "tadsjikisk", "Tadsjikistan"),
  CountryLocalization("tz", "makonde", "Tanzania"),
  CountryLocalization("th", "thai", "Thailand"),
  CountryLocalization("tl", "portugisisk", "Øst-Timor"),
  CountryLocalization("tg", "fransk", "Togo"),
  CountryLocalization("tk", "engelsk", "Tokelau"),
  CountryLocalization("to", "tongansk", "Tonga"),
  CountryLocalization("tt", "engelsk", "Trinidad og Tobago"),
  CountryLocalization("tn", "fransk", "Tunisia"),
  CountryLocalization("tr", "tyrkisk", "Tyrkia"),
  CountryLocalization("tm", "turkmensk", "Turkmenistan"),
  CountryLocalization("tc", "engelsk", "Turks- og Caicosøyene"),
  CountryLocalization("tv", "engelsk", "Tuvalu"),
  CountryLocalization("um", "engelsk", "USAs ytre øyer"),
  CountryLocalization("vi", "engelsk", "De amerikanske jomfruøyene"),
  CountryLocalization("ug", "swahili", "Uganda"),
  CountryLocalization("ua", "ukrainsk", "Ukraina"),
  CountryLocalization("ae", "arabisk", "De forente arabiske emirater"),
  CountryLocalization("gb", "engelsk", "Storbritannia"),
  CountryLocalization("us", "lakota", "USA"),
  CountryLocalization("uy", "spansk", "Uruguay"),
  CountryLocalization("uz", "usbekisk", "Usbekistan"),
  CountryLocalization("vu", "fransk", "Vanuatu"),
  CountryLocalization("va", "italiensk", "Vatikanstaten"),
  CountryLocalization("ve", "spansk", "Venezuela"),
  CountryLocalization("vn", "vietnamesisk", "Vietnam"),
  CountryLocalization("wf", "fransk", "Wallis og Futuna"),
  CountryLocalization("eh", "arabisk", "Vest-Sahara"),
  CountryLocalization("ye", "arabisk", "Jemen"),
  CountryLocalization("zm", "engelsk", "Zambia"),
  CountryLocalization("zw", "nord-ndebele", "Zimbabwe"),
  CountryLocalization("ax", "svensk", "Åland"),
)
