/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot.atlas.extended

import dev.teogor.xenoglot.atlas.CountryLocalization
import kotlin.collections.List

/**
 * Holds the internal list of country-language mappings used for lookups within the package for
 * language code my.
 *
 * This property contains a hardcoded list of [CountryLocalization] objects, each representing
 * a country and its associated official languages. This list is used by [CountryLanguageRegistry]
 * to provide access to country-language data and should not be modified directly.
 *
 * @see CountryLocalization
 * @see CountryLanguageRegistry
 */
internal val _countryLanguageMappings_my: List<CountryLocalization> = listOf(
  CountryLocalization("af", "ပါရှန်", "အာဖဂန်နစ္စတန်"),
  CountryLocalization("al", "အယ်လ်ဘေးနီးယား", "အယ်လ်ဘေးနီးယား"),
  CountryLocalization("dz", "ပြင်သစ်", "အယ်လ်ဂျီးရီးယား"),
  CountryLocalization("as", "အင်္ဂလိပ်", "အမေရိကန် ဆမိုးအား"),
  CountryLocalization("ad", "ကတ်တလန်", "အန်ဒိုရာ"),
  CountryLocalization("ao", "လင်ဂါလာ", "အန်ဂိုလာ"),
  CountryLocalization("ai", "အင်္ဂလိပ်", "အန်ဂီလာ"),
  CountryLocalization("ag", "အင်္ဂလိပ်", "အန်တီဂွါနှင့် ဘာဘူဒါ"),
  CountryLocalization("ar", "စပိန်", "အာဂျင်တီးနား"),
  CountryLocalization("am", "အာမေးနီးယား", "အာမေးနီးယား"),
  CountryLocalization("aw", "ဒတ်ခ်ျ", "အာရူးဗား"),
  CountryLocalization("au", "အင်္ဂလိပ်", "ဩစတြေးလျ"),
  CountryLocalization("at", "အင်္ဂလိပ်", "ဩစတြီးယား"),
  CountryLocalization("az", "အဇာဘိုင်ဂျန်", "အဇာဘိုင်ဂျန်"),
  CountryLocalization("bs", "အင်္ဂလိပ်", "ဘဟားမား"),
  CountryLocalization("bh", "အာရဗီ", "ဘာရိန်း"),
  CountryLocalization("bd", "ဘင်္ဂါလီ", "ဘင်္ဂလားဒေ့ရှ်"),
  CountryLocalization("bb", "အင်္ဂလိပ်", "ဘာဘေးဒိုးစ်"),
  CountryLocalization("by", "ဘီလာရုစ်", "ဘီလာရုစ်"),
  CountryLocalization("be", "ပြင်သစ်", "ဘယ်လ်ဂျီယမ်"),
  CountryLocalization("bz", "အင်္ဂလိပ်", "ဘလိဇ်"),
  CountryLocalization("bj", "ပြင်သစ်", "ဘီနင်"),
  CountryLocalization("bm", "အင်္ဂလိပ်", "ဘာမြူဒါ"),
  CountryLocalization("bt", "ဒဇွန်ကာ", "ဘူတန်"),
  CountryLocalization("bo", "စပိန်", "ဘိုလီးဗီးယား"),
  CountryLocalization("ba", "ဘော့စ်နီးယား", "ဘော့စနီးယားနှင့် ဟာဇီဂိုဗီနား"),
  CountryLocalization("bw", "အင်္ဂလိပ်", "ဘော့ဆွာနာ"),
  CountryLocalization("br", "ပေါ်တူဂီ", "ဘရာဇီး"),
  CountryLocalization("io", "အင်္ဂလိပ်", "ဗြိတိသျှပိုင် အိန္ဒိယသမုဒ္ဒရာကျွန်းများ"),
  CountryLocalization("vg", "အင်္ဂလိပ်", "ဗြိတိသျှ ဗာဂျင်း ကျွန်းစု"),
  CountryLocalization("bn", "မလေး", "ဘရူနိုင်း"),
  CountryLocalization("bg", "ဘူလ်ဂေးရီးယား", "ဘူလ်ဂေးရီးယား"),
  CountryLocalization("bf", "ပြင်သစ်", "ဘာကီးနား ဖားဆို"),
  CountryLocalization("bi", "ပြင်သစ်", "ဘူရွန်ဒီ"),
  CountryLocalization("kh", "ခမာ", "ကမ္ဘောဒီးယား"),
  CountryLocalization("cm", "ဘာဆာ", "ကင်မရွန်း"),
  CountryLocalization("ca", "ပြင်သစ်", "ကနေဒါ"),
  CountryLocalization("ic", "စပိန်", "ကနေရီ ကျွန်းစု"),
  CountryLocalization("cv", "ကဘူဗာဒီအာနူ", "ကိတ်ဗာဒီ"),
  CountryLocalization("bq", "ဒတ်ခ်ျ", "ကာရစ်ဘီယံ နယ်သာလန်"),
  CountryLocalization("ky", "အင်္ဂလိပ်", "ကေမန် ကျွန်းစု"),
  CountryLocalization("cf", "လင်ဂါလာ", "ဗဟို အာဖရိက ပြည်ထောင်စု"),
  CountryLocalization("ea", "စပိန်", "ဆယ်ဥတာနှင့်မယ်လီလ်လာ"),
  CountryLocalization("td", "အာရဗီ", "ချဒ်"),
  CountryLocalization("cl", "စပိန်", "ချီလီ"),
  CountryLocalization("cn", "တိဘက်", "တရုတ်"),
  CountryLocalization("cx", "အင်္ဂလိပ်", "ခရစ်စမတ် ကျွန်း"),
  CountryLocalization("cc", "အင်္ဂလိပ်", "ကိုကိုးကျွန်း"),
  CountryLocalization("co", "စပိန်", "ကိုလံဘီယာ"),
  CountryLocalization("km", "အာရဗီ", "ကိုမိုရိုစ်"),
  CountryLocalization("cg", "လင်ဂါလာ", "ကွန်ဂို-ဘရာဇာဗီးလ်"),
  CountryLocalization("cd", "ဆွာဟီလီ", "ကွန်ဂို"),
  CountryLocalization("ck", "အင်္ဂလိပ်", "ကွတ် ကျွန်းစု"),
  CountryLocalization("cr", "စပိန်", "ကို့စ်တာရီကာ"),
  CountryLocalization("hr", "ခရိုအေးရှား", "ခရိုအေးရှား"),
  CountryLocalization("cu", "စပိန်", "ကျူးဘား"),
  CountryLocalization("cw", "ဒတ်ခ်ျ", "ကျူရေးကိုးစ်"),
  CountryLocalization("cy", "အင်္ဂလိပ်", "ဆိုက်ပရပ်စ်"),
  CountryLocalization("cz", "ချက်", "ချက်ကီယား"),
  CountryLocalization("ci", "ပြင်သစ်", "ကို့တ် ဒီဗွာ"),
  CountryLocalization("dk", "အင်္ဂလိပ်", "ဒိန်းမတ်"),
  CountryLocalization("dg", "အင်္ဂလိပ်", "ဒီအဲဂိုဂါစီရာ"),
  CountryLocalization("dj", "ပြင်သစ်", "ဂျီဘူတီ"),
  CountryLocalization("dm", "အင်္ဂလိပ်", "ဒိုမီနီကာ"),
  CountryLocalization("do", "စပိန်", "ဒိုမီနီကန်"),
  CountryLocalization("ec", "ခီချူဝါအိုဝါ", "အီကွေဒေါ"),
  CountryLocalization("eg", "အာရဗီ", "အီဂျစ်"),
  CountryLocalization("sv", "စပိန်", "အယ်လ်ဆာဗေးဒိုး"),
  CountryLocalization("gq", "စပိန်", "အီကွေတာ ဂီနီ"),
  CountryLocalization("er", "တီဂ်ရင်ယာ", "အီရီထရီးယား"),
  CountryLocalization("ee", "အက်စ်တိုးနီးယား", "အက်စတိုးနီးယား"),
  CountryLocalization("et", "အမ်ဟာရစ်ခ်", "အီသီယိုးပီးယား"),
  CountryLocalization("fk", "အင်္ဂလိပ်", "ဖော့ကလန် ကျွန်းစု"),
  CountryLocalization("fo", "ဖာရို", "ဖာရိုး ကျွန်းစုများ"),
  CountryLocalization("fj", "အင်္ဂလိပ်", "ဖီဂျီ"),
  CountryLocalization("fi", "ဆွီဒင်", "ဖင်လန်"),
  CountryLocalization("fr", "ဆွစ် ဂျာမန်", "ပြင်သစ်"),
  CountryLocalization("gf", "ပြင်သစ်", "ပြင်သစ် ဂီယာနာ"),
  CountryLocalization("pf", "ပြင်သစ်", "ပြင်သစ် ပေါ်လီနီးရှား"),
  CountryLocalization("ga", "ပြင်သစ်", "ဂါဘွန်"),
  CountryLocalization("gm", "အင်္ဂလိပ်", "ဂမ်ဘီရာ"),
  CountryLocalization("ge", "အိုဆဲတစ်ခ်", "ဂျော်ဂျီယာ"),
  CountryLocalization("de", "အနိမ့် ဆိုဘီယန်း", "ဂျာမနီ"),
  CountryLocalization("gh", "အင်္ဂလိပ်", "ဂါနာ"),
  CountryLocalization("gi", "အင်္ဂလိပ်", "ဂျီဘရော်လ်တာ"),
  CountryLocalization("gr", "ဂရိ", "ဂရိ"),
  CountryLocalization("gl", "ကလာအ်လီဆပ်", "ဂရင်းလန်း"),
  CountryLocalization("gd", "အင်္ဂလိပ်", "ဂရီနေဒါ"),
  CountryLocalization("gp", "ပြင်သစ်", "ဂွါဒီလု"),
  CountryLocalization("gu", "အင်္ဂလိပ်", "ဂူအမ်"),
  CountryLocalization("gt", "စပိန်", "ဂွါတီမာလာ"),
  CountryLocalization("gg", "အင်္ဂလိပ်", "ဂွန်းဇီ"),
  CountryLocalization("gn", "ပြင်သစ်", "ဂီနီ"),
  CountryLocalization("gw", "ပေါ်တူဂီ", "ဂီနီ-ဘီစော"),
  CountryLocalization("gy", "အင်္ဂလိပ်", "ဂိုင်ယာနာ"),
  CountryLocalization("ht", "ပြင်သစ်", "ဟေတီ"),
  CountryLocalization("hn", "စပိန်", "ဟွန်ဒူးရပ်စ်"),
  CountryLocalization("hk", "တရုတ်", "ဟောင်ကောင် (တရုတ်ပြည်)"),
  CountryLocalization("hu", "ဟန်ဂေရီ", "ဟန်ဂေရီ"),
  CountryLocalization("is", "အိုက်စ်လန်", "အိုက်စလန်"),
  CountryLocalization("in", "နီပေါ", "အိန္ဒိယ"),
  CountryLocalization("id", "Indonesian", "အင်ဒိုနီးရှား"),
  CountryLocalization("ir", "ပါရှန်", "အီရန်"),
  CountryLocalization("iq", "မြောက်လူရီ", "အီရတ်"),
  CountryLocalization("ie", "အင်္ဂလိပ်", "အိုင်ယာလန်"),
  CountryLocalization("im", "မန်းဇ်", "မန်ကျွန်း"),
  CountryLocalization("il", "အင်္ဂလိပ်", "အစ္စရေး"),
  CountryLocalization("it", "ဂျာမန်", "အီတလီ"),
  CountryLocalization("jm", "အင်္ဂလိပ်", "ဂျမေကာ"),
  CountryLocalization("jp", "ဂျပန်", "ဂျပန်"),
  CountryLocalization("je", "အင်္ဂလိပ်", "ဂျာစီ"),
  CountryLocalization("jo", "အာရဗီ", "ဂျော်ဒန်"),
  CountryLocalization("kz", "ကာဇာခ်", "ကာဇက်စတန်"),
  CountryLocalization("ke", "ဆိုမာလီ", "ကင်ညာ"),
  CountryLocalization("ki", "အင်္ဂလိပ်", "ခီရီဘာတီ"),
  CountryLocalization("xk", "ဆားဘီးယား", "ကိုဆိုဗို"),
  CountryLocalization("kw", "အာရဗီ", "ကူဝိတ်"),
  CountryLocalization("kg", "ရုရှ", "ကာဂျစ္စတန်"),
  CountryLocalization("la", "လာအို", "လာအို"),
  CountryLocalization("lv", "လတ်ဗီးယား", "လတ်ဗီးယား"),
  CountryLocalization("lb", "အာရဗီ", "လက်ဘနွန်"),
  CountryLocalization("ls", "အင်္ဂလိပ်", "လီဆိုသို"),
  CountryLocalization("lr", "အင်္ဂလိပ်", "လိုက်ဘေးရီးယား"),
  CountryLocalization("ly", "အာရဗီ", "လစ်ဗျား"),
  CountryLocalization("li", "ဆွစ် ဂျာမန်", "လစ်တန်စတိန်း"),
  CountryLocalization("lt", "လစ်သူဝေးနီးယား", "လစ်သူယေးနီးယား"),
  CountryLocalization("lu", "လူဇင်ဘတ်", "လူဇင်ဘတ်"),
  CountryLocalization("mo", "ပေါ်တူဂီ", "မကာအို (တရုတ်ပြည်)"),
  CountryLocalization("mk", "အယ်လ်ဘေးနီးယား", "မက်ဆီဒိုးနီးယား"),
  CountryLocalization("mg", "ပြင်သစ်", "မဒါဂတ်စကား"),
  CountryLocalization("mw", "အင်္ဂလိပ်", "မာလာဝီ"),
  CountryLocalization("my", "တမီးလ်", "မလေးရှား"),
  CountryLocalization("ml", "ပြင်သစ်", "မာလီ"),
  CountryLocalization("mt", "အင်္ဂလိပ်", "မောလ်တာ"),
  CountryLocalization("mh", "အင်္ဂလိပ်", "မာရှယ် ကျွန်းစု"),
  CountryLocalization("mq", "ပြင်သစ်", "မာတီနိခ်"),
  CountryLocalization("mr", "အာရဗီ", "မော်ရီတေးနီးယား"),
  CountryLocalization("mu", "မောရစ်ရှ", "မောရစ်ရှ"),
  CountryLocalization("yt", "ပြင်သစ်", "မေယော့"),
  CountryLocalization("mx", "စပိန်", "မက္ကဆီကို"),
  CountryLocalization("fm", "အင်္ဂလိပ်", "မိုင်ခရိုနီရှား"),
  CountryLocalization("md", "ရုရှ", "မောလ်ဒိုဗာ"),
  CountryLocalization("mc", "ပြင်သစ်", "မိုနာကို"),
  CountryLocalization("mn", "မွန်ဂိုလီးယား", "မွန်ဂိုးလီးယား"),
  CountryLocalization("me", "ဆားဘီးယား", "မွန်တီနိဂရိုး"),
  CountryLocalization("ms", "အင်္ဂလိပ်", "မောင့်စဲရက်"),
  CountryLocalization("ma", "အလယ်အာ့တလာစ် တာမာဇိုက်", "မော်ရိုကို"),
  CountryLocalization("mz", "မာခူဝါ-မီအီတို", "မိုဇမ်ဘစ်"),
  CountryLocalization("mm", "မြန်မာ", "မြန်မာ"),
  CountryLocalization("na", "အင်္ဂလိပ်", "နမီးဘီးယား"),
  CountryLocalization("nr", "အင်္ဂလိပ်", "နော်ရူး"),
  CountryLocalization("np", "နီပေါ", "နီပေါ"),
  CountryLocalization("nl", "အင်္ဂလိပ်", "နယ်သာလန်"),
  CountryLocalization("nc", "ပြင်သစ်", "နယူး ကယ်လီဒိုနီးယား"),
  CountryLocalization("nz", "အင်္ဂလိပ်", "နယူးဇီလန်"),
  CountryLocalization("ni", "စပိန်", "နီကာရာဂွါ"),
  CountryLocalization("ne", "ဟာဥစာ", "နိုင်ဂျာ"),
  CountryLocalization("ng", "ဟာဥစာ", "နိုင်ဂျီးရီးယား"),
  CountryLocalization("nu", "အင်္ဂလိပ်", "နီဥူအေ"),
  CountryLocalization("nf", "အင်္ဂလိပ်", "နောဖုတ်ကျွန်း"),
  CountryLocalization("kp", "ကိုရီးယား", "မြောက်ကိုရီးယား"),
  CountryLocalization("mp", "အင်္ဂလိပ်", "တောင်ပိုင်းမာရီအာနာကျွန်းစု"),
  CountryLocalization("no", "မြောက် ဆာမိ", "နော်ဝေ"),
  CountryLocalization("om", "အာရဗီ", "အိုမန်"),
  CountryLocalization("pk", "အင်္ဂလိပ်", "ပါကစ္စတန်"),
  CountryLocalization("pw", "အင်္ဂလိပ်", "ပလာအို"),
  CountryLocalization("ps", "အာရဗီ", "ပါလက်စတိုင်း ပိုင်နက်"),
  CountryLocalization("pa", "စပိန်", "ပနားမား"),
  CountryLocalization("pg", "အင်္ဂလိပ်", "ပါပူအာ နယူးဂီနီ"),
  CountryLocalization("py", "စပိန်", "ပါရာဂွေး"),
  CountryLocalization("pe", "စပိန်", "ပီရူး"),
  CountryLocalization("ph", "ဖိလစ်ပိုင်", "ဖိလစ်ပိုင်"),
  CountryLocalization("pn", "အင်္ဂလိပ်", "ပစ်တ်ကိန်းကျွန်းစု"),
  CountryLocalization("pl", "ပိုလန်", "ပိုလန်"),
  CountryLocalization("pt", "ပေါ်တူဂီ", "ပေါ်တူဂီ"),
  CountryLocalization("pr", "အင်္ဂလိပ်", "ပေါ်တိုရီကို"),
  CountryLocalization("qa", "အာရဗီ", "ကာတာ"),
  CountryLocalization("ro", "ရိုမေနီယား", "ရိုမေးနီးယား"),
  CountryLocalization("ru", "တာတာ", "ရုရှား"),
  CountryLocalization("rw", "အင်္ဂလိပ်", "ရဝန်ဒါ"),
  CountryLocalization("re", "ပြင်သစ်", "ရီယူနီယန်"),
  CountryLocalization("ws", "အင်္ဂလိပ်", "ဆမိုးအား"),
  CountryLocalization("sm", "အီတလီ", "ဆန်မာရီနို"),
  CountryLocalization("sa", "အာရဗီ", "ဆော်ဒီအာရေးဘီးယား"),
  CountryLocalization("sn", "ပြင်သစ်", "ဆီနီဂေါ"),
  CountryLocalization("rs", "ဆားဘီးယား", "ဆားဘီးယား"),
  CountryLocalization("cs", "ဆားဘီးယား", "Serbia and Montenegro"),
  CountryLocalization("sc", "ပြင်သစ်", "ဆေးရှဲ"),
  CountryLocalization("sl", "အင်္ဂလိပ်", "ဆီယာရာ လီယွန်း"),
  CountryLocalization("sg", "တမီးလ်", "စင်္ကာပူ"),
  CountryLocalization("sx", "အင်္ဂလိပ်", "စင့်မာတင်"),
  CountryLocalization("sk", "ဆလိုဗက်", "ဆလိုဗက်ကီးယား"),
  CountryLocalization("si", "ဆလိုဗေးနီးယား", "ဆလိုဗေးနီးယား"),
  CountryLocalization("sb", "အင်္ဂလိပ်", "ဆော်လမွန်ကျွန်းစု"),
  CountryLocalization("so", "အာရဗီ", "ဆိုမာလီယာ"),
  CountryLocalization("za", "အင်္ဂလိပ်", "တောင်အာဖရိက"),
  CountryLocalization("kr", "ကိုရီးယား", "တောင်ကိုရီးယား"),
  CountryLocalization("ss", "နူအာ", "တောင် ဆူဒန်"),
  CountryLocalization("es", "စပိန်", "စပိန်"),
  CountryLocalization("lk", "တမီးလ်", "သီရိလင်္ကာ"),
  CountryLocalization("bl", "ပြင်သစ်", "စိန့်ဘာသယ်လ်မီ"),
  CountryLocalization("sh", "အင်္ဂလိပ်", "စိန့်ဟယ်လယ်နာ"),
  CountryLocalization("kn", "အင်္ဂလိပ်", "စိန့်ကစ်နှင့်နီဗီစ်"),
  CountryLocalization("lc", "အင်္ဂလိပ်", "စိန့်လူစီယာ"),
  CountryLocalization("mf", "ပြင်သစ်", "စိန့်မာတင်"),
  CountryLocalization("pm", "ပြင်သစ်", "စိန့်ပီအဲရ်နှင့် မီကွီလွန်"),
  CountryLocalization("vc", "အင်္ဂလိပ်", "စိန့်ဗင်းဆင့်နှင့် ဂရိနေဒိုင်"),
  CountryLocalization("sd", "အာရဗီ", "ဆူဒန်"),
  CountryLocalization("sr", "ဒတ်ခ်ျ", "ဆူရာနမ်"),
  CountryLocalization("sj", "နော်ဝေ ဘွတ်ခ်မော်လ်", "စဗိုလ်ဘတ်နှင့်ဂျန်မေရန်"),
  CountryLocalization("sz", "အင်္ဂလိပ်", "ဆွာဇီလန်"),
  CountryLocalization("se", "ဆွီဒင်", "ဆွီဒင်"),
  CountryLocalization("ch", "ဆွစ် ဂျာမန်", "ဆွစ်ဇာလန်"),
  CountryLocalization("sy", "အာရဗီ", "ဆီးရီးယား"),
  CountryLocalization("st", "ပေါ်တူဂီ", "ဆောင်တူမေးနှင့် ပရင်စီပီ"),
  CountryLocalization("tw", "တရုတ်", "ထိုင်ဝမ်"),
  CountryLocalization("tj", "တာဂျစ်", "တာဂျီကစ္စတန်"),
  CountryLocalization("tz", "မာခွန်ဒီ", "တန်ဇန်းနီးယား"),
  CountryLocalization("th", "ထိုင်း", "ထိုင်း"),
  CountryLocalization("tl", "ပေါ်တူဂီ", "အရှေ့တီမော"),
  CountryLocalization("tg", "ပြင်သစ်", "တိုဂို"),
  CountryLocalization("tk", "အင်္ဂလိပ်", "တိုကလောင်"),
  CountryLocalization("to", "တွန်ဂါ", "တွန်ဂါ"),
  CountryLocalization("tt", "အင်္ဂလိပ်", "ထရီနီဒတ်နှင့် တိုဘက်ဂို"),
  CountryLocalization("tn", "ပြင်သစ်", "တူနီးရှား"),
  CountryLocalization("tr", "တူရကီ", "တူရကီ"),
  CountryLocalization("tm", "တာ့ခ်မင်နစ္စတန်", "တာ့ခ်မင်နစ္စတန်"),
  CountryLocalization("tc", "အင်္ဂလိပ်", "တခ်စ်နှင့်ကာအီကိုစ်ကျွန်းစု"),
  CountryLocalization("tv", "အင်္ဂလိပ်", "တူဗားလူ"),
  CountryLocalization("um", "အင်္ဂလိပ်", "ယူနိုက်တက်စတိတ် ကျွန်းနိုင်ငံများ"),
  CountryLocalization("vi", "အင်္ဂလိပ်", "ယူအက်စ် ဗာဂျင်း ကျွန်းစု"),
  CountryLocalization("ug", "ဆွာဟီလီ", "ယူဂန်းဒါး"),
  CountryLocalization("ua", "ယူကရိန်း", "ယူကရိန်း"),
  CountryLocalization("ae", "အာရဗီ", "ယူအေအီး"),
  CountryLocalization("gb", "အင်္ဂလိပ်", "ယူနိုက်တက်ကင်းဒမ်း"),
  CountryLocalization("us", "လာကိုတာ", "အမေရိကန် ပြည်ထောင်စု"),
  CountryLocalization("uy", "စပိန်", "ဥရုဂွေး"),
  CountryLocalization("uz", "ဥဇဘတ်", "ဥဇဘက်ကစ္စတန်"),
  CountryLocalization("vu", "ပြင်သစ်", "ဗနွားတူ"),
  CountryLocalization("va", "အီတလီ", "ဗာတီကန်စီးတီး"),
  CountryLocalization("ve", "စပိန်", "ဗင်နီဇွဲလား"),
  CountryLocalization("vn", "ဗီယက်နမ်", "ဗီယက်နမ်"),
  CountryLocalization("wf", "ပြင်သစ်", "ဝေါလစ်နှင့် ဖူကျူးနား"),
  CountryLocalization("eh", "အာရဗီ", "အနောက် ဆာဟာရ"),
  CountryLocalization("ye", "အာရဗီ", "ယီမင်"),
  CountryLocalization("zm", "အင်္ဂလိပ်", "ဇမ်ဘီယာ"),
  CountryLocalization("zw", "မြောက် အွန်န်ဒီဘီလီ", "ဇင်ဘာဘွေ"),
  CountryLocalization("ax", "ဆွီဒင်", "အာလန်ကျွန်း"),
)
