/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot.atlas.extended

import dev.teogor.xenoglot.atlas.CountryLocalization
import kotlin.collections.List

/**
 * Holds the internal list of country-language mappings used for lookups within the package for
 * language code ja.
 *
 * This property contains a hardcoded list of [CountryLocalization] objects, each representing
 * a country and its associated official languages. This list is used by [CountryLanguageRegistry]
 * to provide access to country-language data and should not be modified directly.
 *
 * @see CountryLocalization
 * @see CountryLanguageRegistry
 */
internal val _countryLanguageMappings_ja: List<CountryLocalization> = listOf(
  CountryLocalization("af", "ペルシア語", "アフガニスタン"),
  CountryLocalization("al", "アルバニア語", "アルバニア"),
  CountryLocalization("dz", "フランス語", "アルジェリア"),
  CountryLocalization("as", "英語", "米領サモア"),
  CountryLocalization("ad", "カタロニア語", "アンドラ"),
  CountryLocalization("ao", "リンガラ語", "アンゴラ"),
  CountryLocalization("ai", "英語", "アンギラ"),
  CountryLocalization("ag", "英語", "アンティグア・バーブーダ"),
  CountryLocalization("ar", "スペイン語", "アルゼンチン"),
  CountryLocalization("am", "アルメニア語", "アルメニア"),
  CountryLocalization("aw", "オランダ語", "アルバ"),
  CountryLocalization("au", "英語", "オーストラリア"),
  CountryLocalization("at", "英語", "オーストリア"),
  CountryLocalization("az", "アゼルバイジャン語", "アゼルバイジャン"),
  CountryLocalization("bs", "英語", "バハマ"),
  CountryLocalization("bh", "アラビア語", "バーレーン"),
  CountryLocalization("bd", "ベンガル語", "バングラデシュ"),
  CountryLocalization("bb", "英語", "バルバドス"),
  CountryLocalization("by", "ベラルーシ語", "ベラルーシ"),
  CountryLocalization("be", "フランス語", "ベルギー"),
  CountryLocalization("bz", "英語", "ベリーズ"),
  CountryLocalization("bj", "フランス語", "ベナン"),
  CountryLocalization("bm", "英語", "バミューダ"),
  CountryLocalization("bt", "ゾンカ語", "ブータン"),
  CountryLocalization("bo", "スペイン語", "ボリビア"),
  CountryLocalization("ba", "ボスニア語", "ボスニア・ヘルツェゴビナ"),
  CountryLocalization("bw", "英語", "ボツワナ"),
  CountryLocalization("br", "ポルトガル語", "ブラジル"),
  CountryLocalization("io", "英語", "英領インド洋地域"),
  CountryLocalization("vg", "英語", "英領ヴァージン諸島"),
  CountryLocalization("bn", "マレー語", "ブルネイ"),
  CountryLocalization("bg", "ブルガリア語", "ブルガリア"),
  CountryLocalization("bf", "フランス語", "ブルキナファソ"),
  CountryLocalization("bi", "フランス語", "ブルンジ"),
  CountryLocalization("kh", "クメール語", "カンボジア"),
  CountryLocalization("cm", "バサ語", "カメルーン"),
  CountryLocalization("ca", "フランス語", "カナダ"),
  CountryLocalization("ic", "スペイン語", "カナリア諸島"),
  CountryLocalization("cv", "カーボベルデ・クレオール語", "カーボベルデ"),
  CountryLocalization("bq", "オランダ語", "オランダ領カリブ"),
  CountryLocalization("ky", "英語", "ケイマン諸島"),
  CountryLocalization("cf", "リンガラ語", "中央アフリカ共和国"),
  CountryLocalization("ea", "スペイン語", "セウタ・メリリャ"),
  CountryLocalization("td", "アラビア語", "チャド"),
  CountryLocalization("cl", "スペイン語", "チリ"),
  CountryLocalization("cn", "チベット語", "中国"),
  CountryLocalization("cx", "英語", "クリスマス島"),
  CountryLocalization("cc", "英語", "ココス(キーリング)諸島"),
  CountryLocalization("co", "スペイン語", "コロンビア"),
  CountryLocalization("km", "アラビア語", "コモロ"),
  CountryLocalization("cg", "リンガラ語", "コンゴ共和国(ブラザビル)"),
  CountryLocalization("cd", "スワヒリ語", "コンゴ民主共和国(キンシャサ)"),
  CountryLocalization("ck", "英語", "クック諸島"),
  CountryLocalization("cr", "スペイン語", "コスタリカ"),
  CountryLocalization("hr", "クロアチア語", "クロアチア"),
  CountryLocalization("cu", "スペイン語", "キューバ"),
  CountryLocalization("cw", "オランダ語", "キュラソー"),
  CountryLocalization("cy", "英語", "キプロス"),
  CountryLocalization("cz", "チェコ語", "チェコ"),
  CountryLocalization("ci", "フランス語", "コートジボワール"),
  CountryLocalization("dk", "英語", "デンマーク"),
  CountryLocalization("dg", "英語", "ディエゴガルシア島"),
  CountryLocalization("dj", "フランス語", "ジブチ"),
  CountryLocalization("dm", "英語", "ドミニカ国"),
  CountryLocalization("do", "スペイン語", "ドミニカ共和国"),
  CountryLocalization("ec", "ケチュア語", "エクアドル"),
  CountryLocalization("eg", "アラビア語", "エジプト"),
  CountryLocalization("sv", "スペイン語", "エルサルバドル"),
  CountryLocalization("gq", "スペイン語", "赤道ギニア"),
  CountryLocalization("er", "ティグリニア語", "エリトリア"),
  CountryLocalization("ee", "エストニア語", "エストニア"),
  CountryLocalization("et", "アムハラ語", "エチオピア"),
  CountryLocalization("fk", "英語", "フォークランド諸島"),
  CountryLocalization("fo", "フェロー語", "フェロー諸島"),
  CountryLocalization("fj", "英語", "フィジー"),
  CountryLocalization("fi", "スウェーデン語", "フィンランド"),
  CountryLocalization("fr", "スイスドイツ語", "フランス"),
  CountryLocalization("gf", "フランス語", "仏領ギアナ"),
  CountryLocalization("pf", "フランス語", "仏領ポリネシア"),
  CountryLocalization("ga", "フランス語", "ガボン"),
  CountryLocalization("gm", "英語", "ガンビア"),
  CountryLocalization("ge", "オセット語", "ジョージア"),
  CountryLocalization("de", "低地ソルブ語", "ドイツ"),
  CountryLocalization("gh", "英語", "ガーナ"),
  CountryLocalization("gi", "英語", "ジブラルタル"),
  CountryLocalization("gr", "ギリシャ語", "ギリシャ"),
  CountryLocalization("gl", "グリーンランド語", "グリーンランド"),
  CountryLocalization("gd", "英語", "グレナダ"),
  CountryLocalization("gp", "フランス語", "グアドループ"),
  CountryLocalization("gu", "英語", "グアム"),
  CountryLocalization("gt", "スペイン語", "グアテマラ"),
  CountryLocalization("gg", "英語", "ガーンジー"),
  CountryLocalization("gn", "フランス語", "ギニア"),
  CountryLocalization("gw", "ポルトガル語", "ギニアビサウ"),
  CountryLocalization("gy", "英語", "ガイアナ"),
  CountryLocalization("ht", "フランス語", "ハイチ"),
  CountryLocalization("hn", "スペイン語", "ホンジュラス"),
  CountryLocalization("hk", "中国語", "中華人民共和国香港特別行政区"),
  CountryLocalization("hu", "ハンガリー語", "ハンガリー"),
  CountryLocalization("is", "アイスランド語", "アイスランド"),
  CountryLocalization("in", "ネパール語", "インド"),
  CountryLocalization("id", "インドネシア語", "インドネシア"),
  CountryLocalization("ir", "ペルシア語", "イラン"),
  CountryLocalization("iq", "北ロル語", "イラク"),
  CountryLocalization("ie", "英語", "アイルランド"),
  CountryLocalization("im", "マン島語", "マン島"),
  CountryLocalization("il", "英語", "イスラエル"),
  CountryLocalization("it", "ドイツ語", "イタリア"),
  CountryLocalization("jm", "英語", "ジャマイカ"),
  CountryLocalization("jp", "日本語", "日本"),
  CountryLocalization("je", "英語", "ジャージー"),
  CountryLocalization("jo", "アラビア語", "ヨルダン"),
  CountryLocalization("kz", "カザフ語", "カザフスタン"),
  CountryLocalization("ke", "ソマリ語", "ケニア"),
  CountryLocalization("ki", "英語", "キリバス"),
  CountryLocalization("xk", "セルビア語", "コソボ"),
  CountryLocalization("kw", "アラビア語", "クウェート"),
  CountryLocalization("kg", "ロシア語", "キルギス"),
  CountryLocalization("la", "ラオ語", "ラオス"),
  CountryLocalization("lv", "ラトビア語", "ラトビア"),
  CountryLocalization("lb", "アラビア語", "レバノン"),
  CountryLocalization("ls", "英語", "レソト"),
  CountryLocalization("lr", "英語", "リベリア"),
  CountryLocalization("ly", "アラビア語", "リビア"),
  CountryLocalization("li", "スイスドイツ語", "リヒテンシュタイン"),
  CountryLocalization("lt", "リトアニア語", "リトアニア"),
  CountryLocalization("lu", "ルクセンブルク語", "ルクセンブルク"),
  CountryLocalization("mo", "ポルトガル語", "中華人民共和国マカオ特別行政区"),
  CountryLocalization("mk", "アルバニア語", "マケドニア"),
  CountryLocalization("mg", "フランス語", "マダガスカル"),
  CountryLocalization("mw", "英語", "マラウイ"),
  CountryLocalization("my", "タミル語", "マレーシア"),
  CountryLocalization("ml", "フランス語", "マリ"),
  CountryLocalization("mt", "英語", "マルタ"),
  CountryLocalization("mh", "英語", "マーシャル諸島"),
  CountryLocalization("mq", "フランス語", "マルティニーク"),
  CountryLocalization("mr", "アラビア語", "モーリタニア"),
  CountryLocalization("mu", "モーリシャス・クレオール語", "モーリシャス"),
  CountryLocalization("yt", "フランス語", "マヨット"),
  CountryLocalization("mx", "スペイン語", "メキシコ"),
  CountryLocalization("fm", "英語", "ミクロネシア連邦"),
  CountryLocalization("md", "ロシア語", "モルドバ"),
  CountryLocalization("mc", "フランス語", "モナコ"),
  CountryLocalization("mn", "モンゴル語", "モンゴル"),
  CountryLocalization("me", "セルビア語", "モンテネグロ"),
  CountryLocalization("ms", "英語", "モントセラト"),
  CountryLocalization("ma", "中央アトラス・タマジクト語", "モロッコ"),
  CountryLocalization("mz", "マクア・ミート語", "モザンビーク"),
  CountryLocalization("mm", "ミャンマー語", "ミャンマー (ビルマ)"),
  CountryLocalization("na", "英語", "ナミビア"),
  CountryLocalization("nr", "英語", "ナウル"),
  CountryLocalization("np", "ネパール語", "ネパール"),
  CountryLocalization("nl", "英語", "オランダ"),
  CountryLocalization("nc", "フランス語", "ニューカレドニア"),
  CountryLocalization("nz", "英語", "ニュージーランド"),
  CountryLocalization("ni", "スペイン語", "ニカラグア"),
  CountryLocalization("ne", "ハウサ語", "ニジェール"),
  CountryLocalization("ng", "ハウサ語", "ナイジェリア"),
  CountryLocalization("nu", "英語", "ニウエ"),
  CountryLocalization("nf", "英語", "ノーフォーク島"),
  CountryLocalization("kp", "韓国語", "北朝鮮"),
  CountryLocalization("mp", "英語", "北マリアナ諸島"),
  CountryLocalization("no", "北サーミ語", "ノルウェー"),
  CountryLocalization("om", "アラビア語", "オマーン"),
  CountryLocalization("pk", "英語", "パキスタン"),
  CountryLocalization("pw", "英語", "パラオ"),
  CountryLocalization("ps", "アラビア語", "パレスチナ自治区"),
  CountryLocalization("pa", "スペイン語", "パナマ"),
  CountryLocalization("pg", "英語", "パプアニューギニア"),
  CountryLocalization("py", "スペイン語", "パラグアイ"),
  CountryLocalization("pe", "スペイン語", "ペルー"),
  CountryLocalization("ph", "フィリピノ語", "フィリピン"),
  CountryLocalization("pn", "英語", "ピトケアン諸島"),
  CountryLocalization("pl", "ポーランド語", "ポーランド"),
  CountryLocalization("pt", "ポルトガル語", "ポルトガル"),
  CountryLocalization("pr", "英語", "プエルトリコ"),
  CountryLocalization("qa", "アラビア語", "カタール"),
  CountryLocalization("ro", "ルーマニア語", "ルーマニア"),
  CountryLocalization("ru", "タタール語", "ロシア"),
  CountryLocalization("rw", "英語", "ルワンダ"),
  CountryLocalization("re", "フランス語", "レユニオン"),
  CountryLocalization("ws", "英語", "サモア"),
  CountryLocalization("sm", "イタリア語", "サンマリノ"),
  CountryLocalization("sa", "アラビア語", "サウジアラビア"),
  CountryLocalization("sn", "フランス語", "セネガル"),
  CountryLocalization("rs", "セルビア語", "セルビア"),
  CountryLocalization("cs", "セルビア語", "セルビア・モンテネグロ"),
  CountryLocalization("sc", "フランス語", "セーシェル"),
  CountryLocalization("sl", "英語", "シエラレオネ"),
  CountryLocalization("sg", "タミル語", "シンガポール"),
  CountryLocalization("sx", "英語", "シント・マールテン"),
  CountryLocalization("sk", "スロバキア語", "スロバキア"),
  CountryLocalization("si", "スロベニア語", "スロベニア"),
  CountryLocalization("sb", "英語", "ソロモン諸島"),
  CountryLocalization("so", "アラビア語", "ソマリア"),
  CountryLocalization("za", "英語", "南アフリカ"),
  CountryLocalization("kr", "韓国語", "韓国"),
  CountryLocalization("ss", "ヌエル語", "南スーダン"),
  CountryLocalization("es", "スペイン語", "スペイン"),
  CountryLocalization("lk", "タミル語", "スリランカ"),
  CountryLocalization("bl", "フランス語", "サン・バルテルミー"),
  CountryLocalization("sh", "英語", "セントヘレナ"),
  CountryLocalization("kn", "英語", "セントクリストファー・ネーヴィス"),
  CountryLocalization("lc", "英語", "セントルシア"),
  CountryLocalization("mf", "フランス語", "サン・マルタン"),
  CountryLocalization("pm", "フランス語", "サンピエール島・ミクロン島"),
  CountryLocalization("vc", "英語", "セントビンセント及びグレナディーン諸島"),
  CountryLocalization("sd", "アラビア語", "スーダン"),
  CountryLocalization("sr", "オランダ語", "スリナム"),
  CountryLocalization("sj", "ノルウェー語(ブークモール)", "スバールバル諸島・ヤンマイエン島"),
  CountryLocalization("sz", "英語", "スワジランド"),
  CountryLocalization("se", "スウェーデン語", "スウェーデン"),
  CountryLocalization("ch", "スイスドイツ語", "スイス"),
  CountryLocalization("sy", "アラビア語", "シリア"),
  CountryLocalization("st", "ポルトガル語", "サントメ・プリンシペ"),
  CountryLocalization("tw", "中国語", "台湾"),
  CountryLocalization("tj", "タジク語", "タジキスタン"),
  CountryLocalization("tz", "マコンデ語", "タンザニア"),
  CountryLocalization("th", "タイ語", "タイ"),
  CountryLocalization("tl", "ポルトガル語", "東ティモール"),
  CountryLocalization("tg", "フランス語", "トーゴ"),
  CountryLocalization("tk", "英語", "トケラウ"),
  CountryLocalization("to", "トンガ語", "トンガ"),
  CountryLocalization("tt", "英語", "トリニダード・トバゴ"),
  CountryLocalization("tn", "フランス語", "チュニジア"),
  CountryLocalization("tr", "トルコ語", "トルコ"),
  CountryLocalization("tm", "トルクメン語", "トルクメニスタン"),
  CountryLocalization("tc", "英語", "タークス・カイコス諸島"),
  CountryLocalization("tv", "英語", "ツバル"),
  CountryLocalization("um", "英語", "合衆国領有小離島"),
  CountryLocalization("vi", "英語", "米領ヴァージン諸島"),
  CountryLocalization("ug", "スワヒリ語", "ウガンダ"),
  CountryLocalization("ua", "ウクライナ語", "ウクライナ"),
  CountryLocalization("ae", "アラビア語", "アラブ首長国連邦"),
  CountryLocalization("gb", "英語", "イギリス"),
  CountryLocalization("us", "ラコタ語", "アメリカ合衆国"),
  CountryLocalization("uy", "スペイン語", "ウルグアイ"),
  CountryLocalization("uz", "ウズベク語", "ウズベキスタン"),
  CountryLocalization("vu", "フランス語", "バヌアツ"),
  CountryLocalization("va", "イタリア語", "バチカン市国"),
  CountryLocalization("ve", "スペイン語", "ベネズエラ"),
  CountryLocalization("vn", "ベトナム語", "ベトナム"),
  CountryLocalization("wf", "フランス語", "ウォリス・フツナ"),
  CountryLocalization("eh", "アラビア語", "西サハラ"),
  CountryLocalization("ye", "アラビア語", "イエメン"),
  CountryLocalization("zm", "英語", "ザンビア"),
  CountryLocalization("zw", "北ンデベレ語", "ジンバブエ"),
  CountryLocalization("ax", "スウェーデン語", "オーランド諸島"),
)
