/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot.atlas.extended

import dev.teogor.xenoglot.atlas.CountryLocalization
import kotlin.collections.List

/**
 * Holds the internal list of country-language mappings used for lookups within the package for
 * language code ti.
 *
 * This property contains a hardcoded list of [CountryLocalization] objects, each representing
 * a country and its associated official languages. This list is used by [CountryLanguageRegistry]
 * to provide access to country-language data and should not be modified directly.
 *
 * @see CountryLocalization
 * @see CountryLanguageRegistry
 */
internal val _countryLanguageMappings_ti: List<CountryLocalization> = listOf(
  CountryLocalization("af", "ፐርሲያኛ", "አፍጋኒስታን"),
  CountryLocalization("al", "አልቤኒኛ", "አልባኒያ"),
  CountryLocalization("dz", "ፈረንሳይኛ", "አልጄሪያ"),
  CountryLocalization("as", "እንግሊዝኛ", "ናይ ኣሜሪካ ሳሞኣ"),
  CountryLocalization("ad", "ካታላን", "አንዶራ"),
  CountryLocalization("ao", "Lingala", "አንጐላ"),
  CountryLocalization("ai", "እንግሊዝኛ", "አንጉኢላ"),
  CountryLocalization("ag", "እንግሊዝኛ", "ኣንቲጓን ባሩዳን"),
  CountryLocalization("ar", "ስፓኒሽ", "አርጀንቲና"),
  CountryLocalization("am", "Armenian", "አርሜኒያ"),
  CountryLocalization("aw", "ደች", "አሩባ"),
  CountryLocalization("au", "እንግሊዝኛ", "አውስትሬሊያ"),
  CountryLocalization("at", "እንግሊዝኛ", "ኦስትሪያ"),
  CountryLocalization("az", "አዜርባይጃንኛ", "አዘርባጃን"),
  CountryLocalization("bs", "እንግሊዝኛ", "ባሃማስ"),
  CountryLocalization("bh", "ዓረበኛ", "ባህሬን"),
  CountryLocalization("bd", "በንጋሊኛ", "ባንግላዲሽ"),
  CountryLocalization("bb", "እንግሊዝኛ", "ባርቤዶስ"),
  CountryLocalization("by", "ቤላራሻኛ", "ቤላሩስ"),
  CountryLocalization("be", "ፈረንሳይኛ", "ቤልጄም"),
  CountryLocalization("bz", "እንግሊዝኛ", "ቤሊዘ"),
  CountryLocalization("bj", "ፈረንሳይኛ", "ቤኒን"),
  CountryLocalization("bm", "እንግሊዝኛ", "ቤርሙዳ"),
  CountryLocalization("bt", "Dzongkha", "ቡህታን"),
  CountryLocalization("bo", "ስፓኒሽ", "ቦሊቪያ"),
  CountryLocalization("ba", "ቦስኒያን", "ቦዝንያን ሄርዘጎቪናን"),
  CountryLocalization("bw", "እንግሊዝኛ", "ቦትስዋና"),
  CountryLocalization("br", "ፖርቱጋሊኛ", "ብራዚል"),
  CountryLocalization("io", "እንግሊዝኛ", "ናይ ብሪጣንያ ህንዳዊ ውቅያኖስ ግዝኣት"),
  CountryLocalization("vg", "እንግሊዝኛ", "ቨርጂን ደሴታት እንግሊዝ"),
  CountryLocalization("bn", "ማላይኛ", "ብሩኒ"),
  CountryLocalization("bg", "ቡልጋሪኛ", "ቡልጌሪያ"),
  CountryLocalization("bf", "ፈረንሳይኛ", "ቡርኪና ፋሶ"),
  CountryLocalization("bi", "ፈረንሳይኛ", "ብሩንዲ"),
  CountryLocalization("kh", "Khmer", "ካምቦዲያ"),
  CountryLocalization("cm", "Basaa", "ካሜሩን"),
  CountryLocalization("ca", "ፈረንሳይኛ", "ካናዳ"),
  CountryLocalization("ic", "ስፓኒሽ", "ደሴታት ካናሪ"),
  CountryLocalization("cv", "kea", "ኬፕ ቬርዴ"),
  CountryLocalization("bq", "ደች", "ካሪቢያን ኔዘርላንድስ"),
  CountryLocalization("ky", "እንግሊዝኛ", "ካይማን ደሴቶች"),
  CountryLocalization("cf", "Lingala", "ማእከላይ ኣፍሪቃ ሪፓብሊክ"),
  CountryLocalization("ea", "ስፓኒሽ", "ሲውታን ሜሊላን"),
  CountryLocalization("td", "ዓረበኛ", "ጫድ"),
  CountryLocalization("cl", "ስፓኒሽ", "ቺሊ"),
  CountryLocalization("cn", "Tibetan", "ቻይና"),
  CountryLocalization("cx", "እንግሊዝኛ", "ደሴታት ክሪስትማስ"),
  CountryLocalization("cc", "እንግሊዝኛ", "ኮኮስ ኬሊንግ ደሴቶች"),
  CountryLocalization("co", "ስፓኒሽ", "ኮሎምቢያ"),
  CountryLocalization("km", "ዓረበኛ", "ኮሞሮስ"),
  CountryLocalization("cg", "Lingala", "ኮንጎ ሪፓብሊክ"),
  CountryLocalization("cd", "ሰዋሂሊኛ", "ኮንጎ"),
  CountryLocalization("ck", "እንግሊዝኛ", "ደሴታት ኩክ"),
  CountryLocalization("cr", "ስፓኒሽ", "ኮስታ ሪካ"),
  CountryLocalization("hr", "ክሮሽያንኛ", "ክሮኤሽያ"),
  CountryLocalization("cu", "ስፓኒሽ", "ኩባ"),
  CountryLocalization("cw", "ደች", "ኩራካዎ"),
  CountryLocalization("cy", "እንግሊዝኛ", "ሳይፕረስ"),
  CountryLocalization("cz", "ቼክኛ", "ቼክ ሪፓብሊክ"),
  CountryLocalization("ci", "ፈረንሳይኛ", "ኮት ዲቯር"),
  CountryLocalization("dk", "እንግሊዝኛ", "ዴንማርክ"),
  CountryLocalization("dg", "እንግሊዝኛ", "ዲየጎ ጋርሺያ"),
  CountryLocalization("dj", "ፈረንሳይኛ", "ጂቡቲ"),
  CountryLocalization("dm", "እንግሊዝኛ", "ዶሚኒካ"),
  CountryLocalization("do", "ስፓኒሽ", "ዶመኒካ ሪፓብሊክ"),
  CountryLocalization("ec", "Quechua", "ኢኳዶር"),
  CountryLocalization("eg", "ዓረበኛ", "ግብጽ"),
  CountryLocalization("sv", "ስፓኒሽ", "ኤል ሳልቫዶር"),
  CountryLocalization("gq", "ስፓኒሽ", "ኢኳቶሪያል ጊኒ"),
  CountryLocalization("er", "ትግርኛ", "ኤርትራ"),
  CountryLocalization("ee", "ኤስቶኒአን", "ኤስቶኒያ"),
  CountryLocalization("et", "አምሐረኛ", "ኢትዮጵያ"),
  CountryLocalization("fk", "እንግሊዝኛ", "ደሴታት ፎክላንድ"),
  CountryLocalization("fo", "ፋሮኛ", "ደሴታት ፋራኦ"),
  CountryLocalization("fj", "እንግሊዝኛ", "ፊጂ"),
  CountryLocalization("fi", "ስዊድንኛ", "ፊንላንድ"),
  CountryLocalization("fr", "Swiss German", "ፈረንሳይ"),
  CountryLocalization("gf", "ፈረንሳይኛ", "ናይ ፈረንሳይ ጉይና"),
  CountryLocalization("pf", "ፈረንሳይኛ", "ናይ ፈረንሳይ ፖሊነዝያ"),
  CountryLocalization("ga", "ፈረንሳይኛ", "ጋቦን"),
  CountryLocalization("gm", "እንግሊዝኛ", "ጋምቢያ"),
  CountryLocalization("ge", "Ossetic", "ጆርጂያ"),
  CountryLocalization("de", "Lower Sorbian", "ጀርመን"),
  CountryLocalization("gh", "እንግሊዝኛ", "ጋና"),
  CountryLocalization("gi", "እንግሊዝኛ", "ጊብራልታር"),
  CountryLocalization("gr", "ግሪከኛ", "ግሪክ"),
  CountryLocalization("gl", "Kalaallisut", "ግሪንላንድ"),
  CountryLocalization("gd", "እንግሊዝኛ", "ግሬናዳ"),
  CountryLocalization("gp", "ፈረንሳይኛ", "ጉዋደሉፕ"),
  CountryLocalization("gu", "እንግሊዝኛ", "ጉዋም"),
  CountryLocalization("gt", "ስፓኒሽ", "ጉዋቲማላ"),
  CountryLocalization("gg", "እንግሊዝኛ", "ገርንሲ"),
  CountryLocalization("gn", "ፈረንሳይኛ", "ጊኒ"),
  CountryLocalization("gw", "ፖርቱጋሊኛ", "ቢሳዎ"),
  CountryLocalization("gy", "እንግሊዝኛ", "ጉያና"),
  CountryLocalization("ht", "ፈረንሳይኛ", "ሀይቲ"),
  CountryLocalization("hn", "ስፓኒሽ", "ሆንዱራስ"),
  CountryLocalization("hk", "Chinese", "ሆንግ ኮንግ"),
  CountryLocalization("hu", "ሀንጋሪኛ", "ሀንጋሪ"),
  CountryLocalization("is", "አይስላንደኛ", "አይስላንድ"),
  CountryLocalization("in", "ኔፖሊኛ", "ህንዲ"),
  CountryLocalization("id", "Indonesian", "ኢንዶኔዢያ"),
  CountryLocalization("ir", "ፐርሲያኛ", "ኢራን"),
  CountryLocalization("iq", "lrc", "ኢራቅ"),
  CountryLocalization("ie", "እንግሊዝኛ", "አየርላንድ"),
  CountryLocalization("im", "Manx", "አይል ኦፍ ማን"),
  CountryLocalization("il", "እንግሊዝኛ", "እስራኤል"),
  CountryLocalization("it", "ጀርመን", "ጣሊያን"),
  CountryLocalization("jm", "እንግሊዝኛ", "ጃማይካ"),
  CountryLocalization("jp", "ጃፓንኛ", "ጃፓን"),
  CountryLocalization("je", "እንግሊዝኛ", "ጀርሲ"),
  CountryLocalization("jo", "ዓረበኛ", "ጆርዳን"),
  CountryLocalization("kz", "Kazakh", "ካዛኪስታን"),
  CountryLocalization("ke", "Somali", "ኬንያ"),
  CountryLocalization("ki", "እንግሊዝኛ", "ኪሪባቲ"),
  CountryLocalization("xk", "ሰርቢኛ", "ኮሶቮ"),
  CountryLocalization("kw", "ዓረበኛ", "ክዌት"),
  CountryLocalization("kg", "ራሽኛ", "ኪርጂስታን"),
  CountryLocalization("la", "Lao", "ላኦስ"),
  CountryLocalization("lv", "ላቲቪያን", "ላትቪያ"),
  CountryLocalization("lb", "ዓረበኛ", "ሊባኖስ"),
  CountryLocalization("ls", "እንግሊዝኛ", "ሌሶቶ"),
  CountryLocalization("lr", "እንግሊዝኛ", "ላይቤሪያ"),
  CountryLocalization("ly", "ዓረበኛ", "ሊቢያ"),
  CountryLocalization("li", "Swiss German", "ሊችተንስታይን"),
  CountryLocalization("lt", "ሊቱአኒየን", "ሊቱዌኒያ"),
  CountryLocalization("lu", "Luxembourgish", "ሉክሰምበርግ"),
  CountryLocalization("mo", "ፖርቱጋሊኛ", "ማካዎ"),
  CountryLocalization("mk", "አልቤኒኛ", "ማከዶኒያ"),
  CountryLocalization("mg", "ፈረንሳይኛ", "ማዳጋስካር"),
  CountryLocalization("mw", "እንግሊዝኛ", "ማላዊ"),
  CountryLocalization("my", "ታሚልኛ", "ማሌዢያ"),
  CountryLocalization("ml", "ፈረንሳይኛ", "ማሊ"),
  CountryLocalization("mt", "እንግሊዝኛ", "ማልታ"),
  CountryLocalization("mh", "እንግሊዝኛ", "ማርሻል አይላንድ"),
  CountryLocalization("mq", "ፈረንሳይኛ", "ማርቲኒክ"),
  CountryLocalization("mr", "ዓረበኛ", "ሞሪቴኒያ"),
  CountryLocalization("mu", "mfe", "ማሩሸስ"),
  CountryLocalization("yt", "ፈረንሳይኛ", "ሜይኦቴ"),
  CountryLocalization("mx", "ስፓኒሽ", "ሜክሲኮ"),
  CountryLocalization("fm", "እንግሊዝኛ", "ሚክሮኔዢያ"),
  CountryLocalization("md", "ራሽኛ", "ሞልዶቫ"),
  CountryLocalization("mc", "ፈረንሳይኛ", "ሞናኮ"),
  CountryLocalization("mn", "Mongolian", "ሞንጎሊያ"),
  CountryLocalization("me", "ሰርቢኛ", "ሞንቴኔግሮ"),
  CountryLocalization("ms", "እንግሊዝኛ", "ሞንትሴራት"),
  CountryLocalization("ma", "tzm", "ሞሮኮ"),
  CountryLocalization("mz", "mgh", "ሞዛምቢክ"),
  CountryLocalization("mm", "Burmese", "ማያንማር"),
  CountryLocalization("na", "እንግሊዝኛ", "ናሚቢያ"),
  CountryLocalization("nr", "እንግሊዝኛ", "ናኡሩ"),
  CountryLocalization("np", "ኔፖሊኛ", "ኔፓል"),
  CountryLocalization("nl", "እንግሊዝኛ", "ኔዘርላንድስ"),
  CountryLocalization("nc", "ፈረንሳይኛ", "ኒው ካሌዶኒያ"),
  CountryLocalization("nz", "እንግሊዝኛ", "ኒው ዚላንድ"),
  CountryLocalization("ni", "ስፓኒሽ", "ኒካራጓ"),
  CountryLocalization("ne", "Hausa", "ኒጀር"),
  CountryLocalization("ng", "Hausa", "ናይጄሪያ"),
  CountryLocalization("nu", "እንግሊዝኛ", "ኒኡይ"),
  CountryLocalization("nf", "እንግሊዝኛ", "ኖርፎልክ ደሴት"),
  CountryLocalization("kp", "ኮሪያኛ", "ሰሜን ኮሪያ"),
  CountryLocalization("mp", "እንግሊዝኛ", "ደሴታት ሰሜናዊ ማሪያና"),
  CountryLocalization("no", "Northern Sami", "ኖርዌ"),
  CountryLocalization("om", "ዓረበኛ", "ኦማን"),
  CountryLocalization("pk", "እንግሊዝኛ", "ፓኪስታን"),
  CountryLocalization("pw", "እንግሊዝኛ", "ፓላው"),
  CountryLocalization("ps", "ዓረበኛ", "ምምሕዳር ፍልስጤም"),
  CountryLocalization("pa", "ስፓኒሽ", "ፓናማ"),
  CountryLocalization("pg", "እንግሊዝኛ", "ፓፑዋ ኒው ጊኒ"),
  CountryLocalization("py", "ስፓኒሽ", "ፓራጓይ"),
  CountryLocalization("pe", "ስፓኒሽ", "ፔሩ"),
  CountryLocalization("ph", "ታጋሎገኛ", "ፊሊፒንስ"),
  CountryLocalization("pn", "እንግሊዝኛ", "ፒትካኢርን"),
  CountryLocalization("pl", "ፖሊሽ", "ፖላንድ"),
  CountryLocalization("pt", "ፖርቱጋሊኛ", "ፖርቱጋል"),
  CountryLocalization("pr", "እንግሊዝኛ", "ፖርታ ሪኮ"),
  CountryLocalization("qa", "ዓረበኛ", "ቀጠር"),
  CountryLocalization("ro", "ሮማኒያን", "ሮሜኒያ"),
  CountryLocalization("ru", "Tatar", "ራሺያ"),
  CountryLocalization("rw", "እንግሊዝኛ", "ሩዋንዳ"),
  CountryLocalization("re", "ፈረንሳይኛ", "ሪዩኒየን"),
  CountryLocalization("ws", "እንግሊዝኛ", "ሳሞአ"),
  CountryLocalization("sm", "ጣሊያንኛ", "ሳን ማሪኖ"),
  CountryLocalization("sa", "ዓረበኛ", "ስዑዲ ዓረብ"),
  CountryLocalization("sn", "ፈረንሳይኛ", "ሴኔጋል"),
  CountryLocalization("rs", "ሰርቢኛ", "ሰርቢያ"),
  CountryLocalization("cs", "ሰርቢኛ", "Serbia and Montenegro"),
  CountryLocalization("sc", "ፈረንሳይኛ", "ሲሼልስ"),
  CountryLocalization("sl", "እንግሊዝኛ", "ሴራሊዮን"),
  CountryLocalization("sg", "ታሚልኛ", "ሲንጋፖር"),
  CountryLocalization("sx", "እንግሊዝኛ", "ሲንት ማርቲን"),
  CountryLocalization("sk", "ስሎቨክኛ", "ስሎቫኪያ"),
  CountryLocalization("si", "ስቁቪኛ", "ስሎቬኒያ"),
  CountryLocalization("sb", "እንግሊዝኛ", "ሰሎሞን ደሴት"),
  CountryLocalization("so", "ዓረበኛ", "ሱማሌ"),
  CountryLocalization("za", "እንግሊዝኛ", "ደቡብ አፍሪካ"),
  CountryLocalization("kr", "ኮሪያኛ", "ደቡብ ኮሪያ"),
  CountryLocalization("ss", "nus", "ደቡብ ሱዳን"),
  CountryLocalization("es", "ስፓኒሽ", "ስፔን"),
  CountryLocalization("lk", "ታሚልኛ", "ሲሪላንካ"),
  CountryLocalization("bl", "ፈረንሳይኛ", "ቅዱስ ባርተለሚይ"),
  CountryLocalization("sh", "እንግሊዝኛ", "ሴንት ሄለና"),
  CountryLocalization("kn", "እንግሊዝኛ", "ቅዱስ ኪትስን ኔቪስን"),
  CountryLocalization("lc", "እንግሊዝኛ", "ሴንት ሉቺያ"),
  CountryLocalization("mf", "ፈረንሳይኛ", "ሴንት ማርቲን"),
  CountryLocalization("pm", "ፈረንሳይኛ", "ቅዱስ ፒዬርን ሚኩኤሎን"),
  CountryLocalization("vc", "እንግሊዝኛ", "ቅዱስ ቪንሴንትን ግሬናዲንስን"),
  CountryLocalization("sd", "ዓረበኛ", "ሱዳን"),
  CountryLocalization("sr", "ደች", "ሱሪናም"),
  CountryLocalization("sj", "Norwegian Bokmål", "ስቫልባርድን ዣን ማየን ደሴታት"),
  CountryLocalization("sz", "እንግሊዝኛ", "ሱዋዚላንድ"),
  CountryLocalization("se", "ስዊድንኛ", "ስዊድን"),
  CountryLocalization("ch", "Swiss German", "ስዊዘርላንድ"),
  CountryLocalization("sy", "ዓረበኛ", "ሲሪያ"),
  CountryLocalization("st", "ፖርቱጋሊኛ", "ሳኦ ቶሜን ፕሪንሲፔን"),
  CountryLocalization("tw", "Chinese", "ታይዋን"),
  CountryLocalization("tj", "Tajik", "ታጃኪስታን"),
  CountryLocalization("tz", "kde", "ታንዛኒያ"),
  CountryLocalization("th", "ታይኛ", "ታይላንድ"),
  CountryLocalization("tl", "ፖርቱጋሊኛ", "ምብራቕ ቲሞር"),
  CountryLocalization("tg", "ፈረንሳይኛ", "ቶጐ"),
  CountryLocalization("tk", "እንግሊዝኛ", "ቶክላው"),
  CountryLocalization("to", "Tongan", "ቶንጋ"),
  CountryLocalization("tt", "እንግሊዝኛ", "ትሪኒዳድን ቶባጎን"),
  CountryLocalization("tn", "ፈረንሳይኛ", "ቱኒዚያ"),
  CountryLocalization("tr", "ቱርከኛ", "ቱርክ"),
  CountryLocalization("tm", "ናይ ቱርኪ ሰብዓይ (ቱርካዊ)", "ቱርክሜኒስታን"),
  CountryLocalization("tc", "እንግሊዝኛ", "ደሴታት ቱርክን ካይኮስን"),
  CountryLocalization("tv", "እንግሊዝኛ", "ቱቫሉ"),
  CountryLocalization("um", "እንግሊዝኛ", "ናይ ኣሜሪካ ፍንትት ዝበሉ ደሴታት"),
  CountryLocalization("vi", "እንግሊዝኛ", "ቨርጂን ደሴታት ኣሜሪካ"),
  CountryLocalization("ug", "ሰዋሂሊኛ", "ዩጋንዳ"),
  CountryLocalization("ua", "ዩክረኒኛ", "ዩክሬን"),
  CountryLocalization("ae", "ዓረበኛ", "ሕቡራት ኢማራት ዓረብ"),
  CountryLocalization("gb", "እንግሊዝኛ", "እንግሊዝ"),
  CountryLocalization("us", "lkt", "አሜሪካ"),
  CountryLocalization("uy", "ስፓኒሽ", "ኡራጓይ"),
  CountryLocalization("uz", "ኡዝበክኛ", "ዩዝበኪስታን"),
  CountryLocalization("vu", "ፈረንሳይኛ", "ቫኑአቱ"),
  CountryLocalization("va", "ጣሊያንኛ", "ቫቲካን"),
  CountryLocalization("ve", "ስፓኒሽ", "ቬንዙዌላ"),
  CountryLocalization("vn", "ቪትናምኛ", "ቬትናም"),
  CountryLocalization("wf", "ፈረንሳይኛ", "ዋሊስን ፉቱናን"),
  CountryLocalization("eh", "ዓረበኛ", "ምዕራባዊ ሳህራ"),
  CountryLocalization("ye", "ዓረበኛ", "የመን"),
  CountryLocalization("zm", "እንግሊዝኛ", "ዛምቢያ"),
  CountryLocalization("zw", "North Ndebele", "ዚምቧቤ"),
  CountryLocalization("ax", "ስዊድንኛ", "ደሴታት ኣላንድ"),
)
