/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot.atlas.extended

import dev.teogor.xenoglot.atlas.CountryLocalization
import kotlin.collections.List

/**
 * Holds the internal list of country-language mappings used for lookups within the package for
 * language code lb.
 *
 * This property contains a hardcoded list of [CountryLocalization] objects, each representing
 * a country and its associated official languages. This list is used by [CountryLanguageRegistry]
 * to provide access to country-language data and should not be modified directly.
 *
 * @see CountryLocalization
 * @see CountryLanguageRegistry
 */
internal val _countryLanguageMappings_lb: List<CountryLocalization> = listOf(
  CountryLocalization("af", "Persesch", "Afghanistan"),
  CountryLocalization("al", "Albanesch", "Albanien"),
  CountryLocalization("dz", "Franséisch", "Algerien"),
  CountryLocalization("as", "Englesch", "Amerikanesch-Samoa"),
  CountryLocalization("ad", "Katalanesch", "Andorra"),
  CountryLocalization("ao", "Lingala", "Angola"),
  CountryLocalization("ai", "Englesch", "Anguilla"),
  CountryLocalization("ag", "Englesch", "Antigua a Barbuda"),
  CountryLocalization("ar", "Spuenesch", "Argentinien"),
  CountryLocalization("am", "Armenesch", "Armenien"),
  CountryLocalization("aw", "Hollännesch", "Aruba"),
  CountryLocalization("au", "Englesch", "Australien"),
  CountryLocalization("at", "Englesch", "Éisträich"),
  CountryLocalization("az", "Aserbaidschanesch", "Aserbaidschan"),
  CountryLocalization("bs", "Englesch", "Bahamas"),
  CountryLocalization("bh", "Arabesch", "Bahrain"),
  CountryLocalization("bd", "Bengalesch", "Bangladesch"),
  CountryLocalization("bb", "Englesch", "Barbados"),
  CountryLocalization("by", "Wäissrussesch", "Wäissrussland"),
  CountryLocalization("be", "Franséisch", "Belsch"),
  CountryLocalization("bz", "Englesch", "Belize"),
  CountryLocalization("bj", "Franséisch", "Benin"),
  CountryLocalization("bm", "Englesch", "Bermuda"),
  CountryLocalization("bt", "Bhutanesch", "Bhutan"),
  CountryLocalization("bo", "Spuenesch", "Bolivien"),
  CountryLocalization("ba", "Bosnesch", "Bosnien an Herzegowina"),
  CountryLocalization("bw", "Englesch", "Botsuana"),
  CountryLocalization("br", "Portugisesch", "Brasilien"),
  CountryLocalization("io", "Englesch", "Britescht Territorium am Indeschen Ozean"),
  CountryLocalization("vg", "Englesch", "Britesch Joffereninselen"),
  CountryLocalization("bn", "Malaiesch", "Brunei"),
  CountryLocalization("bg", "Bulgaresch", "Bulgarien"),
  CountryLocalization("bf", "Franséisch", "Burkina Faso"),
  CountryLocalization("bi", "Franséisch", "Burundi"),
  CountryLocalization("kh", "Kambodschanesch", "Kambodscha"),
  CountryLocalization("cm", "Basaa-Sprooch", "Kamerun"),
  CountryLocalization("ca", "Franséisch", "Kanada"),
  CountryLocalization("ic", "Spuenesch", "Kanaresch Inselen"),
  CountryLocalization("cv", "Kabuverdianu", "Kap Verde"),
  CountryLocalization("bq", "Hollännesch", "Karibescht Holland"),
  CountryLocalization("ky", "Englesch", "Kaimaninselen"),
  CountryLocalization("cf", "Lingala", "Zentralafrikanesch Republik"),
  CountryLocalization("ea", "Spuenesch", "Ceuta a Melilla"),
  CountryLocalization("td", "Arabesch", "Tschad"),
  CountryLocalization("cl", "Spuenesch", "Chile"),
  CountryLocalization("cn", "Tibetesch", "China"),
  CountryLocalization("cx", "Englesch", "Chrëschtdagsinsel"),
  CountryLocalization("cc", "Englesch", "Kokosinselen"),
  CountryLocalization("co", "Spuenesch", "Kolumbien"),
  CountryLocalization("km", "Arabesch", "Komoren"),
  CountryLocalization("cg", "Lingala", "Kongo-Brazzaville"),
  CountryLocalization("cd", "Suaheli", "Kongo-Kinshasa"),
  CountryLocalization("ck", "Englesch", "Cookinselen"),
  CountryLocalization("cr", "Spuenesch", "Costa Rica"),
  CountryLocalization("hr", "Kroatesch", "Kroatien"),
  CountryLocalization("cu", "Spuenesch", "Kuba"),
  CountryLocalization("cw", "Hollännesch", "Curaçao"),
  CountryLocalization("cy", "Englesch", "Zypern"),
  CountryLocalization("cz", "Tschechesch", "Tschechien"),
  CountryLocalization("ci", "Franséisch", "Côte d’Ivoire"),
  CountryLocalization("dk", "Englesch", "Dänemark"),
  CountryLocalization("dg", "Englesch", "Diego Garcia"),
  CountryLocalization("dj", "Franséisch", "Dschibuti"),
  CountryLocalization("dm", "Englesch", "Dominica"),
  CountryLocalization("do", "Spuenesch", "Dominikanesch Republik"),
  CountryLocalization("ec", "Quechua", "Ecuador"),
  CountryLocalization("eg", "Arabesch", "Egypten"),
  CountryLocalization("sv", "Spuenesch", "El Salvador"),
  CountryLocalization("gq", "Spuenesch", "Equatorialguinea"),
  CountryLocalization("er", "Tigrinja", "Eritrea"),
  CountryLocalization("ee", "Estnesch", "Estland"),
  CountryLocalization("et", "Amharesch", "Ethiopien"),
  CountryLocalization("fk", "Englesch", "Falklandinselen"),
  CountryLocalization("fo", "Färöesch", "Färöer"),
  CountryLocalization("fj", "Englesch", "Fidschi"),
  CountryLocalization("fi", "Schwedesch", "Finnland"),
  CountryLocalization("fr", "Schwäizerdäitsch", "Frankräich"),
  CountryLocalization("gf", "Franséisch", "Guayane"),
  CountryLocalization("pf", "Franséisch", "Franséisch-Polynesien"),
  CountryLocalization("ga", "Franséisch", "Gabun"),
  CountryLocalization("gm", "Englesch", "Gambia"),
  CountryLocalization("ge", "Ossetesch", "Georgien"),
  CountryLocalization("de", "Niddersorbesch", "Däitschland"),
  CountryLocalization("gh", "Englesch", "Ghana"),
  CountryLocalization("gi", "Englesch", "Gibraltar"),
  CountryLocalization("gr", "Griichesch", "Griicheland"),
  CountryLocalization("gl", "Grönlännesch", "Grönland"),
  CountryLocalization("gd", "Englesch", "Grenada"),
  CountryLocalization("gp", "Franséisch", "Guadeloupe"),
  CountryLocalization("gu", "Englesch", "Guam"),
  CountryLocalization("gt", "Spuenesch", "Guatemala"),
  CountryLocalization("gg", "Englesch", "Guernsey"),
  CountryLocalization("gn", "Franséisch", "Guinea"),
  CountryLocalization("gw", "Portugisesch", "Guinea-Bissau"),
  CountryLocalization("gy", "Englesch", "Guyana"),
  CountryLocalization("ht", "Franséisch", "Haiti"),
  CountryLocalization("hn", "Spuenesch", "Honduras"),
  CountryLocalization("hk", "Chinesesch", "Spezialverwaltungszon Hong Kong"),
  CountryLocalization("hu", "Ungaresch", "Ungarn"),
  CountryLocalization("is", "Islännesch", "Island"),
  CountryLocalization("in", "Nepalesesch", "Indien"),
  CountryLocalization("id", "Indonesian", "Indonesien"),
  CountryLocalization("ir", "Persesch", "Iran"),
  CountryLocalization("iq", "lrc", "Irak"),
  CountryLocalization("ie", "Englesch", "Irland"),
  CountryLocalization("im", "Manx", "Isle of Man"),
  CountryLocalization("il", "Englesch", "Israel"),
  CountryLocalization("it", "Däitsch", "Italien"),
  CountryLocalization("jm", "Englesch", "Jamaika"),
  CountryLocalization("jp", "Japanesch", "Japan"),
  CountryLocalization("je", "Englesch", "Jersey"),
  CountryLocalization("jo", "Arabesch", "Jordanien"),
  CountryLocalization("kz", "Kasachesch", "Kasachstan"),
  CountryLocalization("ke", "Somali", "Kenia"),
  CountryLocalization("ki", "Englesch", "Kiribati"),
  CountryLocalization("xk", "Serbesch", "Kosovo"),
  CountryLocalization("kw", "Arabesch", "Kuwait"),
  CountryLocalization("kg", "Russesch", "Kirgisistan"),
  CountryLocalization("la", "Laotesch", "Laos"),
  CountryLocalization("lv", "Lettesch", "Lettland"),
  CountryLocalization("lb", "Arabesch", "Libanon"),
  CountryLocalization("ls", "Englesch", "Lesotho"),
  CountryLocalization("lr", "Englesch", "Liberia"),
  CountryLocalization("ly", "Arabesch", "Libyen"),
  CountryLocalization("li", "Schwäizerdäitsch", "Liechtenstein"),
  CountryLocalization("lt", "Litauesch", "Litauen"),
  CountryLocalization("lu", "Lëtzebuergesch", "Lëtzebuerg"),
  CountryLocalization("mo", "Portugisesch", "Spezialverwaltungszon Macau"),
  CountryLocalization("mk", "Albanesch", "Mazedonien"),
  CountryLocalization("mg", "Franséisch", "Madagaskar"),
  CountryLocalization("mw", "Englesch", "Malawi"),
  CountryLocalization("my", "Tamilesch", "Malaysia"),
  CountryLocalization("ml", "Franséisch", "Mali"),
  CountryLocalization("mt", "Englesch", "Malta"),
  CountryLocalization("mh", "Englesch", "Marshallinselen"),
  CountryLocalization("mq", "Franséisch", "Martinique"),
  CountryLocalization("mr", "Arabesch", "Mauretanien"),
  CountryLocalization("mu", "Morisyen", "Mauritius"),
  CountryLocalization("yt", "Franséisch", "Mayotte"),
  CountryLocalization("mx", "Spuenesch", "Mexiko"),
  CountryLocalization("fm", "Englesch", "Mikronesien"),
  CountryLocalization("md", "Russesch", "Moldawien"),
  CountryLocalization("mc", "Franséisch", "Monaco"),
  CountryLocalization("mn", "Mongolesch", "Mongolei"),
  CountryLocalization("me", "Serbesch", "Montenegro"),
  CountryLocalization("ms", "Englesch", "Montserrat"),
  CountryLocalization("ma", "Mëttlert-Atlas-Tamazight", "Marokko"),
  CountryLocalization("mz", "Makhuwa-Meetto", "Mosambik"),
  CountryLocalization("mm", "Birmanesch", "Myanmar"),
  CountryLocalization("na", "Englesch", "Namibia"),
  CountryLocalization("nr", "Englesch", "Nauru"),
  CountryLocalization("np", "Nepalesesch", "Nepal"),
  CountryLocalization("nl", "Englesch", "Holland"),
  CountryLocalization("nc", "Franséisch", "Neikaledonien"),
  CountryLocalization("nz", "Englesch", "Neiséiland"),
  CountryLocalization("ni", "Spuenesch", "Nicaragua"),
  CountryLocalization("ne", "Hausa", "Niger"),
  CountryLocalization("ng", "Hausa", "Nigeria"),
  CountryLocalization("nu", "Englesch", "Niue"),
  CountryLocalization("nf", "Englesch", "Norfolkinsel"),
  CountryLocalization("kp", "Koreanesch", "Nordkorea"),
  CountryLocalization("mp", "Englesch", "Nërdlech Marianen"),
  CountryLocalization("no", "Nordsamesch", "Norwegen"),
  CountryLocalization("om", "Arabesch", "Oman"),
  CountryLocalization("pk", "Englesch", "Pakistan"),
  CountryLocalization("pw", "Englesch", "Palau"),
  CountryLocalization("ps", "Arabesch", "Palestinensesch Autonomiegebidder"),
  CountryLocalization("pa", "Spuenesch", "Panama"),
  CountryLocalization("pg", "Englesch", "Papua-Neiguinea"),
  CountryLocalization("py", "Spuenesch", "Paraguay"),
  CountryLocalization("pe", "Spuenesch", "Peru"),
  CountryLocalization("ph", "Filipino", "Philippinnen"),
  CountryLocalization("pn", "Englesch", "Pitcairninselen"),
  CountryLocalization("pl", "Polnesch", "Polen"),
  CountryLocalization("pt", "Portugisesch", "Portugal"),
  CountryLocalization("pr", "Englesch", "Puerto Rico"),
  CountryLocalization("qa", "Arabesch", "Katar"),
  CountryLocalization("ro", "Rumänesch", "Rumänien"),
  CountryLocalization("ru", "Tataresch", "Russland"),
  CountryLocalization("rw", "Englesch", "Ruanda"),
  CountryLocalization("re", "Franséisch", "Réunion"),
  CountryLocalization("ws", "Englesch", "Samoa"),
  CountryLocalization("sm", "Italienesch", "San Marino"),
  CountryLocalization("sa", "Arabesch", "Saudi-Arabien"),
  CountryLocalization("sn", "Franséisch", "Senegal"),
  CountryLocalization("rs", "Serbesch", "Serbien"),
  CountryLocalization("cs", "Serbesch", "Serbia and Montenegro"),
  CountryLocalization("sc", "Franséisch", "Seychellen"),
  CountryLocalization("sl", "Englesch", "Sierra Leone"),
  CountryLocalization("sg", "Tamilesch", "Singapur"),
  CountryLocalization("sx", "Englesch", "Sint Maarten"),
  CountryLocalization("sk", "Slowakesch", "Slowakei"),
  CountryLocalization("si", "Slowenesch", "Slowenien"),
  CountryLocalization("sb", "Englesch", "Salomonen"),
  CountryLocalization("so", "Arabesch", "Somalia"),
  CountryLocalization("za", "Englesch", "Südafrika"),
  CountryLocalization("kr", "Koreanesch", "Südkorea"),
  CountryLocalization("ss", "Nuer", "Südsudan"),
  CountryLocalization("es", "Spuenesch", "Spanien"),
  CountryLocalization("lk", "Tamilesch", "Sri Lanka"),
  CountryLocalization("bl", "Franséisch", "Saint-Barthélemy"),
  CountryLocalization("sh", "Englesch", "St. Helena"),
  CountryLocalization("kn", "Englesch", "St. Kitts an Nevis"),
  CountryLocalization("lc", "Englesch", "St. Lucia"),
  CountryLocalization("mf", "Franséisch", "St. Martin"),
  CountryLocalization("pm", "Franséisch", "St. Pierre a Miquelon"),
  CountryLocalization("vc", "Englesch", "St. Vincent an d’Grenadinnen"),
  CountryLocalization("sd", "Arabesch", "Sudan"),
  CountryLocalization("sr", "Hollännesch", "Suriname"),
  CountryLocalization("sj", "Norwegesch Bokmål", "Svalbard a Jan Mayen"),
  CountryLocalization("sz", "Englesch", "Swasiland"),
  CountryLocalization("se", "Schwedesch", "Schweden"),
  CountryLocalization("ch", "Schwäizerdäitsch", "Schwäiz"),
  CountryLocalization("sy", "Arabesch", "Syrien"),
  CountryLocalization("st", "Portugisesch", "São Tomé a Príncipe"),
  CountryLocalization("tw", "Chinesesch", "Taiwan"),
  CountryLocalization("tj", "Tadschikesch", "Tadschikistan"),
  CountryLocalization("tz", "Makonde", "Tansania"),
  CountryLocalization("th", "Thailännesch", "Thailand"),
  CountryLocalization("tl", "Portugisesch", "Osttimor"),
  CountryLocalization("tg", "Franséisch", "Togo"),
  CountryLocalization("tk", "Englesch", "Tokelau"),
  CountryLocalization("to", "Tongaesch", "Tonga"),
  CountryLocalization("tt", "Englesch", "Trinidad an Tobago"),
  CountryLocalization("tn", "Franséisch", "Tunesien"),
  CountryLocalization("tr", "Tierkesch", "Tierkei"),
  CountryLocalization("tm", "Turkmenesch", "Turkmenistan"),
  CountryLocalization("tc", "Englesch", "Turks- a Caicosinselen"),
  CountryLocalization("tv", "Englesch", "Tuvalu"),
  CountryLocalization("um", "Englesch", "Amerikanesch-Ozeanien"),
  CountryLocalization("vi", "Englesch", "Amerikanesch Joffereninselen"),
  CountryLocalization("ug", "Suaheli", "Uganda"),
  CountryLocalization("ua", "Ukrainesch", "Ukrain"),
  CountryLocalization("ae", "Arabesch", "Vereenegt Arabesch Emirater"),
  CountryLocalization("gb", "Englesch", "Groussbritannien"),
  CountryLocalization("us", "Lakota-Sprooch", "Vereenegt Staaten"),
  CountryLocalization("uy", "Spuenesch", "Uruguay"),
  CountryLocalization("uz", "Usbekesch", "Usbekistan"),
  CountryLocalization("vu", "Franséisch", "Vanuatu"),
  CountryLocalization("va", "Italienesch", "Vatikanstad"),
  CountryLocalization("ve", "Spuenesch", "Venezuela"),
  CountryLocalization("vn", "Vietnamesesch", "Vietnam"),
  CountryLocalization("wf", "Franséisch", "Wallis a Futuna"),
  CountryLocalization("eh", "Arabesch", "Westsahara"),
  CountryLocalization("ye", "Arabesch", "Jemen"),
  CountryLocalization("zm", "Englesch", "Sambia"),
  CountryLocalization("zw", "Nord-Ndebele-Sprooch", "Simbabwe"),
  CountryLocalization("ax", "Schwedesch", "Ålandinselen"),
)
