/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot.atlas.extended

import dev.teogor.xenoglot.atlas.CountryLocalization
import kotlin.collections.List

/**
 * Holds the internal list of country-language mappings used for lookups within the package for
 * language code sr.
 *
 * This property contains a hardcoded list of [CountryLocalization] objects, each representing
 * a country and its associated official languages. This list is used by [CountryLanguageRegistry]
 * to provide access to country-language data and should not be modified directly.
 *
 * @see CountryLocalization
 * @see CountryLanguageRegistry
 */
internal val _countryLanguageMappings_sr: List<CountryLocalization> = listOf(
  CountryLocalization("af", "персијски", "Авганистан"),
  CountryLocalization("al", "албански", "Албанија"),
  CountryLocalization("dz", "француски", "Алжир"),
  CountryLocalization("as", "енглески", "Америчка Самоа"),
  CountryLocalization("ad", "каталонски", "Андора"),
  CountryLocalization("ao", "лингала", "Ангола"),
  CountryLocalization("ai", "енглески", "Ангвила"),
  CountryLocalization("ag", "енглески", "Антигва и Барбуда"),
  CountryLocalization("ar", "шпански", "Аргентина"),
  CountryLocalization("am", "јерменски", "Јерменија"),
  CountryLocalization("aw", "холандски", "Аруба"),
  CountryLocalization("au", "енглески", "Аустралија"),
  CountryLocalization("at", "енглески", "Аустрија"),
  CountryLocalization("az", "азербејџански", "Азербејџан"),
  CountryLocalization("bs", "енглески", "Бахами"),
  CountryLocalization("bh", "арапски", "Бахреин"),
  CountryLocalization("bd", "бангла", "Бангладеш"),
  CountryLocalization("bb", "енглески", "Барбадос"),
  CountryLocalization("by", "белоруски", "Белорусија"),
  CountryLocalization("be", "француски", "Белгија"),
  CountryLocalization("bz", "енглески", "Белизе"),
  CountryLocalization("bj", "француски", "Бенин"),
  CountryLocalization("bm", "енглески", "Бермуда"),
  CountryLocalization("bt", "џонга", "Бутан"),
  CountryLocalization("bo", "шпански", "Боливија"),
  CountryLocalization("ba", "босански", "Босна и Херцеговина"),
  CountryLocalization("bw", "енглески", "Боцвана"),
  CountryLocalization("br", "португалски", "Бразил"),
  CountryLocalization("io", "енглески", "Британска територија Индијског океана"),
  CountryLocalization("vg", "енглески", "Британска Девичанска Острва"),
  CountryLocalization("bn", "малајски", "Брунеј"),
  CountryLocalization("bg", "бугарски", "Бугарска"),
  CountryLocalization("bf", "француски", "Буркина Фасо"),
  CountryLocalization("bi", "француски", "Бурунди"),
  CountryLocalization("kh", "кмерски", "Камбоџа"),
  CountryLocalization("cm", "баса", "Камерун"),
  CountryLocalization("ca", "француски", "Канада"),
  CountryLocalization("ic", "шпански", "Канарска Острва"),
  CountryLocalization("cv", "зеленортски", "Кабо Верде"),
  CountryLocalization("bq", "холандски", "Карипска Холандија"),
  CountryLocalization("ky", "енглески", "Кајманска Острва"),
  CountryLocalization("cf", "лингала", "Централноафричка Република"),
  CountryLocalization("ea", "шпански", "Сеута и Мелиља"),
  CountryLocalization("td", "арапски", "Чад"),
  CountryLocalization("cl", "шпански", "Чиле"),
  CountryLocalization("cn", "тибетански", "Кина"),
  CountryLocalization("cx", "енглески", "Божићно Острво"),
  CountryLocalization("cc", "енглески", "Кокосова (Килингова) Острва"),
  CountryLocalization("co", "шпански", "Колумбија"),
  CountryLocalization("km", "арапски", "Коморска Острва"),
  CountryLocalization("cg", "лингала", "Конго"),
  CountryLocalization("cd", "свахили", "Конго - Киншаса"),
  CountryLocalization("ck", "енглески", "Кукова Острва"),
  CountryLocalization("cr", "шпански", "Костарика"),
  CountryLocalization("hr", "хрватски", "Хрватска"),
  CountryLocalization("cu", "шпански", "Куба"),
  CountryLocalization("cw", "холандски", "Курасао"),
  CountryLocalization("cy", "енглески", "Кипар"),
  CountryLocalization("cz", "чешки", "Чешка Република"),
  CountryLocalization("ci", "француски", "Обала Слоноваче (Кот д’Ивоар)"),
  CountryLocalization("dk", "енглески", "Данска"),
  CountryLocalization("dg", "енглески", "Дијего Гарсија"),
  CountryLocalization("dj", "француски", "Џибути"),
  CountryLocalization("dm", "енглески", "Доминика"),
  CountryLocalization("do", "шпански", "Доминиканска Република"),
  CountryLocalization("ec", "кечуа", "Еквадор"),
  CountryLocalization("eg", "арапски", "Египат"),
  CountryLocalization("sv", "шпански", "Салвадор"),
  CountryLocalization("gq", "шпански", "Екваторијална Гвинеја"),
  CountryLocalization("er", "тигриња", "Еритреја"),
  CountryLocalization("ee", "естонски", "Естонија"),
  CountryLocalization("et", "амхарски", "Етиопија"),
  CountryLocalization("fk", "енглески", "Фокландска Острва"),
  CountryLocalization("fo", "фарски", "Фарска Острва"),
  CountryLocalization("fj", "енглески", "Фиџи"),
  CountryLocalization("fi", "шведски", "Финска"),
  CountryLocalization("fr", "швајцарски немачки", "Француска"),
  CountryLocalization("gf", "француски", "Француска Гвајана"),
  CountryLocalization("pf", "француски", "Француска Полинезија"),
  CountryLocalization("ga", "француски", "Габон"),
  CountryLocalization("gm", "енглески", "Гамбија"),
  CountryLocalization("ge", "осетински", "Грузија"),
  CountryLocalization("de", "доњи лужичкосрпски", "Немачка"),
  CountryLocalization("gh", "енглески", "Гана"),
  CountryLocalization("gi", "енглески", "Гибралтар"),
  CountryLocalization("gr", "грчки", "Грчка"),
  CountryLocalization("gl", "гренландски", "Гренланд"),
  CountryLocalization("gd", "енглески", "Гренада"),
  CountryLocalization("gp", "француски", "Гваделуп"),
  CountryLocalization("gu", "енглески", "Гуам"),
  CountryLocalization("gt", "шпански", "Гватемала"),
  CountryLocalization("gg", "енглески", "Гернзи"),
  CountryLocalization("gn", "француски", "Гвинеја"),
  CountryLocalization("gw", "португалски", "Гвинеја-Бисао"),
  CountryLocalization("gy", "енглески", "Гвајана"),
  CountryLocalization("ht", "француски", "Хаити"),
  CountryLocalization("hn", "шпански", "Хондурас"),
  CountryLocalization("hk", "кинески", "САР Хонгконг"),
  CountryLocalization("hu", "мађарски", "Мађарска"),
  CountryLocalization("is", "исландски", "Исланд"),
  CountryLocalization("in", "непалски", "Индија"),
  CountryLocalization("id", "Индонезијски", "Индонезија"),
  CountryLocalization("ir", "персијски", "Иран"),
  CountryLocalization("iq", "северни лури", "Ирак"),
  CountryLocalization("ie", "енглески", "Ирска"),
  CountryLocalization("im", "манкс", "Острво Ман"),
  CountryLocalization("il", "енглески", "Израел"),
  CountryLocalization("it", "немачки", "Италија"),
  CountryLocalization("jm", "енглески", "Јамајка"),
  CountryLocalization("jp", "јапански", "Јапан"),
  CountryLocalization("je", "енглески", "Џерзи"),
  CountryLocalization("jo", "арапски", "Јордан"),
  CountryLocalization("kz", "казашки", "Казахстан"),
  CountryLocalization("ke", "сомалски", "Кенија"),
  CountryLocalization("ki", "енглески", "Кирибати"),
  CountryLocalization("xk", "српски", "Косово"),
  CountryLocalization("kw", "арапски", "Кувајт"),
  CountryLocalization("kg", "руски", "Киргистан"),
  CountryLocalization("la", "лаошки", "Лаос"),
  CountryLocalization("lv", "летонски", "Летонија"),
  CountryLocalization("lb", "арапски", "Либан"),
  CountryLocalization("ls", "енглески", "Лесото"),
  CountryLocalization("lr", "енглески", "Либерија"),
  CountryLocalization("ly", "арапски", "Либија"),
  CountryLocalization("li", "швајцарски немачки", "Лихтенштајн"),
  CountryLocalization("lt", "литвански", "Литванија"),
  CountryLocalization("lu", "луксембуршки", "Луксембург"),
  CountryLocalization("mo", "португалски", "САР Макао"),
  CountryLocalization("mk", "албански", "Македонија"),
  CountryLocalization("mg", "француски", "Мадагаскар"),
  CountryLocalization("mw", "енглески", "Малави"),
  CountryLocalization("my", "тамилски", "Малезија"),
  CountryLocalization("ml", "француски", "Мали"),
  CountryLocalization("mt", "енглески", "Малта"),
  CountryLocalization("mh", "енглески", "Маршалска Острва"),
  CountryLocalization("mq", "француски", "Мартиник"),
  CountryLocalization("mr", "арапски", "Мауританија"),
  CountryLocalization("mu", "морисјен", "Маурицијус"),
  CountryLocalization("yt", "француски", "Мајот"),
  CountryLocalization("mx", "шпански", "Мексико"),
  CountryLocalization("fm", "енглески", "Микронезија"),
  CountryLocalization("md", "руски", "Молдавија"),
  CountryLocalization("mc", "француски", "Монако"),
  CountryLocalization("mn", "монголски", "Монголија"),
  CountryLocalization("me", "српски", "Црна Гора"),
  CountryLocalization("ms", "енглески", "Монсерат"),
  CountryLocalization("ma", "централноатласки тамашек", "Мароко"),
  CountryLocalization("mz", "макува-мито", "Мозамбик"),
  CountryLocalization("mm", "бурмански", "Мијанмар (Бурма)"),
  CountryLocalization("na", "енглески", "Намибија"),
  CountryLocalization("nr", "енглески", "Науру"),
  CountryLocalization("np", "непалски", "Непал"),
  CountryLocalization("nl", "енглески", "Холандија"),
  CountryLocalization("nc", "француски", "Нова Каледонија"),
  CountryLocalization("nz", "енглески", "Нови Зеланд"),
  CountryLocalization("ni", "шпански", "Никарагва"),
  CountryLocalization("ne", "хауса", "Нигер"),
  CountryLocalization("ng", "хауса", "Нигерија"),
  CountryLocalization("nu", "енглески", "Ниуе"),
  CountryLocalization("nf", "енглески", "Острво Норфок"),
  CountryLocalization("kp", "корејски", "Северна Кореја"),
  CountryLocalization("mp", "енглески", "Северна Маријанска Острва"),
  CountryLocalization("no", "северни сами", "Норвешка"),
  CountryLocalization("om", "арапски", "Оман"),
  CountryLocalization("pk", "енглески", "Пакистан"),
  CountryLocalization("pw", "енглески", "Палау"),
  CountryLocalization("ps", "арапски", "Палестинске територије"),
  CountryLocalization("pa", "шпански", "Панама"),
  CountryLocalization("pg", "енглески", "Папуа Нова Гвинеја"),
  CountryLocalization("py", "шпански", "Парагвај"),
  CountryLocalization("pe", "шпански", "Перу"),
  CountryLocalization("ph", "филипински", "Филипини"),
  CountryLocalization("pn", "енглески", "Питкерн"),
  CountryLocalization("pl", "пољски", "Пољска"),
  CountryLocalization("pt", "португалски", "Португалија"),
  CountryLocalization("pr", "енглески", "Порторико"),
  CountryLocalization("qa", "арапски", "Катар"),
  CountryLocalization("ro", "румунски", "Румунија"),
  CountryLocalization("ru", "татарски", "Русија"),
  CountryLocalization("rw", "енглески", "Руанда"),
  CountryLocalization("re", "француски", "Реунион"),
  CountryLocalization("ws", "енглески", "Самоа"),
  CountryLocalization("sm", "италијански", "Сан Марино"),
  CountryLocalization("sa", "арапски", "Саудијска Арабија"),
  CountryLocalization("sn", "француски", "Сенегал"),
  CountryLocalization("rs", "српски", "Србија"),
  CountryLocalization("cs", "српски", "Србија и Црна Гора"),
  CountryLocalization("sc", "француски", "Сејшели"),
  CountryLocalization("sl", "енглески", "Сијера Леоне"),
  CountryLocalization("sg", "тамилски", "Сингапур"),
  CountryLocalization("sx", "енглески", "Свети Мартин (Холандија)"),
  CountryLocalization("sk", "словачки", "Словачка"),
  CountryLocalization("si", "словеначки", "Словенија"),
  CountryLocalization("sb", "енглески", "Соломонска Острва"),
  CountryLocalization("so", "арапски", "Сомалија"),
  CountryLocalization("za", "енглески", "Јужноафричка Република"),
  CountryLocalization("kr", "корејски", "Јужна Кореја"),
  CountryLocalization("ss", "нуер", "Јужни Судан"),
  CountryLocalization("es", "шпански", "Шпанија"),
  CountryLocalization("lk", "тамилски", "Шри Ланка"),
  CountryLocalization("bl", "француски", "Свети Бартоломеј"),
  CountryLocalization("sh", "енглески", "Света Јелена"),
  CountryLocalization("kn", "енглески", "Свети Китс и Невис"),
  CountryLocalization("lc", "енглески", "Света Луција"),
  CountryLocalization("mf", "француски", "Свети Мартин (Француска)"),
  CountryLocalization("pm", "француски", "Свети Пјер и Микелон"),
  CountryLocalization("vc", "енглески", "Свети Винсент и Гренадини"),
  CountryLocalization("sd", "арапски", "Судан"),
  CountryLocalization("sr", "холандски", "Суринам"),
  CountryLocalization("sj", "норвешки букмол", "Свалбард и Јан Мајен"),
  CountryLocalization("sz", "енглески", "Свазиленд"),
  CountryLocalization("se", "шведски", "Шведска"),
  CountryLocalization("ch", "швајцарски немачки", "Швајцарска"),
  CountryLocalization("sy", "арапски", "Сирија"),
  CountryLocalization("st", "португалски", "Сао Томе и Принципе"),
  CountryLocalization("tw", "кинески", "Тајван"),
  CountryLocalization("tj", "таџички", "Таџикистан"),
  CountryLocalization("tz", "маконде", "Танзанија"),
  CountryLocalization("th", "тајски", "Тајланд"),
  CountryLocalization("tl", "португалски", "Тимор-Лесте (Источни Тимор)"),
  CountryLocalization("tg", "француски", "Того"),
  CountryLocalization("tk", "енглески", "Токелау"),
  CountryLocalization("to", "тонгански", "Тонга"),
  CountryLocalization("tt", "енглески", "Тринидад и Тобаго"),
  CountryLocalization("tn", "француски", "Тунис"),
  CountryLocalization("tr", "турски", "Турска"),
  CountryLocalization("tm", "туркменски", "Туркменистан"),
  CountryLocalization("tc", "енглески", "Острва Туркс и Каикос"),
  CountryLocalization("tv", "енглески", "Тувалу"),
  CountryLocalization("um", "енглески", "Мања удаљена острва САД"),
  CountryLocalization("vi", "енглески", "Америчка Девичанска Острва"),
  CountryLocalization("ug", "свахили", "Уганда"),
  CountryLocalization("ua", "украјински", "Украјина"),
  CountryLocalization("ae", "арапски", "Уједињени Арапски Емирати"),
  CountryLocalization("gb", "енглески", "Уједињено Краљевство"),
  CountryLocalization("us", "лакота", "Сједињене Државе"),
  CountryLocalization("uy", "шпански", "Уругвај"),
  CountryLocalization("uz", "узбечки", "Узбекистан"),
  CountryLocalization("vu", "француски", "Вануату"),
  CountryLocalization("va", "италијански", "Ватикан"),
  CountryLocalization("ve", "шпански", "Венецуела"),
  CountryLocalization("vn", "вијетнамски", "Вијетнам"),
  CountryLocalization("wf", "француски", "Валис и Футуна"),
  CountryLocalization("eh", "арапски", "Западна Сахара"),
  CountryLocalization("ye", "арапски", "Јемен"),
  CountryLocalization("zm", "енглески", "Замбија"),
  CountryLocalization("zw", "северни ндебеле", "Зимбабве"),
  CountryLocalization("ax", "шведски", "Оландска Острва"),
)
