/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot.atlas.extended

import dev.teogor.xenoglot.atlas.CountryLocalization
import kotlin.collections.List

/**
 * Holds the internal list of country-language mappings used for lookups within the package for
 * language code uz.
 *
 * This property contains a hardcoded list of [CountryLocalization] objects, each representing
 * a country and its associated official languages. This list is used by [CountryLanguageRegistry]
 * to provide access to country-language data and should not be modified directly.
 *
 * @see CountryLocalization
 * @see CountryLanguageRegistry
 */
internal val _countryLanguageMappings_uz: List<CountryLocalization> = listOf(
  CountryLocalization("af", "форсий", "Афғонистон"),
  CountryLocalization("al", "албанча", "Албания"),
  CountryLocalization("dz", "французча", "Жазоир"),
  CountryLocalization("as", "инглизча", "Америка Самоаси"),
  CountryLocalization("ad", "каталонча", "Андорра"),
  CountryLocalization("ao", "лингалча", "Ангола"),
  CountryLocalization("ai", "инглизча", "Ангилья"),
  CountryLocalization("ag", "инглизча", "Антигуа ва Барбуда"),
  CountryLocalization("ar", "испанча", "Аргентина"),
  CountryLocalization("am", "арманча", "Арманистон"),
  CountryLocalization("aw", "голландча", "Аруба"),
  CountryLocalization("au", "инглизча", "Австралия"),
  CountryLocalization("at", "инглизча", "Австрия"),
  CountryLocalization("az", "озарбайжонча", "Озарбайжон"),
  CountryLocalization("bs", "инглизча", "Багама ороллари"),
  CountryLocalization("bh", "арабча", "Баҳрайн"),
  CountryLocalization("bd", "бенгалча", "Бангладеш"),
  CountryLocalization("bb", "инглизча", "Барбадос"),
  CountryLocalization("by", "беларусча", "Беларус"),
  CountryLocalization("be", "французча", "Бельгия"),
  CountryLocalization("bz", "инглизча", "Белиз"),
  CountryLocalization("bj", "французча", "Бенин"),
  CountryLocalization("bm", "инглизча", "Бермуда"),
  CountryLocalization("bt", "дзонгка", "Бутан"),
  CountryLocalization("bo", "испанча", "Боливия"),
  CountryLocalization("ba", "боснийча", "Босния ва Герцеговина"),
  CountryLocalization("bw", "инглизча", "Ботсванна"),
  CountryLocalization("br", "португалча", "Бразилия"),
  CountryLocalization("io", "инглизча", "Британиянинг Ҳинд океанидаги ҳудуди"),
  CountryLocalization("vg", "инглизча", "Британия Виргин ороллари"),
  CountryLocalization("bn", "малай тил", "Бруней"),
  CountryLocalization("bg", "болгарча", "Болгария"),
  CountryLocalization("bf", "французча", "Буркина-Фасо"),
  CountryLocalization("bi", "французча", "Бурунди"),
  CountryLocalization("kh", "хмерча", "Камбоджа"),
  CountryLocalization("cm", "басаа", "Камерун"),
  CountryLocalization("ca", "французча", "Канада"),
  CountryLocalization("ic", "испанча", "Канар ороллари"),
  CountryLocalization("cv", "кабувердиану", "Кабо-Верде"),
  CountryLocalization("bq", "голландча", "Бонейр, Синт-Эстатиус ва Саба"),
  CountryLocalization("ky", "инглизча", "Кайман ороллари"),
  CountryLocalization("cf", "лингалча", "Марказий Африка Республикаси"),
  CountryLocalization("ea", "испанча", "Сэута ва Мелилла"),
  CountryLocalization("td", "арабча", "Чад"),
  CountryLocalization("cl", "испанча", "Чили"),
  CountryLocalization("cn", "тибетча", "Хитой"),
  CountryLocalization("cx", "инглизча", "Рождество ороли"),
  CountryLocalization("cc", "инглизча", "Кокос (Килинг) ороллари"),
  CountryLocalization("co", "испанча", "Колумбия"),
  CountryLocalization("km", "арабча", "Комор ороллари"),
  CountryLocalization("cg", "лингалча", "Конго Браззавиль"),
  CountryLocalization("cd", "суахили", "Конго-Киншаса"),
  CountryLocalization("ck", "инглизча", "Кук ороллари"),
  CountryLocalization("cr", "испанча", "Коста-Рика"),
  CountryLocalization("hr", "хорватча", "Хорватия"),
  CountryLocalization("cu", "испанча", "Куба"),
  CountryLocalization("cw", "голландча", "Кюрасао"),
  CountryLocalization("cy", "инглизча", "Кипр"),
  CountryLocalization("cz", "чехча", "Чехия"),
  CountryLocalization("ci", "французча", "Кот-д’Ивуар"),
  CountryLocalization("dk", "инглизча", "Дания"),
  CountryLocalization("dg", "инглизча", "Диего-Гарсия"),
  CountryLocalization("dj", "французча", "Жибути"),
  CountryLocalization("dm", "инглизча", "Доминика"),
  CountryLocalization("do", "испанча", "Доминикан Республикаси"),
  CountryLocalization("ec", "кечуа", "Эквадор"),
  CountryLocalization("eg", "арабча", "Миср"),
  CountryLocalization("sv", "испанча", "Салвадор"),
  CountryLocalization("gq", "испанча", "Экваториал Гвинея"),
  CountryLocalization("er", "тигриняча", "Эритрея"),
  CountryLocalization("ee", "эстонча", "Эстония"),
  CountryLocalization("et", "амхарча", "Эфиопия"),
  CountryLocalization("fk", "инглизча", "Фолкленд ороллари"),
  CountryLocalization("fo", "фарерча", "Фарер ороллари"),
  CountryLocalization("fj", "инглизча", "Фижи"),
  CountryLocalization("fi", "шведча", "Финляндия"),
  CountryLocalization("fr", "немисча (Швейцария)", "Франция"),
  CountryLocalization("gf", "французча", "Француз Гвианаси"),
  CountryLocalization("pf", "французча", "Француз Полинезияси"),
  CountryLocalization("ga", "французча", "Габон"),
  CountryLocalization("gm", "инглизча", "Гамбия"),
  CountryLocalization("ge", "Ossetic", "Грузия"),
  CountryLocalization("de", "қуйи-сорбча", "Германия"),
  CountryLocalization("gh", "инглизча", "Гана"),
  CountryLocalization("gi", "инглизча", "Гибралтар"),
  CountryLocalization("gr", "грекча", "Греция"),
  CountryLocalization("gl", "гренландча", "Гренландия"),
  CountryLocalization("gd", "инглизча", "Гренада"),
  CountryLocalization("gp", "французча", "Гваделупе"),
  CountryLocalization("gu", "инглизча", "Гуам"),
  CountryLocalization("gt", "испанча", "Гватемала"),
  CountryLocalization("gg", "инглизча", "Гернси"),
  CountryLocalization("gn", "французча", "Гвинея"),
  CountryLocalization("gw", "португалча", "Гвинея-Бисау"),
  CountryLocalization("gy", "инглизча", "Гаяна"),
  CountryLocalization("ht", "французча", "Гаити"),
  CountryLocalization("hn", "испанча", "Гондурас"),
  CountryLocalization("hk", "хитойча", "Гонконг (Хитой ММҲ)"),
  CountryLocalization("hu", "венгерча", "Венгрия"),
  CountryLocalization("is", "исландча", "Исландия"),
  CountryLocalization("in", "непалча", "Ҳиндистон"),
  CountryLocalization("id", "Indonesian", "Индонезия"),
  CountryLocalization("ir", "форсий", "Эрон"),
  CountryLocalization("iq", "шимолий лури", "Ироқ"),
  CountryLocalization("ie", "инглизча", "Ирландия"),
  CountryLocalization("im", "мэнча", "Мэн ороли"),
  CountryLocalization("il", "инглизча", "Исроил"),
  CountryLocalization("it", "немисча", "Италия"),
  CountryLocalization("jm", "инглизча", "Ямайка"),
  CountryLocalization("jp", "японча", "Япония"),
  CountryLocalization("je", "инглизча", "Жерси"),
  CountryLocalization("jo", "арабча", "Иордания"),
  CountryLocalization("kz", "қозоқча", "Қозоғистон"),
  CountryLocalization("ke", "сомалича", "Кения"),
  CountryLocalization("ki", "инглизча", "Кирибати"),
  CountryLocalization("xk", "сербча", "Косово"),
  CountryLocalization("kw", "арабча", "Қувайт"),
  CountryLocalization("kg", "русча", "Қирғизистон"),
  CountryLocalization("la", "лаосча", "Лаос"),
  CountryLocalization("lv", "латишча", "Латвия"),
  CountryLocalization("lb", "арабча", "Ливан"),
  CountryLocalization("ls", "инглизча", "Лесото"),
  CountryLocalization("lr", "инглизча", "Либерия"),
  CountryLocalization("ly", "арабча", "Ливия"),
  CountryLocalization("li", "немисча (Швейцария)", "Лихтенштейн"),
  CountryLocalization("lt", "литвача", "Литва"),
  CountryLocalization("lu", "люксембургча", "Люксембург"),
  CountryLocalization("mo", "португалча", "Макао (Хитой ММҲ)"),
  CountryLocalization("mk", "албанча", "Македония"),
  CountryLocalization("mg", "французча", "Мадагаскар"),
  CountryLocalization("mw", "инглизча", "Малави"),
  CountryLocalization("my", "тамилча", "Малайзия"),
  CountryLocalization("ml", "французча", "Мали"),
  CountryLocalization("mt", "инглизча", "Мальта"),
  CountryLocalization("mh", "инглизча", "Маршал ороллари"),
  CountryLocalization("mq", "французча", "Мартиника"),
  CountryLocalization("mr", "арабча", "Мавритания"),
  CountryLocalization("mu", "морисьен", "Маврикий"),
  CountryLocalization("yt", "французча", "Майотта"),
  CountryLocalization("mx", "испанча", "Мексика"),
  CountryLocalization("fm", "инглизча", "Микронезия"),
  CountryLocalization("md", "русча", "Молдова"),
  CountryLocalization("mc", "французча", "Монако"),
  CountryLocalization("mn", "мўғулча", "Монголия"),
  CountryLocalization("me", "сербча", "Черногория"),
  CountryLocalization("ms", "инглизча", "Монтсеррат"),
  CountryLocalization("ma", "марказий атлас тамазигхт", "Марокаш"),
  CountryLocalization("mz", "махува-митто", "Мозамбик"),
  CountryLocalization("mm", "бирманча", "Мьянма (Бирма)"),
  CountryLocalization("na", "инглизча", "Намибия"),
  CountryLocalization("nr", "инглизча", "Науру"),
  CountryLocalization("np", "непалча", "Непал"),
  CountryLocalization("nl", "инглизча", "Нидерландия"),
  CountryLocalization("nc", "французча", "Янги Каледония"),
  CountryLocalization("nz", "инглизча", "Янги Зеландия"),
  CountryLocalization("ni", "испанча", "Никарагуа"),
  CountryLocalization("ne", "хауса", "Нигер"),
  CountryLocalization("ng", "хауса", "Нигерия"),
  CountryLocalization("nu", "инглизча", "Ниуэ"),
  CountryLocalization("nf", "инглизча", "Норфолк ороллари"),
  CountryLocalization("kp", "корейсча", "Шимолий Корея"),
  CountryLocalization("mp", "инглизча", "Шимолий Марианна ороллари"),
  CountryLocalization("no", "шимолий саамча", "Норвегия"),
  CountryLocalization("om", "арабча", "Уммон"),
  CountryLocalization("pk", "инглизча", "Покистон"),
  CountryLocalization("pw", "инглизча", "Палау"),
  CountryLocalization("ps", "арабча", "Фаластин ҳудуди"),
  CountryLocalization("pa", "испанча", "Панама"),
  CountryLocalization("pg", "инглизча", "Папуа - Янги Гвинея"),
  CountryLocalization("py", "испанча", "Парагвай"),
  CountryLocalization("pe", "испанча", "Перу"),
  CountryLocalization("ph", "филипинча", "Филиппин"),
  CountryLocalization("pn", "инглизча", "Питкэрн ороллари"),
  CountryLocalization("pl", "полякча", "Польша"),
  CountryLocalization("pt", "португалча", "Португалия"),
  CountryLocalization("pr", "инглизча", "Пуэрто-Рико"),
  CountryLocalization("qa", "арабча", "Қатар"),
  CountryLocalization("ro", "руминча", "Руминия"),
  CountryLocalization("ru", "татарча", "Россия"),
  CountryLocalization("rw", "инглизча", "Руанда"),
  CountryLocalization("re", "французча", "Реюнион"),
  CountryLocalization("ws", "инглизча", "Самоа"),
  CountryLocalization("sm", "италянча", "Сан-Марино"),
  CountryLocalization("sa", "арабча", "Саудия Арабистони"),
  CountryLocalization("sn", "французча", "Сенегал"),
  CountryLocalization("rs", "сербча", "Сербия"),
  CountryLocalization("cs", "сербча", "Serbia and Montenegro"),
  CountryLocalization("sc", "французча", "Сейшел ороллари"),
  CountryLocalization("sl", "инглизча", "Сьерра-Леоне"),
  CountryLocalization("sg", "тамилча", "Сингапур"),
  CountryLocalization("sx", "инглизча", "Синт-Мартен"),
  CountryLocalization("sk", "словакча", "Словакия"),
  CountryLocalization("si", "словенча", "Словения"),
  CountryLocalization("sb", "инглизча", "Соломон ороллари"),
  CountryLocalization("so", "арабча", "Сомали"),
  CountryLocalization("za", "инглизча", "Жанубий Африка Республикаси"),
  CountryLocalization("kr", "корейсча", "Жанубий Корея"),
  CountryLocalization("ss", "нуэрча", "Жанубий Судан"),
  CountryLocalization("es", "испанча", "Испания"),
  CountryLocalization("lk", "тамилча", "Шри-Ланка"),
  CountryLocalization("bl", "французча", "Сен-Бартелеми"),
  CountryLocalization("sh", "инглизча", "Муқаддас Елена ороли"),
  CountryLocalization("kn", "инглизча", "Сент-Китс ва Невис"),
  CountryLocalization("lc", "инглизча", "Сент-Люсия"),
  CountryLocalization("mf", "французча", "Сент-Мартин"),
  CountryLocalization("pm", "французча", "Сент-Пьер ва Микелон"),
  CountryLocalization("vc", "инглизча", "Сент-Винсент ва Гренадин"),
  CountryLocalization("sd", "арабча", "Судан"),
  CountryLocalization("sr", "голландча", "Суринам"),
  CountryLocalization("sj", "норвегча бокмал", "Свалбард ва Ян-Майен"),
  CountryLocalization("sz", "инглизча", "Свазиленд"),
  CountryLocalization("se", "шведча", "Швеция"),
  CountryLocalization("ch", "немисча (Швейцария)", "Швейцария"),
  CountryLocalization("sy", "арабча", "Сурия"),
  CountryLocalization("st", "португалча", "Сан-Томе ва Принсипи"),
  CountryLocalization("tw", "хитойча", "Тайван"),
  CountryLocalization("tj", "тожикча", "Тожикистон"),
  CountryLocalization("tz", "макондеча", "Танзания"),
  CountryLocalization("th", "тайча", "Таиланд"),
  CountryLocalization("tl", "португалча", "Тимор-Лесте"),
  CountryLocalization("tg", "французча", "Того"),
  CountryLocalization("tk", "инглизча", "Токелау"),
  CountryLocalization("to", "тонганча", "Тонга"),
  CountryLocalization("tt", "инглизча", "Тринидад ва Тобаго"),
  CountryLocalization("tn", "французча", "Тунис"),
  CountryLocalization("tr", "туркча", "Туркия"),
  CountryLocalization("tm", "туркманча", "Туркманистон"),
  CountryLocalization("tc", "инглизча", "Туркс ва Кайкос ороллари"),
  CountryLocalization("tv", "инглизча", "Тувалу"),
  CountryLocalization("um", "инглизча", "АҚШ ёндош ороллари"),
  CountryLocalization("vi", "инглизча", "АҚШ Виргин ороллари"),
  CountryLocalization("ug", "суахили", "Уганда"),
  CountryLocalization("ua", "украинча", "Украина"),
  CountryLocalization("ae", "арабча", "Бирлашган Араб Амирликлари"),
  CountryLocalization("gb", "инглизча", "Буюк Британия"),
  CountryLocalization("us", "лакотачалакотача", "Америка Қўшма Штатлари"),
  CountryLocalization("uy", "испанча", "Уругвай"),
  CountryLocalization("uz", "ўзбекча", "Ўзбекистон"),
  CountryLocalization("vu", "французча", "Вануату"),
  CountryLocalization("va", "италянча", "Ватикан"),
  CountryLocalization("ve", "испанча", "Венесуэла"),
  CountryLocalization("vn", "ветнамча", "Вьетнам"),
  CountryLocalization("wf", "французча", "Уоллис ва Футуна"),
  CountryLocalization("eh", "арабча", "Ғарбий Саҳрои Кабир"),
  CountryLocalization("ye", "арабча", "Яман"),
  CountryLocalization("zm", "инглизча", "Замбия"),
  CountryLocalization("zw", "шимолий ндебеле", "Зимбабве"),
  CountryLocalization("ax", "шведча", "Аланд ороллари"),
)
