/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot.atlas.extended

import dev.teogor.xenoglot.atlas.CountryLocalization
import kotlin.collections.List

/**
 * Holds the internal list of country-language mappings used for lookups within the package for
 * language code ta.
 *
 * This property contains a hardcoded list of [CountryLocalization] objects, each representing
 * a country and its associated official languages. This list is used by [CountryLanguageRegistry]
 * to provide access to country-language data and should not be modified directly.
 *
 * @see CountryLocalization
 * @see CountryLanguageRegistry
 */
internal val _countryLanguageMappings_ta: List<CountryLocalization> = listOf(
  CountryLocalization("af", "பெர்ஷியன்", "ஆப்கானிஸ்தான்"),
  CountryLocalization("al", "அல்பேனியன்", "அல்பேனியா"),
  CountryLocalization("dz", "பிரெஞ்சு", "அல்ஜீரியா"),
  CountryLocalization("as", "ஆங்கிலம்", "அமெரிக்க சமோவா"),
  CountryLocalization("ad", "கேட்டலான்", "அன்டோரா"),
  CountryLocalization("ao", "லிங்காலா", "அங்கோலா"),
  CountryLocalization("ai", "ஆங்கிலம்", "அங்குய்லா"),
  CountryLocalization("ag", "ஆங்கிலம்", "ஆண்டிகுவா மற்றும் பார்புடா"),
  CountryLocalization("ar", "ஸ்பானிஷ்", "அர்ஜென்டினா"),
  CountryLocalization("am", "ஆர்மேனியன்", "அர்மேனியா"),
  CountryLocalization("aw", "டச்சு", "அரூபா"),
  CountryLocalization("au", "ஆங்கிலம்", "ஆஸ்திரேலியா"),
  CountryLocalization("at", "ஆங்கிலம்", "ஆஸ்திரியா"),
  CountryLocalization("az", "அஸர்பைஜானி", "அசர்பைஜான்"),
  CountryLocalization("bs", "ஆங்கிலம்", "பஹாமாஸ்"),
  CountryLocalization("bh", "அரபிக்", "பஹ்ரைன்"),
  CountryLocalization("bd", "வங்காளம்", "பங்களாதேஷ்"),
  CountryLocalization("bb", "ஆங்கிலம்", "பார்படோஸ்"),
  CountryLocalization("by", "பெலாருஷியன்", "பெலாரூஸ்"),
  CountryLocalization("be", "பிரெஞ்சு", "பெல்ஜியம்"),
  CountryLocalization("bz", "ஆங்கிலம்", "பெலிஸ்"),
  CountryLocalization("bj", "பிரெஞ்சு", "பெனின்"),
  CountryLocalization("bm", "ஆங்கிலம்", "பெர்முடா"),
  CountryLocalization("bt", "பூடானி", "பூடான்"),
  CountryLocalization("bo", "ஸ்பானிஷ்", "பொலிவியா"),
  CountryLocalization("ba", "போஸ்னியன்", "போஸ்னியா & ஹெர்ஸகோவினா"),
  CountryLocalization("bw", "ஆங்கிலம்", "போட்ஸ்வானா"),
  CountryLocalization("br", "போர்ச்சுக்கீஸ்", "பிரேசில்"),
  CountryLocalization("io", "ஆங்கிலம்", "பிரிட்டிஷ் இந்தியப் பெருங்கடல் பிரதேசம்"),
  CountryLocalization("vg", "ஆங்கிலம்", "பிரிட்டீஷ் கன்னித் தீவுகள்"),
  CountryLocalization("bn", "மலாய்", "புருனே"),
  CountryLocalization("bg", "பல்கேரியன்", "பல்கேரியா"),
  CountryLocalization("bf", "பிரெஞ்சு", "புர்கினா ஃபாஸோ"),
  CountryLocalization("bi", "பிரெஞ்சு", "புருண்டி"),
  CountryLocalization("kh", "கெமெர்", "கம்போடியா"),
  CountryLocalization("cm", "பாஸா", "கேமரூன்"),
  CountryLocalization("ca", "பிரெஞ்சு", "கனடா"),
  CountryLocalization("ic", "ஸ்பானிஷ்", "கேனரி தீவுகள்"),
  CountryLocalization("cv", "கபுவெர்தியானு", "கேப் வெர்டே"),
  CountryLocalization("bq", "டச்சு", "கரீபியன் நெதர்லாந்து"),
  CountryLocalization("ky", "ஆங்கிலம்", "கெய்மென் தீவுகள்"),
  CountryLocalization("cf", "லிங்காலா", "மத்திய ஆப்ரிக்கக் குடியரசு"),
  CountryLocalization("ea", "ஸ்பானிஷ்", "சியூடா & மெலில்லா"),
  CountryLocalization("td", "அரபிக்", "சாட்"),
  CountryLocalization("cl", "ஸ்பானிஷ்", "சிலி"),
  CountryLocalization("cn", "திபெத்தியன்", "சீனா"),
  CountryLocalization("cx", "ஆங்கிலம்", "கிறிஸ்துமஸ் தீவு"),
  CountryLocalization("cc", "ஆங்கிலம்", "கோகோஸ் (கீலிங்) தீவுகள்"),
  CountryLocalization("co", "ஸ்பானிஷ்", "கொலம்பியா"),
  CountryLocalization("km", "அரபிக்", "கோமரோஸ்"),
  CountryLocalization("cg", "லிங்காலா", "காங்கோ - ப்ராஸாவில்லே"),
  CountryLocalization("cd", "ஸ்வாஹிலி", "காங்கோ - கின்ஷாசா"),
  CountryLocalization("ck", "ஆங்கிலம்", "குக் தீவுகள்"),
  CountryLocalization("cr", "ஸ்பானிஷ்", "கோஸ்டாரிகா"),
  CountryLocalization("hr", "குரோஷியன்", "குரேஷியா"),
  CountryLocalization("cu", "ஸ்பானிஷ்", "கியூபா"),
  CountryLocalization("cw", "டச்சு", "குராகவ்"),
  CountryLocalization("cy", "ஆங்கிலம்", "சைப்ரஸ்"),
  CountryLocalization("cz", "செக்", "செசியா"),
  CountryLocalization("ci", "பிரெஞ்சு", "கோட் தி’வாயர்"),
  CountryLocalization("dk", "ஆங்கிலம்", "டென்மார்க்"),
  CountryLocalization("dg", "ஆங்கிலம்", "டியகோ கார்ஷியா"),
  CountryLocalization("dj", "பிரெஞ்சு", "ஜிபௌட்டி"),
  CountryLocalization("dm", "ஆங்கிலம்", "டொமினிகா"),
  CountryLocalization("do", "ஸ்பானிஷ்", "டொமினிகன் குடியரசு"),
  CountryLocalization("ec", "க்வெச்சுவா", "ஈக்வடார்"),
  CountryLocalization("eg", "அரபிக்", "எகிப்து"),
  CountryLocalization("sv", "ஸ்பானிஷ்", "எல் சால்வடார்"),
  CountryLocalization("gq", "ஸ்பானிஷ்", "ஈக்வடோரியல் கினியா"),
  CountryLocalization("er", "டிக்ரின்யா", "எரிட்ரியா"),
  CountryLocalization("ee", "எஸ்டோனியன்", "எஸ்டோனியா"),
  CountryLocalization("et", "அம்ஹாரிக்", "எத்தியோப்பியா"),
  CountryLocalization("fk", "ஆங்கிலம்", "ஃபாக்லாந்து தீவுகள்"),
  CountryLocalization("fo", "ஃபரோயிஸ்", "ஃபாரோ தீவுகள்"),
  CountryLocalization("fj", "ஆங்கிலம்", "ஃபிஜி"),
  CountryLocalization("fi", "ஸ்வீடிஷ்", "பின்லாந்து"),
  CountryLocalization("fr", "ஸ்விஸ் ஜெர்மன்", "பிரான்ஸ்"),
  CountryLocalization("gf", "பிரெஞ்சு", "பிரெஞ்சு கயானா"),
  CountryLocalization("pf", "பிரெஞ்சு", "பிரெஞ்சு பாலினேஷியா"),
  CountryLocalization("ga", "பிரெஞ்சு", "கேபான்"),
  CountryLocalization("gm", "ஆங்கிலம்", "காம்பியா"),
  CountryLocalization("ge", "ஒசெட்டிக்", "ஜார்ஜியா"),
  CountryLocalization("de", "லோயர் சோர்பியன்", "ஜெர்மனி"),
  CountryLocalization("gh", "ஆங்கிலம்", "கானா"),
  CountryLocalization("gi", "ஆங்கிலம்", "ஜிப்ரால்டர்"),
  CountryLocalization("gr", "கிரேக்கம்", "கிரீஸ்"),
  CountryLocalization("gl", "கலாலிசூட்", "கிரீன்லாந்து"),
  CountryLocalization("gd", "ஆங்கிலம்", "கிரனெடா"),
  CountryLocalization("gp", "பிரெஞ்சு", "க்வாதேலோப்"),
  CountryLocalization("gu", "ஆங்கிலம்", "குவாம்"),
  CountryLocalization("gt", "ஸ்பானிஷ்", "கவுதமாலா"),
  CountryLocalization("gg", "ஆங்கிலம்", "கெர்ன்சி"),
  CountryLocalization("gn", "பிரெஞ்சு", "கினியா"),
  CountryLocalization("gw", "போர்ச்சுக்கீஸ்", "கினியா-பிஸ்ஸாவ்"),
  CountryLocalization("gy", "ஆங்கிலம்", "கயானா"),
  CountryLocalization("ht", "பிரெஞ்சு", "ஹைட்டி"),
  CountryLocalization("hn", "ஸ்பானிஷ்", "ஹோண்டூராஸ்"),
  CountryLocalization("hk", "சீனம்", "ஹாங்காங் எஸ்ஏஆர் சீனா"),
  CountryLocalization("hu", "ஹங்கேரியன்", "ஹங்கேரி"),
  CountryLocalization("is", "ஐஸ்லேண்டிக்", "ஐஸ்லாந்து"),
  CountryLocalization("in", "நேபாளி", "இந்தியா"),
  CountryLocalization("id", "Indonesian", "இந்தோனேசியா"),
  CountryLocalization("ir", "பெர்ஷியன்", "ஈரான்"),
  CountryLocalization("iq", "வடக்கு லுரி", "ஈராக்"),
  CountryLocalization("ie", "ஆங்கிலம்", "அயர்லாந்து"),
  CountryLocalization("im", "மேங்க்ஸ்", "ஐல் ஆஃப் மேன்"),
  CountryLocalization("il", "ஆங்கிலம்", "இஸ்ரேல்"),
  CountryLocalization("it", "ஜெர்மன்", "இத்தாலி"),
  CountryLocalization("jm", "ஆங்கிலம்", "ஜமைகா"),
  CountryLocalization("jp", "ஜப்பானியம்", "ஜப்பான்"),
  CountryLocalization("je", "ஆங்கிலம்", "ஜெர்சி"),
  CountryLocalization("jo", "அரபிக்", "ஜோர்டான்"),
  CountryLocalization("kz", "கசாக்", "கஸகஸ்தான்"),
  CountryLocalization("ke", "சோமாலி", "கென்யா"),
  CountryLocalization("ki", "ஆங்கிலம்", "கிரிபாட்டி"),
  CountryLocalization("xk", "செர்பியன்", "கொசோவோ"),
  CountryLocalization("kw", "அரபிக்", "குவைத்"),
  CountryLocalization("kg", "ரஷியன்", "கிர்கிஸ்தான்"),
  CountryLocalization("la", "லாவோ", "லாவோஸ்"),
  CountryLocalization("lv", "லாட்வியன்", "லாட்வியா"),
  CountryLocalization("lb", "அரபிக்", "லெபனான்"),
  CountryLocalization("ls", "ஆங்கிலம்", "லெசோதோ"),
  CountryLocalization("lr", "ஆங்கிலம்", "லைபீரியா"),
  CountryLocalization("ly", "அரபிக்", "லிபியா"),
  CountryLocalization("li", "ஸ்விஸ் ஜெர்மன்", "லிச்செண்ஸ்டெய்ன்"),
  CountryLocalization("lt", "லிதுவேனியன்", "லிதுவேனியா"),
  CountryLocalization("lu", "லக்ஸம்போர்கிஷ்", "லக்ஸ்சம்பர்க்"),
  CountryLocalization("mo", "போர்ச்சுக்கீஸ்", "மகாவ் எஸ்ஏஆர் சீனா"),
  CountryLocalization("mk", "அல்பேனியன்", "மாசிடோனியா"),
  CountryLocalization("mg", "பிரெஞ்சு", "மடகாஸ்கர்"),
  CountryLocalization("mw", "ஆங்கிலம்", "மலாவி"),
  CountryLocalization("my", "தமிழ்", "மலேசியா"),
  CountryLocalization("ml", "பிரெஞ்சு", "மாலி"),
  CountryLocalization("mt", "ஆங்கிலம்", "மால்டா"),
  CountryLocalization("mh", "ஆங்கிலம்", "மார்ஷல் தீவுகள்"),
  CountryLocalization("mq", "பிரெஞ்சு", "மார்டினிக்"),
  CountryLocalization("mr", "அரபிக்", "மௌரிடானியா"),
  CountryLocalization("mu", "மொரிசியன்", "மொரிசியஸ்"),
  CountryLocalization("yt", "பிரெஞ்சு", "மயோட்"),
  CountryLocalization("mx", "ஸ்பானிஷ்", "மெக்சிகோ"),
  CountryLocalization("fm", "ஆங்கிலம்", "மைக்ரோனேஷியா"),
  CountryLocalization("md", "ரஷியன்", "மால்டோவா"),
  CountryLocalization("mc", "பிரெஞ்சு", "மொனாக்கோ"),
  CountryLocalization("mn", "மங்கோலியன்", "மங்கோலியா"),
  CountryLocalization("me", "செர்பியன்", "மான்டேனெக்ரோ"),
  CountryLocalization("ms", "ஆங்கிலம்", "மாண்ட்செராட்"),
  CountryLocalization("ma", "மத்திய அட்லஸ் டமசைட்", "மொராக்கோ"),
  CountryLocalization("mz", "மகுவா-மீட்டோ", "மொசாம்பிக்"),
  CountryLocalization("mm", "பர்மீஸ்", "மியான்மார் (பர்மா)"),
  CountryLocalization("na", "ஆங்கிலம்", "நமீபியா"),
  CountryLocalization("nr", "ஆங்கிலம்", "நௌரு"),
  CountryLocalization("np", "நேபாளி", "நேபாளம்"),
  CountryLocalization("nl", "ஆங்கிலம்", "நெதர்லாந்து"),
  CountryLocalization("nc", "பிரெஞ்சு", "நியூ கேலிடோனியா"),
  CountryLocalization("nz", "ஆங்கிலம்", "நியூசிலாந்து"),
  CountryLocalization("ni", "ஸ்பானிஷ்", "நிகரகுவா"),
  CountryLocalization("ne", "ஹௌஸா", "நைஜர்"),
  CountryLocalization("ng", "ஹௌஸா", "நைஜீரியா"),
  CountryLocalization("nu", "ஆங்கிலம்", "நியூ"),
  CountryLocalization("nf", "ஆங்கிலம்", "நார்ஃபோக் தீவுகள்"),
  CountryLocalization("kp", "கொரியன்", "வட கொரியா"),
  CountryLocalization("mp", "ஆங்கிலம்", "வடக்கு மரியானா தீவுகள்"),
  CountryLocalization("no", "வடக்கு சமி", "நார்வே"),
  CountryLocalization("om", "அரபிக்", "ஓமன்"),
  CountryLocalization("pk", "ஆங்கிலம்", "பாகிஸ்தான்"),
  CountryLocalization("pw", "ஆங்கிலம்", "பாலோ"),
  CountryLocalization("ps", "அரபிக்", "பாலஸ்தீனிய பிரதேசங்கள்"),
  CountryLocalization("pa", "ஸ்பானிஷ்", "பனாமா"),
  CountryLocalization("pg", "ஆங்கிலம்", "பப்புவா நியூ கினியா"),
  CountryLocalization("py", "ஸ்பானிஷ்", "பராகுவே"),
  CountryLocalization("pe", "ஸ்பானிஷ்", "பெரு"),
  CountryLocalization("ph", "ஃபிலிபினோ", "பிலிப்பைன்ஸ்"),
  CountryLocalization("pn", "ஆங்கிலம்", "பிட்கெய்ர்ன் தீவுகள்"),
  CountryLocalization("pl", "போலிஷ்", "போலந்து"),
  CountryLocalization("pt", "போர்ச்சுக்கீஸ்", "போர்ச்சுக்கல்"),
  CountryLocalization("pr", "ஆங்கிலம்", "பியூர்டோ ரிகோ"),
  CountryLocalization("qa", "அரபிக்", "கத்தார்"),
  CountryLocalization("ro", "ரோமேனியன்", "ருமேனியா"),
  CountryLocalization("ru", "டாடர்", "ரஷ்யா"),
  CountryLocalization("rw", "ஆங்கிலம்", "ருவாண்டா"),
  CountryLocalization("re", "பிரெஞ்சு", "ரீயூனியன்"),
  CountryLocalization("ws", "ஆங்கிலம்", "சமோவா"),
  CountryLocalization("sm", "இத்தாலியன்", "சான் மரினோ"),
  CountryLocalization("sa", "அரபிக்", "சவூதி அரேபியா"),
  CountryLocalization("sn", "பிரெஞ்சு", "செனெகல்"),
  CountryLocalization("rs", "செர்பியன்", "செர்பியா"),
  CountryLocalization("cs", "செர்பியன்", "Serbia and Montenegro"),
  CountryLocalization("sc", "பிரெஞ்சு", "சீஷெல்ஸ்"),
  CountryLocalization("sl", "ஆங்கிலம்", "சியாரா லியோன்"),
  CountryLocalization("sg", "தமிழ்", "சிங்கப்பூர்"),
  CountryLocalization("sx", "ஆங்கிலம்", "சின்ட் மார்டென்"),
  CountryLocalization("sk", "ஸ்லோவாக்", "ஸ்லோவாகியா"),
  CountryLocalization("si", "ஸ்லோவேனியன்", "ஸ்லோவேனியா"),
  CountryLocalization("sb", "ஆங்கிலம்", "சாலமன் தீவுகள்"),
  CountryLocalization("so", "அரபிக்", "சோமாலியா"),
  CountryLocalization("za", "ஆங்கிலம்", "தென் ஆப்பிரிக்கா"),
  CountryLocalization("kr", "கொரியன்", "தென் கொரியா"),
  CountryLocalization("ss", "நியூர்", "தெற்கு சூடான்"),
  CountryLocalization("es", "ஸ்பானிஷ்", "ஸ்பெயின்"),
  CountryLocalization("lk", "தமிழ்", "இலங்கை"),
  CountryLocalization("bl", "பிரெஞ்சு", "செயின்ட் பார்தேலெமி"),
  CountryLocalization("sh", "ஆங்கிலம்", "செயின்ட் ஹெலெனா"),
  CountryLocalization("kn", "ஆங்கிலம்", "செயின்ட் கிட்ஸ் & நெவிஸ்"),
  CountryLocalization("lc", "ஆங்கிலம்", "செயின்ட் லூசியா"),
  CountryLocalization("mf", "பிரெஞ்சு", "செயின்ட் மார்ட்டீன்"),
  CountryLocalization("pm", "பிரெஞ்சு", "செயின்ட் பியர் & மிக்வேலான்"),
  CountryLocalization("vc", "ஆங்கிலம்", "செயின்ட் வின்சென்ட் & கிரெனடைன்ஸ்"),
  CountryLocalization("sd", "அரபிக்", "சூடான்"),
  CountryLocalization("sr", "டச்சு", "சுரினாம்"),
  CountryLocalization("sj", "நார்வேஜியன் பொக்மால்", "ஸ்வல்பார்டு & ஜான் மேயன்"),
  CountryLocalization("sz", "ஆங்கிலம்", "ஸ்வாஸிலாந்து"),
  CountryLocalization("se", "ஸ்வீடிஷ்", "ஸ்வீடன்"),
  CountryLocalization("ch", "ஸ்விஸ் ஜெர்மன்", "ஸ்விட்சர்லாந்து"),
  CountryLocalization("sy", "அரபிக்", "சிரியா"),
  CountryLocalization("st", "போர்ச்சுக்கீஸ்", "சாவ் தோம் & ப்ரின்சிபி"),
  CountryLocalization("tw", "சீனம்", "தைவான்"),
  CountryLocalization("tj", "தஜிக்", "தஜிகிஸ்தான்"),
  CountryLocalization("tz", "மகொண்டே", "தான்சானியா"),
  CountryLocalization("th", "தாய்", "தாய்லாந்து"),
  CountryLocalization("tl", "போர்ச்சுக்கீஸ்", "தைமூர்-லெஸ்தே"),
  CountryLocalization("tg", "பிரெஞ்சு", "டோகோ"),
  CountryLocalization("tk", "ஆங்கிலம்", "டோகேலோ"),
  CountryLocalization("to", "டோங்கான்", "டோங்கா"),
  CountryLocalization("tt", "ஆங்கிலம்", "டிரினிடாட் & டொபாகோ"),
  CountryLocalization("tn", "பிரெஞ்சு", "டுனிசியா"),
  CountryLocalization("tr", "துருக்கிஷ்", "துருக்கி"),
  CountryLocalization("tm", "துருக்மென்", "துர்க்மெனிஸ்தான்"),
  CountryLocalization("tc", "ஆங்கிலம்", "டர்க்ஸ் & கைகோஸ் தீவுகள்"),
  CountryLocalization("tv", "ஆங்கிலம்", "துவாலூ"),
  CountryLocalization("um", "ஆங்கிலம்", "யூ.எஸ். வெளிப்புறத் தீவுகள்"),
  CountryLocalization("vi", "ஆங்கிலம்", "யூ.எஸ். கன்னித் தீவுகள்"),
  CountryLocalization("ug", "ஸ்வாஹிலி", "உகாண்டா"),
  CountryLocalization("ua", "உக்ரைனியன்", "உக்ரைன்"),
  CountryLocalization("ae", "அரபிக்", "ஐக்கிய அரபு எமிரேட்ஸ்"),
  CountryLocalization("gb", "ஆங்கிலம்", "யுனைடெட் கிங்டம்"),
  CountryLocalization("us", "லகோடா", "அமெரிக்கா"),
  CountryLocalization("uy", "ஸ்பானிஷ்", "உருகுவே"),
  CountryLocalization("uz", "உஸ்பெக்", "உஸ்பெகிஸ்தான்"),
  CountryLocalization("vu", "பிரெஞ்சு", "வனுவாட்டு"),
  CountryLocalization("va", "இத்தாலியன்", "வாடிகன் நகரம்"),
  CountryLocalization("ve", "ஸ்பானிஷ்", "வெனிசுலா"),
  CountryLocalization("vn", "வியட்நாமீஸ்", "வியட்நாம்"),
  CountryLocalization("wf", "பிரெஞ்சு", "வாலிஸ் மற்றும் ஃபுடுனா"),
  CountryLocalization("eh", "அரபிக்", "மேற்கு சஹாரா"),
  CountryLocalization("ye", "அரபிக்", "ஏமன்"),
  CountryLocalization("zm", "ஆங்கிலம்", "ஜாம்பியா"),
  CountryLocalization("zw", "வடக்கு தெபெலே", "ஜிம்பாப்வே"),
  CountryLocalization("ax", "ஸ்வீடிஷ்", "ஆலந்து தீவுகள்"),
)
