/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot.atlas.extended

import dev.teogor.xenoglot.atlas.CountryLocalization
import kotlin.collections.List

/**
 * Holds the internal list of country-language mappings used for lookups within the package for
 * language code ha.
 *
 * This property contains a hardcoded list of [CountryLocalization] objects, each representing
 * a country and its associated official languages. This list is used by [CountryLanguageRegistry]
 * to provide access to country-language data and should not be modified directly.
 *
 * @see CountryLocalization
 * @see CountryLanguageRegistry
 */
internal val _countryLanguageMappings_ha: List<CountryLocalization> = listOf(
  CountryLocalization("af", "Parisanci", "Afaganistan"),
  CountryLocalization("al", "Albanian", "Albaniya"),
  CountryLocalization("dz", "Faransanci", "Aljeriya"),
  CountryLocalization("as", "Turanci", "Samowa Ta Amurka"),
  CountryLocalization("ad", "Catalan", "Andora"),
  CountryLocalization("ao", "Lingala", "Angola"),
  CountryLocalization("ai", "Turanci", "Angila"),
  CountryLocalization("ag", "Turanci", "Antigwa da Barbuba"),
  CountryLocalization("ar", "Ispaniyanci", "Arjantiniya"),
  CountryLocalization("am", "Armenian", "Armeniya"),
  CountryLocalization("aw", "Holanci", "Aruba"),
  CountryLocalization("au", "Turanci", "Ostareliya"),
  CountryLocalization("at", "Turanci", "Ostiriya"),
  CountryLocalization("az", "Azerbaijani", "Azarbaijan"),
  CountryLocalization("bs", "Turanci", "Bahamas"),
  CountryLocalization("bh", "Larabci", "Baharan"),
  CountryLocalization("bd", "Bengali", "Bangiladas"),
  CountryLocalization("bb", "Turanci", "Barbadas"),
  CountryLocalization("by", "Belarusanci", "Belarus"),
  CountryLocalization("be", "Faransanci", "Belgiyom"),
  CountryLocalization("bz", "Turanci", "Beliz"),
  CountryLocalization("bj", "Faransanci", "Binin"),
  CountryLocalization("bm", "Turanci", "Barmuda"),
  CountryLocalization("bt", "Dzongkha", "Butan"),
  CountryLocalization("bo", "Ispaniyanci", "Bolibiya"),
  CountryLocalization("ba", "Bosnian", "Bosniya Harzagobina"),
  CountryLocalization("bw", "Turanci", "Baswana"),
  CountryLocalization("br", "Harshen Portugal", "Birazil"),
  CountryLocalization("io", "Turanci", "Yankin Birtaniya Na Tekun Indiya"),
  CountryLocalization("vg", "Turanci", "Tsibirin Birjin Na Birtaniya"),
  CountryLocalization("bn", "Harshen Malai", "Burune"),
  CountryLocalization("bg", "Bulgaranci", "Bulgariya"),
  CountryLocalization("bf", "Faransanci", "Burkina Faso"),
  CountryLocalization("bi", "Faransanci", "Burundi"),
  CountryLocalization("kh", "Harshen Kimar", "Kambodiya"),
  CountryLocalization("cm", "Basaa", "Kamaru"),
  CountryLocalization("ca", "Faransanci", "Kanada"),
  CountryLocalization("ic", "Ispaniyanci", "IC"),
  CountryLocalization("cv", "kea", "Tsibiran Kap Barde"),
  CountryLocalization("bq", "Holanci", "Caribbean Netherlands"),
  CountryLocalization("ky", "Turanci", "Tsibiran Kaiman"),
  CountryLocalization("cf", "Lingala", "Jamhuriyar Afirka Ta Tsakiya"),
  CountryLocalization("ea", "Ispaniyanci", "EA"),
  CountryLocalization("td", "Larabci", "Cadi"),
  CountryLocalization("cl", "Ispaniyanci", "Cayile"),
  CountryLocalization("cn", "Tibetan", "Caina, Sin"),
  CountryLocalization("cx", "Turanci", "Christmas Island"),
  CountryLocalization("cc", "Turanci", "Cocos (Keeling) Islands"),
  CountryLocalization("co", "Ispaniyanci", "Kolambiya"),
  CountryLocalization("km", "Larabci", "Kwamoras"),
  CountryLocalization("cg", "Lingala", "Kongo"),
  CountryLocalization("cd", "Swahili", "Jamhuriyar Dimokuraɗiyyar Kongo"),
  CountryLocalization("ck", "Turanci", "Tsibiran Kuku"),
  CountryLocalization("cr", "Ispaniyanci", "Kwasta Rika"),
  CountryLocalization("hr", "Croatian", "Kurowaishiya"),
  CountryLocalization("cu", "Ispaniyanci", "Kyuba"),
  CountryLocalization("cw", "Holanci", "Curaçao"),
  CountryLocalization("cy", "Turanci", "Sifurus"),
  CountryLocalization("cz", "Harshen Cak", "Jamhuriyar Cak"),
  CountryLocalization("ci", "Faransanci", "Aibari Kwas"),
  CountryLocalization("dk", "Turanci", "Danmark"),
  CountryLocalization("dg", "Turanci", "DG"),
  CountryLocalization("dj", "Faransanci", "Jibuti"),
  CountryLocalization("dm", "Turanci", "Dominika"),
  CountryLocalization("do", "Ispaniyanci", "Jamhuriyar Dominika"),
  CountryLocalization("ec", "Quechua", "Ekwador"),
  CountryLocalization("eg", "Larabci", "Masar, Misira"),
  CountryLocalization("sv", "Ispaniyanci", "El Salbador"),
  CountryLocalization("gq", "Ispaniyanci", "Gini Ta Ikwaita"),
  CountryLocalization("er", "Tigrinya", "Eritireya"),
  CountryLocalization("ee", "Estonian", "Estoniya"),
  CountryLocalization("et", "Amharik", "Habasha"),
  CountryLocalization("fk", "Turanci", "Tsibiran Falkilan"),
  CountryLocalization("fo", "Faroese", "Faroe Islands"),
  CountryLocalization("fj", "Turanci", "Fiji"),
  CountryLocalization("fi", "Harshen Suwedan", "Finlan"),
  CountryLocalization("fr", "Swiss German", "Faransa"),
  CountryLocalization("gf", "Faransanci", "Gini Ta Faransa"),
  CountryLocalization("pf", "Faransanci", "Folinesiya Ta Faransa"),
  CountryLocalization("ga", "Faransanci", "Gabon"),
  CountryLocalization("gm", "Turanci", "Gambiya"),
  CountryLocalization("ge", "Ossetic", "Jiwarjiya"),
  CountryLocalization("de", "Lower Sorbian", "Jamus"),
  CountryLocalization("gh", "Turanci", "Gana"),
  CountryLocalization("gi", "Turanci", "Jibaraltar"),
  CountryLocalization("gr", "Girkanci", "Girka"),
  CountryLocalization("gl", "Kalaallisut", "Grinlan"),
  CountryLocalization("gd", "Turanci", "Girnada"),
  CountryLocalization("gp", "Faransanci", "Gwadaluf"),
  CountryLocalization("gu", "Turanci", "Gwam"),
  CountryLocalization("gt", "Ispaniyanci", "Gwatamala"),
  CountryLocalization("gg", "Turanci", "Guernsey"),
  CountryLocalization("gn", "Faransanci", "Gini"),
  CountryLocalization("gw", "Harshen Portugal", "Gini Bisau"),
  CountryLocalization("gy", "Turanci", "Guyana"),
  CountryLocalization("ht", "Faransanci", "Haiti"),
  CountryLocalization("hn", "Ispaniyanci", "Honduras"),
  CountryLocalization("hk", "Harshen Sin", "Hong Kong SAR China"),
  CountryLocalization("hu", "Harshen Hungari", "Hungari"),
  CountryLocalization("is", "Icelandic", "Aisalan"),
  CountryLocalization("in", "Nepali", "Indiya"),
  CountryLocalization("id", "Indonesian", "Indunusiya"),
  CountryLocalization("ir", "Parisanci", "Iran"),
  CountryLocalization("iq", "lrc", "Iraƙi"),
  CountryLocalization("ie", "Turanci", "Ayalan"),
  CountryLocalization("im", "Manx", "Isle of Man"),
  CountryLocalization("il", "Turanci", "Iziraʼila"),
  CountryLocalization("it", "Jamusanci", "Italiya"),
  CountryLocalization("jm", "Turanci", "Jamaika"),
  CountryLocalization("jp", "Japananci", "Japan"),
  CountryLocalization("je", "Turanci", "Jersey"),
  CountryLocalization("jo", "Larabci", "Jordan"),
  CountryLocalization("kz", "Kazakh", "Kazakistan"),
  CountryLocalization("ke", "Somali", "Kenya"),
  CountryLocalization("ki", "Turanci", "Kiribati"),
  CountryLocalization("xk", "Serbian", "XK"),
  CountryLocalization("kw", "Larabci", "Kwiyat"),
  CountryLocalization("kg", "Rashanci", "Kirgizistan"),
  CountryLocalization("la", "Lao", "Lawas"),
  CountryLocalization("lv", "Latvian", "latibiya"),
  CountryLocalization("lb", "Larabci", "Labanan"),
  CountryLocalization("ls", "Turanci", "Lesoto"),
  CountryLocalization("lr", "Turanci", "Laberiya"),
  CountryLocalization("ly", "Larabci", "Libiya"),
  CountryLocalization("li", "Swiss German", "Licansitan"),
  CountryLocalization("lt", "Lithuanian", "Lituweniya"),
  CountryLocalization("lu", "Luxembourgish", "Lukusambur"),
  CountryLocalization("mo", "Harshen Portugal", "Macao SAR China"),
  CountryLocalization("mk", "Albanian", "Masedoniya"),
  CountryLocalization("mg", "Faransanci", "Madagaskar"),
  CountryLocalization("mw", "Turanci", "Malawi"),
  CountryLocalization("my", "Tamil", "Malaisiya"),
  CountryLocalization("ml", "Faransanci", "Mali"),
  CountryLocalization("mt", "Turanci", "Malta"),
  CountryLocalization("mh", "Turanci", "Tsibiran Marshal"),
  CountryLocalization("mq", "Faransanci", "Martinik"),
  CountryLocalization("mr", "Larabci", "Moritaniya"),
  CountryLocalization("mu", "mfe", "Moritus"),
  CountryLocalization("yt", "Faransanci", "Mayoti"),
  CountryLocalization("mx", "Ispaniyanci", "Makasiko"),
  CountryLocalization("fm", "Turanci", "Mikuronesiya"),
  CountryLocalization("md", "Rashanci", "Maldoba"),
  CountryLocalization("mc", "Faransanci", "Monako"),
  CountryLocalization("mn", "Mongolian", "Mangoliya"),
  CountryLocalization("me", "Serbian", "Montenegro"),
  CountryLocalization("ms", "Turanci", "Manserati"),
  CountryLocalization("ma", "tzm", "Maroko"),
  CountryLocalization("mz", "mgh", "Mozambik"),
  CountryLocalization("mm", "Burmanci", "Burma, Miyamar"),
  CountryLocalization("na", "Turanci", "Namibiya"),
  CountryLocalization("nr", "Turanci", "Nauru"),
  CountryLocalization("np", "Nepali", "Nefal"),
  CountryLocalization("nl", "Turanci", "Holan"),
  CountryLocalization("nc", "Faransanci", "Kaledoniya Sabuwa"),
  CountryLocalization("nz", "Turanci", "Nuzilan"),
  CountryLocalization("ni", "Ispaniyanci", "Nikaraguwa"),
  CountryLocalization("ne", "Hausa", "Nijar"),
  CountryLocalization("ng", "Hausa", "Najeriya"),
  CountryLocalization("nu", "Turanci", "Niyu"),
  CountryLocalization("nf", "Turanci", "Tsibirin Narfalk"),
  CountryLocalization("kp", "Harshen Koreya", "Koreya Ta Arewa"),
  CountryLocalization("mp", "Turanci", "Tsibiran Mariyana Na Arewa"),
  CountryLocalization("no", "Northern Sami", "Norwe"),
  CountryLocalization("om", "Larabci", "Oman"),
  CountryLocalization("pk", "Turanci", "Pakistan"),
  CountryLocalization("pw", "Turanci", "Palau"),
  CountryLocalization("ps", "Larabci", "Palasɗinu"),
  CountryLocalization("pa", "Ispaniyanci", "Panama"),
  CountryLocalization("pg", "Turanci", "Papuwa Nugini"),
  CountryLocalization("py", "Ispaniyanci", "Paragai"),
  CountryLocalization("pe", "Ispaniyanci", "Peru"),
  CountryLocalization("ph", "Filipino", "Filipin"),
  CountryLocalization("pn", "Turanci", "Pitakarin"),
  CountryLocalization("pl", "Harshen Polan", "Polan"),
  CountryLocalization("pt", "Harshen Portugal", "Portugal"),
  CountryLocalization("pr", "Turanci", "Porto Riko"),
  CountryLocalization("qa", "Larabci", "Kwatar"),
  CountryLocalization("ro", "Romaniyanci", "Romaniya"),
  CountryLocalization("ru", "Tatar", "Rasha"),
  CountryLocalization("rw", "Turanci", "Ruwanda"),
  CountryLocalization("re", "Faransanci", "Rawuniyan"),
  CountryLocalization("ws", "Turanci", "Samowa"),
  CountryLocalization("sm", "Italiyanci", "San Marino"),
  CountryLocalization("sa", "Larabci", "Ƙasar Makka"),
  CountryLocalization("sn", "Faransanci", "Sinigal"),
  CountryLocalization("rs", "Serbian", "Serbia"),
  CountryLocalization("cs", "Serbian", "Serbia and Montenegro"),
  CountryLocalization("sc", "Faransanci", "Saishal"),
  CountryLocalization("sl", "Turanci", "Salewo"),
  CountryLocalization("sg", "Tamil", "Singapur"),
  CountryLocalization("sx", "Turanci", "Sint Maarten"),
  CountryLocalization("sk", "Slovak", "Sulobakiya"),
  CountryLocalization("si", "Slovenian", "Sulobeniya"),
  CountryLocalization("sb", "Turanci", "Tsibiran Salaman"),
  CountryLocalization("so", "Larabci", "Somaliya"),
  CountryLocalization("za", "Turanci", "Afirka Ta Kudu"),
  CountryLocalization("kr", "Harshen Koreya", "Koreya Ta Kudu"),
  CountryLocalization("ss", "nus", "South Sudan"),
  CountryLocalization("es", "Ispaniyanci", "Sipen"),
  CountryLocalization("lk", "Tamil", "Siri Lanka"),
  CountryLocalization("bl", "Faransanci", "St. Barthélemy"),
  CountryLocalization("sh", "Turanci", "San Helena"),
  CountryLocalization("kn", "Turanci", "San Kiti Da Nebis"),
  CountryLocalization("lc", "Turanci", "San Lusiya"),
  CountryLocalization("mf", "Faransanci", "St. Martin"),
  CountryLocalization("pm", "Faransanci", "San Piyar Da Mikelan"),
  CountryLocalization("vc", "Turanci", "San Binsan Da Girnadin"),
  CountryLocalization("sd", "Larabci", "Sudan"),
  CountryLocalization("sr", "Holanci", "Suriname"),
  CountryLocalization("sj", "Norwegian Bokmål", "Svalbard & Jan Mayen"),
  CountryLocalization("sz", "Turanci", "Suwazilan"),
  CountryLocalization("se", "Harshen Suwedan", "Suwedan"),
  CountryLocalization("ch", "Swiss German", "Suwizalan"),
  CountryLocalization("sy", "Larabci", "Sham, Siriya"),
  CountryLocalization("st", "Harshen Portugal", "Sawo Tome Da Paransip"),
  CountryLocalization("tw", "Harshen Sin", "Taiwan"),
  CountryLocalization("tj", "Tajik", "Tajikistan"),
  CountryLocalization("tz", "kde", "Tanzaniya"),
  CountryLocalization("th", "Thai", "Tailan"),
  CountryLocalization("tl", "Harshen Portugal", "Timor Ta Gabas"),
  CountryLocalization("tg", "Faransanci", "Togo"),
  CountryLocalization("tk", "Turanci", "Takelau"),
  CountryLocalization("to", "Tongan", "Tanga"),
  CountryLocalization("tt", "Turanci", "Tirinidad Da Tobago"),
  CountryLocalization("tn", "Faransanci", "Tunisiya"),
  CountryLocalization("tr", "Harshen Turkiyya", "Turkiyya"),
  CountryLocalization("tm", "Turkmen", "Turkumenistan"),
  CountryLocalization("tc", "Turanci", "Turkis Da Tsibiran Kaikwas"),
  CountryLocalization("tv", "Turanci", "Tubalu"),
  CountryLocalization("um", "Turanci", "U.S. Outlying Islands"),
  CountryLocalization("vi", "Turanci", "Tsibiran Birjin Ta Amurka"),
  CountryLocalization("ug", "Swahili", "Yuganda"),
  CountryLocalization("ua", "Harshen Yukuren", "Yukaran"),
  CountryLocalization("ae", "Larabci", "Haɗaɗɗiyar Daular Larabawa"),
  CountryLocalization("gb", "Turanci", "Birtaniya"),
  CountryLocalization("us", "lkt", "Amurka"),
  CountryLocalization("uy", "Ispaniyanci", "Yurugai"),
  CountryLocalization("uz", "Uzbek", "Uzubekistan"),
  CountryLocalization("vu", "Faransanci", "Banuwatu"),
  CountryLocalization("va", "Italiyanci", "Batikan"),
  CountryLocalization("ve", "Ispaniyanci", "Benezuwela"),
  CountryLocalization("vn", "Harshen Biyetinam", "Biyetinam"),
  CountryLocalization("wf", "Faransanci", "Walis Da Futuna"),
  CountryLocalization("eh", "Larabci", "Western Sahara"),
  CountryLocalization("ye", "Larabci", "Yamal"),
  CountryLocalization("zm", "Turanci", "Zambiya"),
  CountryLocalization("zw", "North Ndebele", "Zimbabuwe"),
  CountryLocalization("ax", "Harshen Suwedan", "Åland Islands"),
)
