/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot.atlas.extended

import dev.teogor.xenoglot.atlas.CountryLocalization
import kotlin.collections.List

/**
 * Holds the internal list of country-language mappings used for lookups within the package for
 * language code tzm.
 *
 * This property contains a hardcoded list of [CountryLocalization] objects, each representing
 * a country and its associated official languages. This list is used by [CountryLanguageRegistry]
 * to provide access to country-language data and should not be modified directly.
 *
 * @see CountryLocalization
 * @see CountryLanguageRegistry
 */
internal val _countryLanguageMappings_tzm: List<CountryLocalization> = listOf(
  CountryLocalization("af", "Tafarisit", "Afɣanistan"),
  CountryLocalization("al", "Albanian", "Albanya"),
  CountryLocalization("dz", "Tafṛansist", "Dzayer"),
  CountryLocalization("as", "Tanglizt", "Samwa Imirikaniyyin"),
  CountryLocalization("ad", "Catalan", "Anḍurra"),
  CountryLocalization("ao", "Lingala", "Angula"),
  CountryLocalization("ai", "Tanglizt", "Angwilla"),
  CountryLocalization("ag", "Tanglizt", "Antigwa d Barbuda"),
  CountryLocalization("ar", "tasbelyunit", "Arjuntin"),
  CountryLocalization("am", "Armenian", "Arminya"),
  CountryLocalization("aw", "Tahulanḍit", "Aruba"),
  CountryLocalization("au", "Tanglizt", "Usṭralya"),
  CountryLocalization("at", "Tanglizt", "Ustriyya"),
  CountryLocalization("az", "Azerbaijani", "Azerbiǧan"),
  CountryLocalization("bs", "Tanglizt", "Bahamas"),
  CountryLocalization("bh", "Taεrabt", "Baḥrayn"),
  CountryLocalization("bd", "Tabinɣalit", "Bangladic"),
  CountryLocalization("bb", "Tanglizt", "Barbadus"),
  CountryLocalization("by", "Tabilarusit", "Bilarusya"),
  CountryLocalization("be", "Tafṛansist", "Beljika"),
  CountryLocalization("bz", "Tanglizt", "Biliz"),
  CountryLocalization("bj", "Tafṛansist", "Binin"),
  CountryLocalization("bm", "Tanglizt", "Birmuda"),
  CountryLocalization("bt", "Dzongkha", "Buṭan"),
  CountryLocalization("bo", "tasbelyunit", "Bulivya"),
  CountryLocalization("ba", "Bosnian", "Busna-d-Hirsik"),
  CountryLocalization("bw", "Tanglizt", "Butswana"),
  CountryLocalization("br", "Taburtuɣalit", "Bṛazil"),
  CountryLocalization("io", "Tanglizt", "Amur n Agaraw Uhindi Ubṛiṭani"),
  CountryLocalization("vg", "Tanglizt", "Tigzirin (Virgin) Tibṛiṭaniyin"),
  CountryLocalization("bn", "Tamalizit", "Brunay"),
  CountryLocalization("bg", "Tabelɣarit", "Belɣarya"),
  CountryLocalization("bf", "Tafṛansist", "Burkina Fasu"),
  CountryLocalization("bi", "Tafṛansist", "Burundi"),
  CountryLocalization("kh", "Taxmert ,Talammast", "Kambudj"),
  CountryLocalization("cm", "Basaa", "Kamerun"),
  CountryLocalization("ca", "Tafṛansist", "Kanada"),
  CountryLocalization("ic", "tasbelyunit", "IC"),
  CountryLocalization("cv", "kea", "Tigzirin n Iɣf Uzegzaw"),
  CountryLocalization("bq", "Tahulanḍit", "Caribbean Netherlands"),
  CountryLocalization("ky", "Tanglizt", "Tigzirin n Kayman"),
  CountryLocalization("cf", "Lingala", "Tagduda n Afrika Wammas"),
  CountryLocalization("ea", "tasbelyunit", "EA"),
  CountryLocalization("td", "Taεrabt", "Tcad"),
  CountryLocalization("cl", "tasbelyunit", "Ccili"),
  CountryLocalization("cn", "Tibetan", "Ṣṣin"),
  CountryLocalization("cx", "Tanglizt", "Christmas Island"),
  CountryLocalization("cc", "Tanglizt", "Cocos (Keeling) Islands"),
  CountryLocalization("co", "tasbelyunit", "Kulumbya"),
  CountryLocalization("km", "Taεrabt", "Qumur"),
  CountryLocalization("cg", "Lingala", "Kungu"),
  CountryLocalization("cd", "Swahili", "Tagduda Tadimuqraṭit n Kungu"),
  CountryLocalization("ck", "Tanglizt", "Tigzirin n Kuk"),
  CountryLocalization("cr", "tasbelyunit", "Kusṭa Rika"),
  CountryLocalization("hr", "Croatian", "Krwatya"),
  CountryLocalization("cu", "tasbelyunit", "kuba"),
  CountryLocalization("cw", "Tahulanḍit", "Curaçao"),
  CountryLocalization("cy", "Tanglizt", "Qubrus"),
  CountryLocalization("cz", "Tačikt", "Tagduda n Čik"),
  CountryLocalization("ci", "Tafṛansist", "Taɣazut n Uszer"),
  CountryLocalization("dk", "Tanglizt", "Danmark"),
  CountryLocalization("dg", "Tanglizt", "DG"),
  CountryLocalization("dj", "Tafṛansist", "Ǧibuti"),
  CountryLocalization("dm", "Tanglizt", "Ḍuminika"),
  CountryLocalization("do", "tasbelyunit", "Tagduda n Ḍuminikan"),
  CountryLocalization("ec", "Quechua", "Ikwaḍur"),
  CountryLocalization("eg", "Taεrabt", "Miṣr"),
  CountryLocalization("sv", "tasbelyunit", "Salvaḍur"),
  CountryLocalization("gq", "tasbelyunit", "Ɣinya Tikwaṭur it"),
  CountryLocalization("er", "Tigrinya", "Iritrya"),
  CountryLocalization("ee", "Estonian", "Isṭunya"),
  CountryLocalization("et", "Tamharit", "Ityupya"),
  CountryLocalization("fk", "Tanglizt", "Tigzirin n Falkland"),
  CountryLocalization("fo", "Faroese", "Faroe Islands"),
  CountryLocalization("fj", "Tanglizt", "Fiji"),
  CountryLocalization("fi", "Taswidit", "Finlanḍa"),
  CountryLocalization("fr", "Swiss German", "Fṛansa"),
  CountryLocalization("gf", "Tafṛansist", "Guyana Tafransist"),
  CountryLocalization("pf", "Tafṛansist", "Pulinizya Tafransist"),
  CountryLocalization("ga", "Tafṛansist", "Gabun"),
  CountryLocalization("gm", "Tanglizt", "Gambya"),
  CountryLocalization("ge", "Ossetic", "Jyurjya"),
  CountryLocalization("de", "Lower Sorbian", "Almanya"),
  CountryLocalization("gh", "Tanglizt", "Ɣana"),
  CountryLocalization("gi", "Tanglizt", "Jibralṭar"),
  CountryLocalization("gr", "Tayunanit", "Yunan"),
  CountryLocalization("gl", "Kalaallisut", "Grinlanḍa"),
  CountryLocalization("gd", "Tanglizt", "Grinada"),
  CountryLocalization("gp", "Tafṛansist", "Gwadalup"),
  CountryLocalization("gu", "Tanglizt", "Gwam"),
  CountryLocalization("gt", "tasbelyunit", "Gwatimala"),
  CountryLocalization("gg", "Tanglizt", "Guernsey"),
  CountryLocalization("gn", "Tafṛansist", "Ɣinya"),
  CountryLocalization("gw", "Taburtuɣalit", "Ɣinya-Bissaw"),
  CountryLocalization("gy", "Tanglizt", "Guyana"),
  CountryLocalization("ht", "Tafṛansist", "Hayti"),
  CountryLocalization("hn", "tasbelyunit", "Hinduras"),
  CountryLocalization("hk", "Tacinwit,Mandarin", "Hong Kong SAR China"),
  CountryLocalization("hu", "Tahenɣarit", "Henɣarya"),
  CountryLocalization("is", "Icelandic", "Islanḍa"),
  CountryLocalization("in", "Tanippalit", "Hind"),
  CountryLocalization("id", "Indonesian", "Indunizya"),
  CountryLocalization("ir", "Tafarisit", "Iran"),
  CountryLocalization("iq", "lrc", "Ɛiraq"),
  CountryLocalization("ie", "Tanglizt", "Irlanḍa"),
  CountryLocalization("im", "Manx", "Isle of Man"),
  CountryLocalization("il", "Tanglizt", "Israeil"),
  CountryLocalization("it", "Talmanit", "Iṭalya"),
  CountryLocalization("jm", "Tanglizt", "Jamayka"),
  CountryLocalization("jp", "Tajappunit", "Jjappun"),
  CountryLocalization("je", "Tanglizt", "Jersey"),
  CountryLocalization("jo", "Taεrabt", "Urḍun"),
  CountryLocalization("kz", "Kazakh", "Kazaxistan"),
  CountryLocalization("ke", "Taṣumalit", "Kinya"),
  CountryLocalization("ki", "Tanglizt", "Kiribati"),
  CountryLocalization("xk", "Serbian", "XK"),
  CountryLocalization("kw", "Taεrabt", "Kuwwayt"),
  CountryLocalization("kg", "Tarusit", "Kirɣistan"),
  CountryLocalization("la", "Lao", "Laws"),
  CountryLocalization("lv", "Latvian", "Liṭṭunya"),
  CountryLocalization("lb", "Taεrabt", "Lubnan"),
  CountryLocalization("ls", "Tanglizt", "Lisuṭu"),
  CountryLocalization("lr", "Tanglizt", "Libirya"),
  CountryLocalization("ly", "Taεrabt", "Libya"),
  CountryLocalization("li", "Swiss German", "Lictencṭayn"),
  CountryLocalization("lt", "Lithuanian", "Litwanya"),
  CountryLocalization("lu", "Luxembourgish", "Liksumburg"),
  CountryLocalization("mo", "Taburtuɣalit", "Macao SAR China"),
  CountryLocalization("mk", "Albanian", "Maqdunya"),
  CountryLocalization("mg", "Tafṛansist", "Madaɣacqar"),
  CountryLocalization("mw", "Tanglizt", "Malawi"),
  CountryLocalization("my", "Tatamilt", "Malizya"),
  CountryLocalization("ml", "Tafṛansist", "Mali"),
  CountryLocalization("mt", "Tanglizt", "Malṭa"),
  CountryLocalization("mh", "Tanglizt", "Tigzirin n Marcal"),
  CountryLocalization("mq", "Tafṛansist", "Martinik"),
  CountryLocalization("mr", "Taεrabt", "Muritanya"),
  CountryLocalization("mu", "mfe", "Muris"),
  CountryLocalization("yt", "Tafṛansist", "Mayuṭ"),
  CountryLocalization("mx", "tasbelyunit", "Miksik"),
  CountryLocalization("fm", "Tanglizt", "Mikrunizya"),
  CountryLocalization("md", "Tarusit", "Mulḍavya"),
  CountryLocalization("mc", "Tafṛansist", "Munaku"),
  CountryLocalization("mn", "Mongolian", "Manɣulya"),
  CountryLocalization("me", "Serbian", "Montenegro"),
  CountryLocalization("ms", "Tanglizt", "Muntsirra"),
  CountryLocalization("ma", "Tamaziɣt n laṭlaṣ", "Meṛṛuk"),
  CountryLocalization("mz", "mgh", "Muzambiq"),
  CountryLocalization("mm", "Taburmanit", "Myanmar"),
  CountryLocalization("na", "Tanglizt", "Namibya"),
  CountryLocalization("nr", "Tanglizt", "Nawru"),
  CountryLocalization("np", "Tanippalit", "Nippal"),
  CountryLocalization("nl", "Tanglizt", "Hulanḍa"),
  CountryLocalization("nc", "Tafṛansist", "kalidunya Tamaynut"),
  CountryLocalization("nz", "Tanglizt", "Zilanḍa Tamaynut"),
  CountryLocalization("ni", "tasbelyunit", "Nikaragwa"),
  CountryLocalization("ne", "Tahawsat", "Nnijer"),
  CountryLocalization("ng", "Tahawsat", "Nijiria"),
  CountryLocalization("nu", "Tanglizt", "Niwi"),
  CountryLocalization("nf", "Tanglizt", "Tigzirt Nurfulk"),
  CountryLocalization("kp", "Takurit", "Kurya Tugafat"),
  CountryLocalization("mp", "Tanglizt", "Tigzirin n Maryana Tugafat"),
  CountryLocalization("no", "Northern Sami", "Nnurwij"),
  CountryLocalization("om", "Taεrabt", "Ɛumman"),
  CountryLocalization("pk", "Tanglizt", "Pakistan"),
  CountryLocalization("pw", "Tanglizt", "Palu"),
  CountryLocalization("ps", "Taεrabt", "Agemmaḍ Ugut d Ɣazza Ifilisṭiniyen"),
  CountryLocalization("pa", "tasbelyunit", "Panama"),
  CountryLocalization("pg", "Tanglizt", "Papwa Ɣinya Tamaynut"),
  CountryLocalization("py", "tasbelyunit", "Paragway"),
  CountryLocalization("pe", "tasbelyunit", "Piru"),
  CountryLocalization("ph", "Filipino", "Filippin"),
  CountryLocalization("pn", "Tanglizt", "Pitkirn"),
  CountryLocalization("pl", "Tappulunit", "Pulunya"),
  CountryLocalization("pt", "Taburtuɣalit", "Purtuɣal"),
  CountryLocalization("pr", "Tanglizt", "Purturiku"),
  CountryLocalization("qa", "Taεrabt", "Qaṭar"),
  CountryLocalization("ro", "Taṛumanit", "Ṛumanya"),
  CountryLocalization("ru", "Tatar", "Rusya"),
  CountryLocalization("rw", "Tanglizt", "Ruwwanḍa"),
  CountryLocalization("re", "Tafṛansist", "Riyyunyun"),
  CountryLocalization("ws", "Tanglizt", "Samwa"),
  CountryLocalization("sm", "Taṭalyant", "Sanmarinu"),
  CountryLocalization("sa", "Taεrabt", "Ssaεudiyya Taεrabt"),
  CountryLocalization("sn", "Tafṛansist", "Ssiniɣal"),
  CountryLocalization("rs", "Serbian", "Serbia"),
  CountryLocalization("cs", "Serbian", "Serbia and Montenegro"),
  CountryLocalization("sc", "Tafṛansist", "Ssicil"),
  CountryLocalization("sl", "Tanglizt", "Siralyun"),
  CountryLocalization("sg", "Tatamilt", "Sanɣafura"),
  CountryLocalization("sx", "Tanglizt", "Sint Maarten"),
  CountryLocalization("sk", "Slovak", "Sluvakya"),
  CountryLocalization("si", "Slovenian", "Sluvinya"),
  CountryLocalization("sb", "Tanglizt", "Tigzirin n Salumun"),
  CountryLocalization("so", "Taεrabt", "Ṣṣumal"),
  CountryLocalization("za", "Tanglizt", "Tafrikt Tunẓul"),
  CountryLocalization("kr", "Takurit", "Kurya Tunẓult"),
  CountryLocalization("ss", "nus", "South Sudan"),
  CountryLocalization("es", "tasbelyunit", "Sbanya"),
  CountryLocalization("lk", "Tatamilt", "Srilanka"),
  CountryLocalization("bl", "Tafṛansist", "St. Barthélemy"),
  CountryLocalization("sh", "Tanglizt", "Santehilin"),
  CountryLocalization("kn", "Tanglizt", "Santekits d Nivis"),
  CountryLocalization("lc", "Tanglizt", "Santelusya"),
  CountryLocalization("mf", "Tafṛansist", "St. Martin"),
  CountryLocalization("pm", "Tafṛansist", "Santepyir d Mikelun"),
  CountryLocalization("vc", "Tanglizt", "Santevinsent d Grinadin"),
  CountryLocalization("sd", "Taεrabt", "Ssudan"),
  CountryLocalization("sr", "Tahulanḍit", "Surinam"),
  CountryLocalization("sj", "Norwegian Bokmål", "Svalbard & Jan Mayen"),
  CountryLocalization("sz", "Tanglizt", "Swazilanḍa"),
  CountryLocalization("se", "Taswidit", "Ssewwid"),
  CountryLocalization("ch", "Swiss German", "Swisra"),
  CountryLocalization("sy", "Taεrabt", "Surya"),
  CountryLocalization("st", "Taburtuɣalit", "Sawṭumi d Prinsip"),
  CountryLocalization("tw", "Tacinwit,Mandarin", "Ṭaywan"),
  CountryLocalization("tj", "Tajik", "Ṭaǧikistan"),
  CountryLocalization("tz", "kde", "Ṭanzanya"),
  CountryLocalization("th", "Taṭayt", "Ṭaylanḍa"),
  CountryLocalization("tl", "Taburtuɣalit", "Timur Tagmuṭ"),
  CountryLocalization("tg", "Tafṛansist", "Ṭṭugu"),
  CountryLocalization("tk", "Tanglizt", "Tuklu"),
  CountryLocalization("to", "Tongan", "Ṭunga"),
  CountryLocalization("tt", "Tanglizt", "Trinidad d Ṭubagu"),
  CountryLocalization("tn", "Tafṛansist", "Tunes"),
  CountryLocalization("tr", "Taturkit", "Turkya"),
  CountryLocalization("tm", "Turkmen", "Turkmanistan"),
  CountryLocalization("tc", "Tanglizt", "Tigzirin Turkiyyin d Tikaykusin"),
  CountryLocalization("tv", "Tanglizt", "Ṭuvalu"),
  CountryLocalization("um", "Tanglizt", "U.S. Outlying Islands"),
  CountryLocalization("vi", "Tanglizt", "Tigzirin n Virjin n Iwunak Yedduklen"),
  CountryLocalization("ug", "Swahili", "Uɣanda"),
  CountryLocalization("ua", "Tukranit", "Ukranya"),
  CountryLocalization("ae", "Taεrabt", "Imarat Tiεrabin Tidduklin"),
  CountryLocalization("gb", "Tanglizt", "Tagelda Taddukelt"),
  CountryLocalization("us", "lkt", "Iwunak Idduklen n Amirika"),
  CountryLocalization("uy", "tasbelyunit", "Urugway"),
  CountryLocalization("uz", "Uzbek", "Uzbakistan"),
  CountryLocalization("vu", "Tafṛansist", "Vanwatu"),
  CountryLocalization("va", "Taṭalyant", "Awank iɣrem n Vatikan"),
  CountryLocalization("ve", "tasbelyunit", "Vinzwilla"),
  CountryLocalization("vn", "Taviṭnamit", "Viṭnam"),
  CountryLocalization("wf", "Tafṛansist", "Walis d Futuna"),
  CountryLocalization("eh", "Taεrabt", "Western Sahara"),
  CountryLocalization("ye", "Taεrabt", "Yaman"),
  CountryLocalization("zm", "Tanglizt", "Zambya"),
  CountryLocalization("zw", "North Ndebele", "Zimbabwi"),
  CountryLocalization("ax", "Taswidit", "Åland Islands"),
)
