/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot.atlas.extended

import dev.teogor.xenoglot.atlas.CountryLocalization
import kotlin.collections.List

/**
 * Holds the internal list of country-language mappings used for lookups within the package for
 * language code ne.
 *
 * This property contains a hardcoded list of [CountryLocalization] objects, each representing
 * a country and its associated official languages. This list is used by [CountryLanguageRegistry]
 * to provide access to country-language data and should not be modified directly.
 *
 * @see CountryLocalization
 * @see CountryLanguageRegistry
 */
internal val _countryLanguageMappings_ne: List<CountryLocalization> = listOf(
  CountryLocalization("af", "फारसी", "अफगानिस्तान"),
  CountryLocalization("al", "अल्बानियाली", "अल्बेनिया"),
  CountryLocalization("dz", "फ्रान्सेली", "अल्जेरिया"),
  CountryLocalization("as", "अङ्ग्रेजी", "अमेरिकी समोआ"),
  CountryLocalization("ad", "क्याटालन", "अन्डोर्रा"),
  CountryLocalization("ao", "लिङ्गाला", "अङ्गोला"),
  CountryLocalization("ai", "अङ्ग्रेजी", "आङ्गुइला"),
  CountryLocalization("ag", "अङ्ग्रेजी", "एन्टिगुआ र बारबुडा"),
  CountryLocalization("ar", "स्पेनी", "अर्जेन्टिना"),
  CountryLocalization("am", "आर्मेनियाली", "आर्मेनिया"),
  CountryLocalization("aw", "डच", "अरुबा"),
  CountryLocalization("au", "अङ्ग्रेजी", "अष्ट्रेलिया"),
  CountryLocalization("at", "अङ्ग्रेजी", "अष्ट्रिया"),
  CountryLocalization("az", "अजरबैजानी", "अजरबैजान"),
  CountryLocalization("bs", "अङ्ग्रेजी", "बहामास"),
  CountryLocalization("bh", "अरबी", "बहराइन"),
  CountryLocalization("bd", "बंगाली", "बङ्गलादेश"),
  CountryLocalization("bb", "अङ्ग्रेजी", "बार्बाडोस"),
  CountryLocalization("by", "बेलारुसी", "बेलारूस"),
  CountryLocalization("be", "फ्रान्सेली", "बेल्जियम"),
  CountryLocalization("bz", "अङ्ग्रेजी", "बेलिज"),
  CountryLocalization("bj", "फ्रान्सेली", "बेनिन"),
  CountryLocalization("bm", "अङ्ग्रेजी", "बर्मुडा"),
  CountryLocalization("bt", "जोङ्खा", "भुटान"),
  CountryLocalization("bo", "स्पेनी", "बोलिभिया"),
  CountryLocalization("ba", "बोस्नियाली", "बोस्निया एण्ड हर्जगोभिनिया"),
  CountryLocalization("bw", "अङ्ग्रेजी", "बोट्स्वाना"),
  CountryLocalization("br", "पोर्तुगी", "ब्राजिल"),
  CountryLocalization("io", "अङ्ग्रेजी", "बेलायती हिन्द महासागर क्षेत्र"),
  CountryLocalization("vg", "अङ्ग्रेजी", "बेलायती भर्जिन टापुहरु"),
  CountryLocalization("bn", "मलाय", "ब्रुनाइ"),
  CountryLocalization("bg", "बुल्गेरियाली", "बुल्गेरिया"),
  CountryLocalization("bf", "फ्रान्सेली", "बर्किना फासो"),
  CountryLocalization("bi", "फ्रान्सेली", "बुरूण्डी"),
  CountryLocalization("kh", "खमेर", "कम्बोडिया"),
  CountryLocalization("cm", "बासा", "क्यामरून"),
  CountryLocalization("ca", "फ्रान्सेली", "क्यानाडा"),
  CountryLocalization("ic", "स्पेनी", "क्यानारी टापुहरू"),
  CountryLocalization("cv", "काबुभेर्डियानु", "केप भर्डे"),
  CountryLocalization("bq", "डच", "क्यारिवियन नेदरल्याण्ड्स"),
  CountryLocalization("ky", "अङ्ग्रेजी", "केयमान टापु"),
  CountryLocalization("cf", "लिङ्गाला", "केन्द्रीय अफ्रिकी गणतन्त्र"),
  CountryLocalization("ea", "स्पेनी", "सिउटा र मेलिला"),
  CountryLocalization("td", "अरबी", "चाड"),
  CountryLocalization("cl", "स्पेनी", "चिली"),
  CountryLocalization("cn", "तिब्बती", "चीन"),
  CountryLocalization("cx", "अङ्ग्रेजी", "क्रिष्टमस टापु"),
  CountryLocalization("cc", "अङ्ग्रेजी", "कोकोस (किलिंग) टापुहरु"),
  CountryLocalization("co", "स्पेनी", "कोलोम्बिया"),
  CountryLocalization("km", "अरबी", "कोमोरोस"),
  CountryLocalization("cg", "लिङ्गाला", "कङ्गो ब्राजाभिल"),
  CountryLocalization("cd", "स्वाहिली", "कङ्गो - किन्शासा"),
  CountryLocalization("ck", "अङ्ग्रेजी", "कुक टापुहरु"),
  CountryLocalization("cr", "स्पेनी", "कोष्टारिका"),
  CountryLocalization("hr", "क्रोयसियाली", "क्रोएशिया"),
  CountryLocalization("cu", "स्पेनी", "क्युबा"),
  CountryLocalization("cw", "डच", "कुराकाओ"),
  CountryLocalization("cy", "अङ्ग्रेजी", "साइप्रस"),
  CountryLocalization("cz", "चेक", "चेकिया"),
  CountryLocalization("ci", "फ्रान्सेली", "आइभोरी कोस्ट"),
  CountryLocalization("dk", "अङ्ग्रेजी", "डेनमार्क"),
  CountryLocalization("dg", "अङ्ग्रेजी", "डियगो गार्सिया"),
  CountryLocalization("dj", "फ्रान्सेली", "डिजिबुटी"),
  CountryLocalization("dm", "अङ्ग्रेजी", "डोमिनिका"),
  CountryLocalization("do", "स्पेनी", "डोमिनिकन गणतन्त्र"),
  CountryLocalization("ec", "क्वेचुवा", "इक्वेडोर"),
  CountryLocalization("eg", "अरबी", "इजिप्ट"),
  CountryLocalization("sv", "स्पेनी", "एल् साल्भाडोर"),
  CountryLocalization("gq", "स्पेनी", "भू-मध्यीय गिनी"),
  CountryLocalization("er", "टिग्रिन्या", "एरित्रिया"),
  CountryLocalization("ee", "इस्टोनियन", "इस्टोनिया"),
  CountryLocalization("et", "अम्हारिक", "इथियोपिया"),
  CountryLocalization("fk", "अङ्ग्रेजी", "फकल्याण्ड टापुहरु"),
  CountryLocalization("fo", "फारोज", "फारो टापुहरू"),
  CountryLocalization("fj", "अङ्ग्रेजी", "फिजी"),
  CountryLocalization("fi", "स्विडिस", "फिन्ल्याण्ड"),
  CountryLocalization("fr", "स्वीस जर्मन", "फ्रान्स"),
  CountryLocalization("gf", "फ्रान्सेली", "फ्रान्सेली गायना"),
  CountryLocalization("pf", "फ्रान्सेली", "फ्रान्सेली पोलिनेसिया"),
  CountryLocalization("ga", "फ्रान्सेली", "गावोन"),
  CountryLocalization("gm", "अङ्ग्रेजी", "गाम्विया"),
  CountryLocalization("ge", "अोस्सेटिक", "जर्जिया"),
  CountryLocalization("de", "तल्लो सोर्बियन", "जर्मनी"),
  CountryLocalization("gh", "अङ्ग्रेजी", "घाना"),
  CountryLocalization("gi", "अङ्ग्रेजी", "जिब्राल्टार"),
  CountryLocalization("gr", "ग्रीक", "ग्रिस"),
  CountryLocalization("gl", "कालालिसुट", "ग्रिनल्याण्ड"),
  CountryLocalization("gd", "अङ्ग्रेजी", "ग्रेनाडा"),
  CountryLocalization("gp", "फ्रान्सेली", "ग्वाडेलुप"),
  CountryLocalization("gu", "अङ्ग्रेजी", "गुवाम"),
  CountryLocalization("gt", "स्पेनी", "ग्वाटेमाला"),
  CountryLocalization("gg", "अङ्ग्रेजी", "गुएर्नसे"),
  CountryLocalization("gn", "फ्रान्सेली", "गिनी"),
  CountryLocalization("gw", "पोर्तुगी", "गिनी-बिसाउ"),
  CountryLocalization("gy", "अङ्ग्रेजी", "गुयाना"),
  CountryLocalization("ht", "फ्रान्सेली", "हैटी"),
  CountryLocalization("hn", "स्पेनी", "हन्डुरास"),
  CountryLocalization("hk", "चिनियाँ", "हङकङ चिनियाँ समाजबादी स्वायत्त क्षेत्र"),
  CountryLocalization("hu", "हङ्गेरियाली", "हङ्गेरी"),
  CountryLocalization("is", "आइसल्यान्डियाली", "आइस्ल्याण्ड"),
  CountryLocalization("in", "नेपाली", "भारत"),
  CountryLocalization("id", "Indonesian", "इन्डोनेशिया"),
  CountryLocalization("ir", "फारसी", "इरान"),
  CountryLocalization("iq", "उत्तरी लुरी", "इराक"),
  CountryLocalization("ie", "अङ्ग्रेजी", "आयरल्याण्ड"),
  CountryLocalization("im", "मान्क्स", "आइल अफ म्यान"),
  CountryLocalization("il", "अङ्ग्रेजी", "इजरायल"),
  CountryLocalization("it", "जर्मन", "इटाली"),
  CountryLocalization("jm", "अङ्ग्रेजी", "जमाइका"),
  CountryLocalization("jp", "जापानी", "जापान"),
  CountryLocalization("je", "अङ्ग्रेजी", "जर्सी"),
  CountryLocalization("jo", "अरबी", "जोर्डन"),
  CountryLocalization("kz", "काजाख", "काजाकस्तान"),
  CountryLocalization("ke", "सोमाली", "केन्या"),
  CountryLocalization("ki", "अङ्ग्रेजी", "किरिबाटी"),
  CountryLocalization("xk", "सर्बियाली", "कोसोभो"),
  CountryLocalization("kw", "अरबी", "कुवेत"),
  CountryLocalization("kg", "रसियाली", "किर्गिस्तान"),
  CountryLocalization("la", "लाओ", "लाओस"),
  CountryLocalization("lv", "लात्भियाली", "लाट्भिया"),
  CountryLocalization("lb", "अरबी", "लेबनन"),
  CountryLocalization("ls", "अङ्ग्रेजी", "लेसोथो"),
  CountryLocalization("lr", "अङ्ग्रेजी", "लाइबेरिया"),
  CountryLocalization("ly", "अरबी", "लिबिया"),
  CountryLocalization("li", "स्वीस जर्मन", "लिएखटेन्स्टाइन"),
  CountryLocalization("lt", "लिथुआनियाली", "लिथुएनिया"),
  CountryLocalization("lu", "लक्जेम्बर्गी", "लक्जेमबर्ग"),
  CountryLocalization("mo", "पोर्तुगी", "मकाउ चिनियाँ स्वशासित क्षेत्र"),
  CountryLocalization("mk", "अल्बानियाली", "म्यासेडोनिया"),
  CountryLocalization("mg", "फ्रान्सेली", "माडागास्कर"),
  CountryLocalization("mw", "अङ्ग्रेजी", "मालावी"),
  CountryLocalization("my", "तामिल", "मलेसिया"),
  CountryLocalization("ml", "फ्रान्सेली", "माली"),
  CountryLocalization("mt", "अङ्ग्रेजी", "माल्टा"),
  CountryLocalization("mh", "अङ्ग्रेजी", "मार्शल टापुहरु"),
  CountryLocalization("mq", "फ्रान्सेली", "मार्टिनिक"),
  CountryLocalization("mr", "अरबी", "माउरिटानिया"),
  CountryLocalization("mu", "मोरिसेन", "माउरिटस"),
  CountryLocalization("yt", "फ्रान्सेली", "मायोट्ट"),
  CountryLocalization("mx", "स्पेनी", "मेक्सिको"),
  CountryLocalization("fm", "अङ्ग्रेजी", "माइक्रोनेसिया"),
  CountryLocalization("md", "रसियाली", "माल्डोभा"),
  CountryLocalization("mc", "फ्रान्सेली", "मोनाको"),
  CountryLocalization("mn", "मङ्गोलियाली", "मङ्गोलिया"),
  CountryLocalization("me", "सर्बियाली", "मोन्टेनेग्रो"),
  CountryLocalization("ms", "अङ्ग्रेजी", "मोन्टसेर्राट"),
  CountryLocalization("ma", "केन्द्रीय एट्लास टामाजिघट", "मोरोक्को"),
  CountryLocalization("mz", "माखुवा-मिट्टो", "मोजाम्बिक"),
  CountryLocalization("mm", "बर्मेली", "म्यान्मार (बर्मा)"),
  CountryLocalization("na", "अङ्ग्रेजी", "नामिबिया"),
  CountryLocalization("nr", "अङ्ग्रेजी", "नाउरू"),
  CountryLocalization("np", "नेपाली", "नेपाल"),
  CountryLocalization("nl", "अङ्ग्रेजी", "नेदरल्याण्ड"),
  CountryLocalization("nc", "फ्रान्सेली", "न्यु क्यालेडोनिया"),
  CountryLocalization("nz", "अङ्ग्रेजी", "न्युजिल्याण्ड"),
  CountryLocalization("ni", "स्पेनी", "निकारागुवा"),
  CountryLocalization("ne", "हाउसा", "नाइजर"),
  CountryLocalization("ng", "हाउसा", "नाइजेरिया"),
  CountryLocalization("nu", "अङ्ग्रेजी", "नियुइ"),
  CountryLocalization("nf", "अङ्ग्रेजी", "नोरफोल्क टापु"),
  CountryLocalization("kp", "कोरियाली", "उत्तर कोरिया"),
  CountryLocalization("mp", "अङ्ग्रेजी", "उत्तरी मारिआना टापु"),
  CountryLocalization("no", "उत्तरी सामी", "नर्वे"),
  CountryLocalization("om", "अरबी", "ओमन"),
  CountryLocalization("pk", "अङ्ग्रेजी", "पाकिस्तान"),
  CountryLocalization("pw", "अङ्ग्रेजी", "पलाउ"),
  CountryLocalization("ps", "अरबी", "प्यालेस्टनी भू-भागहरु"),
  CountryLocalization("pa", "स्पेनी", "प्यानामा"),
  CountryLocalization("pg", "अङ्ग्रेजी", "पपुआ न्यू गाइनिया"),
  CountryLocalization("py", "स्पेनी", "प्याराग्वे"),
  CountryLocalization("pe", "स्पेनी", "पेरू"),
  CountryLocalization("ph", "फिलिपिनी", "फिलिपिन्स"),
  CountryLocalization("pn", "अङ्ग्रेजी", "पिटकाइर्न टापुहरु"),
  CountryLocalization("pl", "पोलिस", "पोल्याण्ड"),
  CountryLocalization("pt", "पोर्तुगी", "पोर्चुगल"),
  CountryLocalization("pr", "अङ्ग्रेजी", "पुएर्टो रिको"),
  CountryLocalization("qa", "अरबी", "कतार"),
  CountryLocalization("ro", "रोमानियाली", "रोमेनिया"),
  CountryLocalization("ru", "तातार", "रूस"),
  CountryLocalization("rw", "अङ्ग्रेजी", "रवाण्डा"),
  CountryLocalization("re", "फ्रान्सेली", "रियुनियन"),
  CountryLocalization("ws", "अङ्ग्रेजी", "सामोआ"),
  CountryLocalization("sm", "इटालेली", "सान् मारिनो"),
  CountryLocalization("sa", "अरबी", "साउदी अरब"),
  CountryLocalization("sn", "फ्रान्सेली", "सेनेगल"),
  CountryLocalization("rs", "सर्बियाली", "सर्बिया"),
  CountryLocalization("cs", "सर्बियाली", "Serbia and Montenegro"),
  CountryLocalization("sc", "फ्रान्सेली", "सेचेलेस"),
  CountryLocalization("sl", "अङ्ग्रेजी", "सिएर्रा लिओन"),
  CountryLocalization("sg", "तामिल", "सिङ्गापुर"),
  CountryLocalization("sx", "अङ्ग्रेजी", "सिन्ट मार्टेन"),
  CountryLocalization("sk", "स्लोभाकियाली", "स्लोभाकिया"),
  CountryLocalization("si", "स्लोभेनियाली", "स्लोभेनिया"),
  CountryLocalization("sb", "अङ्ग्रेजी", "सोलोमोन टापुहरु"),
  CountryLocalization("so", "अरबी", "सोमालिया"),
  CountryLocalization("za", "अङ्ग्रेजी", "दक्षिण अफ्रिका"),
  CountryLocalization("kr", "कोरियाली", "दक्षिण कोरिया"),
  CountryLocalization("ss", "नुएर", "दक्षिणी सुडान"),
  CountryLocalization("es", "स्पेनी", "स्पेन"),
  CountryLocalization("lk", "तामिल", "श्रीलङ्का"),
  CountryLocalization("bl", "फ्रान्सेली", "सेन्ट बार्थालेमी"),
  CountryLocalization("sh", "अङ्ग्रेजी", "सेन्ट हेलेना"),
  CountryLocalization("kn", "अङ्ग्रेजी", "सेन्ट किट्स र नेभिस"),
  CountryLocalization("lc", "अङ्ग्रेजी", "सेन्ट लुसिया"),
  CountryLocalization("mf", "फ्रान्सेली", "सेन्ट मार्टिन"),
  CountryLocalization("pm", "फ्रान्सेली", "सेन्ट पिर्रे र मिक्केलोन"),
  CountryLocalization("vc", "अङ्ग्रेजी", "सेन्ट भिन्सेन्ट र ग्रेनाडिन्स"),
  CountryLocalization("sd", "अरबी", "सुडान"),
  CountryLocalization("sr", "डच", "सुरिनेम"),
  CountryLocalization("sj", "नर्वेली बोकमाल", "सभाल्बार्ड र जान मायेन"),
  CountryLocalization("sz", "अङ्ग्रेजी", "स्वाजिल्याण्ड"),
  CountryLocalization("se", "स्विडिस", "स्विडेन"),
  CountryLocalization("ch", "स्वीस जर्मन", "स्विजरल्याण्ड"),
  CountryLocalization("sy", "अरबी", "सिरिया"),
  CountryLocalization("st", "पोर्तुगी", "साओ टोमे र प्रिन्सिप"),
  CountryLocalization("tw", "चिनियाँ", "ताइवान"),
  CountryLocalization("tj", "ताजिक", "ताजिकिस्तान"),
  CountryLocalization("tz", "माकोन्डे", "तान्जानिया"),
  CountryLocalization("th", "थाई", "थाइल्याण्ड"),
  CountryLocalization("tl", "पोर्तुगी", "टिमोर-लेस्टे"),
  CountryLocalization("tg", "फ्रान्सेली", "टोगो"),
  CountryLocalization("tk", "अङ्ग्रेजी", "तोकेलाउ"),
  CountryLocalization("to", "टोङ्गन", "टोंगा"),
  CountryLocalization("tt", "अङ्ग्रेजी", "त्रिनिडाड एण्ड टोबागो"),
  CountryLocalization("tn", "फ्रान्सेली", "ट्युनिसिया"),
  CountryLocalization("tr", "टर्किश", "टर्की"),
  CountryLocalization("tm", "टर्कमेन", "तुर्कमेनिस्तान"),
  CountryLocalization("tc", "अङ्ग्रेजी", "तुर्क र काइकोस टापु"),
  CountryLocalization("tv", "अङ्ग्रेजी", "तुभालु"),
  CountryLocalization("um", "अङ्ग्रेजी", "संयुक्त राज्यका बाह्य टापुहरु"),
  CountryLocalization("vi", "अङ्ग्रेजी", "संयुक्त राज्य भर्जिन टापुहरु"),
  CountryLocalization("ug", "स्वाहिली", "युगाण्डा"),
  CountryLocalization("ua", "युक्रेनी", "युक्रेन"),
  CountryLocalization("ae", "अरबी", "संयुक्त अरब इमिराट्स"),
  CountryLocalization("gb", "अङ्ग्रेजी", "बेलायत"),
  CountryLocalization("us", "लाकोता", "संयुक्त राज्य"),
  CountryLocalization("uy", "स्पेनी", "उरूग्वे"),
  CountryLocalization("uz", "उज्बेकी", "उज्बेकिस्तान"),
  CountryLocalization("vu", "फ्रान्सेली", "भानुआतु"),
  CountryLocalization("va", "इटालेली", "भेटिकन सिटी"),
  CountryLocalization("ve", "स्पेनी", "भेनेजुएला"),
  CountryLocalization("vn", "भियतनामी", "भिएतनाम"),
  CountryLocalization("wf", "फ्रान्सेली", "वालिस र फुटुना"),
  CountryLocalization("eh", "अरबी", "पश्चिमी साहारा"),
  CountryLocalization("ye", "अरबी", "येमेन"),
  CountryLocalization("zm", "अङ्ग्रेजी", "जाम्बिया"),
  CountryLocalization("zw", "उत्तरी न्डेबेले", "जिम्बाबे"),
  CountryLocalization("ax", "स्विडिस", "अलान्ड टापुहरु"),
)
