/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot.atlas.extended

import dev.teogor.xenoglot.atlas.CountryLocalization
import kotlin.collections.List

/**
 * Holds the internal list of country-language mappings used for lookups within the package for
 * language code pt.
 *
 * This property contains a hardcoded list of [CountryLocalization] objects, each representing
 * a country and its associated official languages. This list is used by [CountryLanguageRegistry]
 * to provide access to country-language data and should not be modified directly.
 *
 * @see CountryLocalization
 * @see CountryLanguageRegistry
 */
internal val _countryLanguageMappings_pt: List<CountryLocalization> = listOf(
  CountryLocalization("af", "persa", "Afeganistão"),
  CountryLocalization("al", "albanês", "Albânia"),
  CountryLocalization("dz", "francês", "Argélia"),
  CountryLocalization("as", "inglês", "Samoa Americana"),
  CountryLocalization("ad", "catalão", "Andorra"),
  CountryLocalization("ao", "lingala", "Angola"),
  CountryLocalization("ai", "inglês", "Anguilla"),
  CountryLocalization("ag", "inglês", "Antígua e Barbuda"),
  CountryLocalization("ar", "espanhol", "Argentina"),
  CountryLocalization("am", "armênio", "Armênia"),
  CountryLocalization("aw", "holandês", "Aruba"),
  CountryLocalization("au", "inglês", "Austrália"),
  CountryLocalization("at", "inglês", "Áustria"),
  CountryLocalization("az", "azerbaijano", "Azerbaijão"),
  CountryLocalization("bs", "inglês", "Bahamas"),
  CountryLocalization("bh", "árabe", "Bahrein"),
  CountryLocalization("bd", "bengali", "Bangladesh"),
  CountryLocalization("bb", "inglês", "Barbados"),
  CountryLocalization("by", "bielorrusso", "Bielorrússia"),
  CountryLocalization("be", "francês", "Bélgica"),
  CountryLocalization("bz", "inglês", "Belize"),
  CountryLocalization("bj", "francês", "Benin"),
  CountryLocalization("bm", "inglês", "Bermudas"),
  CountryLocalization("bt", "dzonga", "Butão"),
  CountryLocalization("bo", "espanhol", "Bolívia"),
  CountryLocalization("ba", "bósnio", "Bósnia e Herzegovina"),
  CountryLocalization("bw", "inglês", "Botsuana"),
  CountryLocalization("br", "português", "Brasil"),
  CountryLocalization("io", "inglês", "Território Britânico do Oceano Índico"),
  CountryLocalization("vg", "inglês", "Ilhas Virgens Britânicas"),
  CountryLocalization("bn", "malaio", "Brunei"),
  CountryLocalization("bg", "búlgaro", "Bulgária"),
  CountryLocalization("bf", "francês", "Burquina Faso"),
  CountryLocalization("bi", "francês", "Burundi"),
  CountryLocalization("kh", "khmer", "Camboja"),
  CountryLocalization("cm", "basa", "Camarões"),
  CountryLocalization("ca", "francês", "Canadá"),
  CountryLocalization("ic", "espanhol", "Ilhas Canárias"),
  CountryLocalization("cv", "kabuverdianu", "Cabo Verde"),
  CountryLocalization("bq", "holandês", "Países Baixos Caribenhos"),
  CountryLocalization("ky", "inglês", "Ilhas Cayman"),
  CountryLocalization("cf", "lingala", "República Centro-Africana"),
  CountryLocalization("ea", "espanhol", "Ceuta e Melilha"),
  CountryLocalization("td", "árabe", "Chade"),
  CountryLocalization("cl", "espanhol", "Chile"),
  CountryLocalization("cn", "tibetano", "China"),
  CountryLocalization("cx", "inglês", "Ilha Christmas"),
  CountryLocalization("cc", "inglês", "Ilhas Cocos (Keeling)"),
  CountryLocalization("co", "espanhol", "Colômbia"),
  CountryLocalization("km", "árabe", "Comores"),
  CountryLocalization("cg", "lingala", "Congo - Brazzaville"),
  CountryLocalization("cd", "suaíli", "Congo - Kinshasa"),
  CountryLocalization("ck", "inglês", "Ilhas Cook"),
  CountryLocalization("cr", "espanhol", "Costa Rica"),
  CountryLocalization("hr", "croata", "Croácia"),
  CountryLocalization("cu", "espanhol", "Cuba"),
  CountryLocalization("cw", "holandês", "Curaçao"),
  CountryLocalization("cy", "inglês", "Chipre"),
  CountryLocalization("cz", "tcheco", "Tchéquia"),
  CountryLocalization("ci", "francês", "Costa do Marfim"),
  CountryLocalization("dk", "inglês", "Dinamarca"),
  CountryLocalization("dg", "inglês", "Diego Garcia"),
  CountryLocalization("dj", "francês", "Djibuti"),
  CountryLocalization("dm", "inglês", "Dominica"),
  CountryLocalization("do", "espanhol", "República Dominicana"),
  CountryLocalization("ec", "quíchua", "Equador"),
  CountryLocalization("eg", "árabe", "Egito"),
  CountryLocalization("sv", "espanhol", "El Salvador"),
  CountryLocalization("gq", "espanhol", "Guiné Equatorial"),
  CountryLocalization("er", "tigrínia", "Eritreia"),
  CountryLocalization("ee", "estoniano", "Estônia"),
  CountryLocalization("et", "amárico", "Etiópia"),
  CountryLocalization("fk", "inglês", "Ilhas Malvinas"),
  CountryLocalization("fo", "feroês", "Ilhas Faroe"),
  CountryLocalization("fj", "inglês", "Fiji"),
  CountryLocalization("fi", "sueco", "Finlândia"),
  CountryLocalization("fr", "alemão (Suíça)", "França"),
  CountryLocalization("gf", "francês", "Guiana Francesa"),
  CountryLocalization("pf", "francês", "Polinésia Francesa"),
  CountryLocalization("ga", "francês", "Gabão"),
  CountryLocalization("gm", "inglês", "Gâmbia"),
  CountryLocalization("ge", "osseto", "Geórgia"),
  CountryLocalization("de", "baixo sorábio", "Alemanha"),
  CountryLocalization("gh", "inglês", "Gana"),
  CountryLocalization("gi", "inglês", "Gibraltar"),
  CountryLocalization("gr", "grego", "Grécia"),
  CountryLocalization("gl", "groenlandês", "Groenlândia"),
  CountryLocalization("gd", "inglês", "Granada"),
  CountryLocalization("gp", "francês", "Guadalupe"),
  CountryLocalization("gu", "inglês", "Guam"),
  CountryLocalization("gt", "espanhol", "Guatemala"),
  CountryLocalization("gg", "inglês", "Guernsey"),
  CountryLocalization("gn", "francês", "Guiné"),
  CountryLocalization("gw", "português", "Guiné-Bissau"),
  CountryLocalization("gy", "inglês", "Guiana"),
  CountryLocalization("ht", "francês", "Haiti"),
  CountryLocalization("hn", "espanhol", "Honduras"),
  CountryLocalization("hk", "chinês", "Hong Kong, RAE da China"),
  CountryLocalization("hu", "húngaro", "Hungria"),
  CountryLocalization("is", "islandês", "Islândia"),
  CountryLocalization("in", "nepalês", "Índia"),
  CountryLocalization("id", "indonésio", "Indonésia"),
  CountryLocalization("ir", "persa", "Irã"),
  CountryLocalization("iq", "luri setentrional", "Iraque"),
  CountryLocalization("ie", "inglês", "Irlanda"),
  CountryLocalization("im", "manx", "Ilha de Man"),
  CountryLocalization("il", "inglês", "Israel"),
  CountryLocalization("it", "alemão", "Itália"),
  CountryLocalization("jm", "inglês", "Jamaica"),
  CountryLocalization("jp", "japonês", "Japão"),
  CountryLocalization("je", "inglês", "Jersey"),
  CountryLocalization("jo", "árabe", "Jordânia"),
  CountryLocalization("kz", "cazaque", "Cazaquistão"),
  CountryLocalization("ke", "somali", "Quênia"),
  CountryLocalization("ki", "inglês", "Quiribati"),
  CountryLocalization("xk", "sérvio", "Kosovo"),
  CountryLocalization("kw", "árabe", "Kuwait"),
  CountryLocalization("kg", "russo", "Quirguistão"),
  CountryLocalization("la", "laosiano", "Laos"),
  CountryLocalization("lv", "letão", "Letônia"),
  CountryLocalization("lb", "árabe", "Líbano"),
  CountryLocalization("ls", "inglês", "Lesoto"),
  CountryLocalization("lr", "inglês", "Libéria"),
  CountryLocalization("ly", "árabe", "Líbia"),
  CountryLocalization("li", "alemão (Suíça)", "Liechtenstein"),
  CountryLocalization("lt", "lituano", "Lituânia"),
  CountryLocalization("lu", "luxemburguês", "Luxemburgo"),
  CountryLocalization("mo", "português", "Macau, RAE da China"),
  CountryLocalization("mk", "albanês", "Macedônia"),
  CountryLocalization("mg", "francês", "Madagascar"),
  CountryLocalization("mw", "inglês", "Malaui"),
  CountryLocalization("my", "tâmil", "Malásia"),
  CountryLocalization("ml", "francês", "Mali"),
  CountryLocalization("mt", "inglês", "Malta"),
  CountryLocalization("mh", "inglês", "Ilhas Marshall"),
  CountryLocalization("mq", "francês", "Martinica"),
  CountryLocalization("mr", "árabe", "Mauritânia"),
  CountryLocalization("mu", "morisyen", "Maurício"),
  CountryLocalization("yt", "francês", "Mayotte"),
  CountryLocalization("mx", "espanhol", "México"),
  CountryLocalization("fm", "inglês", "Micronésia"),
  CountryLocalization("md", "russo", "Moldávia"),
  CountryLocalization("mc", "francês", "Mônaco"),
  CountryLocalization("mn", "mongol", "Mongólia"),
  CountryLocalization("me", "sérvio", "Montenegro"),
  CountryLocalization("ms", "inglês", "Montserrat"),
  CountryLocalization("ma", "tamazirte do Atlas Central", "Marrocos"),
  CountryLocalization("mz", "macua", "Moçambique"),
  CountryLocalization("mm", "birmanês", "Mianmar (Birmânia)"),
  CountryLocalization("na", "inglês", "Namíbia"),
  CountryLocalization("nr", "inglês", "Nauru"),
  CountryLocalization("np", "nepalês", "Nepal"),
  CountryLocalization("nl", "inglês", "Holanda"),
  CountryLocalization("nc", "francês", "Nova Caledônia"),
  CountryLocalization("nz", "inglês", "Nova Zelândia"),
  CountryLocalization("ni", "espanhol", "Nicarágua"),
  CountryLocalization("ne", "hauçá", "Níger"),
  CountryLocalization("ng", "hauçá", "Nigéria"),
  CountryLocalization("nu", "inglês", "Niue"),
  CountryLocalization("nf", "inglês", "Ilha Norfolk"),
  CountryLocalization("kp", "coreano", "Coreia do Norte"),
  CountryLocalization("mp", "inglês", "Ilhas Marianas do Norte"),
  CountryLocalization("no", "sami setentrional", "Noruega"),
  CountryLocalization("om", "árabe", "Omã"),
  CountryLocalization("pk", "inglês", "Paquistão"),
  CountryLocalization("pw", "inglês", "Palau"),
  CountryLocalization("ps", "árabe", "Territórios palestinos"),
  CountryLocalization("pa", "espanhol", "Panamá"),
  CountryLocalization("pg", "inglês", "Papua-Nova Guiné"),
  CountryLocalization("py", "espanhol", "Paraguai"),
  CountryLocalization("pe", "espanhol", "Peru"),
  CountryLocalization("ph", "filipino", "Filipinas"),
  CountryLocalization("pn", "inglês", "Ilhas Pitcairn"),
  CountryLocalization("pl", "polonês", "Polônia"),
  CountryLocalization("pt", "português", "Portugal"),
  CountryLocalization("pr", "inglês", "Porto Rico"),
  CountryLocalization("qa", "árabe", "Catar"),
  CountryLocalization("ro", "romeno", "Romênia"),
  CountryLocalization("ru", "tártaro", "Rússia"),
  CountryLocalization("rw", "inglês", "Ruanda"),
  CountryLocalization("re", "francês", "Reunião"),
  CountryLocalization("ws", "inglês", "Samoa"),
  CountryLocalization("sm", "italiano", "San Marino"),
  CountryLocalization("sa", "árabe", "Arábia Saudita"),
  CountryLocalization("sn", "francês", "Senegal"),
  CountryLocalization("rs", "sérvio", "Sérvia"),
  CountryLocalization("cs", "sérvio", "Sérvia e Montenegro"),
  CountryLocalization("sc", "francês", "Seicheles"),
  CountryLocalization("sl", "inglês", "Serra Leoa"),
  CountryLocalization("sg", "tâmil", "Singapura"),
  CountryLocalization("sx", "inglês", "Sint Maarten"),
  CountryLocalization("sk", "eslovaco", "Eslováquia"),
  CountryLocalization("si", "esloveno", "Eslovênia"),
  CountryLocalization("sb", "inglês", "Ilhas Salomão"),
  CountryLocalization("so", "árabe", "Somália"),
  CountryLocalization("za", "inglês", "África do Sul"),
  CountryLocalization("kr", "coreano", "Coreia do Sul"),
  CountryLocalization("ss", "nuer", "Sudão do Sul"),
  CountryLocalization("es", "espanhol", "Espanha"),
  CountryLocalization("lk", "tâmil", "Sri Lanka"),
  CountryLocalization("bl", "francês", "São Bartolomeu"),
  CountryLocalization("sh", "inglês", "Santa Helena"),
  CountryLocalization("kn", "inglês", "São Cristóvão e Névis"),
  CountryLocalization("lc", "inglês", "Santa Lúcia"),
  CountryLocalization("mf", "francês", "São Martinho"),
  CountryLocalization("pm", "francês", "São Pedro e Miquelão"),
  CountryLocalization("vc", "inglês", "São Vicente e Granadinas"),
  CountryLocalization("sd", "árabe", "Sudão"),
  CountryLocalization("sr", "holandês", "Suriname"),
  CountryLocalization("sj", "bokmål norueguês", "Svalbard e Jan Mayen"),
  CountryLocalization("sz", "inglês", "Suazilândia"),
  CountryLocalization("se", "sueco", "Suécia"),
  CountryLocalization("ch", "alemão (Suíça)", "Suíça"),
  CountryLocalization("sy", "árabe", "Síria"),
  CountryLocalization("st", "português", "São Tomé e Príncipe"),
  CountryLocalization("tw", "chinês", "Taiwan"),
  CountryLocalization("tj", "tadjique", "Tadjiquistão"),
  CountryLocalization("tz", "maconde", "Tanzânia"),
  CountryLocalization("th", "tailandês", "Tailândia"),
  CountryLocalization("tl", "português", "Timor-Leste"),
  CountryLocalization("tg", "francês", "Togo"),
  CountryLocalization("tk", "inglês", "Tokelau"),
  CountryLocalization("to", "tonganês", "Tonga"),
  CountryLocalization("tt", "inglês", "Trinidad e Tobago"),
  CountryLocalization("tn", "francês", "Tunísia"),
  CountryLocalization("tr", "turco", "Turquia"),
  CountryLocalization("tm", "turcomeno", "Turcomenistão"),
  CountryLocalization("tc", "inglês", "Ilhas Turks e Caicos"),
  CountryLocalization("tv", "inglês", "Tuvalu"),
  CountryLocalization("um", "inglês", "Ilhas Menores Distantes dos EUA"),
  CountryLocalization("vi", "inglês", "Ilhas Virgens Americanas"),
  CountryLocalization("ug", "suaíli", "Uganda"),
  CountryLocalization("ua", "ucraniano", "Ucrânia"),
  CountryLocalization("ae", "árabe", "Emirados Árabes Unidos"),
  CountryLocalization("gb", "inglês", "Reino Unido"),
  CountryLocalization("us", "lacota", "Estados Unidos"),
  CountryLocalization("uy", "espanhol", "Uruguai"),
  CountryLocalization("uz", "uzbeque", "Uzbequistão"),
  CountryLocalization("vu", "francês", "Vanuatu"),
  CountryLocalization("va", "italiano", "Cidade do Vaticano"),
  CountryLocalization("ve", "espanhol", "Venezuela"),
  CountryLocalization("vn", "vietnamita", "Vietnã"),
  CountryLocalization("wf", "francês", "Wallis e Futuna"),
  CountryLocalization("eh", "árabe", "Saara Ocidental"),
  CountryLocalization("ye", "árabe", "Iêmen"),
  CountryLocalization("zm", "inglês", "Zâmbia"),
  CountryLocalization("zw", "ndebele do norte", "Zimbábue"),
  CountryLocalization("ax", "sueco", "Ilhas Aland"),
)
