/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot.atlas.extended

import dev.teogor.xenoglot.atlas.CountryLocalization
import kotlin.collections.List

/**
 * Holds the internal list of country-language mappings used for lookups within the package for
 * language code hr.
 *
 * This property contains a hardcoded list of [CountryLocalization] objects, each representing
 * a country and its associated official languages. This list is used by [CountryLanguageRegistry]
 * to provide access to country-language data and should not be modified directly.
 *
 * @see CountryLocalization
 * @see CountryLanguageRegistry
 */
internal val _countryLanguageMappings_hr: List<CountryLocalization> = listOf(
  CountryLocalization("af", "perzijski", "Afganistan"),
  CountryLocalization("al", "albanski", "Albanija"),
  CountryLocalization("dz", "francuski", "Alžir"),
  CountryLocalization("as", "engleski", "Američka Samoa"),
  CountryLocalization("ad", "katalonski", "Andora"),
  CountryLocalization("ao", "lingala", "Angola"),
  CountryLocalization("ai", "engleski", "Angvila"),
  CountryLocalization("ag", "engleski", "Antigva i Barbuda"),
  CountryLocalization("ar", "španjolski", "Argentina"),
  CountryLocalization("am", "armenski", "Armenija"),
  CountryLocalization("aw", "nizozemski", "Aruba"),
  CountryLocalization("au", "engleski", "Australija"),
  CountryLocalization("at", "engleski", "Austrija"),
  CountryLocalization("az", "azerbajdžanski", "Azerbajdžan"),
  CountryLocalization("bs", "engleski", "Bahami"),
  CountryLocalization("bh", "arapski", "Bahrein"),
  CountryLocalization("bd", "bangla", "Bangladeš"),
  CountryLocalization("bb", "engleski", "Barbados"),
  CountryLocalization("by", "bjeloruski", "Bjelorusija"),
  CountryLocalization("be", "francuski", "Belgija"),
  CountryLocalization("bz", "engleski", "Belize"),
  CountryLocalization("bj", "francuski", "Benin"),
  CountryLocalization("bm", "engleski", "Bermudi"),
  CountryLocalization("bt", "dzongkha", "Butan"),
  CountryLocalization("bo", "španjolski", "Bolivija"),
  CountryLocalization("ba", "bosanski", "Bosna i Hercegovina"),
  CountryLocalization("bw", "engleski", "Bocvana"),
  CountryLocalization("br", "portugalski", "Brazil"),
  CountryLocalization("io", "engleski", "Britanski Indijskooceanski teritorij"),
  CountryLocalization("vg", "engleski", "Britanski Djevičanski otoci"),
  CountryLocalization("bn", "malajski", "Brunej"),
  CountryLocalization("bg", "bugarski", "Bugarska"),
  CountryLocalization("bf", "francuski", "Burkina Faso"),
  CountryLocalization("bi", "francuski", "Burundi"),
  CountryLocalization("kh", "kmerski", "Kambodža"),
  CountryLocalization("cm", "basa", "Kamerun"),
  CountryLocalization("ca", "francuski", "Kanada"),
  CountryLocalization("ic", "španjolski", "Kanarski otoci"),
  CountryLocalization("cv", "zelenortski", "Zelenortska Republika"),
  CountryLocalization("bq", "nizozemski", "Karipski otoci Nizozemske"),
  CountryLocalization("ky", "engleski", "Kajmanski otoci"),
  CountryLocalization("cf", "lingala", "Srednjoafrička Republika"),
  CountryLocalization("ea", "španjolski", "Ceuta i Melilla"),
  CountryLocalization("td", "arapski", "Čad"),
  CountryLocalization("cl", "španjolski", "Čile"),
  CountryLocalization("cn", "tibetski", "Kina"),
  CountryLocalization("cx", "engleski", "Božićni otok"),
  CountryLocalization("cc", "engleski", "Kokosovi (Keelingovi) otoci"),
  CountryLocalization("co", "španjolski", "Kolumbija"),
  CountryLocalization("km", "arapski", "Komori"),
  CountryLocalization("cg", "lingala", "Kongo - Brazzaville"),
  CountryLocalization("cd", "svahili", "Kongo - Kinshasa"),
  CountryLocalization("ck", "engleski", "Cookovi Otoci"),
  CountryLocalization("cr", "španjolski", "Kostarika"),
  CountryLocalization("hr", "hrvatski", "Hrvatska"),
  CountryLocalization("cu", "španjolski", "Kuba"),
  CountryLocalization("cw", "nizozemski", "Curaçao"),
  CountryLocalization("cy", "engleski", "Cipar"),
  CountryLocalization("cz", "češki", "Češka"),
  CountryLocalization("ci", "francuski", "Obala Bjelokosti"),
  CountryLocalization("dk", "engleski", "Danska"),
  CountryLocalization("dg", "engleski", "Diego Garcia"),
  CountryLocalization("dj", "francuski", "Džibuti"),
  CountryLocalization("dm", "engleski", "Dominika"),
  CountryLocalization("do", "španjolski", "Dominikanska Republika"),
  CountryLocalization("ec", "kečuanski", "Ekvador"),
  CountryLocalization("eg", "arapski", "Egipat"),
  CountryLocalization("sv", "španjolski", "Salvador"),
  CountryLocalization("gq", "španjolski", "Ekvatorska Gvineja"),
  CountryLocalization("er", "tigrinja", "Eritreja"),
  CountryLocalization("ee", "estonski", "Estonija"),
  CountryLocalization("et", "amharski", "Etiopija"),
  CountryLocalization("fk", "engleski", "Falklandski otoci"),
  CountryLocalization("fo", "ferojski", "Farski otoci"),
  CountryLocalization("fj", "engleski", "Fidži"),
  CountryLocalization("fi", "švedski", "Finska"),
  CountryLocalization("fr", "švicarski njemački", "Francuska"),
  CountryLocalization("gf", "francuski", "Francuska Gijana"),
  CountryLocalization("pf", "francuski", "Francuska Polinezija"),
  CountryLocalization("ga", "francuski", "Gabon"),
  CountryLocalization("gm", "engleski", "Gambija"),
  CountryLocalization("ge", "osetski", "Gruzija"),
  CountryLocalization("de", "donjolužički", "Njemačka"),
  CountryLocalization("gh", "engleski", "Gana"),
  CountryLocalization("gi", "engleski", "Gibraltar"),
  CountryLocalization("gr", "grčki", "Grčka"),
  CountryLocalization("gl", "kalaallisut", "Grenland"),
  CountryLocalization("gd", "engleski", "Grenada"),
  CountryLocalization("gp", "francuski", "Guadalupe"),
  CountryLocalization("gu", "engleski", "Guam"),
  CountryLocalization("gt", "španjolski", "Gvatemala"),
  CountryLocalization("gg", "engleski", "Guernsey"),
  CountryLocalization("gn", "francuski", "Gvineja"),
  CountryLocalization("gw", "portugalski", "Gvineja Bisau"),
  CountryLocalization("gy", "engleski", "Gvajana"),
  CountryLocalization("ht", "francuski", "Haiti"),
  CountryLocalization("hn", "španjolski", "Honduras"),
  CountryLocalization("hk", "kineski", "PUP Hong Kong Kina"),
  CountryLocalization("hu", "mađarski", "Mađarska"),
  CountryLocalization("is", "islandski", "Island"),
  CountryLocalization("in", "nepalski", "Indija"),
  CountryLocalization("id", "Indonesian", "Indonezija"),
  CountryLocalization("ir", "perzijski", "Iran"),
  CountryLocalization("iq", "sjevernolurski", "Irak"),
  CountryLocalization("ie", "engleski", "Irska"),
  CountryLocalization("im", "manski", "Otok Man"),
  CountryLocalization("il", "engleski", "Izrael"),
  CountryLocalization("it", "njemački", "Italija"),
  CountryLocalization("jm", "engleski", "Jamajka"),
  CountryLocalization("jp", "japanski", "Japan"),
  CountryLocalization("je", "engleski", "Jersey"),
  CountryLocalization("jo", "arapski", "Jordan"),
  CountryLocalization("kz", "kazaški", "Kazahstan"),
  CountryLocalization("ke", "somalski", "Kenija"),
  CountryLocalization("ki", "engleski", "Kiribati"),
  CountryLocalization("xk", "srpski", "Kosovo"),
  CountryLocalization("kw", "arapski", "Kuvajt"),
  CountryLocalization("kg", "ruski", "Kirgistan"),
  CountryLocalization("la", "laoski", "Laos"),
  CountryLocalization("lv", "latvijski", "Latvija"),
  CountryLocalization("lb", "arapski", "Libanon"),
  CountryLocalization("ls", "engleski", "Lesoto"),
  CountryLocalization("lr", "engleski", "Liberija"),
  CountryLocalization("ly", "arapski", "Libija"),
  CountryLocalization("li", "švicarski njemački", "Lihtenštajn"),
  CountryLocalization("lt", "litavski", "Litva"),
  CountryLocalization("lu", "luksemburški", "Luksemburg"),
  CountryLocalization("mo", "portugalski", "PUP Makao Kina"),
  CountryLocalization("mk", "albanski", "Makedonija"),
  CountryLocalization("mg", "francuski", "Madagaskar"),
  CountryLocalization("mw", "engleski", "Malavi"),
  CountryLocalization("my", "tamilski", "Malezija"),
  CountryLocalization("ml", "francuski", "Mali"),
  CountryLocalization("mt", "engleski", "Malta"),
  CountryLocalization("mh", "engleski", "Maršalovi Otoci"),
  CountryLocalization("mq", "francuski", "Martinique"),
  CountryLocalization("mr", "arapski", "Mauretanija"),
  CountryLocalization("mu", "mauricijski kreolski", "Mauricijus"),
  CountryLocalization("yt", "francuski", "Mayotte"),
  CountryLocalization("mx", "španjolski", "Meksiko"),
  CountryLocalization("fm", "engleski", "Mikronezija"),
  CountryLocalization("md", "ruski", "Moldavija"),
  CountryLocalization("mc", "francuski", "Monako"),
  CountryLocalization("mn", "mongolski", "Mongolija"),
  CountryLocalization("me", "srpski", "Crna Gora"),
  CountryLocalization("ms", "engleski", "Montserrat"),
  CountryLocalization("ma", "tamašek (Srednji Atlas)", "Maroko"),
  CountryLocalization("mz", "makhuwa-meetto", "Mozambik"),
  CountryLocalization("mm", "burmanski", "Mjanmar (Burma)"),
  CountryLocalization("na", "engleski", "Namibija"),
  CountryLocalization("nr", "engleski", "Nauru"),
  CountryLocalization("np", "nepalski", "Nepal"),
  CountryLocalization("nl", "engleski", "Nizozemska"),
  CountryLocalization("nc", "francuski", "Nova Kaledonija"),
  CountryLocalization("nz", "engleski", "Novi Zeland"),
  CountryLocalization("ni", "španjolski", "Nikaragva"),
  CountryLocalization("ne", "hausa", "Niger"),
  CountryLocalization("ng", "hausa", "Nigerija"),
  CountryLocalization("nu", "engleski", "Niue"),
  CountryLocalization("nf", "engleski", "Otok Norfolk"),
  CountryLocalization("kp", "korejski", "Sjeverna Koreja"),
  CountryLocalization("mp", "engleski", "Sjevernomarijanski otoci"),
  CountryLocalization("no", "sjeverni sami", "Norveška"),
  CountryLocalization("om", "arapski", "Oman"),
  CountryLocalization("pk", "engleski", "Pakistan"),
  CountryLocalization("pw", "engleski", "Palau"),
  CountryLocalization("ps", "arapski", "Palestinsko područje"),
  CountryLocalization("pa", "španjolski", "Panama"),
  CountryLocalization("pg", "engleski", "Papua Nova Gvineja"),
  CountryLocalization("py", "španjolski", "Paragvaj"),
  CountryLocalization("pe", "španjolski", "Peru"),
  CountryLocalization("ph", "filipinski", "Filipini"),
  CountryLocalization("pn", "engleski", "Otoci Pitcairn"),
  CountryLocalization("pl", "poljski", "Poljska"),
  CountryLocalization("pt", "portugalski", "Portugal"),
  CountryLocalization("pr", "engleski", "Portoriko"),
  CountryLocalization("qa", "arapski", "Katar"),
  CountryLocalization("ro", "rumunjski", "Rumunjska"),
  CountryLocalization("ru", "tatarski", "Rusija"),
  CountryLocalization("rw", "engleski", "Ruanda"),
  CountryLocalization("re", "francuski", "Réunion"),
  CountryLocalization("ws", "engleski", "Samoa"),
  CountryLocalization("sm", "talijanski", "San Marino"),
  CountryLocalization("sa", "arapski", "Saudijska Arabija"),
  CountryLocalization("sn", "francuski", "Senegal"),
  CountryLocalization("rs", "srpski", "Srbija"),
  CountryLocalization("cs", "srpski", "Serbia and Montenegro"),
  CountryLocalization("sc", "francuski", "Sejšeli"),
  CountryLocalization("sl", "engleski", "Sijera Leone"),
  CountryLocalization("sg", "tamilski", "Singapur"),
  CountryLocalization("sx", "engleski", "Sint Maarten"),
  CountryLocalization("sk", "slovački", "Slovačka"),
  CountryLocalization("si", "slovenski", "Slovenija"),
  CountryLocalization("sb", "engleski", "Salomonski Otoci"),
  CountryLocalization("so", "arapski", "Somalija"),
  CountryLocalization("za", "engleski", "Južnoafrička Republika"),
  CountryLocalization("kr", "korejski", "Južna Koreja"),
  CountryLocalization("ss", "nuerski", "Južni Sudan"),
  CountryLocalization("es", "španjolski", "Španjolska"),
  CountryLocalization("lk", "tamilski", "Šri Lanka"),
  CountryLocalization("bl", "francuski", "Saint Barthélemy"),
  CountryLocalization("sh", "engleski", "Sveta Helena"),
  CountryLocalization("kn", "engleski", "Sveti Kristofor i Nevis"),
  CountryLocalization("lc", "engleski", "Sveta Lucija"),
  CountryLocalization("mf", "francuski", "Saint Martin"),
  CountryLocalization("pm", "francuski", "Sveti Petar i Mikelon"),
  CountryLocalization("vc", "engleski", "Sveti Vincent i Grenadini"),
  CountryLocalization("sd", "arapski", "Sudan"),
  CountryLocalization("sr", "nizozemski", "Surinam"),
  CountryLocalization("sj", "norveški bokmål", "Svalbard i Jan Mayen"),
  CountryLocalization("sz", "engleski", "Svazi"),
  CountryLocalization("se", "švedski", "Švedska"),
  CountryLocalization("ch", "švicarski njemački", "Švicarska"),
  CountryLocalization("sy", "arapski", "Sirija"),
  CountryLocalization("st", "portugalski", "Sveti Toma i Princip"),
  CountryLocalization("tw", "kineski", "Tajvan"),
  CountryLocalization("tj", "tadžički", "Tadžikistan"),
  CountryLocalization("tz", "makonde", "Tanzanija"),
  CountryLocalization("th", "tajlandski", "Tajland"),
  CountryLocalization("tl", "portugalski", "Timor-Leste"),
  CountryLocalization("tg", "francuski", "Togo"),
  CountryLocalization("tk", "engleski", "Tokelau"),
  CountryLocalization("to", "tonganski", "Tonga"),
  CountryLocalization("tt", "engleski", "Trinidad i Tobago"),
  CountryLocalization("tn", "francuski", "Tunis"),
  CountryLocalization("tr", "turski", "Turska"),
  CountryLocalization("tm", "turkmenski", "Turkmenistan"),
  CountryLocalization("tc", "engleski", "Otoci Turks i Caicos"),
  CountryLocalization("tv", "engleski", "Tuvalu"),
  CountryLocalization("um", "engleski", "Mali udaljeni otoci SAD-a"),
  CountryLocalization("vi", "engleski", "Američki Djevičanski otoci"),
  CountryLocalization("ug", "svahili", "Uganda"),
  CountryLocalization("ua", "ukrajinski", "Ukrajina"),
  CountryLocalization("ae", "arapski", "Ujedinjeni Arapski Emirati"),
  CountryLocalization("gb", "engleski", "Ujedinjeno Kraljevstvo"),
  CountryLocalization("us", "lakota", "Sjedinjene Američke Države"),
  CountryLocalization("uy", "španjolski", "Urugvaj"),
  CountryLocalization("uz", "uzbečki", "Uzbekistan"),
  CountryLocalization("vu", "francuski", "Vanuatu"),
  CountryLocalization("va", "talijanski", "Vatikanski Grad"),
  CountryLocalization("ve", "španjolski", "Venezuela"),
  CountryLocalization("vn", "vijetnamski", "Vijetnam"),
  CountryLocalization("wf", "francuski", "Wallis i Futuna"),
  CountryLocalization("eh", "arapski", "Zapadna Sahara"),
  CountryLocalization("ye", "arapski", "Jemen"),
  CountryLocalization("zm", "engleski", "Zambija"),
  CountryLocalization("zw", "sjeverni ndebele", "Zimbabve"),
  CountryLocalization("ax", "švedski", "Ålandski otoci"),
)
