/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot.atlas.extended

import dev.teogor.xenoglot.atlas.CountryLocalization
import kotlin.collections.List

/**
 * Holds the internal list of country-language mappings used for lookups within the package for
 * language code th.
 *
 * This property contains a hardcoded list of [CountryLocalization] objects, each representing
 * a country and its associated official languages. This list is used by [CountryLanguageRegistry]
 * to provide access to country-language data and should not be modified directly.
 *
 * @see CountryLocalization
 * @see CountryLanguageRegistry
 */
internal val _countryLanguageMappings_th: List<CountryLocalization> = listOf(
  CountryLocalization("af", "เปอร์เซีย", "อัฟกานิสถาน"),
  CountryLocalization("al", "แอลเบเนีย", "แอลเบเนีย"),
  CountryLocalization("dz", "ฝรั่งเศส", "แอลจีเรีย"),
  CountryLocalization("as", "อังกฤษ", "American Samoa"),
  CountryLocalization("ad", "แคตาแลน", "อันดอร์รา"),
  CountryLocalization("ao", "ลิงกาลา", "อันโกลา"),
  CountryLocalization("ai", "อังกฤษ", "อันกิล่า"),
  CountryLocalization("ag", "อังกฤษ", "Antigua & Barbuda"),
  CountryLocalization("ar", "สเปน", "อาร์เจนติน่า"),
  CountryLocalization("am", "อาร์มีเนีย", "อาร์มีเนีย"),
  CountryLocalization("aw", "ฮอลันดา", "อารูบา"),
  CountryLocalization("au", "อังกฤษ", "ออสเตรเลีย"),
  CountryLocalization("at", "อังกฤษ", "ออสเตรีย"),
  CountryLocalization("az", "อาเซอร์ไบจานี", "อาเซอร์ไบจัน"),
  CountryLocalization("bs", "อังกฤษ", "บาฮามาส"),
  CountryLocalization("bh", "อาระบิค", "บาห์เรน"),
  CountryLocalization("bd", "เบนการี", "บังคลาเทศ"),
  CountryLocalization("bb", "อังกฤษ", "บาร์บาดอส"),
  CountryLocalization("by", "บายโลรัสเซีย", "เบลลารัส"),
  CountryLocalization("be", "ฝรั่งเศส", "เบลเยี่ยม"),
  CountryLocalization("bz", "อังกฤษ", "เบลิซ"),
  CountryLocalization("bj", "ฝรั่งเศส", "เบนิน"),
  CountryLocalization("bm", "อังกฤษ", "เบอร์มิวด้า"),
  CountryLocalization("bt", "ภูฐานี", "ภูฐาน"),
  CountryLocalization("bo", "สเปน", "โบลิเวีย"),
  CountryLocalization("ba", "Bosnian", "บอสเนีย และ เฮิร์ซโกวิเนีย"),
  CountryLocalization("bw", "อังกฤษ", "บอตสวานา"),
  CountryLocalization("br", "โปรตุเกส", "บราซิล"),
  CountryLocalization("io", "อังกฤษ", "British Indian Ocean Territory"),
  CountryLocalization("vg", "อังกฤษ", "บริทิชเวอร์จินไอส์แลนด์"),
  CountryLocalization("bn", "มลายู", "บรูไน"),
  CountryLocalization("bg", "บัลแกเรีย", "บัลแกเรีย"),
  CountryLocalization("bf", "ฝรั่งเศส", "เบอร์กินาฟาโซ"),
  CountryLocalization("bi", "ฝรั่งเศส", "บูรันดิ"),
  CountryLocalization("kh", "เขมร", "กัมพูชา"),
  CountryLocalization("cm", "Basaa", "คาเมรูน"),
  CountryLocalization("ca", "ฝรั่งเศส", "แคนาดา"),
  CountryLocalization("ic", "สเปน", "หมู่เกาะคานารี"),
  CountryLocalization("cv", "คาบูเวอร์เดียนู", "เคพเวอร์ด"),
  CountryLocalization("bq", "ฮอลันดา", "Caribbean Netherlands"),
  CountryLocalization("ky", "อังกฤษ", "Cayman Islands"),
  CountryLocalization("cf", "ลิงกาลา", "สาธารณรัฐแอฟริกากลาง"),
  CountryLocalization("ea", "สเปน", "เซวตาและเมลียา"),
  CountryLocalization("td", "อาระบิค", "ชาด"),
  CountryLocalization("cl", "สเปน", "ชิลี"),
  CountryLocalization("cn", "ทิเบต", "จีน"),
  CountryLocalization("cx", "อังกฤษ", "Christmas Island"),
  CountryLocalization("cc", "อังกฤษ", "Cocos (Keeling) Islands"),
  CountryLocalization("co", "สเปน", "โคลัมเบีย"),
  CountryLocalization("km", "อาระบิค", "โคโมรอส"),
  CountryLocalization("cg", "ลิงกาลา", "คองโก"),
  CountryLocalization("cd", "ซวาฮิรี", "Congo - Kinshasa"),
  CountryLocalization("ck", "อังกฤษ", "Cook Islands"),
  CountryLocalization("cr", "สเปน", "คอสตาริก้า"),
  CountryLocalization("hr", "โครเอเทีย", "โครเอเชีย"),
  CountryLocalization("cu", "สเปน", "คิวบา"),
  CountryLocalization("cw", "ฮอลันดา", "Curaçao"),
  CountryLocalization("cy", "อังกฤษ", "ไซปรัส"),
  CountryLocalization("cz", "เช็ค", "สาธารณรัฐเช็ค"),
  CountryLocalization("ci", "ฝรั่งเศส", "ฝั่งทะเลไอวอริ"),
  CountryLocalization("dk", "อังกฤษ", "เดนมาร์ก"),
  CountryLocalization("dg", "อังกฤษ", "ดิเอโกการ์เซีย"),
  CountryLocalization("dj", "ฝรั่งเศส", "ดิโบติ"),
  CountryLocalization("dm", "อังกฤษ", "โดมินิก้า"),
  CountryLocalization("do", "สเปน", "สาธารณรัฐโดมินิกัน"),
  CountryLocalization("ec", "คิวชัว", "เอกวาดอร์"),
  CountryLocalization("eg", "อาระบิค", "อียิปต์"),
  CountryLocalization("sv", "สเปน", "เอลซาวาดอร์"),
  CountryLocalization("gq", "สเปน", "เอควาโทเรียลกินี"),
  CountryLocalization("er", "ทิกรินยา", "อิริทรี"),
  CountryLocalization("ee", "เอสโตเนีย", "เอสโตเนีย"),
  CountryLocalization("et", "อัมฮาริค", "เอธิโอเปีย"),
  CountryLocalization("fk", "อังกฤษ", "Falkland Islands"),
  CountryLocalization("fo", "ฟาโรส", "Faroe Islands"),
  CountryLocalization("fj", "อังกฤษ", "ฟิจิ"),
  CountryLocalization("fi", "สวีเดน", "ฟินแลนด์"),
  CountryLocalization("fr", "Swiss German", "ฝรั่งเศส"),
  CountryLocalization("gf", "ฝรั่งเศส", "เฟร็นชกิวน่า"),
  CountryLocalization("pf", "ฝรั่งเศส", "เฟร็นชโพลินีเซีย"),
  CountryLocalization("ga", "ฝรั่งเศส", "กาบอน"),
  CountryLocalization("gm", "อังกฤษ", "แกมเบีย"),
  CountryLocalization("ge", "Ossetic", "จอร์เจีย"),
  CountryLocalization("de", "Lower Sorbian", "เยอรมนี"),
  CountryLocalization("gh", "อังกฤษ", "กาน่า"),
  CountryLocalization("gi", "อังกฤษ", "Gibraltar"),
  CountryLocalization("gr", "กรีก", "กรีซ"),
  CountryLocalization("gl", "กรีนแลนด์ดิค", "Greenland"),
  CountryLocalization("gd", "อังกฤษ", "Grenada"),
  CountryLocalization("gp", "ฝรั่งเศส", "กัวเดอลูป"),
  CountryLocalization("gu", "อังกฤษ", "Guam"),
  CountryLocalization("gt", "สเปน", "กัวเตมาลา"),
  CountryLocalization("gg", "อังกฤษ", "Guernsey"),
  CountryLocalization("gn", "ฝรั่งเศส", "กิวนี"),
  CountryLocalization("gw", "โปรตุเกส", "กิวนี-บิสโซ"),
  CountryLocalization("gy", "อังกฤษ", "กูยาน่า"),
  CountryLocalization("ht", "ฝรั่งเศส", "ไฮตี"),
  CountryLocalization("hn", "สเปน", "ฮอนดูรัส"),
  CountryLocalization("hk", "จีน", "ฮ่องกง"),
  CountryLocalization("hu", "ฮังการี", "ฮังการี"),
  CountryLocalization("is", "ไอซ์แลนด์ดิค", "ไอซแลนด์"),
  CountryLocalization("in", "เนปาล", "อินเดีย"),
  CountryLocalization("id", "อินโดนีเชีย", "อินโดนีเซีย"),
  CountryLocalization("ir", "เปอร์เซีย", "อิหร่าน"),
  CountryLocalization("iq", "ลูรีเหนือ", "อิรัก"),
  CountryLocalization("ie", "อังกฤษ", "ไอร์แลนด์"),
  CountryLocalization("im", "Manx", "Isle of Man"),
  CountryLocalization("il", "อังกฤษ", "อิสราเอล"),
  CountryLocalization("it", "เยอรมัน", "อิตาลี"),
  CountryLocalization("jm", "อังกฤษ", "จาไมก้า"),
  CountryLocalization("jp", "ญี่ปุ่น", "ญี่ปุ่น"),
  CountryLocalization("je", "อังกฤษ", "Jersey"),
  CountryLocalization("jo", "อาระบิค", "จอร์แดน"),
  CountryLocalization("kz", "คาซัค", "คาซัคสถาน"),
  CountryLocalization("ke", "โซมาลี", "เคนย่า"),
  CountryLocalization("ki", "อังกฤษ", "คิรีบาติ"),
  CountryLocalization("xk", "เซอร์เบีย", "โคโซโว"),
  CountryLocalization("kw", "อาระบิค", "คูเวต"),
  CountryLocalization("kg", "รัสเซีย", "เคอร์กิสถาน"),
  CountryLocalization("la", "ลาว", "ลาว"),
  CountryLocalization("lv", "แลตเวีย (เลททิสช์)", "ลาตเวีย"),
  CountryLocalization("lb", "อาระบิค", "เลบานอน"),
  CountryLocalization("ls", "อังกฤษ", "เลโซโท"),
  CountryLocalization("lr", "อังกฤษ", "ลิเบอร์เลีย"),
  CountryLocalization("ly", "อาระบิค", "ลิเบีย"),
  CountryLocalization("li", "Swiss German", "ไลเทนสไตน์"),
  CountryLocalization("lt", "ลิธัวเนีย", "ลิเทอร์เนีย"),
  CountryLocalization("lu", "Luxembourgish", "ลักซ์เซมเบอร์ก"),
  CountryLocalization("mo", "โปรตุเกส", "Macao SAR China"),
  CountryLocalization("mk", "แอลเบเนีย", "แมซีโดเนีย"),
  CountryLocalization("mg", "ฝรั่งเศส", "มาดากาสก้า"),
  CountryLocalization("mw", "อังกฤษ", "Malawi"),
  CountryLocalization("my", "ทมิฬ", "มาเลเซีย"),
  CountryLocalization("ml", "ฝรั่งเศส", "มาลี"),
  CountryLocalization("mt", "อังกฤษ", "มัลต้า"),
  CountryLocalization("mh", "อังกฤษ", "Marshall Islands"),
  CountryLocalization("mq", "ฝรั่งเศส", "มาร์ตินิก"),
  CountryLocalization("mr", "อาระบิค", "มอริทาเนีย"),
  CountryLocalization("mu", "มอริสเยน", "มอริเตียส"),
  CountryLocalization("yt", "ฝรั่งเศส", "มายอต"),
  CountryLocalization("mx", "สเปน", "แม็กซิโก"),
  CountryLocalization("fm", "อังกฤษ", "ไมโครนิเซีย"),
  CountryLocalization("md", "รัสเซีย", "โมลโดวา"),
  CountryLocalization("mc", "ฝรั่งเศส", "โมนาโค"),
  CountryLocalization("mn", "มองโกล", "มองโกเลีย"),
  CountryLocalization("me", "เซอร์เบีย", "Montenegro"),
  CountryLocalization("ms", "อังกฤษ", "มอนต์เซอราต"),
  CountryLocalization("ma", "ทามาไซต์แอตลาสกลาง", "โมรอคโค"),
  CountryLocalization("mz", "มากัววา-มีทโท", "โมแซมบิค"),
  CountryLocalization("mm", "พม่า", "สหภาพพม่า"),
  CountryLocalization("na", "อังกฤษ", "นามิเบีย"),
  CountryLocalization("nr", "อังกฤษ", "Nauru"),
  CountryLocalization("np", "เนปาล", "เนปาล"),
  CountryLocalization("nl", "อังกฤษ", "เนเธอร์แลนด์"),
  CountryLocalization("nc", "ฝรั่งเศส", "นิวคาลิโดเนีย"),
  CountryLocalization("nz", "อังกฤษ", "นิวซีแลนด์"),
  CountryLocalization("ni", "สเปน", "นิคารากัว"),
  CountryLocalization("ne", "โฮซา", "ไนเจอร์"),
  CountryLocalization("ng", "โฮซา", "ไนจีเรีย"),
  CountryLocalization("nu", "อังกฤษ", "นียู"),
  CountryLocalization("nf", "อังกฤษ", "Norfolk Island"),
  CountryLocalization("kp", "เกาหลี", "เกาหลีเหนือ"),
  CountryLocalization("mp", "อังกฤษ", "Northern Mariana Islands"),
  CountryLocalization("no", "Northern Sami", "นอร์เวย์"),
  CountryLocalization("om", "อาระบิค", "โอมาน"),
  CountryLocalization("pk", "อังกฤษ", "ปากีสถาน"),
  CountryLocalization("pw", "อังกฤษ", "Palau"),
  CountryLocalization("ps", "อาระบิค", "Palestinian Territories"),
  CountryLocalization("pa", "สเปน", "ปานามา"),
  CountryLocalization("pg", "อังกฤษ", "ปาปัวนิวกีนี"),
  CountryLocalization("py", "สเปน", "ปารากวัย"),
  CountryLocalization("pe", "สเปน", "เปรู"),
  CountryLocalization("ph", "Filipino", "ฟิลิปปินส์"),
  CountryLocalization("pn", "อังกฤษ", "Pitcairn Islands"),
  CountryLocalization("pl", "โปแลนด์", "โปแลนด์"),
  CountryLocalization("pt", "โปรตุเกส", "โปตุกัล"),
  CountryLocalization("pr", "อังกฤษ", "เปอร์โตริโก"),
  CountryLocalization("qa", "อาระบิค", "กาตาร์"),
  CountryLocalization("ro", "โรมัน", "รูเมเนีย"),
  CountryLocalization("ru", "ตาด", "รัสเซีย"),
  CountryLocalization("rw", "อังกฤษ", "ราวัลดา"),
  CountryLocalization("re", "ฝรั่งเศส", "Réunion"),
  CountryLocalization("ws", "อังกฤษ", "Samoa"),
  CountryLocalization("sm", "อิตาลี", "San Marino"),
  CountryLocalization("sa", "อาระบิค", "ซาอุดิอาระเบีย"),
  CountryLocalization("sn", "ฝรั่งเศส", "ซินีกัล"),
  CountryLocalization("rs", "เซอร์เบีย", "Serbia"),
  CountryLocalization("cs", "เซอร์เบีย", "Serbia and Montenegro"),
  CountryLocalization("sc", "ฝรั่งเศส", "เซย์แชลล์"),
  CountryLocalization("sl", "อังกฤษ", "เซียร์ร่าลีออน"),
  CountryLocalization("sg", "ทมิฬ", "สิงคโปร์"),
  CountryLocalization("sx", "อังกฤษ", "Sint Maarten"),
  CountryLocalization("sk", "สโลวัค", "สโลวาเกีย"),
  CountryLocalization("si", "สโลเวเนีย", "สโลวิเนีย"),
  CountryLocalization("sb", "อังกฤษ", "Solomon Islands"),
  CountryLocalization("so", "อาระบิค", "โซมาเลีย"),
  CountryLocalization("za", "อังกฤษ", "แอฟริกาใต้"),
  CountryLocalization("kr", "เกาหลี", "เกาหลีใต้"),
  CountryLocalization("ss", "เนือร์", "South Sudan"),
  CountryLocalization("es", "สเปน", "สเปน"),
  CountryLocalization("lk", "ทมิฬ", "ศรีลังกา"),
  CountryLocalization("bl", "ฝรั่งเศส", "St. Barthélemy"),
  CountryLocalization("sh", "อังกฤษ", "St. Helena"),
  CountryLocalization("kn", "อังกฤษ", "St. Kitts & Nevis"),
  CountryLocalization("lc", "อังกฤษ", "St. Lucia"),
  CountryLocalization("mf", "ฝรั่งเศส", "St. Martin"),
  CountryLocalization("pm", "ฝรั่งเศส", "St. Pierre & Miquelon"),
  CountryLocalization("vc", "อังกฤษ", "St. Vincent & Grenadines"),
  CountryLocalization("sd", "อาระบิค", "ซูดาน"),
  CountryLocalization("sr", "ฮอลันดา", "ซูรินามิ"),
  CountryLocalization("sj", "Norwegian Bokmål", "Svalbard & Jan Mayen"),
  CountryLocalization("sz", "อังกฤษ", "สวาซิแลนด์"),
  CountryLocalization("se", "สวีเดน", "สวีเดน"),
  CountryLocalization("ch", "Swiss German", "สวิสเซอร์แลนด์"),
  CountryLocalization("sy", "อาระบิค", "ซีเรีย"),
  CountryLocalization("st", "โปรตุเกส", "São Tomé & Príncipe"),
  CountryLocalization("tw", "จีน", "ไต้หวัน"),
  CountryLocalization("tj", "ทาจิค", "ทาจิกิสถาน"),
  CountryLocalization("tz", "มาคอนเด", "ทานซาเนีย"),
  CountryLocalization("th", "ไทย", "ประเทศไทย"),
  CountryLocalization("tl", "โปรตุเกส", "Timor-Leste"),
  CountryLocalization("tg", "ฝรั่งเศส", "โตโก"),
  CountryLocalization("tk", "อังกฤษ", "โทกิโล"),
  CountryLocalization("to", "ทองก้า", "ทองก้า"),
  CountryLocalization("tt", "อังกฤษ", "ทรินิแดด และโทบาโก"),
  CountryLocalization("tn", "ฝรั่งเศส", "ตูนิเซีย"),
  CountryLocalization("tr", "ตุรกี", "ตุรกี"),
  CountryLocalization("tm", "เติร์กเมน", "เติร์กเมนิสถาน"),
  CountryLocalization("tc", "อังกฤษ", "Turks & Caicos Islands"),
  CountryLocalization("tv", "อังกฤษ", "Tuvalu"),
  CountryLocalization("um", "อังกฤษ", "U.S. Outlying Islands"),
  CountryLocalization("vi", "อังกฤษ", "ยูเอสเวอร์จินไอส์แลนด์"),
  CountryLocalization("ug", "ซวาฮิรี", "อูกานดา"),
  CountryLocalization("ua", "ยูเครน", "ยูเครน"),
  CountryLocalization("ae", "อาระบิค", "สหรัฐอาหรับเอมิเรตส์"),
  CountryLocalization("gb", "อังกฤษ", "สหราชอาณาจักร"),
  CountryLocalization("us", "ลาโกตา", "สหรัฐอเมริกา"),
  CountryLocalization("uy", "สเปน", "อุรูกวัย"),
  CountryLocalization("uz", "อุสเบค", "อุซเบกิสถาน"),
  CountryLocalization("vu", "ฝรั่งเศส", "วานัวตู"),
  CountryLocalization("va", "อิตาลี", "วาติกัน"),
  CountryLocalization("ve", "สเปน", "เวเนซูเอล่า"),
  CountryLocalization("vn", "เวียดนาม", "เวียดนาม"),
  CountryLocalization("wf", "ฝรั่งเศส", "Wallis & Futuna"),
  CountryLocalization("eh", "อาระบิค", "ซาฮาร่าตะวันตก"),
  CountryLocalization("ye", "อาระบิค", "เยเมน"),
  CountryLocalization("zm", "อังกฤษ", "แซมเบีย"),
  CountryLocalization("zw", "North Ndebele", "ซิมบาบเว"),
  CountryLocalization("ax", "สวีเดน", "Åland Islands"),
)
