/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot.atlas.extended

import dev.teogor.xenoglot.atlas.CountryLocalization
import kotlin.collections.List

/**
 * Holds the internal list of country-language mappings used for lookups within the package for
 * language code sq.
 *
 * This property contains a hardcoded list of [CountryLocalization] objects, each representing
 * a country and its associated official languages. This list is used by [CountryLanguageRegistry]
 * to provide access to country-language data and should not be modified directly.
 *
 * @see CountryLocalization
 * @see CountryLanguageRegistry
 */
internal val _countryLanguageMappings_sq: List<CountryLocalization> = listOf(
  CountryLocalization("af", "persisht", "Afganistan"),
  CountryLocalization("al", "shqip", "Shqipëri"),
  CountryLocalization("dz", "frëngjisht", "Algjeri"),
  CountryLocalization("as", "anglisht", "Samoa Amerikane"),
  CountryLocalization("ad", "katalonisht", "Andorrë"),
  CountryLocalization("ao", "lingalisht", "Angolë"),
  CountryLocalization("ai", "anglisht", "Anguilë"),
  CountryLocalization("ag", "anglisht", "Antigua e Barbuda"),
  CountryLocalization("ar", "spanjisht", "Argjentinë"),
  CountryLocalization("am", "armenisht", "Armeni"),
  CountryLocalization("aw", "holandisht", "Arubë"),
  CountryLocalization("au", "anglisht", "Australi"),
  CountryLocalization("at", "anglisht", "Austri"),
  CountryLocalization("az", "azerbajxhanisht", "Azerbajxhan"),
  CountryLocalization("bs", "anglisht", "Bahamas"),
  CountryLocalization("bh", "arabisht", "Bahrejn"),
  CountryLocalization("bd", "bengalisht", "Bangladesh"),
  CountryLocalization("bb", "anglisht", "Barbados"),
  CountryLocalization("by", "bjellorusisht", "Bjellorusi"),
  CountryLocalization("be", "frëngjisht", "Belgjikë"),
  CountryLocalization("bz", "anglisht", "Belizë"),
  CountryLocalization("bj", "frëngjisht", "Benin"),
  CountryLocalization("bm", "anglisht", "Bermudë"),
  CountryLocalization("bt", "xhongaisht", "Butan"),
  CountryLocalization("bo", "spanjisht", "Bolivi"),
  CountryLocalization("ba", "boshnjakisht", "Bosnjë-Hercegovinë"),
  CountryLocalization("bw", "anglisht", "Botsvanë"),
  CountryLocalization("br", "portugalisht", "Brazil"),
  CountryLocalization("io", "anglisht", "Territori Britanik i Oqeanit Indian"),
  CountryLocalization("vg", "anglisht", "Ishujt e Virgjër Britanikë"),
  CountryLocalization("bn", "malajisht", "Brunei"),
  CountryLocalization("bg", "bullgarisht", "Bullgari"),
  CountryLocalization("bf", "frëngjisht", "Burkina-Faso"),
  CountryLocalization("bi", "frëngjisht", "Burundi"),
  CountryLocalization("kh", "kmerisht", "Kamboxhia"),
  CountryLocalization("cm", "basaisht", "Kamerun"),
  CountryLocalization("ca", "frëngjisht", "Kanada"),
  CountryLocalization("ic", "spanjisht", "Ishujt Kanarie"),
  CountryLocalization("cv", "kreolishte e Kepit të Gjelbër", "Kepi i Gjelbër"),
  CountryLocalization("bq", "holandisht", "Karaibet holandeze"),
  CountryLocalization("ky", "anglisht", "Ishujt Kajman"),
  CountryLocalization("cf", "lingalisht", "Republika e Afrikës Qendrore"),
  CountryLocalization("ea", "spanjisht", "Theuta e Melila"),
  CountryLocalization("td", "arabisht", "Çad"),
  CountryLocalization("cl", "spanjisht", "Kili"),
  CountryLocalization("cn", "tibetisht", "Kinë"),
  CountryLocalization("cx", "anglisht", "Ishulli i Krishtlindjes"),
  CountryLocalization("cc", "anglisht", "Ishujt Kokos"),
  CountryLocalization("co", "spanjisht", "Kolumbi"),
  CountryLocalization("km", "arabisht", "Komore"),
  CountryLocalization("cg", "lingalisht", "Kongo-Brazavilë"),
  CountryLocalization("cd", "suahilisht", "Kongo-Kinshasa"),
  CountryLocalization("ck", "anglisht", "Ishujt Kuk"),
  CountryLocalization("cr", "spanjisht", "Kosta-Rikë"),
  CountryLocalization("hr", "kroatisht", "Kroaci"),
  CountryLocalization("cu", "spanjisht", "Kubë"),
  CountryLocalization("cw", "holandisht", "Kuraçao"),
  CountryLocalization("cy", "anglisht", "Qipro"),
  CountryLocalization("cz", "çekisht", "Çeki"),
  CountryLocalization("ci", "frëngjisht", "Côte d’Ivoire"),
  CountryLocalization("dk", "anglisht", "Danimarkë"),
  CountryLocalization("dg", "anglisht", "Diego-Garsia"),
  CountryLocalization("dj", "frëngjisht", "Xhibuti"),
  CountryLocalization("dm", "anglisht", "Dominikë"),
  CountryLocalization("do", "spanjisht", "Republika Dominikane"),
  CountryLocalization("ec", "keçuaisht", "Ekuador"),
  CountryLocalization("eg", "arabisht", "Egjipt"),
  CountryLocalization("sv", "spanjisht", "Salvador"),
  CountryLocalization("gq", "spanjisht", "Guineja Ekuatoriale"),
  CountryLocalization("er", "tigrinjaisht", "Eritre"),
  CountryLocalization("ee", "estonisht", "Estoni"),
  CountryLocalization("et", "amarisht", "Etiopi"),
  CountryLocalization("fk", "anglisht", "Ishujt Falkland"),
  CountryLocalization("fo", "faroisht", "Ishujt Faroe"),
  CountryLocalization("fj", "anglisht", "Fixhi"),
  CountryLocalization("fi", "suedisht", "Finlandë"),
  CountryLocalization("fr", "gjermanishte zvicerane", "Francë"),
  CountryLocalization("gf", "frëngjisht", "Guajana Franceze"),
  CountryLocalization("pf", "frëngjisht", "Polinezia Franceze"),
  CountryLocalization("ga", "frëngjisht", "Gabon"),
  CountryLocalization("gm", "anglisht", "Gambia"),
  CountryLocalization("ge", "osetisht", "Gjeorgji"),
  CountryLocalization("de", "sorbishte e poshtme", "Gjermani"),
  CountryLocalization("gh", "anglisht", "Ganë"),
  CountryLocalization("gi", "anglisht", "Gjibraltar"),
  CountryLocalization("gr", "greqisht", "Greqi"),
  CountryLocalization("gl", "kalalisutisht", "Grenlandë"),
  CountryLocalization("gd", "anglisht", "Grenadë"),
  CountryLocalization("gp", "frëngjisht", "Guadalupe"),
  CountryLocalization("gu", "anglisht", "Guam"),
  CountryLocalization("gt", "spanjisht", "Guatemalë"),
  CountryLocalization("gg", "anglisht", "Gernsej"),
  CountryLocalization("gn", "frëngjisht", "Guine"),
  CountryLocalization("gw", "portugalisht", "Guine-Bisau"),
  CountryLocalization("gy", "anglisht", "Guajanë"),
  CountryLocalization("ht", "frëngjisht", "Haiti"),
  CountryLocalization("hn", "spanjisht", "Honduras"),
  CountryLocalization("hk", "kinezisht", "RPA i Hong-Kongut"),
  CountryLocalization("hu", "hungarisht", "Hungari"),
  CountryLocalization("is", "islandisht", "Islandë"),
  CountryLocalization("in", "nepalisht", "Indi"),
  CountryLocalization("id", "Indonesian", "Indonezi"),
  CountryLocalization("ir", "persisht", "Iran"),
  CountryLocalization("iq", "lurishte veriore", "Irak"),
  CountryLocalization("ie", "anglisht", "Irlandë"),
  CountryLocalization("im", "manksisht", "Ishulli i Manit"),
  CountryLocalization("il", "anglisht", "Izrael"),
  CountryLocalization("it", "gjermanisht", "Itali"),
  CountryLocalization("jm", "anglisht", "Xhamajkë"),
  CountryLocalization("jp", "japonisht", "Japoni"),
  CountryLocalization("je", "anglisht", "Xhersej"),
  CountryLocalization("jo", "arabisht", "Jordani"),
  CountryLocalization("kz", "kazakisht", "Kazakistan"),
  CountryLocalization("ke", "somalisht", "Kenia"),
  CountryLocalization("ki", "anglisht", "Kiribati"),
  CountryLocalization("xk", "serbisht", "Kosovë"),
  CountryLocalization("kw", "arabisht", "Kuvajt"),
  CountryLocalization("kg", "rusisht", "Kirgistan"),
  CountryLocalization("la", "laosisht", "Laos"),
  CountryLocalization("lv", "letonisht", "Letoni"),
  CountryLocalization("lb", "arabisht", "Liban"),
  CountryLocalization("ls", "anglisht", "Lesoto"),
  CountryLocalization("lr", "anglisht", "Liberi"),
  CountryLocalization("ly", "arabisht", "Libi"),
  CountryLocalization("li", "gjermanishte zvicerane", "Lihtenshtajn"),
  CountryLocalization("lt", "lituanisht", "Lituani"),
  CountryLocalization("lu", "luksemburgisht", "Luksemburg"),
  CountryLocalization("mo", "portugalisht", "RPA i Makaos"),
  CountryLocalization("mk", "shqip", "Maqedoni"),
  CountryLocalization("mg", "frëngjisht", "Madagaskar"),
  CountryLocalization("mw", "anglisht", "Malavi"),
  CountryLocalization("my", "tamilisht", "Malajzi"),
  CountryLocalization("ml", "frëngjisht", "Mali"),
  CountryLocalization("mt", "anglisht", "Maltë"),
  CountryLocalization("mh", "anglisht", "Ishujt Marshall"),
  CountryLocalization("mq", "frëngjisht", "Martinikë"),
  CountryLocalization("mr", "arabisht", "Mauritani"),
  CountryLocalization("mu", "morisjenisht", "Mauritius"),
  CountryLocalization("yt", "frëngjisht", "Majotë"),
  CountryLocalization("mx", "spanjisht", "Meksikë"),
  CountryLocalization("fm", "anglisht", "Mikronezi"),
  CountryLocalization("md", "rusisht", "Moldavi"),
  CountryLocalization("mc", "frëngjisht", "Monako"),
  CountryLocalization("mn", "mongolisht", "Mongoli"),
  CountryLocalization("me", "serbisht", "Mal i Zi"),
  CountryLocalization("ms", "anglisht", "Montserat"),
  CountryLocalization("ma", "tamazajtisht e Atlasit Qendror", "Marok"),
  CountryLocalization("mz", "makua-mitoisht", "Mozambik"),
  CountryLocalization("mm", "birmanisht", "Mianmar (Burma)"),
  CountryLocalization("na", "anglisht", "Namibi"),
  CountryLocalization("nr", "anglisht", "Nauru"),
  CountryLocalization("np", "nepalisht", "Nepal"),
  CountryLocalization("nl", "anglisht", "Holandë"),
  CountryLocalization("nc", "frëngjisht", "Kaledonia e Re"),
  CountryLocalization("nz", "anglisht", "Zelandë e Re"),
  CountryLocalization("ni", "spanjisht", "Nikaragua"),
  CountryLocalization("ne", "hausisht", "Niger"),
  CountryLocalization("ng", "hausisht", "Nigeri"),
  CountryLocalization("nu", "anglisht", "Niue"),
  CountryLocalization("nf", "anglisht", "Ishulli Norfolk"),
  CountryLocalization("kp", "koreanisht", "Koreja e Veriut"),
  CountryLocalization("mp", "anglisht", "Ishujt e Marianës Veriore"),
  CountryLocalization("no", "samishte veriore", "Norvegji"),
  CountryLocalization("om", "arabisht", "Oman"),
  CountryLocalization("pk", "anglisht", "Pakistan"),
  CountryLocalization("pw", "anglisht", "Palau"),
  CountryLocalization("ps", "arabisht", "Territoret Palestineze"),
  CountryLocalization("pa", "spanjisht", "Panama"),
  CountryLocalization("pg", "anglisht", "Guineja e Re-Papua"),
  CountryLocalization("py", "spanjisht", "Paraguai"),
  CountryLocalization("pe", "spanjisht", "Peru"),
  CountryLocalization("ph", "filipinisht", "Filipine"),
  CountryLocalization("pn", "anglisht", "Ishujt Pitkern"),
  CountryLocalization("pl", "polonisht", "Poloni"),
  CountryLocalization("pt", "portugalisht", "Portugali"),
  CountryLocalization("pr", "anglisht", "Porto-Riko"),
  CountryLocalization("qa", "arabisht", "Katar"),
  CountryLocalization("ro", "rumanisht", "Rumani"),
  CountryLocalization("ru", "tatarisht", "Rusi"),
  CountryLocalization("rw", "anglisht", "Ruandë"),
  CountryLocalization("re", "frëngjisht", "Reunion"),
  CountryLocalization("ws", "anglisht", "Samoa"),
  CountryLocalization("sm", "italisht", "San-Marino"),
  CountryLocalization("sa", "arabisht", "Arabia Saudite"),
  CountryLocalization("sn", "frëngjisht", "Senegal"),
  CountryLocalization("rs", "serbisht", "Serbi"),
  CountryLocalization("cs", "serbisht", "Serbia and Montenegro"),
  CountryLocalization("sc", "frëngjisht", "Sejshelle"),
  CountryLocalization("sl", "anglisht", "Siera-Leone"),
  CountryLocalization("sg", "tamilisht", "Singapor"),
  CountryLocalization("sx", "anglisht", "Sint-Marten"),
  CountryLocalization("sk", "sllovakisht", "Sllovaki"),
  CountryLocalization("si", "sllovenisht", "Slloveni"),
  CountryLocalization("sb", "anglisht", "Ishujt Solomon"),
  CountryLocalization("so", "arabisht", "Somali"),
  CountryLocalization("za", "anglisht", "Afrika e Jugut"),
  CountryLocalization("kr", "koreanisht", "Koreja e Jugut"),
  CountryLocalization("ss", "nuerisht", "Sudani i Jugut"),
  CountryLocalization("es", "spanjisht", "Spanjë"),
  CountryLocalization("lk", "tamilisht", "Sri-Lankë"),
  CountryLocalization("bl", "frëngjisht", "Shën-Bartolome"),
  CountryLocalization("sh", "anglisht", "Shën-Helenë"),
  CountryLocalization("kn", "anglisht", "Shën-Kits dhe Nevis"),
  CountryLocalization("lc", "anglisht", "Shën-Luçia"),
  CountryLocalization("mf", "frëngjisht", "Shën-Martin"),
  CountryLocalization("pm", "frëngjisht", "Shën-Pier dhe Mikelon"),
  CountryLocalization("vc", "anglisht", "Shën-Vincent dhe Grenadine"),
  CountryLocalization("sd", "arabisht", "Sudan"),
  CountryLocalization("sr", "holandisht", "Surinami"),
  CountryLocalization("sj", "norvegjishte letrare", "Svalbard e Jan-Majen"),
  CountryLocalization("sz", "anglisht", "Svazilandë"),
  CountryLocalization("se", "suedisht", "Suedi"),
  CountryLocalization("ch", "gjermanishte zvicerane", "Zvicër"),
  CountryLocalization("sy", "arabisht", "Siri"),
  CountryLocalization("st", "portugalisht", "Sao-Tome e Principe"),
  CountryLocalization("tw", "kinezisht", "Tajvan"),
  CountryLocalization("tj", "taxhikisht", "Taxhikistan"),
  CountryLocalization("tz", "makondisht", "Tanzani"),
  CountryLocalization("th", "tajlandisht", "Tajlandë"),
  CountryLocalization("tl", "portugalisht", "Timor-Leste"),
  CountryLocalization("tg", "frëngjisht", "Togo"),
  CountryLocalization("tk", "anglisht", "Tokelau"),
  CountryLocalization("to", "tonganisht", "Tonga"),
  CountryLocalization("tt", "anglisht", "Trinidad e Tobago"),
  CountryLocalization("tn", "frëngjisht", "Tunizi"),
  CountryLocalization("tr", "turqisht", "Turqi"),
  CountryLocalization("tm", "turkmenisht", "Turkmenistan"),
  CountryLocalization("tc", "anglisht", "Ishujt Turks dhe Kaikos"),
  CountryLocalization("tv", "anglisht", "Tuvalu"),
  CountryLocalization("um", "anglisht", "Ishujt Periferikë të SHBA-së"),
  CountryLocalization("vi", "anglisht", "Ishujt e Virgjër të SHBA-së"),
  CountryLocalization("ug", "suahilisht", "Ugandë"),
  CountryLocalization("ua", "ukrainisht", "Ukrainë"),
  CountryLocalization("ae", "arabisht", "Emiratet e Bashkuara Arabe"),
  CountryLocalization("gb", "anglisht", "Mbretëria e Bashkuar"),
  CountryLocalization("us", "lakotisht", "Shtetet e Bashkuara të Amerikës"),
  CountryLocalization("uy", "spanjisht", "Uruguai"),
  CountryLocalization("uz", "uzbekisht", "Uzbekistan"),
  CountryLocalization("vu", "frëngjisht", "Vanuatu"),
  CountryLocalization("va", "italisht", "Vatikan"),
  CountryLocalization("ve", "spanjisht", "Venezuelë"),
  CountryLocalization("vn", "vietnamisht", "Vietnam"),
  CountryLocalization("wf", "frëngjisht", "Uollis e Futuna"),
  CountryLocalization("eh", "arabisht", "Saharaja Perëndimore"),
  CountryLocalization("ye", "arabisht", "Jemen"),
  CountryLocalization("zm", "anglisht", "Zambia"),
  CountryLocalization("zw", "ndebelishte veriore", "Zimbabve"),
  CountryLocalization("ax", "suedisht", "Ishujt Alandë"),
)
