/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot.atlas.extended

import dev.teogor.xenoglot.atlas.CountryLocalization
import kotlin.collections.List

/**
 * Holds the internal list of country-language mappings used for lookups within the package for
 * language code lrc.
 *
 * This property contains a hardcoded list of [CountryLocalization] objects, each representing
 * a country and its associated official languages. This list is used by [CountryLanguageRegistry]
 * to provide access to country-language data and should not be modified directly.
 *
 * @see CountryLocalization
 * @see CountryLanguageRegistry
 */
internal val _countryLanguageMappings_lrc: List<CountryLocalization> = listOf(
  CountryLocalization("af", "فارسی", "Afghanistan"),
  CountryLocalization("al", "آلبانی", "Albania"),
  CountryLocalization("dz", "فآرانسئ ئی", "Algeria"),
  CountryLocalization("as", "ئینگیلیسی", "American Samoa"),
  CountryLocalization("ad", "کاتالان", "Andorra"),
  CountryLocalization("ao", "لینگالا", "Angola"),
  CountryLocalization("ai", "ئینگیلیسی", "Anguilla"),
  CountryLocalization("ag", "ئینگیلیسی", "Antigua & Barbuda"),
  CountryLocalization("ar", "ئسپانیایی", "Argentina"),
  CountryLocalization("am", "أرمأنی", "Armenia"),
  CountryLocalization("aw", "ھولأندی", "Aruba"),
  CountryLocalization("au", "ئینگیلیسی", "Australia"),
  CountryLocalization("at", "ئینگیلیسی", "Austria"),
  CountryLocalization("az", "آذأربایئجانی ھارگە", "Azerbaijan"),
  CountryLocalization("bs", "ئینگیلیسی", "Bahamas"),
  CountryLocalization("bh", "أرأڤی", "Bahrain"),
  CountryLocalization("bd", "بأنگالی", "Bangladesh"),
  CountryLocalization("bb", "ئینگیلیسی", "Barbados"),
  CountryLocalization("by", "بئلاروٙسی", "Belarus"),
  CountryLocalization("be", "فآرانسئ ئی", "Belgium"),
  CountryLocalization("bz", "ئینگیلیسی", "Belize"),
  CountryLocalization("bj", "فآرانسئ ئی", "Benin"),
  CountryLocalization("bm", "ئینگیلیسی", "Bermuda"),
  CountryLocalization("bt", "زوٙنگخا", "Bhutan"),
  CountryLocalization("bo", "ئسپانیایی", "Bolivia"),
  CountryLocalization("ba", "بوسنیایی", "Bosnia & Herzegovina"),
  CountryLocalization("bw", "ئینگیلیسی", "Botswana"),
  CountryLocalization("br", "پورتئغالی", "بئرئزیل"),
  CountryLocalization("io", "ئینگیلیسی", "British Indian Ocean Territory"),
  CountryLocalization("vg", "ئینگیلیسی", "British Virgin Islands"),
  CountryLocalization("bn", "مالایی", "Brunei"),
  CountryLocalization("bg", "بولغاری", "Bulgaria"),
  CountryLocalization("bf", "فآرانسئ ئی", "Burkina Faso"),
  CountryLocalization("bi", "فآرانسئ ئی", "Burundi"),
  CountryLocalization("kh", "خئمئر", "Cambodia"),
  CountryLocalization("cm", "Basaa", "Cameroon"),
  CountryLocalization("ca", "فآرانسئ ئی", "Canada"),
  CountryLocalization("ic", "ئسپانیایی", "IC"),
  CountryLocalization("cv", "کاباردینو", "Cape Verde"),
  CountryLocalization("bq", "ھولأندی", "Caribbean Netherlands"),
  CountryLocalization("ky", "ئینگیلیسی", "Cayman Islands"),
  CountryLocalization("cf", "لینگالا", "Central African Republic"),
  CountryLocalization("ea", "ئسپانیایی", "EA"),
  CountryLocalization("td", "أرأڤی", "Chad"),
  CountryLocalization("cl", "ئسپانیایی", "Chile"),
  CountryLocalization("cn", "تأبأتی", "چین"),
  CountryLocalization("cx", "ئینگیلیسی", "Christmas Island"),
  CountryLocalization("cc", "ئینگیلیسی", "Cocos (Keeling) Islands"),
  CountryLocalization("co", "ئسپانیایی", "Colombia"),
  CountryLocalization("km", "أرأڤی", "Comoros"),
  CountryLocalization("cg", "لینگالا", "Congo - Brazzaville"),
  CountryLocalization("cd", "سأڤاحیلی", "Congo - Kinshasa"),
  CountryLocalization("ck", "ئینگیلیسی", "Cook Islands"),
  CountryLocalization("cr", "ئسپانیایی", "Costa Rica"),
  CountryLocalization("hr", "کوروڤاتی", "Croatia"),
  CountryLocalization("cu", "ئسپانیایی", "Cuba"),
  CountryLocalization("cw", "ھولأندی", "Curaçao"),
  CountryLocalization("cy", "ئینگیلیسی", "Cyprus"),
  CountryLocalization("cz", "Czech", "Czechia"),
  CountryLocalization("ci", "فآرانسئ ئی", "Côte d’Ivoire"),
  CountryLocalization("dk", "ئینگیلیسی", "Denmark"),
  CountryLocalization("dg", "ئینگیلیسی", "DG"),
  CountryLocalization("dj", "فآرانسئ ئی", "Djibouti"),
  CountryLocalization("dm", "ئینگیلیسی", "Dominica"),
  CountryLocalization("do", "ئسپانیایی", "Dominican Republic"),
  CountryLocalization("ec", "کوچوٙا", "Ecuador"),
  CountryLocalization("eg", "أرأڤی", "Egypt"),
  CountryLocalization("sv", "ئسپانیایی", "El Salvador"),
  CountryLocalization("gq", "ئسپانیایی", "Equatorial Guinea"),
  CountryLocalization("er", "تیگرینیا", "Eritrea"),
  CountryLocalization("ee", "ئستونیایی", "Estonia"),
  CountryLocalization("et", "أمھأری", "Ethiopia"),
  CountryLocalization("fk", "ئینگیلیسی", "Falkland Islands"),
  CountryLocalization("fo", "فاروٙسی", "Faroe Islands"),
  CountryLocalization("fj", "ئینگیلیسی", "Fiji"),
  CountryLocalization("fi", "سوٙئدی", "Finland"),
  CountryLocalization("fr", "آلمانی سوٙئیسی", "فأرانسە"),
  CountryLocalization("gf", "فآرانسئ ئی", "French Guiana"),
  CountryLocalization("pf", "فآرانسئ ئی", "French Polynesia"),
  CountryLocalization("ga", "فآرانسئ ئی", "Gabon"),
  CountryLocalization("gm", "ئینگیلیسی", "Gambia"),
  CountryLocalization("ge", "Ossetic", "Georgia"),
  CountryLocalization("de", "سوربی ھاری", "آلمان"),
  CountryLocalization("gh", "ئینگیلیسی", "Ghana"),
  CountryLocalization("gi", "ئینگیلیسی", "Gibraltar"),
  CountryLocalization("gr", "یوٙنانی", "Greece"),
  CountryLocalization("gl", "کالالیسوٙت", "Greenland"),
  CountryLocalization("gd", "ئینگیلیسی", "Grenada"),
  CountryLocalization("gp", "فآرانسئ ئی", "Guadeloupe"),
  CountryLocalization("gu", "ئینگیلیسی", "Guam"),
  CountryLocalization("gt", "ئسپانیایی", "Guatemala"),
  CountryLocalization("gg", "ئینگیلیسی", "Guernsey"),
  CountryLocalization("gn", "فآرانسئ ئی", "Guinea"),
  CountryLocalization("gw", "پورتئغالی", "Guinea-Bissau"),
  CountryLocalization("gy", "ئینگیلیسی", "Guyana"),
  CountryLocalization("ht", "فآرانسئ ئی", "Haiti"),
  CountryLocalization("hn", "ئسپانیایی", "Honduras"),
  CountryLocalization("hk", "چینی", "Hong Kong SAR China"),
  CountryLocalization("hu", "مأجاری", "Hungary"),
  CountryLocalization("is", "ئیسلأندی", "Iceland"),
  CountryLocalization("in", "نئپالی", "ھئن"),
  CountryLocalization("id", "Indonesian", "Indonesia"),
  CountryLocalization("ir", "فارسی", "Iran"),
  CountryLocalization("iq", "لۊری شومالی", "Iraq"),
  CountryLocalization("ie", "ئینگیلیسی", "Ireland"),
  CountryLocalization("im", "مانکس", "Isle of Man"),
  CountryLocalization("il", "ئینگیلیسی", "Israel"),
  CountryLocalization("it", "آلمانی", "ئیتالیا"),
  CountryLocalization("jm", "ئینگیلیسی", "Jamaica"),
  CountryLocalization("jp", "جاپوٙنی", "جاپوٙن"),
  CountryLocalization("je", "ئینگیلیسی", "Jersey"),
  CountryLocalization("jo", "أرأڤی", "Jordan"),
  CountryLocalization("kz", "قأزاق", "Kazakhstan"),
  CountryLocalization("ke", "سوٙمالی", "Kenya"),
  CountryLocalization("ki", "ئینگیلیسی", "Kiribati"),
  CountryLocalization("xk", "سئربی", "XK"),
  CountryLocalization("kw", "أرأڤی", "Kuwait"),
  CountryLocalization("kg", "روٙسی", "Kyrgyzstan"),
  CountryLocalization("la", "لاو", "Laos"),
  CountryLocalization("lv", "لاتوڤیایی", "Latvia"),
  CountryLocalization("lb", "أرأڤی", "Lebanon"),
  CountryLocalization("ls", "ئینگیلیسی", "Lesotho"),
  CountryLocalization("lr", "ئینگیلیسی", "Liberia"),
  CountryLocalization("ly", "أرأڤی", "Libya"),
  CountryLocalization("li", "آلمانی سوٙئیسی", "Liechtenstein"),
  CountryLocalization("lt", "لیتوڤانیایی", "Lithuania"),
  CountryLocalization("lu", "لوٙکزامبوٙرگی", "Luxembourg"),
  CountryLocalization("mo", "پورتئغالی", "Macao SAR China"),
  CountryLocalization("mk", "آلبانی", "North Macedonia"),
  CountryLocalization("mg", "فآرانسئ ئی", "Madagascar"),
  CountryLocalization("mw", "ئینگیلیسی", "Malawi"),
  CountryLocalization("my", "تامیل", "Malaysia"),
  CountryLocalization("ml", "فآرانسئ ئی", "Mali"),
  CountryLocalization("mt", "ئینگیلیسی", "Malta"),
  CountryLocalization("mh", "ئینگیلیسی", "Marshall Islands"),
  CountryLocalization("mq", "فآرانسئ ئی", "Martinique"),
  CountryLocalization("mr", "أرأڤی", "Mauritania"),
  CountryLocalization("mu", "موٙریسی", "Mauritius"),
  CountryLocalization("yt", "فآرانسئ ئی", "Mayotte"),
  CountryLocalization("mx", "ئسپانیایی", "Mexico"),
  CountryLocalization("fm", "ئینگیلیسی", "Micronesia"),
  CountryLocalization("md", "روٙسی", "Moldova"),
  CountryLocalization("mc", "فآرانسئ ئی", "Monaco"),
  CountryLocalization("mn", "موغولی", "Mongolia"),
  CountryLocalization("me", "سئربی", "Montenegro"),
  CountryLocalization("ms", "ئینگیلیسی", "Montserrat"),
  CountryLocalization("ma", "تامازیغ مینجایی", "Morocco"),
  CountryLocalization("mz", "ماخوڤا میتو", "Mozambique"),
  CountryLocalization("mm", "بئرمئ یی", "Myanmar (Burma)"),
  CountryLocalization("na", "ئینگیلیسی", "Namibia"),
  CountryLocalization("nr", "ئینگیلیسی", "Nauru"),
  CountryLocalization("np", "نئپالی", "Nepal"),
  CountryLocalization("nl", "ئینگیلیسی", "Netherlands"),
  CountryLocalization("nc", "فآرانسئ ئی", "New Caledonia"),
  CountryLocalization("nz", "ئینگیلیسی", "New Zealand"),
  CountryLocalization("ni", "ئسپانیایی", "Nicaragua"),
  CountryLocalization("ne", "ھائوسا", "Niger"),
  CountryLocalization("ng", "ھائوسا", "Nigeria"),
  CountryLocalization("nu", "ئینگیلیسی", "Niue"),
  CountryLocalization("nf", "ئینگیلیسی", "Norfolk Island"),
  CountryLocalization("kp", "کورئ یی", "North Korea"),
  CountryLocalization("mp", "ئینگیلیسی", "Northern Mariana Islands"),
  CountryLocalization("no", "سامی شومالی", "Norway"),
  CountryLocalization("om", "أرأڤی", "Oman"),
  CountryLocalization("pk", "ئینگیلیسی", "Pakistan"),
  CountryLocalization("pw", "ئینگیلیسی", "Palau"),
  CountryLocalization("ps", "أرأڤی", "Palestinian Territories"),
  CountryLocalization("pa", "ئسپانیایی", "Panama"),
  CountryLocalization("pg", "ئینگیلیسی", "Papua New Guinea"),
  CountryLocalization("py", "ئسپانیایی", "Paraguay"),
  CountryLocalization("pe", "ئسپانیایی", "Peru"),
  CountryLocalization("ph", "فیلیپینی", "Philippines"),
  CountryLocalization("pn", "ئینگیلیسی", "Pitcairn Islands"),
  CountryLocalization("pl", "لأھئستانی", "Poland"),
  CountryLocalization("pt", "پورتئغالی", "Portugal"),
  CountryLocalization("pr", "ئینگیلیسی", "Puerto Rico"),
  CountryLocalization("qa", "أرأڤی", "Qatar"),
  CountryLocalization("ro", "رومانیایی", "Romania"),
  CountryLocalization("ru", "تاتار", "روٙسیە"),
  CountryLocalization("rw", "ئینگیلیسی", "Rwanda"),
  CountryLocalization("re", "فآرانسئ ئی", "Réunion"),
  CountryLocalization("ws", "ئینگیلیسی", "Samoa"),
  CountryLocalization("sm", "ئیتالیایی", "San Marino"),
  CountryLocalization("sa", "أرأڤی", "Saudi Arabia"),
  CountryLocalization("sn", "فآرانسئ ئی", "Senegal"),
  CountryLocalization("rs", "سئربی", "Serbia"),
  CountryLocalization("cs", "سئربی", "Serbia and Montenegro"),
  CountryLocalization("sc", "فآرانسئ ئی", "Seychelles"),
  CountryLocalization("sl", "ئینگیلیسی", "Sierra Leone"),
  CountryLocalization("sg", "تامیل", "Singapore"),
  CountryLocalization("sx", "ئینگیلیسی", "Sint Maarten"),
  CountryLocalization("sk", "ئسلوڤاکی", "Slovakia"),
  CountryLocalization("si", "ئسلوڤئنیایی", "Slovenia"),
  CountryLocalization("sb", "ئینگیلیسی", "Solomon Islands"),
  CountryLocalization("so", "أرأڤی", "Somalia"),
  CountryLocalization("za", "ئینگیلیسی", "South Africa"),
  CountryLocalization("kr", "کورئ یی", "South Korea"),
  CountryLocalization("ss", "نیوٙئر", "South Sudan"),
  CountryLocalization("es", "ئسپانیایی", "Spain"),
  CountryLocalization("lk", "تامیل", "Sri Lanka"),
  CountryLocalization("bl", "فآرانسئ ئی", "St. Barthélemy"),
  CountryLocalization("sh", "ئینگیلیسی", "St. Helena"),
  CountryLocalization("kn", "ئینگیلیسی", "St. Kitts & Nevis"),
  CountryLocalization("lc", "ئینگیلیسی", "St. Lucia"),
  CountryLocalization("mf", "فآرانسئ ئی", "St. Martin"),
  CountryLocalization("pm", "فآرانسئ ئی", "St. Pierre & Miquelon"),
  CountryLocalization("vc", "ئینگیلیسی", "St. Vincent & Grenadines"),
  CountryLocalization("sd", "أرأڤی", "Sudan"),
  CountryLocalization("sr", "ھولأندی", "Suriname"),
  CountryLocalization("sj", "نورڤئجی بوٙکمال", "Svalbard & Jan Mayen"),
  CountryLocalization("sz", "ئینگیلیسی", "Eswatini"),
  CountryLocalization("se", "سوٙئدی", "Sweden"),
  CountryLocalization("ch", "آلمانی سوٙئیسی", "Switzerland"),
  CountryLocalization("sy", "أرأڤی", "Syria"),
  CountryLocalization("st", "پورتئغالی", "São Tomé & Príncipe"),
  CountryLocalization("tw", "چینی", "Taiwan"),
  CountryLocalization("tj", "تاجیکی", "Tajikistan"),
  CountryLocalization("tz", "ماکوٙندئ", "Tanzania"),
  CountryLocalization("th", "تایلأندی", "Thailand"),
  CountryLocalization("tl", "پورتئغالی", "Timor-Leste"),
  CountryLocalization("tg", "فآرانسئ ئی", "Togo"),
  CountryLocalization("tk", "ئینگیلیسی", "Tokelau"),
  CountryLocalization("to", "توٙنگان", "Tonga"),
  CountryLocalization("tt", "ئینگیلیسی", "Trinidad & Tobago"),
  CountryLocalization("tn", "فآرانسئ ئی", "Tunisia"),
  CountryLocalization("tr", "تورکی", "Turkey"),
  CountryLocalization("tm", "تورکأمأنی", "Turkmenistan"),
  CountryLocalization("tc", "ئینگیلیسی", "Turks & Caicos Islands"),
  CountryLocalization("tv", "ئینگیلیسی", "Tuvalu"),
  CountryLocalization("um", "ئینگیلیسی", "U.S. Outlying Islands"),
  CountryLocalization("vi", "ئینگیلیسی", "U.S. Virgin Islands"),
  CountryLocalization("ug", "سأڤاحیلی", "Uganda"),
  CountryLocalization("ua", "ئوکراینی", "Ukraine"),
  CountryLocalization("ae", "أرأڤی", "United Arab Emirates"),
  CountryLocalization("gb", "ئینگیلیسی", "بیریتانیا گأپ"),
  CountryLocalization("us", "لاکوٙتا", "ڤولاتیا یأکاگئرتە"),
  CountryLocalization("uy", "ئسپانیایی", "Uruguay"),
  CountryLocalization("uz", "ئوزبأکی", "Uzbekistan"),
  CountryLocalization("vu", "فآرانسئ ئی", "Vanuatu"),
  CountryLocalization("va", "ئیتالیایی", "Vatican City"),
  CountryLocalization("ve", "ئسپانیایی", "Venezuela"),
  CountryLocalization("vn", "ڤییئتنامی", "Vietnam"),
  CountryLocalization("wf", "فآرانسئ ئی", "Wallis & Futuna"),
  CountryLocalization("eh", "أرأڤی", "Western Sahara"),
  CountryLocalization("ye", "أرأڤی", "Yemen"),
  CountryLocalization("zm", "ئینگیلیسی", "Zambia"),
  CountryLocalization("zw", "نئدئبئلئ شومالی", "Zimbabwe"),
  CountryLocalization("ax", "سوٙئدی", "Åland Islands"),
)
