/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot.atlas.extended

import dev.teogor.xenoglot.atlas.CountryLocalization
import kotlin.collections.List

/**
 * Holds the internal list of country-language mappings used for lookups within the package for
 * language code ca.
 *
 * This property contains a hardcoded list of [CountryLocalization] objects, each representing
 * a country and its associated official languages. This list is used by [CountryLanguageRegistry]
 * to provide access to country-language data and should not be modified directly.
 *
 * @see CountryLocalization
 * @see CountryLanguageRegistry
 */
internal val _countryLanguageMappings_ca: List<CountryLocalization> = listOf(
  CountryLocalization("af", "persa", "Afganistan"),
  CountryLocalization("al", "albanès", "Albània"),
  CountryLocalization("dz", "francès", "Algèria"),
  CountryLocalization("as", "anglès", "Samoa Nord-americana"),
  CountryLocalization("ad", "català", "Andorra"),
  CountryLocalization("ao", "lingala", "Angola"),
  CountryLocalization("ai", "anglès", "Anguilla"),
  CountryLocalization("ag", "anglès", "Antigua i Barbuda"),
  CountryLocalization("ar", "espanyol", "Argentina"),
  CountryLocalization("am", "armeni", "Armènia"),
  CountryLocalization("aw", "neerlandès", "Aruba"),
  CountryLocalization("au", "anglès", "Austràlia"),
  CountryLocalization("at", "anglès", "Àustria"),
  CountryLocalization("az", "àzeri", "Azerbaidjan"),
  CountryLocalization("bs", "anglès", "Bahames"),
  CountryLocalization("bh", "àrab", "Bahrain"),
  CountryLocalization("bd", "bengalí", "Bangla Desh"),
  CountryLocalization("bb", "anglès", "Barbados"),
  CountryLocalization("by", "bielorús", "Belarús"),
  CountryLocalization("be", "francès", "Bèlgica"),
  CountryLocalization("bz", "anglès", "Belize"),
  CountryLocalization("bj", "francès", "Benín"),
  CountryLocalization("bm", "anglès", "Bermudes"),
  CountryLocalization("bt", "dzongka", "Bhutan"),
  CountryLocalization("bo", "espanyol", "Bolívia"),
  CountryLocalization("ba", "bosnià", "Bòsnia i Hercegovina"),
  CountryLocalization("bw", "anglès", "Botswana"),
  CountryLocalization("br", "portuguès", "Brasil"),
  CountryLocalization("io", "anglès", "Territori Britànic de l’Oceà Índic"),
  CountryLocalization("vg", "anglès", "Illes Verges Britàniques"),
  CountryLocalization("bn", "malai", "Brunei"),
  CountryLocalization("bg", "búlgar", "Bulgària"),
  CountryLocalization("bf", "francès", "Burkina Faso"),
  CountryLocalization("bi", "francès", "Burundi"),
  CountryLocalization("kh", "khmer", "Cambodja"),
  CountryLocalization("cm", "basa", "Camerun"),
  CountryLocalization("ca", "francès", "Canadà"),
  CountryLocalization("ic", "espanyol", "Illes Canàries"),
  CountryLocalization("cv", "crioll capverdià", "Cap Verd"),
  CountryLocalization("bq", "neerlandès", "Carib Neerlandès"),
  CountryLocalization("ky", "anglès", "Illes Caiman"),
  CountryLocalization("cf", "lingala", "República Centreafricana"),
  CountryLocalization("ea", "espanyol", "Ceuta i Melilla"),
  CountryLocalization("td", "àrab", "Txad"),
  CountryLocalization("cl", "espanyol", "Xile"),
  CountryLocalization("cn", "tibetà", "Xina"),
  CountryLocalization("cx", "anglès", "Illa Christmas"),
  CountryLocalization("cc", "anglès", "Illes Cocos"),
  CountryLocalization("co", "espanyol", "Colòmbia"),
  CountryLocalization("km", "àrab", "Comores"),
  CountryLocalization("cg", "lingala", "Congo - Brazzaville"),
  CountryLocalization("cd", "suahili", "Congo - Kinshasa"),
  CountryLocalization("ck", "anglès", "Illes Cook"),
  CountryLocalization("cr", "espanyol", "Costa Rica"),
  CountryLocalization("hr", "croat", "Croàcia"),
  CountryLocalization("cu", "espanyol", "Cuba"),
  CountryLocalization("cw", "neerlandès", "Curaçao"),
  CountryLocalization("cy", "anglès", "Xipre"),
  CountryLocalization("cz", "txec", "Txèquia"),
  CountryLocalization("ci", "francès", "Costa d’Ivori"),
  CountryLocalization("dk", "anglès", "Dinamarca"),
  CountryLocalization("dg", "anglès", "Diego Garcia"),
  CountryLocalization("dj", "francès", "Djibouti"),
  CountryLocalization("dm", "anglès", "Dominica"),
  CountryLocalization("do", "espanyol", "República Dominicana"),
  CountryLocalization("ec", "quítxua", "Equador"),
  CountryLocalization("eg", "àrab", "Egipte"),
  CountryLocalization("sv", "espanyol", "El Salvador"),
  CountryLocalization("gq", "espanyol", "Guinea Equatorial"),
  CountryLocalization("er", "tigrinya", "Eritrea"),
  CountryLocalization("ee", "estonià", "Estònia"),
  CountryLocalization("et", "amhàric", "Etiòpia"),
  CountryLocalization("fk", "anglès", "Illes Malvines"),
  CountryLocalization("fo", "feroès", "Illes Fèroe"),
  CountryLocalization("fj", "anglès", "Fiji"),
  CountryLocalization("fi", "suec", "Finlàndia"),
  CountryLocalization("fr", "alemany suís", "França"),
  CountryLocalization("gf", "francès", "Guaiana Francesa"),
  CountryLocalization("pf", "francès", "Polinèsia Francesa"),
  CountryLocalization("ga", "francès", "Gabon"),
  CountryLocalization("gm", "anglès", "Gàmbia"),
  CountryLocalization("ge", "osseta", "Geòrgia"),
  CountryLocalization("de", "baix sòrab", "Alemanya"),
  CountryLocalization("gh", "anglès", "Ghana"),
  CountryLocalization("gi", "anglès", "Gibraltar"),
  CountryLocalization("gr", "grec", "Grècia"),
  CountryLocalization("gl", "grenlandès", "Grenlàndia"),
  CountryLocalization("gd", "anglès", "Grenada"),
  CountryLocalization("gp", "francès", "Guadeloupe"),
  CountryLocalization("gu", "anglès", "Guam"),
  CountryLocalization("gt", "espanyol", "Guatemala"),
  CountryLocalization("gg", "anglès", "Guernsey"),
  CountryLocalization("gn", "francès", "Guinea"),
  CountryLocalization("gw", "portuguès", "Guinea Bissau"),
  CountryLocalization("gy", "anglès", "Guyana"),
  CountryLocalization("ht", "francès", "Haití"),
  CountryLocalization("hn", "espanyol", "Hondures"),
  CountryLocalization("hk", "xinès", "Hong Kong (RAE Xina)"),
  CountryLocalization("hu", "hongarès", "Hongria"),
  CountryLocalization("is", "islandès", "Islàndia"),
  CountryLocalization("in", "nepalès", "Índia"),
  CountryLocalization("id", "indonesi", "Indonèsia"),
  CountryLocalization("ir", "persa", "Iran"),
  CountryLocalization("iq", "luri septentrional", "Iraq"),
  CountryLocalization("ie", "anglès", "Irlanda"),
  CountryLocalization("im", "manx", "Illa de Man"),
  CountryLocalization("il", "anglès", "Israel"),
  CountryLocalization("it", "alemany", "Itàlia"),
  CountryLocalization("jm", "anglès", "Jamaica"),
  CountryLocalization("jp", "japonès", "Japó"),
  CountryLocalization("je", "anglès", "Jersey"),
  CountryLocalization("jo", "àrab", "Jordània"),
  CountryLocalization("kz", "kazakh", "Kazakhstan"),
  CountryLocalization("ke", "somali", "Kenya"),
  CountryLocalization("ki", "anglès", "Kiribati"),
  CountryLocalization("xk", "serbi", "Kosovo"),
  CountryLocalization("kw", "àrab", "Kuwait"),
  CountryLocalization("kg", "rus", "Kirguizistan"),
  CountryLocalization("la", "laosià", "Laos"),
  CountryLocalization("lv", "letó", "Letònia"),
  CountryLocalization("lb", "àrab", "Líban"),
  CountryLocalization("ls", "anglès", "Lesotho"),
  CountryLocalization("lr", "anglès", "Libèria"),
  CountryLocalization("ly", "àrab", "Líbia"),
  CountryLocalization("li", "alemany suís", "Liechtenstein"),
  CountryLocalization("lt", "lituà", "Lituània"),
  CountryLocalization("lu", "luxemburguès", "Luxemburg"),
  CountryLocalization("mo", "portuguès", "Macau (RAE Xina)"),
  CountryLocalization("mk", "albanès", "Macedònia"),
  CountryLocalization("mg", "francès", "Madagascar"),
  CountryLocalization("mw", "anglès", "Malawi"),
  CountryLocalization("my", "tàmil", "Malàisia"),
  CountryLocalization("ml", "francès", "Mali"),
  CountryLocalization("mt", "anglès", "Malta"),
  CountryLocalization("mh", "anglès", "Illes Marshall"),
  CountryLocalization("mq", "francès", "Martinica"),
  CountryLocalization("mr", "àrab", "Mauritània"),
  CountryLocalization("mu", "mauricià", "Maurici"),
  CountryLocalization("yt", "francès", "Mayotte"),
  CountryLocalization("mx", "espanyol", "Mèxic"),
  CountryLocalization("fm", "anglès", "Micronèsia"),
  CountryLocalization("md", "rus", "Moldàvia"),
  CountryLocalization("mc", "francès", "Mònaco"),
  CountryLocalization("mn", "mongol", "Mongòlia"),
  CountryLocalization("me", "serbi", "Montenegro"),
  CountryLocalization("ms", "anglès", "Montserrat"),
  CountryLocalization("ma", "amazic del Marroc central", "Marroc"),
  CountryLocalization("mz", "makhuwa-metto", "Moçambic"),
  CountryLocalization("mm", "birmà", "Myanmar (Birmània)"),
  CountryLocalization("na", "anglès", "Namíbia"),
  CountryLocalization("nr", "anglès", "Nauru"),
  CountryLocalization("np", "nepalès", "Nepal"),
  CountryLocalization("nl", "anglès", "Països Baixos"),
  CountryLocalization("nc", "francès", "Nova Caledònia"),
  CountryLocalization("nz", "anglès", "Nova Zelanda"),
  CountryLocalization("ni", "espanyol", "Nicaragua"),
  CountryLocalization("ne", "haussa", "Níger"),
  CountryLocalization("ng", "haussa", "Nigèria"),
  CountryLocalization("nu", "anglès", "Niue"),
  CountryLocalization("nf", "anglès", "Norfolk"),
  CountryLocalization("kp", "coreà", "Corea del Nord"),
  CountryLocalization("mp", "anglès", "Illes Mariannes del Nord"),
  CountryLocalization("no", "sami septentrional", "Noruega"),
  CountryLocalization("om", "àrab", "Oman"),
  CountryLocalization("pk", "anglès", "Pakistan"),
  CountryLocalization("pw", "anglès", "Palau"),
  CountryLocalization("ps", "àrab", "territoris palestins"),
  CountryLocalization("pa", "espanyol", "Panamà"),
  CountryLocalization("pg", "anglès", "Papua Nova Guinea"),
  CountryLocalization("py", "espanyol", "Paraguai"),
  CountryLocalization("pe", "espanyol", "Perú"),
  CountryLocalization("ph", "filipí", "Filipines"),
  CountryLocalization("pn", "anglès", "Illes Pitcairn"),
  CountryLocalization("pl", "polonès", "Polònia"),
  CountryLocalization("pt", "portuguès", "Portugal"),
  CountryLocalization("pr", "anglès", "Puerto Rico"),
  CountryLocalization("qa", "àrab", "Qatar"),
  CountryLocalization("ro", "romanès", "Romania"),
  CountryLocalization("ru", "tàtar", "Rússia"),
  CountryLocalization("rw", "anglès", "Ruanda"),
  CountryLocalization("re", "francès", "Illa de la Reunió"),
  CountryLocalization("ws", "anglès", "Samoa"),
  CountryLocalization("sm", "italià", "San Marino"),
  CountryLocalization("sa", "àrab", "Aràbia Saudita"),
  CountryLocalization("sn", "francès", "Senegal"),
  CountryLocalization("rs", "serbi", "Sèrbia"),
  CountryLocalization("cs", "serbi", "Serbia and Montenegro"),
  CountryLocalization("sc", "francès", "Seychelles"),
  CountryLocalization("sl", "anglès", "Sierra Leone"),
  CountryLocalization("sg", "tàmil", "Singapur"),
  CountryLocalization("sx", "anglès", "Sint Maarten"),
  CountryLocalization("sk", "eslovac", "Eslovàquia"),
  CountryLocalization("si", "eslovè", "Eslovènia"),
  CountryLocalization("sb", "anglès", "Illes Salomó"),
  CountryLocalization("so", "àrab", "Somàlia"),
  CountryLocalization("za", "anglès", "República de Sud-àfrica"),
  CountryLocalization("kr", "coreà", "Corea del Sud"),
  CountryLocalization("ss", "nuer", "Sudan del Sud"),
  CountryLocalization("es", "espanyol", "Espanya"),
  CountryLocalization("lk", "tàmil", "Sri Lanka"),
  CountryLocalization("bl", "francès", "Saint Barthélemy"),
  CountryLocalization("sh", "anglès", "Saint Helena"),
  CountryLocalization("kn", "anglès", "Saint Christopher i Nevis"),
  CountryLocalization("lc", "anglès", "Saint Lucia"),
  CountryLocalization("mf", "francès", "Saint Martin"),
  CountryLocalization("pm", "francès", "Saint-Pierre-et-Miquelon"),
  CountryLocalization("vc", "anglès", "Saint Vincent i les Grenadines"),
  CountryLocalization("sd", "àrab", "Sudan"),
  CountryLocalization("sr", "neerlandès", "Surinam"),
  CountryLocalization("sj", "noruec bokmål", "Svalbard i Jan Mayen"),
  CountryLocalization("sz", "anglès", "Swazilàndia"),
  CountryLocalization("se", "suec", "Suècia"),
  CountryLocalization("ch", "alemany suís", "Suïssa"),
  CountryLocalization("sy", "àrab", "Síria"),
  CountryLocalization("st", "portuguès", "São Tomé i Príncipe"),
  CountryLocalization("tw", "xinès", "Taiwan"),
  CountryLocalization("tj", "tadjik", "Tadjikistan"),
  CountryLocalization("tz", "makonde", "Tanzània"),
  CountryLocalization("th", "tai", "Tailàndia"),
  CountryLocalization("tl", "portuguès", "Timor Oriental"),
  CountryLocalization("tg", "francès", "Togo"),
  CountryLocalization("tk", "anglès", "Tokelau"),
  CountryLocalization("to", "tongalès", "Tonga"),
  CountryLocalization("tt", "anglès", "Trinitat i Tobago"),
  CountryLocalization("tn", "francès", "Tunísia"),
  CountryLocalization("tr", "turc", "Turquia"),
  CountryLocalization("tm", "turcman", "Turkmenistan"),
  CountryLocalization("tc", "anglès", "Illes Turks i Caicos"),
  CountryLocalization("tv", "anglès", "Tuvalu"),
  CountryLocalization("um", "anglès", "Illes Perifèriques Menors dels EUA"),
  CountryLocalization("vi", "anglès", "Illes Verges Nord-americanes"),
  CountryLocalization("ug", "suahili", "Uganda"),
  CountryLocalization("ua", "ucraïnès", "Ucraïna"),
  CountryLocalization("ae", "àrab", "Emirats Àrabs Units"),
  CountryLocalization("gb", "anglès", "Regne Unit"),
  CountryLocalization("us", "lakota", "Estats Units"),
  CountryLocalization("uy", "espanyol", "Uruguai"),
  CountryLocalization("uz", "uzbek", "Uzbekistan"),
  CountryLocalization("vu", "francès", "Vanuatu"),
  CountryLocalization("va", "italià", "Ciutat del Vaticà"),
  CountryLocalization("ve", "espanyol", "Veneçuela"),
  CountryLocalization("vn", "vietnamita", "Vietnam"),
  CountryLocalization("wf", "francès", "Wallis i Futuna"),
  CountryLocalization("eh", "àrab", "Sàhara Occidental"),
  CountryLocalization("ye", "àrab", "Iemen"),
  CountryLocalization("zm", "anglès", "Zàmbia"),
  CountryLocalization("zw", "ndebele septentrional", "Zimbàbue"),
  CountryLocalization("ax", "suec", "Illes Åland"),
)
