/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot.atlas.extended

import dev.teogor.xenoglot.atlas.CountryLocalization
import kotlin.collections.List

/**
 * Holds the internal list of country-language mappings used for lookups within the package for
 * language code lv.
 *
 * This property contains a hardcoded list of [CountryLocalization] objects, each representing
 * a country and its associated official languages. This list is used by [CountryLanguageRegistry]
 * to provide access to country-language data and should not be modified directly.
 *
 * @see CountryLocalization
 * @see CountryLanguageRegistry
 */
internal val _countryLanguageMappings_lv: List<CountryLocalization> = listOf(
  CountryLocalization("af", "persiešu", "Afganistāna"),
  CountryLocalization("al", "albāņu", "Albānija"),
  CountryLocalization("dz", "franču", "Alžīrija"),
  CountryLocalization("as", "angļu", "ASV Samoa"),
  CountryLocalization("ad", "katalāņu", "Andora"),
  CountryLocalization("ao", "lingala", "Angola"),
  CountryLocalization("ai", "angļu", "Angilja"),
  CountryLocalization("ag", "angļu", "Antigva un Barbuda"),
  CountryLocalization("ar", "spāņu", "Argentīna"),
  CountryLocalization("am", "armēņu", "Armēnija"),
  CountryLocalization("aw", "holandiešu", "Aruba"),
  CountryLocalization("au", "angļu", "Austrālija"),
  CountryLocalization("at", "angļu", "Austrija"),
  CountryLocalization("az", "azerbaidžāņu", "Azerbaidžāna"),
  CountryLocalization("bs", "angļu", "Bahamu salas"),
  CountryLocalization("bh", "arābu", "Bahreina"),
  CountryLocalization("bd", "bengāļu", "Bangladeša"),
  CountryLocalization("bb", "angļu", "Barbadosa"),
  CountryLocalization("by", "baltkrievu", "Baltkrievija"),
  CountryLocalization("be", "franču", "Beļģija"),
  CountryLocalization("bz", "angļu", "Beliza"),
  CountryLocalization("bj", "franču", "Benina"),
  CountryLocalization("bm", "angļu", "Bermudu salas"),
  CountryLocalization("bt", "dzongke", "Butāna"),
  CountryLocalization("bo", "spāņu", "Bolīvija"),
  CountryLocalization("ba", "bosniešu", "Bosnija un Hercegovina"),
  CountryLocalization("bw", "angļu", "Botsvāna"),
  CountryLocalization("br", "portugāļu", "Brazīlija"),
  CountryLocalization("io", "angļu", "Indijas okeāna Britu teritorija"),
  CountryLocalization("vg", "angļu", "Britu Virdžīnas"),
  CountryLocalization("bn", "malajiešu", "Bruneja"),
  CountryLocalization("bg", "bulgāru", "Bulgārija"),
  CountryLocalization("bf", "franču", "Burkinafaso"),
  CountryLocalization("bi", "franču", "Burundija"),
  CountryLocalization("kh", "khmeru", "Kambodža"),
  CountryLocalization("cm", "basu", "Kamerūna"),
  CountryLocalization("ca", "franču", "Kanāda"),
  CountryLocalization("ic", "spāņu", "Kanāriju salas"),
  CountryLocalization("cv", "kaboverdiešu", "Kaboverde"),
  CountryLocalization("bq", "holandiešu", "Nīderlandes Karību salas"),
  CountryLocalization("ky", "angļu", "Kaimanu salas"),
  CountryLocalization("cf", "lingala", "Centrālāfrikas Republika"),
  CountryLocalization("ea", "spāņu", "Seūta un Melilja"),
  CountryLocalization("td", "arābu", "Čada"),
  CountryLocalization("cl", "spāņu", "Čīle"),
  CountryLocalization("cn", "tibetiešu", "Ķīna"),
  CountryLocalization("cx", "angļu", "Ziemsvētku sala"),
  CountryLocalization("cc", "angļu", "Kokosu (Kīlinga) salas"),
  CountryLocalization("co", "spāņu", "Kolumbija"),
  CountryLocalization("km", "arābu", "Komoru salas"),
  CountryLocalization("cg", "lingala", "Kongo (Brazavila)"),
  CountryLocalization("cd", "svahili", "Kongo (Kinšasa)"),
  CountryLocalization("ck", "angļu", "Kuka salas"),
  CountryLocalization("cr", "spāņu", "Kostarika"),
  CountryLocalization("hr", "horvātu", "Horvātija"),
  CountryLocalization("cu", "spāņu", "Kuba"),
  CountryLocalization("cw", "holandiešu", "Kirasao"),
  CountryLocalization("cy", "angļu", "Kipra"),
  CountryLocalization("cz", "čehu", "Čehija"),
  CountryLocalization("ci", "franču", "Kotdivuāra"),
  CountryLocalization("dk", "angļu", "Dānija"),
  CountryLocalization("dg", "angļu", "Djego Garsijas atols"),
  CountryLocalization("dj", "franču", "Džibutija"),
  CountryLocalization("dm", "angļu", "Dominika"),
  CountryLocalization("do", "spāņu", "Dominikāna"),
  CountryLocalization("ec", "kečvu", "Ekvadora"),
  CountryLocalization("eg", "arābu", "Ēģipte"),
  CountryLocalization("sv", "spāņu", "Salvadora"),
  CountryLocalization("gq", "spāņu", "Ekvatoriālā Gvineja"),
  CountryLocalization("er", "tigrinja", "Eritreja"),
  CountryLocalization("ee", "igauņu", "Igaunija"),
  CountryLocalization("et", "amharu", "Etiopija"),
  CountryLocalization("fk", "angļu", "Folklenda salas"),
  CountryLocalization("fo", "fēru", "Fēru salas"),
  CountryLocalization("fj", "angļu", "Fidži"),
  CountryLocalization("fi", "zviedru", "Somija"),
  CountryLocalization("fr", "Šveices vācu", "Francija"),
  CountryLocalization("gf", "franču", "Francijas Gviāna"),
  CountryLocalization("pf", "franču", "Francijas Polinēzija"),
  CountryLocalization("ga", "franču", "Gabona"),
  CountryLocalization("gm", "angļu", "Gambija"),
  CountryLocalization("ge", "osetīnu", "Gruzija"),
  CountryLocalization("de", "lejassorbu", "Vācija"),
  CountryLocalization("gh", "angļu", "Gana"),
  CountryLocalization("gi", "angļu", "Gibraltārs"),
  CountryLocalization("gr", "grieķu", "Grieķija"),
  CountryLocalization("gl", "grenlandiešu", "Grenlande"),
  CountryLocalization("gd", "angļu", "Grenāda"),
  CountryLocalization("gp", "franču", "Gvadelupa"),
  CountryLocalization("gu", "angļu", "Guama"),
  CountryLocalization("gt", "spāņu", "Gvatemala"),
  CountryLocalization("gg", "angļu", "Gērnsija"),
  CountryLocalization("gn", "franču", "Gvineja"),
  CountryLocalization("gw", "portugāļu", "Gvineja-Bisava"),
  CountryLocalization("gy", "angļu", "Gajāna"),
  CountryLocalization("ht", "franču", "Haiti"),
  CountryLocalization("hn", "spāņu", "Hondurasa"),
  CountryLocalization("hk", "ķīniešu", "Ķīnas īpašās pārvaldes apgabals Honkonga"),
  CountryLocalization("hu", "ungāru", "Ungārija"),
  CountryLocalization("is", "islandiešu", "Islande"),
  CountryLocalization("in", "nepāliešu", "Indija"),
  CountryLocalization("id", "Indonesian", "Indonēzija"),
  CountryLocalization("ir", "persiešu", "Irāna"),
  CountryLocalization("iq", "ziemeļluru", "Irāka"),
  CountryLocalization("ie", "angļu", "Īrija"),
  CountryLocalization("im", "meniešu", "Mena"),
  CountryLocalization("il", "angļu", "Izraēla"),
  CountryLocalization("it", "vācu", "Itālija"),
  CountryLocalization("jm", "angļu", "Jamaika"),
  CountryLocalization("jp", "japāņu", "Japāna"),
  CountryLocalization("je", "angļu", "Džērsija"),
  CountryLocalization("jo", "arābu", "Jordānija"),
  CountryLocalization("kz", "kazahu", "Kazahstāna"),
  CountryLocalization("ke", "somāļu", "Kenija"),
  CountryLocalization("ki", "angļu", "Kiribati"),
  CountryLocalization("xk", "serbu", "Kosova"),
  CountryLocalization("kw", "arābu", "Kuveita"),
  CountryLocalization("kg", "krievu", "Kirgizstāna"),
  CountryLocalization("la", "laosiešu", "Laosa"),
  CountryLocalization("lv", "latviešu", "Latvija"),
  CountryLocalization("lb", "arābu", "Libāna"),
  CountryLocalization("ls", "angļu", "Lesoto"),
  CountryLocalization("lr", "angļu", "Libērija"),
  CountryLocalization("ly", "arābu", "Lībija"),
  CountryLocalization("li", "Šveices vācu", "Lihtenšteina"),
  CountryLocalization("lt", "lietuviešu", "Lietuva"),
  CountryLocalization("lu", "luksemburgiešu", "Luksemburga"),
  CountryLocalization("mo", "portugāļu", "Ķīnas īpašās pārvaldes apgabals Makao"),
  CountryLocalization("mk", "albāņu", "Maķedonija"),
  CountryLocalization("mg", "franču", "Madagaskara"),
  CountryLocalization("mw", "angļu", "Malāvija"),
  CountryLocalization("my", "tamilu", "Malaizija"),
  CountryLocalization("ml", "franču", "Mali"),
  CountryLocalization("mt", "angļu", "Malta"),
  CountryLocalization("mh", "angļu", "Māršala salas"),
  CountryLocalization("mq", "franču", "Martinika"),
  CountryLocalization("mr", "arābu", "Mauritānija"),
  CountryLocalization("mu", "Maurīcijas kreolu", "Maurīcija"),
  CountryLocalization("yt", "franču", "Majota"),
  CountryLocalization("mx", "spāņu", "Meksika"),
  CountryLocalization("fm", "angļu", "Mikronēzija"),
  CountryLocalization("md", "krievu", "Moldova"),
  CountryLocalization("mc", "franču", "Monako"),
  CountryLocalization("mn", "mongoļu", "Mongolija"),
  CountryLocalization("me", "serbu", "Melnkalne"),
  CountryLocalization("ms", "angļu", "Montserrata"),
  CountryLocalization("ma", "Centrālmarokas tamazīts", "Maroka"),
  CountryLocalization("mz", "makua", "Mozambika"),
  CountryLocalization("mm", "birmiešu", "Mjanma (Birma)"),
  CountryLocalization("na", "angļu", "Namībija"),
  CountryLocalization("nr", "angļu", "Nauru"),
  CountryLocalization("np", "nepāliešu", "Nepāla"),
  CountryLocalization("nl", "angļu", "Nīderlande"),
  CountryLocalization("nc", "franču", "Jaunkaledonija"),
  CountryLocalization("nz", "angļu", "Jaunzēlande"),
  CountryLocalization("ni", "spāņu", "Nikaragva"),
  CountryLocalization("ne", "hausu", "Nigēra"),
  CountryLocalization("ng", "hausu", "Nigērija"),
  CountryLocalization("nu", "angļu", "Niue"),
  CountryLocalization("nf", "angļu", "Norfolkas sala"),
  CountryLocalization("kp", "korejiešu", "Ziemeļkoreja"),
  CountryLocalization("mp", "angļu", "Ziemeļu Marianas salas"),
  CountryLocalization("no", "ziemeļsāmu", "Norvēģija"),
  CountryLocalization("om", "arābu", "Omāna"),
  CountryLocalization("pk", "angļu", "Pakistāna"),
  CountryLocalization("pw", "angļu", "Palau"),
  CountryLocalization("ps", "arābu", "Palestīna"),
  CountryLocalization("pa", "spāņu", "Panama"),
  CountryLocalization("pg", "angļu", "Papua-Jaungvineja"),
  CountryLocalization("py", "spāņu", "Paragvaja"),
  CountryLocalization("pe", "spāņu", "Peru"),
  CountryLocalization("ph", "filipīniešu", "Filipīnas"),
  CountryLocalization("pn", "angļu", "Pitkērnas salas"),
  CountryLocalization("pl", "poļu", "Polija"),
  CountryLocalization("pt", "portugāļu", "Portugāle"),
  CountryLocalization("pr", "angļu", "Puertoriko"),
  CountryLocalization("qa", "arābu", "Katara"),
  CountryLocalization("ro", "rumāņu", "Rumānija"),
  CountryLocalization("ru", "tatāru", "Krievija"),
  CountryLocalization("rw", "angļu", "Ruanda"),
  CountryLocalization("re", "franču", "Reinjona"),
  CountryLocalization("ws", "angļu", "Samoa"),
  CountryLocalization("sm", "itāļu", "Sanmarīno"),
  CountryLocalization("sa", "arābu", "Saūda Arābija"),
  CountryLocalization("sn", "franču", "Senegāla"),
  CountryLocalization("rs", "serbu", "Serbija"),
  CountryLocalization("cs", "serbu", "Serbia and Montenegro"),
  CountryLocalization("sc", "franču", "Seišelu salas"),
  CountryLocalization("sl", "angļu", "Sjerraleone"),
  CountryLocalization("sg", "tamilu", "Singapūra"),
  CountryLocalization("sx", "angļu", "Sintmārtena"),
  CountryLocalization("sk", "slovāku", "Slovākija"),
  CountryLocalization("si", "slovēņu", "Slovēnija"),
  CountryLocalization("sb", "angļu", "Zālamana salas"),
  CountryLocalization("so", "arābu", "Somālija"),
  CountryLocalization("za", "angļu", "Dienvidāfrikas Republika"),
  CountryLocalization("kr", "korejiešu", "Dienvidkoreja"),
  CountryLocalization("ss", "nueru", "Dienvidsudāna"),
  CountryLocalization("es", "spāņu", "Spānija"),
  CountryLocalization("lk", "tamilu", "Šrilanka"),
  CountryLocalization("bl", "franču", "Senbartelmī"),
  CountryLocalization("sh", "angļu", "Sv.Helēnas sala"),
  CountryLocalization("kn", "angļu", "Sentkitsa un Nevisa"),
  CountryLocalization("lc", "angļu", "Sentlūsija"),
  CountryLocalization("mf", "franču", "Senmartēna"),
  CountryLocalization("pm", "franču", "Senpjēra un Mikelona"),
  CountryLocalization("vc", "angļu", "Sentvinsenta un Grenadīnas"),
  CountryLocalization("sd", "arābu", "Sudāna"),
  CountryLocalization("sr", "holandiešu", "Surinama"),
  CountryLocalization("sj", "norvēģu bukmols", "Svalbāra un Jana Majena sala"),
  CountryLocalization("sz", "angļu", "Svazilenda"),
  CountryLocalization("se", "zviedru", "Zviedrija"),
  CountryLocalization("ch", "Šveices vācu", "Šveice"),
  CountryLocalization("sy", "arābu", "Sīrija"),
  CountryLocalization("st", "portugāļu", "Santome un Prinsipi"),
  CountryLocalization("tw", "ķīniešu", "Taivāna"),
  CountryLocalization("tj", "tadžiku", "Tadžikistāna"),
  CountryLocalization("tz", "makonde", "Tanzānija"),
  CountryLocalization("th", "taju", "Taizeme"),
  CountryLocalization("tl", "portugāļu", "Austrumtimora"),
  CountryLocalization("tg", "franču", "Togo"),
  CountryLocalization("tk", "angļu", "Tokelau"),
  CountryLocalization("to", "tongiešu", "Tonga"),
  CountryLocalization("tt", "angļu", "Trinidāda un Tobāgo"),
  CountryLocalization("tn", "franču", "Tunisija"),
  CountryLocalization("tr", "turku", "Turcija"),
  CountryLocalization("tm", "turkmēņu", "Turkmenistāna"),
  CountryLocalization("tc", "angļu", "Tērksas un Kaikosas salas"),
  CountryLocalization("tv", "angļu", "Tuvalu"),
  CountryLocalization("um", "angļu", "ASV Mazās Aizjūras salas"),
  CountryLocalization("vi", "angļu", "ASV Virdžīnas"),
  CountryLocalization("ug", "svahili", "Uganda"),
  CountryLocalization("ua", "ukraiņu", "Ukraina"),
  CountryLocalization("ae", "arābu", "Apvienotie Arābu Emirāti"),
  CountryLocalization("gb", "angļu", "Lielbritānija"),
  CountryLocalization("us", "lakotu", "Amerikas Savienotās Valstis"),
  CountryLocalization("uy", "spāņu", "Urugvaja"),
  CountryLocalization("uz", "uzbeku", "Uzbekistāna"),
  CountryLocalization("vu", "franču", "Vanuatu"),
  CountryLocalization("va", "itāļu", "Vatikāns"),
  CountryLocalization("ve", "spāņu", "Venecuēla"),
  CountryLocalization("vn", "vjetnamiešu", "Vjetnama"),
  CountryLocalization("wf", "franču", "Volisa un Futunas salas"),
  CountryLocalization("eh", "arābu", "Rietumsahāra"),
  CountryLocalization("ye", "arābu", "Jemena"),
  CountryLocalization("zm", "angļu", "Zambija"),
  CountryLocalization("zw", "ziemeļndebelu", "Zimbabve"),
  CountryLocalization("ax", "zviedru", "Olandes salas"),
)
