/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot.atlas.extended

import dev.teogor.xenoglot.atlas.CountryLocalization
import kotlin.collections.List

/**
 * Holds the internal list of country-language mappings used for lookups within the package for
 * language code nl.
 *
 * This property contains a hardcoded list of [CountryLocalization] objects, each representing
 * a country and its associated official languages. This list is used by [CountryLanguageRegistry]
 * to provide access to country-language data and should not be modified directly.
 *
 * @see CountryLocalization
 * @see CountryLanguageRegistry
 */
internal val _countryLanguageMappings_nl: List<CountryLocalization> = listOf(
  CountryLocalization("af", "Perzisch", "Afghanistan"),
  CountryLocalization("al", "Albanees", "Albanië"),
  CountryLocalization("dz", "Frans", "Algerije"),
  CountryLocalization("as", "Engels", "Amerikaans-Samoa"),
  CountryLocalization("ad", "Catalaans", "Andorra"),
  CountryLocalization("ao", "Lingala", "Angola"),
  CountryLocalization("ai", "Engels", "Anguilla"),
  CountryLocalization("ag", "Engels", "Antigua en Barbuda"),
  CountryLocalization("ar", "Spaans", "Argentinië"),
  CountryLocalization("am", "Armeens", "Armenië"),
  CountryLocalization("aw", "Nederlands", "Aruba"),
  CountryLocalization("au", "Engels", "Australië"),
  CountryLocalization("at", "Engels", "Oostenrijk"),
  CountryLocalization("az", "Azerbeidzjaans", "Azerbeidzjan"),
  CountryLocalization("bs", "Engels", "Bahama’s"),
  CountryLocalization("bh", "Arabisch", "Bahrein"),
  CountryLocalization("bd", "Bengaals", "Bangladesh"),
  CountryLocalization("bb", "Engels", "Barbados"),
  CountryLocalization("by", "Wit-Russisch", "Belarus"),
  CountryLocalization("be", "Frans", "België"),
  CountryLocalization("bz", "Engels", "Belize"),
  CountryLocalization("bj", "Frans", "Benin"),
  CountryLocalization("bm", "Engels", "Bermuda"),
  CountryLocalization("bt", "Dzongkha", "Bhutan"),
  CountryLocalization("bo", "Spaans", "Bolivia"),
  CountryLocalization("ba", "Bosnisch", "Bosnië en Herzegovina"),
  CountryLocalization("bw", "Engels", "Botswana"),
  CountryLocalization("br", "Portugees", "Brazilië"),
  CountryLocalization("io", "Engels", "Brits Indische Oceaanterritorium"),
  CountryLocalization("vg", "Engels", "Britse Maagdeneilanden"),
  CountryLocalization("bn", "Maleis", "Brunei"),
  CountryLocalization("bg", "Bulgaars", "Bulgarije"),
  CountryLocalization("bf", "Frans", "Burkina Faso"),
  CountryLocalization("bi", "Frans", "Burundi"),
  CountryLocalization("kh", "Khmer", "Cambodja"),
  CountryLocalization("cm", "Basa", "Kameroen"),
  CountryLocalization("ca", "Frans", "Canada"),
  CountryLocalization("ic", "Spaans", "Canarische Eilanden"),
  CountryLocalization("cv", "Kaapverdisch Creools", "Kaapverdië"),
  CountryLocalization("bq", "Nederlands", "Caribisch Nederland"),
  CountryLocalization("ky", "Engels", "Kaaimaneilanden"),
  CountryLocalization("cf", "Lingala", "Centraal-Afrikaanse Republiek"),
  CountryLocalization("ea", "Spaans", "Ceuta en Melilla"),
  CountryLocalization("td", "Arabisch", "Tsjaad"),
  CountryLocalization("cl", "Spaans", "Chili"),
  CountryLocalization("cn", "Tibetaans", "China"),
  CountryLocalization("cx", "Engels", "Christmaseiland"),
  CountryLocalization("cc", "Engels", "Cocoseilanden"),
  CountryLocalization("co", "Spaans", "Colombia"),
  CountryLocalization("km", "Arabisch", "Comoren"),
  CountryLocalization("cg", "Lingala", "Congo-Brazzaville"),
  CountryLocalization("cd", "Swahili", "Congo-Kinshasa"),
  CountryLocalization("ck", "Engels", "Cookeilanden"),
  CountryLocalization("cr", "Spaans", "Costa Rica"),
  CountryLocalization("hr", "Kroatisch", "Kroatië"),
  CountryLocalization("cu", "Spaans", "Cuba"),
  CountryLocalization("cw", "Nederlands", "Curaçao"),
  CountryLocalization("cy", "Engels", "Cyprus"),
  CountryLocalization("cz", "Tsjechisch", "Tsjechië"),
  CountryLocalization("ci", "Frans", "Ivoorkust"),
  CountryLocalization("dk", "Engels", "Denemarken"),
  CountryLocalization("dg", "Engels", "Diego Garcia"),
  CountryLocalization("dj", "Frans", "Djibouti"),
  CountryLocalization("dm", "Engels", "Dominica"),
  CountryLocalization("do", "Spaans", "Dominicaanse Republiek"),
  CountryLocalization("ec", "Quechua", "Ecuador"),
  CountryLocalization("eg", "Arabisch", "Egypte"),
  CountryLocalization("sv", "Spaans", "El Salvador"),
  CountryLocalization("gq", "Spaans", "Equatoriaal-Guinea"),
  CountryLocalization("er", "Tigrinya", "Eritrea"),
  CountryLocalization("ee", "Estisch", "Estland"),
  CountryLocalization("et", "Amhaars", "Ethiopië"),
  CountryLocalization("fk", "Engels", "Falklandeilanden"),
  CountryLocalization("fo", "Faeröers", "Faeröer"),
  CountryLocalization("fj", "Engels", "Fiji"),
  CountryLocalization("fi", "Zweeds", "Finland"),
  CountryLocalization("fr", "Zwitserduits", "Frankrijk"),
  CountryLocalization("gf", "Frans", "Frans-Guyana"),
  CountryLocalization("pf", "Frans", "Frans-Polynesië"),
  CountryLocalization("ga", "Frans", "Gabon"),
  CountryLocalization("gm", "Engels", "Gambia"),
  CountryLocalization("ge", "Ossetisch", "Georgië"),
  CountryLocalization("de", "Nedersorbisch", "Duitsland"),
  CountryLocalization("gh", "Engels", "Ghana"),
  CountryLocalization("gi", "Engels", "Gibraltar"),
  CountryLocalization("gr", "Grieks", "Griekenland"),
  CountryLocalization("gl", "Groenlands", "Groenland"),
  CountryLocalization("gd", "Engels", "Grenada"),
  CountryLocalization("gp", "Frans", "Guadeloupe"),
  CountryLocalization("gu", "Engels", "Guam"),
  CountryLocalization("gt", "Spaans", "Guatemala"),
  CountryLocalization("gg", "Engels", "Guernsey"),
  CountryLocalization("gn", "Frans", "Guinee"),
  CountryLocalization("gw", "Portugees", "Guinee-Bissau"),
  CountryLocalization("gy", "Engels", "Guyana"),
  CountryLocalization("ht", "Frans", "Haïti"),
  CountryLocalization("hn", "Spaans", "Honduras"),
  CountryLocalization("hk", "Chinees", "Hongkong SAR van China"),
  CountryLocalization("hu", "Hongaars", "Hongarije"),
  CountryLocalization("is", "IJslands", "IJsland"),
  CountryLocalization("in", "Nepalees", "India"),
  CountryLocalization("id", "Indonesian", "Indonesië"),
  CountryLocalization("ir", "Perzisch", "Iran"),
  CountryLocalization("iq", "Noordelijk Luri", "Irak"),
  CountryLocalization("ie", "Engels", "Ierland"),
  CountryLocalization("im", "Manx", "Isle of Man"),
  CountryLocalization("il", "Engels", "Israël"),
  CountryLocalization("it", "Duits", "Italië"),
  CountryLocalization("jm", "Engels", "Jamaica"),
  CountryLocalization("jp", "Japans", "Japan"),
  CountryLocalization("je", "Engels", "Jersey"),
  CountryLocalization("jo", "Arabisch", "Jordanië"),
  CountryLocalization("kz", "Kazachs", "Kazachstan"),
  CountryLocalization("ke", "Somalisch", "Kenia"),
  CountryLocalization("ki", "Engels", "Kiribati"),
  CountryLocalization("xk", "Servisch", "Kosovo"),
  CountryLocalization("kw", "Arabisch", "Koeweit"),
  CountryLocalization("kg", "Russisch", "Kirgizië"),
  CountryLocalization("la", "Laotiaans", "Laos"),
  CountryLocalization("lv", "Lets", "Letland"),
  CountryLocalization("lb", "Arabisch", "Libanon"),
  CountryLocalization("ls", "Engels", "Lesotho"),
  CountryLocalization("lr", "Engels", "Liberia"),
  CountryLocalization("ly", "Arabisch", "Libië"),
  CountryLocalization("li", "Zwitserduits", "Liechtenstein"),
  CountryLocalization("lt", "Litouws", "Litouwen"),
  CountryLocalization("lu", "Luxemburgs", "Luxemburg"),
  CountryLocalization("mo", "Portugees", "Macau SAR van China"),
  CountryLocalization("mk", "Albanees", "Macedonië"),
  CountryLocalization("mg", "Frans", "Madagaskar"),
  CountryLocalization("mw", "Engels", "Malawi"),
  CountryLocalization("my", "Tamil", "Maleisië"),
  CountryLocalization("ml", "Frans", "Mali"),
  CountryLocalization("mt", "Engels", "Malta"),
  CountryLocalization("mh", "Engels", "Marshalleilanden"),
  CountryLocalization("mq", "Frans", "Martinique"),
  CountryLocalization("mr", "Arabisch", "Mauritanië"),
  CountryLocalization("mu", "Morisyen", "Mauritius"),
  CountryLocalization("yt", "Frans", "Mayotte"),
  CountryLocalization("mx", "Spaans", "Mexico"),
  CountryLocalization("fm", "Engels", "Micronesia"),
  CountryLocalization("md", "Russisch", "Moldavië"),
  CountryLocalization("mc", "Frans", "Monaco"),
  CountryLocalization("mn", "Mongools", "Mongolië"),
  CountryLocalization("me", "Servisch", "Montenegro"),
  CountryLocalization("ms", "Engels", "Montserrat"),
  CountryLocalization("ma", "Tamazight (Centraal-Marokko)", "Marokko"),
  CountryLocalization("mz", "Makhuwa-Meetto", "Mozambique"),
  CountryLocalization("mm", "Birmaans", "Myanmar (Birma)"),
  CountryLocalization("na", "Engels", "Namibië"),
  CountryLocalization("nr", "Engels", "Nauru"),
  CountryLocalization("np", "Nepalees", "Nepal"),
  CountryLocalization("nl", "Engels", "Nederland"),
  CountryLocalization("nc", "Frans", "Nieuw-Caledonië"),
  CountryLocalization("nz", "Engels", "Nieuw-Zeeland"),
  CountryLocalization("ni", "Spaans", "Nicaragua"),
  CountryLocalization("ne", "Hausa", "Niger"),
  CountryLocalization("ng", "Hausa", "Nigeria"),
  CountryLocalization("nu", "Engels", "Niue"),
  CountryLocalization("nf", "Engels", "Norfolk"),
  CountryLocalization("kp", "Koreaans", "Noord-Korea"),
  CountryLocalization("mp", "Engels", "Noordelijke Marianen"),
  CountryLocalization("no", "Noord-Samisch", "Noorwegen"),
  CountryLocalization("om", "Arabisch", "Oman"),
  CountryLocalization("pk", "Engels", "Pakistan"),
  CountryLocalization("pw", "Engels", "Palau"),
  CountryLocalization("ps", "Arabisch", "Palestijnse gebieden"),
  CountryLocalization("pa", "Spaans", "Panama"),
  CountryLocalization("pg", "Engels", "Papoea-Nieuw-Guinea"),
  CountryLocalization("py", "Spaans", "Paraguay"),
  CountryLocalization("pe", "Spaans", "Peru"),
  CountryLocalization("ph", "Filipijns", "Filipijnen"),
  CountryLocalization("pn", "Engels", "Pitcairneilanden"),
  CountryLocalization("pl", "Pools", "Polen"),
  CountryLocalization("pt", "Portugees", "Portugal"),
  CountryLocalization("pr", "Engels", "Puerto Rico"),
  CountryLocalization("qa", "Arabisch", "Qatar"),
  CountryLocalization("ro", "Roemeens", "Roemenië"),
  CountryLocalization("ru", "Tataars", "Rusland"),
  CountryLocalization("rw", "Engels", "Rwanda"),
  CountryLocalization("re", "Frans", "Réunion"),
  CountryLocalization("ws", "Engels", "Samoa"),
  CountryLocalization("sm", "Italiaans", "San Marino"),
  CountryLocalization("sa", "Arabisch", "Saoedi-Arabië"),
  CountryLocalization("sn", "Frans", "Senegal"),
  CountryLocalization("rs", "Servisch", "Servië"),
  CountryLocalization("cs", "Servisch", "Servië en Montenegro"),
  CountryLocalization("sc", "Frans", "Seychellen"),
  CountryLocalization("sl", "Engels", "Sierra Leone"),
  CountryLocalization("sg", "Tamil", "Singapore"),
  CountryLocalization("sx", "Engels", "Sint-Maarten"),
  CountryLocalization("sk", "Slowaaks", "Slowakije"),
  CountryLocalization("si", "Sloveens", "Slovenië"),
  CountryLocalization("sb", "Engels", "Salomonseilanden"),
  CountryLocalization("so", "Arabisch", "Somalië"),
  CountryLocalization("za", "Engels", "Zuid-Afrika"),
  CountryLocalization("kr", "Koreaans", "Zuid-Korea"),
  CountryLocalization("ss", "Nuer", "Zuid-Soedan"),
  CountryLocalization("es", "Spaans", "Spanje"),
  CountryLocalization("lk", "Tamil", "Sri Lanka"),
  CountryLocalization("bl", "Frans", "Saint-Barthélemy"),
  CountryLocalization("sh", "Engels", "Sint-Helena"),
  CountryLocalization("kn", "Engels", "Saint Kitts en Nevis"),
  CountryLocalization("lc", "Engels", "Saint Lucia"),
  CountryLocalization("mf", "Frans", "Saint-Martin"),
  CountryLocalization("pm", "Frans", "Saint-Pierre en Miquelon"),
  CountryLocalization("vc", "Engels", "Saint Vincent en de Grenadines"),
  CountryLocalization("sd", "Arabisch", "Soedan"),
  CountryLocalization("sr", "Nederlands", "Suriname"),
  CountryLocalization("sj", "Noors - Bokmål", "Spitsbergen en Jan Mayen"),
  CountryLocalization("sz", "Engels", "Swaziland"),
  CountryLocalization("se", "Zweeds", "Zweden"),
  CountryLocalization("ch", "Zwitserduits", "Zwitserland"),
  CountryLocalization("sy", "Arabisch", "Syrië"),
  CountryLocalization("st", "Portugees", "Sao Tomé en Principe"),
  CountryLocalization("tw", "Chinees", "Taiwan"),
  CountryLocalization("tj", "Tadzjieks", "Tadzjikistan"),
  CountryLocalization("tz", "Makonde", "Tanzania"),
  CountryLocalization("th", "Thai", "Thailand"),
  CountryLocalization("tl", "Portugees", "Oost-Timor"),
  CountryLocalization("tg", "Frans", "Togo"),
  CountryLocalization("tk", "Engels", "Tokelau"),
  CountryLocalization("to", "Tongaans", "Tonga"),
  CountryLocalization("tt", "Engels", "Trinidad en Tobago"),
  CountryLocalization("tn", "Frans", "Tunesië"),
  CountryLocalization("tr", "Turks", "Turkije"),
  CountryLocalization("tm", "Turkmeens", "Turkmenistan"),
  CountryLocalization("tc", "Engels", "Turks- en Caicoseilanden"),
  CountryLocalization("tv", "Engels", "Tuvalu"),
  CountryLocalization("um", "Engels", "Kleine afgelegen eilanden van de Verenigde Staten"),
  CountryLocalization("vi", "Engels", "Amerikaanse Maagdeneilanden"),
  CountryLocalization("ug", "Swahili", "Oeganda"),
  CountryLocalization("ua", "Oekraïens", "Oekraïne"),
  CountryLocalization("ae", "Arabisch", "Verenigde Arabische Emiraten"),
  CountryLocalization("gb", "Engels", "Verenigd Koninkrijk"),
  CountryLocalization("us", "Lakota", "Verenigde Staten"),
  CountryLocalization("uy", "Spaans", "Uruguay"),
  CountryLocalization("uz", "Oezbeeks", "Oezbekistan"),
  CountryLocalization("vu", "Frans", "Vanuatu"),
  CountryLocalization("va", "Italiaans", "Vaticaanstad"),
  CountryLocalization("ve", "Spaans", "Venezuela"),
  CountryLocalization("vn", "Vietnamees", "Vietnam"),
  CountryLocalization("wf", "Frans", "Wallis en Futuna"),
  CountryLocalization("eh", "Arabisch", "Westelijke Sahara"),
  CountryLocalization("ye", "Arabisch", "Jemen"),
  CountryLocalization("zm", "Engels", "Zambia"),
  CountryLocalization("zw", "Noord-Ndebele", "Zimbabwe"),
  CountryLocalization("ax", "Zweeds", "Åland"),
)
