/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot.atlas.extended

import dev.teogor.xenoglot.atlas.CountryLocalization
import kotlin.collections.List

/**
 * Holds the internal list of country-language mappings used for lookups within the package for
 * language code bg.
 *
 * This property contains a hardcoded list of [CountryLocalization] objects, each representing
 * a country and its associated official languages. This list is used by [CountryLanguageRegistry]
 * to provide access to country-language data and should not be modified directly.
 *
 * @see CountryLocalization
 * @see CountryLanguageRegistry
 */
internal val _countryLanguageMappings_bg: List<CountryLocalization> = listOf(
  CountryLocalization("af", "персийски", "Афганистан"),
  CountryLocalization("al", "албански", "Албания"),
  CountryLocalization("dz", "френски", "Алжир"),
  CountryLocalization("as", "английски", "Американска Самоа"),
  CountryLocalization("ad", "каталонски", "Андора"),
  CountryLocalization("ao", "лингала", "Ангола"),
  CountryLocalization("ai", "английски", "Ангуила"),
  CountryLocalization("ag", "английски", "Антигуа и Барбуда"),
  CountryLocalization("ar", "испански", "Аржентина"),
  CountryLocalization("am", "арменски", "Армения"),
  CountryLocalization("aw", "нидерландски", "Аруба"),
  CountryLocalization("au", "английски", "Австралия"),
  CountryLocalization("at", "английски", "Австрия"),
  CountryLocalization("az", "азербайджански", "Азербайджан"),
  CountryLocalization("bs", "английски", "Бахами"),
  CountryLocalization("bh", "арабски", "Бахрейн"),
  CountryLocalization("bd", "бенгалски", "Бангладеш"),
  CountryLocalization("bb", "английски", "Барбадос"),
  CountryLocalization("by", "беларуски", "Беларус"),
  CountryLocalization("be", "френски", "Белгия"),
  CountryLocalization("bz", "английски", "Белиз"),
  CountryLocalization("bj", "френски", "Бенин"),
  CountryLocalization("bm", "английски", "Бермудски острови"),
  CountryLocalization("bt", "дзонгкха", "Бутан"),
  CountryLocalization("bo", "испански", "Боливия"),
  CountryLocalization("ba", "босненски", "Босна и Херцеговина"),
  CountryLocalization("bw", "английски", "Ботсвана"),
  CountryLocalization("br", "португалски", "Бразилия"),
  CountryLocalization("io", "английски", "Британска територия в Индийския океан"),
  CountryLocalization("vg", "английски", "Британски Вирджински острови"),
  CountryLocalization("bn", "малайски", "Бруней Даруссалам"),
  CountryLocalization("bg", "български", "България"),
  CountryLocalization("bf", "френски", "Буркина Фасо"),
  CountryLocalization("bi", "френски", "Бурунди"),
  CountryLocalization("kh", "кхмерски", "Камбоджа"),
  CountryLocalization("cm", "баса", "Камерун"),
  CountryLocalization("ca", "френски", "Канада"),
  CountryLocalization("ic", "испански", "Канарски острови"),
  CountryLocalization("cv", "кабовердиански", "Кабо Верде"),
  CountryLocalization("bq", "нидерландски", "Карибска Нидерландия"),
  CountryLocalization("ky", "английски", "Кайманови острови"),
  CountryLocalization("cf", "лингала", "Централноафриканска република"),
  CountryLocalization("ea", "испански", "Сеута и Мелия"),
  CountryLocalization("td", "арабски", "Чад"),
  CountryLocalization("cl", "испански", "Чили"),
  CountryLocalization("cn", "тибетски", "Китай"),
  CountryLocalization("cx", "английски", "остров Рождество"),
  CountryLocalization("cc", "английски", "Кокосови острови (острови Кийлинг)"),
  CountryLocalization("co", "испански", "Колумбия"),
  CountryLocalization("km", "арабски", "Коморски острови"),
  CountryLocalization("cg", "лингала", "Конго (Бразавил)"),
  CountryLocalization("cd", "суахили", "Конго (Киншаса)"),
  CountryLocalization("ck", "английски", "острови Кук"),
  CountryLocalization("cr", "испански", "Коста Рика"),
  CountryLocalization("hr", "хърватски", "Хърватия"),
  CountryLocalization("cu", "испански", "Куба"),
  CountryLocalization("cw", "нидерландски", "Кюрасао"),
  CountryLocalization("cy", "английски", "Кипър"),
  CountryLocalization("cz", "чешки", "Чехия"),
  CountryLocalization("ci", "френски", "Кот д’Ивоар"),
  CountryLocalization("dk", "английски", "Дания"),
  CountryLocalization("dg", "английски", "Диего Гарсия"),
  CountryLocalization("dj", "френски", "Джибути"),
  CountryLocalization("dm", "английски", "Доминика"),
  CountryLocalization("do", "испански", "Доминиканска република"),
  CountryLocalization("ec", "кечуа", "Еквадор"),
  CountryLocalization("eg", "арабски", "Египет"),
  CountryLocalization("sv", "испански", "Салвадор"),
  CountryLocalization("gq", "испански", "Екваториална Гвинея"),
  CountryLocalization("er", "тигриня", "Еритрея"),
  CountryLocalization("ee", "естонски", "Естония"),
  CountryLocalization("et", "амхарски", "Етиопия"),
  CountryLocalization("fk", "английски", "Фолклендски острови"),
  CountryLocalization("fo", "фарьорски", "Фарьорски острови"),
  CountryLocalization("fj", "английски", "Фиджи"),
  CountryLocalization("fi", "шведски", "Финландия"),
  CountryLocalization("fr", "швейцарски немски", "Франция"),
  CountryLocalization("gf", "френски", "Френска Гвиана"),
  CountryLocalization("pf", "френски", "Френска Полинезия"),
  CountryLocalization("ga", "френски", "Габон"),
  CountryLocalization("gm", "английски", "Гамбия"),
  CountryLocalization("ge", "осетски", "Грузия"),
  CountryLocalization("de", "долнолужишки", "Германия"),
  CountryLocalization("gh", "английски", "Гана"),
  CountryLocalization("gi", "английски", "Гибралтар"),
  CountryLocalization("gr", "гръцки", "Гърция"),
  CountryLocalization("gl", "гренландски", "Гренландия"),
  CountryLocalization("gd", "английски", "Гренада"),
  CountryLocalization("gp", "френски", "Гваделупа"),
  CountryLocalization("gu", "английски", "Гуам"),
  CountryLocalization("gt", "испански", "Гватемала"),
  CountryLocalization("gg", "английски", "Гърнзи"),
  CountryLocalization("gn", "френски", "Гвинея"),
  CountryLocalization("gw", "португалски", "Гвинея-Бисау"),
  CountryLocalization("gy", "английски", "Гаяна"),
  CountryLocalization("ht", "френски", "Хаити"),
  CountryLocalization("hn", "испански", "Хондурас"),
  CountryLocalization("hk", "китайски", "Хонконг, САР на Китай"),
  CountryLocalization("hu", "унгарски", "Унгария"),
  CountryLocalization("is", "исландски", "Исландия"),
  CountryLocalization("in", "непалски", "Индия"),
  CountryLocalization("id", "Indonesian", "Индонезия"),
  CountryLocalization("ir", "персийски", "Иран"),
  CountryLocalization("iq", "северен лури", "Ирак"),
  CountryLocalization("ie", "английски", "Ирландия"),
  CountryLocalization("im", "манкски", "остров Ман"),
  CountryLocalization("il", "английски", "Израел"),
  CountryLocalization("it", "немски", "Италия"),
  CountryLocalization("jm", "английски", "Ямайка"),
  CountryLocalization("jp", "японски", "Япония"),
  CountryLocalization("je", "английски", "Джърси"),
  CountryLocalization("jo", "арабски", "Йордания"),
  CountryLocalization("kz", "казахски", "Казахстан"),
  CountryLocalization("ke", "сомалийски", "Кения"),
  CountryLocalization("ki", "английски", "Кирибати"),
  CountryLocalization("xk", "сръбски", "Косово"),
  CountryLocalization("kw", "арабски", "Кувейт"),
  CountryLocalization("kg", "руски", "Киргизстан"),
  CountryLocalization("la", "лаоски", "Лаос"),
  CountryLocalization("lv", "латвийски", "Латвия"),
  CountryLocalization("lb", "арабски", "Ливан"),
  CountryLocalization("ls", "английски", "Лесото"),
  CountryLocalization("lr", "английски", "Либерия"),
  CountryLocalization("ly", "арабски", "Либия"),
  CountryLocalization("li", "швейцарски немски", "Лихтенщайн"),
  CountryLocalization("lt", "литовски", "Литва"),
  CountryLocalization("lu", "люксембургски", "Люксембург"),
  CountryLocalization("mo", "португалски", "Макао, САР на Китай"),
  CountryLocalization("mk", "албански", "Македония"),
  CountryLocalization("mg", "френски", "Мадагаскар"),
  CountryLocalization("mw", "английски", "Малави"),
  CountryLocalization("my", "тамилски", "Малайзия"),
  CountryLocalization("ml", "френски", "Мали"),
  CountryLocalization("mt", "английски", "Малта"),
  CountryLocalization("mh", "английски", "Маршалови острови"),
  CountryLocalization("mq", "френски", "Мартиника"),
  CountryLocalization("mr", "арабски", "Мавритания"),
  CountryLocalization("mu", "морисиен", "Мавриций"),
  CountryLocalization("yt", "френски", "Майот"),
  CountryLocalization("mx", "испански", "Мексико"),
  CountryLocalization("fm", "английски", "Микронезия"),
  CountryLocalization("md", "руски", "Молдова"),
  CountryLocalization("mc", "френски", "Монако"),
  CountryLocalization("mn", "монголски", "Монголия"),
  CountryLocalization("me", "сръбски", "Черна гора"),
  CountryLocalization("ms", "английски", "Монтсерат"),
  CountryLocalization("ma", "централноатласки тамазигт", "Мароко"),
  CountryLocalization("mz", "макуа мето", "Мозамбик"),
  CountryLocalization("mm", "бирмански", "Мианмар (Бирма)"),
  CountryLocalization("na", "английски", "Намибия"),
  CountryLocalization("nr", "английски", "Науру"),
  CountryLocalization("np", "непалски", "Непал"),
  CountryLocalization("nl", "английски", "Нидерландия"),
  CountryLocalization("nc", "френски", "Нова Каледония"),
  CountryLocalization("nz", "английски", "Нова Зеландия"),
  CountryLocalization("ni", "испански", "Никарагуа"),
  CountryLocalization("ne", "хауса", "Нигер"),
  CountryLocalization("ng", "хауса", "Нигерия"),
  CountryLocalization("nu", "английски", "Ниуе"),
  CountryLocalization("nf", "английски", "остров Норфолк"),
  CountryLocalization("kp", "корейски", "Северна Корея"),
  CountryLocalization("mp", "английски", "Северни Мариански острови"),
  CountryLocalization("no", "северносаамски", "Норвегия"),
  CountryLocalization("om", "арабски", "Оман"),
  CountryLocalization("pk", "английски", "Пакистан"),
  CountryLocalization("pw", "английски", "Палау"),
  CountryLocalization("ps", "арабски", "Палестински територии"),
  CountryLocalization("pa", "испански", "Панама"),
  CountryLocalization("pg", "английски", "Папуа-Нова Гвинея"),
  CountryLocalization("py", "испански", "Парагвай"),
  CountryLocalization("pe", "испански", "Перу"),
  CountryLocalization("ph", "филипински", "Филипини"),
  CountryLocalization("pn", "английски", "Острови Питкерн"),
  CountryLocalization("pl", "полски", "Полша"),
  CountryLocalization("pt", "португалски", "Португалия"),
  CountryLocalization("pr", "английски", "Пуерто Рико"),
  CountryLocalization("qa", "арабски", "Катар"),
  CountryLocalization("ro", "румънски", "Румъния"),
  CountryLocalization("ru", "татарски", "Русия"),
  CountryLocalization("rw", "английски", "Руанда"),
  CountryLocalization("re", "френски", "Реюнион"),
  CountryLocalization("ws", "английски", "Самоа"),
  CountryLocalization("sm", "италиански", "Сан Марино"),
  CountryLocalization("sa", "арабски", "Саудитска Арабия"),
  CountryLocalization("sn", "френски", "Сенегал"),
  CountryLocalization("rs", "сръбски", "Сърбия"),
  CountryLocalization("cs", "сръбски", "Serbia and Montenegro"),
  CountryLocalization("sc", "френски", "Сейшели"),
  CountryLocalization("sl", "английски", "Сиера Леоне"),
  CountryLocalization("sg", "тамилски", "Сингапур"),
  CountryLocalization("sx", "английски", "Синт Мартен"),
  CountryLocalization("sk", "словашки", "Словакия"),
  CountryLocalization("si", "словенски", "Словения"),
  CountryLocalization("sb", "английски", "Соломонови острови"),
  CountryLocalization("so", "арабски", "Сомалия"),
  CountryLocalization("za", "английски", "Южна Африка"),
  CountryLocalization("kr", "корейски", "Южна Корея"),
  CountryLocalization("ss", "нуер", "Южен Судан"),
  CountryLocalization("es", "испански", "Испания"),
  CountryLocalization("lk", "тамилски", "Шри Ланка"),
  CountryLocalization("bl", "френски", "Сен Бартелеми"),
  CountryLocalization("sh", "английски", "Света Елена"),
  CountryLocalization("kn", "английски", "Сейнт Китс и Невис"),
  CountryLocalization("lc", "английски", "Сейнт Лусия"),
  CountryLocalization("mf", "френски", "Сен Мартен"),
  CountryLocalization("pm", "френски", "Сен Пиер и Микелон"),
  CountryLocalization("vc", "английски", "Сейнт Винсънт и Гренадини"),
  CountryLocalization("sd", "арабски", "Судан"),
  CountryLocalization("sr", "нидерландски", "Суринам"),
  CountryLocalization("sj", "норвежки (букмол)", "Свалбард и Ян Майен"),
  CountryLocalization("sz", "английски", "Свазиленд"),
  CountryLocalization("se", "шведски", "Швеция"),
  CountryLocalization("ch", "швейцарски немски", "Швейцария"),
  CountryLocalization("sy", "арабски", "Сирия"),
  CountryLocalization("st", "португалски", "Сао Томе и Принсипи"),
  CountryLocalization("tw", "китайски", "Тайван"),
  CountryLocalization("tj", "таджикски", "Таджикистан"),
  CountryLocalization("tz", "маконде", "Танзания"),
  CountryLocalization("th", "тайски", "Тайланд"),
  CountryLocalization("tl", "португалски", "Източен Тимор"),
  CountryLocalization("tg", "френски", "Того"),
  CountryLocalization("tk", "английски", "Токелау"),
  CountryLocalization("to", "тонгански", "Тонга"),
  CountryLocalization("tt", "английски", "Тринидад и Тобаго"),
  CountryLocalization("tn", "френски", "Тунис"),
  CountryLocalization("tr", "турски", "Турция"),
  CountryLocalization("tm", "туркменски", "Туркменистан"),
  CountryLocalization("tc", "английски", "острови Търкс и Кайкос"),
  CountryLocalization("tv", "английски", "Тувалу"),
  CountryLocalization("um", "английски", "Отдалечени острови на САЩ"),
  CountryLocalization("vi", "английски", "Американски Вирджински острови"),
  CountryLocalization("ug", "суахили", "Уганда"),
  CountryLocalization("ua", "украински", "Украйна"),
  CountryLocalization("ae", "арабски", "Обединени арабски емирства"),
  CountryLocalization("gb", "английски", "Обединеното кралство"),
  CountryLocalization("us", "лакота", "Съединени щати"),
  CountryLocalization("uy", "испански", "Уругвай"),
  CountryLocalization("uz", "узбекски", "Узбекистан"),
  CountryLocalization("vu", "френски", "Вануату"),
  CountryLocalization("va", "италиански", "Ватикан"),
  CountryLocalization("ve", "испански", "Венецуела"),
  CountryLocalization("vn", "виетнамски", "Виетнам"),
  CountryLocalization("wf", "френски", "Уолис и Футуна"),
  CountryLocalization("eh", "арабски", "Западна Сахара"),
  CountryLocalization("ye", "арабски", "Йемен"),
  CountryLocalization("zm", "английски", "Замбия"),
  CountryLocalization("zw", "северен ндебеле", "Зимбабве"),
  CountryLocalization("ax", "шведски", "Оландски острови"),
)
