/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot.atlas.extended

import dev.teogor.xenoglot.atlas.CountryLocalization
import kotlin.collections.List

/**
 * Holds the internal list of country-language mappings used for lookups within the package for
 * language code gsw.
 *
 * This property contains a hardcoded list of [CountryLocalization] objects, each representing
 * a country and its associated official languages. This list is used by [CountryLanguageRegistry]
 * to provide access to country-language data and should not be modified directly.
 *
 * @see CountryLocalization
 * @see CountryLanguageRegistry
 */
internal val _countryLanguageMappings_gsw: List<CountryLocalization> = listOf(
  CountryLocalization("af", "Persisch", "Afganischtan"),
  CountryLocalization("al", "Albanisch", "Albaanie"),
  CountryLocalization("dz", "Französisch", "Algeerie"),
  CountryLocalization("as", "Änglisch", "Amerikaanisch-Samoa"),
  CountryLocalization("ad", "Katalaanisch", "Andorra"),
  CountryLocalization("ao", "Lingala", "Angoola"),
  CountryLocalization("ai", "Änglisch", "Anguilla"),
  CountryLocalization("ag", "Änglisch", "Antigua und Barbuda"),
  CountryLocalization("ar", "Schpanisch", "Argentiinie"),
  CountryLocalization("am", "Armenisch", "Armeenie"),
  CountryLocalization("aw", "Niderländisch", "Aruba"),
  CountryLocalization("au", "Änglisch", "Auschtraalie"),
  CountryLocalization("at", "Änglisch", "Ööschtriich"),
  CountryLocalization("az", "Aserbaidschanisch", "Aserbäidschan"),
  CountryLocalization("bs", "Änglisch", "Bahaamas"),
  CountryLocalization("bh", "Arabisch", "Bachräin"),
  CountryLocalization("bd", "Bengalisch", "Bangladesch"),
  CountryLocalization("bb", "Änglisch", "Barbados"),
  CountryLocalization("by", "Wiissrussisch", "Wiissrussland"),
  CountryLocalization("be", "Französisch", "Belgie"),
  CountryLocalization("bz", "Änglisch", "Belize"),
  CountryLocalization("bj", "Französisch", "Benin"),
  CountryLocalization("bm", "Änglisch", "Bermuuda"),
  CountryLocalization("bt", "Dschongkha", "Bhutan"),
  CountryLocalization("bo", "Schpanisch", "Boliivie"),
  CountryLocalization("ba", "Bosnisch", "Bosnie und Herzegowina"),
  CountryLocalization("bw", "Änglisch", "Botswana"),
  CountryLocalization("br", "Portugiisisch", "Brasilie"),
  CountryLocalization("io", "Änglisch", "Britischs Territoorium im Indische Oozean"),
  CountryLocalization("vg", "Änglisch", "Britischi Jungfere-Insle"),
  CountryLocalization("bn", "Malaiisch", "Brunäi Tarussalam"),
  CountryLocalization("bg", "Bulgaarisch", "Bulgaarie"),
  CountryLocalization("bf", "Französisch", "Burkina Faaso"),
  CountryLocalization("bi", "Französisch", "Burundi"),
  CountryLocalization("kh", "Kambodschanisch", "Kambodscha"),
  CountryLocalization("cm", "Basaa", "Kamerun"),
  CountryLocalization("ca", "Französisch", "Kanada"),
  CountryLocalization("ic", "Schpanisch", "IC"),
  CountryLocalization("cv", "kea", "Kap Verde"),
  CountryLocalization("bq", "Niderländisch", "Caribbean Netherlands"),
  CountryLocalization("ky", "Änglisch", "Käimän-Insle"),
  CountryLocalization("cf", "Lingala", "Zentraalafrikaanischi Republik"),
  CountryLocalization("ea", "Schpanisch", "EA"),
  CountryLocalization("td", "Arabisch", "Tschad"),
  CountryLocalization("cl", "Schpanisch", "Tschile"),
  CountryLocalization("cn", "Tibeetisch", "Chiina"),
  CountryLocalization("cx", "Änglisch", "Wienachts-Insle"),
  CountryLocalization("cc", "Änglisch", "Kokos-Insle"),
  CountryLocalization("co", "Schpanisch", "Kolumbie"),
  CountryLocalization("km", "Arabisch", "Komoore"),
  CountryLocalization("cg", "Lingala", "Kongo"),
  CountryLocalization("cd", "Suaheli", "Temokraatischi Republik Kongo"),
  CountryLocalization("ck", "Änglisch", "Cook-Insle"),
  CountryLocalization("cr", "Schpanisch", "Coschta Rica"),
  CountryLocalization("hr", "Kroazisch", "Kroaazie"),
  CountryLocalization("cu", "Schpanisch", "Kuba"),
  CountryLocalization("cw", "Niderländisch", "Curaçao"),
  CountryLocalization("cy", "Änglisch", "Zypere"),
  CountryLocalization("cz", "Tschechisch", "Tschechischi Republik"),
  CountryLocalization("ci", "Französisch", "Elfebäiküschte"),
  CountryLocalization("dk", "Änglisch", "Tänemark"),
  CountryLocalization("dg", "Änglisch", "DG"),
  CountryLocalization("dj", "Französisch", "Tschibuuti"),
  CountryLocalization("dm", "Änglisch", "Tominica"),
  CountryLocalization("do", "Schpanisch", "Tominikaanischi Republik"),
  CountryLocalization("ec", "Quechua", "Ecuador"),
  CountryLocalization("eg", "Arabisch", "Ägüpte"),
  CountryLocalization("sv", "Schpanisch", "El Salvador"),
  CountryLocalization("gq", "Schpanisch", "Äquatoriaalgineea"),
  CountryLocalization("er", "Tigrinja", "Äritreea"),
  CountryLocalization("ee", "Eestnisch", "Eestland"),
  CountryLocalization("et", "Amharisch", "Äthiopie"),
  CountryLocalization("fk", "Änglisch", "Falkland-Insle"),
  CountryLocalization("fo", "Färöisch", "Färöer"),
  CountryLocalization("fj", "Änglisch", "Fitschi"),
  CountryLocalization("fi", "Schwedisch", "Finnland"),
  CountryLocalization("fr", "Schwiizertüütsch", "Frankriich"),
  CountryLocalization("gf", "Französisch", "Französisch-Guäjaana"),
  CountryLocalization("pf", "Französisch", "Französisch-Polineesie"),
  CountryLocalization("ga", "Französisch", "Gabun"),
  CountryLocalization("gm", "Änglisch", "Gambia"),
  CountryLocalization("ge", "Ossezisch", "Geoorgie"),
  CountryLocalization("de", "Nidersorbisch", "Tüütschland"),
  CountryLocalization("gh", "Änglisch", "Gaana"),
  CountryLocalization("gi", "Änglisch", "Gibraltar"),
  CountryLocalization("gr", "Griechisch", "Griecheland"),
  CountryLocalization("gl", "Gröönländisch", "Gröönland"),
  CountryLocalization("gd", "Änglisch", "Grenada"),
  CountryLocalization("gp", "Französisch", "Guadälup"),
  CountryLocalization("gu", "Änglisch", "Guam"),
  CountryLocalization("gt", "Schpanisch", "Guatemaala"),
  CountryLocalization("gg", "Änglisch", "Gäärnsi"),
  CountryLocalization("gn", "Französisch", "Gineea"),
  CountryLocalization("gw", "Portugiisisch", "Gineea-Bissau"),
  CountryLocalization("gy", "Änglisch", "Guäjaana"),
  CountryLocalization("ht", "Französisch", "Haiti"),
  CountryLocalization("hn", "Schpanisch", "Honduras"),
  CountryLocalization("hk", "Chineesisch", "Sonderverwaltigszone Hongkong"),
  CountryLocalization("hu", "Ungarisch", "Ungarn"),
  CountryLocalization("is", "Iisländisch", "Iisland"),
  CountryLocalization("in", "Nepalesisch", "Indie"),
  CountryLocalization("id", "Indonesian", "Indoneesie"),
  CountryLocalization("ir", "Persisch", "Iraan"),
  CountryLocalization("iq", "lrc", "Iraak"),
  CountryLocalization("ie", "Änglisch", "Irland"),
  CountryLocalization("im", "Manx-Gäälisch", "Insle vo Män"),
  CountryLocalization("il", "Änglisch", "Israel"),
  CountryLocalization("it", "Tüütsch", "Itaalie"),
  CountryLocalization("jm", "Änglisch", "Dschamäika"),
  CountryLocalization("jp", "Japanisch", "Japan"),
  CountryLocalization("je", "Änglisch", "Dschörsi"),
  CountryLocalization("jo", "Arabisch", "Jordaanie"),
  CountryLocalization("kz", "Kasachisch", "Kasachschtan"),
  CountryLocalization("ke", "Somali", "Keenia"),
  CountryLocalization("ki", "Änglisch", "Kiribaati"),
  CountryLocalization("xk", "Serbisch", "XK"),
  CountryLocalization("kw", "Arabisch", "Kuwäit"),
  CountryLocalization("kg", "Russisch", "Kirgiisischtan"),
  CountryLocalization("la", "Laozisch", "Laaos"),
  CountryLocalization("lv", "Lettisch", "Lettland"),
  CountryLocalization("lb", "Arabisch", "Libanon"),
  CountryLocalization("ls", "Änglisch", "Lesooto"),
  CountryLocalization("lr", "Änglisch", "Libeeria"),
  CountryLocalization("ly", "Arabisch", "Lüübie"),
  CountryLocalization("li", "Schwiizertüütsch", "Liächteschtäi"),
  CountryLocalization("lt", "Litauisch", "Littaue"),
  CountryLocalization("lu", "Luxemburgisch", "Luxemburg"),
  CountryLocalization("mo", "Portugiisisch", "Sonderverwaltigszone Macao"),
  CountryLocalization("mk", "Albanisch", "Mazedoonie"),
  CountryLocalization("mg", "Französisch", "Madagaschkar"),
  CountryLocalization("mw", "Änglisch", "Malaawi"),
  CountryLocalization("my", "Tamilisch", "Maläisia"),
  CountryLocalization("ml", "Französisch", "Maali"),
  CountryLocalization("mt", "Änglisch", "Malta"),
  CountryLocalization("mh", "Änglisch", "Marshallinsle"),
  CountryLocalization("mq", "Französisch", "Martinigg"),
  CountryLocalization("mr", "Arabisch", "Mauretaanie"),
  CountryLocalization("mu", "mfe", "Mauriizius"),
  CountryLocalization("yt", "Französisch", "Majott"),
  CountryLocalization("mx", "Schpanisch", "Mexiko"),
  CountryLocalization("fm", "Änglisch", "Mikroneesie"),
  CountryLocalization("md", "Russisch", "Republik Moldau"),
  CountryLocalization("mc", "Französisch", "Monaco"),
  CountryLocalization("mn", "Mongolisch", "Mongolei"),
  CountryLocalization("me", "Serbisch", "Monteneegro"),
  CountryLocalization("ms", "Änglisch", "Moosörrat"),
  CountryLocalization("ma", "tzm", "Marokko"),
  CountryLocalization("mz", "mgh", "Mosambik"),
  CountryLocalization("mm", "Birmanisch", "Myanmar (Burma)"),
  CountryLocalization("na", "Änglisch", "Namiibia"),
  CountryLocalization("nr", "Änglisch", "Nauru"),
  CountryLocalization("np", "Nepalesisch", "Neepal"),
  CountryLocalization("nl", "Änglisch", "Holland"),
  CountryLocalization("nc", "Französisch", "Nöikaledoonie"),
  CountryLocalization("nz", "Änglisch", "Nöiseeland"),
  CountryLocalization("ni", "Schpanisch", "Nicaraagua"),
  CountryLocalization("ne", "Haussa", "Niger"),
  CountryLocalization("ng", "Haussa", "Nigeeria"),
  CountryLocalization("nu", "Änglisch", "Niue"),
  CountryLocalization("nf", "Änglisch", "Norfolk-Insle"),
  CountryLocalization("kp", "Koreaanisch", "Demokraatischi Volksrepublik Koreea"),
  CountryLocalization("mp", "Änglisch", "Nördlichi Mariaane"),
  CountryLocalization("no", "Nord-Samisch", "Norweege"),
  CountryLocalization("om", "Arabisch", "Omaan"),
  CountryLocalization("pk", "Änglisch", "Pakischtan"),
  CountryLocalization("pw", "Änglisch", "Palau"),
  CountryLocalization("ps", "Arabisch", "Paläschtinänsischi Gebiet"),
  CountryLocalization("pa", "Schpanisch", "Panama"),
  CountryLocalization("pg", "Änglisch", "Papua-Neuguinea"),
  CountryLocalization("py", "Schpanisch", "Paraguai"),
  CountryLocalization("pe", "Schpanisch", "Peru"),
  CountryLocalization("ph", "Filipino", "Philippiine"),
  CountryLocalization("pn", "Änglisch", "Pitggäärn"),
  CountryLocalization("pl", "Polnisch", "Poole"),
  CountryLocalization("pt", "Portugiisisch", "Portugal"),
  CountryLocalization("pr", "Änglisch", "Puerto Riggo"),
  CountryLocalization("qa", "Arabisch", "Ggatar"),
  CountryLocalization("ro", "Rumänisch", "Rumäänie"),
  CountryLocalization("ru", "Tatarisch", "Russland"),
  CountryLocalization("rw", "Änglisch", "Ruanda"),
  CountryLocalization("re", "Französisch", "Reünioon"),
  CountryLocalization("ws", "Änglisch", "Samooa"),
  CountryLocalization("sm", "Italiänisch", "San Mariino"),
  CountryLocalization("sa", "Arabisch", "Saudi-Araabie"),
  CountryLocalization("sn", "Französisch", "Senegal"),
  CountryLocalization("rs", "Serbisch", "Särbie"),
  CountryLocalization("cs", "Serbisch", "Serbia and Montenegro"),
  CountryLocalization("sc", "Französisch", "Seischälle"),
  CountryLocalization("sl", "Änglisch", "Sierra Leoone"),
  CountryLocalization("sg", "Tamilisch", "Singapuur"),
  CountryLocalization("sx", "Änglisch", "Sint Maarten"),
  CountryLocalization("sk", "Slowakisch", "Slowakäi"),
  CountryLocalization("si", "Slowenisch", "Sloweenie"),
  CountryLocalization("sb", "Änglisch", "Salomoone"),
  CountryLocalization("so", "Arabisch", "Somaalie"),
  CountryLocalization("za", "Änglisch", "Süüdafrika"),
  CountryLocalization("kr", "Koreaanisch", "Republik Koreea"),
  CountryLocalization("ss", "nus", "South Sudan"),
  CountryLocalization("es", "Schpanisch", "Schpanie"),
  CountryLocalization("lk", "Tamilisch", "Schri Lanka"),
  CountryLocalization("bl", "Französisch", "St. Barthelemi"),
  CountryLocalization("sh", "Änglisch", "St. Helena"),
  CountryLocalization("kn", "Änglisch", "St. Kitts und Niuwis"),
  CountryLocalization("lc", "Änglisch", "St. Lutschiia"),
  CountryLocalization("mf", "Französisch", "St. Martin"),
  CountryLocalization("pm", "Französisch", "St. Pierr und Miggelo"),
  CountryLocalization("vc", "Änglisch", "St. Vincent und d’Grönadiine"),
  CountryLocalization("sd", "Arabisch", "Sudan"),
  CountryLocalization("sr", "Niderländisch", "Surinam"),
  CountryLocalization("sj", "Norwegisch Bokmål", "Svalbard und Jaan Määie"),
  CountryLocalization("sz", "Änglisch", "Swasiland"),
  CountryLocalization("se", "Schwedisch", "Schweede"),
  CountryLocalization("ch", "Schwiizertüütsch", "Schwiiz"),
  CountryLocalization("sy", "Arabisch", "Süürie"),
  CountryLocalization("st", "Portugiisisch", "Sao Tome und Prinssipe"),
  CountryLocalization("tw", "Chineesisch", "Taiwan"),
  CountryLocalization("tj", "Tadschikisch", "Tadschikischtan"),
  CountryLocalization("tz", "kde", "Tansaniia"),
  CountryLocalization("th", "Thailändisch", "Thailand"),
  CountryLocalization("tl", "Portugiisisch", "Oschttimor"),
  CountryLocalization("tg", "Französisch", "Toogo"),
  CountryLocalization("tk", "Änglisch", "Tokelau"),
  CountryLocalization("to", "Tongaisch", "Tonga"),
  CountryLocalization("tt", "Änglisch", "Trinidad und Tobaago"),
  CountryLocalization("tn", "Französisch", "Tuneesie"),
  CountryLocalization("tr", "Türkisch", "Türggei"),
  CountryLocalization("tm", "Turkmenisch", "Turkmeenischtan"),
  CountryLocalization("tc", "Änglisch", "Törks- und Gaiggos-Insle"),
  CountryLocalization("tv", "Änglisch", "Tuvalu"),
  CountryLocalization("um", "Änglisch", "Amerikanisch-Ozeaanie"),
  CountryLocalization("vi", "Änglisch", "Amerikaanischi Jungfere-Insle"),
  CountryLocalization("ug", "Suaheli", "Uganda"),
  CountryLocalization("ua", "Ukrainisch", "Ukraiine"),
  CountryLocalization("ae", "Arabisch", "Veräinigti Arabischi Emirate"),
  CountryLocalization("gb", "Änglisch", "Veräinigts Chönigriich"),
  CountryLocalization("us", "lkt", "Veräinigti Schtaate"),
  CountryLocalization("uy", "Schpanisch", "Uruguay"),
  CountryLocalization("uz", "Usbekisch", "Uschbeekischtan"),
  CountryLocalization("vu", "Französisch", "Wanuatu"),
  CountryLocalization("va", "Italiänisch", "Vatikanstadt"),
  CountryLocalization("ve", "Schpanisch", "Venezueela"),
  CountryLocalization("vn", "Vietnamesisch", "Wietnam"),
  CountryLocalization("wf", "Französisch", "Wallis und Futuuna"),
  CountryLocalization("eh", "Arabisch", "Weschtsahara"),
  CountryLocalization("ye", "Arabisch", "Jeeme"),
  CountryLocalization("zm", "Änglisch", "Sambia"),
  CountryLocalization("zw", "Nord-Ndebele-Schpraach", "Simbabwe"),
  CountryLocalization("ax", "Schwedisch", "Aaland-Insle"),
)
