/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot.atlas.extended

import dev.teogor.xenoglot.atlas.CountryLocalization
import kotlin.collections.List

/**
 * Holds the internal list of country-language mappings used for lookups within the package for
 * language code ru.
 *
 * This property contains a hardcoded list of [CountryLocalization] objects, each representing
 * a country and its associated official languages. This list is used by [CountryLanguageRegistry]
 * to provide access to country-language data and should not be modified directly.
 *
 * @see CountryLocalization
 * @see CountryLanguageRegistry
 */
internal val _countryLanguageMappings_ru: List<CountryLocalization> = listOf(
  CountryLocalization("af", "персидский", "Афганистан"),
  CountryLocalization("al", "албанский", "Албания"),
  CountryLocalization("dz", "французский", "Алжир"),
  CountryLocalization("as", "английский", "Американское Самоа"),
  CountryLocalization("ad", "каталанский", "Андорра"),
  CountryLocalization("ao", "лингала", "Ангола"),
  CountryLocalization("ai", "английский", "Ангилья"),
  CountryLocalization("ag", "английский", "Антигуа и Барбуда"),
  CountryLocalization("ar", "испанский", "Аргентина"),
  CountryLocalization("am", "армянский", "Армения"),
  CountryLocalization("aw", "нидерландский", "Аруба"),
  CountryLocalization("au", "английский", "Австралия"),
  CountryLocalization("at", "английский", "Австрия"),
  CountryLocalization("az", "азербайджанский", "Азербайджан"),
  CountryLocalization("bs", "английский", "Багамы"),
  CountryLocalization("bh", "арабский", "Бахрейн"),
  CountryLocalization("bd", "бенгальский", "Бангладеш"),
  CountryLocalization("bb", "английский", "Барбадос"),
  CountryLocalization("by", "белорусский", "Беларусь"),
  CountryLocalization("be", "французский", "Бельгия"),
  CountryLocalization("bz", "английский", "Белиз"),
  CountryLocalization("bj", "французский", "Бенин"),
  CountryLocalization("bm", "английский", "Бермудские о-ва"),
  CountryLocalization("bt", "дзонг-кэ", "Бутан"),
  CountryLocalization("bo", "испанский", "Боливия"),
  CountryLocalization("ba", "боснийский", "Босния и Герцеговина"),
  CountryLocalization("bw", "английский", "Ботсвана"),
  CountryLocalization("br", "португальский", "Бразилия"),
  CountryLocalization("io", "английский", "Британская территория в Индийском океане"),
  CountryLocalization("vg", "английский", "Виргинские о-ва (Британские)"),
  CountryLocalization("bn", "малайский", "Бруней-Даруссалам"),
  CountryLocalization("bg", "болгарский", "Болгария"),
  CountryLocalization("bf", "французский", "Буркина-Фасо"),
  CountryLocalization("bi", "французский", "Бурунди"),
  CountryLocalization("kh", "кхмерский", "Камбоджа"),
  CountryLocalization("cm", "баса", "Камерун"),
  CountryLocalization("ca", "французский", "Канада"),
  CountryLocalization("ic", "испанский", "Канарские о-ва"),
  CountryLocalization("cv", "кабувердьяну", "Кабо-Верде"),
  CountryLocalization("bq", "нидерландский", "Бонэйр, Синт-Эстатиус и Саба"),
  CountryLocalization("ky", "английский", "Каймановы о-ва"),
  CountryLocalization("cf", "лингала", "Центрально-Африканская Республика"),
  CountryLocalization("ea", "испанский", "Сеута и Мелилья"),
  CountryLocalization("td", "арабский", "Чад"),
  CountryLocalization("cl", "испанский", "Чили"),
  CountryLocalization("cn", "тибетский", "Китай"),
  CountryLocalization("cx", "английский", "о-в Рождества"),
  CountryLocalization("cc", "английский", "Кокосовые о-ва"),
  CountryLocalization("co", "испанский", "Колумбия"),
  CountryLocalization("km", "арабский", "Коморы"),
  CountryLocalization("cg", "лингала", "Конго - Браззавиль"),
  CountryLocalization("cd", "суахили", "Конго - Киншаса"),
  CountryLocalization("ck", "английский", "Острова Кука"),
  CountryLocalization("cr", "испанский", "Коста-Рика"),
  CountryLocalization("hr", "хорватский", "Хорватия"),
  CountryLocalization("cu", "испанский", "Куба"),
  CountryLocalization("cw", "нидерландский", "Кюрасао"),
  CountryLocalization("cy", "английский", "Кипр"),
  CountryLocalization("cz", "чешский", "Чехия"),
  CountryLocalization("ci", "французский", "Кот-д’Ивуар"),
  CountryLocalization("dk", "английский", "Дания"),
  CountryLocalization("dg", "английский", "Диего-Гарсия"),
  CountryLocalization("dj", "французский", "Джибути"),
  CountryLocalization("dm", "английский", "Доминика"),
  CountryLocalization("do", "испанский", "Доминиканская Республика"),
  CountryLocalization("ec", "кечуа", "Эквадор"),
  CountryLocalization("eg", "арабский", "Египет"),
  CountryLocalization("sv", "испанский", "Сальвадор"),
  CountryLocalization("gq", "испанский", "Экваториальная Гвинея"),
  CountryLocalization("er", "тигринья", "Эритрея"),
  CountryLocalization("ee", "эстонский", "Эстония"),
  CountryLocalization("et", "амхарский", "Эфиопия"),
  CountryLocalization("fk", "английский", "Фолклендские о-ва"),
  CountryLocalization("fo", "фарерский", "Фарерские о-ва"),
  CountryLocalization("fj", "английский", "Фиджи"),
  CountryLocalization("fi", "шведский", "Финляндия"),
  CountryLocalization("fr", "швейцарский немецкий", "Франция"),
  CountryLocalization("gf", "французский", "Французская Гвиана"),
  CountryLocalization("pf", "французский", "Французская Полинезия"),
  CountryLocalization("ga", "французский", "Габон"),
  CountryLocalization("gm", "английский", "Гамбия"),
  CountryLocalization("ge", "осетинский", "Грузия"),
  CountryLocalization("de", "нижнелужицкий", "Германия"),
  CountryLocalization("gh", "английский", "Гана"),
  CountryLocalization("gi", "английский", "Гибралтар"),
  CountryLocalization("gr", "греческий", "Греция"),
  CountryLocalization("gl", "гренландский", "Гренландия"),
  CountryLocalization("gd", "английский", "Гренада"),
  CountryLocalization("gp", "французский", "Гваделупа"),
  CountryLocalization("gu", "английский", "Гуам"),
  CountryLocalization("gt", "испанский", "Гватемала"),
  CountryLocalization("gg", "английский", "Гернси"),
  CountryLocalization("gn", "французский", "Гвинея"),
  CountryLocalization("gw", "португальский", "Гвинея-Бисау"),
  CountryLocalization("gy", "английский", "Гайана"),
  CountryLocalization("ht", "французский", "Гаити"),
  CountryLocalization("hn", "испанский", "Гондурас"),
  CountryLocalization("hk", "китайский", "Гонконг (САР)"),
  CountryLocalization("hu", "венгерский", "Венгрия"),
  CountryLocalization("is", "исландский", "Исландия"),
  CountryLocalization("in", "непальский", "Индия"),
  CountryLocalization("id", "индонезийский", "Индонезия"),
  CountryLocalization("ir", "персидский", "Иран"),
  CountryLocalization("iq", "севернолурский", "Ирак"),
  CountryLocalization("ie", "английский", "Ирландия"),
  CountryLocalization("im", "мэнский", "о-в Мэн"),
  CountryLocalization("il", "английский", "Израиль"),
  CountryLocalization("it", "немецкий", "Италия"),
  CountryLocalization("jm", "английский", "Ямайка"),
  CountryLocalization("jp", "японский", "Япония"),
  CountryLocalization("je", "английский", "Джерси"),
  CountryLocalization("jo", "арабский", "Иордания"),
  CountryLocalization("kz", "казахский", "Казахстан"),
  CountryLocalization("ke", "сомали", "Кения"),
  CountryLocalization("ki", "английский", "Кирибати"),
  CountryLocalization("xk", "сербский", "Косово"),
  CountryLocalization("kw", "арабский", "Кувейт"),
  CountryLocalization("kg", "русский", "Киргизия"),
  CountryLocalization("la", "лаосский", "Лаос"),
  CountryLocalization("lv", "латышский", "Латвия"),
  CountryLocalization("lb", "арабский", "Ливан"),
  CountryLocalization("ls", "английский", "Лесото"),
  CountryLocalization("lr", "английский", "Либерия"),
  CountryLocalization("ly", "арабский", "Ливия"),
  CountryLocalization("li", "швейцарский немецкий", "Лихтенштейн"),
  CountryLocalization("lt", "литовский", "Литва"),
  CountryLocalization("lu", "люксембургский", "Люксембург"),
  CountryLocalization("mo", "португальский", "Макао (САР)"),
  CountryLocalization("mk", "албанский", "Македония"),
  CountryLocalization("mg", "французский", "Мадагаскар"),
  CountryLocalization("mw", "английский", "Малави"),
  CountryLocalization("my", "тамильский", "Малайзия"),
  CountryLocalization("ml", "французский", "Мали"),
  CountryLocalization("mt", "английский", "Мальта"),
  CountryLocalization("mh", "английский", "Маршалловы Острова"),
  CountryLocalization("mq", "французский", "Мартиника"),
  CountryLocalization("mr", "арабский", "Мавритания"),
  CountryLocalization("mu", "маврикийский креольский", "Маврикий"),
  CountryLocalization("yt", "французский", "Майотта"),
  CountryLocalization("mx", "испанский", "Мексика"),
  CountryLocalization("fm", "английский", "Федеративные Штаты Микронезии"),
  CountryLocalization("md", "русский", "Молдова"),
  CountryLocalization("mc", "французский", "Монако"),
  CountryLocalization("mn", "монгольский", "Монголия"),
  CountryLocalization("me", "сербский", "Черногория"),
  CountryLocalization("ms", "английский", "Монтсеррат"),
  CountryLocalization("ma", "среднеатласский тамазигхтский", "Марокко"),
  CountryLocalization("mz", "макуа-меетто", "Мозамбик"),
  CountryLocalization("mm", "бирманский", "Мьянма (Бирма)"),
  CountryLocalization("na", "английский", "Намибия"),
  CountryLocalization("nr", "английский", "Науру"),
  CountryLocalization("np", "непальский", "Непал"),
  CountryLocalization("nl", "английский", "Нидерланды"),
  CountryLocalization("nc", "французский", "Новая Каледония"),
  CountryLocalization("nz", "английский", "Новая Зеландия"),
  CountryLocalization("ni", "испанский", "Никарагуа"),
  CountryLocalization("ne", "хауса", "Нигер"),
  CountryLocalization("ng", "хауса", "Нигерия"),
  CountryLocalization("nu", "английский", "Ниуэ"),
  CountryLocalization("nf", "английский", "о-в Норфолк"),
  CountryLocalization("kp", "корейский", "КНДР"),
  CountryLocalization("mp", "английский", "Северные Марианские о-ва"),
  CountryLocalization("no", "северносаамский", "Норвегия"),
  CountryLocalization("om", "арабский", "Оман"),
  CountryLocalization("pk", "английский", "Пакистан"),
  CountryLocalization("pw", "английский", "Палау"),
  CountryLocalization("ps", "арабский", "Палестинские территории"),
  CountryLocalization("pa", "испанский", "Панама"),
  CountryLocalization("pg", "английский", "Папуа — Новая Гвинея"),
  CountryLocalization("py", "испанский", "Парагвай"),
  CountryLocalization("pe", "испанский", "Перу"),
  CountryLocalization("ph", "филиппинский", "Филиппины"),
  CountryLocalization("pn", "английский", "о-ва Питкэрн"),
  CountryLocalization("pl", "польский", "Польша"),
  CountryLocalization("pt", "португальский", "Португалия"),
  CountryLocalization("pr", "английский", "Пуэрто-Рико"),
  CountryLocalization("qa", "арабский", "Катар"),
  CountryLocalization("ro", "румынский", "Румыния"),
  CountryLocalization("ru", "татарский", "Россия"),
  CountryLocalization("rw", "английский", "Руанда"),
  CountryLocalization("re", "французский", "Реюньон"),
  CountryLocalization("ws", "английский", "Самоа"),
  CountryLocalization("sm", "итальянский", "Сан-Марино"),
  CountryLocalization("sa", "арабский", "Саудовская Аравия"),
  CountryLocalization("sn", "французский", "Сенегал"),
  CountryLocalization("rs", "сербский", "Сербия"),
  CountryLocalization("cs", "сербский", "Serbia and Montenegro"),
  CountryLocalization("sc", "французский", "Сейшельские Острова"),
  CountryLocalization("sl", "английский", "Сьерра-Леоне"),
  CountryLocalization("sg", "тамильский", "Сингапур"),
  CountryLocalization("sx", "английский", "Синт-Мартен"),
  CountryLocalization("sk", "словацкий", "Словакия"),
  CountryLocalization("si", "словенский", "Словения"),
  CountryLocalization("sb", "английский", "Соломоновы Острова"),
  CountryLocalization("so", "арабский", "Сомали"),
  CountryLocalization("za", "английский", "Южно-Африканская Республика"),
  CountryLocalization("kr", "корейский", "Республика Корея"),
  CountryLocalization("ss", "нуэр", "Южный Судан"),
  CountryLocalization("es", "испанский", "Испания"),
  CountryLocalization("lk", "тамильский", "Шри-Ланка"),
  CountryLocalization("bl", "французский", "Сен-Бартелеми"),
  CountryLocalization("sh", "английский", "о-в Св. Елены"),
  CountryLocalization("kn", "английский", "Сент-Китс и Невис"),
  CountryLocalization("lc", "английский", "Сент-Люсия"),
  CountryLocalization("mf", "французский", "Сен-Мартен"),
  CountryLocalization("pm", "французский", "Сен-Пьер и Микелон"),
  CountryLocalization("vc", "английский", "Сент-Винсент и Гренадины"),
  CountryLocalization("sd", "арабский", "Судан"),
  CountryLocalization("sr", "нидерландский", "Суринам"),
  CountryLocalization("sj", "норвежский букмол", "Шпицберген и Ян-Майен"),
  CountryLocalization("sz", "английский", "Свазиленд"),
  CountryLocalization("se", "шведский", "Швеция"),
  CountryLocalization("ch", "швейцарский немецкий", "Швейцария"),
  CountryLocalization("sy", "арабский", "Сирия"),
  CountryLocalization("st", "португальский", "Сан-Томе и Принсипи"),
  CountryLocalization("tw", "китайский", "Тайвань"),
  CountryLocalization("tj", "таджикский", "Таджикистан"),
  CountryLocalization("tz", "маконде", "Танзания"),
  CountryLocalization("th", "тайский", "Таиланд"),
  CountryLocalization("tl", "португальский", "Восточный Тимор"),
  CountryLocalization("tg", "французский", "Того"),
  CountryLocalization("tk", "английский", "Токелау"),
  CountryLocalization("to", "тонганский", "Тонга"),
  CountryLocalization("tt", "английский", "Тринидад и Тобаго"),
  CountryLocalization("tn", "французский", "Тунис"),
  CountryLocalization("tr", "турецкий", "Турция"),
  CountryLocalization("tm", "туркменский", "Туркменистан"),
  CountryLocalization("tc", "английский", "о-ва Тёркс и Кайкос"),
  CountryLocalization("tv", "английский", "Тувалу"),
  CountryLocalization("um", "английский", "Внешние малые о-ва (США)"),
  CountryLocalization("vi", "английский", "Виргинские о-ва (США)"),
  CountryLocalization("ug", "суахили", "Уганда"),
  CountryLocalization("ua", "украинский", "Украина"),
  CountryLocalization("ae", "арабский", "ОАЭ"),
  CountryLocalization("gb", "английский", "Великобритания"),
  CountryLocalization("us", "лакота", "Соединенные Штаты"),
  CountryLocalization("uy", "испанский", "Уругвай"),
  CountryLocalization("uz", "узбекский", "Узбекистан"),
  CountryLocalization("vu", "французский", "Вануату"),
  CountryLocalization("va", "итальянский", "Ватикан"),
  CountryLocalization("ve", "испанский", "Венесуэла"),
  CountryLocalization("vn", "вьетнамский", "Вьетнам"),
  CountryLocalization("wf", "французский", "Уоллис и Футуна"),
  CountryLocalization("eh", "арабский", "Западная Сахара"),
  CountryLocalization("ye", "арабский", "Йемен"),
  CountryLocalization("zm", "английский", "Замбия"),
  CountryLocalization("zw", "северный ндебеле", "Зимбабве"),
  CountryLocalization("ax", "шведский", "Аландские о-ва"),
)
