/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot.atlas.extended

import dev.teogor.xenoglot.atlas.CountryLocalization
import kotlin.collections.List

/**
 * Holds the internal list of country-language mappings used for lookups within the package for
 * language code tk.
 *
 * This property contains a hardcoded list of [CountryLocalization] objects, each representing
 * a country and its associated official languages. This list is used by [CountryLanguageRegistry]
 * to provide access to country-language data and should not be modified directly.
 *
 * @see CountryLocalization
 * @see CountryLanguageRegistry
 */
internal val _countryLanguageMappings_tk: List<CountryLocalization> = listOf(
  CountryLocalization("af", "pars dili", "Owganystan"),
  CountryLocalization("al", "alban dili", "Albaniýa"),
  CountryLocalization("dz", "fransuz dili", "Alžir"),
  CountryLocalization("as", "iňlis dili", "Amerikan Samoasy"),
  CountryLocalization("ad", "katalan dili", "Andorra"),
  CountryLocalization("ao", "lingala dili", "Angola"),
  CountryLocalization("ai", "iňlis dili", "Angilýa"),
  CountryLocalization("ag", "iňlis dili", "Antigua we Barbuda"),
  CountryLocalization("ar", "ispan dili", "Argentina"),
  CountryLocalization("am", "ermeni dili", "Ermenistan"),
  CountryLocalization("aw", "niderland dili", "Aruba"),
  CountryLocalization("au", "iňlis dili", "Awstraliýa"),
  CountryLocalization("at", "iňlis dili", "Awstriýa"),
  CountryLocalization("az", "azerbaýjan dili", "Azerbaýjan"),
  CountryLocalization("bs", "iňlis dili", "Bagama adalary"),
  CountryLocalization("bh", "arap dili", "Bahreýn"),
  CountryLocalization("bd", "bengal dili", "Bangladeş"),
  CountryLocalization("bb", "iňlis dili", "Barbadow"),
  CountryLocalization("by", "belarus dili", "Belarus"),
  CountryLocalization("be", "fransuz dili", "Belgiýa"),
  CountryLocalization("bz", "iňlis dili", "Beliz"),
  CountryLocalization("bj", "fransuz dili", "Benin"),
  CountryLocalization("bm", "iňlis dili", "Bermuda"),
  CountryLocalization("bt", "dzong-ke dili", "Butan"),
  CountryLocalization("bo", "ispan dili", "Boliwiýa"),
  CountryLocalization("ba", "boşnak dili", "Bosniýa we Gersegowina"),
  CountryLocalization("bw", "iňlis dili", "Botswana"),
  CountryLocalization("br", "portugal dili", "Braziliýa"),
  CountryLocalization("io", "iňlis dili", "Britaniýanyň Hint okeanyndaky territoriýalary"),
  CountryLocalization("vg", "iňlis dili", "Britan Wirgin adalary"),
  CountryLocalization("bn", "malaý dili", "Bruneý"),
  CountryLocalization("bg", "bolgar dili", "Bolgariýa"),
  CountryLocalization("bf", "fransuz dili", "Burkina-Faso"),
  CountryLocalization("bi", "fransuz dili", "Burundi"),
  CountryLocalization("kh", "khmer dili", "Kamboja"),
  CountryLocalization("cm", "basaa dili", "Kamerun"),
  CountryLocalization("ca", "fransuz dili", "Kanada"),
  CountryLocalization("ic", "ispan dili", "Kanar adalary"),
  CountryLocalization("cv", "kabuwerdianu dili", "Kabo-Werde"),
  CountryLocalization("bq", "niderland dili", "Karib Niderlandy"),
  CountryLocalization("ky", "iňlis dili", "Kaýman adalary"),
  CountryLocalization("cf", "lingala dili", "Orta Afrika Respublikasy"),
  CountryLocalization("ea", "ispan dili", "Seuta we Melilýa"),
  CountryLocalization("td", "arap dili", "Çad"),
  CountryLocalization("cl", "ispan dili", "Çili"),
  CountryLocalization("cn", "tibet dili", "Hytaý"),
  CountryLocalization("cx", "iňlis dili", "Roždestwo adasy"),
  CountryLocalization("cc", "iňlis dili", "Kokos (Kiling) adalary"),
  CountryLocalization("co", "ispan dili", "Kolumbiýa"),
  CountryLocalization("km", "arap dili", "Komor Adalary"),
  CountryLocalization("cg", "lingala dili", "Kongo - Brazzawil"),
  CountryLocalization("cd", "suahili dili", "Kongo - Kinşasa"),
  CountryLocalization("ck", "iňlis dili", "Kuk adalary"),
  CountryLocalization("cr", "ispan dili", "Kosta-Rika"),
  CountryLocalization("hr", "horwat dili", "Horwatiýa"),
  CountryLocalization("cu", "ispan dili", "Kuba"),
  CountryLocalization("cw", "niderland dili", "Kýurasao"),
  CountryLocalization("cy", "iňlis dili", "Kipr"),
  CountryLocalization("cz", "çeh dili", "Çehiýa"),
  CountryLocalization("ci", "fransuz dili", "Kot-d’Iwuar"),
  CountryLocalization("dk", "iňlis dili", "Daniýa"),
  CountryLocalization("dg", "iňlis dili", "Diýego-Garsiýa"),
  CountryLocalization("dj", "fransuz dili", "Jibuti"),
  CountryLocalization("dm", "iňlis dili", "Dominika"),
  CountryLocalization("do", "ispan dili", "Dominikan Respublikasy"),
  CountryLocalization("ec", "keçua dili", "Ekwador"),
  CountryLocalization("eg", "arap dili", "Müsür"),
  CountryLocalization("sv", "ispan dili", "Salwador"),
  CountryLocalization("gq", "ispan dili", "Ekwatorial Gwineýa"),
  CountryLocalization("er", "tigrinýa dili", "Eritreýa"),
  CountryLocalization("ee", "eston dili", "Estoniýa"),
  CountryLocalization("et", "amhar dili", "Efiopiýa"),
  CountryLocalization("fk", "iňlis dili", "Folklend adalary"),
  CountryLocalization("fo", "farer dili", "Farer adalary"),
  CountryLocalization("fj", "iňlis dili", "Fiji"),
  CountryLocalization("fi", "şwed dili", "Finlandiýa"),
  CountryLocalization("fr", "nemes dili (Şweýsariýa)", "Fransiýa"),
  CountryLocalization("gf", "fransuz dili", "Fransuz Gwianasy"),
  CountryLocalization("pf", "fransuz dili", "Fransuz Polineziýasy"),
  CountryLocalization("ga", "fransuz dili", "Gabon"),
  CountryLocalization("gm", "iňlis dili", "Gambiýa"),
  CountryLocalization("ge", "osetin dili", "Gruziýa"),
  CountryLocalization("de", "aşaky lužits dili", "Germaniýa"),
  CountryLocalization("gh", "iňlis dili", "Gana"),
  CountryLocalization("gi", "iňlis dili", "Gibraltar"),
  CountryLocalization("gr", "grek dili", "Gresiýa"),
  CountryLocalization("gl", "grenland dili", "Grenlandiýa"),
  CountryLocalization("gd", "iňlis dili", "Grenada"),
  CountryLocalization("gp", "fransuz dili", "Gwadelupa"),
  CountryLocalization("gu", "iňlis dili", "Guam"),
  CountryLocalization("gt", "ispan dili", "Gwatemala"),
  CountryLocalization("gg", "iňlis dili", "Gernsi"),
  CountryLocalization("gn", "fransuz dili", "Gwineýa"),
  CountryLocalization("gw", "portugal dili", "Gwineýa-Bisau"),
  CountryLocalization("gy", "iňlis dili", "Gaýana"),
  CountryLocalization("ht", "fransuz dili", "Gaiti"),
  CountryLocalization("hn", "ispan dili", "Gonduras"),
  CountryLocalization("hk", "hytaý dili", "Gonkong AAS Hytaý"),
  CountryLocalization("hu", "wenger dili", "Wengriýa"),
  CountryLocalization("is", "island dili", "Islandiýa"),
  CountryLocalization("in", "nepal dili", "Hindistan"),
  CountryLocalization("id", "Indonesian", "Indoneziýa"),
  CountryLocalization("ir", "pars dili", "Eýran"),
  CountryLocalization("iq", "demirgazyk luri dili", "Yrak"),
  CountryLocalization("ie", "iňlis dili", "Irlandiýa"),
  CountryLocalization("im", "men dili", "Men adasy"),
  CountryLocalization("il", "iňlis dili", "Ysraýyl"),
  CountryLocalization("it", "nemes dili", "Italiýa"),
  CountryLocalization("jm", "iňlis dili", "Ýamaýka"),
  CountryLocalization("jp", "ýapon dili", "Ýaponiýa"),
  CountryLocalization("je", "iňlis dili", "Jersi"),
  CountryLocalization("jo", "arap dili", "Iordaniýa"),
  CountryLocalization("kz", "gazak dili", "Gazagystan"),
  CountryLocalization("ke", "somali dili", "Keniýa"),
  CountryLocalization("ki", "iňlis dili", "Kiribati"),
  CountryLocalization("xk", "serb dili", "Kosowo"),
  CountryLocalization("kw", "arap dili", "Kuweýt"),
  CountryLocalization("kg", "rus dili", "Gyrgyzystan"),
  CountryLocalization("la", "laos dili", "Laos"),
  CountryLocalization("lv", "latyş dili", "Latwiýa"),
  CountryLocalization("lb", "arap dili", "Liwan"),
  CountryLocalization("ls", "iňlis dili", "Lesoto"),
  CountryLocalization("lr", "iňlis dili", "Liberiýa"),
  CountryLocalization("ly", "arap dili", "Liwiýa"),
  CountryLocalization("li", "nemes dili (Şweýsariýa)", "Lihtenşteýn"),
  CountryLocalization("lt", "litwa dili", "Litwa"),
  CountryLocalization("lu", "lýuksemburg dili", "Lýuksemburg"),
  CountryLocalization("mo", "portugal dili", "Makau AAS Hytaý"),
  CountryLocalization("mk", "alban dili", "Makedoniýa"),
  CountryLocalization("mg", "fransuz dili", "Madagaskar"),
  CountryLocalization("mw", "iňlis dili", "Malawi"),
  CountryLocalization("my", "tamil dili", "Malaýziýa"),
  CountryLocalization("ml", "fransuz dili", "Mali"),
  CountryLocalization("mt", "iňlis dili", "Malta"),
  CountryLocalization("mh", "iňlis dili", "Marşall adalary"),
  CountryLocalization("mq", "fransuz dili", "Martinika"),
  CountryLocalization("mr", "arap dili", "Mawritaniýa"),
  CountryLocalization("mu", "morisýen dili", "Mawrikiý"),
  CountryLocalization("yt", "fransuz dili", "Maýotta"),
  CountryLocalization("mx", "ispan dili", "Meksika"),
  CountryLocalization("fm", "iňlis dili", "Mikroneziýa"),
  CountryLocalization("md", "rus dili", "Moldowa"),
  CountryLocalization("mc", "fransuz dili", "Monako"),
  CountryLocalization("mn", "mongol dili", "Mongoliýa"),
  CountryLocalization("me", "serb dili", "Montenegro"),
  CountryLocalization("ms", "iňlis dili", "Monserrat"),
  CountryLocalization("ma", "orta-Atlas tamazight dili", "Marokko"),
  CountryLocalization("mz", "makua-Mitto dili", "Mozambik"),
  CountryLocalization("mm", "birma dili", "Mýanma (Burma)"),
  CountryLocalization("na", "iňlis dili", "Namibiýa"),
  CountryLocalization("nr", "iňlis dili", "Nauru"),
  CountryLocalization("np", "nepal dili", "Nepal"),
  CountryLocalization("nl", "iňlis dili", "Niderlandiýa"),
  CountryLocalization("nc", "fransuz dili", "Täze Kaledoniýa"),
  CountryLocalization("nz", "iňlis dili", "Täze Zelandiýa"),
  CountryLocalization("ni", "ispan dili", "Nikaragua"),
  CountryLocalization("ne", "hausa dili", "Niger"),
  CountryLocalization("ng", "hausa dili", "Nigeriýa"),
  CountryLocalization("nu", "iňlis dili", "Niue"),
  CountryLocalization("nf", "iňlis dili", "Norfolk adasy"),
  CountryLocalization("kp", "koreý dili", "Demirgazyk Koreýa"),
  CountryLocalization("mp", "iňlis dili", "Demirgazyk Mariana adalary"),
  CountryLocalization("no", "demirgazyk saam dili", "Norwegiýa"),
  CountryLocalization("om", "arap dili", "Oman"),
  CountryLocalization("pk", "iňlis dili", "Pakistan"),
  CountryLocalization("pw", "iňlis dili", "Palau"),
  CountryLocalization("ps", "arap dili", "Palestina territoriýasy"),
  CountryLocalization("pa", "ispan dili", "Panama"),
  CountryLocalization("pg", "iňlis dili", "Papua - Täze Gwineýa"),
  CountryLocalization("py", "ispan dili", "Paragwaý"),
  CountryLocalization("pe", "ispan dili", "Peru"),
  CountryLocalization("ph", "filippin dili", "Filippinler"),
  CountryLocalization("pn", "iňlis dili", "Pitkern adalary"),
  CountryLocalization("pl", "polýak dili", "Polşa"),
  CountryLocalization("pt", "portugal dili", "Portugaliýa"),
  CountryLocalization("pr", "iňlis dili", "Puerto-Riko"),
  CountryLocalization("qa", "arap dili", "Katar"),
  CountryLocalization("ro", "rumyn dili", "Rumyniýa"),
  CountryLocalization("ru", "tatar dili", "Russiýa"),
  CountryLocalization("rw", "iňlis dili", "Ruanda"),
  CountryLocalization("re", "fransuz dili", "Reýunýon"),
  CountryLocalization("ws", "iňlis dili", "Samoa"),
  CountryLocalization("sm", "italýan dili", "San-Marino"),
  CountryLocalization("sa", "arap dili", "Saud Arabystany"),
  CountryLocalization("sn", "fransuz dili", "Senegal"),
  CountryLocalization("rs", "serb dili", "Serbiýa"),
  CountryLocalization("cs", "serb dili", "Serbia and Montenegro"),
  CountryLocalization("sc", "fransuz dili", "Seýşel Adalary"),
  CountryLocalization("sl", "iňlis dili", "Sýerra-Leone"),
  CountryLocalization("sg", "tamil dili", "Singapur"),
  CountryLocalization("sx", "iňlis dili", "Sint-Marten"),
  CountryLocalization("sk", "slowak dili", "Slowakiýa"),
  CountryLocalization("si", "slowen dili", "Sloweniýa"),
  CountryLocalization("sb", "iňlis dili", "Solomon adalary"),
  CountryLocalization("so", "arap dili", "Somali"),
  CountryLocalization("za", "iňlis dili", "Günorta Afrika"),
  CountryLocalization("kr", "koreý dili", "Günorta Koreýa"),
  CountryLocalization("ss", "nuer dili", "Günorta Sudan"),
  CountryLocalization("es", "ispan dili", "Ispaniýa"),
  CountryLocalization("lk", "tamil dili", "Şri-Lanka"),
  CountryLocalization("bl", "fransuz dili", "Sen-Bartelemi"),
  CountryLocalization("sh", "iňlis dili", "Keramatly Ýelena adasy"),
  CountryLocalization("kn", "iňlis dili", "Sent-Kits we Newis"),
  CountryLocalization("lc", "iňlis dili", "Sent-Lýusiýa"),
  CountryLocalization("mf", "fransuz dili", "Sen-Marten"),
  CountryLocalization("pm", "fransuz dili", "Sen-Pýer we Mikelon"),
  CountryLocalization("vc", "iňlis dili", "Sent-Winsent we Grenadinler"),
  CountryLocalization("sd", "arap dili", "Sudan"),
  CountryLocalization("sr", "niderland dili", "Surinam"),
  CountryLocalization("sj", "norwegiýa bukmol dili", "Şpisbergen we Ýan-Maýen"),
  CountryLocalization("sz", "iňlis dili", "Swazilend"),
  CountryLocalization("se", "şwed dili", "Şwesiýa"),
  CountryLocalization("ch", "nemes dili (Şweýsariýa)", "Şweýsariýa"),
  CountryLocalization("sy", "arap dili", "Siriýa"),
  CountryLocalization("st", "portugal dili", "San-Tome we Prinsipi"),
  CountryLocalization("tw", "hytaý dili", "Taýwan"),
  CountryLocalization("tj", "täjik dili", "Täjigistan"),
  CountryLocalization("tz", "makonde dili", "Tanzaniýa"),
  CountryLocalization("th", "taý dili", "Taýland"),
  CountryLocalization("tl", "portugal dili", "Timor-Leste"),
  CountryLocalization("tg", "fransuz dili", "Togo"),
  CountryLocalization("tk", "iňlis dili", "Tokelau"),
  CountryLocalization("to", "tongan dili", "Tonga"),
  CountryLocalization("tt", "iňlis dili", "Trinidad we Tobago"),
  CountryLocalization("tn", "fransuz dili", "Tunis"),
  CountryLocalization("tr", "türk dili", "Türkiýe"),
  CountryLocalization("tm", "türkmen dili", "Türkmenistan"),
  CountryLocalization("tc", "iňlis dili", "Terks we Kaýkos adalary"),
  CountryLocalization("tv", "iňlis dili", "Tuwalu"),
  CountryLocalization("um", "iňlis dili", "ABŞ-nyň daşarky adalary"),
  CountryLocalization("vi", "iňlis dili", "ABŞ-nyň Wirgin adalary"),
  CountryLocalization("ug", "suahili dili", "Uganda"),
  CountryLocalization("ua", "ukrain dili", "Ukraina"),
  CountryLocalization("ae", "arap dili", "Birleşen Arap Emirlikleri"),
  CountryLocalization("gb", "iňlis dili", "Birleşen Patyşalyk"),
  CountryLocalization("us", "lakota dili", "Amerikanyň Birleşen Ştatlary"),
  CountryLocalization("uy", "ispan dili", "Urugwaý"),
  CountryLocalization("uz", "özbek dili", "Özbegistan"),
  CountryLocalization("vu", "fransuz dili", "Wanuatu"),
  CountryLocalization("va", "italýan dili", "Watikan"),
  CountryLocalization("ve", "ispan dili", "Wenesuela"),
  CountryLocalization("vn", "wýetnam dili", "Wýetnam"),
  CountryLocalization("wf", "fransuz dili", "Uollis we Futuna"),
  CountryLocalization("eh", "arap dili", "Günbatar Sahara"),
  CountryLocalization("ye", "arap dili", "Ýemen"),
  CountryLocalization("zm", "iňlis dili", "Zambiýa"),
  CountryLocalization("zw", "demirgazyk ndebele dili", "Zimbabwe"),
  CountryLocalization("ax", "şwed dili", "Aland adalary"),
)
