/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot.atlas.extended

import dev.teogor.xenoglot.atlas.CountryLocalization
import kotlin.collections.List

/**
 * Holds the internal list of country-language mappings used for lookups within the package for
 * language code vi.
 *
 * This property contains a hardcoded list of [CountryLocalization] objects, each representing
 * a country and its associated official languages. This list is used by [CountryLanguageRegistry]
 * to provide access to country-language data and should not be modified directly.
 *
 * @see CountryLocalization
 * @see CountryLanguageRegistry
 */
internal val _countryLanguageMappings_vi: List<CountryLocalization> = listOf(
  CountryLocalization("af", "Tiếng Ba Tư", "Afghanistan"),
  CountryLocalization("al", "Tiếng Albania", "Albania"),
  CountryLocalization("dz", "Tiếng Pháp", "Algeria"),
  CountryLocalization("as", "Tiếng Anh", "Samoa thuộc Mỹ"),
  CountryLocalization("ad", "Tiếng Catalan", "Andorra"),
  CountryLocalization("ao", "Tiếng Lingala", "Angola"),
  CountryLocalization("ai", "Tiếng Anh", "Anguilla"),
  CountryLocalization("ag", "Tiếng Anh", "Antigua và Barbuda"),
  CountryLocalization("ar", "Tiếng Tây Ban Nha", "Argentina"),
  CountryLocalization("am", "Tiếng Armenia", "Armenia"),
  CountryLocalization("aw", "Tiếng Hà Lan", "Aruba"),
  CountryLocalization("au", "Tiếng Anh", "Australia"),
  CountryLocalization("at", "Tiếng Anh", "Áo"),
  CountryLocalization("az", "Tiếng Azerbaijan", "Azerbaijan"),
  CountryLocalization("bs", "Tiếng Anh", "Bahamas"),
  CountryLocalization("bh", "Tiếng Ả Rập", "Bahrain"),
  CountryLocalization("bd", "Tiếng Bangla", "Bangladesh"),
  CountryLocalization("bb", "Tiếng Anh", "Barbados"),
  CountryLocalization("by", "Tiếng Belarus", "Belarus"),
  CountryLocalization("be", "Tiếng Pháp", "Bỉ"),
  CountryLocalization("bz", "Tiếng Anh", "Belize"),
  CountryLocalization("bj", "Tiếng Pháp", "Benin"),
  CountryLocalization("bm", "Tiếng Anh", "Bermuda"),
  CountryLocalization("bt", "Tiếng Dzongkha", "Bhutan"),
  CountryLocalization("bo", "Tiếng Tây Ban Nha", "Bolivia"),
  CountryLocalization("ba", "Tiếng Bosnia", "Bosnia và Herzegovina"),
  CountryLocalization("bw", "Tiếng Anh", "Botswana"),
  CountryLocalization("br", "Tiếng Bồ Đào Nha", "Brazil"),
  CountryLocalization("io", "Tiếng Anh", "Lãnh thổ Ấn độ dương thuộc Anh"),
  CountryLocalization("vg", "Tiếng Anh", "Quần đảo Virgin thuộc Anh"),
  CountryLocalization("bn", "Tiếng Mã Lai", "Brunei"),
  CountryLocalization("bg", "Tiếng Bulgaria", "Bulgaria"),
  CountryLocalization("bf", "Tiếng Pháp", "Burkina Faso"),
  CountryLocalization("bi", "Tiếng Pháp", "Burundi"),
  CountryLocalization("kh", "Tiếng Khmer", "Campuchia"),
  CountryLocalization("cm", "Tiếng Basaa", "Cameroon"),
  CountryLocalization("ca", "Tiếng Pháp", "Canada"),
  CountryLocalization("ic", "Tiếng Tây Ban Nha", "Quần đảo Canary"),
  CountryLocalization("cv", "Tiếng Kabuverdianu", "Cape Verde"),
  CountryLocalization("bq", "Tiếng Hà Lan", "Ca-ri-bê Hà Lan"),
  CountryLocalization("ky", "Tiếng Anh", "Quần đảo Cayman"),
  CountryLocalization("cf", "Tiếng Lingala", "Cộng hòa Trung Phi"),
  CountryLocalization("ea", "Tiếng Tây Ban Nha", "Ceuta và Melilla"),
  CountryLocalization("td", "Tiếng Ả Rập", "Chad"),
  CountryLocalization("cl", "Tiếng Tây Ban Nha", "Chile"),
  CountryLocalization("cn", "Tiếng Tây Tạng", "Trung Quốc"),
  CountryLocalization("cx", "Tiếng Anh", "Đảo Giáng Sinh"),
  CountryLocalization("cc", "Tiếng Anh", "Quần đảo Cocos (Keeling)"),
  CountryLocalization("co", "Tiếng Tây Ban Nha", "Colombia"),
  CountryLocalization("km", "Tiếng Ả Rập", "Comoros"),
  CountryLocalization("cg", "Tiếng Lingala", "Congo - Brazzaville"),
  CountryLocalization("cd", "Tiếng Swahili", "Congo - Kinshasa"),
  CountryLocalization("ck", "Tiếng Anh", "Quần đảo Cook"),
  CountryLocalization("cr", "Tiếng Tây Ban Nha", "Costa Rica"),
  CountryLocalization("hr", "Tiếng Croatia", "Croatia"),
  CountryLocalization("cu", "Tiếng Tây Ban Nha", "Cuba"),
  CountryLocalization("cw", "Tiếng Hà Lan", "Curaçao"),
  CountryLocalization("cy", "Tiếng Anh", "Síp"),
  CountryLocalization("cz", "Tiếng Séc", "Séc"),
  CountryLocalization("ci", "Tiếng Pháp", "Côte d’Ivoire"),
  CountryLocalization("dk", "Tiếng Anh", "Đan Mạch"),
  CountryLocalization("dg", "Tiếng Anh", "Diego Garcia"),
  CountryLocalization("dj", "Tiếng Pháp", "Djibouti"),
  CountryLocalization("dm", "Tiếng Anh", "Dominica"),
  CountryLocalization("do", "Tiếng Tây Ban Nha", "Cộng hòa Dominica"),
  CountryLocalization("ec", "Tiếng Quechua", "Ecuador"),
  CountryLocalization("eg", "Tiếng Ả Rập", "Ai Cập"),
  CountryLocalization("sv", "Tiếng Tây Ban Nha", "El Salvador"),
  CountryLocalization("gq", "Tiếng Tây Ban Nha", "Guinea Xích Đạo"),
  CountryLocalization("er", "Tiếng Tigrinya", "Eritrea"),
  CountryLocalization("ee", "Tiếng Estonia", "Estonia"),
  CountryLocalization("et", "Tiếng Amharic", "Ethiopia"),
  CountryLocalization("fk", "Tiếng Anh", "Quần đảo Falkland"),
  CountryLocalization("fo", "Tiếng Faroe", "Quần đảo Faroe"),
  CountryLocalization("fj", "Tiếng Anh", "Fiji"),
  CountryLocalization("fi", "Tiếng Thụy Điển", "Phần Lan"),
  CountryLocalization("fr", "Tiếng Đức (Thụy Sĩ)", "Pháp"),
  CountryLocalization("gf", "Tiếng Pháp", "Guiana thuộc Pháp"),
  CountryLocalization("pf", "Tiếng Pháp", "Polynesia thuộc Pháp"),
  CountryLocalization("ga", "Tiếng Pháp", "Gabon"),
  CountryLocalization("gm", "Tiếng Anh", "Gambia"),
  CountryLocalization("ge", "Tiếng Ossetic", "Gruzia"),
  CountryLocalization("de", "Tiếng Hạ Sorbia", "Đức"),
  CountryLocalization("gh", "Tiếng Anh", "Ghana"),
  CountryLocalization("gi", "Tiếng Anh", "Gibraltar"),
  CountryLocalization("gr", "Tiếng Hy Lạp", "Hy Lạp"),
  CountryLocalization("gl", "Tiếng Kalaallisut", "Greenland"),
  CountryLocalization("gd", "Tiếng Anh", "Grenada"),
  CountryLocalization("gp", "Tiếng Pháp", "Guadeloupe"),
  CountryLocalization("gu", "Tiếng Anh", "Guam"),
  CountryLocalization("gt", "Tiếng Tây Ban Nha", "Guatemala"),
  CountryLocalization("gg", "Tiếng Anh", "Guernsey"),
  CountryLocalization("gn", "Tiếng Pháp", "Guinea"),
  CountryLocalization("gw", "Tiếng Bồ Đào Nha", "Guinea-Bissau"),
  CountryLocalization("gy", "Tiếng Anh", "Guyana"),
  CountryLocalization("ht", "Tiếng Pháp", "Haiti"),
  CountryLocalization("hn", "Tiếng Tây Ban Nha", "Honduras"),
  CountryLocalization("hk", "Tiếng Trung", "Hồng Kông, Trung Quốc"),
  CountryLocalization("hu", "Tiếng Hungary", "Hungary"),
  CountryLocalization("is", "Tiếng Iceland", "Iceland"),
  CountryLocalization("in", "Tiếng Nepal", "Ấn Độ"),
  CountryLocalization("id", "Indonesian", "Indonesia"),
  CountryLocalization("ir", "Tiếng Ba Tư", "Iran"),
  CountryLocalization("iq", "Tiếng Bắc Luri", "Iraq"),
  CountryLocalization("ie", "Tiếng Anh", "Ireland"),
  CountryLocalization("im", "Tiếng Manx", "Đảo Man"),
  CountryLocalization("il", "Tiếng Anh", "Israel"),
  CountryLocalization("it", "Tiếng Đức", "Italy"),
  CountryLocalization("jm", "Tiếng Anh", "Jamaica"),
  CountryLocalization("jp", "Tiếng Nhật", "Nhật Bản"),
  CountryLocalization("je", "Tiếng Anh", "Jersey"),
  CountryLocalization("jo", "Tiếng Ả Rập", "Jordan"),
  CountryLocalization("kz", "Tiếng Kazakh", "Kazakhstan"),
  CountryLocalization("ke", "Tiếng Somali", "Kenya"),
  CountryLocalization("ki", "Tiếng Anh", "Kiribati"),
  CountryLocalization("xk", "Tiếng Serbia", "Kosovo"),
  CountryLocalization("kw", "Tiếng Ả Rập", "Kuwait"),
  CountryLocalization("kg", "Tiếng Nga", "Kyrgyzstan"),
  CountryLocalization("la", "Tiếng Lào", "Lào"),
  CountryLocalization("lv", "Tiếng Latvia", "Latvia"),
  CountryLocalization("lb", "Tiếng Ả Rập", "Li-băng"),
  CountryLocalization("ls", "Tiếng Anh", "Lesotho"),
  CountryLocalization("lr", "Tiếng Anh", "Liberia"),
  CountryLocalization("ly", "Tiếng Ả Rập", "Libya"),
  CountryLocalization("li", "Tiếng Đức (Thụy Sĩ)", "Liechtenstein"),
  CountryLocalization("lt", "Tiếng Litva", "Litva"),
  CountryLocalization("lu", "Tiếng Luxembourg", "Luxembourg"),
  CountryLocalization("mo", "Tiếng Bồ Đào Nha", "Macao, Trung Quốc"),
  CountryLocalization("mk", "Tiếng Albania", "Macedonia"),
  CountryLocalization("mg", "Tiếng Pháp", "Madagascar"),
  CountryLocalization("mw", "Tiếng Anh", "Malawi"),
  CountryLocalization("my", "Tiếng Tamil", "Malaysia"),
  CountryLocalization("ml", "Tiếng Pháp", "Mali"),
  CountryLocalization("mt", "Tiếng Anh", "Malta"),
  CountryLocalization("mh", "Tiếng Anh", "Quần đảo Marshall"),
  CountryLocalization("mq", "Tiếng Pháp", "Martinique"),
  CountryLocalization("mr", "Tiếng Ả Rập", "Mauritania"),
  CountryLocalization("mu", "Tiếng Morisyen", "Mauritius"),
  CountryLocalization("yt", "Tiếng Pháp", "Mayotte"),
  CountryLocalization("mx", "Tiếng Tây Ban Nha", "Mexico"),
  CountryLocalization("fm", "Tiếng Anh", "Micronesia"),
  CountryLocalization("md", "Tiếng Nga", "Moldova"),
  CountryLocalization("mc", "Tiếng Pháp", "Monaco"),
  CountryLocalization("mn", "Tiếng Mông Cổ", "Mông Cổ"),
  CountryLocalization("me", "Tiếng Serbia", "Montenegro"),
  CountryLocalization("ms", "Tiếng Anh", "Montserrat"),
  CountryLocalization("ma", "Tiếng Tamazight Miền Trung Ma-rốc", "Ma-rốc"),
  CountryLocalization("mz", "Tiếng Makhuwa-Meetto", "Mozambique"),
  CountryLocalization("mm", "Tiếng Miến Điện", "Myanmar (Miến Điện)"),
  CountryLocalization("na", "Tiếng Anh", "Namibia"),
  CountryLocalization("nr", "Tiếng Anh", "Nauru"),
  CountryLocalization("np", "Tiếng Nepal", "Nepal"),
  CountryLocalization("nl", "Tiếng Anh", "Hà Lan"),
  CountryLocalization("nc", "Tiếng Pháp", "New Caledonia"),
  CountryLocalization("nz", "Tiếng Anh", "New Zealand"),
  CountryLocalization("ni", "Tiếng Tây Ban Nha", "Nicaragua"),
  CountryLocalization("ne", "Tiếng Hausa", "Niger"),
  CountryLocalization("ng", "Tiếng Hausa", "Nigeria"),
  CountryLocalization("nu", "Tiếng Anh", "Niue"),
  CountryLocalization("nf", "Tiếng Anh", "Đảo Norfolk"),
  CountryLocalization("kp", "Tiếng Hàn", "Triều Tiên"),
  CountryLocalization("mp", "Tiếng Anh", "Quần đảo Bắc Mariana"),
  CountryLocalization("no", "Tiếng Sami Miền Bắc", "Na Uy"),
  CountryLocalization("om", "Tiếng Ả Rập", "Oman"),
  CountryLocalization("pk", "Tiếng Anh", "Pakistan"),
  CountryLocalization("pw", "Tiếng Anh", "Palau"),
  CountryLocalization("ps", "Tiếng Ả Rập", "Lãnh thổ Palestine"),
  CountryLocalization("pa", "Tiếng Tây Ban Nha", "Panama"),
  CountryLocalization("pg", "Tiếng Anh", "Papua New Guinea"),
  CountryLocalization("py", "Tiếng Tây Ban Nha", "Paraguay"),
  CountryLocalization("pe", "Tiếng Tây Ban Nha", "Peru"),
  CountryLocalization("ph", "Tiếng Philippines", "Philippines"),
  CountryLocalization("pn", "Tiếng Anh", "Quần đảo Pitcairn"),
  CountryLocalization("pl", "Tiếng Ba Lan", "Ba Lan"),
  CountryLocalization("pt", "Tiếng Bồ Đào Nha", "Bồ Đào Nha"),
  CountryLocalization("pr", "Tiếng Anh", "Puerto Rico"),
  CountryLocalization("qa", "Tiếng Ả Rập", "Qatar"),
  CountryLocalization("ro", "Tiếng Romania", "Romania"),
  CountryLocalization("ru", "Tiếng Tatar", "Nga"),
  CountryLocalization("rw", "Tiếng Anh", "Rwanda"),
  CountryLocalization("re", "Tiếng Pháp", "Réunion"),
  CountryLocalization("ws", "Tiếng Anh", "Samoa"),
  CountryLocalization("sm", "Tiếng Italy", "San Marino"),
  CountryLocalization("sa", "Tiếng Ả Rập", "Ả Rập Xê-út"),
  CountryLocalization("sn", "Tiếng Pháp", "Senegal"),
  CountryLocalization("rs", "Tiếng Serbia", "Serbia"),
  CountryLocalization("cs", "Tiếng Serbia", "Serbia and Montenegro"),
  CountryLocalization("sc", "Tiếng Pháp", "Seychelles"),
  CountryLocalization("sl", "Tiếng Anh", "Sierra Leone"),
  CountryLocalization("sg", "Tiếng Tamil", "Singapore"),
  CountryLocalization("sx", "Tiếng Anh", "Sint Maarten"),
  CountryLocalization("sk", "Tiếng Slovak", "Slovakia"),
  CountryLocalization("si", "Tiếng Slovenia", "Slovenia"),
  CountryLocalization("sb", "Tiếng Anh", "Quần đảo Solomon"),
  CountryLocalization("so", "Tiếng Ả Rập", "Somalia"),
  CountryLocalization("za", "Tiếng Anh", "Nam Phi"),
  CountryLocalization("kr", "Tiếng Hàn", "Hàn Quốc"),
  CountryLocalization("ss", "Tiếng Nuer", "Nam Sudan"),
  CountryLocalization("es", "Tiếng Tây Ban Nha", "Tây Ban Nha"),
  CountryLocalization("lk", "Tiếng Tamil", "Sri Lanka"),
  CountryLocalization("bl", "Tiếng Pháp", "St. Barthélemy"),
  CountryLocalization("sh", "Tiếng Anh", "St. Helena"),
  CountryLocalization("kn", "Tiếng Anh", "St. Kitts và Nevis"),
  CountryLocalization("lc", "Tiếng Anh", "St. Lucia"),
  CountryLocalization("mf", "Tiếng Pháp", "St. Martin"),
  CountryLocalization("pm", "Tiếng Pháp", "Saint Pierre và Miquelon"),
  CountryLocalization("vc", "Tiếng Anh", "St. Vincent và Grenadines"),
  CountryLocalization("sd", "Tiếng Ả Rập", "Sudan"),
  CountryLocalization("sr", "Tiếng Hà Lan", "Suriname"),
  CountryLocalization("sj", "Tiếng Na Uy (Bokmål)", "Svalbard và Jan Mayen"),
  CountryLocalization("sz", "Tiếng Anh", "Swaziland"),
  CountryLocalization("se", "Tiếng Thụy Điển", "Thụy Điển"),
  CountryLocalization("ch", "Tiếng Đức (Thụy Sĩ)", "Thụy Sĩ"),
  CountryLocalization("sy", "Tiếng Ả Rập", "Syria"),
  CountryLocalization("st", "Tiếng Bồ Đào Nha", "São Tomé và Príncipe"),
  CountryLocalization("tw", "Tiếng Trung", "Đài Loan"),
  CountryLocalization("tj", "Tiếng Tajik", "Tajikistan"),
  CountryLocalization("tz", "Tiếng Makonde", "Tanzania"),
  CountryLocalization("th", "Tiếng Thái", "Thái Lan"),
  CountryLocalization("tl", "Tiếng Bồ Đào Nha", "Timor-Leste"),
  CountryLocalization("tg", "Tiếng Pháp", "Togo"),
  CountryLocalization("tk", "Tiếng Anh", "Tokelau"),
  CountryLocalization("to", "Tiếng Tonga", "Tonga"),
  CountryLocalization("tt", "Tiếng Anh", "Trinidad và Tobago"),
  CountryLocalization("tn", "Tiếng Pháp", "Tunisia"),
  CountryLocalization("tr", "Tiếng Thổ Nhĩ Kỳ", "Thổ Nhĩ Kỳ"),
  CountryLocalization("tm", "Tiếng Turkmen", "Turkmenistan"),
  CountryLocalization("tc", "Tiếng Anh", "Quần đảo Turks và Caicos"),
  CountryLocalization("tv", "Tiếng Anh", "Tuvalu"),
  CountryLocalization("um", "Tiếng Anh", "Các tiểu đảo xa của Hoa Kỳ"),
  CountryLocalization("vi", "Tiếng Anh", "Quần đảo Virgin thuộc Mỹ"),
  CountryLocalization("ug", "Tiếng Swahili", "Uganda"),
  CountryLocalization("ua", "Tiếng Ucraina", "Ukraina"),
  CountryLocalization("ae", "Tiếng Ả Rập", "Các Tiểu Vương quốc Ả Rập Thống nhất"),
  CountryLocalization("gb", "Tiếng Anh", "Vương quốc Anh"),
  CountryLocalization("us", "Tiếng Lakota", "Hoa Kỳ"),
  CountryLocalization("uy", "Tiếng Tây Ban Nha", "Uruguay"),
  CountryLocalization("uz", "Tiếng Uzbek", "Uzbekistan"),
  CountryLocalization("vu", "Tiếng Pháp", "Vanuatu"),
  CountryLocalization("va", "Tiếng Italy", "Thành Vatican"),
  CountryLocalization("ve", "Tiếng Tây Ban Nha", "Venezuela"),
  CountryLocalization("vn", "Tiếng Việt", "Việt Nam"),
  CountryLocalization("wf", "Tiếng Pháp", "Wallis và Futuna"),
  CountryLocalization("eh", "Tiếng Ả Rập", "Tây Sahara"),
  CountryLocalization("ye", "Tiếng Ả Rập", "Yemen"),
  CountryLocalization("zm", "Tiếng Anh", "Zambia"),
  CountryLocalization("zw", "Tiếng Ndebele Miền Bắc", "Zimbabwe"),
  CountryLocalization("ax", "Tiếng Thụy Điển", "Quần đảo Åland"),
)
