/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot.atlas.extended

import dev.teogor.xenoglot.atlas.CountryLocalization
import kotlin.collections.List

/**
 * Holds the internal list of country-language mappings used for lookups within the package for
 * language code mn.
 *
 * This property contains a hardcoded list of [CountryLocalization] objects, each representing
 * a country and its associated official languages. This list is used by [CountryLanguageRegistry]
 * to provide access to country-language data and should not be modified directly.
 *
 * @see CountryLocalization
 * @see CountryLanguageRegistry
 */
internal val _countryLanguageMappings_mn: List<CountryLocalization> = listOf(
  CountryLocalization("af", "перс", "Афганистан"),
  CountryLocalization("al", "албани", "Албани"),
  CountryLocalization("dz", "франц", "Алжир"),
  CountryLocalization("as", "англи", "Америкийн Самоа"),
  CountryLocalization("ad", "каталан", "Андорра"),
  CountryLocalization("ao", "лингала", "Ангол"),
  CountryLocalization("ai", "англи", "Ангилья"),
  CountryLocalization("ag", "англи", "Антигуа ба Барбуда"),
  CountryLocalization("ar", "испани", "Аргентин"),
  CountryLocalization("am", "армен", "Армени"),
  CountryLocalization("aw", "нидерланд", "Аруба"),
  CountryLocalization("au", "англи", "Австрали"),
  CountryLocalization("at", "англи", "Австри"),
  CountryLocalization("az", "азербайжан", "Азербайжан"),
  CountryLocalization("bs", "англи", "Багамын арлууд"),
  CountryLocalization("bh", "араб", "Бахрейн"),
  CountryLocalization("bd", "бенгал", "Бангладеш"),
  CountryLocalization("bb", "англи", "Барбадос"),
  CountryLocalization("by", "беларусь", "Беларусь"),
  CountryLocalization("be", "франц", "Бельги"),
  CountryLocalization("bz", "англи", "Белиз"),
  CountryLocalization("bj", "франц", "Бенин"),
  CountryLocalization("bm", "англи", "Бермуда"),
  CountryLocalization("bt", "зонха", "Бутан"),
  CountryLocalization("bo", "испани", "Боливи"),
  CountryLocalization("ba", "босни", "Босни-Герцеговин"),
  CountryLocalization("bw", "англи", "Ботсвана"),
  CountryLocalization("br", "португал", "Бразил"),
  CountryLocalization("io", "англи", "Британийн харьяа Энэтхэгийн далай дахь нутаг дэвсгэр"),
  CountryLocalization("vg", "англи", "Британийн Виржиний Арлууд"),
  CountryLocalization("bn", "малай", "Бруней"),
  CountryLocalization("bg", "болгар", "Болгар"),
  CountryLocalization("bf", "франц", "Буркина Фасо"),
  CountryLocalization("bi", "франц", "Бурунди"),
  CountryLocalization("kh", "кхмер", "Камбож"),
  CountryLocalization("cm", "басаа", "Камерун"),
  CountryLocalization("ca", "франц", "Канад"),
  CountryLocalization("ic", "испани", "Канарын арлууд"),
  CountryLocalization("cv", "кабүвердиану", "Кабо-Верде"),
  CountryLocalization("bq", "нидерланд", "Карибын Нидерланд"),
  CountryLocalization("ky", "англи", "Кайманы арлууд"),
  CountryLocalization("cf", "лингала", "Төв Африкийн Бүгд Найрамдах Улс"),
  CountryLocalization("ea", "испани", "Сеута ба Мелилья"),
  CountryLocalization("td", "араб", "Чад"),
  CountryLocalization("cl", "испани", "Чили"),
  CountryLocalization("cn", "төвд", "Хятад"),
  CountryLocalization("cx", "англи", "Зул сарын арал"),
  CountryLocalization("cc", "англи", "Кокос (Кийлинг) арлууд"),
  CountryLocalization("co", "испани", "Колумби"),
  CountryLocalization("km", "араб", "Коморын арлууд"),
  CountryLocalization("cg", "лингала", "Конго Браззавиль"),
  CountryLocalization("cd", "свахили", "Конго-Киншаса"),
  CountryLocalization("ck", "англи", "Күүкийн арлууд"),
  CountryLocalization("cr", "испани", "Коста-Рика"),
  CountryLocalization("hr", "хорват", "Хорват"),
  CountryLocalization("cu", "испани", "Куба"),
  CountryLocalization("cw", "нидерланд", "Кюрасао"),
  CountryLocalization("cy", "англи", "Кипр"),
  CountryLocalization("cz", "чех", "Чех"),
  CountryLocalization("ci", "франц", "Кот-д’Ивуар"),
  CountryLocalization("dk", "англи", "Дани"),
  CountryLocalization("dg", "англи", "Диего Гарсиа"),
  CountryLocalization("dj", "франц", "Джибути"),
  CountryLocalization("dm", "англи", "Доминика"),
  CountryLocalization("do", "испани", "Бүгд Найрамдах Доминикан Улс"),
  CountryLocalization("ec", "кечуа", "Эквадор"),
  CountryLocalization("eg", "араб", "Египет"),
  CountryLocalization("sv", "испани", "Эль Сальвадор"),
  CountryLocalization("gq", "испани", "Экваторын Гвиней"),
  CountryLocalization("er", "тигринья", "Эритрей"),
  CountryLocalization("ee", "эстони", "Эстони"),
  CountryLocalization("et", "амхар", "Этиоп"),
  CountryLocalization("fk", "англи", "Фолклендийн арлууд"),
  CountryLocalization("fo", "фарер", "Фарерын арлууд"),
  CountryLocalization("fj", "англи", "Фижи"),
  CountryLocalization("fi", "швед", "Финланд"),
  CountryLocalization("fr", "швейцари-герман", "Франц"),
  CountryLocalization("gf", "франц", "Францын Гвиана"),
  CountryLocalization("pf", "франц", "Францын Полинез"),
  CountryLocalization("ga", "франц", "Габон"),
  CountryLocalization("gm", "англи", "Гамби"),
  CountryLocalization("ge", "оссетин", "Гүрж"),
  CountryLocalization("de", "доод сорби", "Герман"),
  CountryLocalization("gh", "англи", "Гана"),
  CountryLocalization("gi", "англи", "Гибралтар"),
  CountryLocalization("gr", "грек", "Грек"),
  CountryLocalization("gl", "калалисут", "Гренланд"),
  CountryLocalization("gd", "англи", "Гренада"),
  CountryLocalization("gp", "франц", "Гваделуп"),
  CountryLocalization("gu", "англи", "Гуам"),
  CountryLocalization("gt", "испани", "Гватемал"),
  CountryLocalization("gg", "англи", "Гернси"),
  CountryLocalization("gn", "франц", "Гвиней"),
  CountryLocalization("gw", "португал", "Гвиней-Бисау"),
  CountryLocalization("gy", "англи", "Гайана"),
  CountryLocalization("ht", "франц", "Гаити"),
  CountryLocalization("hn", "испани", "Гондурас"),
  CountryLocalization("hk", "хятад", "БНХАУ-ын Тусгай захиргааны бүс Хонг Конг"),
  CountryLocalization("hu", "унгар", "Унгар"),
  CountryLocalization("is", "исланд", "Исланд"),
  CountryLocalization("in", "балба", "Энэтхэг"),
  CountryLocalization("id", "Indonesian", "Индонез"),
  CountryLocalization("ir", "перс", "Иран"),
  CountryLocalization("iq", "хойд лури", "Ирак"),
  CountryLocalization("ie", "англи", "Ирланд"),
  CountryLocalization("im", "манкс", "Мэн Арал"),
  CountryLocalization("il", "англи", "Израиль"),
  CountryLocalization("it", "герман", "Итали"),
  CountryLocalization("jm", "англи", "Ямайка"),
  CountryLocalization("jp", "япон", "Япон"),
  CountryLocalization("je", "англи", "Жерси"),
  CountryLocalization("jo", "араб", "Йордан"),
  CountryLocalization("kz", "хасаг", "Казахстан"),
  CountryLocalization("ke", "сомали", "Кени"),
  CountryLocalization("ki", "англи", "Кирибати"),
  CountryLocalization("xk", "серб", "Косово"),
  CountryLocalization("kw", "араб", "Кувейт"),
  CountryLocalization("kg", "орос", "Кыргызстан"),
  CountryLocalization("la", "лаос", "Лаос"),
  CountryLocalization("lv", "латви", "Латви"),
  CountryLocalization("lb", "араб", "Ливан"),
  CountryLocalization("ls", "англи", "Лесото"),
  CountryLocalization("lr", "англи", "Либери"),
  CountryLocalization("ly", "араб", "Ливи"),
  CountryLocalization("li", "швейцари-герман", "Лихтенштейн"),
  CountryLocalization("lt", "литва", "Литва"),
  CountryLocalization("lu", "люксембург", "Люксембург"),
  CountryLocalization("mo", "португал", "БНХАУ-ын Тусгай захиргааны бүс Макао"),
  CountryLocalization("mk", "албани", "Македон"),
  CountryLocalization("mg", "франц", "Мадагаскар"),
  CountryLocalization("mw", "англи", "Малави"),
  CountryLocalization("my", "тамил", "Малайз"),
  CountryLocalization("ml", "франц", "Мали"),
  CountryLocalization("mt", "англи", "Мальта"),
  CountryLocalization("mh", "англи", "Маршаллын арлууд"),
  CountryLocalization("mq", "франц", "Мартиник"),
  CountryLocalization("mr", "араб", "Мавритани"),
  CountryLocalization("mu", "морисен", "Маврики"),
  CountryLocalization("yt", "франц", "Майотта"),
  CountryLocalization("mx", "испани", "Мексик"),
  CountryLocalization("fm", "англи", "Микронези"),
  CountryLocalization("md", "орос", "Молдав"),
  CountryLocalization("mc", "франц", "Монако"),
  CountryLocalization("mn", "монгол", "Монгол"),
  CountryLocalization("me", "серб", "Монтенегро"),
  CountryLocalization("ms", "англи", "Монтсеррат"),
  CountryLocalization("ma", "төв атласын тамазайт", "Морокко"),
  CountryLocalization("mz", "макува-мито", "Мозамбик"),
  CountryLocalization("mm", "бирм", "Мьянмар"),
  CountryLocalization("na", "англи", "Намиби"),
  CountryLocalization("nr", "англи", "Науру"),
  CountryLocalization("np", "балба", "Балба"),
  CountryLocalization("nl", "англи", "Нидерланд"),
  CountryLocalization("nc", "франц", "Шинэ Каледони"),
  CountryLocalization("nz", "англи", "Шинэ Зеланд"),
  CountryLocalization("ni", "испани", "Никарагуа"),
  CountryLocalization("ne", "хауса", "Нигер"),
  CountryLocalization("ng", "хауса", "Нигери"),
  CountryLocalization("nu", "англи", "Ниуэ"),
  CountryLocalization("nf", "англи", "Норфолк арал"),
  CountryLocalization("kp", "солонгос", "Хойд Солонгос"),
  CountryLocalization("mp", "англи", "Хойд Марианы арлууд"),
  CountryLocalization("no", "хойд сами", "Норвеги"),
  CountryLocalization("om", "араб", "Оман"),
  CountryLocalization("pk", "англи", "Пакистан"),
  CountryLocalization("pw", "англи", "Палау"),
  CountryLocalization("ps", "араб", "Палестины нутаг дэвсгэрүүд"),
  CountryLocalization("pa", "испани", "Панам"),
  CountryLocalization("pg", "англи", "Папуа Шинэ Гвиней"),
  CountryLocalization("py", "испани", "Парагвай"),
  CountryLocalization("pe", "испани", "Перу"),
  CountryLocalization("ph", "филиппин", "Филиппин"),
  CountryLocalization("pn", "англи", "Питкэрн арлууд"),
  CountryLocalization("pl", "польш", "Польш"),
  CountryLocalization("pt", "португал", "Португал"),
  CountryLocalization("pr", "англи", "Пуэрто-Рико"),
  CountryLocalization("qa", "араб", "Катар"),
  CountryLocalization("ro", "румын", "Румын"),
  CountryLocalization("ru", "татар", "Орос"),
  CountryLocalization("rw", "англи", "Руанда"),
  CountryLocalization("re", "франц", "Реюнион"),
  CountryLocalization("ws", "англи", "Самоа"),
  CountryLocalization("sm", "итали", "Сан-Марино"),
  CountryLocalization("sa", "араб", "Саудын Араб"),
  CountryLocalization("sn", "франц", "Сенегал"),
  CountryLocalization("rs", "серб", "Серби"),
  CountryLocalization("cs", "серб", "Serbia and Montenegro"),
  CountryLocalization("sc", "франц", "Сейшелийн арлууд"),
  CountryLocalization("sl", "англи", "Сьерра-Леоне"),
  CountryLocalization("sg", "тамил", "Сингапур"),
  CountryLocalization("sx", "англи", "Синт Мартен"),
  CountryLocalization("sk", "словак", "Словак"),
  CountryLocalization("si", "словени", "Словени"),
  CountryLocalization("sb", "англи", "Соломоны арлууд"),
  CountryLocalization("so", "араб", "Сомали"),
  CountryLocalization("za", "англи", "Өмнөд Африк"),
  CountryLocalization("kr", "солонгос", "Өмнөд Солонгос"),
  CountryLocalization("ss", "нуер", "Өмнөд Судан"),
  CountryLocalization("es", "испани", "Испани"),
  CountryLocalization("lk", "тамил", "Шри-Ланка"),
  CountryLocalization("bl", "франц", "Сент-Бартельми"),
  CountryLocalization("sh", "англи", "Сент Хелена"),
  CountryLocalization("kn", "англи", "Сент-Киттс ба Невис"),
  CountryLocalization("lc", "англи", "Сент Люсиа"),
  CountryLocalization("mf", "франц", "Сент-Мартин"),
  CountryLocalization("pm", "франц", "Сент-Пьер ба Микело"),
  CountryLocalization("vc", "англи", "Сент-Винсент ба Гренадин"),
  CountryLocalization("sd", "араб", "Судан"),
  CountryLocalization("sr", "нидерланд", "Суринам"),
  CountryLocalization("sj", "норвегийн букмол", "Свалбард ба Ян Майен"),
  CountryLocalization("sz", "англи", "Свазиланд"),
  CountryLocalization("se", "швед", "Швед"),
  CountryLocalization("ch", "швейцари-герман", "Швейцарь"),
  CountryLocalization("sy", "араб", "Сири"),
  CountryLocalization("st", "португал", "Сан-Томе Принсипи"),
  CountryLocalization("tw", "хятад", "Тайвань"),
  CountryLocalization("tj", "тажик", "Тажикистан"),
  CountryLocalization("tz", "маконде", "Танзани"),
  CountryLocalization("th", "тай", "Тайланд"),
  CountryLocalization("tl", "португал", "Тимор-Лесте"),
  CountryLocalization("tg", "франц", "Того"),
  CountryLocalization("tk", "англи", "Токелау"),
  CountryLocalization("to", "тонга", "Тонга"),
  CountryLocalization("tt", "англи", "Тринидад ба Тобаго"),
  CountryLocalization("tn", "франц", "Тунис"),
  CountryLocalization("tr", "турк", "Турк"),
  CountryLocalization("tm", "туркмен", "Туркменистан"),
  CountryLocalization("tc", "англи", "Турк ба Кайкосын Арлууд"),
  CountryLocalization("tv", "англи", "Тувалу"),
  CountryLocalization("um", "англи", "Америкийн Нэгдсэн Улсын бага арлууд"),
  CountryLocalization("vi", "англи", "АНУ-ын Виржиний Арлууд"),
  CountryLocalization("ug", "свахили", "Уганда"),
  CountryLocalization("ua", "украин", "Украин"),
  CountryLocalization("ae", "араб", "Арабын Нэгдсэн Эмират Улс"),
  CountryLocalization("gb", "англи", "Их Британи"),
  CountryLocalization("us", "лакота", "Америкийн Нэгдсэн Улс"),
  CountryLocalization("uy", "испани", "Уругвай"),
  CountryLocalization("uz", "узбек", "Узбекистан"),
  CountryLocalization("vu", "франц", "Вануату"),
  CountryLocalization("va", "итали", "Ватикан хот улс"),
  CountryLocalization("ve", "испани", "Венесуэл"),
  CountryLocalization("vn", "вьетнам", "Вьетнам"),
  CountryLocalization("wf", "франц", "Уоллис ба Футуна"),
  CountryLocalization("eh", "араб", "Баруун Сахар"),
  CountryLocalization("ye", "араб", "Йемен"),
  CountryLocalization("zm", "англи", "Замби"),
  CountryLocalization("zw", "хойд ндебеле", "Зимбабве"),
  CountryLocalization("ax", "швед", "Аландын арлууд"),
)
