/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot.atlas.extended

import dev.teogor.xenoglot.atlas.CountryLocalization
import kotlin.collections.List

/**
 * Holds the internal list of country-language mappings used for lookups within the package for
 * language code os.
 *
 * This property contains a hardcoded list of [CountryLocalization] objects, each representing
 * a country and its associated official languages. This list is used by [CountryLanguageRegistry]
 * to provide access to country-language data and should not be modified directly.
 *
 * @see CountryLocalization
 * @see CountryLanguageRegistry
 */
internal val _countryLanguageMappings_os: List<CountryLocalization> = listOf(
  CountryLocalization("af", "персайнаг", "Afghanistan"),
  CountryLocalization("al", "Albanian", "Albania"),
  CountryLocalization("dz", "францаг", "Algeria"),
  CountryLocalization("as", "англисаг", "American Samoa"),
  CountryLocalization("ad", "каталайнаг", "Andorra"),
  CountryLocalization("ao", "Lingala", "Angola"),
  CountryLocalization("ai", "англисаг", "Anguilla"),
  CountryLocalization("ag", "англисаг", "Antigua & Barbuda"),
  CountryLocalization("ar", "испайнаг", "Argentina"),
  CountryLocalization("am", "сомихаг", "Armenia"),
  CountryLocalization("aw", "Dutch", "Aruba"),
  CountryLocalization("au", "англисаг", "Australia"),
  CountryLocalization("at", "англисаг", "Austria"),
  CountryLocalization("az", "тӕтӕйраг", "Azerbaijan"),
  CountryLocalization("bs", "англисаг", "Bahamas"),
  CountryLocalization("bh", "араббаг", "Bahrain"),
  CountryLocalization("bd", "Bangla", "Bangladesh"),
  CountryLocalization("bb", "англисаг", "Barbados"),
  CountryLocalization("by", "Belarusian", "Belarus"),
  CountryLocalization("be", "францаг", "Belgium"),
  CountryLocalization("bz", "англисаг", "Belize"),
  CountryLocalization("bj", "францаг", "Benin"),
  CountryLocalization("bm", "англисаг", "Bermuda"),
  CountryLocalization("bt", "Dzongkha", "Bhutan"),
  CountryLocalization("bo", "испайнаг", "Bolivia"),
  CountryLocalization("ba", "босниаг", "Bosnia & Herzegovina"),
  CountryLocalization("bw", "англисаг", "Botswana"),
  CountryLocalization("br", "португалиаг", "Бразили"),
  CountryLocalization("io", "англисаг", "British Indian Ocean Territory"),
  CountryLocalization("vg", "англисаг", "British Virgin Islands"),
  CountryLocalization("bn", "Malay", "Brunei"),
  CountryLocalization("bg", "болгайраг", "Bulgaria"),
  CountryLocalization("bf", "францаг", "Burkina Faso"),
  CountryLocalization("bi", "францаг", "Burundi"),
  CountryLocalization("kh", "Khmer", "Cambodia"),
  CountryLocalization("cm", "Basaa", "Cameroon"),
  CountryLocalization("ca", "францаг", "Canada"),
  CountryLocalization("ic", "испайнаг", "IC"),
  CountryLocalization("cv", "kea", "Cape Verde"),
  CountryLocalization("bq", "Dutch", "Caribbean Netherlands"),
  CountryLocalization("ky", "англисаг", "Cayman Islands"),
  CountryLocalization("cf", "Lingala", "Central African Republic"),
  CountryLocalization("ea", "испайнаг", "EA"),
  CountryLocalization("td", "араббаг", "Chad"),
  CountryLocalization("cl", "испайнаг", "Chile"),
  CountryLocalization("cn", "Tibetan", "Китай"),
  CountryLocalization("cx", "англисаг", "Christmas Island"),
  CountryLocalization("cc", "англисаг", "Cocos (Keeling) Islands"),
  CountryLocalization("co", "испайнаг", "Colombia"),
  CountryLocalization("km", "араббаг", "Comoros"),
  CountryLocalization("cg", "Lingala", "Congo - Brazzaville"),
  CountryLocalization("cd", "Swahili", "Congo - Kinshasa"),
  CountryLocalization("ck", "англисаг", "Cook Islands"),
  CountryLocalization("cr", "испайнаг", "Costa Rica"),
  CountryLocalization("hr", "хорватаг", "Croatia"),
  CountryLocalization("cu", "испайнаг", "Cuba"),
  CountryLocalization("cw", "Dutch", "Curaçao"),
  CountryLocalization("cy", "англисаг", "Cyprus"),
  CountryLocalization("cz", "чехаг", "Czechia"),
  CountryLocalization("ci", "францаг", "Côte d’Ivoire"),
  CountryLocalization("dk", "англисаг", "Denmark"),
  CountryLocalization("dg", "англисаг", "DG"),
  CountryLocalization("dj", "францаг", "Djibouti"),
  CountryLocalization("dm", "англисаг", "Dominica"),
  CountryLocalization("do", "испайнаг", "Dominican Republic"),
  CountryLocalization("ec", "Quechua", "Ecuador"),
  CountryLocalization("eg", "араббаг", "Egypt"),
  CountryLocalization("sv", "испайнаг", "El Salvador"),
  CountryLocalization("gq", "испайнаг", "Equatorial Guinea"),
  CountryLocalization("er", "Tigrinya", "Eritrea"),
  CountryLocalization("ee", "естойнаг", "Estonia"),
  CountryLocalization("et", "Amharic", "Ethiopia"),
  CountryLocalization("fk", "англисаг", "Falkland Islands"),
  CountryLocalization("fo", "фарераг", "Faroe Islands"),
  CountryLocalization("fj", "англисаг", "Fiji"),
  CountryLocalization("fi", "Swedish", "Finland"),
  CountryLocalization("fr", "Swiss German", "Франц"),
  CountryLocalization("gf", "францаг", "French Guiana"),
  CountryLocalization("pf", "францаг", "French Polynesia"),
  CountryLocalization("ga", "францаг", "Gabon"),
  CountryLocalization("gm", "англисаг", "Gambia"),
  CountryLocalization("ge", "ирон", "Гуырдзыстон"),
  CountryLocalization("de", "Lower Sorbian", "Герман"),
  CountryLocalization("gh", "англисаг", "Ghana"),
  CountryLocalization("gi", "англисаг", "Gibraltar"),
  CountryLocalization("gr", "бердзейнаг", "Greece"),
  CountryLocalization("gl", "Kalaallisut", "Greenland"),
  CountryLocalization("gd", "англисаг", "Grenada"),
  CountryLocalization("gp", "францаг", "Guadeloupe"),
  CountryLocalization("gu", "англисаг", "Guam"),
  CountryLocalization("gt", "испайнаг", "Guatemala"),
  CountryLocalization("gg", "англисаг", "Guernsey"),
  CountryLocalization("gn", "францаг", "Guinea"),
  CountryLocalization("gw", "португалиаг", "Guinea-Bissau"),
  CountryLocalization("gy", "англисаг", "Guyana"),
  CountryLocalization("ht", "францаг", "Haiti"),
  CountryLocalization("hn", "испайнаг", "Honduras"),
  CountryLocalization("hk", "китайаг", "Hong Kong SAR China"),
  CountryLocalization("hu", "венгериаг", "Hungary"),
  CountryLocalization("is", "Icelandic", "Iceland"),
  CountryLocalization("in", "Nepali", "Инди"),
  CountryLocalization("id", "Indonesian", "Indonesia"),
  CountryLocalization("ir", "персайнаг", "Iran"),
  CountryLocalization("iq", "lrc", "Iraq"),
  CountryLocalization("ie", "англисаг", "Ireland"),
  CountryLocalization("im", "Manx", "Isle of Man"),
  CountryLocalization("il", "англисаг", "Israel"),
  CountryLocalization("it", "немыцаг", "Итали"),
  CountryLocalization("jm", "англисаг", "Jamaica"),
  CountryLocalization("jp", "япойнаг", "Япон"),
  CountryLocalization("je", "англисаг", "Jersey"),
  CountryLocalization("jo", "араббаг", "Jordan"),
  CountryLocalization("kz", "Kazakh", "Kazakhstan"),
  CountryLocalization("ke", "Somali", "Kenya"),
  CountryLocalization("ki", "англисаг", "Kiribati"),
  CountryLocalization("xk", "Serbian", "XK"),
  CountryLocalization("kw", "араббаг", "Kuwait"),
  CountryLocalization("kg", "уырыссаг", "Kyrgyzstan"),
  CountryLocalization("la", "Lao", "Laos"),
  CountryLocalization("lv", "Latvian", "Latvia"),
  CountryLocalization("lb", "араббаг", "Lebanon"),
  CountryLocalization("ls", "англисаг", "Lesotho"),
  CountryLocalization("lr", "англисаг", "Liberia"),
  CountryLocalization("ly", "араббаг", "Libya"),
  CountryLocalization("li", "Swiss German", "Liechtenstein"),
  CountryLocalization("lt", "Lithuanian", "Lithuania"),
  CountryLocalization("lu", "Luxembourgish", "Luxembourg"),
  CountryLocalization("mo", "португалиаг", "Macao SAR China"),
  CountryLocalization("mk", "Albanian", "North Macedonia"),
  CountryLocalization("mg", "францаг", "Madagascar"),
  CountryLocalization("mw", "англисаг", "Malawi"),
  CountryLocalization("my", "Tamil", "Malaysia"),
  CountryLocalization("ml", "францаг", "Mali"),
  CountryLocalization("mt", "англисаг", "Malta"),
  CountryLocalization("mh", "англисаг", "Marshall Islands"),
  CountryLocalization("mq", "францаг", "Martinique"),
  CountryLocalization("mr", "араббаг", "Mauritania"),
  CountryLocalization("mu", "mfe", "Mauritius"),
  CountryLocalization("yt", "францаг", "Mayotte"),
  CountryLocalization("mx", "испайнаг", "Mexico"),
  CountryLocalization("fm", "англисаг", "Micronesia"),
  CountryLocalization("md", "уырыссаг", "Moldova"),
  CountryLocalization("mc", "францаг", "Monaco"),
  CountryLocalization("mn", "Mongolian", "Mongolia"),
  CountryLocalization("me", "Serbian", "Montenegro"),
  CountryLocalization("ms", "англисаг", "Montserrat"),
  CountryLocalization("ma", "tzm", "Morocco"),
  CountryLocalization("mz", "mgh", "Mozambique"),
  CountryLocalization("mm", "Burmese", "Myanmar (Burma)"),
  CountryLocalization("na", "англисаг", "Namibia"),
  CountryLocalization("nr", "англисаг", "Nauru"),
  CountryLocalization("np", "Nepali", "Nepal"),
  CountryLocalization("nl", "англисаг", "Netherlands"),
  CountryLocalization("nc", "францаг", "New Caledonia"),
  CountryLocalization("nz", "англисаг", "New Zealand"),
  CountryLocalization("ni", "испайнаг", "Nicaragua"),
  CountryLocalization("ne", "Hausa", "Niger"),
  CountryLocalization("ng", "Hausa", "Nigeria"),
  CountryLocalization("nu", "англисаг", "Niue"),
  CountryLocalization("nf", "англисаг", "Norfolk Island"),
  CountryLocalization("kp", "Korean", "North Korea"),
  CountryLocalization("mp", "англисаг", "Northern Mariana Islands"),
  CountryLocalization("no", "Northern Sami", "Norway"),
  CountryLocalization("om", "араббаг", "Oman"),
  CountryLocalization("pk", "англисаг", "Pakistan"),
  CountryLocalization("pw", "англисаг", "Palau"),
  CountryLocalization("ps", "араббаг", "Palestinian Territories"),
  CountryLocalization("pa", "испайнаг", "Panama"),
  CountryLocalization("pg", "англисаг", "Papua New Guinea"),
  CountryLocalization("py", "испайнаг", "Paraguay"),
  CountryLocalization("pe", "испайнаг", "Peru"),
  CountryLocalization("ph", "филиппинаг", "Philippines"),
  CountryLocalization("pn", "англисаг", "Pitcairn Islands"),
  CountryLocalization("pl", "Polish", "Poland"),
  CountryLocalization("pt", "португалиаг", "Portugal"),
  CountryLocalization("pr", "англисаг", "Puerto Rico"),
  CountryLocalization("qa", "араббаг", "Qatar"),
  CountryLocalization("ro", "Romanian", "Romania"),
  CountryLocalization("ru", "Tatar", "Уӕрӕсе"),
  CountryLocalization("rw", "англисаг", "Rwanda"),
  CountryLocalization("re", "францаг", "Réunion"),
  CountryLocalization("ws", "англисаг", "Samoa"),
  CountryLocalization("sm", "италиаг", "San Marino"),
  CountryLocalization("sa", "араббаг", "Saudi Arabia"),
  CountryLocalization("sn", "францаг", "Senegal"),
  CountryLocalization("rs", "Serbian", "Serbia"),
  CountryLocalization("cs", "Serbian", "Serbia and Montenegro"),
  CountryLocalization("sc", "францаг", "Seychelles"),
  CountryLocalization("sl", "англисаг", "Sierra Leone"),
  CountryLocalization("sg", "Tamil", "Singapore"),
  CountryLocalization("sx", "англисаг", "Sint Maarten"),
  CountryLocalization("sk", "Slovak", "Slovakia"),
  CountryLocalization("si", "Slovenian", "Slovenia"),
  CountryLocalization("sb", "англисаг", "Solomon Islands"),
  CountryLocalization("so", "араббаг", "Somalia"),
  CountryLocalization("za", "англисаг", "South Africa"),
  CountryLocalization("kr", "Korean", "South Korea"),
  CountryLocalization("ss", "nus", "South Sudan"),
  CountryLocalization("es", "испайнаг", "Spain"),
  CountryLocalization("lk", "Tamil", "Sri Lanka"),
  CountryLocalization("bl", "францаг", "St. Barthélemy"),
  CountryLocalization("sh", "англисаг", "St. Helena"),
  CountryLocalization("kn", "англисаг", "St. Kitts & Nevis"),
  CountryLocalization("lc", "англисаг", "St. Lucia"),
  CountryLocalization("mf", "францаг", "St. Martin"),
  CountryLocalization("pm", "францаг", "St. Pierre & Miquelon"),
  CountryLocalization("vc", "англисаг", "St. Vincent & Grenadines"),
  CountryLocalization("sd", "араббаг", "Sudan"),
  CountryLocalization("sr", "Dutch", "Suriname"),
  CountryLocalization("sj", "Norwegian Bokmål", "Svalbard & Jan Mayen"),
  CountryLocalization("sz", "англисаг", "Eswatini"),
  CountryLocalization("se", "Swedish", "Sweden"),
  CountryLocalization("ch", "Swiss German", "Switzerland"),
  CountryLocalization("sy", "араббаг", "Syria"),
  CountryLocalization("st", "португалиаг", "São Tomé & Príncipe"),
  CountryLocalization("tw", "китайаг", "Taiwan"),
  CountryLocalization("tj", "Tajik", "Tajikistan"),
  CountryLocalization("tz", "kde", "Tanzania"),
  CountryLocalization("th", "Thai", "Thailand"),
  CountryLocalization("tl", "португалиаг", "Timor-Leste"),
  CountryLocalization("tg", "францаг", "Togo"),
  CountryLocalization("tk", "англисаг", "Tokelau"),
  CountryLocalization("to", "Tongan", "Tonga"),
  CountryLocalization("tt", "англисаг", "Trinidad & Tobago"),
  CountryLocalization("tn", "францаг", "Tunisia"),
  CountryLocalization("tr", "Turkish", "Turkey"),
  CountryLocalization("tm", "Turkmen", "Turkmenistan"),
  CountryLocalization("tc", "англисаг", "Turks & Caicos Islands"),
  CountryLocalization("tv", "англисаг", "Tuvalu"),
  CountryLocalization("um", "англисаг", "U.S. Outlying Islands"),
  CountryLocalization("vi", "англисаг", "U.S. Virgin Islands"),
  CountryLocalization("ug", "Swahili", "Uganda"),
  CountryLocalization("ua", "Ukrainian", "Ukraine"),
  CountryLocalization("ae", "араббаг", "United Arab Emirates"),
  CountryLocalization("gb", "англисаг", "Стыр Британи"),
  CountryLocalization("us", "lkt", "АИШ"),
  CountryLocalization("uy", "испайнаг", "Uruguay"),
  CountryLocalization("uz", "Uzbek", "Uzbekistan"),
  CountryLocalization("vu", "францаг", "Vanuatu"),
  CountryLocalization("va", "италиаг", "Vatican City"),
  CountryLocalization("ve", "испайнаг", "Venezuela"),
  CountryLocalization("vn", "Vietnamese", "Vietnam"),
  CountryLocalization("wf", "францаг", "Wallis & Futuna"),
  CountryLocalization("eh", "араббаг", "Western Sahara"),
  CountryLocalization("ye", "араббаг", "Yemen"),
  CountryLocalization("zm", "англисаг", "Zambia"),
  CountryLocalization("zw", "North Ndebele", "Zimbabwe"),
  CountryLocalization("ax", "Swedish", "Åland Islands"),
)
