/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot.atlas.extended

import dev.teogor.xenoglot.atlas.CountryLocalization
import kotlin.collections.List

/**
 * Holds the internal list of country-language mappings used for lookups within the package for
 * language code ar.
 *
 * This property contains a hardcoded list of [CountryLocalization] objects, each representing
 * a country and its associated official languages. This list is used by [CountryLanguageRegistry]
 * to provide access to country-language data and should not be modified directly.
 *
 * @see CountryLocalization
 * @see CountryLanguageRegistry
 */
internal val _countryLanguageMappings_ar: List<CountryLocalization> = listOf(
  CountryLocalization("af", "الفارسية", "أفغانستان"),
  CountryLocalization("al", "الألبانية", "ألبانيا"),
  CountryLocalization("dz", "الفرنسية", "الجزائر"),
  CountryLocalization("as", "الإنجليزية", "ساموا الأمريكية"),
  CountryLocalization("ad", "الكتالانية", "أندورا"),
  CountryLocalization("ao", "اللينجالا", "أنغولا"),
  CountryLocalization("ai", "الإنجليزية", "أنغويلا"),
  CountryLocalization("ag", "الإنجليزية", "أنتيغوا وبربودا"),
  CountryLocalization("ar", "الإسبانية", "الأرجنتين"),
  CountryLocalization("am", "الأرمنية", "أرمينيا"),
  CountryLocalization("aw", "الهولندية", "أروبا"),
  CountryLocalization("au", "الإنجليزية", "أستراليا"),
  CountryLocalization("at", "الإنجليزية", "النمسا"),
  CountryLocalization("az", "الأذربيجانية", "أذربيجان"),
  CountryLocalization("bs", "الإنجليزية", "البهاما"),
  CountryLocalization("bh", "العربية", "البحرين"),
  CountryLocalization("bd", "البنغالية", "بنغلاديش"),
  CountryLocalization("bb", "الإنجليزية", "بربادوس"),
  CountryLocalization("by", "البيلاروسية", "بيلاروس"),
  CountryLocalization("be", "الفرنسية", "بلجيكا"),
  CountryLocalization("bz", "الإنجليزية", "بليز"),
  CountryLocalization("bj", "الفرنسية", "بنين"),
  CountryLocalization("bm", "الإنجليزية", "برمودا"),
  CountryLocalization("bt", "الزونخاية", "بوتان"),
  CountryLocalization("bo", "الإسبانية", "بوليفيا"),
  CountryLocalization("ba", "البوسنية", "البوسنة والهرسك"),
  CountryLocalization("bw", "الإنجليزية", "بوتسوانا"),
  CountryLocalization("br", "البرتغالية", "البرازيل"),
  CountryLocalization("io", "الإنجليزية", "الإقليم البريطاني في المحيط الهندي"),
  CountryLocalization("vg", "الإنجليزية", "جزر فيرجن البريطانية"),
  CountryLocalization("bn", "الماليزية", "بروناي"),
  CountryLocalization("bg", "البلغارية", "بلغاريا"),
  CountryLocalization("bf", "الفرنسية", "بوركينا فاسو"),
  CountryLocalization("bi", "الفرنسية", "بوروندي"),
  CountryLocalization("kh", "الخميرية", "كمبوديا"),
  CountryLocalization("cm", "الباسا", "الكاميرون"),
  CountryLocalization("ca", "الفرنسية", "كندا"),
  CountryLocalization("ic", "الإسبانية", "جزر الكناري"),
  CountryLocalization("cv", "كابوفيرديانو", "الرأس الأخضر"),
  CountryLocalization("bq", "الهولندية", "هولندا الكاريبية"),
  CountryLocalization("ky", "الإنجليزية", "جزر كايمان"),
  CountryLocalization("cf", "اللينجالا", "جمهورية أفريقيا الوسطى"),
  CountryLocalization("ea", "الإسبانية", "سيوتا وميليلا"),
  CountryLocalization("td", "العربية", "تشاد"),
  CountryLocalization("cl", "الإسبانية", "تشيلي"),
  CountryLocalization("cn", "التبتية", "الصين"),
  CountryLocalization("cx", "الإنجليزية", "جزيرة كريسماس"),
  CountryLocalization("cc", "الإنجليزية", "جزر كوكوس (كيلينغ)"),
  CountryLocalization("co", "الإسبانية", "كولومبيا"),
  CountryLocalization("km", "العربية", "جزر القمر"),
  CountryLocalization("cg", "اللينجالا", "الكونغو - برازافيل"),
  CountryLocalization("cd", "السواحلية", "الكونغو - كينشاسا"),
  CountryLocalization("ck", "الإنجليزية", "جزر كوك"),
  CountryLocalization("cr", "الإسبانية", "كوستاريكا"),
  CountryLocalization("hr", "الكرواتية", "كرواتيا"),
  CountryLocalization("cu", "الإسبانية", "كوبا"),
  CountryLocalization("cw", "الهولندية", "كوراساو"),
  CountryLocalization("cy", "الإنجليزية", "قبرص"),
  CountryLocalization("cz", "التشيكية", "التشيك"),
  CountryLocalization("ci", "الفرنسية", "ساحل العاج"),
  CountryLocalization("dk", "الإنجليزية", "الدانمرك"),
  CountryLocalization("dg", "الإنجليزية", "دييغو غارسيا"),
  CountryLocalization("dj", "الفرنسية", "جيبوتي"),
  CountryLocalization("dm", "الإنجليزية", "دومينيكا"),
  CountryLocalization("do", "الإسبانية", "جمهورية الدومينيكان"),
  CountryLocalization("ec", "الكويتشوا", "الإكوادور"),
  CountryLocalization("eg", "العربية", "مصر"),
  CountryLocalization("sv", "الإسبانية", "السلفادور"),
  CountryLocalization("gq", "الإسبانية", "غينيا الاستوائية"),
  CountryLocalization("er", "التغرينية", "إريتريا"),
  CountryLocalization("ee", "الإستونية", "إستونيا"),
  CountryLocalization("et", "الأمهرية", "إثيوبيا"),
  CountryLocalization("fk", "الإنجليزية", "جزر فوكلاند"),
  CountryLocalization("fo", "الفاروية", "جزر فارو"),
  CountryLocalization("fj", "الإنجليزية", "فيجي"),
  CountryLocalization("fi", "السويدية", "فنلندا"),
  CountryLocalization("fr", "الألمانية السويسرية", "فرنسا"),
  CountryLocalization("gf", "الفرنسية", "غويانا الفرنسية"),
  CountryLocalization("pf", "الفرنسية", "بولينيزيا الفرنسية"),
  CountryLocalization("ga", "الفرنسية", "الغابون"),
  CountryLocalization("gm", "الإنجليزية", "غامبيا"),
  CountryLocalization("ge", "الأوسيتيك", "جورجيا"),
  CountryLocalization("de", "صوربيا السفلى", "ألمانيا"),
  CountryLocalization("gh", "الإنجليزية", "غانا"),
  CountryLocalization("gi", "الإنجليزية", "جبل طارق"),
  CountryLocalization("gr", "اليونانية", "اليونان"),
  CountryLocalization("gl", "الكالاليست", "غرينلاند"),
  CountryLocalization("gd", "الإنجليزية", "غرينادا"),
  CountryLocalization("gp", "الفرنسية", "غوادلوب"),
  CountryLocalization("gu", "الإنجليزية", "غوام"),
  CountryLocalization("gt", "الإسبانية", "غواتيمالا"),
  CountryLocalization("gg", "الإنجليزية", "غيرنزي"),
  CountryLocalization("gn", "الفرنسية", "غينيا"),
  CountryLocalization("gw", "البرتغالية", "غينيا بيساو"),
  CountryLocalization("gy", "الإنجليزية", "غيانا"),
  CountryLocalization("ht", "الفرنسية", "هايتي"),
  CountryLocalization("hn", "الإسبانية", "هندوراس"),
  CountryLocalization("hk", "الصينية", "هونغ كونغ الصينية (منطقة إدارية خاصة)"),
  CountryLocalization("hu", "الهنغارية", "هنغاريا"),
  CountryLocalization("is", "الأيسلندية", "آيسلندا"),
  CountryLocalization("in", "النيبالية", "الهند"),
  CountryLocalization("id", "Indonesian", "إندونيسيا"),
  CountryLocalization("ir", "الفارسية", "إيران"),
  CountryLocalization("iq", "اللرية الشمالية", "العراق"),
  CountryLocalization("ie", "الإنجليزية", "أيرلندا"),
  CountryLocalization("im", "المنكية", "جزيرة مان"),
  CountryLocalization("il", "الإنجليزية", "إسرائيل"),
  CountryLocalization("it", "الألمانية", "إيطاليا"),
  CountryLocalization("jm", "الإنجليزية", "جامايكا"),
  CountryLocalization("jp", "اليابانية", "اليابان"),
  CountryLocalization("je", "الإنجليزية", "جيرسي"),
  CountryLocalization("jo", "العربية", "الأردن"),
  CountryLocalization("kz", "الكازاخستانية", "كازاخستان"),
  CountryLocalization("ke", "الصومالية", "كينيا"),
  CountryLocalization("ki", "الإنجليزية", "كيريباتي"),
  CountryLocalization("xk", "الصربية", "كوسوفو"),
  CountryLocalization("kw", "العربية", "الكويت"),
  CountryLocalization("kg", "الروسية", "قيرغيزستان"),
  CountryLocalization("la", "اللاوية", "لاوس"),
  CountryLocalization("lv", "اللاتفية", "لاتفيا"),
  CountryLocalization("lb", "العربية", "لبنان"),
  CountryLocalization("ls", "الإنجليزية", "ليسوتو"),
  CountryLocalization("lr", "الإنجليزية", "ليبيريا"),
  CountryLocalization("ly", "العربية", "ليبيا"),
  CountryLocalization("li", "الألمانية السويسرية", "ليختنشتاين"),
  CountryLocalization("lt", "الليتوانية", "ليتوانيا"),
  CountryLocalization("lu", "اللكسمبورغية", "لوكسمبورغ"),
  CountryLocalization("mo", "البرتغالية", "مكاو الصينية (منطقة إدارية خاصة)"),
  CountryLocalization("mk", "الألبانية", "مقدونيا"),
  CountryLocalization("mg", "الفرنسية", "مدغشقر"),
  CountryLocalization("mw", "الإنجليزية", "ملاوي"),
  CountryLocalization("my", "التاميلية", "ماليزيا"),
  CountryLocalization("ml", "الفرنسية", "مالي"),
  CountryLocalization("mt", "الإنجليزية", "مالطا"),
  CountryLocalization("mh", "الإنجليزية", "جزر مارشال"),
  CountryLocalization("mq", "الفرنسية", "جزر المارتينيك"),
  CountryLocalization("mr", "العربية", "موريتانيا"),
  CountryLocalization("mu", "المورسيانية", "موريشيوس"),
  CountryLocalization("yt", "الفرنسية", "مايوت"),
  CountryLocalization("mx", "الإسبانية", "المكسيك"),
  CountryLocalization("fm", "الإنجليزية", "ميكرونيزيا"),
  CountryLocalization("md", "الروسية", "مولدوفا"),
  CountryLocalization("mc", "الفرنسية", "موناكو"),
  CountryLocalization("mn", "المنغولية", "منغوليا"),
  CountryLocalization("me", "الصربية", "الجبل الأسود"),
  CountryLocalization("ms", "الإنجليزية", "مونتسرات"),
  CountryLocalization("ma", "الأمازيغية وسط الأطلس", "المغرب"),
  CountryLocalization("mz", "ماخاوا-ميتو", "موزمبيق"),
  CountryLocalization("mm", "البورمية", "ميانمار (بورما)"),
  CountryLocalization("na", "الإنجليزية", "ناميبيا"),
  CountryLocalization("nr", "الإنجليزية", "ناورو"),
  CountryLocalization("np", "النيبالية", "نيبال"),
  CountryLocalization("nl", "الإنجليزية", "هولندا"),
  CountryLocalization("nc", "الفرنسية", "كاليدونيا الجديدة"),
  CountryLocalization("nz", "الإنجليزية", "نيوزيلندا"),
  CountryLocalization("ni", "الإسبانية", "نيكاراغوا"),
  CountryLocalization("ne", "الهوسا", "النيجر"),
  CountryLocalization("ng", "الهوسا", "نيجيريا"),
  CountryLocalization("nu", "الإنجليزية", "نيوي"),
  CountryLocalization("nf", "الإنجليزية", "جزيرة نورفولك"),
  CountryLocalization("kp", "الكورية", "كوريا الشمالية"),
  CountryLocalization("mp", "الإنجليزية", "جزر ماريانا الشمالية"),
  CountryLocalization("no", "سامي الشمالية", "النرويج"),
  CountryLocalization("om", "العربية", "عُمان"),
  CountryLocalization("pk", "الإنجليزية", "باكستان"),
  CountryLocalization("pw", "الإنجليزية", "بالاو"),
  CountryLocalization("ps", "العربية", "الأراضي الفلسطينية"),
  CountryLocalization("pa", "الإسبانية", "بنما"),
  CountryLocalization("pg", "الإنجليزية", "بابوا غينيا الجديدة"),
  CountryLocalization("py", "الإسبانية", "باراغواي"),
  CountryLocalization("pe", "الإسبانية", "بيرو"),
  CountryLocalization("ph", "الفلبينية", "الفلبين"),
  CountryLocalization("pn", "الإنجليزية", "جزر بيتكيرن"),
  CountryLocalization("pl", "البولندية", "بولندا"),
  CountryLocalization("pt", "البرتغالية", "البرتغال"),
  CountryLocalization("pr", "الإنجليزية", "بورتوريكو"),
  CountryLocalization("qa", "العربية", "قطر"),
  CountryLocalization("ro", "الرومانية", "رومانيا"),
  CountryLocalization("ru", "التترية", "روسيا"),
  CountryLocalization("rw", "الإنجليزية", "رواندا"),
  CountryLocalization("re", "الفرنسية", "روينيون"),
  CountryLocalization("ws", "الإنجليزية", "ساموا"),
  CountryLocalization("sm", "الإيطالية", "سان مارينو"),
  CountryLocalization("sa", "العربية", "المملكة العربية السعودية"),
  CountryLocalization("sn", "الفرنسية", "السنغال"),
  CountryLocalization("rs", "الصربية", "صربيا"),
  CountryLocalization("cs", "الصربية", "Serbia and Montenegro"),
  CountryLocalization("sc", "الفرنسية", "سيشل"),
  CountryLocalization("sl", "الإنجليزية", "سيراليون"),
  CountryLocalization("sg", "التاميلية", "سنغافورة"),
  CountryLocalization("sx", "الإنجليزية", "سانت مارتن"),
  CountryLocalization("sk", "السلوفاكية", "سلوفاكيا"),
  CountryLocalization("si", "السلوفانية", "سلوفينيا"),
  CountryLocalization("sb", "الإنجليزية", "جزر سليمان"),
  CountryLocalization("so", "العربية", "الصومال"),
  CountryLocalization("za", "الإنجليزية", "جنوب أفريقيا"),
  CountryLocalization("kr", "الكورية", "كوريا الجنوبية"),
  CountryLocalization("ss", "النوير", "جنوب السودان"),
  CountryLocalization("es", "الإسبانية", "إسبانيا"),
  CountryLocalization("lk", "التاميلية", "سريلانكا"),
  CountryLocalization("bl", "الفرنسية", "سان بارتليمي"),
  CountryLocalization("sh", "الإنجليزية", "سانت هيلينا"),
  CountryLocalization("kn", "الإنجليزية", "سانت كيتس ونيفيس"),
  CountryLocalization("lc", "الإنجليزية", "سانت لوسيا"),
  CountryLocalization("mf", "الفرنسية", "سان مارتن"),
  CountryLocalization("pm", "الفرنسية", "سان بيير ومكويلون"),
  CountryLocalization("vc", "الإنجليزية", "سانت فنسنت وجزر غرينادين"),
  CountryLocalization("sd", "العربية", "السودان"),
  CountryLocalization("sr", "الهولندية", "سورينام"),
  CountryLocalization("sj", "بوكمول النرويجية", "سفالبارد وجان ماين"),
  CountryLocalization("sz", "الإنجليزية", "سوازيلاند"),
  CountryLocalization("se", "السويدية", "السويد"),
  CountryLocalization("ch", "الألمانية السويسرية", "سويسرا"),
  CountryLocalization("sy", "العربية", "سوريا"),
  CountryLocalization("st", "البرتغالية", "ساو تومي وبرينسيبي"),
  CountryLocalization("tw", "الصينية", "تايوان"),
  CountryLocalization("tj", "الطاجيكية", "طاجيكستان"),
  CountryLocalization("tz", "ماكونده", "تنزانيا"),
  CountryLocalization("th", "التايلاندية", "تايلاند"),
  CountryLocalization("tl", "البرتغالية", "تيمور- ليشتي"),
  CountryLocalization("tg", "الفرنسية", "توغو"),
  CountryLocalization("tk", "الإنجليزية", "توكيلو"),
  CountryLocalization("to", "التونغية", "تونغا"),
  CountryLocalization("tt", "الإنجليزية", "ترينيداد وتوباغو"),
  CountryLocalization("tn", "الفرنسية", "تونس"),
  CountryLocalization("tr", "التركية", "تركيا"),
  CountryLocalization("tm", "التركمانية", "تركمانستان"),
  CountryLocalization("tc", "الإنجليزية", "جزر توركس وكايكوس"),
  CountryLocalization("tv", "الإنجليزية", "توفالو"),
  CountryLocalization("um", "الإنجليزية", "جزر الولايات المتحدة النائية"),
  CountryLocalization("vi", "الإنجليزية", "جزر فيرجن التابعة للولايات المتحدة"),
  CountryLocalization("ug", "السواحلية", "أوغندا"),
  CountryLocalization("ua", "الأوكرانية", "أوكرانيا"),
  CountryLocalization("ae", "العربية", "الإمارات العربية المتحدة"),
  CountryLocalization("gb", "الإنجليزية", "المملكة المتحدة"),
  CountryLocalization("us", "لاكوتا", "الولايات المتحدة"),
  CountryLocalization("uy", "الإسبانية", "أورغواي"),
  CountryLocalization("uz", "الأوزبكية", "أوزبكستان"),
  CountryLocalization("vu", "الفرنسية", "فانواتو"),
  CountryLocalization("va", "الإيطالية", "الفاتيكان"),
  CountryLocalization("ve", "الإسبانية", "فنزويلا"),
  CountryLocalization("vn", "الفيتنامية", "فيتنام"),
  CountryLocalization("wf", "الفرنسية", "جزر والس وفوتونا"),
  CountryLocalization("eh", "العربية", "الصحراء الغربية"),
  CountryLocalization("ye", "العربية", "اليمن"),
  CountryLocalization("zm", "الإنجليزية", "زامبيا"),
  CountryLocalization("zw", "النديبيل الشمالية", "زيمبابوي"),
  CountryLocalization("ax", "السويدية", "جزر آلاند"),
)
