/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot.atlas.extended

import dev.teogor.xenoglot.atlas.CountryLocalization
import kotlin.collections.List

/**
 * Holds the internal list of country-language mappings used for lookups within the package for
 * language code fr.
 *
 * This property contains a hardcoded list of [CountryLocalization] objects, each representing
 * a country and its associated official languages. This list is used by [CountryLanguageRegistry]
 * to provide access to country-language data and should not be modified directly.
 *
 * @see CountryLocalization
 * @see CountryLanguageRegistry
 */
internal val _countryLanguageMappings_fr: List<CountryLocalization> = listOf(
  CountryLocalization("af", "persan", "Afghanistan"),
  CountryLocalization("al", "albanais", "Albanie"),
  CountryLocalization("dz", "français", "Algérie"),
  CountryLocalization("as", "anglais", "Samoa américaines"),
  CountryLocalization("ad", "catalan", "Andorre"),
  CountryLocalization("ao", "lingala", "Angola"),
  CountryLocalization("ai", "anglais", "Anguilla"),
  CountryLocalization("ag", "anglais", "Antigua-et-Barbuda"),
  CountryLocalization("ar", "espagnol", "Argentine"),
  CountryLocalization("am", "arménien", "Arménie"),
  CountryLocalization("aw", "néerlandais", "Aruba"),
  CountryLocalization("au", "anglais", "Australie"),
  CountryLocalization("at", "anglais", "Autriche"),
  CountryLocalization("az", "azéri", "Azerbaïdjan"),
  CountryLocalization("bs", "anglais", "Bahamas"),
  CountryLocalization("bh", "arabe", "Bahreïn"),
  CountryLocalization("bd", "bengali", "Bangladesh"),
  CountryLocalization("bb", "anglais", "Barbade"),
  CountryLocalization("by", "biélorusse", "Biélorussie"),
  CountryLocalization("be", "français", "Belgique"),
  CountryLocalization("bz", "anglais", "Belize"),
  CountryLocalization("bj", "français", "Bénin"),
  CountryLocalization("bm", "anglais", "Bermudes"),
  CountryLocalization("bt", "dzongkha", "Bhoutan"),
  CountryLocalization("bo", "espagnol", "Bolivie"),
  CountryLocalization("ba", "bosniaque", "Bosnie-Herzégovine"),
  CountryLocalization("bw", "anglais", "Botswana"),
  CountryLocalization("br", "portugais", "Brésil"),
  CountryLocalization("io", "anglais", "Territoire britannique de l’océan Indien"),
  CountryLocalization("vg", "anglais", "Îles Vierges britanniques"),
  CountryLocalization("bn", "malais", "Brunéi Darussalam"),
  CountryLocalization("bg", "bulgare", "Bulgarie"),
  CountryLocalization("bf", "français", "Burkina Faso"),
  CountryLocalization("bi", "français", "Burundi"),
  CountryLocalization("kh", "khmer", "Cambodge"),
  CountryLocalization("cm", "bassa", "Cameroun"),
  CountryLocalization("ca", "français", "Canada"),
  CountryLocalization("ic", "espagnol", "Îles Canaries"),
  CountryLocalization("cv", "capverdien", "Cap-Vert"),
  CountryLocalization("bq", "néerlandais", "Pays-Bas caribéens"),
  CountryLocalization("ky", "anglais", "Îles Caïmans"),
  CountryLocalization("cf", "lingala", "République centrafricaine"),
  CountryLocalization("ea", "espagnol", "Ceuta et Melilla"),
  CountryLocalization("td", "arabe", "Tchad"),
  CountryLocalization("cl", "espagnol", "Chili"),
  CountryLocalization("cn", "tibétain", "Chine"),
  CountryLocalization("cx", "anglais", "Île Christmas"),
  CountryLocalization("cc", "anglais", "Îles Cocos"),
  CountryLocalization("co", "espagnol", "Colombie"),
  CountryLocalization("km", "arabe", "Comores"),
  CountryLocalization("cg", "lingala", "Congo-Brazzaville"),
  CountryLocalization("cd", "swahili", "Congo-Kinshasa"),
  CountryLocalization("ck", "anglais", "Îles Cook"),
  CountryLocalization("cr", "espagnol", "Costa Rica"),
  CountryLocalization("hr", "croate", "Croatie"),
  CountryLocalization("cu", "espagnol", "Cuba"),
  CountryLocalization("cw", "néerlandais", "Curaçao"),
  CountryLocalization("cy", "anglais", "Chypre"),
  CountryLocalization("cz", "tchèque", "Tchéquie"),
  CountryLocalization("ci", "français", "Côte d’Ivoire"),
  CountryLocalization("dk", "anglais", "Danemark"),
  CountryLocalization("dg", "anglais", "Diego Garcia"),
  CountryLocalization("dj", "français", "Djibouti"),
  CountryLocalization("dm", "anglais", "Dominique"),
  CountryLocalization("do", "espagnol", "République dominicaine"),
  CountryLocalization("ec", "quechua", "Équateur"),
  CountryLocalization("eg", "arabe", "Égypte"),
  CountryLocalization("sv", "espagnol", "Salvador"),
  CountryLocalization("gq", "espagnol", "Guinée équatoriale"),
  CountryLocalization("er", "tigrigna", "Érythrée"),
  CountryLocalization("ee", "estonien", "Estonie"),
  CountryLocalization("et", "amharique", "Éthiopie"),
  CountryLocalization("fk", "anglais", "Îles Malouines"),
  CountryLocalization("fo", "féroïen", "Îles Féroé"),
  CountryLocalization("fj", "anglais", "Fidji"),
  CountryLocalization("fi", "suédois", "Finlande"),
  CountryLocalization("fr", "suisse allemand", "France"),
  CountryLocalization("gf", "français", "Guyane française"),
  CountryLocalization("pf", "français", "Polynésie française"),
  CountryLocalization("ga", "français", "Gabon"),
  CountryLocalization("gm", "anglais", "Gambie"),
  CountryLocalization("ge", "ossète", "Géorgie"),
  CountryLocalization("de", "bas-sorabe", "Allemagne"),
  CountryLocalization("gh", "anglais", "Ghana"),
  CountryLocalization("gi", "anglais", "Gibraltar"),
  CountryLocalization("gr", "grec", "Grèce"),
  CountryLocalization("gl", "groenlandais", "Groenland"),
  CountryLocalization("gd", "anglais", "Grenade"),
  CountryLocalization("gp", "français", "Guadeloupe"),
  CountryLocalization("gu", "anglais", "Guam"),
  CountryLocalization("gt", "espagnol", "Guatemala"),
  CountryLocalization("gg", "anglais", "Guernesey"),
  CountryLocalization("gn", "français", "Guinée"),
  CountryLocalization("gw", "portugais", "Guinée-Bissau"),
  CountryLocalization("gy", "anglais", "Guyana"),
  CountryLocalization("ht", "français", "Haïti"),
  CountryLocalization("hn", "espagnol", "Honduras"),
  CountryLocalization("hk", "chinois", "R.A.S. chinoise de Hong Kong"),
  CountryLocalization("hu", "hongrois", "Hongrie"),
  CountryLocalization("is", "islandais", "Islande"),
  CountryLocalization("in", "népalais", "Inde"),
  CountryLocalization("id", "indonésien", "Indonésie"),
  CountryLocalization("ir", "persan", "Iran"),
  CountryLocalization("iq", "lori du Nord", "Irak"),
  CountryLocalization("ie", "anglais", "Irlande"),
  CountryLocalization("im", "mannois", "Île de Man"),
  CountryLocalization("il", "anglais", "Israël"),
  CountryLocalization("it", "allemand", "Italie"),
  CountryLocalization("jm", "anglais", "Jamaïque"),
  CountryLocalization("jp", "japonais", "Japon"),
  CountryLocalization("je", "anglais", "Jersey"),
  CountryLocalization("jo", "arabe", "Jordanie"),
  CountryLocalization("kz", "kazakh", "Kazakhstan"),
  CountryLocalization("ke", "somali", "Kenya"),
  CountryLocalization("ki", "anglais", "Kiribati"),
  CountryLocalization("xk", "serbe", "Kosovo"),
  CountryLocalization("kw", "arabe", "Koweït"),
  CountryLocalization("kg", "russe", "Kirghizistan"),
  CountryLocalization("la", "lao", "Laos"),
  CountryLocalization("lv", "letton", "Lettonie"),
  CountryLocalization("lb", "arabe", "Liban"),
  CountryLocalization("ls", "anglais", "Lesotho"),
  CountryLocalization("lr", "anglais", "Libéria"),
  CountryLocalization("ly", "arabe", "Libye"),
  CountryLocalization("li", "suisse allemand", "Liechtenstein"),
  CountryLocalization("lt", "lituanien", "Lituanie"),
  CountryLocalization("lu", "luxembourgeois", "Luxembourg"),
  CountryLocalization("mo", "portugais", "R.A.S. chinoise de Macao"),
  CountryLocalization("mk", "albanais", "Macédoine"),
  CountryLocalization("mg", "français", "Madagascar"),
  CountryLocalization("mw", "anglais", "Malawi"),
  CountryLocalization("my", "tamoul", "Malaisie"),
  CountryLocalization("ml", "français", "Mali"),
  CountryLocalization("mt", "anglais", "Malte"),
  CountryLocalization("mh", "anglais", "Îles Marshall"),
  CountryLocalization("mq", "français", "Martinique"),
  CountryLocalization("mr", "arabe", "Mauritanie"),
  CountryLocalization("mu", "créole mauricien", "Maurice"),
  CountryLocalization("yt", "français", "Mayotte"),
  CountryLocalization("mx", "espagnol", "Mexique"),
  CountryLocalization("fm", "anglais", "États fédérés de Micronésie"),
  CountryLocalization("md", "russe", "Moldavie"),
  CountryLocalization("mc", "français", "Monaco"),
  CountryLocalization("mn", "mongol", "Mongolie"),
  CountryLocalization("me", "serbe", "Monténégro"),
  CountryLocalization("ms", "anglais", "Montserrat"),
  CountryLocalization("ma", "amazighe de l’Atlas central", "Maroc"),
  CountryLocalization("mz", "makhuwa-meetto", "Mozambique"),
  CountryLocalization("mm", "birman", "Myanmar (Birmanie)"),
  CountryLocalization("na", "anglais", "Namibie"),
  CountryLocalization("nr", "anglais", "Nauru"),
  CountryLocalization("np", "népalais", "Népal"),
  CountryLocalization("nl", "anglais", "Pays-Bas"),
  CountryLocalization("nc", "français", "Nouvelle-Calédonie"),
  CountryLocalization("nz", "anglais", "Nouvelle-Zélande"),
  CountryLocalization("ni", "espagnol", "Nicaragua"),
  CountryLocalization("ne", "haoussa", "Niger"),
  CountryLocalization("ng", "haoussa", "Nigéria"),
  CountryLocalization("nu", "anglais", "Niue"),
  CountryLocalization("nf", "anglais", "Île Norfolk"),
  CountryLocalization("kp", "coréen", "Corée du Nord"),
  CountryLocalization("mp", "anglais", "Îles Mariannes du Nord"),
  CountryLocalization("no", "sami du Nord", "Norvège"),
  CountryLocalization("om", "arabe", "Oman"),
  CountryLocalization("pk", "anglais", "Pakistan"),
  CountryLocalization("pw", "anglais", "Palaos"),
  CountryLocalization("ps", "arabe", "Territoires palestiniens"),
  CountryLocalization("pa", "espagnol", "Panama"),
  CountryLocalization("pg", "anglais", "Papouasie-Nouvelle-Guinée"),
  CountryLocalization("py", "espagnol", "Paraguay"),
  CountryLocalization("pe", "espagnol", "Pérou"),
  CountryLocalization("ph", "filipino", "Philippines"),
  CountryLocalization("pn", "anglais", "Îles Pitcairn"),
  CountryLocalization("pl", "polonais", "Pologne"),
  CountryLocalization("pt", "portugais", "Portugal"),
  CountryLocalization("pr", "anglais", "Porto Rico"),
  CountryLocalization("qa", "arabe", "Qatar"),
  CountryLocalization("ro", "roumain", "Roumanie"),
  CountryLocalization("ru", "tatar", "Russie"),
  CountryLocalization("rw", "anglais", "Rwanda"),
  CountryLocalization("re", "français", "La Réunion"),
  CountryLocalization("ws", "anglais", "Samoa"),
  CountryLocalization("sm", "italien", "Saint-Marin"),
  CountryLocalization("sa", "arabe", "Arabie saoudite"),
  CountryLocalization("sn", "français", "Sénégal"),
  CountryLocalization("rs", "serbe", "Serbie"),
  CountryLocalization("cs", "serbe", "Serbie et Monténégro"),
  CountryLocalization("sc", "français", "Seychelles"),
  CountryLocalization("sl", "anglais", "Sierra Leone"),
  CountryLocalization("sg", "tamoul", "Singapour"),
  CountryLocalization("sx", "anglais", "Saint-Martin (partie néerlandaise)"),
  CountryLocalization("sk", "slovaque", "Slovaquie"),
  CountryLocalization("si", "slovène", "Slovénie"),
  CountryLocalization("sb", "anglais", "Îles Salomon"),
  CountryLocalization("so", "arabe", "Somalie"),
  CountryLocalization("za", "anglais", "Afrique du Sud"),
  CountryLocalization("kr", "coréen", "Corée du Sud"),
  CountryLocalization("ss", "nuer", "Soudan du Sud"),
  CountryLocalization("es", "espagnol", "Espagne"),
  CountryLocalization("lk", "tamoul", "Sri Lanka"),
  CountryLocalization("bl", "français", "Saint-Barthélemy"),
  CountryLocalization("sh", "anglais", "Sainte-Hélène"),
  CountryLocalization("kn", "anglais", "Saint-Christophe-et-Niévès"),
  CountryLocalization("lc", "anglais", "Sainte-Lucie"),
  CountryLocalization("mf", "français", "Saint-Martin"),
  CountryLocalization("pm", "français", "Saint-Pierre-et-Miquelon"),
  CountryLocalization("vc", "anglais", "Saint-Vincent-et-les-Grenadines"),
  CountryLocalization("sd", "arabe", "Soudan"),
  CountryLocalization("sr", "néerlandais", "Suriname"),
  CountryLocalization("sj", "norvégien bokmål", "Svalbard et Jan Mayen"),
  CountryLocalization("sz", "anglais", "Swaziland"),
  CountryLocalization("se", "suédois", "Suède"),
  CountryLocalization("ch", "suisse allemand", "Suisse"),
  CountryLocalization("sy", "arabe", "Syrie"),
  CountryLocalization("st", "portugais", "Sao Tomé-et-Principe"),
  CountryLocalization("tw", "chinois", "Taïwan"),
  CountryLocalization("tj", "tadjik", "Tadjikistan"),
  CountryLocalization("tz", "makondé", "Tanzanie"),
  CountryLocalization("th", "thaï", "Thaïlande"),
  CountryLocalization("tl", "portugais", "Timor oriental"),
  CountryLocalization("tg", "français", "Togo"),
  CountryLocalization("tk", "anglais", "Tokélaou"),
  CountryLocalization("to", "tonguien", "Tonga"),
  CountryLocalization("tt", "anglais", "Trinité-et-Tobago"),
  CountryLocalization("tn", "français", "Tunisie"),
  CountryLocalization("tr", "turc", "Turquie"),
  CountryLocalization("tm", "turkmène", "Turkménistan"),
  CountryLocalization("tc", "anglais", "Îles Turques-et-Caïques"),
  CountryLocalization("tv", "anglais", "Tuvalu"),
  CountryLocalization("um", "anglais", "Îles mineures éloignées des États-Unis"),
  CountryLocalization("vi", "anglais", "Îles Vierges des États-Unis"),
  CountryLocalization("ug", "swahili", "Ouganda"),
  CountryLocalization("ua", "ukrainien", "Ukraine"),
  CountryLocalization("ae", "arabe", "Émirats arabes unis"),
  CountryLocalization("gb", "anglais", "Royaume-Uni"),
  CountryLocalization("us", "lakota", "États-Unis"),
  CountryLocalization("uy", "espagnol", "Uruguay"),
  CountryLocalization("uz", "ouzbek", "Ouzbékistan"),
  CountryLocalization("vu", "français", "Vanuatu"),
  CountryLocalization("va", "italien", "État de la Cité du Vatican"),
  CountryLocalization("ve", "espagnol", "Venezuela"),
  CountryLocalization("vn", "vietnamien", "Vietnam"),
  CountryLocalization("wf", "français", "Wallis-et-Futuna"),
  CountryLocalization("eh", "arabe", "Sahara occidental"),
  CountryLocalization("ye", "arabe", "Yémen"),
  CountryLocalization("zm", "anglais", "Zambie"),
  CountryLocalization("zw", "ndébélé du Nord", "Zimbabwe"),
  CountryLocalization("ax", "suédois", "Îles Åland"),
)
