/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot.atlas.extended

import dev.teogor.xenoglot.atlas.CountryLocalization
import kotlin.collections.List

/**
 * Holds the internal list of country-language mappings used for lookups within the package for
 * language code sw.
 *
 * This property contains a hardcoded list of [CountryLocalization] objects, each representing
 * a country and its associated official languages. This list is used by [CountryLanguageRegistry]
 * to provide access to country-language data and should not be modified directly.
 *
 * @see CountryLocalization
 * @see CountryLanguageRegistry
 */
internal val _countryLanguageMappings_sw: List<CountryLocalization> = listOf(
  CountryLocalization("af", "Kiajemi", "Afuganistani"),
  CountryLocalization("al", "Kialbania", "Albania"),
  CountryLocalization("dz", "Kifaransa", "Aljeria"),
  CountryLocalization("as", "Kiingereza", "Samoa ya Marekani"),
  CountryLocalization("ad", "Kikatalani", "Andorra"),
  CountryLocalization("ao", "Kilingala", "Angola"),
  CountryLocalization("ai", "Kiingereza", "Anguilla"),
  CountryLocalization("ag", "Kiingereza", "Antigua na Barbuda"),
  CountryLocalization("ar", "Kihispania", "Ajentina"),
  CountryLocalization("am", "Kiarmenia", "Armenia"),
  CountryLocalization("aw", "Kiholanzi", "Aruba"),
  CountryLocalization("au", "Kiingereza", "Australia"),
  CountryLocalization("at", "Kiingereza", "Austria"),
  CountryLocalization("az", "Kiazabajani", "Azabajani"),
  CountryLocalization("bs", "Kiingereza", "Bahama"),
  CountryLocalization("bh", "Kiarabu", "Bahareni"),
  CountryLocalization("bd", "Kibengali", "Bangladeshi"),
  CountryLocalization("bb", "Kiingereza", "Babadosi"),
  CountryLocalization("by", "Kibelarusi", "Belarus"),
  CountryLocalization("be", "Kifaransa", "Ubelgiji"),
  CountryLocalization("bz", "Kiingereza", "Belize"),
  CountryLocalization("bj", "Kifaransa", "Benini"),
  CountryLocalization("bm", "Kiingereza", "Bermuda"),
  CountryLocalization("bt", "Kizongkha", "Bhutan"),
  CountryLocalization("bo", "Kihispania", "Bolivia"),
  CountryLocalization("ba", "Kibosnia", "Bosnia na Hezegovina"),
  CountryLocalization("bw", "Kiingereza", "Botswana"),
  CountryLocalization("br", "Kireno", "Brazil"),
  CountryLocalization("io", "Kiingereza", "Eneo la Uingereza katika Bahari Hindi"),
  CountryLocalization("vg", "Kiingereza", "Visiwa vya Virgin, Uingereza"),
  CountryLocalization("bn", "Kimalei", "Brunei"),
  CountryLocalization("bg", "Kibulgaria", "Bulgaria"),
  CountryLocalization("bf", "Kifaransa", "Bukinafaso"),
  CountryLocalization("bi", "Kifaransa", "Burundi"),
  CountryLocalization("kh", "Kikambodia", "Kambodia"),
  CountryLocalization("cm", "Kibasaa", "Kameruni"),
  CountryLocalization("ca", "Kifaransa", "Kanada"),
  CountryLocalization("ic", "Kihispania", "Visiwa vya Kanari"),
  CountryLocalization("cv", "Kikabuverdianu", "Cape Verde"),
  CountryLocalization("bq", "Kiholanzi", "Uholanzi ya Karibiani"),
  CountryLocalization("ky", "Kiingereza", "Visiwa vya Cayman"),
  CountryLocalization("cf", "Kilingala", "Jamhuri ya Afrika ya Kati"),
  CountryLocalization("ea", "Kihispania", "Ceuta na Melilla"),
  CountryLocalization("td", "Kiarabu", "Chadi"),
  CountryLocalization("cl", "Kihispania", "Chile"),
  CountryLocalization("cn", "Kitibeti", "Uchina"),
  CountryLocalization("cx", "Kiingereza", "Kisiwa cha Christmas"),
  CountryLocalization("cc", "Kiingereza", "Visiwa vya Cocos (Keeling)"),
  CountryLocalization("co", "Kihispania", "Kolombia"),
  CountryLocalization("km", "Kiarabu", "Komoro"),
  CountryLocalization("cg", "Kilingala", "Kongo - Brazzaville"),
  CountryLocalization("cd", "Kiswahili", "Jamhuri ya Kidemokrasia ya Kongo"),
  CountryLocalization("ck", "Kiingereza", "Visiwa vya Cook"),
  CountryLocalization("cr", "Kihispania", "Kostarika"),
  CountryLocalization("hr", "Kikroeshia", "Kroeshia"),
  CountryLocalization("cu", "Kihispania", "Cuba"),
  CountryLocalization("cw", "Kiholanzi", "Curacao"),
  CountryLocalization("cy", "Kiingereza", "Saiprasi"),
  CountryLocalization("cz", "Kicheki", "Chechia"),
  CountryLocalization("ci", "Kifaransa", "Kodivaa"),
  CountryLocalization("dk", "Kiingereza", "Denmaki"),
  CountryLocalization("dg", "Kiingereza", "Diego Garcia"),
  CountryLocalization("dj", "Kifaransa", "Jibuti"),
  CountryLocalization("dm", "Kiingereza", "Dominika"),
  CountryLocalization("do", "Kihispania", "Jamhuri ya Dominika"),
  CountryLocalization("ec", "Kiquechua", "Ecuador"),
  CountryLocalization("eg", "Kiarabu", "Misri"),
  CountryLocalization("sv", "Kihispania", "El Salvador"),
  CountryLocalization("gq", "Kihispania", "Guinea ya Ikweta"),
  CountryLocalization("er", "Kitigrinya", "Eritrea"),
  CountryLocalization("ee", "Kiestonia", "Estonia"),
  CountryLocalization("et", "Kiamhari", "Ethiopia"),
  CountryLocalization("fk", "Kiingereza", "Visiwa vya Falkland"),
  CountryLocalization("fo", "Kifaroe", "Visiwa vya Faroe"),
  CountryLocalization("fj", "Kiingereza", "Fiji"),
  CountryLocalization("fi", "Kiswidi", "Ufini"),
  CountryLocalization("fr", "Kijerumani cha Uswisi", "Ufaransa"),
  CountryLocalization("gf", "Kifaransa", "Guiana ya Ufaransa"),
  CountryLocalization("pf", "Kifaransa", "Polynesia ya Ufaransa"),
  CountryLocalization("ga", "Kifaransa", "Gabon"),
  CountryLocalization("gm", "Kiingereza", "Gambia"),
  CountryLocalization("ge", "Kiosetia", "Jojia"),
  CountryLocalization("de", "Kidolnoserbski", "Ujerumani"),
  CountryLocalization("gh", "Kiingereza", "Ghana"),
  CountryLocalization("gi", "Kiingereza", "Gibraltar"),
  CountryLocalization("gr", "Kigiriki", "Ugiriki"),
  CountryLocalization("gl", "Kikalaallisut", "Greenland"),
  CountryLocalization("gd", "Kiingereza", "Grenada"),
  CountryLocalization("gp", "Kifaransa", "Guadeloupe"),
  CountryLocalization("gu", "Kiingereza", "Guam"),
  CountryLocalization("gt", "Kihispania", "Guatemala"),
  CountryLocalization("gg", "Kiingereza", "Guernsey"),
  CountryLocalization("gn", "Kifaransa", "Gine"),
  CountryLocalization("gw", "Kireno", "Ginebisau"),
  CountryLocalization("gy", "Kiingereza", "Guyana"),
  CountryLocalization("ht", "Kifaransa", "Haiti"),
  CountryLocalization("hn", "Kihispania", "Honduras"),
  CountryLocalization("hk", "Kichina", "Hong Kong SAR China"),
  CountryLocalization("hu", "Kihangari", "Hungaria"),
  CountryLocalization("is", "Kiaisilandi", "Aislandi"),
  CountryLocalization("in", "Kinepali", "India"),
  CountryLocalization("id", "Indonesian", "Indonesia"),
  CountryLocalization("ir", "Kiajemi", "Iran"),
  CountryLocalization("iq", "Kiluri cha Kaskazini", "Iraki"),
  CountryLocalization("ie", "Kiingereza", "Ayalandi"),
  CountryLocalization("im", "Kimanksi", "Isle of Man"),
  CountryLocalization("il", "Kiingereza", "Israeli"),
  CountryLocalization("it", "Kijerumani", "Italia"),
  CountryLocalization("jm", "Kiingereza", "Jamaika"),
  CountryLocalization("jp", "Kijapani", "Japani"),
  CountryLocalization("je", "Kiingereza", "Jersey"),
  CountryLocalization("jo", "Kiarabu", "Yordani"),
  CountryLocalization("kz", "Kikazakh", "Kazakistani"),
  CountryLocalization("ke", "Kisomali", "Kenya"),
  CountryLocalization("ki", "Kiingereza", "Kiribati"),
  CountryLocalization("xk", "Kiserbia", "Kosovo"),
  CountryLocalization("kw", "Kiarabu", "Kuwait"),
  CountryLocalization("kg", "Kirusi", "Kirigizistani"),
  CountryLocalization("la", "Kilaosi", "Laos"),
  CountryLocalization("lv", "Kilatvia", "Lativia"),
  CountryLocalization("lb", "Kiarabu", "Lebanoni"),
  CountryLocalization("ls", "Kiingereza", "Lesoto"),
  CountryLocalization("lr", "Kiingereza", "Liberia"),
  CountryLocalization("ly", "Kiarabu", "Libya"),
  CountryLocalization("li", "Kijerumani cha Uswisi", "Lishenteni"),
  CountryLocalization("lt", "Kilithuania", "Lithuania"),
  CountryLocalization("lu", "Kilasembagi", "Lasembagi"),
  CountryLocalization("mo", "Kireno", "Macau SAR China"),
  CountryLocalization("mk", "Kialbania", "Macedonia"),
  CountryLocalization("mg", "Kifaransa", "Madagaska"),
  CountryLocalization("mw", "Kiingereza", "Malawi"),
  CountryLocalization("my", "Kitamil", "Malesia"),
  CountryLocalization("ml", "Kifaransa", "Mali"),
  CountryLocalization("mt", "Kiingereza", "Malta"),
  CountryLocalization("mh", "Kiingereza", "Visiwa vya Marshall"),
  CountryLocalization("mq", "Kifaransa", "Martinique"),
  CountryLocalization("mr", "Kiarabu", "Moritania"),
  CountryLocalization("mu", "Kimoriseni", "Morisi"),
  CountryLocalization("yt", "Kifaransa", "Mayotte"),
  CountryLocalization("mx", "Kihispania", "Meksiko"),
  CountryLocalization("fm", "Kiingereza", "Micronesia"),
  CountryLocalization("md", "Kirusi", "Moldova"),
  CountryLocalization("mc", "Kifaransa", "Monaco"),
  CountryLocalization("mn", "Kimongolia", "Mongolia"),
  CountryLocalization("me", "Kiserbia", "Montenegro"),
  CountryLocalization("ms", "Kiingereza", "Montserrat"),
  CountryLocalization("ma", "Central Atlas Tamazight", "Moroko"),
  CountryLocalization("mz", "Kimakhuwa-Meetto", "Msumbiji"),
  CountryLocalization("mm", "Kiburma", "Myama"),
  CountryLocalization("na", "Kiingereza", "Namibia"),
  CountryLocalization("nr", "Kiingereza", "Nauru"),
  CountryLocalization("np", "Kinepali", "Nepali"),
  CountryLocalization("nl", "Kiingereza", "Uholanzi"),
  CountryLocalization("nc", "Kifaransa", "New Caledonia"),
  CountryLocalization("nz", "Kiingereza", "Nyuzilandi"),
  CountryLocalization("ni", "Kihispania", "Nikaragwa"),
  CountryLocalization("ne", "Kihausa", "Nijeri"),
  CountryLocalization("ng", "Kihausa", "Nijeria"),
  CountryLocalization("nu", "Kiingereza", "Niue"),
  CountryLocalization("nf", "Kiingereza", "Kisiwa cha Norfolk"),
  CountryLocalization("kp", "Kikorea", "Korea Kaskazini"),
  CountryLocalization("mp", "Kiingereza", "Visiwa vya Mariana vya Kaskazini"),
  CountryLocalization("no", "Kisami cha Kaskazini", "Norwe"),
  CountryLocalization("om", "Kiarabu", "Omani"),
  CountryLocalization("pk", "Kiingereza", "Pakistani"),
  CountryLocalization("pw", "Kiingereza", "Palau"),
  CountryLocalization("ps", "Kiarabu", "Maeneo ya Palestina"),
  CountryLocalization("pa", "Kihispania", "Panama"),
  CountryLocalization("pg", "Kiingereza", "Papua New Guinea"),
  CountryLocalization("py", "Kihispania", "Paraguay"),
  CountryLocalization("pe", "Kihispania", "Peru"),
  CountryLocalization("ph", "Kifilipino", "Ufilipino"),
  CountryLocalization("pn", "Kiingereza", "Visiwa vya Pitcairn"),
  CountryLocalization("pl", "Kipolandi", "Poland"),
  CountryLocalization("pt", "Kireno", "Ureno"),
  CountryLocalization("pr", "Kiingereza", "Puetoriko"),
  CountryLocalization("qa", "Kiarabu", "Katari"),
  CountryLocalization("ro", "Kiromania", "Romania"),
  CountryLocalization("ru", "Kitatari", "Urusi"),
  CountryLocalization("rw", "Kiingereza", "Rwanda"),
  CountryLocalization("re", "Kifaransa", "Reunion"),
  CountryLocalization("ws", "Kiingereza", "Samoa"),
  CountryLocalization("sm", "Kiitaliano", "San Marino"),
  CountryLocalization("sa", "Kiarabu", "Saudia"),
  CountryLocalization("sn", "Kifaransa", "Senegali"),
  CountryLocalization("rs", "Kiserbia", "Serbia"),
  CountryLocalization("cs", "Kiserbia", "Serbia and Montenegro"),
  CountryLocalization("sc", "Kifaransa", "Ushelisheli"),
  CountryLocalization("sl", "Kiingereza", "Siera Leoni"),
  CountryLocalization("sg", "Kitamil", "Singapore"),
  CountryLocalization("sx", "Kiingereza", "Sint Maarten"),
  CountryLocalization("sk", "Kislovakia", "Slovakia"),
  CountryLocalization("si", "Kislovenia", "Slovenia"),
  CountryLocalization("sb", "Kiingereza", "Visiwa vya Solomon"),
  CountryLocalization("so", "Kiarabu", "Somalia"),
  CountryLocalization("za", "Kiingereza", "Afrika Kusini"),
  CountryLocalization("kr", "Kikorea", "Korea Kusini"),
  CountryLocalization("ss", "Kinuer", "Sudan Kusini"),
  CountryLocalization("es", "Kihispania", "Uhispania"),
  CountryLocalization("lk", "Kitamil", "Sri Lanka"),
  CountryLocalization("bl", "Kifaransa", "St. Barthelemy"),
  CountryLocalization("sh", "Kiingereza", "St. Helena"),
  CountryLocalization("kn", "Kiingereza", "St. Kitts na Nevis"),
  CountryLocalization("lc", "Kiingereza", "St. Lucia"),
  CountryLocalization("mf", "Kifaransa", "St. Martin"),
  CountryLocalization("pm", "Kifaransa", "Santapierre na Miquelon"),
  CountryLocalization("vc", "Kiingereza", "St. Vincent na Grenadines"),
  CountryLocalization("sd", "Kiarabu", "Sudani"),
  CountryLocalization("sr", "Kiholanzi", "Suriname"),
  CountryLocalization("sj", "Kinorwe cha Bokmal", "Svalbard na Jan Mayen"),
  CountryLocalization("sz", "Kiingereza", "Uswazi"),
  CountryLocalization("se", "Kiswidi", "Uswidi"),
  CountryLocalization("ch", "Kijerumani cha Uswisi", "Uswisi"),
  CountryLocalization("sy", "Kiarabu", "Syria"),
  CountryLocalization("st", "Kireno", "Sao Tome na Prinsipe"),
  CountryLocalization("tw", "Kichina", "Taiwan"),
  CountryLocalization("tj", "Kitajiki", "Tajikistani"),
  CountryLocalization("tz", "Kimakonde", "Tanzania"),
  CountryLocalization("th", "Kitailandi", "Tailandi"),
  CountryLocalization("tl", "Kireno", "Timori ya Mashariki"),
  CountryLocalization("tg", "Kifaransa", "Togo"),
  CountryLocalization("tk", "Kiingereza", "Tokelau"),
  CountryLocalization("to", "Kitonga", "Tonga"),
  CountryLocalization("tt", "Kiingereza", "Trinidad na Tobago"),
  CountryLocalization("tn", "Kifaransa", "Tunisia"),
  CountryLocalization("tr", "Kituruki", "Uturuki"),
  CountryLocalization("tm", "Kiturukimeni", "Turkmenistan"),
  CountryLocalization("tc", "Kiingereza", "Visiwa vya Turks na Caicos"),
  CountryLocalization("tv", "Kiingereza", "Tuvalu"),
  CountryLocalization("um", "Kiingereza", "Visiwa Vidogo vya Nje vya Marekani"),
  CountryLocalization("vi", "Kiingereza", "Visiwa vya Virgin, Marekani"),
  CountryLocalization("ug", "Kiswahili", "Uganda"),
  CountryLocalization("ua", "Kiukraine", "Ukraine"),
  CountryLocalization("ae", "Kiarabu", "Falme za Kiarabu"),
  CountryLocalization("gb", "Kiingereza", "Uingereza"),
  CountryLocalization("us", "Kilakota", "Marekani"),
  CountryLocalization("uy", "Kihispania", "Uruguay"),
  CountryLocalization("uz", "Kiuzbeki", "Uzibekistani"),
  CountryLocalization("vu", "Kifaransa", "Vanuatu"),
  CountryLocalization("va", "Kiitaliano", "Mji wa Vatican"),
  CountryLocalization("ve", "Kihispania", "Venezuela"),
  CountryLocalization("vn", "Kivietinamu", "Vietnamu"),
  CountryLocalization("wf", "Kifaransa", "Wallis na Futuna"),
  CountryLocalization("eh", "Kiarabu", "Sahara Magharibi"),
  CountryLocalization("ye", "Kiarabu", "Yemeni"),
  CountryLocalization("zm", "Kiingereza", "Zambia"),
  CountryLocalization("zw", "Kindebele cha Kaskazini", "Zimbabwe"),
  CountryLocalization("ax", "Kiswidi", "Visiwa vya Aland"),
)
