/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot.atlas.extended

import dev.teogor.xenoglot.atlas.CountryLocalization
import kotlin.collections.List

/**
 * Holds the internal list of country-language mappings used for lookups within the package for
 * language code is.
 *
 * This property contains a hardcoded list of [CountryLocalization] objects, each representing
 * a country and its associated official languages. This list is used by [CountryLanguageRegistry]
 * to provide access to country-language data and should not be modified directly.
 *
 * @see CountryLocalization
 * @see CountryLanguageRegistry
 */
internal val _countryLanguageMappings_is: List<CountryLocalization> = listOf(
  CountryLocalization("af", "persneska", "Afganistan"),
  CountryLocalization("al", "albanska", "Albanía"),
  CountryLocalization("dz", "franska", "Alsír"),
  CountryLocalization("as", "enska", "Bandaríska Samóa"),
  CountryLocalization("ad", "katalónska", "Andorra"),
  CountryLocalization("ao", "lingala", "Angóla"),
  CountryLocalization("ai", "enska", "Angvilla"),
  CountryLocalization("ag", "enska", "Antígva og Barbúda"),
  CountryLocalization("ar", "spænska", "Argentína"),
  CountryLocalization("am", "armenska", "Armenía"),
  CountryLocalization("aw", "hollenska", "Arúba"),
  CountryLocalization("au", "enska", "Ástralía"),
  CountryLocalization("at", "enska", "Austurríki"),
  CountryLocalization("az", "aserska", "Aserbaídsjan"),
  CountryLocalization("bs", "enska", "Bahamaeyjar"),
  CountryLocalization("bh", "arabíska", "Barein"),
  CountryLocalization("bd", "bengalska", "Bangladess"),
  CountryLocalization("bb", "enska", "Barbados"),
  CountryLocalization("by", "hvítrússneska", "Hvíta-Rússland"),
  CountryLocalization("be", "franska", "Belgía"),
  CountryLocalization("bz", "enska", "Belís"),
  CountryLocalization("bj", "franska", "Benín"),
  CountryLocalization("bm", "enska", "Bermúdaeyjar"),
  CountryLocalization("bt", "dsongka", "Bútan"),
  CountryLocalization("bo", "spænska", "Bólivía"),
  CountryLocalization("ba", "bosníska", "Bosnía og Hersegóvína"),
  CountryLocalization("bw", "enska", "Botsvana"),
  CountryLocalization("br", "portúgalska", "Brasilía"),
  CountryLocalization("io", "enska", "Bresku Indlandshafseyjar"),
  CountryLocalization("vg", "enska", "Bresku Jómfrúaeyjar"),
  CountryLocalization("bn", "malaíska", "Brúnei"),
  CountryLocalization("bg", "búlgarska", "Búlgaría"),
  CountryLocalization("bf", "franska", "Búrkína Fasó"),
  CountryLocalization("bi", "franska", "Búrúndí"),
  CountryLocalization("kh", "kmer", "Kambódía"),
  CountryLocalization("cm", "basa", "Kamerún"),
  CountryLocalization("ca", "franska", "Kanada"),
  CountryLocalization("ic", "spænska", "Kanaríeyjar"),
  CountryLocalization("cv", "grænhöfðeyska", "Grænhöfðaeyjar"),
  CountryLocalization("bq", "hollenska", "Karíbahafshluti Hollands"),
  CountryLocalization("ky", "enska", "Caymaneyjar"),
  CountryLocalization("cf", "lingala", "Mið-Afríkulýðveldið"),
  CountryLocalization("ea", "spænska", "Ceuta og Melilla"),
  CountryLocalization("td", "arabíska", "Tsjad"),
  CountryLocalization("cl", "spænska", "Síle"),
  CountryLocalization("cn", "tíbeska", "Kína"),
  CountryLocalization("cx", "enska", "Jólaey"),
  CountryLocalization("cc", "enska", "Kókoseyjar (Keeling)"),
  CountryLocalization("co", "spænska", "Kólumbía"),
  CountryLocalization("km", "arabíska", "Kómoreyjar"),
  CountryLocalization("cg", "lingala", "Kongó-Brazzaville"),
  CountryLocalization("cd", "svahílí", "Kongó-Kinshasa"),
  CountryLocalization("ck", "enska", "Cooks-eyjar"),
  CountryLocalization("cr", "spænska", "Kostaríka"),
  CountryLocalization("hr", "króatíska", "Króatía"),
  CountryLocalization("cu", "spænska", "Kúba"),
  CountryLocalization("cw", "hollenska", "Curacao"),
  CountryLocalization("cy", "enska", "Kýpur"),
  CountryLocalization("cz", "tékkneska", "Tékkland"),
  CountryLocalization("ci", "franska", "Côte d’Ivoire"),
  CountryLocalization("dk", "enska", "Danmörk"),
  CountryLocalization("dg", "enska", "Diego Garcia"),
  CountryLocalization("dj", "franska", "Djíbútí"),
  CountryLocalization("dm", "enska", "Dóminíka"),
  CountryLocalization("do", "spænska", "Dóminíska lýðveldið"),
  CountryLocalization("ec", "kvesjúa", "Ekvador"),
  CountryLocalization("eg", "arabíska", "Egyptaland"),
  CountryLocalization("sv", "spænska", "El Salvador"),
  CountryLocalization("gq", "spænska", "Miðbaugs-Gínea"),
  CountryLocalization("er", "tígrinja", "Erítrea"),
  CountryLocalization("ee", "eistneska", "Eistland"),
  CountryLocalization("et", "amharíska", "Eþíópía"),
  CountryLocalization("fk", "enska", "Falklandseyjar"),
  CountryLocalization("fo", "færeyska", "Færeyjar"),
  CountryLocalization("fj", "enska", "Fídjíeyjar"),
  CountryLocalization("fi", "sænska", "Finnland"),
  CountryLocalization("fr", "svissnesk þýska", "Frakkland"),
  CountryLocalization("gf", "franska", "Franska Gvæjana"),
  CountryLocalization("pf", "franska", "Franska Pólýnesía"),
  CountryLocalization("ga", "franska", "Gabon"),
  CountryLocalization("gm", "enska", "Gambía"),
  CountryLocalization("ge", "ossetíska", "Georgía"),
  CountryLocalization("de", "lágsorbneska", "Þýskaland"),
  CountryLocalization("gh", "enska", "Gana"),
  CountryLocalization("gi", "enska", "Gíbraltar"),
  CountryLocalization("gr", "gríska", "Grikkland"),
  CountryLocalization("gl", "grænlenska", "Grænland"),
  CountryLocalization("gd", "enska", "Grenada"),
  CountryLocalization("gp", "franska", "Gvadelúpeyjar"),
  CountryLocalization("gu", "enska", "Gvam"),
  CountryLocalization("gt", "spænska", "Gvatemala"),
  CountryLocalization("gg", "enska", "Guernsey"),
  CountryLocalization("gn", "franska", "Gínea"),
  CountryLocalization("gw", "portúgalska", "Gínea-Bissá"),
  CountryLocalization("gy", "enska", "Gvæjana"),
  CountryLocalization("ht", "franska", "Haítí"),
  CountryLocalization("hn", "spænska", "Hondúras"),
  CountryLocalization("hk", "kínverska", "sérstjórnarsvæðið Hong Kong"),
  CountryLocalization("hu", "ungverska", "Ungverjaland"),
  CountryLocalization("is", "íslenska", "Ísland"),
  CountryLocalization("in", "nepalska", "Indland"),
  CountryLocalization("id", "Indonesian", "Indónesía"),
  CountryLocalization("ir", "persneska", "Íran"),
  CountryLocalization("iq", "norðurlúrí", "Írak"),
  CountryLocalization("ie", "enska", "Írland"),
  CountryLocalization("im", "manska", "Mön"),
  CountryLocalization("il", "enska", "Ísrael"),
  CountryLocalization("it", "þýska", "Ítalía"),
  CountryLocalization("jm", "enska", "Jamaíka"),
  CountryLocalization("jp", "japanska", "Japan"),
  CountryLocalization("je", "enska", "Jersey"),
  CountryLocalization("jo", "arabíska", "Jórdanía"),
  CountryLocalization("kz", "kasakska", "Kasakstan"),
  CountryLocalization("ke", "sómalska", "Kenía"),
  CountryLocalization("ki", "enska", "Kíribatí"),
  CountryLocalization("xk", "serbneska", "Kósóvó"),
  CountryLocalization("kw", "arabíska", "Kúveit"),
  CountryLocalization("kg", "rússneska", "Kirgistan"),
  CountryLocalization("la", "laó", "Laos"),
  CountryLocalization("lv", "lettneska", "Lettland"),
  CountryLocalization("lb", "arabíska", "Líbanon"),
  CountryLocalization("ls", "enska", "Lesótó"),
  CountryLocalization("lr", "enska", "Líbería"),
  CountryLocalization("ly", "arabíska", "Líbía"),
  CountryLocalization("li", "svissnesk þýska", "Liechtenstein"),
  CountryLocalization("lt", "litháíska", "Litháen"),
  CountryLocalization("lu", "lúxemborgíska", "Lúxemborg"),
  CountryLocalization("mo", "portúgalska", "sérstjórnarsvæðið Makaó"),
  CountryLocalization("mk", "albanska", "Makedónía"),
  CountryLocalization("mg", "franska", "Madagaskar"),
  CountryLocalization("mw", "enska", "Malaví"),
  CountryLocalization("my", "tamílska", "Malasía"),
  CountryLocalization("ml", "franska", "Malí"),
  CountryLocalization("mt", "enska", "Malta"),
  CountryLocalization("mh", "enska", "Marshalleyjar"),
  CountryLocalization("mq", "franska", "Martiník"),
  CountryLocalization("mr", "arabíska", "Máritanía"),
  CountryLocalization("mu", "máritíska", "Máritíus"),
  CountryLocalization("yt", "franska", "Mayotte"),
  CountryLocalization("mx", "spænska", "Mexíkó"),
  CountryLocalization("fm", "enska", "Míkrónesía"),
  CountryLocalization("md", "rússneska", "Moldóva"),
  CountryLocalization("mc", "franska", "Mónakó"),
  CountryLocalization("mn", "mongólska", "Mongólía"),
  CountryLocalization("me", "serbneska", "Svartfjallaland"),
  CountryLocalization("ms", "enska", "Montserrat"),
  CountryLocalization("ma", "tamazight", "Marokkó"),
  CountryLocalization("mz", "makhuwa-meetto", "Mósambík"),
  CountryLocalization("mm", "burmneska", "Mjanmar (Búrma)"),
  CountryLocalization("na", "enska", "Namibía"),
  CountryLocalization("nr", "enska", "Nárú"),
  CountryLocalization("np", "nepalska", "Nepal"),
  CountryLocalization("nl", "enska", "Holland"),
  CountryLocalization("nc", "franska", "Nýja-Kaledónía"),
  CountryLocalization("nz", "enska", "Nýja-Sjáland"),
  CountryLocalization("ni", "spænska", "Níkaragva"),
  CountryLocalization("ne", "hása", "Níger"),
  CountryLocalization("ng", "hása", "Nígería"),
  CountryLocalization("nu", "enska", "Niue"),
  CountryLocalization("nf", "enska", "Norfolkeyja"),
  CountryLocalization("kp", "kóreska", "Norður-Kórea"),
  CountryLocalization("mp", "enska", "Norður-Maríanaeyjar"),
  CountryLocalization("no", "norðursamíska", "Noregur"),
  CountryLocalization("om", "arabíska", "Óman"),
  CountryLocalization("pk", "enska", "Pakistan"),
  CountryLocalization("pw", "enska", "Palá"),
  CountryLocalization("ps", "arabíska", "Heimastjórnarsvæði Palestínumanna"),
  CountryLocalization("pa", "spænska", "Panama"),
  CountryLocalization("pg", "enska", "Papúa Nýja-Gínea"),
  CountryLocalization("py", "spænska", "Paragvæ"),
  CountryLocalization("pe", "spænska", "Perú"),
  CountryLocalization("ph", "filippseyska", "Filippseyjar"),
  CountryLocalization("pn", "enska", "Pitcairn-eyjar"),
  CountryLocalization("pl", "pólska", "Pólland"),
  CountryLocalization("pt", "portúgalska", "Portúgal"),
  CountryLocalization("pr", "enska", "Púertó Ríkó"),
  CountryLocalization("qa", "arabíska", "Katar"),
  CountryLocalization("ro", "rúmenska", "Rúmenía"),
  CountryLocalization("ru", "tatarska", "Rússland"),
  CountryLocalization("rw", "enska", "Rúanda"),
  CountryLocalization("re", "franska", "Réunion"),
  CountryLocalization("ws", "enska", "Samóa"),
  CountryLocalization("sm", "ítalska", "San Marínó"),
  CountryLocalization("sa", "arabíska", "Sádi-Arabía"),
  CountryLocalization("sn", "franska", "Senegal"),
  CountryLocalization("rs", "serbneska", "Serbía"),
  CountryLocalization("cs", "serbneska", "Serbia and Montenegro"),
  CountryLocalization("sc", "franska", "Seychelles-eyjar"),
  CountryLocalization("sl", "enska", "Síerra Leóne"),
  CountryLocalization("sg", "tamílska", "Singapúr"),
  CountryLocalization("sx", "enska", "Sankti Martin"),
  CountryLocalization("sk", "slóvakíska", "Slóvakía"),
  CountryLocalization("si", "slóvenska", "Slóvenía"),
  CountryLocalization("sb", "enska", "Salómonseyjar"),
  CountryLocalization("so", "arabíska", "Sómalía"),
  CountryLocalization("za", "enska", "Suður-Afríka"),
  CountryLocalization("kr", "kóreska", "Suður-Kórea"),
  CountryLocalization("ss", "núer", "Suður-Súdan"),
  CountryLocalization("es", "spænska", "Spánn"),
  CountryLocalization("lk", "tamílska", "Srí Lanka"),
  CountryLocalization("bl", "franska", "Sankti Bartólómeusareyjar"),
  CountryLocalization("sh", "enska", "Sankti Helena"),
  CountryLocalization("kn", "enska", "Sankti Kitts og Nevis"),
  CountryLocalization("lc", "enska", "Sankti Lúsía"),
  CountryLocalization("mf", "franska", "St. Martin"),
  CountryLocalization("pm", "franska", "Sankti Pierre og Miquelon"),
  CountryLocalization("vc", "enska", "Sankti Vinsent og Grenadíneyjar"),
  CountryLocalization("sd", "arabíska", "Súdan"),
  CountryLocalization("sr", "hollenska", "Súrínam"),
  CountryLocalization("sj", "norskt bókmál", "Svalbarði og Jan Mayen"),
  CountryLocalization("sz", "enska", "Svasíland"),
  CountryLocalization("se", "sænska", "Svíþjóð"),
  CountryLocalization("ch", "svissnesk þýska", "Sviss"),
  CountryLocalization("sy", "arabíska", "Sýrland"),
  CountryLocalization("st", "portúgalska", "Saó Tóme og Prinsípe"),
  CountryLocalization("tw", "kínverska", "Taívan"),
  CountryLocalization("tj", "tadsjikska", "Tadsjikistan"),
  CountryLocalization("tz", "makonde", "Tansanía"),
  CountryLocalization("th", "taílenska", "Taíland"),
  CountryLocalization("tl", "portúgalska", "Tímor-Leste"),
  CountryLocalization("tg", "franska", "Tógó"),
  CountryLocalization("tk", "enska", "Tókelá"),
  CountryLocalization("to", "tongverska", "Tonga"),
  CountryLocalization("tt", "enska", "Trínidad og Tóbagó"),
  CountryLocalization("tn", "franska", "Túnis"),
  CountryLocalization("tr", "tyrkneska", "Tyrkland"),
  CountryLocalization("tm", "túrkmenska", "Túrkmenistan"),
  CountryLocalization("tc", "enska", "Turks- og Caicoseyjar"),
  CountryLocalization("tv", "enska", "Túvalú"),
  CountryLocalization("um", "enska", "Smáeyjar Bandaríkjanna"),
  CountryLocalization("vi", "enska", "Bandarísku Jómfrúaeyjar"),
  CountryLocalization("ug", "svahílí", "Úganda"),
  CountryLocalization("ua", "úkraínska", "Úkraína"),
  CountryLocalization("ae", "arabíska", "Sameinuðu arabísku furstadæmin"),
  CountryLocalization("gb", "enska", "Bretland"),
  CountryLocalization("us", "lakóta", "Bandaríkin"),
  CountryLocalization("uy", "spænska", "Úrúgvæ"),
  CountryLocalization("uz", "úsbekska", "Úsbekistan"),
  CountryLocalization("vu", "franska", "Vanúatú"),
  CountryLocalization("va", "ítalska", "Vatíkanið"),
  CountryLocalization("ve", "spænska", "Venesúela"),
  CountryLocalization("vn", "víetnamska", "Víetnam"),
  CountryLocalization("wf", "franska", "Wallis- og Fútúnaeyjar"),
  CountryLocalization("eh", "arabíska", "Vestur-Sahara"),
  CountryLocalization("ye", "arabíska", "Jemen"),
  CountryLocalization("zm", "enska", "Sambía"),
  CountryLocalization("zw", "norður-ndebele", "Simbabve"),
  CountryLocalization("ax", "sænska", "Álandseyjar"),
)
