/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot.atlas.extended

import dev.teogor.xenoglot.atlas.CountryLocalization
import kotlin.collections.List

/**
 * Holds the internal list of country-language mappings used for lookups within the package for
 * language code uk.
 *
 * This property contains a hardcoded list of [CountryLocalization] objects, each representing
 * a country and its associated official languages. This list is used by [CountryLanguageRegistry]
 * to provide access to country-language data and should not be modified directly.
 *
 * @see CountryLocalization
 * @see CountryLanguageRegistry
 */
internal val _countryLanguageMappings_uk: List<CountryLocalization> = listOf(
  CountryLocalization("af", "перська", "Афганістан"),
  CountryLocalization("al", "албанська", "Албанія"),
  CountryLocalization("dz", "французька", "Алжир"),
  CountryLocalization("as", "англійська", "Американське Самоа"),
  CountryLocalization("ad", "каталонська", "Андорра"),
  CountryLocalization("ao", "лінгала", "Ангола"),
  CountryLocalization("ai", "англійська", "Анґілья"),
  CountryLocalization("ag", "англійська", "Антиґуа і Барбуда"),
  CountryLocalization("ar", "іспанська", "Аргентина"),
  CountryLocalization("am", "вірменська", "Вірменія"),
  CountryLocalization("aw", "нідерландська", "Аруба"),
  CountryLocalization("au", "англійська", "Австралія"),
  CountryLocalization("at", "англійська", "Австрія"),
  CountryLocalization("az", "азербайджанська", "Азербайджан"),
  CountryLocalization("bs", "англійська", "Багамські Острови"),
  CountryLocalization("bh", "арабська", "Бахрейн"),
  CountryLocalization("bd", "банґла", "Бангладеш"),
  CountryLocalization("bb", "англійська", "Барбадос"),
  CountryLocalization("by", "білоруська", "Білорусь"),
  CountryLocalization("be", "французька", "Бельґія"),
  CountryLocalization("bz", "англійська", "Беліз"),
  CountryLocalization("bj", "французька", "Бенін"),
  CountryLocalization("bm", "англійська", "Бермудські острови"),
  CountryLocalization("bt", "дзонг-ке", "Бутан"),
  CountryLocalization("bo", "іспанська", "Болівія"),
  CountryLocalization("ba", "боснійська", "Боснія і Герцеґовина"),
  CountryLocalization("bw", "англійська", "Ботсвана"),
  CountryLocalization("br", "портуґальська", "Бразілія"),
  CountryLocalization("io", "англійська", "Британська територія в Індійському Океані"),
  CountryLocalization("vg", "англійська", "Британські Віргінські острови"),
  CountryLocalization("bn", "малайська", "Бруней"),
  CountryLocalization("bg", "болгарська", "Болгарія"),
  CountryLocalization("bf", "французька", "Буркіна-Фасо"),
  CountryLocalization("bi", "французька", "Бурунді"),
  CountryLocalization("kh", "кхмерська", "Камбоджа"),
  CountryLocalization("cm", "баса", "Камерун"),
  CountryLocalization("ca", "французька", "Канада"),
  CountryLocalization("ic", "іспанська", "Канарські острови"),
  CountryLocalization("cv", "кабувердіану", "Кабо-Верде"),
  CountryLocalization("bq", "нідерландська", "Нідерландські Карибські острови"),
  CountryLocalization("ky", "англійська", "Кайманові острови"),
  CountryLocalization("cf", "лінгала", "Центральноафриканська Республіка"),
  CountryLocalization("ea", "іспанська", "Сеута і Мелілья"),
  CountryLocalization("td", "арабська", "Чад"),
  CountryLocalization("cl", "іспанська", "Чілі"),
  CountryLocalization("cn", "тибетська", "Китай"),
  CountryLocalization("cx", "англійська", "Острів Різдва"),
  CountryLocalization("cc", "англійська", "Кокосові (Кілінгові) острови"),
  CountryLocalization("co", "іспанська", "Колумбія"),
  CountryLocalization("km", "арабська", "Коморські острови"),
  CountryLocalization("cg", "лінгала", "Конго – Браззавіль"),
  CountryLocalization("cd", "суахілі", "Конго – Кіншаса"),
  CountryLocalization("ck", "англійська", "Острови Кука"),
  CountryLocalization("cr", "іспанська", "Коста-Ріка"),
  CountryLocalization("hr", "хорватська", "Хорватія"),
  CountryLocalization("cu", "іспанська", "Куба"),
  CountryLocalization("cw", "нідерландська", "Кюрасао"),
  CountryLocalization("cy", "англійська", "Кіпр"),
  CountryLocalization("cz", "чеська", "Чехія"),
  CountryLocalization("ci", "французька", "Кот-д’Івуар"),
  CountryLocalization("dk", "англійська", "Данія"),
  CountryLocalization("dg", "англійська", "Дієго-Гарсія"),
  CountryLocalization("dj", "французька", "Джибуті"),
  CountryLocalization("dm", "англійська", "Домініка"),
  CountryLocalization("do", "іспанська", "Домініканська Республіка"),
  CountryLocalization("ec", "кечуа", "Еквадор"),
  CountryLocalization("eg", "арабська", "Єгипет"),
  CountryLocalization("sv", "іспанська", "Сальвадор"),
  CountryLocalization("gq", "іспанська", "Екваторіальна Гвінея"),
  CountryLocalization("er", "тигринья", "Еритрея"),
  CountryLocalization("ee", "естонська", "Естонія"),
  CountryLocalization("et", "амхарська", "Ефіопія"),
  CountryLocalization("fk", "англійська", "Фолклендські острови"),
  CountryLocalization("fo", "фарерська", "Фарерські Острови"),
  CountryLocalization("fj", "англійська", "Фіджі"),
  CountryLocalization("fi", "шведська", "Фінляндія"),
  CountryLocalization("fr", "німецька (Швейцарія)", "Франція"),
  CountryLocalization("gf", "французька", "Французька Ґвіана"),
  CountryLocalization("pf", "французька", "Французька Полінезія"),
  CountryLocalization("ga", "французька", "Габон"),
  CountryLocalization("gm", "англійська", "Гамбія"),
  CountryLocalization("ge", "осетинська", "Грузія"),
  CountryLocalization("de", "нижньолужицька", "Німеччина"),
  CountryLocalization("gh", "англійська", "Гана"),
  CountryLocalization("gi", "англійська", "Ґібралтар"),
  CountryLocalization("gr", "грецька", "Греція"),
  CountryLocalization("gl", "калааллісут", "Ґренландія"),
  CountryLocalization("gd", "англійська", "Ґренада"),
  CountryLocalization("gp", "французька", "Ґваделупа"),
  CountryLocalization("gu", "англійська", "Ґуам"),
  CountryLocalization("gt", "іспанська", "Ґватемала"),
  CountryLocalization("gg", "англійська", "Ґернсі"),
  CountryLocalization("gn", "французька", "Гвінея"),
  CountryLocalization("gw", "портуґальська", "Гвінея-Бісау"),
  CountryLocalization("gy", "англійська", "Ґайана"),
  CountryLocalization("ht", "французька", "Гаїті"),
  CountryLocalization("hn", "іспанська", "Гондурас"),
  CountryLocalization("hk", "китайська", "Гонконг, О.А.Р. Китаю"),
  CountryLocalization("hu", "угорська", "Угорщина"),
  CountryLocalization("is", "ісландська", "Ісландія"),
  CountryLocalization("in", "непальська", "Індія"),
  CountryLocalization("id", "Indonesian", "Індонезія"),
  CountryLocalization("ir", "перська", "Іран"),
  CountryLocalization("iq", "північнолурська", "Ірак"),
  CountryLocalization("ie", "англійська", "Ірландія"),
  CountryLocalization("im", "менкська", "Острів Мен"),
  CountryLocalization("il", "англійська", "Ізраїль"),
  CountryLocalization("it", "німецька", "Італія"),
  CountryLocalization("jm", "англійська", "Ямайка"),
  CountryLocalization("jp", "японська", "Японія"),
  CountryLocalization("je", "англійська", "Джерсі"),
  CountryLocalization("jo", "арабська", "Йорданія"),
  CountryLocalization("kz", "казахська", "Казахстан"),
  CountryLocalization("ke", "сомалі", "Кенія"),
  CountryLocalization("ki", "англійська", "Кірібаті"),
  CountryLocalization("xk", "сербська", "Косово"),
  CountryLocalization("kw", "арабська", "Кувейт"),
  CountryLocalization("kg", "російська", "Киргизстан"),
  CountryLocalization("la", "лаоська", "Лаос"),
  CountryLocalization("lv", "латвійська", "Латвія"),
  CountryLocalization("lb", "арабська", "Ліван"),
  CountryLocalization("ls", "англійська", "Лесото"),
  CountryLocalization("lr", "англійська", "Ліберія"),
  CountryLocalization("ly", "арабська", "Лівія"),
  CountryLocalization("li", "німецька (Швейцарія)", "Ліхтенштейн"),
  CountryLocalization("lt", "литовська", "Литва"),
  CountryLocalization("lu", "люксембурзька", "Люксембурґ"),
  CountryLocalization("mo", "портуґальська", "Макао, О.А.Р Китаю"),
  CountryLocalization("mk", "албанська", "Македонія"),
  CountryLocalization("mg", "французька", "Мадагаскар"),
  CountryLocalization("mw", "англійська", "Малаві"),
  CountryLocalization("my", "тамільська", "Малайзія"),
  CountryLocalization("ml", "французька", "Малі"),
  CountryLocalization("mt", "англійська", "Мальта"),
  CountryLocalization("mh", "англійська", "Маршаллові Острови"),
  CountryLocalization("mq", "французька", "Мартініка"),
  CountryLocalization("mr", "арабська", "Мавританія"),
  CountryLocalization("mu", "маврикійська креольська", "Маврікій"),
  CountryLocalization("yt", "французька", "Майотта"),
  CountryLocalization("mx", "іспанська", "Мексика"),
  CountryLocalization("fm", "англійська", "Мікронезія"),
  CountryLocalization("md", "російська", "Молдова"),
  CountryLocalization("mc", "французька", "Монако"),
  CountryLocalization("mn", "монгольська", "Монголія"),
  CountryLocalization("me", "сербська", "Чорногорія"),
  CountryLocalization("ms", "англійська", "Монтсеррат"),
  CountryLocalization("ma", "центральномароканська тамазіт", "Марокко"),
  CountryLocalization("mz", "макува-меето", "Мозамбік"),
  CountryLocalization("mm", "бірманська", "Мʼянма (Бірма)"),
  CountryLocalization("na", "англійська", "Намібія"),
  CountryLocalization("nr", "англійська", "Науру"),
  CountryLocalization("np", "непальська", "Непал"),
  CountryLocalization("nl", "англійська", "Нідерланди"),
  CountryLocalization("nc", "французька", "Нова Каледонія"),
  CountryLocalization("nz", "англійська", "Нова Зеландія"),
  CountryLocalization("ni", "іспанська", "Нікараґуа"),
  CountryLocalization("ne", "хауса", "Нігер"),
  CountryLocalization("ng", "хауса", "Нігерія"),
  CountryLocalization("nu", "англійська", "Ніуе"),
  CountryLocalization("nf", "англійська", "Острів Норфолк"),
  CountryLocalization("kp", "корейська", "Північна Корея"),
  CountryLocalization("mp", "англійська", "Північні Маріанські Острови"),
  CountryLocalization("no", "північносаамська", "Норвеґія"),
  CountryLocalization("om", "арабська", "Оман"),
  CountryLocalization("pk", "англійська", "Пакистан"),
  CountryLocalization("pw", "англійська", "Палау"),
  CountryLocalization("ps", "арабська", "Палестинські території"),
  CountryLocalization("pa", "іспанська", "Панама"),
  CountryLocalization("pg", "англійська", "Папуа-Нова Ґвінея"),
  CountryLocalization("py", "іспанська", "Параґвай"),
  CountryLocalization("pe", "іспанська", "Перу"),
  CountryLocalization("ph", "філіппінська", "Філіппіни"),
  CountryLocalization("pn", "англійська", "Острови Піткерн"),
  CountryLocalization("pl", "польська", "Польща"),
  CountryLocalization("pt", "портуґальська", "Портуґалія"),
  CountryLocalization("pr", "англійська", "Пуерто-Ріко"),
  CountryLocalization("qa", "арабська", "Катар"),
  CountryLocalization("ro", "румунська", "Румунія"),
  CountryLocalization("ru", "татарська", "Росія"),
  CountryLocalization("rw", "англійська", "Руанда"),
  CountryLocalization("re", "французька", "Реюньйон"),
  CountryLocalization("ws", "англійська", "Самоа"),
  CountryLocalization("sm", "італійська", "Сан-Маріно"),
  CountryLocalization("sa", "арабська", "Саудівська Аравія"),
  CountryLocalization("sn", "французька", "Сенегал"),
  CountryLocalization("rs", "сербська", "Сербія"),
  CountryLocalization("cs", "сербська", "Serbia and Montenegro"),
  CountryLocalization("sc", "французька", "Сейшельські Острови"),
  CountryLocalization("sl", "англійська", "Сьєрра-Леоне"),
  CountryLocalization("sg", "тамільська", "Сінгапур"),
  CountryLocalization("sx", "англійська", "Сінт-Мартен"),
  CountryLocalization("sk", "словацька", "Словаччина"),
  CountryLocalization("si", "словенська", "Словенія"),
  CountryLocalization("sb", "англійська", "Соломонові Острови"),
  CountryLocalization("so", "арабська", "Сомалі"),
  CountryLocalization("za", "англійська", "Південно-Африканська Республіка"),
  CountryLocalization("kr", "корейська", "Південна Корея"),
  CountryLocalization("ss", "нуер", "Південний Судан"),
  CountryLocalization("es", "іспанська", "Іспанія"),
  CountryLocalization("lk", "тамільська", "Шрі-Ланка"),
  CountryLocalization("bl", "французька", "Сен-Бартельмі"),
  CountryLocalization("sh", "англійська", "Острів Святої Єлени"),
  CountryLocalization("kn", "англійська", "Сент-Кітс і Невіс"),
  CountryLocalization("lc", "англійська", "Сент-Люсія"),
  CountryLocalization("mf", "французька", "Сен-Мартен"),
  CountryLocalization("pm", "французька", "Сен-Пʼєр і Мікелон"),
  CountryLocalization("vc", "англійська", "Сент-Вінсент і Ґренадіни"),
  CountryLocalization("sd", "арабська", "Судан"),
  CountryLocalization("sr", "нідерландська", "Сурінам"),
  CountryLocalization("sj", "норвезька (букмол)", "Шпіцберґен і Ян-Майен"),
  CountryLocalization("sz", "англійська", "Свазіленд"),
  CountryLocalization("se", "шведська", "Швеція"),
  CountryLocalization("ch", "німецька (Швейцарія)", "Швейцарія"),
  CountryLocalization("sy", "арабська", "Сирія"),
  CountryLocalization("st", "портуґальська", "Сан-Томе і Прінсіпі"),
  CountryLocalization("tw", "китайська", "Тайвань"),
  CountryLocalization("tj", "таджицька", "Таджикистан"),
  CountryLocalization("tz", "маконде", "Танзанія"),
  CountryLocalization("th", "тайська", "Таїланд"),
  CountryLocalization("tl", "портуґальська", "Тімор-Лешті"),
  CountryLocalization("tg", "французька", "Того"),
  CountryLocalization("tk", "англійська", "Токелау"),
  CountryLocalization("to", "тонґанська", "Тонґа"),
  CountryLocalization("tt", "англійська", "Трінідад і Тобаґо"),
  CountryLocalization("tn", "французька", "Туніс"),
  CountryLocalization("tr", "турецька", "Туреччина"),
  CountryLocalization("tm", "туркменська", "Туркменістан"),
  CountryLocalization("tc", "англійська", "Острови Теркс і Кайкос"),
  CountryLocalization("tv", "англійська", "Тувалу"),
  CountryLocalization("um", "англійська", "Віддалені острови США"),
  CountryLocalization("vi", "англійська", "Віргінські острови, США"),
  CountryLocalization("ug", "суахілі", "Уганда"),
  CountryLocalization("ua", "українська", "Україна"),
  CountryLocalization("ae", "арабська", "Обʼєднані Арабські Емірати"),
  CountryLocalization("gb", "англійська", "Велика Британія"),
  CountryLocalization("us", "лакота", "Сполучені Штати"),
  CountryLocalization("uy", "іспанська", "Уруґвай"),
  CountryLocalization("uz", "узбецька", "Узбекистан"),
  CountryLocalization("vu", "французька", "Вануату"),
  CountryLocalization("va", "італійська", "Ватикан"),
  CountryLocalization("ve", "іспанська", "Венесуела"),
  CountryLocalization("vn", "вʼєтнамська", "Вʼєтнам"),
  CountryLocalization("wf", "французька", "Уолліс і Футуна"),
  CountryLocalization("eh", "арабська", "Західна Сахара"),
  CountryLocalization("ye", "арабська", "Ємен"),
  CountryLocalization("zm", "англійська", "Замбія"),
  CountryLocalization("zw", "північна ндебеле", "Зімбабве"),
  CountryLocalization("ax", "шведська", "Аландські острови"),
)
