/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot.atlas.extended

import dev.teogor.xenoglot.atlas.CountryLocalization
import kotlin.collections.List

/**
 * Holds the internal list of country-language mappings used for lookups within the package for
 * language code km.
 *
 * This property contains a hardcoded list of [CountryLocalization] objects, each representing
 * a country and its associated official languages. This list is used by [CountryLanguageRegistry]
 * to provide access to country-language data and should not be modified directly.
 *
 * @see CountryLocalization
 * @see CountryLanguageRegistry
 */
internal val _countryLanguageMappings_km: List<CountryLocalization> = listOf(
  CountryLocalization("af", "ភឺសៀន", "អាហ្វហ្គានីស្ថាន"),
  CountryLocalization("al", "អាល់បានី", "អាល់បានី"),
  CountryLocalization("dz", "បារាំង", "អាល់ហ្សេរី"),
  CountryLocalization("as", "អង់គ្លេស", "សាម័រ អាមេរិកាំង"),
  CountryLocalization("ad", "កាតាឡាន", "អង់ដូរ៉ា"),
  CountryLocalization("ao", "លីនកាឡា", "អង់ហ្គោឡា"),
  CountryLocalization("ai", "អង់គ្លេស", "អង់ហ្គីឡា"),
  CountryLocalization("ag", "អង់គ្លេស", "អង់ទីហ្គា និង បាប៊ុយដា"),
  CountryLocalization("ar", "អេស្ប៉ាញ", "អាហ្សង់ទីន"),
  CountryLocalization("am", "អាមេនី", "អាមេនី"),
  CountryLocalization("aw", "ហូឡង់", "អារូបា"),
  CountryLocalization("au", "អង់គ្លេស", "អូស្ត្រាលី"),
  CountryLocalization("at", "អង់គ្លេស", "អូទ្រីស"),
  CountryLocalization("az", "អាស៊ែបៃហ្សង់", "អាស៊ែបៃហ្សង់"),
  CountryLocalization("bs", "អង់គ្លេស", "បាហាម៉ា"),
  CountryLocalization("bh", "អារ៉ាប់", "បារ៉ែន"),
  CountryLocalization("bd", "បង់ក្លាដែស", "បង់ក្លាដែស"),
  CountryLocalization("bb", "អង់គ្លេស", "បាបាដុស"),
  CountryLocalization("by", "បេឡារុស", "បេឡារុស"),
  CountryLocalization("be", "បារាំង", "បែលហ្ស៊ិក"),
  CountryLocalization("bz", "អង់គ្លេស", "បេលី"),
  CountryLocalization("bj", "បារាំង", "បេណាំង"),
  CountryLocalization("bm", "អង់គ្លេស", "ប៊ឺមុយដា"),
  CountryLocalization("bt", "ដុងខា", "ប៊ូតង់"),
  CountryLocalization("bo", "អេស្ប៉ាញ", "បូលីវី"),
  CountryLocalization("ba", "បូស្នី", "បូស្នី និងហឺហ្សីហ្គូវីណា"),
  CountryLocalization("bw", "អង់គ្លេស", "បុតស្វាណា"),
  CountryLocalization("br", "ព័រទុយហ្គាល់", "ប្រេស៊ីល"),
  CountryLocalization("io", "អង់គ្លេស", "ដែនដី​អង់គ្លេស​នៅ​មហា​សមុទ្រ​ឥណ្ឌា"),
  CountryLocalization("vg", "អង់គ្លេស", "កោះ​វឺជិន​ចក្រភព​អង់គ្លេស"),
  CountryLocalization("bn", "ម៉ាឡេ", "ព្រុយណេ"),
  CountryLocalization("bg", "ប៊ុលហ្គារី", "ប៊ុលហ្គារី"),
  CountryLocalization("bf", "បារាំង", "បួគីណាហ្វាសូ"),
  CountryLocalization("bi", "បារាំង", "ប៊ូរុនឌី"),
  CountryLocalization("kh", "ខ្មែរ", "កម្ពុជា"),
  CountryLocalization("cm", "បាសា", "កាមេរូន"),
  CountryLocalization("ca", "បារាំង", "កាណាដា"),
  CountryLocalization("ic", "អេស្ប៉ាញ", "កោះ​កាណារី"),
  CountryLocalization("cv", "កាប៊ូវឺឌៀនូ", "កាប់វែរ"),
  CountryLocalization("bq", "ហូឡង់", "ហូឡង់ ការ៉ាប៊ីន"),
  CountryLocalization("ky", "អង់គ្លេស", "កោះ​កៃម៉ង់"),
  CountryLocalization("cf", "លីនកាឡា", "សាធារណរដ្ឋអាហ្វ្រិកកណ្ដាល"),
  CountryLocalization("ea", "អេស្ប៉ាញ", "ជឺតា និង​ម៉េលីឡា"),
  CountryLocalization("td", "អារ៉ាប់", "ឆាដ"),
  CountryLocalization("cl", "អេស្ប៉ាញ", "ស៊ីលី"),
  CountryLocalization("cn", "ទីបេ", "ចិន"),
  CountryLocalization("cx", "អង់គ្លេស", "កោះ​គ្រីស្មាស"),
  CountryLocalization("cc", "អង់គ្លេស", "កោះ​កូកូស (គីលីង)"),
  CountryLocalization("co", "អេស្ប៉ាញ", "កូឡុំប៊ី"),
  CountryLocalization("km", "អារ៉ាប់", "កូម័រ"),
  CountryLocalization("cg", "លីនកាឡា", "កុងហ្គោ - ប្រាហ្សាវីល"),
  CountryLocalization("cd", "ស្វាហ៊ីលី", "កុងហ្គោ- គីនស្ហាសា"),
  CountryLocalization("ck", "អង់គ្លេស", "កោះ​ខូក"),
  CountryLocalization("cr", "អេស្ប៉ាញ", "កូស្តារីកា"),
  CountryLocalization("hr", "ក្រូអាត", "ក្រូអាស៊ី"),
  CountryLocalization("cu", "អេស្ប៉ាញ", "គុយបា"),
  CountryLocalization("cw", "ហូឡង់", "កូរ៉ាកៅ"),
  CountryLocalization("cy", "អង់គ្លេស", "ស៊ីប"),
  CountryLocalization("cz", "ឆែក", "ឆែគា"),
  CountryLocalization("ci", "បារាំង", "កូតឌីវ័រ"),
  CountryLocalization("dk", "អង់គ្លេស", "ដាណឺម៉ាក"),
  CountryLocalization("dg", "អង់គ្លេស", "ឌៀហ្គោហ្គាស៊ី"),
  CountryLocalization("dj", "បារាំង", "ជីប៊ូទី"),
  CountryLocalization("dm", "អង់គ្លេស", "ដូមីនីក"),
  CountryLocalization("do", "អេស្ប៉ាញ", "សាធារណរដ្ឋ​ដូមីនីក"),
  CountryLocalization("ec", "ហ្គិកឈួ", "អេក្វាទ័រ"),
  CountryLocalization("eg", "អារ៉ាប់", "អេហ្ស៊ីប"),
  CountryLocalization("sv", "អេស្ប៉ាញ", "អែលសាល់វ៉ាឌ័រ"),
  CountryLocalization("gq", "អេស្ប៉ាញ", "ហ្គីណេអេក្វាទ័រ"),
  CountryLocalization("er", "ទីហ្គ្រីញ៉ា", "អេរីត្រេ"),
  CountryLocalization("ee", "អេស្តូនី", "អេស្តូនី"),
  CountryLocalization("et", "អាំហារិក", "អេត្យូពី"),
  CountryLocalization("fk", "អង់គ្លេស", "កោះ​ហ្វក់ឡែន"),
  CountryLocalization("fo", "ហ្វារូស", "កោះ​ហ្វារ៉ូ"),
  CountryLocalization("fj", "អង់គ្លេស", "ហ្វីជី"),
  CountryLocalization("fi", "ស៊ុយអែត", "ហ្វាំងឡង់"),
  CountryLocalization("fr", "អាល្លឺម៉ង (ស្វីស)", "បារាំង"),
  CountryLocalization("gf", "បារាំង", "ហ្គីអាណា បារាំង"),
  CountryLocalization("pf", "បារាំង", "ប៉ូលី​ណេស៊ី​បារាំង"),
  CountryLocalization("ga", "បារាំង", "ហ្គាបុង"),
  CountryLocalization("gm", "អង់គ្លេស", "ហ្គំប៊ី"),
  CountryLocalization("ge", "អូស៊ីទិក", "ហ្សកហ្ស៊ី"),
  CountryLocalization("de", "សូប៊ីក្រោម", "អាល្លឺម៉ង់"),
  CountryLocalization("gh", "អង់គ្លេស", "ហ្គាណា"),
  CountryLocalization("gi", "អង់គ្លេស", "ហ្ស៊ីប្រាល់តា"),
  CountryLocalization("gr", "ក្រិក", "ក្រិក"),
  CountryLocalization("gl", "កាឡាលលីស៊ុត", "ហ្គ្រោអង់ឡង់"),
  CountryLocalization("gd", "អង់គ្លេស", "ហ្គ្រើណាដ"),
  CountryLocalization("gp", "បារាំង", "ហ្គោដឺឡុប"),
  CountryLocalization("gu", "អង់គ្លេស", "ហ្គាំ"),
  CountryLocalization("gt", "អេស្ប៉ាញ", "ក្វាតេម៉ាឡា"),
  CountryLocalization("gg", "អង់គ្លេស", "ហ្គេនស៊ី"),
  CountryLocalization("gn", "បារាំង", "ហ្គីណេ"),
  CountryLocalization("gw", "ព័រទុយហ្គាល់", "ហ្គីណេប៊ីស្សូ"),
  CountryLocalization("gy", "អង់គ្លេស", "ហ្គីយ៉ាន"),
  CountryLocalization("ht", "បារាំង", "ហៃទី"),
  CountryLocalization("hn", "អេស្ប៉ាញ", "ហុងឌូរ៉ាស"),
  CountryLocalization("hk", "ចិន", "ហុងកុង"),
  CountryLocalization("hu", "ហុងគ្រី", "ហុងគ្រី"),
  CountryLocalization("is", "អ៊ីស្លង់", "អ៊ីស្លង់"),
  CountryLocalization("in", "នេប៉ាល់", "ឥណ្ឌា"),
  CountryLocalization("id", "Indonesian", "ឥណ្ឌូណេស៊ី"),
  CountryLocalization("ir", "ភឺសៀន", "អ៊ីរ៉ង់"),
  CountryLocalization("iq", "លូរីខាងជើង", "អ៊ីរ៉ាក់"),
  CountryLocalization("ie", "អង់គ្លេស", "អៀរឡង់"),
  CountryLocalization("im", "មេន", "អែលអុហ្វមែន"),
  CountryLocalization("il", "អង់គ្លេស", "អ៊ីស្រាអែល"),
  CountryLocalization("it", "អាល្លឺម៉ង់", "អ៊ីតាលី"),
  CountryLocalization("jm", "អង់គ្លេស", "ហ្សាម៉ាអ៊ីក"),
  CountryLocalization("jp", "ជប៉ុន", "ជប៉ុន"),
  CountryLocalization("je", "អង់គ្លេស", "ជឺស៊ី"),
  CountryLocalization("jo", "អារ៉ាប់", "ហ៊្សកដានី"),
  CountryLocalization("kz", "កាហ្សាក់", "កាហ្សាក់ស្ថាន"),
  CountryLocalization("ke", "សូម៉ាលី", "កេនយ៉ា"),
  CountryLocalization("ki", "អង់គ្លេស", "គិរីបាទី"),
  CountryLocalization("xk", "ស៊ែប", "កូសូវ៉ូ"),
  CountryLocalization("kw", "អារ៉ាប់", "កូវ៉ែត"),
  CountryLocalization("kg", "រុស្ស៊ី", "កៀហ្ស៊ីស៊ីស្ថាន"),
  CountryLocalization("la", "ឡាវ", "ឡាវ"),
  CountryLocalization("lv", "ឡាតវី", "ឡេតូនី"),
  CountryLocalization("lb", "អារ៉ាប់", "លីបង់"),
  CountryLocalization("ls", "អង់គ្លេស", "ឡេសូតូ"),
  CountryLocalization("lr", "អង់គ្លេស", "លីបេរីយ៉ា"),
  CountryLocalization("ly", "អារ៉ាប់", "លីប៊ី"),
  CountryLocalization("li", "អាល្លឺម៉ង (ស្វីស)", "លិចតិនស្ដាញ"),
  CountryLocalization("lt", "លីទុយអានី", "លីទុយអានី"),
  CountryLocalization("lu", "លុចសំបួ", "លុចសំបួ"),
  CountryLocalization("mo", "ព័រទុយហ្គាល់", "ម៉ាកាវ តំបន់រដ្ឋបាលពិសេសចិន"),
  CountryLocalization("mk", "អាល់បានី", "ម៉ាសេដ្វាន"),
  CountryLocalization("mg", "បារាំង", "ម៉ាដាហ្គាស្កា"),
  CountryLocalization("mw", "អង់គ្លេស", "ម៉ាឡាវី"),
  CountryLocalization("my", "តាមីល", "ម៉ាឡេស៊ី"),
  CountryLocalization("ml", "បារាំង", "ម៉ាលី"),
  CountryLocalization("mt", "អង់គ្លេស", "ម៉ាល់ត៍"),
  CountryLocalization("mh", "អង់គ្លេស", "កោះ​ម៉ាស់សល"),
  CountryLocalization("mq", "បារាំង", "ម៉ាទីនីក"),
  CountryLocalization("mr", "អារ៉ាប់", "ម៉ូរីតានី"),
  CountryLocalization("mu", "ម៉ូរីស៊ីន", "ម៉ូរីស"),
  CountryLocalization("yt", "បារាំង", "ម៉ាយុត"),
  CountryLocalization("mx", "អេស្ប៉ាញ", "ម៉ិកស៊ិក"),
  CountryLocalization("fm", "អង់គ្លេស", "មីក្រូណេស៊ី"),
  CountryLocalization("md", "រុស្ស៊ី", "ម៉ុលដាវី"),
  CountryLocalization("mc", "បារាំង", "ម៉ូណាកូ"),
  CountryLocalization("mn", "ម៉ុងហ្គោលី", "ម៉ុងហ្គោលី"),
  CountryLocalization("me", "ស៊ែប", "ម៉ុងតេណេហ្គ្រោ"),
  CountryLocalization("ms", "អង់គ្លេស", "ម៉ុងស៊ែរ៉ា"),
  CountryLocalization("ma", "តាម៉ាសាយអាត្លាសកណ្តាល", "ម៉ារ៉ុក"),
  CountryLocalization("mz", "ម៉ាកគូវ៉ាមីតូ", "ម៉ូសំប៊ិក"),
  CountryLocalization("mm", "ភូមា", "មីយ៉ាន់ម៉ា (ភូមា)"),
  CountryLocalization("na", "អង់គ្លេស", "ណាមីប៊ី"),
  CountryLocalization("nr", "អង់គ្លេស", "ណូរូ"),
  CountryLocalization("np", "នេប៉ាល់", "នេប៉ាល់"),
  CountryLocalization("nl", "អង់គ្លេស", "ហូឡង់"),
  CountryLocalization("nc", "បារាំង", "នូវែល​កាឡេដូនី"),
  CountryLocalization("nz", "អង់គ្លេស", "នូវែល​សេឡង់"),
  CountryLocalization("ni", "អេស្ប៉ាញ", "នីការ៉ាហ្គា"),
  CountryLocalization("ne", "ហូសា", "នីហ្សេ"),
  CountryLocalization("ng", "ហូសា", "នីហ្សេរីយ៉ា"),
  CountryLocalization("nu", "អង់គ្លេស", "ណៀ"),
  CountryLocalization("nf", "អង់គ្លេស", "កោះ​ណ័រហ្វក់"),
  CountryLocalization("kp", "កូរ៉េ", "កូរ៉េ​ខាង​ជើង"),
  CountryLocalization("mp", "អង់គ្លេស", "កោះ​ម៉ារីណា​ខាង​ជើង"),
  CountryLocalization("no", "សាមីខាងជើង", "ន័រវែស"),
  CountryLocalization("om", "អារ៉ាប់", "អូម៉ង់"),
  CountryLocalization("pk", "អង់គ្លេស", "ប៉ាគីស្ថាន"),
  CountryLocalization("pw", "អង់គ្លេស", "ផៅឡូ"),
  CountryLocalization("ps", "អារ៉ាប់", "ដែន​ដីប៉ាលេស្ទីន"),
  CountryLocalization("pa", "អេស្ប៉ាញ", "ប៉ាណាម៉ា"),
  CountryLocalization("pg", "អង់គ្លេស", "ប៉ាពូអាស៊ី​នូវែលហ្គីណេ"),
  CountryLocalization("py", "អេស្ប៉ាញ", "ប៉ារ៉ាហ្គាយ"),
  CountryLocalization("pe", "អេស្ប៉ាញ", "ប៉េរូ"),
  CountryLocalization("ph", "ហ្វីលីពីន", "ហ្វីលីពីន"),
  CountryLocalization("pn", "អង់គ្លេស", "កោះ​ភីតកាន"),
  CountryLocalization("pl", "ប៉ូឡូញ", "ប៉ូឡូញ"),
  CountryLocalization("pt", "ព័រទុយហ្គាល់", "ព័រទុយហ្គាល់"),
  CountryLocalization("pr", "អង់គ្លេស", "ព័រតូរីកូ"),
  CountryLocalization("qa", "អារ៉ាប់", "កាតា"),
  CountryLocalization("ro", "រូម៉ានី", "រូម៉ានី"),
  CountryLocalization("ru", "តាតា", "រុស្ស៊ី"),
  CountryLocalization("rw", "អង់គ្លេស", "រវ៉ាន់ដា"),
  CountryLocalization("re", "បារាំង", "រេអុយញ៉ុង"),
  CountryLocalization("ws", "អង់គ្លេស", "សាម័រ"),
  CountryLocalization("sm", "អ៊ីតាលី", "សាន​ម៉ារីណូ"),
  CountryLocalization("sa", "អារ៉ាប់", "អារ៉ាប៊ីសាអូឌីត"),
  CountryLocalization("sn", "បារាំង", "សេណេហ្គាល់"),
  CountryLocalization("rs", "ស៊ែប", "សែប៊ី"),
  CountryLocalization("cs", "ស៊ែប", "Serbia and Montenegro"),
  CountryLocalization("sc", "បារាំង", "សីស្ហែល"),
  CountryLocalization("sl", "អង់គ្លេស", "សៀរ៉ាឡេអូន"),
  CountryLocalization("sg", "តាមីល", "សិង្ហបុរី"),
  CountryLocalization("sx", "អង់គ្លេស", "សីង​ម៉ាធីន"),
  CountryLocalization("sk", "ស្លូវ៉ាគី", "ស្លូវ៉ាគី"),
  CountryLocalization("si", "ស្លូវ៉ានី", "ស្លូវេនី"),
  CountryLocalization("sb", "អង់គ្លេស", "កោះ​សូឡូម៉ុង"),
  CountryLocalization("so", "អារ៉ាប់", "សូម៉ាលី"),
  CountryLocalization("za", "អង់គ្លេស", "អាហ្វ្រិកខាងត្បូង"),
  CountryLocalization("kr", "កូរ៉េ", "កូរ៉េ​ខាង​ត្បូង"),
  CountryLocalization("ss", "នូអ័រ", "ស៊ូដង់​ខាង​ត្បូង"),
  CountryLocalization("es", "អេស្ប៉ាញ", "អេស្ប៉ាញ"),
  CountryLocalization("lk", "តាមីល", "ស្រីលង្កា"),
  CountryLocalization("bl", "បារាំង", "សាំង​បាថេឡេមី"),
  CountryLocalization("sh", "អង់គ្លេស", "សង់​ហេឡេណា"),
  CountryLocalization("kn", "អង់គ្លេស", "សាំង​គីត និង ណេវីស"),
  CountryLocalization("lc", "អង់គ្លេស", "សាំងលូស៊ី"),
  CountryLocalization("mf", "បារាំង", "សាំង​ម៉ាទីន"),
  CountryLocalization("pm", "បារាំង", "សង់ព្យែរ និង​មីគីឡុង"),
  CountryLocalization("vc", "អង់គ្លេស", "សាំង​វ៉ាំងសង់ និង ហ្គ្រេណាឌីន"),
  CountryLocalization("sd", "អារ៉ាប់", "ស៊ូដង់"),
  CountryLocalization("sr", "ហូឡង់", "សូរីណាម"),
  CountryLocalization("sj", "ន័រវែស បុកម៉ាល់", "ស្វាលបាដ និង ហ្សង់ម៉ាយេន"),
  CountryLocalization("sz", "អង់គ្លេស", "ស្វាស៊ីឡង់"),
  CountryLocalization("se", "ស៊ុយអែត", "ស៊ុយអែត"),
  CountryLocalization("ch", "អាល្លឺម៉ង (ស្វីស)", "ស្វីស"),
  CountryLocalization("sy", "អារ៉ាប់", "ស៊ីរី"),
  CountryLocalization("st", "ព័រទុយហ្គាល់", "សៅតូម៉េ និង ប្រាំងស៊ីប"),
  CountryLocalization("tw", "ចិន", "តៃវ៉ាន់"),
  CountryLocalization("tj", "តាហ្ស៊ីគ", "តាហ្ស៊ីគីស្ថាន"),
  CountryLocalization("tz", "ម៉ាកូនដេ", "តង់សានី"),
  CountryLocalization("th", "ថៃ", "ថៃ"),
  CountryLocalization("tl", "ព័រទុយហ្គាល់", "ទីម័រលីស"),
  CountryLocalization("tg", "បារាំង", "តូហ្គោ"),
  CountryLocalization("tk", "អង់គ្លេស", "តូខេឡៅ"),
  CountryLocalization("to", "តុងហ្គា", "តុងហ្គា"),
  CountryLocalization("tt", "អង់គ្លេស", "ទ្រីនីដាត និង​តូបាហ្គោ"),
  CountryLocalization("tn", "បារាំង", "ទុយនីស៊ី"),
  CountryLocalization("tr", "ទួរគី", "តួកគី"),
  CountryLocalization("tm", "តួកម៉េន", "តួកម៉េនីស្ថាន"),
  CountryLocalization("tc", "អង់គ្លេស", "កោះ​ទួគ និង កៃកូស"),
  CountryLocalization("tv", "អង់គ្លេស", "ទូវ៉ាលូ"),
  CountryLocalization("um", "អង់គ្លេស", "កោះ​អៅឡាយីង​អាមេរិក"),
  CountryLocalization("vi", "អង់គ្លេស", "កោះ​វឺជីន​អាមេរិក"),
  CountryLocalization("ug", "ស្វាហ៊ីលី", "អ៊ូហ្គង់ដា"),
  CountryLocalization("ua", "អ៊ុយក្រែន", "អ៊ុយក្រែន"),
  CountryLocalization("ae", "អារ៉ាប់", "អេមីរ៉ាត​អារ៉ាប់​រួម"),
  CountryLocalization("gb", "អង់គ្លេស", "ចក្រភព​អង់គ្លេស"),
  CountryLocalization("us", "ឡាកូតា", "សហរដ្ឋអាមេរិក"),
  CountryLocalization("uy", "អេស្ប៉ាញ", "អ៊ុយរូហ្គាយ"),
  CountryLocalization("uz", "អ៊ូសបេគ", "អ៊ូសបេគីស្ថាន"),
  CountryLocalization("vu", "បារាំង", "វ៉ានូទូ"),
  CountryLocalization("va", "អ៊ីតាលី", "បុរី​វ៉ាទីកង់"),
  CountryLocalization("ve", "អេស្ប៉ាញ", "វ៉េណេស៊ុយអេឡា"),
  CountryLocalization("vn", "វៀតណាម", "វៀតណាម"),
  CountryLocalization("wf", "បារាំង", "វ៉ាលីស និង​ហ្វូទូណា"),
  CountryLocalization("eh", "អារ៉ាប់", "សាហារ៉ាខាងលិច"),
  CountryLocalization("ye", "អារ៉ាប់", "យេម៉ែន"),
  CountryLocalization("zm", "អង់គ្លេស", "សំប៊ី"),
  CountryLocalization("zw", "នេបេលេខាងជើង", "ស៊ីមបាវ៉េ"),
  CountryLocalization("ax", "ស៊ុយអែត", "កោះ​អាឡង់"),
)
