/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot.atlas.extended

import dev.teogor.xenoglot.atlas.CountryLocalization
import kotlin.collections.List

/**
 * Holds the internal list of country-language mappings used for lookups within the package for
 * language code am.
 *
 * This property contains a hardcoded list of [CountryLocalization] objects, each representing
 * a country and its associated official languages. This list is used by [CountryLanguageRegistry]
 * to provide access to country-language data and should not be modified directly.
 *
 * @see CountryLocalization
 * @see CountryLanguageRegistry
 */
internal val _countryLanguageMappings_am: List<CountryLocalization> = listOf(
  CountryLocalization("af", "ፐርሺያኛ", "አፍጋኒስታን"),
  CountryLocalization("al", "አልባንያንኛ", "አልባኒያ"),
  CountryLocalization("dz", "ፈረንሳይኛ", "አልጄሪያ"),
  CountryLocalization("as", "እንግሊዝኛ", "የአሜሪካ ሳሞአ"),
  CountryLocalization("ad", "ካታላንኛ", "አንዶራ"),
  CountryLocalization("ao", "ሊንጋላኛ", "አንጐላ"),
  CountryLocalization("ai", "እንግሊዝኛ", "አንጉይላ"),
  CountryLocalization("ag", "እንግሊዝኛ", "አንቲጓ እና ባሩዳ"),
  CountryLocalization("ar", "ስፓንሽኛ", "አርጀንቲና"),
  CountryLocalization("am", "አርመናዊ", "አርሜኒያ"),
  CountryLocalization("aw", "ደች", "አሩባ"),
  CountryLocalization("au", "እንግሊዝኛ", "አውስትራልያ"),
  CountryLocalization("at", "እንግሊዝኛ", "ኦስትሪያ"),
  CountryLocalization("az", "አዘርባጃንኛ", "አዘርባጃን"),
  CountryLocalization("bs", "እንግሊዝኛ", "ባሃማስ"),
  CountryLocalization("bh", "ዓረብኛ", "ባህሬን"),
  CountryLocalization("bd", "ቤንጋሊኛ", "ባንግላዲሽ"),
  CountryLocalization("bb", "እንግሊዝኛ", "ባርቤዶስ"),
  CountryLocalization("by", "ቤላራሻኛ", "ቤላሩስ"),
  CountryLocalization("be", "ፈረንሳይኛ", "ቤልጄም"),
  CountryLocalization("bz", "እንግሊዝኛ", "በሊዝ"),
  CountryLocalization("bj", "ፈረንሳይኛ", "ቤኒን"),
  CountryLocalization("bm", "እንግሊዝኛ", "ቤርሙዳ"),
  CountryLocalization("bt", "ድዞንግኻኛ", "ቡህታን"),
  CountryLocalization("bo", "ስፓንሽኛ", "ቦሊቪያ"),
  CountryLocalization("ba", "ቦስኒያንኛ", "ቦስኒያ እና ሄርዞጎቪኒያ"),
  CountryLocalization("bw", "እንግሊዝኛ", "ቦትስዋና"),
  CountryLocalization("br", "ፖርቹጋልኛ", "ብራዚል"),
  CountryLocalization("io", "እንግሊዝኛ", "የብሪታኒያ ህንድ ውቂያኖስ ግዛት"),
  CountryLocalization("vg", "እንግሊዝኛ", "የእንግሊዝ ቨርጂን ደሴቶች"),
  CountryLocalization("bn", "ማላይኛ", "ብሩኒ"),
  CountryLocalization("bg", "ቡልጋሪኛ", "ቡልጌሪያ"),
  CountryLocalization("bf", "ፈረንሳይኛ", "ቡርኪና ፋሶ"),
  CountryLocalization("bi", "ፈረንሳይኛ", "ብሩንዲ"),
  CountryLocalization("kh", "ክህመርኛ", "ካምቦዲያ"),
  CountryLocalization("cm", "ባሳ", "ካሜሩን"),
  CountryLocalization("ca", "ፈረንሳይኛ", "ካናዳ"),
  CountryLocalization("ic", "ስፓንሽኛ", "የካናሪ ደሴቶች"),
  CountryLocalization("cv", "ካቡቨርዲያኑ", "ኬፕ ቬርዴ"),
  CountryLocalization("bq", "ደች", "የካሪቢያን ኔዘርላንድስ"),
  CountryLocalization("ky", "እንግሊዝኛ", "ካይማን ደሴቶች"),
  CountryLocalization("cf", "ሊንጋላኛ", "የመካከለኛው አፍሪካ ሪፐብሊክ"),
  CountryLocalization("ea", "ስፓንሽኛ", "ሴኡታና ሜሊላ"),
  CountryLocalization("td", "ዓረብኛ", "ቻድ"),
  CountryLocalization("cl", "ስፓንሽኛ", "ቺሊ"),
  CountryLocalization("cn", "ቲቤታንኛ", "ቻይና"),
  CountryLocalization("cx", "እንግሊዝኛ", "የገና ደሴት"),
  CountryLocalization("cc", "እንግሊዝኛ", "ኮኮስ(ኬሊንግ) ደሴቶች"),
  CountryLocalization("co", "ስፓንሽኛ", "ኮሎምቢያ"),
  CountryLocalization("km", "ዓረብኛ", "ኮሞሮስ"),
  CountryLocalization("cg", "ሊንጋላኛ", "ኮንጎ ብራዛቪል"),
  CountryLocalization("cd", "ስዋሂሊኛ", "ኮንጎ-ኪንሻሳ"),
  CountryLocalization("ck", "እንግሊዝኛ", "ኩክ ደሴቶች"),
  CountryLocalization("cr", "ስፓንሽኛ", "ኮስታሪካ"),
  CountryLocalization("hr", "ክሮሽያንኛ", "ክሮኤሽያ"),
  CountryLocalization("cu", "ስፓንሽኛ", "ኩባ"),
  CountryLocalization("cw", "ደች", "ኩራሳዎ"),
  CountryLocalization("cy", "እንግሊዝኛ", "ሳይፕረስ"),
  CountryLocalization("cz", "ቼክኛ", "ቼችኒያ"),
  CountryLocalization("ci", "ፈረንሳይኛ", "ኮት ዲቯር"),
  CountryLocalization("dk", "እንግሊዝኛ", "ዴንማርክ"),
  CountryLocalization("dg", "እንግሊዝኛ", "ዲዬጎ ጋርሺያ"),
  CountryLocalization("dj", "ፈረንሳይኛ", "ጂቡቲ"),
  CountryLocalization("dm", "እንግሊዝኛ", "ዶሚኒካ"),
  CountryLocalization("do", "ስፓንሽኛ", "ዶመኒካን ሪፑብሊክ"),
  CountryLocalization("ec", "ኵቿኛ", "ኢኳዶር"),
  CountryLocalization("eg", "ዓረብኛ", "ግብጽ"),
  CountryLocalization("sv", "ስፓንሽኛ", "ኤል ሳልቫዶር"),
  CountryLocalization("gq", "ስፓንሽኛ", "ኢኳቶሪያል ጊኒ"),
  CountryLocalization("er", "ትግርኛ", "ኤርትራ"),
  CountryLocalization("ee", "ኢስቶኒያንኛ", "ኤስቶኒያ"),
  CountryLocalization("et", "አማርኛ", "ኢትዮጵያ"),
  CountryLocalization("fk", "እንግሊዝኛ", "የፎክላንድ ደሴቶች"),
  CountryLocalization("fo", "ፋሮኛ", "የፋሮ ደሴቶች"),
  CountryLocalization("fj", "እንግሊዝኛ", "ፊጂ"),
  CountryLocalization("fi", "ስዊድንኛ", "ፊንላንድ"),
  CountryLocalization("fr", "የስዊዝ ጀርመን", "ፈረንሳይ"),
  CountryLocalization("gf", "ፈረንሳይኛ", "የፈረንሳይ ጉዊአና"),
  CountryLocalization("pf", "ፈረንሳይኛ", "የፈረንሳይ ፖሊኔዢያ"),
  CountryLocalization("ga", "ፈረንሳይኛ", "ጋቦን"),
  CountryLocalization("gm", "እንግሊዝኛ", "ጋምቢያ"),
  CountryLocalization("ge", "ኦሴቲክ", "ጆርጂያ"),
  CountryLocalization("de", "የታችኛው ሰርቢያንኛ", "ጀርመን"),
  CountryLocalization("gh", "እንግሊዝኛ", "ጋና"),
  CountryLocalization("gi", "እንግሊዝኛ", "ጂብራልተር"),
  CountryLocalization("gr", "ግሪክኛ", "ግሪክ"),
  CountryLocalization("gl", "ካላሊሱትኛ", "ግሪንላንድ"),
  CountryLocalization("gd", "እንግሊዝኛ", "ግሬናዳ"),
  CountryLocalization("gp", "ፈረንሳይኛ", "ጉዋደሉፕ"),
  CountryLocalization("gu", "እንግሊዝኛ", "ጉዋም"),
  CountryLocalization("gt", "ስፓንሽኛ", "ጉዋቲማላ"),
  CountryLocalization("gg", "እንግሊዝኛ", "ጉርነሲ"),
  CountryLocalization("gn", "ፈረንሳይኛ", "ጊኒ"),
  CountryLocalization("gw", "ፖርቹጋልኛ", "ጊኒ ቢሳኦ"),
  CountryLocalization("gy", "እንግሊዝኛ", "ጉያና"),
  CountryLocalization("ht", "ፈረንሳይኛ", "ሀይቲ"),
  CountryLocalization("hn", "ስፓንሽኛ", "ሆንዱራስ"),
  CountryLocalization("hk", "ቻይንኛ", "ሆንግ ኮንግ ልዩ የአስተዳደር ክልል ቻይና"),
  CountryLocalization("hu", "ሀንጋሪኛ", "ሀንጋሪ"),
  CountryLocalization("is", "አይስላንድኛ", "አይስላንድ"),
  CountryLocalization("in", "ኔፓሊኛ", "ህንድ"),
  CountryLocalization("id", "Indonesian", "ኢንዶኔዢያ"),
  CountryLocalization("ir", "ፐርሺያኛ", "ኢራን"),
  CountryLocalization("iq", "ሰሜናዊ ሉሪ", "ኢራቅ"),
  CountryLocalization("ie", "እንግሊዝኛ", "አየርላንድ"),
  CountryLocalization("im", "ማንክስኛ", "አይል ኦፍ ማን"),
  CountryLocalization("il", "እንግሊዝኛ", "እስራኤል"),
  CountryLocalization("it", "ጀርመን", "ጣሊያን"),
  CountryLocalization("jm", "እንግሊዝኛ", "ጃማይካ"),
  CountryLocalization("jp", "ጃፓንኛ", "ጃፓን"),
  CountryLocalization("je", "እንግሊዝኛ", "ጀርሲ"),
  CountryLocalization("jo", "ዓረብኛ", "ጆርዳን"),
  CountryLocalization("kz", "ካዛክኛ", "ካዛኪስታን"),
  CountryLocalization("ke", "ሱማልኛ", "ኬንያ"),
  CountryLocalization("ki", "እንግሊዝኛ", "ኪሪባቲ"),
  CountryLocalization("xk", "ሰርቢኛ", "ኮሶቮ"),
  CountryLocalization("kw", "ዓረብኛ", "ክዌት"),
  CountryLocalization("kg", "ራሽያኛ", "ኪርጊስታን"),
  CountryLocalization("la", "ላኦኛ", "ላኦስ"),
  CountryLocalization("lv", "ላትቪያን", "ላትቪያ"),
  CountryLocalization("lb", "ዓረብኛ", "ሊባኖስ"),
  CountryLocalization("ls", "እንግሊዝኛ", "ሌሶቶ"),
  CountryLocalization("lr", "እንግሊዝኛ", "ላይቤሪያ"),
  CountryLocalization("ly", "ዓረብኛ", "ሊቢያ"),
  CountryLocalization("li", "የስዊዝ ጀርመን", "ሊችተንስታይን"),
  CountryLocalization("lt", "ሉቴንያንኛ", "ሊቱዌኒያ"),
  CountryLocalization("lu", "ሉክዘምበርኛ", "ሉክሰምበርግ"),
  CountryLocalization("mo", "ፖርቹጋልኛ", "ማካኡ ልዩ የአስተዳደር ክልል ቻይና"),
  CountryLocalization("mk", "አልባንያንኛ", "መቄዶንያ"),
  CountryLocalization("mg", "ፈረንሳይኛ", "ማዳጋስካር"),
  CountryLocalization("mw", "እንግሊዝኛ", "ማላዊ"),
  CountryLocalization("my", "ታሚልኛ", "ማሌዢያ"),
  CountryLocalization("ml", "ፈረንሳይኛ", "ማሊ"),
  CountryLocalization("mt", "እንግሊዝኛ", "ማልታ"),
  CountryLocalization("mh", "እንግሊዝኛ", "ማርሻል አይላንድ"),
  CountryLocalization("mq", "ፈረንሳይኛ", "ማርቲኒክ"),
  CountryLocalization("mr", "ዓረብኛ", "ሞሪቴኒያ"),
  CountryLocalization("mu", "ሞሪሲየኛ", "ሞሪሸስ"),
  CountryLocalization("yt", "ፈረንሳይኛ", "ሜይኦቴ"),
  CountryLocalization("mx", "ስፓንሽኛ", "ሜክሲኮ"),
  CountryLocalization("fm", "እንግሊዝኛ", "ሚክሮኔዢያ"),
  CountryLocalization("md", "ራሽያኛ", "ሞልዶቫ"),
  CountryLocalization("mc", "ፈረንሳይኛ", "ሞናኮ"),
  CountryLocalization("mn", "ሞንጎላዊኛ", "ሞንጎሊያ"),
  CountryLocalization("me", "ሰርቢኛ", "ሞንተኔግሮ"),
  CountryLocalization("ms", "እንግሊዝኛ", "ሞንትሴራት"),
  CountryLocalization("ma", "መካከለኛ አትላስ ታማዚግት", "ሞሮኮ"),
  CountryLocalization("mz", "ማኩዋ ሜቶ", "ሞዛምቢክ"),
  CountryLocalization("mm", "ቡርማኛ", "ማይናማር(በርማ)"),
  CountryLocalization("na", "እንግሊዝኛ", "ናሚቢያ"),
  CountryLocalization("nr", "እንግሊዝኛ", "ናኡሩ"),
  CountryLocalization("np", "ኔፓሊኛ", "ኔፓል"),
  CountryLocalization("nl", "እንግሊዝኛ", "ኔዘርላንድ"),
  CountryLocalization("nc", "ፈረንሳይኛ", "ኒው ካሌዶኒያ"),
  CountryLocalization("nz", "እንግሊዝኛ", "ኒው ዚላንድ"),
  CountryLocalization("ni", "ስፓንሽኛ", "ኒካራጓ"),
  CountryLocalization("ne", "ሃውሳኛ", "ኒጀር"),
  CountryLocalization("ng", "ሃውሳኛ", "ናይጄሪያ"),
  CountryLocalization("nu", "እንግሊዝኛ", "ኒኡይ"),
  CountryLocalization("nf", "እንግሊዝኛ", "ኖርፎልክ ደሴት"),
  CountryLocalization("kp", "ኮሪያኛ", "ሰሜን ኮሪያ"),
  CountryLocalization("mp", "እንግሊዝኛ", "የሰሜናዊ ማሪያና ደሴቶች"),
  CountryLocalization("no", "ሰሜናዊ ሳሚ", "ኖርዌይ"),
  CountryLocalization("om", "ዓረብኛ", "ኦማን"),
  CountryLocalization("pk", "እንግሊዝኛ", "ፓኪስታን"),
  CountryLocalization("pw", "እንግሊዝኛ", "ፓላው"),
  CountryLocalization("ps", "ዓረብኛ", "የፍልስጤም ግዛት"),
  CountryLocalization("pa", "ስፓንሽኛ", "ፓናማ"),
  CountryLocalization("pg", "እንግሊዝኛ", "ፓፑዋ ኒው ጊኒ"),
  CountryLocalization("py", "ስፓንሽኛ", "ፓራጓይ"),
  CountryLocalization("pe", "ስፓንሽኛ", "ፔሩ"),
  CountryLocalization("ph", "ፊሊፒንኛ", "ፊሊፒንስ"),
  CountryLocalization("pn", "እንግሊዝኛ", "ፒትካኢርን አይስላንድ"),
  CountryLocalization("pl", "ፖሊሽኛ", "ፖላንድ"),
  CountryLocalization("pt", "ፖርቹጋልኛ", "ፖርቱጋል"),
  CountryLocalization("pr", "እንግሊዝኛ", "ፖርታ ሪኮ"),
  CountryLocalization("qa", "ዓረብኛ", "ኳታር"),
  CountryLocalization("ro", "ሮማኒያን", "ሮሜኒያ"),
  CountryLocalization("ru", "ታታርኛ", "ሩስያ"),
  CountryLocalization("rw", "እንግሊዝኛ", "ሩዋንዳ"),
  CountryLocalization("re", "ፈረንሳይኛ", "ሪዩኒየን"),
  CountryLocalization("ws", "እንግሊዝኛ", "ሳሞአ"),
  CountryLocalization("sm", "ጣሊያንኛ", "ሳን ማሪኖ"),
  CountryLocalization("sa", "ዓረብኛ", "ሳውድአረቢያ"),
  CountryLocalization("sn", "ፈረንሳይኛ", "ሴኔጋል"),
  CountryLocalization("rs", "ሰርቢኛ", "ሰርብያ"),
  CountryLocalization("cs", "ሰርቢኛ", "Serbia and Montenegro"),
  CountryLocalization("sc", "ፈረንሳይኛ", "ሲሼልስ"),
  CountryLocalization("sl", "እንግሊዝኛ", "ሴራሊዮን"),
  CountryLocalization("sg", "ታሚልኛ", "ሲንጋፖር"),
  CountryLocalization("sx", "እንግሊዝኛ", "ሲንት ማርተን"),
  CountryLocalization("sk", "ስሎቫክኛ", "ስሎቫኪያ"),
  CountryLocalization("si", "ስሎቪኛ", "ስሎቬኒያ"),
  CountryLocalization("sb", "እንግሊዝኛ", "ሰሎሞን ደሴት"),
  CountryLocalization("so", "ዓረብኛ", "ሱማሌ"),
  CountryLocalization("za", "እንግሊዝኛ", "ደቡብ አፍሪካ"),
  CountryLocalization("kr", "ኮሪያኛ", "ደቡብ ኮሪያ"),
  CountryLocalization("ss", "ኑዌር", "ደቡብ ሱዳን"),
  CountryLocalization("es", "ስፓንሽኛ", "ስፔን"),
  CountryLocalization("lk", "ታሚልኛ", "ሲሪላንካ"),
  CountryLocalization("bl", "ፈረንሳይኛ", "ቅዱስ በርቴሎሜ"),
  CountryLocalization("sh", "እንግሊዝኛ", "ሴንት ሄለና"),
  CountryLocalization("kn", "እንግሊዝኛ", "ቅዱስ ኪትስ እና ኔቪስ"),
  CountryLocalization("lc", "እንግሊዝኛ", "ሴንት ሉቺያ"),
  CountryLocalization("mf", "ፈረንሳይኛ", "ሴንት ማርቲን"),
  CountryLocalization("pm", "ፈረንሳይኛ", "ቅዱስ ፒዬር እና ሚኩኤሎን"),
  CountryLocalization("vc", "እንግሊዝኛ", "ቅዱስ ቪንሴንት እና ግሬናዲንስ"),
  CountryLocalization("sd", "ዓረብኛ", "ሱዳን"),
  CountryLocalization("sr", "ደች", "ሱሪናም"),
  CountryLocalization("sj", "የኖርዌይ ቦክማል", "ስቫልባርድ እና ጃን ማየን"),
  CountryLocalization("sz", "እንግሊዝኛ", "ሱዋዚላንድ"),
  CountryLocalization("se", "ስዊድንኛ", "ስዊድን"),
  CountryLocalization("ch", "የስዊዝ ጀርመን", "ስዊዘርላንድ"),
  CountryLocalization("sy", "ዓረብኛ", "ሲሪያ"),
  CountryLocalization("st", "ፖርቹጋልኛ", "ሳኦ ቶሜ እና ፕሪንሲፔ"),
  CountryLocalization("tw", "ቻይንኛ", "ታይዋን"),
  CountryLocalization("tj", "ታጂኪኛ", "ታጃኪስታን"),
  CountryLocalization("tz", "ማኮንዴ", "ታንዛኒያ"),
  CountryLocalization("th", "ታይኛ", "ታይላንድ"),
  CountryLocalization("tl", "ፖርቹጋልኛ", "ምስራቅ ሌስት"),
  CountryLocalization("tg", "ፈረንሳይኛ", "ቶጐ"),
  CountryLocalization("tk", "እንግሊዝኛ", "ቶክላው"),
  CountryLocalization("to", "ቶንጋኛ", "ቶንጋ"),
  CountryLocalization("tt", "እንግሊዝኛ", "ትሪናዳድ እና ቶቤጎ"),
  CountryLocalization("tn", "ፈረንሳይኛ", "ቱኒዚያ"),
  CountryLocalization("tr", "ቱርክኛ", "ቱርክ"),
  CountryLocalization("tm", "ቱርክሜንኛ", "ቱርክሜኒስታን"),
  CountryLocalization("tc", "እንግሊዝኛ", "የቱርኮችና የካኢኮስ ደሴቶች"),
  CountryLocalization("tv", "እንግሊዝኛ", "ቱቫሉ"),
  CountryLocalization("um", "እንግሊዝኛ", "የዩ ኤስ ጠረፍ ላይ ያሉ ደሴቶች"),
  CountryLocalization("vi", "እንግሊዝኛ", "የአሜሪካ ቨርጂን ደሴቶች"),
  CountryLocalization("ug", "ስዋሂሊኛ", "ዩጋንዳ"),
  CountryLocalization("ua", "ዩክሬንኛ", "ዩክሬን"),
  CountryLocalization("ae", "ዓረብኛ", "የተባበሩት ዓረብ ኤምሬትስ"),
  CountryLocalization("gb", "እንግሊዝኛ", "ዩናይትድ ኪንግደም"),
  CountryLocalization("us", "ላኮታ", "ዩናይትድ ስቴትስ"),
  CountryLocalization("uy", "ስፓንሽኛ", "ኡራጓይ"),
  CountryLocalization("uz", "ኡዝቤክኛ", "ኡዝቤኪስታን"),
  CountryLocalization("vu", "ፈረንሳይኛ", "ቫኑአቱ"),
  CountryLocalization("va", "ጣሊያንኛ", "ቫቲካን ከተማ"),
  CountryLocalization("ve", "ስፓንሽኛ", "ቬንዙዌላ"),
  CountryLocalization("vn", "ቪየትናምኛ", "ቬትናም"),
  CountryLocalization("wf", "ፈረንሳይኛ", "ዋሊስ እና ፉቱና ደሴቶች"),
  CountryLocalization("eh", "ዓረብኛ", "ምዕራባዊ ሳህራ"),
  CountryLocalization("ye", "ዓረብኛ", "የመን"),
  CountryLocalization("zm", "እንግሊዝኛ", "ዛምቢያ"),
  CountryLocalization("zw", "ሰሜን ንዴብሌ", "ዚምቧቤ"),
  CountryLocalization("ax", "ስዊድንኛ", "የአላንድ ደሴቶች"),
)
