/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot.atlas.extended

import dev.teogor.xenoglot.atlas.CountryLocalization
import kotlin.collections.List

/**
 * Holds the internal list of country-language mappings used for lookups within the package for
 * language code kea.
 *
 * This property contains a hardcoded list of [CountryLocalization] objects, each representing
 * a country and its associated official languages. This list is used by [CountryLanguageRegistry]
 * to provide access to country-language data and should not be modified directly.
 *
 * @see CountryLocalization
 * @see CountryLanguageRegistry
 */
internal val _countryLanguageMappings_kea: List<CountryLocalization> = listOf(
  CountryLocalization("af", "persa", "Afeganistãu"),
  CountryLocalization("al", "albanes", "Albánia"),
  CountryLocalization("dz", "franses", "Arjélia"),
  CountryLocalization("as", "ingles", "Samoa Merkanu"),
  CountryLocalization("ad", "katalãu", "Andora"),
  CountryLocalization("ao", "Lingala", "Angola"),
  CountryLocalization("ai", "ingles", "Angila"),
  CountryLocalization("ag", "ingles", "Antigua i Barbuda"),
  CountryLocalization("ar", "spanhol", "Arjentina"),
  CountryLocalization("am", "arméniu", "Arménia"),
  CountryLocalization("aw", "olandes", "Aruba"),
  CountryLocalization("au", "ingles", "Austrália"),
  CountryLocalization("at", "ingles", "Áustria"),
  CountryLocalization("az", "azerbaijanu", "Azerbaijãu"),
  CountryLocalization("bs", "ingles", "Baamas"),
  CountryLocalization("bh", "árabi", "Barain"),
  CountryLocalization("bd", "bengali", "Bangladexi"),
  CountryLocalization("bb", "ingles", "Barbadus"),
  CountryLocalization("by", "bielorusu", "Belarus"),
  CountryLocalization("be", "franses", "Béljika"),
  CountryLocalization("bz", "ingles", "Belizi"),
  CountryLocalization("bj", "franses", "Benin"),
  CountryLocalization("bm", "ingles", "Bermudas"),
  CountryLocalization("bt", "dzonka", "Butãu"),
  CountryLocalization("bo", "spanhol", "Bolívia"),
  CountryLocalization("ba", "bosniu", "Bósnia i Erzegovina"),
  CountryLocalization("bw", "ingles", "Botsuana"),
  CountryLocalization("br", "purtuges", "Brazil"),
  CountryLocalization("io", "ingles", "Ilhas Británikas di Índiku"),
  CountryLocalization("vg", "ingles", "Ilhas Virjens Británikas"),
  CountryLocalization("bn", "maláiu", "Brunei"),
  CountryLocalization("bg", "búlgaru", "Bulgária"),
  CountryLocalization("bf", "franses", "Burkina Fasu"),
  CountryLocalization("bi", "franses", "Burundi"),
  CountryLocalization("kh", "kmer", "Kambodja"),
  CountryLocalization("cm", "Basaa", "Kamarõis"),
  CountryLocalization("ca", "franses", "Kanadá"),
  CountryLocalization("ic", "spanhol", "Kanárias"),
  CountryLocalization("cv", "kabuverdianu", "Kabu Verdi"),
  CountryLocalization("bq", "olandes", "Karaibas Olandezas"),
  CountryLocalization("ky", "ingles", "Ilhas Kaimãu"),
  CountryLocalization("cf", "Lingala", "Republika Sentru-Afrikanu"),
  CountryLocalization("ea", "spanhol", "Seuta i Melilha"),
  CountryLocalization("td", "árabi", "Txadi"),
  CountryLocalization("cl", "spanhol", "Xili"),
  CountryLocalization("cn", "tibetanu", "Xina"),
  CountryLocalization("cx", "ingles", "Ilha di Natal"),
  CountryLocalization("cc", "ingles", "Ilhas Kokus (Keeling)"),
  CountryLocalization("co", "spanhol", "Kolômbia"),
  CountryLocalization("km", "árabi", "Kamoris"),
  CountryLocalization("cg", "Lingala", "Kongu - Brazavili"),
  CountryLocalization("cd", "suaíli", "Kongu - Kinxasa"),
  CountryLocalization("ck", "ingles", "Ilhas Kuk"),
  CountryLocalization("cr", "spanhol", "Kosta Rika"),
  CountryLocalization("hr", "kroata", "Kroásia"),
  CountryLocalization("cu", "spanhol", "Kuba"),
  CountryLocalization("cw", "olandes", "Kurasau"),
  CountryLocalization("cy", "ingles", "Xipri"),
  CountryLocalization("cz", "txeku", "Txékia"),
  CountryLocalization("ci", "franses", "Kosta di Marfin"),
  CountryLocalization("dk", "ingles", "Dinamarka"),
  CountryLocalization("dg", "ingles", "Diegu Garsia"),
  CountryLocalization("dj", "franses", "Djibuti"),
  CountryLocalization("dm", "ingles", "Dominika"),
  CountryLocalization("do", "spanhol", "Repúblika Dominikana"),
  CountryLocalization("ec", "kexua", "Ekuador"),
  CountryLocalization("eg", "árabi", "Ejitu"),
  CountryLocalization("sv", "spanhol", "El Salvador"),
  CountryLocalization("gq", "spanhol", "Gine Ekuatorial"),
  CountryLocalization("er", "tigrinia", "Iritreia"),
  CountryLocalization("ee", "stonianu", "Stónia"),
  CountryLocalization("et", "amáriku", "Etiópia"),
  CountryLocalization("fk", "ingles", "Ilhas Malvinas"),
  CountryLocalization("fo", "faroes", "Ilhas Faroe"),
  CountryLocalization("fj", "ingles", "Fidji"),
  CountryLocalization("fi", "sueku", "Finlándia"),
  CountryLocalization("fr", "alimãu suísu", "Fransa"),
  CountryLocalization("gf", "franses", "Giana Franseza"),
  CountryLocalization("pf", "franses", "Polinézia Franseza"),
  CountryLocalization("ga", "franses", "Gabãu"),
  CountryLocalization("gm", "ingles", "Gámbia"),
  CountryLocalization("ge", "Ossetic", "Jiórjia"),
  CountryLocalization("de", "sórbiu baxu", "Alimanha"),
  CountryLocalization("gh", "ingles", "Gana"),
  CountryLocalization("gi", "ingles", "Jibraltar"),
  CountryLocalization("gr", "gregu", "Grésia"),
  CountryLocalization("gl", "groenlandes", "Gronelándia"),
  CountryLocalization("gd", "ingles", "Granada"),
  CountryLocalization("gp", "franses", "Guadalupi"),
  CountryLocalization("gu", "ingles", "Guam"),
  CountryLocalization("gt", "spanhol", "Guatimala"),
  CountryLocalization("gg", "ingles", "Gernzi"),
  CountryLocalization("gn", "franses", "Gine"),
  CountryLocalization("gw", "purtuges", "Gine-Bisau"),
  CountryLocalization("gy", "ingles", "Giana"),
  CountryLocalization("ht", "franses", "Aití"),
  CountryLocalization("hn", "spanhol", "Onduras"),
  CountryLocalization("hk", "xines", "Rejiãu Administrativu Spesial di Hong Kong"),
  CountryLocalization("hu", "úngaru", "Ungria"),
  CountryLocalization("is", "islandes", "Islándia"),
  CountryLocalization("in", "nepales", "Índia"),
  CountryLocalization("id", "Indonesian", "Indonézia"),
  CountryLocalization("ir", "persa", "Irãu"),
  CountryLocalization("iq", "lrc", "Iraki"),
  CountryLocalization("ie", "ingles", "Irlanda"),
  CountryLocalization("im", "manks", "Ilha di Man"),
  CountryLocalization("il", "ingles", "Israel"),
  CountryLocalization("it", "alimãu", "Itália"),
  CountryLocalization("jm", "ingles", "Jamaika"),
  CountryLocalization("jp", "japones", "Japãu"),
  CountryLocalization("je", "ingles", "Jersi"),
  CountryLocalization("jo", "árabi", "Jordánia"),
  CountryLocalization("kz", "kazak", "Kazakistãu"),
  CountryLocalization("ke", "somali", "Kénia"),
  CountryLocalization("ki", "ingles", "Kiribati"),
  CountryLocalization("xk", "sérviu", "Kozovu"),
  CountryLocalization("kw", "árabi", "Kueiti"),
  CountryLocalization("kg", "rusu", "Kirgistãu"),
  CountryLocalization("la", "lausianu", "Laus"),
  CountryLocalization("lv", "letãu", "Letónia"),
  CountryLocalization("lb", "árabi", "Líbanu"),
  CountryLocalization("ls", "ingles", "Lezotu"),
  CountryLocalization("lr", "ingles", "Libéria"),
  CountryLocalization("ly", "árabi", "Líbia"),
  CountryLocalization("li", "alimãu suísu", "Lixenstain"),
  CountryLocalization("lt", "lituanes", "Lituánia"),
  CountryLocalization("lu", "luxemburges", "Luxemburgu"),
  CountryLocalization("mo", "purtuges", "Rejiãu Administrativu Spesial di Makau"),
  CountryLocalization("mk", "albanes", "Masidónia"),
  CountryLocalization("mg", "franses", "Madagaskar"),
  CountryLocalization("mw", "ingles", "Malaui"),
  CountryLocalization("my", "tamil", "Malázia"),
  CountryLocalization("ml", "franses", "Mali"),
  CountryLocalization("mt", "ingles", "Malta"),
  CountryLocalization("mh", "ingles", "Ilhas Marxal"),
  CountryLocalization("mq", "franses", "Martinika"),
  CountryLocalization("mr", "árabi", "Mauritánia"),
  CountryLocalization("mu", "mfe", "Maurísia"),
  CountryLocalization("yt", "franses", "Maiote"),
  CountryLocalization("mx", "spanhol", "Méxiku"),
  CountryLocalization("fm", "ingles", "Mikronézia"),
  CountryLocalization("md", "rusu", "Moldávia"),
  CountryLocalization("mc", "franses", "Mónaku"),
  CountryLocalization("mn", "Mongolian", "Mongólia"),
  CountryLocalization("me", "sérviu", "Montenegru"),
  CountryLocalization("ms", "ingles", "Monserat"),
  CountryLocalization("ma", "tamazait di Atlas Sentral", "Marokus"),
  CountryLocalization("mz", "mgh", "Musambiki"),
  CountryLocalization("mm", "birmanes", "Mianmar (Birmánia)"),
  CountryLocalization("na", "ingles", "Namíbia"),
  CountryLocalization("nr", "ingles", "Nauru"),
  CountryLocalization("np", "nepales", "Nepal"),
  CountryLocalization("nl", "ingles", "Olanda"),
  CountryLocalization("nc", "franses", "Nova Kalidónia"),
  CountryLocalization("nz", "ingles", "Nova Zilándia"),
  CountryLocalization("ni", "spanhol", "Nikarágua"),
  CountryLocalization("ne", "auza", "Nijer"),
  CountryLocalization("ng", "auza", "Nijéria"),
  CountryLocalization("nu", "ingles", "Niue"),
  CountryLocalization("nf", "ingles", "Ilhas Norfolk"),
  CountryLocalization("kp", "korianu", "Koreia di Norti"),
  CountryLocalization("mp", "ingles", "Ilhas Marianas di Norti"),
  CountryLocalization("no", "Northern Sami", "Noruega"),
  CountryLocalization("om", "árabi", "Oman"),
  CountryLocalization("pk", "ingles", "Pakistãu"),
  CountryLocalization("pw", "ingles", "Palau"),
  CountryLocalization("ps", "árabi", "Palistina"),
  CountryLocalization("pa", "spanhol", "Panamá"),
  CountryLocalization("pg", "ingles", "Papua-Nova Gine"),
  CountryLocalization("py", "spanhol", "Paraguai"),
  CountryLocalization("pe", "spanhol", "Peru"),
  CountryLocalization("ph", "filipinu", "Filipinas"),
  CountryLocalization("pn", "ingles", "Pirkairn"),
  CountryLocalization("pl", "pulaku", "Pulónia"),
  CountryLocalization("pt", "purtuges", "Purtugal"),
  CountryLocalization("pr", "ingles", "Portu Riku"),
  CountryLocalization("qa", "árabi", "Katar"),
  CountryLocalization("ro", "rumenu", "Ruménia"),
  CountryLocalization("ru", "tatar", "Rúsia"),
  CountryLocalization("rw", "ingles", "Ruanda"),
  CountryLocalization("re", "franses", "Runiãu"),
  CountryLocalization("ws", "ingles", "Samoa"),
  CountryLocalization("sm", "italianu", "San Marinu"),
  CountryLocalization("sa", "árabi", "Arábia Saudita"),
  CountryLocalization("sn", "franses", "Senegal"),
  CountryLocalization("rs", "sérviu", "Sérvia"),
  CountryLocalization("cs", "sérviu", "Serbia and Montenegro"),
  CountryLocalization("sc", "franses", "Seixelis"),
  CountryLocalization("sl", "ingles", "Sera Lioa"),
  CountryLocalization("sg", "tamil", "Singapura"),
  CountryLocalization("sx", "ingles", "Sãu Martinhu di Olanda"),
  CountryLocalization("sk", "slovaku", "Slovákia"),
  CountryLocalization("si", "slovéniu", "Slovénia"),
  CountryLocalization("sb", "ingles", "Ilhas Salumãu"),
  CountryLocalization("so", "árabi", "Sumália"),
  CountryLocalization("za", "ingles", "Áfrika di Sul"),
  CountryLocalization("kr", "korianu", "Koreia di Sul"),
  CountryLocalization("ss", "nus", "Sudãu di Sul"),
  CountryLocalization("es", "spanhol", "Spanha"),
  CountryLocalization("lk", "tamil", "Sri Lanka"),
  CountryLocalization("bl", "franses", "Sãu Bartolomeu"),
  CountryLocalization("sh", "ingles", "Santa Ilena"),
  CountryLocalization("kn", "ingles", "Sãu Kristovãu i Nevis"),
  CountryLocalization("lc", "ingles", "Santa Lúsia"),
  CountryLocalization("mf", "franses", "Sãu Martinhu di Fransa"),
  CountryLocalization("pm", "franses", "San Piere i Mikelon"),
  CountryLocalization("vc", "ingles", "Sãu Bisenti i Granadinas"),
  CountryLocalization("sd", "árabi", "Sudãu"),
  CountryLocalization("sr", "olandes", "Surinami"),
  CountryLocalization("sj", "norueges bokmål", "Svalbard i Jan Maien"),
  CountryLocalization("sz", "ingles", "Suazilándia"),
  CountryLocalization("se", "sueku", "Suésia"),
  CountryLocalization("ch", "alimãu suísu", "Suisa"),
  CountryLocalization("sy", "árabi", "Síria"),
  CountryLocalization("st", "purtuges", "Sãu Tume i Prínsipi"),
  CountryLocalization("tw", "xines", "Taiuan"),
  CountryLocalization("tj", "tadjiki", "Tadjikistãu"),
  CountryLocalization("tz", "kde", "Tanzánia"),
  CountryLocalization("th", "tailandes", "Tailándia"),
  CountryLocalization("tl", "purtuges", "Timor Lesti"),
  CountryLocalization("tg", "franses", "Togu"),
  CountryLocalization("tk", "ingles", "Tokelau"),
  CountryLocalization("to", "tonganes", "Tonga"),
  CountryLocalization("tt", "ingles", "Trinidad i Tobagu"),
  CountryLocalization("tn", "franses", "Tunízia"),
  CountryLocalization("tr", "turku", "Turkia"),
  CountryLocalization("tm", "turkmenu", "Turkumenistãu"),
  CountryLocalization("tc", "ingles", "Ilhas Turkas i Kaikus"),
  CountryLocalization("tv", "ingles", "Tuvalu"),
  CountryLocalization("um", "ingles", "Ilhas Minoris Distantis de Stadus Unidus"),
  CountryLocalization("vi", "ingles", "Ilhas Virjens Merkanas"),
  CountryLocalization("ug", "suaíli", "Uganda"),
  CountryLocalization("ua", "ukranianu", "Ukránia"),
  CountryLocalization("ae", "árabi", "Emiradus Árabi Unidu"),
  CountryLocalization("gb", "ingles", "Reinu Unidu"),
  CountryLocalization("us", "lkt", "Stadus Unidos di Merka"),
  CountryLocalization("uy", "spanhol", "Uruguai"),
  CountryLocalization("uz", "uzbeki", "Uzbekistãu"),
  CountryLocalization("vu", "franses", "Vanuatu"),
  CountryLocalization("va", "italianu", "Vatikanu"),
  CountryLocalization("ve", "spanhol", "Vinizuela"),
  CountryLocalization("vn", "vietnamita", "Vietnam"),
  CountryLocalization("wf", "franses", "Ualis i Futuna"),
  CountryLocalization("eh", "árabi", "Sara Osidental"),
  CountryLocalization("ye", "árabi", "Iémen"),
  CountryLocalization("zm", "ingles", "Zámbia"),
  CountryLocalization("zw", "North Ndebele", "Zimbábui"),
  CountryLocalization("ax", "sueku", "Ilhas Åland"),
)
