/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot.atlas.extended

import dev.teogor.xenoglot.atlas.CountryLocalization
import kotlin.collections.List

/**
 * Holds the internal list of country-language mappings used for lookups within the package for
 * language code dsb.
 *
 * This property contains a hardcoded list of [CountryLocalization] objects, each representing
 * a country and its associated official languages. This list is used by [CountryLanguageRegistry]
 * to provide access to country-language data and should not be modified directly.
 *
 * @see CountryLocalization
 * @see CountryLanguageRegistry
 */
internal val _countryLanguageMappings_dsb: List<CountryLocalization> = listOf(
  CountryLocalization("af", "persišćina", "Afghanistan"),
  CountryLocalization("al", "albanšćina", "Albańska"),
  CountryLocalization("dz", "francojšćina", "Algeriska"),
  CountryLocalization("as", "engelšćina", "Ameriska Samoa"),
  CountryLocalization("ad", "katanlanšćina", "Andorra"),
  CountryLocalization("ao", "lingala", "Angola"),
  CountryLocalization("ai", "engelšćina", "Anguilla"),
  CountryLocalization("ag", "engelšćina", "Antigua a Barbuda"),
  CountryLocalization("ar", "špańšćina", "Argentinska"),
  CountryLocalization("am", "armeńšćina", "Armeńska"),
  CountryLocalization("aw", "nižozemšćina", "Aruba"),
  CountryLocalization("au", "engelšćina", "Awstralska"),
  CountryLocalization("at", "engelšćina", "Awstriska"),
  CountryLocalization("az", "azerbajdžanšćina", "Azerbajdžan"),
  CountryLocalization("bs", "engelšćina", "Bahamy"),
  CountryLocalization("bh", "arabšćina", "Bahrain"),
  CountryLocalization("bd", "bengalšćina", "Bangladeš"),
  CountryLocalization("bb", "engelšćina", "Barbados"),
  CountryLocalization("by", "běłorušćina", "Běłoruska"),
  CountryLocalization("be", "francojšćina", "Belgiska"),
  CountryLocalization("bz", "engelšćina", "Belize"),
  CountryLocalization("bj", "francojšćina", "Benin"),
  CountryLocalization("bm", "engelšćina", "Bermudy"),
  CountryLocalization("bt", "dzongkha", "Bhutan"),
  CountryLocalization("bo", "špańšćina", "Boliwiska"),
  CountryLocalization("ba", "bosnišćina", "Bosniska a Hercegowina"),
  CountryLocalization("bw", "engelšćina", "Botswana"),
  CountryLocalization("br", "portugalšćina", "Brazilska"),
  CountryLocalization("io", "engelšćina", "Britiski indiskooceaniski teritorium"),
  CountryLocalization("vg", "engelšćina", "Britiske kněžniske kupy"),
  CountryLocalization("bn", "malajšćina", "Brunei"),
  CountryLocalization("bg", "bulgaršćina", "Bulgarska"),
  CountryLocalization("bf", "francojšćina", "Burkina Faso"),
  CountryLocalization("bi", "francojšćina", "Burundi"),
  CountryLocalization("kh", "kambodžanšćina", "Kambodža"),
  CountryLocalization("cm", "Basaa", "Kamerun"),
  CountryLocalization("ca", "francojšćina", "Kanada"),
  CountryLocalization("ic", "špańšćina", "Kanariske kupy"),
  CountryLocalization("cv", "kapverdšćina", "Kap Verde"),
  CountryLocalization("bq", "nižozemšćina", "Karibiska Nižozemska"),
  CountryLocalization("ky", "engelšćina", "Kajmaniske kupy"),
  CountryLocalization("cf", "lingala", "Centralnoafriska republika"),
  CountryLocalization("ea", "špańšćina", "Ceuta a Melilla"),
  CountryLocalization("td", "arabšćina", "Čad"),
  CountryLocalization("cl", "špańšćina", "Chilska"),
  CountryLocalization("cn", "tibetšćina", "China"),
  CountryLocalization("cx", "engelšćina", "Gódowne kupy"),
  CountryLocalization("cc", "engelšćina", "Kokosowe kupy"),
  CountryLocalization("co", "špańšćina", "Kolumbiska"),
  CountryLocalization("km", "arabšćina", "Komory"),
  CountryLocalization("cg", "lingala", "Kongo-Brazzaville"),
  CountryLocalization("cd", "swahilišćina", "Kongo-Kinshasa"),
  CountryLocalization("ck", "engelšćina", "Cookowe kupy"),
  CountryLocalization("cr", "špańšćina", "Kosta Rika"),
  CountryLocalization("hr", "chorwatšćina", "Chorwatska"),
  CountryLocalization("cu", "špańšćina", "Kuba"),
  CountryLocalization("cw", "nižozemšćina", "Curaçao"),
  CountryLocalization("cy", "engelšćina", "Cypriska"),
  CountryLocalization("cz", "češćina", "Česka republika"),
  CountryLocalization("ci", "francojšćina", "Côte d’Ivoire"),
  CountryLocalization("dk", "engelšćina", "Dańska"),
  CountryLocalization("dg", "engelšćina", "Diego Garcia"),
  CountryLocalization("dj", "francojšćina", "Džibuti"),
  CountryLocalization("dm", "engelšćina", "Dominika"),
  CountryLocalization("do", "špańšćina", "Dominikańska republika"),
  CountryLocalization("ec", "kečua", "Ekwador"),
  CountryLocalization("eg", "arabšćina", "Egyptojska"),
  CountryLocalization("sv", "špańšćina", "El Salvador"),
  CountryLocalization("gq", "špańšćina", "Ekwatorialna Gineja"),
  CountryLocalization("er", "tigrinja", "Eritreja"),
  CountryLocalization("ee", "estišćina", "Estniska"),
  CountryLocalization("et", "amharšćina", "Etiopiska"),
  CountryLocalization("fk", "engelšćina", "Falklandske kupy"),
  CountryLocalization("fo", "ferejšćina", "Färöje"),
  CountryLocalization("fj", "engelšćina", "Fidži"),
  CountryLocalization("fi", "šwedšćina", "Finska"),
  CountryLocalization("fr", "šwicarska nimšćina", "Francojska"),
  CountryLocalization("gf", "francojšćina", "Francojska Guyana"),
  CountryLocalization("pf", "francojšćina", "Francojska Polyneziska"),
  CountryLocalization("ga", "francojšćina", "Gabun"),
  CountryLocalization("gm", "engelšćina", "Gambija"),
  CountryLocalization("ge", "Ossetic", "Georgiska"),
  CountryLocalization("de", "dolnoserbšćina", "Nimska"),
  CountryLocalization("gh", "engelšćina", "Ghana"),
  CountryLocalization("gi", "engelšćina", "Gibraltar"),
  CountryLocalization("gr", "grichišćina", "Grichiska"),
  CountryLocalization("gl", "grönlandšćina", "Grönlandska"),
  CountryLocalization("gd", "engelšćina", "Grenada"),
  CountryLocalization("gp", "francojšćina", "Guadeloupe"),
  CountryLocalization("gu", "engelšćina", "Guam"),
  CountryLocalization("gt", "špańšćina", "Guatemala"),
  CountryLocalization("gg", "engelšćina", "Guernsey"),
  CountryLocalization("gn", "francojšćina", "Gineja"),
  CountryLocalization("gw", "portugalšćina", "Gineja-Bissau"),
  CountryLocalization("gy", "engelšćina", "Guyana"),
  CountryLocalization("ht", "francojšćina", "Haiti"),
  CountryLocalization("hn", "špańšćina", "Honduras"),
  CountryLocalization("hk", "chinšćina", "Wósebna zastojnstwowa cona Hongkong"),
  CountryLocalization("hu", "hungoršćina", "Hungorska"),
  CountryLocalization("is", "islandšćina", "Islandska"),
  CountryLocalization("in", "nepalšćina", "Indiska"),
  CountryLocalization("id", "Indonesian", "Indoneziska"),
  CountryLocalization("ir", "persišćina", "Iran"),
  CountryLocalization("iq", "lrc", "Irak"),
  CountryLocalization("ie", "engelšćina", "Irska"),
  CountryLocalization("im", "manšćina", "Man"),
  CountryLocalization("il", "engelšćina", "Israel"),
  CountryLocalization("it", "nimšćina", "Italska"),
  CountryLocalization("jm", "engelšćina", "Jamaika"),
  CountryLocalization("jp", "japańšćina", "Japańska"),
  CountryLocalization("je", "engelšćina", "Jersey"),
  CountryLocalization("jo", "arabšćina", "Jordaniska"),
  CountryLocalization("kz", "kazachšćina", "Kazachstan"),
  CountryLocalization("ke", "somališćina", "Kenia"),
  CountryLocalization("ki", "engelšćina", "Kiribati"),
  CountryLocalization("xk", "serbišćina", "Kosowo"),
  CountryLocalization("kw", "arabšćina", "Kuwait"),
  CountryLocalization("kg", "rušćina", "Kirgizistan"),
  CountryLocalization("la", "laošćina", "Laos"),
  CountryLocalization("lv", "letišćina", "Letiska"),
  CountryLocalization("lb", "arabšćina", "Libanon"),
  CountryLocalization("ls", "engelšćina", "Lesotho"),
  CountryLocalization("lr", "engelšćina", "Liberija"),
  CountryLocalization("ly", "arabšćina", "Libyska"),
  CountryLocalization("li", "šwicarska nimšćina", "Liechtenstein"),
  CountryLocalization("lt", "litawšćina", "Litawska"),
  CountryLocalization("lu", "luxemburgšćina", "Luxemburgska"),
  CountryLocalization("mo", "portugalšćina", "Wósebna zastojnstwowa cona Macao"),
  CountryLocalization("mk", "albanšćina", "Makedońska"),
  CountryLocalization("mg", "francojšćina", "Madagaskar"),
  CountryLocalization("mw", "engelšćina", "Malawi"),
  CountryLocalization("my", "tamilšćina", "Malajzija"),
  CountryLocalization("ml", "francojšćina", "Mali"),
  CountryLocalization("mt", "engelšćina", "Malta"),
  CountryLocalization("mh", "engelšćina", "Marshallowe kupy"),
  CountryLocalization("mq", "francojšćina", "Martinique"),
  CountryLocalization("mr", "arabšćina", "Mawretańska"),
  CountryLocalization("mu", "mauriciska kreolšćina", "Mauritius"),
  CountryLocalization("yt", "francojšćina", "Mayotte"),
  CountryLocalization("mx", "špańšćina", "Mexiko"),
  CountryLocalization("fm", "engelšćina", "Mikroneziska"),
  CountryLocalization("md", "rušćina", "Moldawska"),
  CountryLocalization("mc", "francojšćina", "Monaco"),
  CountryLocalization("mn", "mongolšćina", "Mongolska"),
  CountryLocalization("me", "serbišćina", "Carna Góra"),
  CountryLocalization("ms", "engelšćina", "Montserrat"),
  CountryLocalization("ma", "centralnoatlaski tamazight", "Marokko"),
  CountryLocalization("mz", "makhuwa-meetto", "Mosambik"),
  CountryLocalization("mm", "burmašćina", "Myanmar"),
  CountryLocalization("na", "engelšćina", "Namibija"),
  CountryLocalization("nr", "engelšćina", "Nauru"),
  CountryLocalization("np", "nepalšćina", "Nepal"),
  CountryLocalization("nl", "engelšćina", "Nižozemska"),
  CountryLocalization("nc", "francojšćina", "Nowa Kaledoniska"),
  CountryLocalization("nz", "engelšćina", "Nowoseelandska"),
  CountryLocalization("ni", "špańšćina", "Nikaragua"),
  CountryLocalization("ne", "hausa", "Niger"),
  CountryLocalization("ng", "hausa", "Nigerija"),
  CountryLocalization("nu", "engelšćina", "Niue"),
  CountryLocalization("nf", "engelšćina", "Norfolkowa kupa"),
  CountryLocalization("kp", "korejańšćina", "Pódpołnocna Koreja"),
  CountryLocalization("mp", "engelšćina", "Pódpołnocne Mariany"),
  CountryLocalization("no", "lapšćina", "Norwegska"),
  CountryLocalization("om", "arabšćina", "Oman"),
  CountryLocalization("pk", "engelšćina", "Pakistan"),
  CountryLocalization("pw", "engelšćina", "Palau"),
  CountryLocalization("ps", "arabšćina", "Palestinski awtonomny teritorium"),
  CountryLocalization("pa", "špańšćina", "Panama"),
  CountryLocalization("pg", "engelšćina", "Papua-Neuguinea"),
  CountryLocalization("py", "špańšćina", "Paraguay"),
  CountryLocalization("pe", "špańšćina", "Peru"),
  CountryLocalization("ph", "filipinšćina", "Filipiny"),
  CountryLocalization("pn", "engelšćina", "Pitcairnowe kupy"),
  CountryLocalization("pl", "pólšćina", "Pólska"),
  CountryLocalization("pt", "portugalšćina", "Portugalska"),
  CountryLocalization("pr", "engelšćina", "Puerto Rico"),
  CountryLocalization("qa", "arabšćina", "Katar"),
  CountryLocalization("ro", "rumunšćina", "Rumuńska"),
  CountryLocalization("ru", "tataršćina", "Ruska"),
  CountryLocalization("rw", "engelšćina", "Ruanda"),
  CountryLocalization("re", "francojšćina", "Réunion"),
  CountryLocalization("ws", "engelšćina", "Samoa"),
  CountryLocalization("sm", "italšćina", "San Marino"),
  CountryLocalization("sa", "arabšćina", "Saudi-Arabiska"),
  CountryLocalization("sn", "francojšćina", "Senegal"),
  CountryLocalization("rs", "serbišćina", "Serbiska"),
  CountryLocalization("cs", "serbišćina", "Serbia and Montenegro"),
  CountryLocalization("sc", "francojšćina", "Seychelle"),
  CountryLocalization("sl", "engelšćina", "Sierra Leone"),
  CountryLocalization("sg", "tamilšćina", "Singapur"),
  CountryLocalization("sx", "engelšćina", "Sint Maarten"),
  CountryLocalization("sk", "słowakšćina", "Słowakska"),
  CountryLocalization("si", "słowjeńšćina", "Słowjeńska"),
  CountryLocalization("sb", "engelšćina", "Salomony"),
  CountryLocalization("so", "arabšćina", "Somalija"),
  CountryLocalization("za", "engelšćina", "Pódpołdnjowa Afrika (Republika)"),
  CountryLocalization("kr", "korejańšćina", "Pódpołdnjowa Koreja"),
  CountryLocalization("ss", "nuer", "Pódpołdnjowy Sudan"),
  CountryLocalization("es", "špańšćina", "Špańska"),
  CountryLocalization("lk", "tamilšćina", "Sri Lanka"),
  CountryLocalization("bl", "francojšćina", "St. Barthélemy"),
  CountryLocalization("sh", "engelšćina", "St. Helena"),
  CountryLocalization("kn", "engelšćina", "St. Kitts a Nevis"),
  CountryLocalization("lc", "engelšćina", "St. Lucia"),
  CountryLocalization("mf", "francojšćina", "St. Martin"),
  CountryLocalization("pm", "francojšćina", "St. Pierre a Miquelon"),
  CountryLocalization("vc", "engelšćina", "St. Vincent a Grenadiny"),
  CountryLocalization("sd", "arabšćina", "Sudan"),
  CountryLocalization("sr", "nižozemšćina", "Surinamska"),
  CountryLocalization("sj", "norwegske bokmål", "Svalbard a Jan Mayen"),
  CountryLocalization("sz", "engelšćina", "Swasiska"),
  CountryLocalization("se", "šwedšćina", "Šwedska"),
  CountryLocalization("ch", "šwicarska nimšćina", "Šwicarska"),
  CountryLocalization("sy", "arabšćina", "Syriska"),
  CountryLocalization("st", "portugalšćina", "São Tomé a Príncipe"),
  CountryLocalization("tw", "chinšćina", "Taiwan"),
  CountryLocalization("tj", "tadžikišćina", "Tadźikistan"),
  CountryLocalization("tz", "makonde", "Tansanija"),
  CountryLocalization("th", "thailandšćina", "Thailandska"),
  CountryLocalization("tl", "portugalšćina", "Timor-Leste"),
  CountryLocalization("tg", "francojšćina", "Togo"),
  CountryLocalization("tk", "engelšćina", "Tokelau"),
  CountryLocalization("to", "tonganšćina", "Tonga"),
  CountryLocalization("tt", "engelšćina", "Trinidad a Tobago"),
  CountryLocalization("tn", "francojšćina", "Tuneziska"),
  CountryLocalization("tr", "turkojšćina", "Turkojska"),
  CountryLocalization("tm", "turkmeńšćina", "Turkmeniska"),
  CountryLocalization("tc", "engelšćina", "Turks a Caicos kupy"),
  CountryLocalization("tv", "engelšćina", "Tuvalu"),
  CountryLocalization("um", "engelšćina", "Ameriska Oceaniska"),
  CountryLocalization("vi", "engelšćina", "Ameriske kněžniske kupy"),
  CountryLocalization("ug", "swahilišćina", "Uganda"),
  CountryLocalization("ua", "ukrainšćina", "Ukraina"),
  CountryLocalization("ae", "arabšćina", "Zjadnośone arabiske emiraty"),
  CountryLocalization("gb", "engelšćina", "Zjadnośone kralejstwo"),
  CountryLocalization("us", "lakotšćina", "Zjadnośone staty Ameriki"),
  CountryLocalization("uy", "špańšćina", "Uruguay"),
  CountryLocalization("uz", "usbekšćina", "Uzbekistan"),
  CountryLocalization("vu", "francojšćina", "Vanuatu"),
  CountryLocalization("va", "italšćina", "Vatikańske město"),
  CountryLocalization("ve", "špańšćina", "Venezuela"),
  CountryLocalization("vn", "vietnamšćina", "Vietnam"),
  CountryLocalization("wf", "francojšćina", "Wallis a Futuna"),
  CountryLocalization("eh", "arabšćina", "Pódwjacorna Sahara"),
  CountryLocalization("ye", "arabšćina", "Jemen"),
  CountryLocalization("zm", "engelšćina", "Sambija"),
  CountryLocalization("zw", "pódpołnocne ndebele", "Simbabwe"),
  CountryLocalization("ax", "šwedšćina", "Åland"),
)
