/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot.atlas.extended

import dev.teogor.xenoglot.atlas.CountryLocalization
import kotlin.collections.List

/**
 * Holds the internal list of country-language mappings used for lookups within the package for
 * language code ji.
 *
 * This property contains a hardcoded list of [CountryLocalization] objects, each representing
 * a country and its associated official languages. This list is used by [CountryLanguageRegistry]
 * to provide access to country-language data and should not be modified directly.
 *
 * @see CountryLocalization
 * @see CountryLanguageRegistry
 */
internal val _countryLanguageMappings_ji: List<CountryLocalization> = listOf(
  CountryLocalization("af", "פּערסיש", "אַפֿגהאַניסטאַן"),
  CountryLocalization("al", "אַלבאַניש", "אַלבאַניע"),
  CountryLocalization("dz", "פֿראַנצויזיש", "Algeria"),
  CountryLocalization("as", "ענגליש", "American Samoa"),
  CountryLocalization("ad", "קאַטאַלאניש", "אַנדארע"),
  CountryLocalization("ao", "Lingala", "אַנגאלע"),
  CountryLocalization("ai", "ענגליש", "Anguilla"),
  CountryLocalization("ag", "ענגליש", "אַנטיגוע און באַרבודע"),
  CountryLocalization("ar", "שפּאַניש", "אַרגענטינע"),
  CountryLocalization("am", "אַרמעניש", "אַרמעניע"),
  CountryLocalization("aw", "האלענדיש", "אַרובאַ"),
  CountryLocalization("au", "ענגליש", "אויסטראַליע"),
  CountryLocalization("at", "ענגליש", "עסטרייך"),
  CountryLocalization("az", "אַזערביידזשאַניש", "Azerbaijan"),
  CountryLocalization("bs", "ענגליש", "באַהאַמאַס"),
  CountryLocalization("bh", "אַראַביש", "Bahrain"),
  CountryLocalization("bd", "בענגאַליש", "באַנגלאַדעש"),
  CountryLocalization("bb", "ענגליש", "באַרבאַדאס"),
  CountryLocalization("by", "בעלאַרוסיש", "בעלאַרוס"),
  CountryLocalization("be", "פֿראַנצויזיש", "בעלגיע"),
  CountryLocalization("bz", "ענגליש", "בעליז"),
  CountryLocalization("bj", "פֿראַנצויזיש", "בענין"),
  CountryLocalization("bm", "ענגליש", "בערמודע"),
  CountryLocalization("bt", "Dzongkha", "בהוטאַן"),
  CountryLocalization("bo", "שפּאַניש", "באליוויע"),
  CountryLocalization("ba", "באסניש", "באסניע הערצעגאווינע"),
  CountryLocalization("bw", "ענגליש", "באצוואַנע"),
  CountryLocalization("br", "פּארטוגעזיש", "בראַזיל"),
  CountryLocalization("io", "ענגליש", "British Indian Ocean Territory"),
  CountryLocalization("vg", "ענגליש", "British Virgin Islands"),
  CountryLocalization("bn", "Malay", "ברוניי"),
  CountryLocalization("bg", "בולגאַריש", "בולגאַריע"),
  CountryLocalization("bf", "פֿראַנצויזיש", "בורקינע פֿאַסא"),
  CountryLocalization("bi", "פֿראַנצויזיש", "בורונדי"),
  CountryLocalization("kh", "כמער", "קאַמבאדיע"),
  CountryLocalization("cm", "Basaa", "קאַמערון"),
  CountryLocalization("ca", "פֿראַנצויזיש", "קאַנאַדע"),
  CountryLocalization("ic", "שפּאַניש", "קאַנאַרישע אינזלען"),
  CountryLocalization("cv", "kea", "קאַפּווערדישע אינזלען"),
  CountryLocalization("bq", "האלענדיש", "Caribbean Netherlands"),
  CountryLocalization("ky", "ענגליש", "קיימאַן אינזלען"),
  CountryLocalization("cf", "Lingala", "צענטראַל־אַפֿריקאַנישע רעפּובליק"),
  CountryLocalization("ea", "שפּאַניש", "EA"),
  CountryLocalization("td", "אַראַביש", "טשאַד"),
  CountryLocalization("cl", "שפּאַניש", "טשילע"),
  CountryLocalization("cn", "טיבעטיש", "כינע"),
  CountryLocalization("cx", "ענגליש", "Christmas Island"),
  CountryLocalization("cc", "ענגליש", "Cocos (Keeling) Islands"),
  CountryLocalization("co", "שפּאַניש", "קאלאמביע"),
  CountryLocalization("km", "אַראַביש", "קאמאראס"),
  CountryLocalization("cg", "Lingala", "Congo - Brazzaville"),
  CountryLocalization("cd", "סוואַהיליש", "קאנגא־קינשאַזע"),
  CountryLocalization("ck", "ענגליש", "קוק אינזלען"),
  CountryLocalization("cr", "שפּאַניש", "קאסטאַ ריקאַ"),
  CountryLocalization("hr", "קראאַטיש", "קראאַטיע"),
  CountryLocalization("cu", "שפּאַניש", "קובאַ"),
  CountryLocalization("cw", "האלענדיש", "קוראַסאַא"),
  CountryLocalization("cy", "ענגליש", "Cyprus"),
  CountryLocalization("cz", "טשעכיש", "טשעכיי"),
  CountryLocalization("ci", "פֿראַנצויזיש", "העלפֿאַ נדביין בארטן"),
  CountryLocalization("dk", "ענגליש", "דענמאַרק"),
  CountryLocalization("dg", "ענגליש", "DG"),
  CountryLocalization("dj", "פֿראַנצויזיש", "דזשיבוטי"),
  CountryLocalization("dm", "ענגליש", "דאמיניקע"),
  CountryLocalization("do", "שפּאַניש", "דאמיניקאַנישע רעפּובליק"),
  CountryLocalization("ec", "Quechua", "עקוואַדאר"),
  CountryLocalization("eg", "אַראַביש", "עגיפּטן"),
  CountryLocalization("sv", "שפּאַניש", "על סאַלוואַדאר"),
  CountryLocalization("gq", "שפּאַניש", "עקוואַטארישע גינע"),
  CountryLocalization("er", "Tigrinya", "עריטרעע"),
  CountryLocalization("ee", "עסטיש", "עסטלאַנד"),
  CountryLocalization("et", "אַמהאַריש", "עטיאפּיע"),
  CountryLocalization("fk", "ענגליש", "פֿאַלקלאַנד אינזלען"),
  CountryLocalization("fo", "פֿאַראיש", "פֿאַרא אינזלען"),
  CountryLocalization("fj", "ענגליש", "פֿידזשי"),
  CountryLocalization("fi", "שוועדיש", "פֿינלאַנד"),
  CountryLocalization("fr", "Swiss German", "פֿראַנקרייך"),
  CountryLocalization("gf", "פֿראַנצויזיש", "פֿראַנצויזישע גויאַנע"),
  CountryLocalization("pf", "פֿראַנצויזיש", "פֿראַנצויזישע פּאלינעזיע"),
  CountryLocalization("ga", "פֿראַנצויזיש", "גאַבאן"),
  CountryLocalization("gm", "ענגליש", "גאַמביע"),
  CountryLocalization("ge", "אסעטיש", "גרוזיע"),
  CountryLocalization("de", "אונטער־סארביש", "דייטשלאַנד"),
  CountryLocalization("gh", "ענגליש", "גהאַנע"),
  CountryLocalization("gi", "ענגליש", "גיבראַלטאַר"),
  CountryLocalization("gr", "גריכיש", "גריכנלאַנד"),
  CountryLocalization("gl", "Kalaallisut", "גרינלאַנד"),
  CountryLocalization("gd", "ענגליש", "גרענאַדאַ"),
  CountryLocalization("gp", "פֿראַנצויזיש", "גוואַדעלופ"),
  CountryLocalization("gu", "ענגליש", "גוואַם"),
  CountryLocalization("gt", "שפּאַניש", "גוואַטעמאַלע"),
  CountryLocalization("gg", "ענגליש", "גערנזי"),
  CountryLocalization("gn", "פֿראַנצויזיש", "גינע"),
  CountryLocalization("gw", "פּארטוגעזיש", "גינע־ביסאַו"),
  CountryLocalization("gy", "ענגליש", "גויאַנע"),
  CountryLocalization("ht", "פֿראַנצויזיש", "האַיטי"),
  CountryLocalization("hn", "שפּאַניש", "האנדוראַס"),
  CountryLocalization("hk", "כינעזיש", "Hong Kong SAR China"),
  CountryLocalization("hu", "אונגעריש", "אונגערן"),
  CountryLocalization("is", "איסלאַנדיש", "איסלאַנד"),
  CountryLocalization("in", "נעפּאַליש", "אינדיע"),
  CountryLocalization("id", "Indonesian", "אינדאנעזיע"),
  CountryLocalization("ir", "פּערסיש", "איראַן"),
  CountryLocalization("iq", "lrc", "Iraq"),
  CountryLocalization("ie", "ענגליש", "אירלאַנד"),
  CountryLocalization("im", "מאַנקס", "Isle of Man"),
  CountryLocalization("il", "ענגליש", "ישראל"),
  CountryLocalization("it", "דײַטש", "איטאַליע"),
  CountryLocalization("jm", "ענגליש", "דזשאַמייקע"),
  CountryLocalization("jp", "יאַפּאַניש", "יאַפּאַן"),
  CountryLocalization("je", "ענגליש", "דזשערזי"),
  CountryLocalization("jo", "אַראַביש", "Jordan"),
  CountryLocalization("kz", "קאַזאַכיש", "Kazakhstan"),
  CountryLocalization("ke", "סאמאַליש", "קעניע"),
  CountryLocalization("ki", "ענגליש", "קיריבאַטי"),
  CountryLocalization("xk", "סערביש", "קאסאווא"),
  CountryLocalization("kw", "אַראַביש", "Kuwait"),
  CountryLocalization("kg", "רוסיש", "Kyrgyzstan"),
  CountryLocalization("la", "לאַא", "לאַאס"),
  CountryLocalization("lv", "לעטיש", "לעטלאַנד"),
  CountryLocalization("lb", "אַראַביש", "לבנון"),
  CountryLocalization("ls", "ענגליש", "לעסאטא"),
  CountryLocalization("lr", "ענגליש", "ליבעריע"),
  CountryLocalization("ly", "אַראַביש", "ליביע"),
  CountryLocalization("li", "Swiss German", "ליכטנשטיין"),
  CountryLocalization("lt", "ליטוויש", "ליטע"),
  CountryLocalization("lu", "לוקסעמבורגיש", "לוקסעמבורג"),
  CountryLocalization("mo", "פּארטוגעזיש", "Macao SAR China"),
  CountryLocalization("mk", "אַלבאַניש", "מאַקעדאניע"),
  CountryLocalization("mg", "פֿראַנצויזיש", "מאַדאַגאַסקאַר"),
  CountryLocalization("mw", "ענגליש", "מאַלאַווי"),
  CountryLocalization("my", "טאַמיל", "מאַלייזיע"),
  CountryLocalization("ml", "פֿראַנצויזיש", "מאַלי"),
  CountryLocalization("mt", "ענגליש", "מאַלטאַ"),
  CountryLocalization("mh", "ענגליש", "מאַרשאַל אינזלען"),
  CountryLocalization("mq", "פֿראַנצויזיש", "מאַרטיניק"),
  CountryLocalization("mr", "אַראַביש", "מאַריטאַניע"),
  CountryLocalization("mu", "mfe", "מאריציוס"),
  CountryLocalization("yt", "פֿראַנצויזיש", "מאַיאט"),
  CountryLocalization("mx", "שפּאַניש", "מעקסיקע"),
  CountryLocalization("fm", "ענגליש", "מיקראנעזיע"),
  CountryLocalization("md", "רוסיש", "מאלדאווע"),
  CountryLocalization("mc", "פֿראַנצויזיש", "מאנאַקא"),
  CountryLocalization("mn", "מאנגאליש", "מאנגאליי"),
  CountryLocalization("me", "סערביש", "מאנטענעגרא"),
  CountryLocalization("ms", "ענגליש", "מאנטסעראַט"),
  CountryLocalization("ma", "tzm", "מאַראקא"),
  CountryLocalization("mz", "mgh", "מאזאַמביק"),
  CountryLocalization("mm", "בירמאַניש", "מיאַנמאַר"),
  CountryLocalization("na", "ענגליש", "נאַמיביע"),
  CountryLocalization("nr", "ענגליש", "Nauru"),
  CountryLocalization("np", "נעפּאַליש", "נעפּאַל"),
  CountryLocalization("nl", "ענגליש", "האלאַנד"),
  CountryLocalization("nc", "פֿראַנצויזיש", "נײַ קאַלעדאניע"),
  CountryLocalization("nz", "ענגליש", "ניו זילאַנד"),
  CountryLocalization("ni", "שפּאַניש", "ניקאַראַגוע"),
  CountryLocalization("ne", "האַוסאַ", "ניזשער"),
  CountryLocalization("ng", "האַוסאַ", "ניגעריע"),
  CountryLocalization("nu", "ענגליש", "Niue"),
  CountryLocalization("nf", "ענגליש", "נארפֿאלק אינזל"),
  CountryLocalization("kp", "קארעאיש", "North Korea"),
  CountryLocalization("mp", "ענגליש", "Northern Mariana Islands"),
  CountryLocalization("no", "נארדסאַמיש", "נארוועגיע"),
  CountryLocalization("om", "אַראַביש", "Oman"),
  CountryLocalization("pk", "ענגליש", "פּאַקיסטאַן"),
  CountryLocalization("pw", "ענגליש", "Palau"),
  CountryLocalization("ps", "אַראַביש", "Palestinian Territories"),
  CountryLocalization("pa", "שפּאַניש", "פּאַנאַמאַ"),
  CountryLocalization("pg", "ענגליש", "פּאַפּואַ נײַ גינע"),
  CountryLocalization("py", "שפּאַניש", "פּאַראַגווײַ"),
  CountryLocalization("pe", "שפּאַניש", "פּערו"),
  CountryLocalization("ph", "פֿיליפּינא", "פֿיליפּינען"),
  CountryLocalization("pn", "ענגליש", "פּיטקערן אינזלען"),
  CountryLocalization("pl", "פּויליש", "פּוילן"),
  CountryLocalization("pt", "פּארטוגעזיש", "פּארטוגאַל"),
  CountryLocalization("pr", "ענגליש", "פּארטא־ריקא"),
  CountryLocalization("qa", "אַראַביש", "קאַטאַר"),
  CountryLocalization("ro", "רומעניש", "רומעניע"),
  CountryLocalization("ru", "טאָטעריש", "רוסלאַנד"),
  CountryLocalization("rw", "ענגליש", "רוואַנדע"),
  CountryLocalization("re", "פֿראַנצויזיש", "רעאוניאן"),
  CountryLocalization("ws", "ענגליש", "סאַמאאַ"),
  CountryLocalization("sm", "איטאַליעניש", "סאַן מאַרינא"),
  CountryLocalization("sa", "אַראַביש", "Saudi Arabia"),
  CountryLocalization("sn", "פֿראַנצויזיש", "סענעגאַל"),
  CountryLocalization("rs", "סערביש", "סערביע"),
  CountryLocalization("cs", "סערביש", "Serbia and Montenegro"),
  CountryLocalization("sc", "פֿראַנצויזיש", "סיישעל"),
  CountryLocalization("sl", "ענגליש", "סיערע לעאנע"),
  CountryLocalization("sg", "טאַמיל", "סינגאַפּור"),
  CountryLocalization("sx", "ענגליש", "Sint Maarten"),
  CountryLocalization("sk", "סלאוואַקיש", "סלאוואַקיי"),
  CountryLocalization("si", "סלאוועניש", "סלאוועניע"),
  CountryLocalization("sb", "ענגליש", "סאלאמאן אינזלען"),
  CountryLocalization("so", "אַראַביש", "סאמאַליע"),
  CountryLocalization("za", "ענגליש", "דרום־אַפֿריקע"),
  CountryLocalization("kr", "קארעאיש", "South Korea"),
  CountryLocalization("ss", "nus", "דרום־סודאַן"),
  CountryLocalization("es", "שפּאַניש", "שפּאַניע"),
  CountryLocalization("lk", "טאַמיל", "סרי־לאַנקאַ"),
  CountryLocalization("bl", "פֿראַנצויזיש", "St. Barthélemy"),
  CountryLocalization("sh", "ענגליש", "סט העלענע"),
  CountryLocalization("kn", "ענגליש", "St. Kitts & Nevis"),
  CountryLocalization("lc", "ענגליש", "St. Lucia"),
  CountryLocalization("mf", "פֿראַנצויזיש", "St. Martin"),
  CountryLocalization("pm", "פֿראַנצויזיש", "St. Pierre & Miquelon"),
  CountryLocalization("vc", "ענגליש", "St. Vincent & Grenadines"),
  CountryLocalization("sd", "אַראַביש", "סודאַן"),
  CountryLocalization("sr", "האלענדיש", "סורינאַם"),
  CountryLocalization("sj", "Norwegian Bokmål", "Svalbard & Jan Mayen"),
  CountryLocalization("sz", "ענגליש", "סוואַזילאַנד"),
  CountryLocalization("se", "שוועדיש", "שוועדן"),
  CountryLocalization("ch", "Swiss German", "שווייץ"),
  CountryLocalization("sy", "אַראַביש", "סיריע"),
  CountryLocalization("st", "פּארטוגעזיש", "סאַא טאמע און פּרינסיפּע"),
  CountryLocalization("tw", "כינעזיש", "Taiwan"),
  CountryLocalization("tj", "Tajik", "Tajikistan"),
  CountryLocalization("tz", "kde", "טאַנזאַניע"),
  CountryLocalization("th", "Thai", "טיילאַנד"),
  CountryLocalization("tl", "פּארטוגעזיש", "Timor-Leste"),
  CountryLocalization("tg", "פֿראַנצויזיש", "טאגא"),
  CountryLocalization("tk", "ענגליש", "Tokelau"),
  CountryLocalization("to", "Tongan", "טאנגאַ"),
  CountryLocalization("tt", "ענגליש", "טרינידאַד און טאבאַגא"),
  CountryLocalization("tn", "פֿראַנצויזיש", "טוניסיע"),
  CountryLocalization("tr", "Turkish", "טערקיי"),
  CountryLocalization("tm", "טורקמעניש", "טורקמעניסטאַן"),
  CountryLocalization("tc", "ענגליש", "Turks & Caicos Islands"),
  CountryLocalization("tv", "ענגליש", "טואוואַלו"),
  CountryLocalization("um", "ענגליש", "U.S. Outlying Islands"),
  CountryLocalization("vi", "ענגליש", "U.S. Virgin Islands"),
  CountryLocalization("ug", "סוואַהיליש", "אוגאַנדע"),
  CountryLocalization("ua", "אוקראַאיניש", "אוקראַינע"),
  CountryLocalization("ae", "אַראַביש", "United Arab Emirates"),
  CountryLocalization("gb", "ענגליש", "פֿאַראייניגטע קעניגרייך"),
  CountryLocalization("us", "lkt", "פֿאַראייניגטע שטאַטן"),
  CountryLocalization("uy", "שפּאַניש", "אורוגוויי"),
  CountryLocalization("uz", "אוזבעקיש", "Uzbekistan"),
  CountryLocalization("vu", "פֿראַנצויזיש", "וואַנואַטו"),
  CountryLocalization("va", "איטאַליעניש", "וואַטיקאַן שטאָט"),
  CountryLocalization("ve", "שפּאַניש", "ווענעזועלע"),
  CountryLocalization("vn", "וויעטנאַמעזיש", "וויעטנאַם"),
  CountryLocalization("wf", "פֿראַנצויזיש", "Wallis & Futuna"),
  CountryLocalization("eh", "אַראַביש", "Western Sahara"),
  CountryLocalization("ye", "אַראַביש", "תימן"),
  CountryLocalization("zm", "ענגליש", "זאַמביע"),
  CountryLocalization("zw", "North Ndebele", "זימבאַבווע"),
  CountryLocalization("ax", "שוועדיש", "Åland Islands"),
)
