/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot.atlas.extended

import dev.teogor.xenoglot.atlas.CountryLocalization
import kotlin.collections.List

/**
 * Holds the internal list of country-language mappings used for lookups within the package for
 * language code it.
 *
 * This property contains a hardcoded list of [CountryLocalization] objects, each representing
 * a country and its associated official languages. This list is used by [CountryLanguageRegistry]
 * to provide access to country-language data and should not be modified directly.
 *
 * @see CountryLocalization
 * @see CountryLanguageRegistry
 */
internal val _countryLanguageMappings_it: List<CountryLocalization> = listOf(
  CountryLocalization("af", "persiano", "Afghanistan"),
  CountryLocalization("al", "albanese", "Albania"),
  CountryLocalization("dz", "francese", "Algeria"),
  CountryLocalization("as", "inglese", "Samoa americane"),
  CountryLocalization("ad", "catalano", "Andorra"),
  CountryLocalization("ao", "lingala", "Angola"),
  CountryLocalization("ai", "inglese", "Anguilla"),
  CountryLocalization("ag", "inglese", "Antigua e Barbuda"),
  CountryLocalization("ar", "spagnolo", "Argentina"),
  CountryLocalization("am", "armeno", "Armenia"),
  CountryLocalization("aw", "olandese", "Aruba"),
  CountryLocalization("au", "inglese", "Australia"),
  CountryLocalization("at", "inglese", "Austria"),
  CountryLocalization("az", "azerbaigiano", "Azerbaigian"),
  CountryLocalization("bs", "inglese", "Bahamas"),
  CountryLocalization("bh", "arabo", "Bahrein"),
  CountryLocalization("bd", "bengalese", "Bangladesh"),
  CountryLocalization("bb", "inglese", "Barbados"),
  CountryLocalization("by", "bielorusso", "Bielorussia"),
  CountryLocalization("be", "francese", "Belgio"),
  CountryLocalization("bz", "inglese", "Belize"),
  CountryLocalization("bj", "francese", "Benin"),
  CountryLocalization("bm", "inglese", "Bermuda"),
  CountryLocalization("bt", "dzongkha", "Bhutan"),
  CountryLocalization("bo", "spagnolo", "Bolivia"),
  CountryLocalization("ba", "bosniaco", "Bosnia ed Erzegovina"),
  CountryLocalization("bw", "inglese", "Botswana"),
  CountryLocalization("br", "portoghese", "Brasile"),
  CountryLocalization("io", "inglese", "Territorio britannico dell’Oceano Indiano"),
  CountryLocalization("vg", "inglese", "Isole Vergini Britanniche"),
  CountryLocalization("bn", "malese", "Brunei"),
  CountryLocalization("bg", "bulgaro", "Bulgaria"),
  CountryLocalization("bf", "francese", "Burkina Faso"),
  CountryLocalization("bi", "francese", "Burundi"),
  CountryLocalization("kh", "khmer", "Cambogia"),
  CountryLocalization("cm", "basa", "Camerun"),
  CountryLocalization("ca", "francese", "Canada"),
  CountryLocalization("ic", "spagnolo", "Isole Canarie"),
  CountryLocalization("cv", "capoverdiano", "Capo Verde"),
  CountryLocalization("bq", "olandese", "Caraibi olandesi"),
  CountryLocalization("ky", "inglese", "Isole Cayman"),
  CountryLocalization("cf", "lingala", "Repubblica Centrafricana"),
  CountryLocalization("ea", "spagnolo", "Ceuta e Melilla"),
  CountryLocalization("td", "arabo", "Ciad"),
  CountryLocalization("cl", "spagnolo", "Cile"),
  CountryLocalization("cn", "tibetano", "Cina"),
  CountryLocalization("cx", "inglese", "Isola Christmas"),
  CountryLocalization("cc", "inglese", "Isole Cocos (Keeling)"),
  CountryLocalization("co", "spagnolo", "Colombia"),
  CountryLocalization("km", "arabo", "Comore"),
  CountryLocalization("cg", "lingala", "Congo-Brazzaville"),
  CountryLocalization("cd", "swahili", "Congo - Kinshasa"),
  CountryLocalization("ck", "inglese", "Isole Cook"),
  CountryLocalization("cr", "spagnolo", "Costa Rica"),
  CountryLocalization("hr", "croato", "Croazia"),
  CountryLocalization("cu", "spagnolo", "Cuba"),
  CountryLocalization("cw", "olandese", "Curaçao"),
  CountryLocalization("cy", "inglese", "Cipro"),
  CountryLocalization("cz", "ceco", "Cechia"),
  CountryLocalization("ci", "francese", "Costa d’Avorio"),
  CountryLocalization("dk", "inglese", "Danimarca"),
  CountryLocalization("dg", "inglese", "Diego Garcia"),
  CountryLocalization("dj", "francese", "Gibuti"),
  CountryLocalization("dm", "inglese", "Dominica"),
  CountryLocalization("do", "spagnolo", "Repubblica Dominicana"),
  CountryLocalization("ec", "quechua", "Ecuador"),
  CountryLocalization("eg", "arabo", "Egitto"),
  CountryLocalization("sv", "spagnolo", "El Salvador"),
  CountryLocalization("gq", "spagnolo", "Guinea Equatoriale"),
  CountryLocalization("er", "tigrino", "Eritrea"),
  CountryLocalization("ee", "estone", "Estonia"),
  CountryLocalization("et", "amarico", "Etiopia"),
  CountryLocalization("fk", "inglese", "Isole Falkland"),
  CountryLocalization("fo", "faroese", "Isole Fær Øer"),
  CountryLocalization("fj", "inglese", "Figi"),
  CountryLocalization("fi", "svedese", "Finlandia"),
  CountryLocalization("fr", "tedesco svizzero", "Francia"),
  CountryLocalization("gf", "francese", "Guyana francese"),
  CountryLocalization("pf", "francese", "Polinesia francese"),
  CountryLocalization("ga", "francese", "Gabon"),
  CountryLocalization("gm", "inglese", "Gambia"),
  CountryLocalization("ge", "ossetico", "Georgia"),
  CountryLocalization("de", "basso sorabo", "Germania"),
  CountryLocalization("gh", "inglese", "Ghana"),
  CountryLocalization("gi", "inglese", "Gibilterra"),
  CountryLocalization("gr", "greco", "Grecia"),
  CountryLocalization("gl", "groenlandese", "Groenlandia"),
  CountryLocalization("gd", "inglese", "Grenada"),
  CountryLocalization("gp", "francese", "Guadalupa"),
  CountryLocalization("gu", "inglese", "Guam"),
  CountryLocalization("gt", "spagnolo", "Guatemala"),
  CountryLocalization("gg", "inglese", "Guernsey"),
  CountryLocalization("gn", "francese", "Guinea"),
  CountryLocalization("gw", "portoghese", "Guinea-Bissau"),
  CountryLocalization("gy", "inglese", "Guyana"),
  CountryLocalization("ht", "francese", "Haiti"),
  CountryLocalization("hn", "spagnolo", "Honduras"),
  CountryLocalization("hk", "cinese", "RAS di Hong Kong"),
  CountryLocalization("hu", "ungherese", "Ungheria"),
  CountryLocalization("is", "islandese", "Islanda"),
  CountryLocalization("in", "nepalese", "India"),
  CountryLocalization("id", "indonesiano", "Indonesia"),
  CountryLocalization("ir", "persiano", "Iran"),
  CountryLocalization("iq", "luri settentrionale", "Iraq"),
  CountryLocalization("ie", "inglese", "Irlanda"),
  CountryLocalization("im", "mannese", "Isola di Man"),
  CountryLocalization("il", "inglese", "Israele"),
  CountryLocalization("it", "tedesco", "Italia"),
  CountryLocalization("jm", "inglese", "Giamaica"),
  CountryLocalization("jp", "giapponese", "Giappone"),
  CountryLocalization("je", "inglese", "Jersey"),
  CountryLocalization("jo", "arabo", "Giordania"),
  CountryLocalization("kz", "kazako", "Kazakistan"),
  CountryLocalization("ke", "somalo", "Kenya"),
  CountryLocalization("ki", "inglese", "Kiribati"),
  CountryLocalization("xk", "serbo", "Kosovo"),
  CountryLocalization("kw", "arabo", "Kuwait"),
  CountryLocalization("kg", "russo", "Kirghizistan"),
  CountryLocalization("la", "lao", "Laos"),
  CountryLocalization("lv", "lettone", "Lettonia"),
  CountryLocalization("lb", "arabo", "Libano"),
  CountryLocalization("ls", "inglese", "Lesotho"),
  CountryLocalization("lr", "inglese", "Liberia"),
  CountryLocalization("ly", "arabo", "Libia"),
  CountryLocalization("li", "tedesco svizzero", "Liechtenstein"),
  CountryLocalization("lt", "lituano", "Lituania"),
  CountryLocalization("lu", "lussemburghese", "Lussemburgo"),
  CountryLocalization("mo", "portoghese", "RAS di Macao"),
  CountryLocalization("mk", "albanese", "Repubblica di Macedonia"),
  CountryLocalization("mg", "francese", "Madagascar"),
  CountryLocalization("mw", "inglese", "Malawi"),
  CountryLocalization("my", "tamil", "Malaysia"),
  CountryLocalization("ml", "francese", "Mali"),
  CountryLocalization("mt", "inglese", "Malta"),
  CountryLocalization("mh", "inglese", "Isole Marshall"),
  CountryLocalization("mq", "francese", "Martinica"),
  CountryLocalization("mr", "arabo", "Mauritania"),
  CountryLocalization("mu", "creolo mauriziano", "Mauritius"),
  CountryLocalization("yt", "francese", "Mayotte"),
  CountryLocalization("mx", "spagnolo", "Messico"),
  CountryLocalization("fm", "inglese", "Micronesia"),
  CountryLocalization("md", "russo", "Moldavia"),
  CountryLocalization("mc", "francese", "Monaco"),
  CountryLocalization("mn", "mongolo", "Mongolia"),
  CountryLocalization("me", "serbo", "Montenegro"),
  CountryLocalization("ms", "inglese", "Montserrat"),
  CountryLocalization("ma", "tamazight", "Marocco"),
  CountryLocalization("mz", "makhuwa-meetto", "Mozambico"),
  CountryLocalization("mm", "birmano", "Myanmar (Birmania)"),
  CountryLocalization("na", "inglese", "Namibia"),
  CountryLocalization("nr", "inglese", "Nauru"),
  CountryLocalization("np", "nepalese", "Nepal"),
  CountryLocalization("nl", "inglese", "Paesi Bassi"),
  CountryLocalization("nc", "francese", "Nuova Caledonia"),
  CountryLocalization("nz", "inglese", "Nuova Zelanda"),
  CountryLocalization("ni", "spagnolo", "Nicaragua"),
  CountryLocalization("ne", "hausa", "Niger"),
  CountryLocalization("ng", "hausa", "Nigeria"),
  CountryLocalization("nu", "inglese", "Niue"),
  CountryLocalization("nf", "inglese", "Isola Norfolk"),
  CountryLocalization("kp", "coreano", "Corea del Nord"),
  CountryLocalization("mp", "inglese", "Isole Marianne settentrionali"),
  CountryLocalization("no", "sami del nord", "Norvegia"),
  CountryLocalization("om", "arabo", "Oman"),
  CountryLocalization("pk", "inglese", "Pakistan"),
  CountryLocalization("pw", "inglese", "Palau"),
  CountryLocalization("ps", "arabo", "Territori palestinesi"),
  CountryLocalization("pa", "spagnolo", "Panamá"),
  CountryLocalization("pg", "inglese", "Papua Nuova Guinea"),
  CountryLocalization("py", "spagnolo", "Paraguay"),
  CountryLocalization("pe", "spagnolo", "Perù"),
  CountryLocalization("ph", "filippino", "Filippine"),
  CountryLocalization("pn", "inglese", "Isole Pitcairn"),
  CountryLocalization("pl", "polacco", "Polonia"),
  CountryLocalization("pt", "portoghese", "Portogallo"),
  CountryLocalization("pr", "inglese", "Portorico"),
  CountryLocalization("qa", "arabo", "Qatar"),
  CountryLocalization("ro", "rumeno", "Romania"),
  CountryLocalization("ru", "tataro", "Russia"),
  CountryLocalization("rw", "inglese", "Ruanda"),
  CountryLocalization("re", "francese", "Riunione"),
  CountryLocalization("ws", "inglese", "Samoa"),
  CountryLocalization("sm", "italiano", "San Marino"),
  CountryLocalization("sa", "arabo", "Arabia Saudita"),
  CountryLocalization("sn", "francese", "Senegal"),
  CountryLocalization("rs", "serbo", "Serbia"),
  CountryLocalization("cs", "serbo", "Serbia e Montenegro"),
  CountryLocalization("sc", "francese", "Seychelles"),
  CountryLocalization("sl", "inglese", "Sierra Leone"),
  CountryLocalization("sg", "tamil", "Singapore"),
  CountryLocalization("sx", "inglese", "Sint Maarten"),
  CountryLocalization("sk", "slovacco", "Slovacchia"),
  CountryLocalization("si", "sloveno", "Slovenia"),
  CountryLocalization("sb", "inglese", "Isole Salomone"),
  CountryLocalization("so", "arabo", "Somalia"),
  CountryLocalization("za", "inglese", "Sudafrica"),
  CountryLocalization("kr", "coreano", "Corea del Sud"),
  CountryLocalization("ss", "nuer", "Sud Sudan"),
  CountryLocalization("es", "spagnolo", "Spagna"),
  CountryLocalization("lk", "tamil", "Sri Lanka"),
  CountryLocalization("bl", "francese", "Saint-Barthélemy"),
  CountryLocalization("sh", "inglese", "Sant’Elena"),
  CountryLocalization("kn", "inglese", "Saint Kitts e Nevis"),
  CountryLocalization("lc", "inglese", "Saint Lucia"),
  CountryLocalization("mf", "francese", "Saint Martin"),
  CountryLocalization("pm", "francese", "Saint-Pierre e Miquelon"),
  CountryLocalization("vc", "inglese", "Saint Vincent e Grenadine"),
  CountryLocalization("sd", "arabo", "Sudan"),
  CountryLocalization("sr", "olandese", "Suriname"),
  CountryLocalization("sj", "norvegese bokmål", "Svalbard e Jan Mayen"),
  CountryLocalization("sz", "inglese", "Swaziland"),
  CountryLocalization("se", "svedese", "Svezia"),
  CountryLocalization("ch", "tedesco svizzero", "Svizzera"),
  CountryLocalization("sy", "arabo", "Siria"),
  CountryLocalization("st", "portoghese", "São Tomé e Príncipe"),
  CountryLocalization("tw", "cinese", "Taiwan"),
  CountryLocalization("tj", "tagico", "Tagikistan"),
  CountryLocalization("tz", "makonde", "Tanzania"),
  CountryLocalization("th", "thai", "Thailandia"),
  CountryLocalization("tl", "portoghese", "Timor Est"),
  CountryLocalization("tg", "francese", "Togo"),
  CountryLocalization("tk", "inglese", "Tokelau"),
  CountryLocalization("to", "tongano", "Tonga"),
  CountryLocalization("tt", "inglese", "Trinidad e Tobago"),
  CountryLocalization("tn", "francese", "Tunisia"),
  CountryLocalization("tr", "turco", "Turchia"),
  CountryLocalization("tm", "turcomanno", "Turkmenistan"),
  CountryLocalization("tc", "inglese", "Isole Turks e Caicos"),
  CountryLocalization("tv", "inglese", "Tuvalu"),
  CountryLocalization("um", "inglese", "Altre isole americane del Pacifico"),
  CountryLocalization("vi", "inglese", "Isole Vergini Americane"),
  CountryLocalization("ug", "swahili", "Uganda"),
  CountryLocalization("ua", "ucraino", "Ucraina"),
  CountryLocalization("ae", "arabo", "Emirati Arabi Uniti"),
  CountryLocalization("gb", "inglese", "Regno Unito"),
  CountryLocalization("us", "lakota", "Stati Uniti"),
  CountryLocalization("uy", "spagnolo", "Uruguay"),
  CountryLocalization("uz", "uzbeco", "Uzbekistan"),
  CountryLocalization("vu", "francese", "Vanuatu"),
  CountryLocalization("va", "italiano", "Città del Vaticano"),
  CountryLocalization("ve", "spagnolo", "Venezuela"),
  CountryLocalization("vn", "vietnamita", "Vietnam"),
  CountryLocalization("wf", "francese", "Wallis e Futuna"),
  CountryLocalization("eh", "arabo", "Sahara occidentale"),
  CountryLocalization("ye", "arabo", "Yemen"),
  CountryLocalization("zm", "inglese", "Zambia"),
  CountryLocalization("zw", "ndebele del nord", "Zimbabwe"),
  CountryLocalization("ax", "svedese", "Isole Åland"),
)
