/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot.atlas.extended

import dev.teogor.xenoglot.atlas.CountryLocalization
import kotlin.collections.List

/**
 * Holds the internal list of country-language mappings used for lookups within the package for
 * language code kde.
 *
 * This property contains a hardcoded list of [CountryLocalization] objects, each representing
 * a country and its associated official languages. This list is used by [CountryLanguageRegistry]
 * to provide access to country-language data and should not be modified directly.
 *
 * @see CountryLocalization
 * @see CountryLanguageRegistry
 */
internal val _countryLanguageMappings_kde: List<CountryLocalization> = listOf(
  CountryLocalization("af", "Chiajemi", "Afuganistani"),
  CountryLocalization("al", "Albanian", "Albania"),
  CountryLocalization("dz", "Chifalansa", "Aljelia"),
  CountryLocalization("as", "Chiingeleza", "Samoa ya Malekani"),
  CountryLocalization("ad", "Catalan", "Andola"),
  CountryLocalization("ao", "Lingala", "Angola"),
  CountryLocalization("ai", "Chiingeleza", "Angwila"),
  CountryLocalization("ag", "Chiingeleza", "Antigua na Balbuda"),
  CountryLocalization("ar", "Chihispania", "Adyentina"),
  CountryLocalization("am", "Armenian", "Almenia"),
  CountryLocalization("aw", "Chiholanzi", "Aluba"),
  CountryLocalization("au", "Chiingeleza", "Austlalia"),
  CountryLocalization("at", "Chiingeleza", "Austlia"),
  CountryLocalization("az", "Azerbaijani", "Azabadyani"),
  CountryLocalization("bs", "Chiingeleza", "Bahama"),
  CountryLocalization("bh", "Chalabu", "Bahaleni"),
  CountryLocalization("bd", "Chibangla", "Bangladeshi"),
  CountryLocalization("bb", "Chiingeleza", "Babadosi"),
  CountryLocalization("by", "Chibelalusi", "Belalusi"),
  CountryLocalization("be", "Chifalansa", "Ubelgidi"),
  CountryLocalization("bz", "Chiingeleza", "Belize"),
  CountryLocalization("bj", "Chifalansa", "Benini"),
  CountryLocalization("bm", "Chiingeleza", "Belmuda"),
  CountryLocalization("bt", "Dzongkha", "Butani"),
  CountryLocalization("bo", "Chihispania", "Bolivia"),
  CountryLocalization("ba", "Bosnian", "Bosnia na Hezegovina"),
  CountryLocalization("bw", "Chiingeleza", "Botswana"),
  CountryLocalization("br", "Chileno", "Blazili"),
  CountryLocalization("io", "Chiingeleza", "Lieneo lyaki Nngalesa Nbahali ya Hindi"),
  CountryLocalization("vg", "Chiingeleza", "Chisiwa Chivihi cha Wingalesa"),
  CountryLocalization("bn", "Chimalesia", "Blunei"),
  CountryLocalization("bg", "Chibulgalia", "Bulgalia"),
  CountryLocalization("bf", "Chifalansa", "Buchinafaso"),
  CountryLocalization("bi", "Chifalansa", "Bulundi"),
  CountryLocalization("kh", "Chikambodia", "Kambodia"),
  CountryLocalization("cm", "Basaa", "Kameluni"),
  CountryLocalization("ca", "Chifalansa", "Kanada"),
  CountryLocalization("ic", "Chihispania", "IC"),
  CountryLocalization("cv", "kea", "Kepuvede"),
  CountryLocalization("bq", "Chiholanzi", "Caribbean Netherlands"),
  CountryLocalization("ky", "Chiingeleza", "Chisiwa cha Kemen"),
  CountryLocalization("cf", "Lingala", "Jamuhuli ya Afilika ya Paching’ati"),
  CountryLocalization("ea", "Chihispania", "EA"),
  CountryLocalization("td", "Chalabu", "Chadi"),
  CountryLocalization("cl", "Chihispania", "Chile"),
  CountryLocalization("cn", "Tibetan", "China"),
  CountryLocalization("cx", "Chiingeleza", "Christmas Island"),
  CountryLocalization("cc", "Chiingeleza", "Cocos (Keeling) Islands"),
  CountryLocalization("co", "Chihispania", "Kolombia"),
  CountryLocalization("km", "Chalabu", "Komolo"),
  CountryLocalization("cg", "Lingala", "Kongo"),
  CountryLocalization("cd", "Swahili", "Jamuhuli ya Chidemoklasia ya kuKongo"),
  CountryLocalization("ck", "Chiingeleza", "Chisiwa cha Cook"),
  CountryLocalization("cr", "Chihispania", "Kostalika"),
  CountryLocalization("hr", "Croatian", "Kolasia"),
  CountryLocalization("cu", "Chihispania", "Kuba"),
  CountryLocalization("cw", "Chiholanzi", "Curaçao"),
  CountryLocalization("cy", "Chiingeleza", "Kuplosi"),
  CountryLocalization("cz", "Chichechi", "Jamuhuli ya Chechi"),
  CountryLocalization("ci", "Chifalansa", "Kodivaa"),
  CountryLocalization("dk", "Chiingeleza", "Denmaki"),
  CountryLocalization("dg", "Chiingeleza", "DG"),
  CountryLocalization("dj", "Chifalansa", "Dyibuti"),
  CountryLocalization("dm", "Chiingeleza", "Dominika"),
  CountryLocalization("do", "Chihispania", "Jamuhuli ya Dominika"),
  CountryLocalization("ec", "Quechua", "Ekwado"),
  CountryLocalization("eg", "Chalabu", "Misli"),
  CountryLocalization("sv", "Chihispania", "Elsavado"),
  CountryLocalization("gq", "Chihispania", "Ginekweta"),
  CountryLocalization("er", "Tigrinya", "Elitilea"),
  CountryLocalization("ee", "Estonian", "Estonia"),
  CountryLocalization("et", "Chamhali", "Uhabeshi"),
  CountryLocalization("fk", "Chiingeleza", "Chisiwa cha Falkland"),
  CountryLocalization("fo", "Faroese", "Faroe Islands"),
  CountryLocalization("fj", "Chiingeleza", "Fiji"),
  CountryLocalization("fi", "Chiswidi", "Ufini"),
  CountryLocalization("fr", "Swiss German", "Ufalansa"),
  CountryLocalization("gf", "Chifalansa", "Gwiyana ya Ufalansa"),
  CountryLocalization("pf", "Chifalansa", "Polinesia ya Ufalansa"),
  CountryLocalization("ga", "Chifalansa", "Gaboni"),
  CountryLocalization("gm", "Chiingeleza", "Gambia"),
  CountryLocalization("ge", "Ossetic", "Dyodya"),
  CountryLocalization("de", "Lower Sorbian", "Udyerumani"),
  CountryLocalization("gh", "Chiingeleza", "Ghana"),
  CountryLocalization("gi", "Chiingeleza", "Diblalta"),
  CountryLocalization("gr", "Chigilichi", "Ugilichi"),
  CountryLocalization("gl", "Kalaallisut", "Glinlandi"),
  CountryLocalization("gd", "Chiingeleza", "Glenada"),
  CountryLocalization("gp", "Chifalansa", "Gwadelupe"),
  CountryLocalization("gu", "Chiingeleza", "Gwam"),
  CountryLocalization("gt", "Chihispania", "Gwatemala"),
  CountryLocalization("gg", "Chiingeleza", "Guernsey"),
  CountryLocalization("gn", "Chifalansa", "Gine"),
  CountryLocalization("gw", "Chileno", "Ginebisau"),
  CountryLocalization("gy", "Chiingeleza", "Guyana"),
  CountryLocalization("ht", "Chifalansa", "Haiti"),
  CountryLocalization("hn", "Chihispania", "Hondulasi"),
  CountryLocalization("hk", "Chichina", "Hong Kong SAR China"),
  CountryLocalization("hu", "Chihungali", "Hungalia"),
  CountryLocalization("is", "Icelandic", "Aislandi"),
  CountryLocalization("in", "Chinepali", "India"),
  CountryLocalization("id", "Indonesian", "Indonesia"),
  CountryLocalization("ir", "Chiajemi", "Uadyemi"),
  CountryLocalization("iq", "lrc", "Ilaki"),
  CountryLocalization("ie", "Chiingeleza", "Ayalandi"),
  CountryLocalization("im", "Manx", "Isle of Man"),
  CountryLocalization("il", "Chiingeleza", "Islaeli"),
  CountryLocalization("it", "Chidyelumani", "Italia"),
  CountryLocalization("jm", "Chiingeleza", "Dyamaika"),
  CountryLocalization("jp", "Chidyapani", "Dyapani"),
  CountryLocalization("je", "Chiingeleza", "Jersey"),
  CountryLocalization("jo", "Chalabu", "Yordani"),
  CountryLocalization("kz", "Kazakh", "Kazachistani"),
  CountryLocalization("ke", "Chisomali", "Kenya"),
  CountryLocalization("ki", "Chiingeleza", "Kilibati"),
  CountryLocalization("xk", "Serbian", "XK"),
  CountryLocalization("kw", "Chalabu", "Kuwaiti"),
  CountryLocalization("kg", "Chilusi", "Kiligizistani"),
  CountryLocalization("la", "Lao", "Laosi"),
  CountryLocalization("lv", "Latvian", "Lativia"),
  CountryLocalization("lb", "Chalabu", "Lebanoni"),
  CountryLocalization("ls", "Chiingeleza", "Lesoto"),
  CountryLocalization("lr", "Chiingeleza", "Libelia"),
  CountryLocalization("ly", "Chalabu", "Libya"),
  CountryLocalization("li", "Swiss German", "Lishenteni"),
  CountryLocalization("lt", "Lithuanian", "Litwania"),
  CountryLocalization("lu", "Luxembourgish", "Lasembagi"),
  CountryLocalization("mo", "Chileno", "Macao SAR China"),
  CountryLocalization("mk", "Albanian", "Masedonia"),
  CountryLocalization("mg", "Chifalansa", "Bukini"),
  CountryLocalization("mw", "Chiingeleza", "Malawi"),
  CountryLocalization("my", "Chitamil", "Malesia"),
  CountryLocalization("ml", "Chifalansa", "Mali"),
  CountryLocalization("mt", "Chiingeleza", "Malta"),
  CountryLocalization("mh", "Chiingeleza", "Chisiwa cha Malushal"),
  CountryLocalization("mq", "Chifalansa", "Malitiniki"),
  CountryLocalization("mr", "Chalabu", "Molitania"),
  CountryLocalization("mu", "mfe", "Molisi"),
  CountryLocalization("yt", "Chifalansa", "Maole"),
  CountryLocalization("mx", "Chihispania", "Meksiko"),
  CountryLocalization("fm", "Chiingeleza", "Mikilonesia"),
  CountryLocalization("md", "Chilusi", "Moldova"),
  CountryLocalization("mc", "Chifalansa", "Monako"),
  CountryLocalization("mn", "Mongolian", "Mongolia"),
  CountryLocalization("me", "Serbian", "Montenegro"),
  CountryLocalization("ms", "Chiingeleza", "Monselati"),
  CountryLocalization("ma", "tzm", "Moloko"),
  CountryLocalization("mz", "mgh", "Msumbiji"),
  CountryLocalization("mm", "Chibulma", "Myama"),
  CountryLocalization("na", "Chiingeleza", "Namibia"),
  CountryLocalization("nr", "Chiingeleza", "Naulu"),
  CountryLocalization("np", "Chinepali", "Nepali"),
  CountryLocalization("nl", "Chiingeleza", "Uholanzi"),
  CountryLocalization("nc", "Chifalansa", "Nyukaledonia"),
  CountryLocalization("nz", "Chiingeleza", "Nyuzilandi"),
  CountryLocalization("ni", "Chihispania", "Nikalagwa"),
  CountryLocalization("ne", "Chihausa", "Nidyeli"),
  CountryLocalization("ng", "Chihausa", "Nidyelia"),
  CountryLocalization("nu", "Chiingeleza", "Niue"),
  CountryLocalization("nf", "Chiingeleza", "Chisiwa cha Nolufok"),
  CountryLocalization("kp", "Chikolea", "Kolea Kasikazini"),
  CountryLocalization("mp", "Chiingeleza", "Chisiwa cha Marian cha Kasikazini"),
  CountryLocalization("no", "Northern Sami", "Norwe"),
  CountryLocalization("om", "Chalabu", "Omani"),
  CountryLocalization("pk", "Chiingeleza", "Pakistani"),
  CountryLocalization("pw", "Chiingeleza", "Palau"),
  CountryLocalization("ps", "Chalabu", "Nchingu wa Magalibi wa Mpanda wa kuGaza wa kuPales"),
  CountryLocalization("pa", "Chihispania", "Panama"),
  CountryLocalization("pg", "Chiingeleza", "Papua"),
  CountryLocalization("py", "Chihispania", "Palagwai"),
  CountryLocalization("pe", "Chihispania", "Pelu"),
  CountryLocalization("ph", "Filipino", "Filipino"),
  CountryLocalization("pn", "Chiingeleza", "Pitikeluni"),
  CountryLocalization("pl", "Chipolandi", "Polandi"),
  CountryLocalization("pt", "Chileno", "Uleno"),
  CountryLocalization("pr", "Chiingeleza", "Pwetoliko"),
  CountryLocalization("qa", "Chalabu", "Katali"),
  CountryLocalization("ro", "Chilomania", "Lomania"),
  CountryLocalization("ru", "Tatar", "Ulusi"),
  CountryLocalization("rw", "Chiingeleza", "Lwanda"),
  CountryLocalization("re", "Chifalansa", "Liyunioni"),
  CountryLocalization("ws", "Chiingeleza", "Samoa"),
  CountryLocalization("sm", "Chiitaliano", "Samalino"),
  CountryLocalization("sa", "Chalabu", "Saudia"),
  CountryLocalization("sn", "Chifalansa", "Senegali"),
  CountryLocalization("rs", "Serbian", "Serbia"),
  CountryLocalization("cs", "Serbian", "Serbia and Montenegro"),
  CountryLocalization("sc", "Chifalansa", "Shelisheli"),
  CountryLocalization("sl", "Chiingeleza", "Siela Leoni"),
  CountryLocalization("sg", "Chitamil", "Singapoo"),
  CountryLocalization("sx", "Chiingeleza", "Sint Maarten"),
  CountryLocalization("sk", "Slovak", "Slovakia"),
  CountryLocalization("si", "Slovenian", "Slovenia"),
  CountryLocalization("sb", "Chiingeleza", "Chisiwa cha Solomon"),
  CountryLocalization("so", "Chalabu", "Somalia"),
  CountryLocalization("za", "Chiingeleza", "Afilika Kusini"),
  CountryLocalization("kr", "Chikolea", "Kolea Kusini"),
  CountryLocalization("ss", "nus", "South Sudan"),
  CountryLocalization("es", "Chihispania", "Hispania"),
  CountryLocalization("lk", "Chitamil", "Sililanka"),
  CountryLocalization("bl", "Chifalansa", "St. Barthélemy"),
  CountryLocalization("sh", "Chiingeleza", "Santahelena"),
  CountryLocalization("kn", "Chiingeleza", "Santakitzi na Nevis"),
  CountryLocalization("lc", "Chiingeleza", "Santalusia"),
  CountryLocalization("mf", "Chifalansa", "St. Martin"),
  CountryLocalization("pm", "Chifalansa", "Santapieli na Mikeloni"),
  CountryLocalization("vc", "Chiingeleza", "Santavisenti na Glenadini"),
  CountryLocalization("sd", "Chalabu", "Sudani"),
  CountryLocalization("sr", "Chiholanzi", "Sulinamu"),
  CountryLocalization("sj", "Norwegian Bokmål", "Svalbard & Jan Mayen"),
  CountryLocalization("sz", "Chiingeleza", "Uswazi"),
  CountryLocalization("se", "Chiswidi", "Uswidi"),
  CountryLocalization("ch", "Swiss German", "Uswisi"),
  CountryLocalization("sy", "Chalabu", "Silia"),
  CountryLocalization("st", "Chileno", "Saotome na Prinsipe"),
  CountryLocalization("tw", "Chichina", "Taiwani"),
  CountryLocalization("tj", "Tajik", "Tadikistani"),
  CountryLocalization("tz", "Chimakonde", "Tanzania"),
  CountryLocalization("th", "Chitailandi", "Tailandi"),
  CountryLocalization("tl", "Chileno", "Timoli ya Mashaliki"),
  CountryLocalization("tg", "Chifalansa", "Togo"),
  CountryLocalization("tk", "Chiingeleza", "Tokelau"),
  CountryLocalization("to", "Tongan", "Tonga"),
  CountryLocalization("tt", "Chiingeleza", "Tilinidad na Tobago"),
  CountryLocalization("tn", "Chifalansa", "Tunisia"),
  CountryLocalization("tr", "Chituluchi", "Utuluchi"),
  CountryLocalization("tm", "Turkmen", "Tuluchimenistani"),
  CountryLocalization("tc", "Chiingeleza", "Chisiwa cha Tuluchi na Kaiko"),
  CountryLocalization("tv", "Chiingeleza", "Tuvalu"),
  CountryLocalization("um", "Chiingeleza", "U.S. Outlying Islands"),
  CountryLocalization("vi", "Chiingeleza", "Chisiwa Chivihi cha Malekani"),
  CountryLocalization("ug", "Swahili", "Uganda"),
  CountryLocalization("ua", "Chiuklania", "Uklaini"),
  CountryLocalization("ae", "Chalabu", "Dimiliki dya Vakulungwa va Chalabu"),
  CountryLocalization("gb", "Chiingeleza", "Nngalesa"),
  CountryLocalization("us", "lkt", "Malekani"),
  CountryLocalization("uy", "Chihispania", "Ulugwai"),
  CountryLocalization("uz", "Uzbek", "Uzibechistani"),
  CountryLocalization("vu", "Chifalansa", "Vanuatu"),
  CountryLocalization("va", "Chiitaliano", "Vatikani"),
  CountryLocalization("ve", "Chihispania", "Venezuela"),
  CountryLocalization("vn", "Chivietinamu", "Vietinamu"),
  CountryLocalization("wf", "Chifalansa", "Walis na Futuna"),
  CountryLocalization("eh", "Chalabu", "Western Sahara"),
  CountryLocalization("ye", "Chalabu", "Yemeni"),
  CountryLocalization("zm", "Chiingeleza", "Zambia"),
  CountryLocalization("zw", "North Ndebele", "Zimbabwe"),
  CountryLocalization("ax", "Chiswidi", "Åland Islands"),
)
