/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot.atlas.extended

import dev.teogor.xenoglot.atlas.CountryLocalization
import kotlin.collections.List

/**
 * Holds the internal list of country-language mappings used for lookups within the package for
 * language code kk.
 *
 * This property contains a hardcoded list of [CountryLocalization] objects, each representing
 * a country and its associated official languages. This list is used by [CountryLanguageRegistry]
 * to provide access to country-language data and should not be modified directly.
 *
 * @see CountryLocalization
 * @see CountryLanguageRegistry
 */
internal val _countryLanguageMappings_kk: List<CountryLocalization> = listOf(
  CountryLocalization("af", "парсы тілі", "Ауғанстан"),
  CountryLocalization("al", "албан тілі", "Албания"),
  CountryLocalization("dz", "француз тілі", "Алжир"),
  CountryLocalization("as", "ағылшын тілі", "Америкалық Самоа"),
  CountryLocalization("ad", "каталан тілі", "Андорра"),
  CountryLocalization("ao", "лингала тілі", "Ангола"),
  CountryLocalization("ai", "ағылшын тілі", "Ангилья"),
  CountryLocalization("ag", "ағылшын тілі", "Антигуа және Барбуда"),
  CountryLocalization("ar", "испан тілі", "Аргентина"),
  CountryLocalization("am", "армян тілі", "Армения"),
  CountryLocalization("aw", "нидерланд тілі", "Аруба"),
  CountryLocalization("au", "ағылшын тілі", "Австралия"),
  CountryLocalization("at", "ағылшын тілі", "Австрия"),
  CountryLocalization("az", "әзірбайжан тілі", "Әзірбайжан"),
  CountryLocalization("bs", "ағылшын тілі", "Багам аралдары"),
  CountryLocalization("bh", "араб тілі", "Бахрейн"),
  CountryLocalization("bd", "бенгал тілі", "Бангладеш"),
  CountryLocalization("bb", "ағылшын тілі", "Барбадос"),
  CountryLocalization("by", "беларусь тілі", "Беларусь"),
  CountryLocalization("be", "француз тілі", "Бельгия"),
  CountryLocalization("bz", "ағылшын тілі", "Белиз"),
  CountryLocalization("bj", "француз тілі", "Бенин"),
  CountryLocalization("bm", "ағылшын тілі", "Бермуд аралдары"),
  CountryLocalization("bt", "дзонг-кэ тілі", "Бутан"),
  CountryLocalization("bo", "испан тілі", "Боливия"),
  CountryLocalization("ba", "босния тілі", "Босния және Герцеговина"),
  CountryLocalization("bw", "ағылшын тілі", "Ботсвана"),
  CountryLocalization("br", "португал тілі", "Бразилия"),
  CountryLocalization("io", "ағылшын тілі", "Үнді мұхитындағы Британ аймағы"),
  CountryLocalization("vg", "ағылшын тілі", "Британдық Виргин аралдары"),
  CountryLocalization("bn", "малай тілі", "Бруней"),
  CountryLocalization("bg", "болгар тілі", "Болгария"),
  CountryLocalization("bf", "француз тілі", "Буркина-Фасо"),
  CountryLocalization("bi", "француз тілі", "Бурунди"),
  CountryLocalization("kh", "кхмер тілі", "Камбоджа"),
  CountryLocalization("cm", "баса тілі", "Камерун"),
  CountryLocalization("ca", "француз тілі", "Канада"),
  CountryLocalization("ic", "испан тілі", "Канар аралдары"),
  CountryLocalization("cv", "кабувердьяну тілі", "Кабо-Верде"),
  CountryLocalization("bq", "нидерланд тілі", "Бонэйр, Синт-Эстатиус және Саба"),
  CountryLocalization("ky", "ағылшын тілі", "Кайман аралдары"),
  CountryLocalization("cf", "лингала тілі", "Орталық Африка Республикасы"),
  CountryLocalization("ea", "испан тілі", "Сеута және Мелилья"),
  CountryLocalization("td", "араб тілі", "Чад"),
  CountryLocalization("cl", "испан тілі", "Чили"),
  CountryLocalization("cn", "тибет тілі", "Қытай"),
  CountryLocalization("cx", "ағылшын тілі", "Рождество аралы"),
  CountryLocalization("cc", "ағылшын тілі", "Кокос (Килинг) аралдары"),
  CountryLocalization("co", "испан тілі", "Колумбия"),
  CountryLocalization("km", "араб тілі", "Комор аралдары"),
  CountryLocalization("cg", "лингала тілі", "Конго-Браззавиль Республикасы"),
  CountryLocalization("cd", "суахили тілі", "Конго"),
  CountryLocalization("ck", "ағылшын тілі", "Кук аралдары"),
  CountryLocalization("cr", "испан тілі", "Коста-Рика"),
  CountryLocalization("hr", "хорват тілі", "Хорватия"),
  CountryLocalization("cu", "испан тілі", "Куба"),
  CountryLocalization("cw", "нидерланд тілі", "Кюрасао"),
  CountryLocalization("cy", "ағылшын тілі", "Кипр"),
  CountryLocalization("cz", "чех тілі", "Чехия"),
  CountryLocalization("ci", "француз тілі", "Кот-д’Ивуар"),
  CountryLocalization("dk", "ағылшын тілі", "Дания"),
  CountryLocalization("dg", "ағылшын тілі", "Диего-Гарсия"),
  CountryLocalization("dj", "француз тілі", "Джибути"),
  CountryLocalization("dm", "ағылшын тілі", "Доминика"),
  CountryLocalization("do", "испан тілі", "Доминикан Республикасы"),
  CountryLocalization("ec", "кечуа тілі", "Эквадор"),
  CountryLocalization("eg", "араб тілі", "Мысыр"),
  CountryLocalization("sv", "испан тілі", "Сальвадор"),
  CountryLocalization("gq", "испан тілі", "Экваторлық Гвинея"),
  CountryLocalization("er", "тигринья тілі", "Эритрея"),
  CountryLocalization("ee", "эстон тілі", "Эстония"),
  CountryLocalization("et", "амхар тілі", "Эфиопия"),
  CountryLocalization("fk", "ағылшын тілі", "Фолкленд аралдары"),
  CountryLocalization("fo", "фарер тілі", "Фарер аралдары"),
  CountryLocalization("fj", "ағылшын тілі", "Фиджи"),
  CountryLocalization("fi", "швед тілі", "Финляндия"),
  CountryLocalization("fr", "швейцариялық неміс тілі", "Франция"),
  CountryLocalization("gf", "француз тілі", "Француз Гвианасы"),
  CountryLocalization("pf", "француз тілі", "Француз Полинезиясы"),
  CountryLocalization("ga", "француз тілі", "Габон"),
  CountryLocalization("gm", "ағылшын тілі", "Гамбия"),
  CountryLocalization("ge", "осетин тілі", "Грузия"),
  CountryLocalization("de", "төменгі лужица тілі", "Германия"),
  CountryLocalization("gh", "ағылшын тілі", "Гана"),
  CountryLocalization("gi", "ағылшын тілі", "Гибралтар"),
  CountryLocalization("gr", "грек тілі", "Грекия"),
  CountryLocalization("gl", "калаалисут тілі", "Гренландия"),
  CountryLocalization("gd", "ағылшын тілі", "Гренада"),
  CountryLocalization("gp", "француз тілі", "Гваделупа"),
  CountryLocalization("gu", "ағылшын тілі", "Гуам"),
  CountryLocalization("gt", "испан тілі", "Гватемала"),
  CountryLocalization("gg", "ағылшын тілі", "Гернси"),
  CountryLocalization("gn", "француз тілі", "Гвинея"),
  CountryLocalization("gw", "португал тілі", "Гвинея-Бисау"),
  CountryLocalization("gy", "ағылшын тілі", "Гайана"),
  CountryLocalization("ht", "француз тілі", "Гаити"),
  CountryLocalization("hn", "испан тілі", "Гондурас"),
  CountryLocalization("hk", "қытай тілі", "Сянган АӘА"),
  CountryLocalization("hu", "венгр тілі", "Венгрия"),
  CountryLocalization("is", "исланд тілі", "Исландия"),
  CountryLocalization("in", "непал тілі", "Үндістан"),
  CountryLocalization("id", "Indonesian", "Индонезия"),
  CountryLocalization("ir", "парсы тілі", "Иран"),
  CountryLocalization("iq", "солтүстік люри тілі", "Ирак"),
  CountryLocalization("ie", "ағылшын тілі", "Ирландия"),
  CountryLocalization("im", "мэн тілі", "Мэн аралы"),
  CountryLocalization("il", "ағылшын тілі", "Израиль"),
  CountryLocalization("it", "неміс тілі", "Италия"),
  CountryLocalization("jm", "ағылшын тілі", "Ямайка"),
  CountryLocalization("jp", "жапон тілі", "Жапония"),
  CountryLocalization("je", "ағылшын тілі", "Джерси"),
  CountryLocalization("jo", "араб тілі", "Иордания"),
  CountryLocalization("kz", "қазақ тілі", "Қазақстан"),
  CountryLocalization("ke", "сомали тілі", "Кения"),
  CountryLocalization("ki", "ағылшын тілі", "Кирибати"),
  CountryLocalization("xk", "серб тілі", "Косово"),
  CountryLocalization("kw", "араб тілі", "Кувейт"),
  CountryLocalization("kg", "орыс тілі", "Қырғызстан"),
  CountryLocalization("la", "лаос тілі", "Лаос"),
  CountryLocalization("lv", "латыш тілі", "Латвия"),
  CountryLocalization("lb", "араб тілі", "Ливан"),
  CountryLocalization("ls", "ағылшын тілі", "Лесото"),
  CountryLocalization("lr", "ағылшын тілі", "Либерия"),
  CountryLocalization("ly", "араб тілі", "Ливия"),
  CountryLocalization("li", "швейцариялық неміс тілі", "Лихтенштейн"),
  CountryLocalization("lt", "литва тілі", "Литва"),
  CountryLocalization("lu", "люксембург тілі", "Люксембург"),
  CountryLocalization("mo", "португал тілі", "Макао АӘА"),
  CountryLocalization("mk", "албан тілі", "Македония"),
  CountryLocalization("mg", "француз тілі", "Мадагаскар"),
  CountryLocalization("mw", "ағылшын тілі", "Малави"),
  CountryLocalization("my", "тамил тілі", "Малайзия"),
  CountryLocalization("ml", "француз тілі", "Мали"),
  CountryLocalization("mt", "ағылшын тілі", "Мальта"),
  CountryLocalization("mh", "ағылшын тілі", "Маршалл аралдары"),
  CountryLocalization("mq", "француз тілі", "Мартиника"),
  CountryLocalization("mr", "араб тілі", "Мавритания"),
  CountryLocalization("mu", "морисиен тілі", "Маврикий"),
  CountryLocalization("yt", "француз тілі", "Майотта"),
  CountryLocalization("mx", "испан тілі", "Мексика"),
  CountryLocalization("fm", "ағылшын тілі", "Микронезия"),
  CountryLocalization("md", "орыс тілі", "Молдова"),
  CountryLocalization("mc", "француз тілі", "Монако"),
  CountryLocalization("mn", "моңғол тілі", "Моңғолия"),
  CountryLocalization("me", "серб тілі", "Черногория"),
  CountryLocalization("ms", "ағылшын тілі", "Монтсеррат"),
  CountryLocalization("ma", "орталық атлас тамазигхт тілі", "Марокко"),
  CountryLocalization("mz", "макуа-меетто тілі", "Мозамбик"),
  CountryLocalization("mm", "бирма тілі", "Мьянма (Бирма)"),
  CountryLocalization("na", "ағылшын тілі", "Намибия"),
  CountryLocalization("nr", "ағылшын тілі", "Науру"),
  CountryLocalization("np", "непал тілі", "Непал"),
  CountryLocalization("nl", "ағылшын тілі", "Нидерланд"),
  CountryLocalization("nc", "француз тілі", "Жаңа Каледония"),
  CountryLocalization("nz", "ағылшын тілі", "Жаңа Зеландия"),
  CountryLocalization("ni", "испан тілі", "Никарагуа"),
  CountryLocalization("ne", "хауса тілі", "Нигер"),
  CountryLocalization("ng", "хауса тілі", "Нигерия"),
  CountryLocalization("nu", "ағылшын тілі", "Ниуэ"),
  CountryLocalization("nf", "ағылшын тілі", "Норфолк аралы"),
  CountryLocalization("kp", "корей тілі", "Солтүстік Корея"),
  CountryLocalization("mp", "ағылшын тілі", "Солтүстік Мариана аралдары"),
  CountryLocalization("no", "солтүстік саам тілі", "Норвегия"),
  CountryLocalization("om", "араб тілі", "Оман"),
  CountryLocalization("pk", "ағылшын тілі", "Пәкістан"),
  CountryLocalization("pw", "ағылшын тілі", "Палау"),
  CountryLocalization("ps", "араб тілі", "Палестина аймақтары"),
  CountryLocalization("pa", "испан тілі", "Панама"),
  CountryLocalization("pg", "ағылшын тілі", "Папуа — Жаңа Гвинея"),
  CountryLocalization("py", "испан тілі", "Парагвай"),
  CountryLocalization("pe", "испан тілі", "Перу"),
  CountryLocalization("ph", "филиппин тілі", "Филиппин аралдары"),
  CountryLocalization("pn", "ағылшын тілі", "Питкэрн аралдары"),
  CountryLocalization("pl", "поляк тілі", "Польша"),
  CountryLocalization("pt", "португал тілі", "Португалия"),
  CountryLocalization("pr", "ағылшын тілі", "Пуэрто-Рико"),
  CountryLocalization("qa", "араб тілі", "Катар"),
  CountryLocalization("ro", "румын тілі", "Румыния"),
  CountryLocalization("ru", "татар тілі", "Ресей"),
  CountryLocalization("rw", "ағылшын тілі", "Руанда"),
  CountryLocalization("re", "француз тілі", "Реюньон"),
  CountryLocalization("ws", "ағылшын тілі", "Самоа"),
  CountryLocalization("sm", "итальян тілі", "Сан-Марино"),
  CountryLocalization("sa", "араб тілі", "Сауд Арабиясы"),
  CountryLocalization("sn", "француз тілі", "Сенегал"),
  CountryLocalization("rs", "серб тілі", "Сербия"),
  CountryLocalization("cs", "серб тілі", "Serbia and Montenegro"),
  CountryLocalization("sc", "француз тілі", "Сейшель аралдары"),
  CountryLocalization("sl", "ағылшын тілі", "Сьерра-Леоне"),
  CountryLocalization("sg", "тамил тілі", "Сингапур"),
  CountryLocalization("sx", "ағылшын тілі", "Синт-Мартен"),
  CountryLocalization("sk", "словак тілі", "Словакия"),
  CountryLocalization("si", "словен тілі", "Словения"),
  CountryLocalization("sb", "ағылшын тілі", "Соломон аралдары"),
  CountryLocalization("so", "араб тілі", "Сомали"),
  CountryLocalization("za", "ағылшын тілі", "Оңтүстік Африка Республикасы"),
  CountryLocalization("kr", "корей тілі", "Оңтүстік Корея"),
  CountryLocalization("ss", "нуэр тілі", "Оңтүстік Судан"),
  CountryLocalization("es", "испан тілі", "Испания"),
  CountryLocalization("lk", "тамил тілі", "Шри-Ланка"),
  CountryLocalization("bl", "француз тілі", "Сен-Бартелеми"),
  CountryLocalization("sh", "ағылшын тілі", "Әулие Елена аралы"),
  CountryLocalization("kn", "ағылшын тілі", "Сент-Китс және Невис"),
  CountryLocalization("lc", "ағылшын тілі", "Сент-Люсия"),
  CountryLocalization("mf", "француз тілі", "Сен-Мартен"),
  CountryLocalization("pm", "француз тілі", "Сен-Пьер және Микелон"),
  CountryLocalization("vc", "ағылшын тілі", "Сент-Винсент және Гренадин аралдары"),
  CountryLocalization("sd", "араб тілі", "Судан"),
  CountryLocalization("sr", "нидерланд тілі", "Суринам"),
  CountryLocalization("sj", "норвегиялық букмол тілі", "Шпицберген және Ян-Майен"),
  CountryLocalization("sz", "ағылшын тілі", "Свазиленд"),
  CountryLocalization("se", "швед тілі", "Швеция"),
  CountryLocalization("ch", "швейцариялық неміс тілі", "Швейцария"),
  CountryLocalization("sy", "араб тілі", "Сирия"),
  CountryLocalization("st", "португал тілі", "Сан-Томе және Принсипи"),
  CountryLocalization("tw", "қытай тілі", "Тайвань"),
  CountryLocalization("tj", "тәжік тілі", "Тәжікстан"),
  CountryLocalization("tz", "маконде тілі", "Танзания"),
  CountryLocalization("th", "тай тілі", "Тайланд"),
  CountryLocalization("tl", "португал тілі", "Тимор-Лесте"),
  CountryLocalization("tg", "француз тілі", "Того"),
  CountryLocalization("tk", "ағылшын тілі", "Токелау"),
  CountryLocalization("to", "тонган тілі", "Тонга"),
  CountryLocalization("tt", "ағылшын тілі", "Тринидад және Тобаго"),
  CountryLocalization("tn", "француз тілі", "Тунис"),
  CountryLocalization("tr", "түрік тілі", "Түркия"),
  CountryLocalization("tm", "түрікмен тілі", "Түрікменстан"),
  CountryLocalization("tc", "ағылшын тілі", "Теркс және Кайкос аралдары"),
  CountryLocalization("tv", "ағылшын тілі", "Тувалу"),
  CountryLocalization("um", "ағылшын тілі", "АҚШ-тың сыртқы кіші аралдары"),
  CountryLocalization("vi", "ағылшын тілі", "АҚШ-тың Виргин аралдары"),
  CountryLocalization("ug", "суахили тілі", "Уганда"),
  CountryLocalization("ua", "украин тілі", "Украина"),
  CountryLocalization("ae", "араб тілі", "Біріккен Араб Әмірліктері"),
  CountryLocalization("gb", "ағылшын тілі", "Ұлыбритания"),
  CountryLocalization("us", "лакота тілі", "Америка Құрама Штаттары"),
  CountryLocalization("uy", "испан тілі", "Уругвай"),
  CountryLocalization("uz", "өзбек тілі", "Өзбекстан"),
  CountryLocalization("vu", "француз тілі", "Вануату"),
  CountryLocalization("va", "итальян тілі", "Ватикан"),
  CountryLocalization("ve", "испан тілі", "Венесуэла"),
  CountryLocalization("vn", "вьетнам тілі", "Вьетнам"),
  CountryLocalization("wf", "француз тілі", "Уоллис және Футуна"),
  CountryLocalization("eh", "араб тілі", "Батыс Сахара"),
  CountryLocalization("ye", "араб тілі", "Йемен"),
  CountryLocalization("zm", "ағылшын тілі", "Замбия"),
  CountryLocalization("zw", "солтүстік ндебеле тілі", "Зимбабве"),
  CountryLocalization("ax", "швед тілі", "Аланд аралдары"),
)
