/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot.atlas.extended

import dev.teogor.xenoglot.atlas.CountryLocalization
import kotlin.collections.List

/**
 * Holds the internal list of country-language mappings used for lookups within the package for
 * language code fo.
 *
 * This property contains a hardcoded list of [CountryLocalization] objects, each representing
 * a country and its associated official languages. This list is used by [CountryLanguageRegistry]
 * to provide access to country-language data and should not be modified directly.
 *
 * @see CountryLocalization
 * @see CountryLanguageRegistry
 */
internal val _countryLanguageMappings_fo: List<CountryLocalization> = listOf(
  CountryLocalization("af", "persiskt", "Afganistan"),
  CountryLocalization("al", "albanskt", "Albania"),
  CountryLocalization("dz", "franskt", "Algeria"),
  CountryLocalization("as", "enskt", "Amerikanska Samoa"),
  CountryLocalization("ad", "katalani", "Andorra"),
  CountryLocalization("ao", "lingala", "Angola"),
  CountryLocalization("ai", "enskt", "Anguilla"),
  CountryLocalization("ag", "enskt", "Antigua & Barbuda"),
  CountryLocalization("ar", "spanskt", "Argentina"),
  CountryLocalization("am", "armenskt", "Armenia"),
  CountryLocalization("aw", "hálendskt", "Aruba"),
  CountryLocalization("au", "enskt", "Avstralia"),
  CountryLocalization("at", "enskt", "Eysturríki"),
  CountryLocalization("az", "aserbajdsjanskt", "Aserbadjan"),
  CountryLocalization("bs", "enskt", "Bahamaoyggjar"),
  CountryLocalization("bh", "arabiskt", "Barein"),
  CountryLocalization("bd", "bangla", "Bangladesj"),
  CountryLocalization("bb", "enskt", "Barbados"),
  CountryLocalization("by", "hvitarussiskt", "Hvítarussland"),
  CountryLocalization("be", "franskt", "Belgia"),
  CountryLocalization("bz", "enskt", "Belis"),
  CountryLocalization("bj", "franskt", "Benin"),
  CountryLocalization("bm", "enskt", "Bermuda"),
  CountryLocalization("bt", "dzongkha", "Butan"),
  CountryLocalization("bo", "spanskt", "Bolivia"),
  CountryLocalization("ba", "bosniskt", "Bosnia-Hersegovina"),
  CountryLocalization("bw", "enskt", "Botsvana"),
  CountryLocalization("br", "portugiskiskt", "Brasil"),
  CountryLocalization("io", "enskt", "Stóra Bretlands Indiahavoyggjar"),
  CountryLocalization("vg", "enskt", "Stóra Bretlands Jomfrúoyggjar"),
  CountryLocalization("bn", "malaiiskt", "Brunei"),
  CountryLocalization("bg", "bulgarskt", "Bulgaria"),
  CountryLocalization("bf", "franskt", "Burkina Faso"),
  CountryLocalization("bi", "franskt", "Burundi"),
  CountryLocalization("kh", "khmer", "Kambodja"),
  CountryLocalization("cm", "basaa", "Kamerun"),
  CountryLocalization("ca", "franskt", "Kanada"),
  CountryLocalization("ic", "spanskt", "Kanariuoyggjar"),
  CountryLocalization("cv", "grønhøvdaoyggjarskt", "Grønhøvdaoyggjar"),
  CountryLocalization("bq", "hálendskt", "Niðurlonds Karibia"),
  CountryLocalization("ky", "enskt", "Caymanoyggjar"),
  CountryLocalization("cf", "lingala", "Miðafrikalýðveldið"),
  CountryLocalization("ea", "spanskt", "Ceuta & Melilla"),
  CountryLocalization("td", "arabiskt", "Kjad"),
  CountryLocalization("cl", "spanskt", "Kili"),
  CountryLocalization("cn", "tibetskt", "Kina"),
  CountryLocalization("cx", "enskt", "Jólaoyggjin"),
  CountryLocalization("cc", "enskt", "Kokosoyggjar"),
  CountryLocalization("co", "spanskt", "Kolombia"),
  CountryLocalization("km", "arabiskt", "Komoroyggjar"),
  CountryLocalization("cg", "lingala", "Kongo"),
  CountryLocalization("cd", "swahili", "Kongo, Dem. Lýðveldið"),
  CountryLocalization("ck", "enskt", "Cooksoyggjar"),
  CountryLocalization("cr", "spanskt", "Kosta Rika"),
  CountryLocalization("hr", "kroatiskt", "Kroatia"),
  CountryLocalization("cu", "spanskt", "Kuba"),
  CountryLocalization("cw", "hálendskt", "Curaçao"),
  CountryLocalization("cy", "enskt", "Kýpros"),
  CountryLocalization("cz", "kekkiskt", "Kekkia"),
  CountryLocalization("ci", "franskt", "Fílabeinsstrondin"),
  CountryLocalization("dk", "enskt", "Danmark"),
  CountryLocalization("dg", "enskt", "Diego Garcia"),
  CountryLocalization("dj", "franskt", "Djibuti"),
  CountryLocalization("dm", "enskt", "Dominika"),
  CountryLocalization("do", "spanskt", "Dominikalýðveldið"),
  CountryLocalization("ec", "quechua", "Ekvador"),
  CountryLocalization("eg", "arabiskt", "Egyptaland"),
  CountryLocalization("sv", "spanskt", "El Salvador"),
  CountryLocalization("gq", "spanskt", "Ekvatorguinea"),
  CountryLocalization("er", "tigrinya", "Eritrea"),
  CountryLocalization("ee", "estiskt", "Estland"),
  CountryLocalization("et", "amhariskt", "Etiopia"),
  CountryLocalization("fk", "enskt", "Falklandsoyggjar"),
  CountryLocalization("fo", "føroyskt", "Føroyar"),
  CountryLocalization("fj", "enskt", "Fiji"),
  CountryLocalization("fi", "svenskt", "Finnland"),
  CountryLocalization("fr", "týskt (Sveis)", "Frakland"),
  CountryLocalization("gf", "franskt", "Franska Gujana"),
  CountryLocalization("pf", "franskt", "Franska Polynesia"),
  CountryLocalization("ga", "franskt", "Gabon"),
  CountryLocalization("gm", "enskt", "Gambia"),
  CountryLocalization("ge", "ossetiskt", "Georgia"),
  CountryLocalization("de", "lágt sorbian", "Týskland"),
  CountryLocalization("gh", "enskt", "Gana"),
  CountryLocalization("gi", "enskt", "Gibraltar"),
  CountryLocalization("gr", "grikskt", "Grikkaland"),
  CountryLocalization("gl", "kalaallisut", "Grønland"),
  CountryLocalization("gd", "enskt", "Grenada"),
  CountryLocalization("gp", "franskt", "Guadeloupe"),
  CountryLocalization("gu", "enskt", "Guam"),
  CountryLocalization("gt", "spanskt", "Guatemala"),
  CountryLocalization("gg", "enskt", "Guernsey"),
  CountryLocalization("gn", "franskt", "Guinea"),
  CountryLocalization("gw", "portugiskiskt", "Guinea-Bissau"),
  CountryLocalization("gy", "enskt", "Gujana"),
  CountryLocalization("ht", "franskt", "Haiti"),
  CountryLocalization("hn", "spanskt", "Honduras"),
  CountryLocalization("hk", "kinesiskt", "Hong Kong SAR Kina"),
  CountryLocalization("hu", "ungarskt", "Ungarn"),
  CountryLocalization("is", "íslendskt", "Ísland"),
  CountryLocalization("in", "nepalskt", "India"),
  CountryLocalization("id", "Indonesian", "Indonesia"),
  CountryLocalization("ir", "persiskt", "Iran"),
  CountryLocalization("iq", "norður luri", "Irak"),
  CountryLocalization("ie", "enskt", "Írland"),
  CountryLocalization("im", "manx", "Isle of Man"),
  CountryLocalization("il", "enskt", "Ísrael"),
  CountryLocalization("it", "týskt", "Italia"),
  CountryLocalization("jm", "enskt", "Jamaika"),
  CountryLocalization("jp", "japanskt", "Japan"),
  CountryLocalization("je", "enskt", "Jersey"),
  CountryLocalization("jo", "arabiskt", "Jordan"),
  CountryLocalization("kz", "kazakh", "Kasakstan"),
  CountryLocalization("ke", "somaliskt", "Kenja"),
  CountryLocalization("ki", "enskt", "Kiribati"),
  CountryLocalization("xk", "serbiskt", "Kosovo"),
  CountryLocalization("kw", "arabiskt", "Kuvait"),
  CountryLocalization("kg", "russiskt", "Kirgisia"),
  CountryLocalization("la", "laoskt", "Laos"),
  CountryLocalization("lv", "lettiskt", "Lettland"),
  CountryLocalization("lb", "arabiskt", "Libanon"),
  CountryLocalization("ls", "enskt", "Lesoto"),
  CountryLocalization("lr", "enskt", "Liberia"),
  CountryLocalization("ly", "arabiskt", "Libya"),
  CountryLocalization("li", "týskt (Sveis)", "Liktinstein"),
  CountryLocalization("lt", "litaviskt", "Litava"),
  CountryLocalization("lu", "luksemborgskt", "Luksemborg"),
  CountryLocalization("mo", "portugiskiskt", "Makao SAR Kina"),
  CountryLocalization("mk", "albanskt", "Makedónia"),
  CountryLocalization("mg", "franskt", "Madagaskar"),
  CountryLocalization("mw", "enskt", "Malavi"),
  CountryLocalization("my", "tamilskt", "Malaisia"),
  CountryLocalization("ml", "franskt", "Mali"),
  CountryLocalization("mt", "enskt", "Malta"),
  CountryLocalization("mh", "enskt", "Marshalloyggjar"),
  CountryLocalization("mq", "franskt", "Martinique"),
  CountryLocalization("mr", "arabiskt", "Móritania"),
  CountryLocalization("mu", "morisyen", "Móritius"),
  CountryLocalization("yt", "franskt", "Mayotte"),
  CountryLocalization("mx", "spanskt", "Meksiko"),
  CountryLocalization("fm", "enskt", "Mikronesiasamveldið"),
  CountryLocalization("md", "russiskt", "Moldova"),
  CountryLocalization("mc", "franskt", "Monako"),
  CountryLocalization("mn", "mongolskt", "Mongolia"),
  CountryLocalization("me", "serbiskt", "Montenegro"),
  CountryLocalization("ms", "enskt", "Montserrat"),
  CountryLocalization("ma", "miðatlasfjøll tamazight", "Marokko"),
  CountryLocalization("mz", "makhuwa-meetto", "Mosambik"),
  CountryLocalization("mm", "burmesiskt", "Myanmar (Burma)"),
  CountryLocalization("na", "enskt", "Namibia"),
  CountryLocalization("nr", "enskt", "Nauru"),
  CountryLocalization("np", "nepalskt", "Nepal"),
  CountryLocalization("nl", "enskt", "Niðurlond"),
  CountryLocalization("nc", "franskt", "Nýkaledónia"),
  CountryLocalization("nz", "enskt", "Nýsæland"),
  CountryLocalization("ni", "spanskt", "Nikaragua"),
  CountryLocalization("ne", "hausa", "Niger"),
  CountryLocalization("ng", "hausa", "Nigeria"),
  CountryLocalization("nu", "enskt", "Niue"),
  CountryLocalization("nf", "enskt", "Norfolksoyggj"),
  CountryLocalization("kp", "koreanskt", "Norðurkorea"),
  CountryLocalization("mp", "enskt", "Norðaru Mariuoyggjar"),
  CountryLocalization("no", "norður sámiskt", "Noreg"),
  CountryLocalization("om", "arabiskt", "Oman"),
  CountryLocalization("pk", "enskt", "Pakistan"),
  CountryLocalization("pw", "enskt", "Palau"),
  CountryLocalization("ps", "arabiskt", "Palestinskt landøki"),
  CountryLocalization("pa", "spanskt", "Panama"),
  CountryLocalization("pg", "enskt", "Papua Nýguinea"),
  CountryLocalization("py", "spanskt", "Paraguai"),
  CountryLocalization("pe", "spanskt", "Peru"),
  CountryLocalization("ph", "filipiniskt", "Filipsoyggjar"),
  CountryLocalization("pn", "enskt", "Pitcairnoyggjar"),
  CountryLocalization("pl", "pólskt", "Pólland"),
  CountryLocalization("pt", "portugiskiskt", "Portugal"),
  CountryLocalization("pr", "enskt", "Puerto Riko"),
  CountryLocalization("qa", "arabiskt", "Katar"),
  CountryLocalization("ro", "rumenskt", "Rumenia"),
  CountryLocalization("ru", "tatar", "Russland"),
  CountryLocalization("rw", "enskt", "Ruanda"),
  CountryLocalization("re", "franskt", "Réunion"),
  CountryLocalization("ws", "enskt", "Samoa"),
  CountryLocalization("sm", "italskt", "San Marino"),
  CountryLocalization("sa", "arabiskt", "Saudiarabia"),
  CountryLocalization("sn", "franskt", "Senegal"),
  CountryLocalization("rs", "serbiskt", "Serbia"),
  CountryLocalization("cs", "serbiskt", "Serbia and Montenegro"),
  CountryLocalization("sc", "franskt", "Seyskelloyggjar"),
  CountryLocalization("sl", "enskt", "Sierra Leona"),
  CountryLocalization("sg", "tamilskt", "Singapor"),
  CountryLocalization("sx", "enskt", "Sint Maarten"),
  CountryLocalization("sk", "slovakiskt", "Slovakia"),
  CountryLocalization("si", "slovenskt", "Slovenia"),
  CountryLocalization("sb", "enskt", "Salomonoyggjar"),
  CountryLocalization("so", "arabiskt", "Somalia"),
  CountryLocalization("za", "enskt", "Suðurafrika"),
  CountryLocalization("kr", "koreanskt", "Suðurkorea"),
  CountryLocalization("ss", "nuer", "Suðursudan"),
  CountryLocalization("es", "spanskt", "Spania"),
  CountryLocalization("lk", "tamilskt", "Sri Lanka"),
  CountryLocalization("bl", "franskt", "St. Barthélemy"),
  CountryLocalization("sh", "enskt", "St. Helena"),
  CountryLocalization("kn", "enskt", "St. Kitts & Nevis"),
  CountryLocalization("lc", "enskt", "St. Lusia"),
  CountryLocalization("mf", "franskt", "St-Martin"),
  CountryLocalization("pm", "franskt", "Saint Pierre & Miquelon"),
  CountryLocalization("vc", "enskt", "St. Vinsent & Grenadinoyggjar"),
  CountryLocalization("sd", "arabiskt", "Sudan"),
  CountryLocalization("sr", "hálendskt", "Surinam"),
  CountryLocalization("sj", "norskt bókmál", "Svalbard & Jan Mayen"),
  CountryLocalization("sz", "enskt", "Svasiland"),
  CountryLocalization("se", "svenskt", "Svøríki"),
  CountryLocalization("ch", "týskt (Sveis)", "Sveis"),
  CountryLocalization("sy", "arabiskt", "Sýria"),
  CountryLocalization("st", "portugiskiskt", "Sao Tome & Prinsipi"),
  CountryLocalization("tw", "kinesiskt", "Taivan"),
  CountryLocalization("tj", "tajik", "Tadsjikistan"),
  CountryLocalization("tz", "makonde", "Tansania"),
  CountryLocalization("th", "tailendskt", "Tailand"),
  CountryLocalization("tl", "portugiskiskt", "Eysturtimor"),
  CountryLocalization("tg", "franskt", "Togo"),
  CountryLocalization("tk", "enskt", "Tokelau"),
  CountryLocalization("to", "tonganskt", "Tonga"),
  CountryLocalization("tt", "enskt", "Trinidad & Tobago"),
  CountryLocalization("tn", "franskt", "Tunesia"),
  CountryLocalization("tr", "turkiskt", "Turkaland"),
  CountryLocalization("tm", "turkmenskt", "Turkmenistan"),
  CountryLocalization("tc", "enskt", "Turks- og Caicosoyggjar"),
  CountryLocalization("tv", "enskt", "Tuvalu"),
  CountryLocalization("um", "enskt", "Sambandsríki Amerikas fjarskotnu oyggjar"),
  CountryLocalization("vi", "enskt", "Sambandsríki Amerikas Jomfrúoyggjar"),
  CountryLocalization("ug", "swahili", "Uganda"),
  CountryLocalization("ua", "ukrainskt", "Ukraina"),
  CountryLocalization("ae", "arabiskt", "Sameindu Emirríkini"),
  CountryLocalization("gb", "enskt", "Stórabretland"),
  CountryLocalization("us", "lakota", "Sambandsríki Amerika"),
  CountryLocalization("uy", "spanskt", "Uruguai"),
  CountryLocalization("uz", "usbekiskt", "Usbekistan"),
  CountryLocalization("vu", "franskt", "Vanuatu"),
  CountryLocalization("va", "italskt", "Vatikanbýur"),
  CountryLocalization("ve", "spanskt", "Venesuela"),
  CountryLocalization("vn", "vjetnamesiskt", "Vjetnam"),
  CountryLocalization("wf", "franskt", "Wallis- og Futunaoyggjar"),
  CountryLocalization("eh", "arabiskt", "Vestursahara"),
  CountryLocalization("ye", "arabiskt", "Jemen"),
  CountryLocalization("zm", "enskt", "Sambia"),
  CountryLocalization("zw", "norður ndebele", "Simbabvi"),
  CountryLocalization("ax", "svenskt", "Áland"),
)
