/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot.atlas.extended

import dev.teogor.xenoglot.atlas.CountryLocalization
import kotlin.collections.List

/**
 * Holds the internal list of country-language mappings used for lookups within the package for
 * language code so.
 *
 * This property contains a hardcoded list of [CountryLocalization] objects, each representing
 * a country and its associated official languages. This list is used by [CountryLanguageRegistry]
 * to provide access to country-language data and should not be modified directly.
 *
 * @see CountryLocalization
 * @see CountryLanguageRegistry
 */
internal val _countryLanguageMappings_so: List<CountryLocalization> = listOf(
  CountryLocalization("af", "Faarisi", "Afgaanistaan"),
  CountryLocalization("al", "Albanian", "Albaaniya"),
  CountryLocalization("dz", "Faransiis", "Aljeeriya"),
  CountryLocalization("as", "Ingiriisi", "Samowa Ameerika"),
  CountryLocalization("ad", "Catalan", "Andora"),
  CountryLocalization("ao", "Lingala", "Angoola"),
  CountryLocalization("ai", "Ingiriisi", "Anguilla"),
  CountryLocalization("ag", "Ingiriisi", "Antigua iyo Barbuda"),
  CountryLocalization("ar", "Isbaanish", "Arjantiin"),
  CountryLocalization("am", "Armenian", "Armeeniya"),
  CountryLocalization("aw", "Holandays", "Aruba"),
  CountryLocalization("au", "Ingiriisi", "Awstaraaliya"),
  CountryLocalization("at", "Ingiriisi", "Awsteriya"),
  CountryLocalization("az", "Azerbaijani", "Azerbajaan"),
  CountryLocalization("bs", "Ingiriisi", "Bahaamas"),
  CountryLocalization("bh", "Carabi", "Baxreyn"),
  CountryLocalization("bd", "Bangaali", "Bangaaladheesh"),
  CountryLocalization("bb", "Ingiriisi", "Baarbadoos"),
  CountryLocalization("by", "Beleruusiyaan", "Belarus"),
  CountryLocalization("be", "Faransiis", "Biljam"),
  CountryLocalization("bz", "Ingiriisi", "Belize"),
  CountryLocalization("bj", "Faransiis", "Biniin"),
  CountryLocalization("bm", "Ingiriisi", "Bermuuda"),
  CountryLocalization("bt", "Dzongkha", "Bhutan"),
  CountryLocalization("bo", "Isbaanish", "Boliifiya"),
  CountryLocalization("ba", "Bosnian", "Bosniya Hersigoviina"),
  CountryLocalization("bw", "Ingiriisi", "Botuswaana"),
  CountryLocalization("br", "Boortaqiis", "Braasiil"),
  CountryLocalization("io", "Ingiriisi", "British Indian Ocean Territory"),
  CountryLocalization("vg", "Ingiriisi", "British Virgin Islands"),
  CountryLocalization("bn", "Malaay", "Buruneeya"),
  CountryLocalization("bg", "Bulgeeriyaan", "Bulgaariya"),
  CountryLocalization("bf", "Faransiis", "Burkiina Faaso"),
  CountryLocalization("bi", "Faransiis", "Burundi"),
  CountryLocalization("kh", "Kamboodhian", "Kamboodiya"),
  CountryLocalization("cm", "Basaa", "Kaameruun"),
  CountryLocalization("ca", "Faransiis", "Kanada"),
  CountryLocalization("ic", "Isbaanish", "IC"),
  CountryLocalization("cv", "kea", "Cape Verde Islands"),
  CountryLocalization("bq", "Holandays", "Caribbean Netherlands"),
  CountryLocalization("ky", "Ingiriisi", "Cayman Islands"),
  CountryLocalization("cf", "Lingala", "Jamhuuriyadda Afrikada Dhexe"),
  CountryLocalization("ea", "Isbaanish", "EA"),
  CountryLocalization("td", "Carabi", "Jaad"),
  CountryLocalization("cl", "Isbaanish", "Jili"),
  CountryLocalization("cn", "Tibetan", "Shiinaha"),
  CountryLocalization("cx", "Ingiriisi", "Christmas Island"),
  CountryLocalization("cc", "Ingiriisi", "Cocos (Keeling) Islands"),
  CountryLocalization("co", "Isbaanish", "Kolombiya"),
  CountryLocalization("km", "Carabi", "Komooros"),
  CountryLocalization("cg", "Lingala", "Kongo"),
  CountryLocalization("cd", "Swahili", "Jamhuuriyadda Dimuquraadiga Kongo"),
  CountryLocalization("ck", "Ingiriisi", "Jaziiradda Cook"),
  CountryLocalization("cr", "Isbaanish", "Kosta Riika"),
  CountryLocalization("hr", "Croatian", "Korweeshiya"),
  CountryLocalization("cu", "Isbaanish", "Kuuba"),
  CountryLocalization("cw", "Holandays", "Curaçao"),
  CountryLocalization("cy", "Ingiriisi", "Qubrus"),
  CountryLocalization("cz", "Jeeg", "Jamhuuriyadda Jek"),
  CountryLocalization("ci", "Faransiis", "Ivory coast"),
  CountryLocalization("dk", "Ingiriisi", "Denmark"),
  CountryLocalization("dg", "Ingiriisi", "DG"),
  CountryLocalization("dj", "Faransiis", "Jabuuti"),
  CountryLocalization("dm", "Ingiriisi", "Domeenika"),
  CountryLocalization("do", "Isbaanish", "Jamhuuriyadda Domeenika"),
  CountryLocalization("ec", "Quechua", "Ikuwadoor"),
  CountryLocalization("eg", "Carabi", "Masar"),
  CountryLocalization("sv", "Isbaanish", "El Salvador"),
  CountryLocalization("gq", "Isbaanish", "Equatorial Guinea"),
  CountryLocalization("er", "Tigrinya", "Eretereeya"),
  CountryLocalization("ee", "Estonian", "Estooniya"),
  CountryLocalization("et", "Axmaari", "Itoobiya"),
  CountryLocalization("fk", "Ingiriisi", "Jaziiradaha Fooklaan"),
  CountryLocalization("fo", "Faroese", "Faroe Islands"),
  CountryLocalization("fj", "Ingiriisi", "Fiji"),
  CountryLocalization("fi", "Swiidhis", "Finland"),
  CountryLocalization("fr", "Swiss German", "Faransiis"),
  CountryLocalization("gf", "Faransiis", "French Guiana"),
  CountryLocalization("pf", "Faransiis", "French Polynesia"),
  CountryLocalization("ga", "Faransiis", "Gaaboon"),
  CountryLocalization("gm", "Ingiriisi", "Gambiya"),
  CountryLocalization("ge", "Ossetic", "Joorjiya"),
  CountryLocalization("de", "Lower Sorbian", "Jarmal"),
  CountryLocalization("gh", "Ingiriisi", "Gaana"),
  CountryLocalization("gi", "Ingiriisi", "Gibraltar"),
  CountryLocalization("gr", "Giriik", "Giriig"),
  CountryLocalization("gl", "Kalaallisut", "Greenland"),
  CountryLocalization("gd", "Ingiriisi", "Giriinaada"),
  CountryLocalization("gp", "Faransiis", "Guadeloupe"),
  CountryLocalization("gu", "Ingiriisi", "Guam"),
  CountryLocalization("gt", "Isbaanish", "Guwaatamaala"),
  CountryLocalization("gg", "Ingiriisi", "Guernsey"),
  CountryLocalization("gn", "Faransiis", "Gini"),
  CountryLocalization("gw", "Boortaqiis", "Gini-Bisaaw"),
  CountryLocalization("gy", "Ingiriisi", "Guyana"),
  CountryLocalization("ht", "Faransiis", "Hayti"),
  CountryLocalization("hn", "Isbaanish", "Honduras"),
  CountryLocalization("hk", "Jayniis", "Hong Kong SAR China"),
  CountryLocalization("hu", "Hangariyaan", "Hangeri"),
  CountryLocalization("is", "Icelandic", "Iislaand"),
  CountryLocalization("in", "Nebaali", "Hindiya"),
  CountryLocalization("id", "Indonesian", "Indoneesiya"),
  CountryLocalization("ir", "Faarisi", "Iiraan"),
  CountryLocalization("iq", "lrc", "Ciraaq"),
  CountryLocalization("ie", "Ingiriisi", "Ayrlaand"),
  CountryLocalization("im", "Manx", "Isle of Man"),
  CountryLocalization("il", "Ingiriisi", "Israaʼiil"),
  CountryLocalization("it", "Jarmal", "Talyaani"),
  CountryLocalization("jm", "Ingiriisi", "Jameyka"),
  CountryLocalization("jp", "Jabbaaniis", "Jabaan"),
  CountryLocalization("je", "Ingiriisi", "Jersey"),
  CountryLocalization("jo", "Carabi", "Urdun"),
  CountryLocalization("kz", "Kazakh", "Kasaakhistaan"),
  CountryLocalization("ke", "Soomaali", "Kiiniya"),
  CountryLocalization("ki", "Ingiriisi", "Kiribati"),
  CountryLocalization("xk", "Serbian", "XK"),
  CountryLocalization("kw", "Carabi", "Kuwayt"),
  CountryLocalization("kg", "Ruush", "Kirgistaan"),
  CountryLocalization("la", "Lao", "Laos"),
  CountryLocalization("lv", "Latvian", "Latfiya"),
  CountryLocalization("lb", "Carabi", "Lubnaan"),
  CountryLocalization("ls", "Ingiriisi", "Losooto"),
  CountryLocalization("lr", "Ingiriisi", "Laybeeriya"),
  CountryLocalization("ly", "Carabi", "Liibiya"),
  CountryLocalization("li", "Swiss German", "Liechtenstein"),
  CountryLocalization("lt", "Lithuanian", "Lituweeniya"),
  CountryLocalization("lu", "Luxembourgish", "Luksemboorg"),
  CountryLocalization("mo", "Boortaqiis", "Macao SAR China"),
  CountryLocalization("mk", "Albanian", "Makadooniya"),
  CountryLocalization("mg", "Faransiis", "Madagaskar"),
  CountryLocalization("mw", "Ingiriisi", "Malaawi"),
  CountryLocalization("my", "Tamiil", "Malaysia"),
  CountryLocalization("ml", "Faransiis", "Maali"),
  CountryLocalization("mt", "Ingiriisi", "Maalda"),
  CountryLocalization("mh", "Ingiriisi", "Marshall Islands"),
  CountryLocalization("mq", "Faransiis", "Martinique"),
  CountryLocalization("mr", "Carabi", "Muritaaniya"),
  CountryLocalization("mu", "mfe", "Murishiyoos"),
  CountryLocalization("yt", "Faransiis", "Mayotte"),
  CountryLocalization("mx", "Isbaanish", "Meksiko"),
  CountryLocalization("fm", "Ingiriisi", "Micronesia"),
  CountryLocalization("md", "Ruush", "Moldofa"),
  CountryLocalization("mc", "Faransiis", "Moonako"),
  CountryLocalization("mn", "Mongolian", "Mongooliya"),
  CountryLocalization("me", "Serbian", "Montenegro"),
  CountryLocalization("ms", "Ingiriisi", "Montserrat"),
  CountryLocalization("ma", "tzm", "Marooko"),
  CountryLocalization("mz", "mgh", "Musambiig"),
  CountryLocalization("mm", "Burmese", "Miyanmar"),
  CountryLocalization("na", "Ingiriisi", "Namiibiya"),
  CountryLocalization("nr", "Ingiriisi", "Nauru"),
  CountryLocalization("np", "Nebaali", "Nebaal"),
  CountryLocalization("nl", "Ingiriisi", "Netherlands"),
  CountryLocalization("nc", "Faransiis", "New Caledonia"),
  CountryLocalization("nz", "Ingiriisi", "Neyuusilaand"),
  CountryLocalization("ni", "Isbaanish", "Nikaraaguwa"),
  CountryLocalization("ne", "Hawsa", "Nayjer"),
  CountryLocalization("ng", "Hawsa", "Nayjeeriya"),
  CountryLocalization("nu", "Ingiriisi", "Niue"),
  CountryLocalization("nf", "Ingiriisi", "Norfolk Island"),
  CountryLocalization("kp", "Kuuriyaan", "Kuuriyada Waqooyi"),
  CountryLocalization("mp", "Ingiriisi", "Northern Mariana Islands"),
  CountryLocalization("no", "Northern Sami", "Noorweey"),
  CountryLocalization("om", "Carabi", "Cumaan"),
  CountryLocalization("pk", "Ingiriisi", "Bakistaan"),
  CountryLocalization("pw", "Ingiriisi", "Palau"),
  CountryLocalization("ps", "Carabi", "Falastiin Daanka galbeed iyo Qasa"),
  CountryLocalization("pa", "Isbaanish", "Panama"),
  CountryLocalization("pg", "Ingiriisi", "Papua New Guinea"),
  CountryLocalization("py", "Isbaanish", "Paraguay"),
  CountryLocalization("pe", "Isbaanish", "Peru"),
  CountryLocalization("ph", "Filipino", "Filibiin"),
  CountryLocalization("pn", "Ingiriisi", "Pitcairn"),
  CountryLocalization("pl", "Boolish", "Booland"),
  CountryLocalization("pt", "Boortaqiis", "Bortuqaal"),
  CountryLocalization("pr", "Ingiriisi", "Puerto Rico"),
  CountryLocalization("qa", "Carabi", "Qadar"),
  CountryLocalization("ro", "Romanka", "Rumaaniya"),
  CountryLocalization("ru", "Tatar", "Ruush"),
  CountryLocalization("rw", "Ingiriisi", "Ruwanda"),
  CountryLocalization("re", "Faransiis", "Réunion"),
  CountryLocalization("ws", "Ingiriisi", "Samoa"),
  CountryLocalization("sm", "Talyaani", "San Marino"),
  CountryLocalization("sa", "Carabi", "Sacuudi Carabiya"),
  CountryLocalization("sn", "Faransiis", "Sinigaal"),
  CountryLocalization("rs", "Serbian", "Serbia"),
  CountryLocalization("cs", "Serbian", "Serbia and Montenegro"),
  CountryLocalization("sc", "Faransiis", "Sishelis"),
  CountryLocalization("sl", "Ingiriisi", "Siraaliyoon"),
  CountryLocalization("sg", "Tamiil", "Singaboor"),
  CountryLocalization("sx", "Ingiriisi", "Sint Maarten"),
  CountryLocalization("sk", "Slovak", "Slovakia"),
  CountryLocalization("si", "Slovenian", "Slovenia"),
  CountryLocalization("sb", "Ingiriisi", "Solomon Islands"),
  CountryLocalization("so", "Carabi", "Soomaaliya"),
  CountryLocalization("za", "Ingiriisi", "Koonfur Afrika"),
  CountryLocalization("kr", "Kuuriyaan", "Kuuriyada Koonfureed"),
  CountryLocalization("ss", "nus", "South Sudan"),
  CountryLocalization("es", "Isbaanish", "Isbeyn"),
  CountryLocalization("lk", "Tamiil", "Sirilaanka"),
  CountryLocalization("bl", "Faransiis", "St. Barthélemy"),
  CountryLocalization("sh", "Ingiriisi", "Saint Helena"),
  CountryLocalization("kn", "Ingiriisi", "Saint Kitts and Nevis"),
  CountryLocalization("lc", "Ingiriisi", "Saint Lucia"),
  CountryLocalization("mf", "Faransiis", "St. Martin"),
  CountryLocalization("pm", "Faransiis", "Saint Pierre and Miquelon"),
  CountryLocalization("vc", "Ingiriisi", "Saint Vincent and the Grenadines"),
  CountryLocalization("sd", "Carabi", "Suudaan"),
  CountryLocalization("sr", "Holandays", "Suriname"),
  CountryLocalization("sj", "Norwegian Bokmål", "Svalbard & Jan Mayen"),
  CountryLocalization("sz", "Ingiriisi", "Iswaasilaand"),
  CountryLocalization("se", "Swiidhis", "Iswidhan"),
  CountryLocalization("ch", "Swiss German", "Swiiserlaand"),
  CountryLocalization("sy", "Carabi", "Suuriya"),
  CountryLocalization("st", "Boortaqiis", "São Tomé and Príncipe"),
  CountryLocalization("tw", "Jayniis", "Taywaan"),
  CountryLocalization("tj", "Tajik", "Tajikistan"),
  CountryLocalization("tz", "kde", "Tansaaniya"),
  CountryLocalization("th", "Taaylandays", "Taylaand"),
  CountryLocalization("tl", "Boortaqiis", "Timorka bari"),
  CountryLocalization("tg", "Faransiis", "Toogo"),
  CountryLocalization("tk", "Ingiriisi", "Tokelau"),
  CountryLocalization("to", "Tongan", "Tonga"),
  CountryLocalization("tt", "Ingiriisi", "Trinidad and Tobago"),
  CountryLocalization("tn", "Faransiis", "Tuniisiya"),
  CountryLocalization("tr", "Turkish", "Turki"),
  CountryLocalization("tm", "Turkmen", "Turkmenistan"),
  CountryLocalization("tc", "Ingiriisi", "Turks and Caicos Islands"),
  CountryLocalization("tv", "Ingiriisi", "Tuvalu"),
  CountryLocalization("um", "Ingiriisi", "U.S. Outlying Islands"),
  CountryLocalization("vi", "Ingiriisi", "U.S. Virgin Islands"),
  CountryLocalization("ug", "Swahili", "Ugaanda"),
  CountryLocalization("ua", "Yukreeniyaan", "Ukrayn"),
  CountryLocalization("ae", "Carabi", "Imaaraadka Carabta ee Midoobay"),
  CountryLocalization("gb", "Ingiriisi", "United Kingdom"),
  CountryLocalization("us", "lkt", "Maraykanka"),
  CountryLocalization("uy", "Isbaanish", "Uruguwaay"),
  CountryLocalization("uz", "Uzbek", "Uusbakistaan"),
  CountryLocalization("vu", "Faransiis", "Vanuatu"),
  CountryLocalization("va", "Talyaani", "Faatikaan"),
  CountryLocalization("ve", "Isbaanish", "Fenisuweela"),
  CountryLocalization("vn", "Fiitnaamays", "Fiyetnaam"),
  CountryLocalization("wf", "Faransiis", "Wallis and Futuna"),
  CountryLocalization("eh", "Carabi", "Western Sahara"),
  CountryLocalization("ye", "Carabi", "Yaman"),
  CountryLocalization("zm", "Ingiriisi", "Saambiya"),
  CountryLocalization("zw", "North Ndebele", "Simbaabwe"),
  CountryLocalization("ax", "Swiidhis", "Åland Islands"),
)
