/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot.atlas.extended

import dev.teogor.xenoglot.atlas.CountryLocalization
import kotlin.collections.List

/**
 * Holds the internal list of country-language mappings used for lookups within the package for
 * language code to.
 *
 * This property contains a hardcoded list of [CountryLocalization] objects, each representing
 * a country and its associated official languages. This list is used by [CountryLanguageRegistry]
 * to provide access to country-language data and should not be modified directly.
 *
 * @see CountryLocalization
 * @see CountryLanguageRegistry
 */
internal val _countryLanguageMappings_to: List<CountryLocalization> = listOf(
  CountryLocalization("af", "lea fakapēsia", "ʻAfikānisitani"),
  CountryLocalization("al", "lea fakaʻalapēnia", "ʻAlipania"),
  CountryLocalization("dz", "lea fakafalanisē", "ʻAlisilia"),
  CountryLocalization("as", "lea fakapālangi", "Haʻamoa ʻAmelika"),
  CountryLocalization("ad", "lea fakakatalani", "ʻAnitola"),
  CountryLocalization("ao", "lea lingikala", "ʻAngikola"),
  CountryLocalization("ai", "lea fakapālangi", "Anikuila"),
  CountryLocalization("ag", "lea fakapālangi", "Anitikua mo Palaputa"),
  CountryLocalization("ar", "lea fakasipēnisi", "ʻAsenitina"),
  CountryLocalization("am", "lea fakaʻāmenia", "ʻĀmenia"),
  CountryLocalization("aw", "lea fakahōlani", "ʻAlupa"),
  CountryLocalization("au", "lea fakapālangi", "ʻAositelēlia"),
  CountryLocalization("at", "lea fakapālangi", "ʻAositulia"),
  CountryLocalization("az", "lea fakaʻasapaisani", "ʻAsapaisani"),
  CountryLocalization("bs", "lea fakapālangi", "Pahama"),
  CountryLocalization("bh", "lea fakaʻalepea", "Paleini"),
  CountryLocalization("bd", "lea fakapāngilā", "Pengilātesi"),
  CountryLocalization("bb", "lea fakapālangi", "Pāpeitosi"),
  CountryLocalization("by", "lea fakapelalusi", "Pelalusi"),
  CountryLocalization("be", "lea fakafalanisē", "Pelesiume"),
  CountryLocalization("bz", "lea fakapālangi", "Pelise"),
  CountryLocalization("bj", "lea fakafalanisē", "Penini"),
  CountryLocalization("bm", "lea fakapālangi", "Pēmuta"),
  CountryLocalization("bt", "lea fakatisōngika", "Pūtani"),
  CountryLocalization("bo", "lea fakasipēnisi", "Polīvia"),
  CountryLocalization("ba", "lea fakaposinia", "Posinia mo Hesikōvina"),
  CountryLocalization("bw", "lea fakapālangi", "Potisiuana"),
  CountryLocalization("br", "lea fakapotukali", "Palāsili"),
  CountryLocalization("io", "lea fakapālangi", "Potu fonua moana ʻInitia fakapilitānia"),
  CountryLocalization("vg", "lea fakapālangi", "ʻOtumotu Vilikini fakapilitānia"),
  CountryLocalization("bn", "lea fakamalei", "Pulunei"),
  CountryLocalization("bg", "lea fakapulukalia", "Pulukalia"),
  CountryLocalization("bf", "lea fakafalanisē", "Pekano Faso"),
  CountryLocalization("bi", "lea fakafalanisē", "Puluniti"),
  CountryLocalization("kh", "lea fakakamipōtia", "Kamipōtia"),
  CountryLocalization("cm", "lea fakapasaʻa", "Kameluni"),
  CountryLocalization("ca", "lea fakafalanisē", "Kānata"),
  CountryLocalization("ic", "lea fakasipēnisi", "ʻOtumotu Kaneli"),
  CountryLocalization("cv", "lea fakakapuvelitianu", "Muiʻi Vēte"),
  CountryLocalization("bq", "lea fakahōlani", "Kalipiane fakahōlani"),
  CountryLocalization("ky", "lea fakapālangi", "ʻOtumotu Keimeni"),
  CountryLocalization("cf", "lea lingikala", "Lepupelika ʻAfilika Lotoloto"),
  CountryLocalization("ea", "lea fakasipēnisi", "Siuta mo Melila"),
  CountryLocalization("td", "lea fakaʻalepea", "Sāti"),
  CountryLocalization("cl", "lea fakasipēnisi", "Sili"),
  CountryLocalization("cn", "lea fakatipeti", "Siaina"),
  CountryLocalization("cx", "lea fakapālangi", "Motu Kilisimasi"),
  CountryLocalization("cc", "lea fakapālangi", "ʻOtumotu Koko"),
  CountryLocalization("co", "lea fakasipēnisi", "Kolomipia"),
  CountryLocalization("km", "lea fakaʻalepea", "Komolosi"),
  CountryLocalization("cg", "lea lingikala", "Kongo - Palasavila"),
  CountryLocalization("cd", "lea fakasuahili", "Kongo - Kinisasa"),
  CountryLocalization("ck", "lea fakapālangi", "ʻOtumotu Kuki"),
  CountryLocalization("cr", "lea fakasipēnisi", "Kosita Lika"),
  CountryLocalization("hr", "lea fakakuloisia", "Kuloisia"),
  CountryLocalization("cu", "lea fakasipēnisi", "Kiupa"),
  CountryLocalization("cw", "lea fakahōlani", "Kulasao"),
  CountryLocalization("cy", "lea fakapālangi", "Saipalesi"),
  CountryLocalization("cz", "lea fakaseki", "Sēkia"),
  CountryLocalization("ci", "lea fakafalanisē", "Matafonua ʻAivolī"),
  CountryLocalization("dk", "lea fakapālangi", "Tenimaʻake"),
  CountryLocalization("dg", "lea fakapālangi", "Tieko Kāsia"),
  CountryLocalization("dj", "lea fakafalanisē", "Siputi"),
  CountryLocalization("dm", "lea fakapālangi", "Tominika"),
  CountryLocalization("do", "lea fakasipēnisi", "Lepupelika Tominika"),
  CountryLocalization("ec", "lea fakakuetisa", "ʻEkuetoa"),
  CountryLocalization("eg", "lea fakaʻalepea", "ʻIsipite"),
  CountryLocalization("sv", "lea fakasipēnisi", "ʻEle Salavatoa"),
  CountryLocalization("gq", "lea fakasipēnisi", "ʻEkueta Kini"),
  CountryLocalization("er", "lea fakatikilinia", "ʻElitulia"),
  CountryLocalization("ee", "lea fakaʻesitōnia", "ʻEsitōnia"),
  CountryLocalization("et", "lea fakaʻameliki", "ʻĪtiōpia"),
  CountryLocalization("fk", "lea fakapālangi", "ʻOtumotu Fokulani"),
  CountryLocalization("fo", "lea fakafaloe", "ʻOtumotu Faloe"),
  CountryLocalization("fj", "lea fakapālangi", "Fisi"),
  CountryLocalization("fi", "lea fakasuēteni", "Finilani"),
  CountryLocalization("fr", "lea fakasiamane-suisilani", "Falanisē"),
  CountryLocalization("gf", "lea fakafalanisē", "Kuiana fakafalanisē"),
  CountryLocalization("pf", "lea fakafalanisē", "Polinisia fakafalanisē"),
  CountryLocalization("ga", "lea fakafalanisē", "Kaponi"),
  CountryLocalization("gm", "lea fakapālangi", "Kamipia"),
  CountryLocalization("ge", "lea fakaʻosetiki", "Seōsia"),
  CountryLocalization("de", "lea fakasōpia-hifo", "Siamane"),
  CountryLocalization("gh", "lea fakapālangi", "Kana"),
  CountryLocalization("gi", "lea fakapālangi", "Sipalālitā"),
  CountryLocalization("gr", "lea fakakalisi", "Kalisi"),
  CountryLocalization("gl", "lea fakakalaʻalisuti", "Kulinilani"),
  CountryLocalization("gd", "lea fakapālangi", "Kelenatā"),
  CountryLocalization("gp", "lea fakafalanisē", "Kuatalupe"),
  CountryLocalization("gu", "lea fakapālangi", "Kuamu"),
  CountryLocalization("gt", "lea fakasipēnisi", "Kuatamala"),
  CountryLocalization("gg", "lea fakapālangi", "Kuenisī"),
  CountryLocalization("gn", "lea fakafalanisē", "Kini"),
  CountryLocalization("gw", "lea fakapotukali", "Kini-Pisau"),
  CountryLocalization("gy", "lea fakapālangi", "Kuiana"),
  CountryLocalization("ht", "lea fakafalanisē", "Haiti"),
  CountryLocalization("hn", "lea fakasipēnisi", "Honitulasi"),
  CountryLocalization("hk", "lea fakasiaina", "Hongi Kongi SAR Siaina"),
  CountryLocalization("hu", "lea fakahungakalia", "Hungakalia"),
  CountryLocalization("is", "lea fakaʻaisilani", "ʻAisilani"),
  CountryLocalization("in", "lea fakanepali", "ʻInitia"),
  CountryLocalization("id", "Indonesian", "ʻInitonēsia"),
  CountryLocalization("ir", "lea fakapēsia", "ʻIlaani"),
  CountryLocalization("iq", "lea fakaluli-tokelau", "ʻIlaaki"),
  CountryLocalization("ie", "lea fakapālangi", "ʻAealani"),
  CountryLocalization("im", "lea fakamangikī", "Motu Mani"),
  CountryLocalization("il", "lea fakapālangi", "ʻIsileli"),
  CountryLocalization("it", "lea fakasiamane", "ʻĪtali"),
  CountryLocalization("jm", "lea fakapālangi", "Samaika"),
  CountryLocalization("jp", "lea fakasiapani", "Siapani"),
  CountryLocalization("je", "lea fakapālangi", "Selusī"),
  CountryLocalization("jo", "lea fakaʻalepea", "Soatane"),
  CountryLocalization("kz", "lea fakakasaki", "Kasakitani"),
  CountryLocalization("ke", "lea fakasomali", "Keniā"),
  CountryLocalization("ki", "lea fakapālangi", "Kilipasi"),
  CountryLocalization("xk", "lea fakasēpia", "Kōsovo"),
  CountryLocalization("kw", "lea fakaʻalepea", "Kueiti"),
  CountryLocalization("kg", "lea fakalūsia", "Kīkisitani"),
  CountryLocalization("la", "lea fakalau", "Lau"),
  CountryLocalization("lv", "lea fakalativia", "Lativia"),
  CountryLocalization("lb", "lea fakaʻalepea", "Lepanoni"),
  CountryLocalization("ls", "lea fakapālangi", "Lesoto"),
  CountryLocalization("lr", "lea fakapālangi", "Laipelia"),
  CountryLocalization("ly", "lea fakaʻalepea", "Līpia"),
  CountryLocalization("li", "lea fakasiamane-suisilani", "Likitenisiteini"),
  CountryLocalization("lt", "lea fakalituania", "Lituania"),
  CountryLocalization("lu", "lea fakalakisimipeki", "Lakisimipeki"),
  CountryLocalization("mo", "lea fakapotukali", "Makau SAR Siaina"),
  CountryLocalization("mk", "lea fakaʻalapēnia", "Masetōnia"),
  CountryLocalization("mg", "lea fakafalanisē", "Matakasika"),
  CountryLocalization("mw", "lea fakapālangi", "Malaui"),
  CountryLocalization("my", "lea fakatamili", "Malēsia"),
  CountryLocalization("ml", "lea fakafalanisē", "Māli"),
  CountryLocalization("mt", "lea fakapālangi", "Malita"),
  CountryLocalization("mh", "lea fakapālangi", "ʻOtumotu Māsolo"),
  CountryLocalization("mq", "lea fakafalanisē", "Mātiniki"),
  CountryLocalization("mr", "lea fakaʻalepea", "Maulitenia"),
  CountryLocalization("mu", "lea fakamolisieni", "Maulitiusi"),
  CountryLocalization("yt", "lea fakafalanisē", "Maiote"),
  CountryLocalization("mx", "lea fakasipēnisi", "Mekisikou"),
  CountryLocalization("fm", "lea fakapālangi", "Mikolonīsia"),
  CountryLocalization("md", "lea fakalūsia", "Molotova"),
  CountryLocalization("mc", "lea fakafalanisē", "Monako"),
  CountryLocalization("mn", "lea fakamongokōlia", "Mongokōlia"),
  CountryLocalization("me", "lea fakasēpia", "Monitenikalo"),
  CountryLocalization("ms", "lea fakapālangi", "Moʻungaselati"),
  CountryLocalization("ma", "lea fakatamasaiti-ʻatilasi-loloto", "Moloko"),
  CountryLocalization("mz", "lea fakamakūa-meʻeto", "Mosēmipiki"),
  CountryLocalization("mm", "lea fakapema", "Pema"),
  CountryLocalization("na", "lea fakapālangi", "Namipia"),
  CountryLocalization("nr", "lea fakapālangi", "Naulu"),
  CountryLocalization("np", "lea fakanepali", "Nepali"),
  CountryLocalization("nl", "lea fakapālangi", "Hōlani"),
  CountryLocalization("nc", "lea fakafalanisē", "Niu Kaletōnia"),
  CountryLocalization("nz", "lea fakapālangi", "Nuʻusila"),
  CountryLocalization("ni", "lea fakasipēnisi", "Nikalakua"),
  CountryLocalization("ne", "lea fakahausa", "Nisia"),
  CountryLocalization("ng", "lea fakahausa", "Naisilia"),
  CountryLocalization("nu", "lea fakapālangi", "Niuē"),
  CountryLocalization("nf", "lea fakapālangi", "Motu Nōfoliki"),
  CountryLocalization("kp", "lea fakakōlea", "Kōlea tokelau"),
  CountryLocalization("mp", "lea fakapālangi", "ʻOtumotu Maliana tokelau"),
  CountryLocalization("no", "lea fakasami-tokelau", "Noauē"),
  CountryLocalization("om", "lea fakaʻalepea", "ʻOmani"),
  CountryLocalization("pk", "lea fakapālangi", "Pākisitani"),
  CountryLocalization("pw", "lea fakapālangi", "Palau"),
  CountryLocalization("ps", "lea fakaʻalepea", "Potu Palesitaine"),
  CountryLocalization("pa", "lea fakasipēnisi", "Panamā"),
  CountryLocalization("pg", "lea fakapālangi", "Papuaniukini"),
  CountryLocalization("py", "lea fakasipēnisi", "Palakuai"),
  CountryLocalization("pe", "lea fakasipēnisi", "Pelū"),
  CountryLocalization("ph", "lea fakafilipaini", "Filipaini"),
  CountryLocalization("pn", "lea fakapālangi", "ʻOtumotu Pitikeni"),
  CountryLocalization("pl", "lea fakapolani", "Polani"),
  CountryLocalization("pt", "lea fakapotukali", "Potukali"),
  CountryLocalization("pr", "lea fakapālangi", "Puēto Liko"),
  CountryLocalization("qa", "lea fakaʻalepea", "Katā"),
  CountryLocalization("ro", "lea fakalōmenia", "Lomēnia"),
  CountryLocalization("ru", "lea fakatatale", "Lūsia"),
  CountryLocalization("rw", "lea fakapālangi", "Luanitā"),
  CountryLocalization("re", "lea fakafalanisē", "Lēunioni"),
  CountryLocalization("ws", "lea fakapālangi", "Haʻamoa"),
  CountryLocalization("sm", "lea fakaʻītali", "Sā Malino"),
  CountryLocalization("sa", "lea fakaʻalepea", "Saute ʻAlepea"),
  CountryLocalization("sn", "lea fakafalanisē", "Senekalo"),
  CountryLocalization("rs", "lea fakasēpia", "Sēpia"),
  CountryLocalization("cs", "lea fakasēpia", "Serbia and Montenegro"),
  CountryLocalization("sc", "lea fakafalanisē", "ʻOtumotu Seiseli"),
  CountryLocalization("sl", "lea fakapālangi", "Siela Leone"),
  CountryLocalization("sg", "lea fakatamili", "Singapoa"),
  CountryLocalization("sx", "lea fakapālangi", "Sā Mātini (fakahōlani)"),
  CountryLocalization("sk", "lea fakasolāvaki", "Silōvakia"),
  CountryLocalization("si", "lea fakasolovenia", "Silōvenia"),
  CountryLocalization("sb", "lea fakapālangi", "ʻOtumotu Solomone"),
  CountryLocalization("so", "lea fakaʻalepea", "Sōmalia"),
  CountryLocalization("za", "lea fakapālangi", "ʻAfilika tonga"),
  CountryLocalization("kr", "lea fakakōlea", "Kōlea tonga"),
  CountryLocalization("ss", "lea fakanueli", "Sūtani fakatonga"),
  CountryLocalization("es", "lea fakasipēnisi", "Sipeini"),
  CountryLocalization("lk", "lea fakatamili", "Sīlangikā"),
  CountryLocalization("bl", "lea fakafalanisē", "Sā Patēlemi"),
  CountryLocalization("sh", "lea fakapālangi", "Sā Helena"),
  CountryLocalization("kn", "lea fakapālangi", "Sā Kitisi mo Nevisi"),
  CountryLocalization("lc", "lea fakapālangi", "Sā Lūsia"),
  CountryLocalization("mf", "lea fakafalanisē", "Sā Mātini (fakafalanisē)"),
  CountryLocalization("pm", "lea fakafalanisē", "Sā Piea mo Mikeloni"),
  CountryLocalization("vc", "lea fakapālangi", "Sā Viniseni mo Kulenatini"),
  CountryLocalization("sd", "lea fakaʻalepea", "Sūteni"),
  CountryLocalization("sr", "lea fakahōlani", "Suliname"),
  CountryLocalization("sj", "lea fakanouaē-pokimali", "Sivolopāti mo Sani Maieni"),
  CountryLocalization("sz", "lea fakapālangi", "Suasilani"),
  CountryLocalization("se", "lea fakasuēteni", "Suēteni"),
  CountryLocalization("ch", "lea fakasiamane-suisilani", "Suisilani"),
  CountryLocalization("sy", "lea fakaʻalepea", "Sīlia"),
  CountryLocalization("st", "lea fakapotukali", "Sao Tomē mo Pilinisipe"),
  CountryLocalization("tw", "lea fakasiaina", "Taiuani"),
  CountryLocalization("tj", "lea fakatāsiki", "Tasikitani"),
  CountryLocalization("tz", "lea fakamakōnite", "Tenisānia"),
  CountryLocalization("th", "lea fakatailani", "Tailani"),
  CountryLocalization("tl", "lea fakapotukali", "Timoa hahake"),
  CountryLocalization("tg", "lea fakafalanisē", "Toko"),
  CountryLocalization("tk", "lea fakapālangi", "Tokelau"),
  CountryLocalization("to", "lea fakatonga", "Tonga"),
  CountryLocalization("tt", "lea fakapālangi", "Tilinitati mo Topako"),
  CountryLocalization("tn", "lea fakafalanisē", "Tunīsia"),
  CountryLocalization("tr", "lea fakatoake", "Toake"),
  CountryLocalization("tm", "lea fakatēkimeni", "Tūkimenisitani"),
  CountryLocalization("tc", "lea fakapālangi", "ʻOtumotu Tuki mo Kaikosi"),
  CountryLocalization("tv", "lea fakapālangi", "Tūvalu"),
  CountryLocalization("um", "lea fakapālangi", "ʻOtumotu siʻi ʻo ʻAmelika"),
  CountryLocalization("vi", "lea fakapālangi", "ʻOtumotu Vilikini fakaʻamelika"),
  CountryLocalization("ug", "lea fakasuahili", "ʻIukanitā"),
  CountryLocalization("ua", "lea fakaʻūkalaʻine", "ʻŪkalaʻine"),
  CountryLocalization("ae", "lea fakaʻalepea", "ʻAlepea Fakatahataha"),
  CountryLocalization("gb", "lea fakapālangi", "Pilitānia"),
  CountryLocalization("us", "lea fakalakota", "Puleʻanga fakatahataha ʻAmelika"),
  CountryLocalization("uy", "lea fakasipēnisi", "ʻUlukuai"),
  CountryLocalization("uz", "lea fakaʻusipeki", "ʻUsipekitani"),
  CountryLocalization("vu", "lea fakafalanisē", "Vanuatu"),
  CountryLocalization("va", "lea fakaʻītali", "Kolo Vatikani"),
  CountryLocalization("ve", "lea fakasipēnisi", "Venesuela"),
  CountryLocalization("vn", "lea fakavietinami", "Vietinami"),
  CountryLocalization("wf", "lea fakafalanisē", "ʻUvea mo Futuna"),
  CountryLocalization("eh", "lea fakaʻalepea", "Sahala fakahihifo"),
  CountryLocalization("ye", "lea fakaʻalepea", "Iemeni"),
  CountryLocalization("zm", "lea fakapālangi", "Semipia"),
  CountryLocalization("zw", "lea fakanetepele-tokelau", "Simipapuei"),
  CountryLocalization("ax", "lea fakasuēteni", "ʻOtumotu ʻAlani"),
)
