/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot.atlas.extended

import dev.teogor.xenoglot.atlas.CountryLocalization
import kotlin.collections.List

/**
 * Holds the internal list of country-language mappings used for lookups within the package for
 * language code tg.
 *
 * This property contains a hardcoded list of [CountryLocalization] objects, each representing
 * a country and its associated official languages. This list is used by [CountryLanguageRegistry]
 * to provide access to country-language data and should not be modified directly.
 *
 * @see CountryLocalization
 * @see CountryLanguageRegistry
 */
internal val _countryLanguageMappings_tg: List<CountryLocalization> = listOf(
  CountryLocalization("af", "форсӣ", "Афғонистон"),
  CountryLocalization("al", "албанӣ", "Албания"),
  CountryLocalization("dz", "франсузӣ", "Алҷазоир"),
  CountryLocalization("as", "англисӣ", "Самоаи Америка"),
  CountryLocalization("ad", "каталонӣ", "Андорра"),
  CountryLocalization("ao", "Lingala", "Ангола"),
  CountryLocalization("ai", "англисӣ", "Ангилия"),
  CountryLocalization("ag", "англисӣ", "Антигуа ва Барбуда"),
  CountryLocalization("ar", "испанӣ", "Аргентина"),
  CountryLocalization("am", "арманӣ", "Арманистон"),
  CountryLocalization("aw", "голландӣ", "Аруба"),
  CountryLocalization("au", "англисӣ", "Австралия"),
  CountryLocalization("at", "англисӣ", "Австрия"),
  CountryLocalization("az", "озарбойҷонӣ", "Озарбойҷон"),
  CountryLocalization("bs", "англисӣ", "Багам"),
  CountryLocalization("bh", "арабӣ", "Баҳрайн"),
  CountryLocalization("bd", "бинғолӣ", "Бангладеш"),
  CountryLocalization("bb", "англисӣ", "Барбадос"),
  CountryLocalization("by", "белорусӣ", "Белорус"),
  CountryLocalization("be", "франсузӣ", "Белгия"),
  CountryLocalization("bz", "англисӣ", "Белиз"),
  CountryLocalization("bj", "франсузӣ", "Бенин"),
  CountryLocalization("bm", "англисӣ", "Бермуда"),
  CountryLocalization("bt", "дзонгха", "Бутон"),
  CountryLocalization("bo", "испанӣ", "Боливия"),
  CountryLocalization("ba", "босниягӣ", "Босния ва Ҳерсеговина"),
  CountryLocalization("bw", "англисӣ", "Ботсвана"),
  CountryLocalization("br", "португалӣ", "Бразилия"),
  CountryLocalization("io", "англисӣ", "Қаламрави Британия дар уқёнуси Ҳинд"),
  CountryLocalization("vg", "англисӣ", "Ҷазираҳои Виргини Британия"),
  CountryLocalization("bn", "малайӣ", "Бруней"),
  CountryLocalization("bg", "булғорӣ", "Булғория"),
  CountryLocalization("bf", "франсузӣ", "Буркина-Фасо"),
  CountryLocalization("bi", "франсузӣ", "Бурунди"),
  CountryLocalization("kh", "кхмерӣ", "Камбоҷа"),
  CountryLocalization("cm", "Basaa", "Камерун"),
  CountryLocalization("ca", "франсузӣ", "Канада"),
  CountryLocalization("ic", "испанӣ", "IC"),
  CountryLocalization("cv", "kea", "Кабо-Верде"),
  CountryLocalization("bq", "голландӣ", "Caribbean Netherlands"),
  CountryLocalization("ky", "англисӣ", "Ҷазираҳои Кайман"),
  CountryLocalization("cf", "Lingala", "Ҷумҳурии Африқои Марказӣ"),
  CountryLocalization("ea", "испанӣ", "EA"),
  CountryLocalization("td", "арабӣ", "Чад"),
  CountryLocalization("cl", "испанӣ", "Чили"),
  CountryLocalization("cn", "тибетӣ", "Хитой"),
  CountryLocalization("cx", "англисӣ", "Ҷазираи Крисмас"),
  CountryLocalization("cc", "англисӣ", "Ҷазираҳои Кокос (Килинг)"),
  CountryLocalization("co", "испанӣ", "Колумбия"),
  CountryLocalization("km", "арабӣ", "Комор"),
  CountryLocalization("cg", "Lingala", "Congo - Brazzaville"),
  CountryLocalization("cd", "Swahili", "Congo - Kinshasa"),
  CountryLocalization("ck", "англисӣ", "Ҷазираҳои Кук"),
  CountryLocalization("cr", "испанӣ", "Коста-Рика"),
  CountryLocalization("hr", "хорватӣ", "Хорватия"),
  CountryLocalization("cu", "испанӣ", "Куба"),
  CountryLocalization("cw", "голландӣ", "Кюрасао"),
  CountryLocalization("cy", "англисӣ", "Кипр"),
  CountryLocalization("cz", "чехӣ", "Ҷумҳурии Чех"),
  CountryLocalization("ci", "франсузӣ", "Кот-д’Ивуар"),
  CountryLocalization("dk", "англисӣ", "Дания"),
  CountryLocalization("dg", "англисӣ", "DG"),
  CountryLocalization("dj", "франсузӣ", "Ҷибути"),
  CountryLocalization("dm", "англисӣ", "Доминика"),
  CountryLocalization("do", "испанӣ", "Ҷумҳурии Доминикан"),
  CountryLocalization("ec", "кечуа", "Эквадор"),
  CountryLocalization("eg", "арабӣ", "Миср"),
  CountryLocalization("sv", "испанӣ", "Эл-Салвадор"),
  CountryLocalization("gq", "испанӣ", "Гвинеяи Экваторӣ"),
  CountryLocalization("er", "тигриня", "Эритрея"),
  CountryLocalization("ee", "эстонӣ", "Эстония"),
  CountryLocalization("et", "амҳарӣ", "Эфиопия"),
  CountryLocalization("fk", "англисӣ", "Ҷазираҳои Фолкленд"),
  CountryLocalization("fo", "фарерӣ", "Ҷазираҳои Фарер"),
  CountryLocalization("fj", "англисӣ", "Фиҷи"),
  CountryLocalization("fi", "шведӣ", "Финляндия"),
  CountryLocalization("fr", "Swiss German", "Франсия"),
  CountryLocalization("gf", "франсузӣ", "Гвианаи Фаронса"),
  CountryLocalization("pf", "франсузӣ", "Полинезияи Фаронса"),
  CountryLocalization("ga", "франсузӣ", "Габон"),
  CountryLocalization("gm", "англисӣ", "Гамбия"),
  CountryLocalization("ge", "Ossetic", "Гурҷистон"),
  CountryLocalization("de", "сербии поёнӣ", "Германия"),
  CountryLocalization("gh", "англисӣ", "Гана"),
  CountryLocalization("gi", "англисӣ", "Гибралтар"),
  CountryLocalization("gr", "юнонӣ", "Юнон"),
  CountryLocalization("gl", "Kalaallisut", "Гренландия"),
  CountryLocalization("gd", "англисӣ", "Гренада"),
  CountryLocalization("gp", "франсузӣ", "Гваделупа"),
  CountryLocalization("gu", "англисӣ", "Гуам"),
  CountryLocalization("gt", "испанӣ", "Гватемала"),
  CountryLocalization("gg", "англисӣ", "Гернси"),
  CountryLocalization("gn", "франсузӣ", "Гвинея"),
  CountryLocalization("gw", "португалӣ", "Гвинея-Бисау"),
  CountryLocalization("gy", "англисӣ", "Гайана"),
  CountryLocalization("ht", "франсузӣ", "Гаити"),
  CountryLocalization("hn", "испанӣ", "Гондурас"),
  CountryLocalization("hk", "хитоӣ", "Ҳонконг (МММ)"),
  CountryLocalization("hu", "маҷорӣ", "Маҷористон"),
  CountryLocalization("is", "исландӣ", "Исландия"),
  CountryLocalization("in", "непалӣ", "Ҳиндустон"),
  CountryLocalization("id", "Indonesian", "Индонезия"),
  CountryLocalization("ir", "форсӣ", "Эрон"),
  CountryLocalization("iq", "lrc", "Ироқ"),
  CountryLocalization("ie", "англисӣ", "Ирландия"),
  CountryLocalization("im", "Manx", "Ҷазираи Мэн"),
  CountryLocalization("il", "англисӣ", "Исроил"),
  CountryLocalization("it", "немисӣ", "Италия"),
  CountryLocalization("jm", "англисӣ", "Ямайка"),
  CountryLocalization("jp", "японӣ", "Япония"),
  CountryLocalization("je", "англисӣ", "Ҷерси"),
  CountryLocalization("jo", "арабӣ", "Урдун"),
  CountryLocalization("kz", "қазоқӣ", "Қазоқистон"),
  CountryLocalization("ke", "сомалӣ", "Кения"),
  CountryLocalization("ki", "англисӣ", "Кирибати"),
  CountryLocalization("xk", "сербӣ", "Косово"),
  CountryLocalization("kw", "арабӣ", "Қувайт"),
  CountryLocalization("kg", "русӣ", "Қирғизистон"),
  CountryLocalization("la", "лаосӣ", "Лаос"),
  CountryLocalization("lv", "латишӣ", "Латвия"),
  CountryLocalization("lb", "арабӣ", "Лубнон"),
  CountryLocalization("ls", "англисӣ", "Лесото"),
  CountryLocalization("lr", "англисӣ", "Либерия"),
  CountryLocalization("ly", "арабӣ", "Либия"),
  CountryLocalization("li", "Swiss German", "Лихтенштейн"),
  CountryLocalization("lt", "литвонӣ", "Литва"),
  CountryLocalization("lu", "люксембургӣ", "Люксембург"),
  CountryLocalization("mo", "португалӣ", "Макао (МММ)"),
  CountryLocalization("mk", "албанӣ", "Мақдун"),
  CountryLocalization("mg", "франсузӣ", "Мадагаскар"),
  CountryLocalization("mw", "англисӣ", "Малави"),
  CountryLocalization("my", "тамилӣ", "Малайзия"),
  CountryLocalization("ml", "франсузӣ", "Мали"),
  CountryLocalization("mt", "англисӣ", "Малта"),
  CountryLocalization("mh", "англисӣ", "Ҷазираҳои Маршалл"),
  CountryLocalization("mq", "франсузӣ", "Мартиника"),
  CountryLocalization("mr", "арабӣ", "Мавритания"),
  CountryLocalization("mu", "mfe", "Маврикий"),
  CountryLocalization("yt", "франсузӣ", "Майотта"),
  CountryLocalization("mx", "испанӣ", "Мексика"),
  CountryLocalization("fm", "англисӣ", "Штатҳои Федеративии Микронезия"),
  CountryLocalization("md", "русӣ", "Молдова"),
  CountryLocalization("mc", "франсузӣ", "Монако"),
  CountryLocalization("mn", "муғулӣ", "Муғулистон"),
  CountryLocalization("me", "сербӣ", "Черногория"),
  CountryLocalization("ms", "англисӣ", "Монтсеррат"),
  CountryLocalization("ma", "тамазайти атласи марказӣ", "Марокаш"),
  CountryLocalization("mz", "mgh", "Мозамбик"),
  CountryLocalization("mm", "бирманӣ", "Мянма"),
  CountryLocalization("na", "англисӣ", "Намибия"),
  CountryLocalization("nr", "англисӣ", "Науру"),
  CountryLocalization("np", "непалӣ", "Непал"),
  CountryLocalization("nl", "англисӣ", "Нидерландия"),
  CountryLocalization("nc", "франсузӣ", "Каледонияи Нав"),
  CountryLocalization("nz", "англисӣ", "Зеландияи Нав"),
  CountryLocalization("ni", "испанӣ", "Никарагуа"),
  CountryLocalization("ne", "ҳауса", "Нигер"),
  CountryLocalization("ng", "ҳауса", "Нигерия"),
  CountryLocalization("nu", "англисӣ", "Ниуэ"),
  CountryLocalization("nf", "англисӣ", "Ҷазираи Норфолк"),
  CountryLocalization("kp", "кореягӣ", "Кореяи Шимолӣ"),
  CountryLocalization("mp", "англисӣ", "Ҷазираҳои Марианаи Шимолӣ"),
  CountryLocalization("no", "самии шимолӣ", "Норвегия"),
  CountryLocalization("om", "арабӣ", "Умон"),
  CountryLocalization("pk", "англисӣ", "Покистон"),
  CountryLocalization("pw", "англисӣ", "Палау"),
  CountryLocalization("ps", "арабӣ", "Palestinian Territories"),
  CountryLocalization("pa", "испанӣ", "Панама"),
  CountryLocalization("pg", "англисӣ", "Папуа Гвинеяи Нав"),
  CountryLocalization("py", "испанӣ", "Парагвай"),
  CountryLocalization("pe", "испанӣ", "Перу"),
  CountryLocalization("ph", "филиппинӣ", "Филиппин"),
  CountryLocalization("pn", "англисӣ", "Ҷазираҳои Питкейрн"),
  CountryLocalization("pl", "лаҳистонӣ", "Лаҳистон"),
  CountryLocalization("pt", "португалӣ", "Португалия"),
  CountryLocalization("pr", "англисӣ", "Пуэрто-Рико"),
  CountryLocalization("qa", "арабӣ", "Қатар"),
  CountryLocalization("ro", "руминӣ", "Руминия"),
  CountryLocalization("ru", "тоторӣ", "Русия"),
  CountryLocalization("rw", "англисӣ", "Руанда"),
  CountryLocalization("re", "франсузӣ", "Реюнион"),
  CountryLocalization("ws", "англисӣ", "Самоа"),
  CountryLocalization("sm", "италиявӣ", "Сан-Марино"),
  CountryLocalization("sa", "арабӣ", "Арабистони Саудӣ"),
  CountryLocalization("sn", "франсузӣ", "Сенегал"),
  CountryLocalization("rs", "сербӣ", "Сербия"),
  CountryLocalization("cs", "сербӣ", "Serbia and Montenegro"),
  CountryLocalization("sc", "франсузӣ", "Сейшел"),
  CountryLocalization("sl", "англисӣ", "Сиерра-Леоне"),
  CountryLocalization("sg", "тамилӣ", "Сингапур"),
  CountryLocalization("sx", "англисӣ", "Синт-Маартен"),
  CountryLocalization("sk", "словакӣ", "Словакия"),
  CountryLocalization("si", "словенӣ", "Словения"),
  CountryLocalization("sb", "англисӣ", "Ҷазираҳои Соломон"),
  CountryLocalization("so", "арабӣ", "Сомалӣ"),
  CountryLocalization("za", "англисӣ", "Африкаи Ҷанубӣ"),
  CountryLocalization("kr", "кореягӣ", "South Korea"),
  CountryLocalization("ss", "nus", "Судони Ҷанубӣ"),
  CountryLocalization("es", "испанӣ", "Испания"),
  CountryLocalization("lk", "тамилӣ", "Шри-Ланка"),
  CountryLocalization("bl", "франсузӣ", "Сент-Бартелми"),
  CountryLocalization("sh", "англисӣ", "Сент Елена"),
  CountryLocalization("kn", "англисӣ", "Сент-Китс ва Невис"),
  CountryLocalization("lc", "англисӣ", "Сент-Люсия"),
  CountryLocalization("mf", "франсузӣ", "Ҷазираи Сент-Мартин"),
  CountryLocalization("pm", "франсузӣ", "Сент-Пер ва Микелон"),
  CountryLocalization("vc", "англисӣ", "Сент-Винсент ва Гренадина"),
  CountryLocalization("sd", "арабӣ", "Судон"),
  CountryLocalization("sr", "голландӣ", "Суринам"),
  CountryLocalization("sj", "Norwegian Bokmål", "Шпитсберген ва Ян Майен"),
  CountryLocalization("sz", "англисӣ", "Свазиленд"),
  CountryLocalization("se", "шведӣ", "Шветсия"),
  CountryLocalization("ch", "Swiss German", "Швейтсария"),
  CountryLocalization("sy", "арабӣ", "Сурия"),
  CountryLocalization("st", "португалӣ", "Сан Томе ва Принсипи"),
  CountryLocalization("tw", "хитоӣ", "Тайван"),
  CountryLocalization("tj", "тоҷикӣ", "Тоҷикистон"),
  CountryLocalization("tz", "kde", "Танзания"),
  CountryLocalization("th", "тайӣ", "Таиланд"),
  CountryLocalization("tl", "португалӣ", "Тимор-Лесте"),
  CountryLocalization("tg", "франсузӣ", "Того"),
  CountryLocalization("tk", "англисӣ", "Токелау"),
  CountryLocalization("to", "тонганӣ", "Тонга"),
  CountryLocalization("tt", "англисӣ", "Тринидад ва Тобаго"),
  CountryLocalization("tn", "франсузӣ", "Тунис"),
  CountryLocalization("tr", "туркӣ", "Туркия"),
  CountryLocalization("tm", "туркманӣ", "Туркманистон"),
  CountryLocalization("tc", "англисӣ", "Ҷазираҳои Теркс ва Кайкос"),
  CountryLocalization("tv", "англисӣ", "Тувалу"),
  CountryLocalization("um", "англисӣ", "Ҷазираҳои Хурди Дурдасти ИМА"),
  CountryLocalization("vi", "англисӣ", "Ҷазираҳои Виргини ИМА"),
  CountryLocalization("ug", "Swahili", "Уганда"),
  CountryLocalization("ua", "украинӣ", "Украина"),
  CountryLocalization("ae", "арабӣ", "Аморатҳои Муттаҳидаи Араб"),
  CountryLocalization("gb", "англисӣ", "Шоҳигарии Муттаҳида"),
  CountryLocalization("us", "lkt", "Иёлоти Муттаҳида"),
  CountryLocalization("uy", "испанӣ", "Уругвай"),
  CountryLocalization("uz", "ӯзбекӣ", "Ӯзбекистон"),
  CountryLocalization("vu", "франсузӣ", "Вануату"),
  CountryLocalization("va", "италиявӣ", "Шаҳри Вотикон"),
  CountryLocalization("ve", "испанӣ", "Венесуэла"),
  CountryLocalization("vn", "ветнамӣ", "Ветнам"),
  CountryLocalization("wf", "франсузӣ", "Уоллис ва Футуна"),
  CountryLocalization("eh", "арабӣ", "Western Sahara"),
  CountryLocalization("ye", "арабӣ", "Яман"),
  CountryLocalization("zm", "англисӣ", "Замбия"),
  CountryLocalization("zw", "North Ndebele", "Зимбабве"),
  CountryLocalization("ax", "шведӣ", "Ҷазираҳои Аланд"),
)
