/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot.atlas.extended

import dev.teogor.xenoglot.atlas.CountryLocalization
import kotlin.collections.List

/**
 * Holds the internal list of country-language mappings used for lookups within the package for
 * language code lt.
 *
 * This property contains a hardcoded list of [CountryLocalization] objects, each representing
 * a country and its associated official languages. This list is used by [CountryLanguageRegistry]
 * to provide access to country-language data and should not be modified directly.
 *
 * @see CountryLocalization
 * @see CountryLanguageRegistry
 */
internal val _countryLanguageMappings_lt: List<CountryLocalization> = listOf(
  CountryLocalization("af", "persų", "Afganistanas"),
  CountryLocalization("al", "albanų", "Albanija"),
  CountryLocalization("dz", "prancūzų", "Alžyras"),
  CountryLocalization("as", "anglų", "Amerikos Samoa"),
  CountryLocalization("ad", "katalonų", "Andora"),
  CountryLocalization("ao", "ngalų", "Angola"),
  CountryLocalization("ai", "anglų", "Angilija"),
  CountryLocalization("ag", "anglų", "Antigva ir Barbuda"),
  CountryLocalization("ar", "ispanų", "Argentina"),
  CountryLocalization("am", "armėnų", "Armėnija"),
  CountryLocalization("aw", "olandų", "Aruba"),
  CountryLocalization("au", "anglų", "Australija"),
  CountryLocalization("at", "anglų", "Austrija"),
  CountryLocalization("az", "azerbaidžaniečių", "Azerbaidžanas"),
  CountryLocalization("bs", "anglų", "Bahamos"),
  CountryLocalization("bh", "arabų", "Bahreinas"),
  CountryLocalization("bd", "bengalų", "Bangladešas"),
  CountryLocalization("bb", "anglų", "Barbadosas"),
  CountryLocalization("by", "baltarusių", "Baltarusija"),
  CountryLocalization("be", "prancūzų", "Belgija"),
  CountryLocalization("bz", "anglų", "Belizas"),
  CountryLocalization("bj", "prancūzų", "Beninas"),
  CountryLocalization("bm", "anglų", "Bermuda"),
  CountryLocalization("bt", "botijų", "Butanas"),
  CountryLocalization("bo", "ispanų", "Bolivija"),
  CountryLocalization("ba", "bosnių", "Bosnija ir Hercegovina"),
  CountryLocalization("bw", "anglų", "Botsvana"),
  CountryLocalization("br", "portugalų", "Brazilija"),
  CountryLocalization("io", "anglų", "Indijos Vandenyno Britų Sritis"),
  CountryLocalization("vg", "anglų", "Didžiosios Britanijos Mergelių Salos"),
  CountryLocalization("bn", "malajiečių", "Brunėjus"),
  CountryLocalization("bg", "bulgarų", "Bulgarija"),
  CountryLocalization("bf", "prancūzų", "Burkina Fasas"),
  CountryLocalization("bi", "prancūzų", "Burundis"),
  CountryLocalization("kh", "khmerų", "Kambodža"),
  CountryLocalization("cm", "basų", "Kamerūnas"),
  CountryLocalization("ca", "prancūzų", "Kanada"),
  CountryLocalization("ic", "ispanų", "Kanarų salos"),
  CountryLocalization("cv", "Žaliojo Kyšulio kreolų", "Žaliasis Kyšulys"),
  CountryLocalization("bq", "olandų", "Karibų Nyderlandai"),
  CountryLocalization("ky", "anglų", "Kaimanų Salos"),
  CountryLocalization("cf", "ngalų", "Centrinės Afrikos Respublika"),
  CountryLocalization("ea", "ispanų", "Seuta ir Melila"),
  CountryLocalization("td", "arabų", "Čadas"),
  CountryLocalization("cl", "ispanų", "Čilė"),
  CountryLocalization("cn", "tibetiečių", "Kinija"),
  CountryLocalization("cx", "anglų", "Kalėdų Sala"),
  CountryLocalization("cc", "anglų", "Kokosų (Kilingo) Salos"),
  CountryLocalization("co", "ispanų", "Kolumbija"),
  CountryLocalization("km", "arabų", "Komorai"),
  CountryLocalization("cg", "ngalų", "Kongas-Brazavilis"),
  CountryLocalization("cd", "suahilių", "Kongas-Kinšasa"),
  CountryLocalization("ck", "anglų", "Kuko Salos"),
  CountryLocalization("cr", "ispanų", "Kosta Rika"),
  CountryLocalization("hr", "kroatų", "Kroatija"),
  CountryLocalization("cu", "ispanų", "Kuba"),
  CountryLocalization("cw", "olandų", "Kiurasao"),
  CountryLocalization("cy", "anglų", "Kipras"),
  CountryLocalization("cz", "čekų", "Čekija"),
  CountryLocalization("ci", "prancūzų", "Dramblio Kaulo Krantas"),
  CountryLocalization("dk", "anglų", "Danija"),
  CountryLocalization("dg", "anglų", "Diego Garsija"),
  CountryLocalization("dj", "prancūzų", "Džibutis"),
  CountryLocalization("dm", "anglų", "Dominika"),
  CountryLocalization("do", "ispanų", "Dominikos Respublika"),
  CountryLocalization("ec", "kečujų", "Ekvadoras"),
  CountryLocalization("eg", "arabų", "Egiptas"),
  CountryLocalization("sv", "ispanų", "Salvadoras"),
  CountryLocalization("gq", "ispanų", "Pusiaujo Gvinėja"),
  CountryLocalization("er", "tigrajų", "Eritrėja"),
  CountryLocalization("ee", "estų", "Estija"),
  CountryLocalization("et", "amharų", "Etiopija"),
  CountryLocalization("fk", "anglų", "Folklando Salos"),
  CountryLocalization("fo", "farerų", "Farerų Salos"),
  CountryLocalization("fj", "anglų", "Fidžis"),
  CountryLocalization("fi", "švedų", "Suomija"),
  CountryLocalization("fr", "Šveicarijos vokiečių", "Prancūzija"),
  CountryLocalization("gf", "prancūzų", "Prancūzijos Gviana"),
  CountryLocalization("pf", "prancūzų", "Prancūzijos Polinezija"),
  CountryLocalization("ga", "prancūzų", "Gabonas"),
  CountryLocalization("gm", "anglų", "Gambija"),
  CountryLocalization("ge", "osetinų", "Gruzija"),
  CountryLocalization("de", "žemutinių sorbų", "Vokietija"),
  CountryLocalization("gh", "anglų", "Gana"),
  CountryLocalization("gi", "anglų", "Gibraltaras"),
  CountryLocalization("gr", "graikų", "Graikija"),
  CountryLocalization("gl", "kalalisut", "Grenlandija"),
  CountryLocalization("gd", "anglų", "Grenada"),
  CountryLocalization("gp", "prancūzų", "Gvadelupa"),
  CountryLocalization("gu", "anglų", "Guamas"),
  CountryLocalization("gt", "ispanų", "Gvatemala"),
  CountryLocalization("gg", "anglų", "Gernsis"),
  CountryLocalization("gn", "prancūzų", "Gvinėja"),
  CountryLocalization("gw", "portugalų", "Bisau Gvinėja"),
  CountryLocalization("gy", "anglų", "Gajana"),
  CountryLocalization("ht", "prancūzų", "Haitis"),
  CountryLocalization("hn", "ispanų", "Hondūras"),
  CountryLocalization("hk", "kinų", "Ypatingasis Administracinis Kinijos Regionas Honkongas"),
  CountryLocalization("hu", "vengrų", "Vengrija"),
  CountryLocalization("is", "islandų", "Islandija"),
  CountryLocalization("in", "nepaliečių", "Indija"),
  CountryLocalization("id", "Indonesian", "Indonezija"),
  CountryLocalization("ir", "persų", "Iranas"),
  CountryLocalization("iq", "šiaurės luri", "Irakas"),
  CountryLocalization("ie", "anglų", "Airija"),
  CountryLocalization("im", "meniečių", "Meno Sala"),
  CountryLocalization("il", "anglų", "Izraelis"),
  CountryLocalization("it", "vokiečių", "Italija"),
  CountryLocalization("jm", "anglų", "Jamaika"),
  CountryLocalization("jp", "japonų", "Japonija"),
  CountryLocalization("je", "anglų", "Džersis"),
  CountryLocalization("jo", "arabų", "Jordanija"),
  CountryLocalization("kz", "kazachų", "Kazachstanas"),
  CountryLocalization("ke", "somaliečių", "Kenija"),
  CountryLocalization("ki", "anglų", "Kiribatis"),
  CountryLocalization("xk", "serbų", "Kosovas"),
  CountryLocalization("kw", "arabų", "Kuveitas"),
  CountryLocalization("kg", "rusų", "Kirgizija"),
  CountryLocalization("la", "laosiečių", "Laosas"),
  CountryLocalization("lv", "latvių", "Latvija"),
  CountryLocalization("lb", "arabų", "Libanas"),
  CountryLocalization("ls", "anglų", "Lesotas"),
  CountryLocalization("lr", "anglų", "Liberija"),
  CountryLocalization("ly", "arabų", "Libija"),
  CountryLocalization("li", "Šveicarijos vokiečių", "Lichtenšteinas"),
  CountryLocalization("lt", "lietuvių", "Lietuva"),
  CountryLocalization("lu", "liuksemburgiečių", "Liuksemburgas"),
  CountryLocalization("mo", "portugalų", "Ypatingasis Administracinis Kinijos Regionas Makao"),
  CountryLocalization("mk", "albanų", "Makedonija"),
  CountryLocalization("mg", "prancūzų", "Madagaskaras"),
  CountryLocalization("mw", "anglų", "Malavis"),
  CountryLocalization("my", "tamilų", "Malaizija"),
  CountryLocalization("ml", "prancūzų", "Malis"),
  CountryLocalization("mt", "anglų", "Malta"),
  CountryLocalization("mh", "anglų", "Maršalo Salos"),
  CountryLocalization("mq", "prancūzų", "Martinika"),
  CountryLocalization("mr", "arabų", "Mauritanija"),
  CountryLocalization("mu", "morisijų", "Mauricijus"),
  CountryLocalization("yt", "prancūzų", "Majotas"),
  CountryLocalization("mx", "ispanų", "Meksika"),
  CountryLocalization("fm", "anglų", "Mikronezija"),
  CountryLocalization("md", "rusų", "Moldova"),
  CountryLocalization("mc", "prancūzų", "Monakas"),
  CountryLocalization("mn", "mongolų", "Mongolija"),
  CountryLocalization("me", "serbų", "Juodkalnija"),
  CountryLocalization("ms", "anglų", "Montseratas"),
  CountryLocalization("ma", "Centrinio Maroko tamazitų", "Marokas"),
  CountryLocalization("mz", "makua-maeto", "Mozambikas"),
  CountryLocalization("mm", "birmiečių", "Mianmaras (Birma)"),
  CountryLocalization("na", "anglų", "Namibija"),
  CountryLocalization("nr", "anglų", "Nauru"),
  CountryLocalization("np", "nepaliečių", "Nepalas"),
  CountryLocalization("nl", "anglų", "Nyderlandai"),
  CountryLocalization("nc", "prancūzų", "Naujoji Kaledonija"),
  CountryLocalization("nz", "anglų", "Naujoji Zelandija"),
  CountryLocalization("ni", "ispanų", "Nikaragva"),
  CountryLocalization("ne", "hausų", "Nigeris"),
  CountryLocalization("ng", "hausų", "Nigerija"),
  CountryLocalization("nu", "anglų", "Niujė"),
  CountryLocalization("nf", "anglų", "Norfolko sala"),
  CountryLocalization("kp", "korėjiečių", "Šiaurės Korėja"),
  CountryLocalization("mp", "anglų", "Marianos Šiaurinės Salos"),
  CountryLocalization("no", "šiaurės samių", "Norvegija"),
  CountryLocalization("om", "arabų", "Omanas"),
  CountryLocalization("pk", "anglų", "Pakistanas"),
  CountryLocalization("pw", "anglų", "Palau"),
  CountryLocalization("ps", "arabų", "Palestinos teritorija"),
  CountryLocalization("pa", "ispanų", "Panama"),
  CountryLocalization("pg", "anglų", "Papua Naujoji Gvinėja"),
  CountryLocalization("py", "ispanų", "Paragvajus"),
  CountryLocalization("pe", "ispanų", "Peru"),
  CountryLocalization("ph", "filipiniečių", "Filipinai"),
  CountryLocalization("pn", "anglų", "Pitkerno salos"),
  CountryLocalization("pl", "lenkų", "Lenkija"),
  CountryLocalization("pt", "portugalų", "Portugalija"),
  CountryLocalization("pr", "anglų", "Puerto Rikas"),
  CountryLocalization("qa", "arabų", "Kataras"),
  CountryLocalization("ro", "rumunų", "Rumunija"),
  CountryLocalization("ru", "totorių", "Rusija"),
  CountryLocalization("rw", "anglų", "Ruanda"),
  CountryLocalization("re", "prancūzų", "Reunjonas"),
  CountryLocalization("ws", "anglų", "Samoa"),
  CountryLocalization("sm", "italų", "San Marinas"),
  CountryLocalization("sa", "arabų", "Saudo Arabija"),
  CountryLocalization("sn", "prancūzų", "Senegalas"),
  CountryLocalization("rs", "serbų", "Serbija"),
  CountryLocalization("cs", "serbų", "Serbia and Montenegro"),
  CountryLocalization("sc", "prancūzų", "Seišeliai"),
  CountryLocalization("sl", "anglų", "Siera Leonė"),
  CountryLocalization("sg", "tamilų", "Singapūras"),
  CountryLocalization("sx", "anglų", "Sint Martenas"),
  CountryLocalization("sk", "slovakų", "Slovakija"),
  CountryLocalization("si", "slovėnų", "Slovėnija"),
  CountryLocalization("sb", "anglų", "Saliamono Salos"),
  CountryLocalization("so", "arabų", "Somalis"),
  CountryLocalization("za", "anglų", "Pietų Afrika"),
  CountryLocalization("kr", "korėjiečių", "Pietų Korėja"),
  CountryLocalization("ss", "nuerų", "Pietų Sudanas"),
  CountryLocalization("es", "ispanų", "Ispanija"),
  CountryLocalization("lk", "tamilų", "Šri Lanka"),
  CountryLocalization("bl", "prancūzų", "Sen Bartelemi"),
  CountryLocalization("sh", "anglų", "Šv. Elenos Sala"),
  CountryLocalization("kn", "anglų", "Sent Kitsas ir Nevis"),
  CountryLocalization("lc", "anglų", "Sent Lusija"),
  CountryLocalization("mf", "prancūzų", "Sen Martenas"),
  CountryLocalization("pm", "prancūzų", "Sen Pjeras ir Mikelonas"),
  CountryLocalization("vc", "anglų", "Šventasis Vincentas ir Grenadinai"),
  CountryLocalization("sd", "arabų", "Sudanas"),
  CountryLocalization("sr", "olandų", "Surinamas"),
  CountryLocalization("sj", "norvegų bukmolas", "Svalbardas ir Janas Majenas"),
  CountryLocalization("sz", "anglų", "Svazilandas"),
  CountryLocalization("se", "švedų", "Švedija"),
  CountryLocalization("ch", "Šveicarijos vokiečių", "Šveicarija"),
  CountryLocalization("sy", "arabų", "Sirija"),
  CountryLocalization("st", "portugalų", "San Tomė ir Prinsipė"),
  CountryLocalization("tw", "kinų", "Taivanas"),
  CountryLocalization("tj", "tadžikų", "Tadžikija"),
  CountryLocalization("tz", "makondų", "Tanzanija"),
  CountryLocalization("th", "tajų", "Tailandas"),
  CountryLocalization("tl", "portugalų", "Rytų Timoras"),
  CountryLocalization("tg", "prancūzų", "Togas"),
  CountryLocalization("tk", "anglų", "Tokelau"),
  CountryLocalization("to", "tonganų", "Tonga"),
  CountryLocalization("tt", "anglų", "Trinidadas ir Tobagas"),
  CountryLocalization("tn", "prancūzų", "Tunisas"),
  CountryLocalization("tr", "turkų", "Turkija"),
  CountryLocalization("tm", "turkmėnų", "Turkmėnistanas"),
  CountryLocalization("tc", "anglų", "Terkso ir Kaikoso Salos"),
  CountryLocalization("tv", "anglų", "Tuvalu"),
  CountryLocalization("um", "anglų", "Jungtinių Valstijų Mažosios Tolimosios Salos"),
  CountryLocalization("vi", "anglų", "Jungtinių Valstijų Mergelių Salos"),
  CountryLocalization("ug", "suahilių", "Uganda"),
  CountryLocalization("ua", "ukrainiečių", "Ukraina"),
  CountryLocalization("ae", "arabų", "Jungtiniai Arabų Emyratai"),
  CountryLocalization("gb", "anglų", "Jungtinė Karalystė"),
  CountryLocalization("us", "lakotų", "Jungtinės Valstijos"),
  CountryLocalization("uy", "ispanų", "Urugvajus"),
  CountryLocalization("uz", "uzbekų", "Uzbekistanas"),
  CountryLocalization("vu", "prancūzų", "Vanuatu"),
  CountryLocalization("va", "italų", "Vatikano Miesto Valstybė"),
  CountryLocalization("ve", "ispanų", "Venesuela"),
  CountryLocalization("vn", "vietnamiečių", "Vietnamas"),
  CountryLocalization("wf", "prancūzų", "Volisas ir Futūna"),
  CountryLocalization("eh", "arabų", "Vakarų Sachara"),
  CountryLocalization("ye", "arabų", "Jemenas"),
  CountryLocalization("zm", "anglų", "Zambija"),
  CountryLocalization("zw", "šiaurės ndebelų", "Zimbabvė"),
  CountryLocalization("ax", "švedų", "Alandų Salos"),
)
