/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot.atlas.extended

import dev.teogor.xenoglot.atlas.CountryLocalization
import kotlin.collections.List

/**
 * Holds the internal list of country-language mappings used for lookups within the package for
 * language code sk.
 *
 * This property contains a hardcoded list of [CountryLocalization] objects, each representing
 * a country and its associated official languages. This list is used by [CountryLanguageRegistry]
 * to provide access to country-language data and should not be modified directly.
 *
 * @see CountryLocalization
 * @see CountryLanguageRegistry
 */
internal val _countryLanguageMappings_sk: List<CountryLocalization> = listOf(
  CountryLocalization("af", "perzština", "Afganistan"),
  CountryLocalization("al", "albánčina", "Albánsko"),
  CountryLocalization("dz", "francúzština", "Alžírsko"),
  CountryLocalization("as", "angličtina", "Americká Samoa"),
  CountryLocalization("ad", "katalánčina", "Andorra"),
  CountryLocalization("ao", "lingalčina", "Angola"),
  CountryLocalization("ai", "angličtina", "Anguilla"),
  CountryLocalization("ag", "angličtina", "Antigua a Barbuda"),
  CountryLocalization("ar", "španielčina", "Argentína"),
  CountryLocalization("am", "arménčina", "Arménsko"),
  CountryLocalization("aw", "holandčina", "Aruba"),
  CountryLocalization("au", "angličtina", "Austrália"),
  CountryLocalization("at", "angličtina", "Rakúsko"),
  CountryLocalization("az", "azerbajdžančina", "Azerbajdžan"),
  CountryLocalization("bs", "angličtina", "Bahamy"),
  CountryLocalization("bh", "arabčina", "Bahrajn"),
  CountryLocalization("bd", "bengálčina", "Bangladéš"),
  CountryLocalization("bb", "angličtina", "Barbados"),
  CountryLocalization("by", "bieloruština", "Bielorusko"),
  CountryLocalization("be", "francúzština", "Belgicko"),
  CountryLocalization("bz", "angličtina", "Belize"),
  CountryLocalization("bj", "francúzština", "Benin"),
  CountryLocalization("bm", "angličtina", "Bermudy"),
  CountryLocalization("bt", "dzongkha", "Bhután"),
  CountryLocalization("bo", "španielčina", "Bolívia"),
  CountryLocalization("ba", "bosniačtina", "Bosna a Hercegovina"),
  CountryLocalization("bw", "angličtina", "Botswana"),
  CountryLocalization("br", "portugalčina", "Brazília"),
  CountryLocalization("io", "angličtina", "Britské indickooceánske územie"),
  CountryLocalization("vg", "angličtina", "Britské Panenské ostrovy"),
  CountryLocalization("bn", "malajčina", "Brunej"),
  CountryLocalization("bg", "bulharčina", "Bulharsko"),
  CountryLocalization("bf", "francúzština", "Burkina Faso"),
  CountryLocalization("bi", "francúzština", "Burundi"),
  CountryLocalization("kh", "khmérčina", "Kambodža"),
  CountryLocalization("cm", "basa", "Kamerun"),
  CountryLocalization("ca", "francúzština", "Kanada"),
  CountryLocalization("ic", "španielčina", "Kanárske ostrovy"),
  CountryLocalization("cv", "kapverdčina", "Kapverdy"),
  CountryLocalization("bq", "holandčina", "Karibské Holandsko"),
  CountryLocalization("ky", "angličtina", "Kajmanie ostrovy"),
  CountryLocalization("cf", "lingalčina", "Stredoafrická republika"),
  CountryLocalization("ea", "španielčina", "Ceuta a Melilla"),
  CountryLocalization("td", "arabčina", "Čad"),
  CountryLocalization("cl", "španielčina", "Čile"),
  CountryLocalization("cn", "tibetčina", "Čína"),
  CountryLocalization("cx", "angličtina", "Vianočný ostrov"),
  CountryLocalization("cc", "angličtina", "Kokosové ostrovy"),
  CountryLocalization("co", "španielčina", "Kolumbia"),
  CountryLocalization("km", "arabčina", "Komory"),
  CountryLocalization("cg", "lingalčina", "Konžská republika"),
  CountryLocalization("cd", "swahilčina", "Konžská demokratická republika"),
  CountryLocalization("ck", "angličtina", "Cookove ostrovy"),
  CountryLocalization("cr", "španielčina", "Kostarika"),
  CountryLocalization("hr", "chorvátčina", "Chorvátsko"),
  CountryLocalization("cu", "španielčina", "Kuba"),
  CountryLocalization("cw", "holandčina", "Curaçao"),
  CountryLocalization("cy", "angličtina", "Cyprus"),
  CountryLocalization("cz", "čeština", "Česko"),
  CountryLocalization("ci", "francúzština", "Pobrežie Slonoviny"),
  CountryLocalization("dk", "angličtina", "Dánsko"),
  CountryLocalization("dg", "angličtina", "Diego Garcia"),
  CountryLocalization("dj", "francúzština", "Džibutsko"),
  CountryLocalization("dm", "angličtina", "Dominika"),
  CountryLocalization("do", "španielčina", "Dominikánska republika"),
  CountryLocalization("ec", "kečuánčina", "Ekvádor"),
  CountryLocalization("eg", "arabčina", "Egypt"),
  CountryLocalization("sv", "španielčina", "Salvádor"),
  CountryLocalization("gq", "španielčina", "Rovníková Guinea"),
  CountryLocalization("er", "tigriňa", "Eritrea"),
  CountryLocalization("ee", "estónčina", "Estónsko"),
  CountryLocalization("et", "amharčina", "Etiópia"),
  CountryLocalization("fk", "angličtina", "Falklandy"),
  CountryLocalization("fo", "faerčina", "Faerské ostrovy"),
  CountryLocalization("fj", "angličtina", "Fidži"),
  CountryLocalization("fi", "švédčina", "Fínsko"),
  CountryLocalization("fr", "nemčina (švajčiarska)", "Francúzsko"),
  CountryLocalization("gf", "francúzština", "Francúzska Guyana"),
  CountryLocalization("pf", "francúzština", "Francúzska Polynézia"),
  CountryLocalization("ga", "francúzština", "Gabon"),
  CountryLocalization("gm", "angličtina", "Gambia"),
  CountryLocalization("ge", "osetčina", "Gruzínsko"),
  CountryLocalization("de", "dolnolužická srbčina", "Nemecko"),
  CountryLocalization("gh", "angličtina", "Ghana"),
  CountryLocalization("gi", "angličtina", "Gibraltár"),
  CountryLocalization("gr", "gréčtina", "Grécko"),
  CountryLocalization("gl", "grónčina", "Grónsko"),
  CountryLocalization("gd", "angličtina", "Grenada"),
  CountryLocalization("gp", "francúzština", "Guadeloupe"),
  CountryLocalization("gu", "angličtina", "Guam"),
  CountryLocalization("gt", "španielčina", "Guatemala"),
  CountryLocalization("gg", "angličtina", "Guernsey"),
  CountryLocalization("gn", "francúzština", "Guinea"),
  CountryLocalization("gw", "portugalčina", "Guinea-Bissau"),
  CountryLocalization("gy", "angličtina", "Guyana"),
  CountryLocalization("ht", "francúzština", "Haiti"),
  CountryLocalization("hn", "španielčina", "Honduras"),
  CountryLocalization("hk", "čínština", "Hongkong – OAO Číny"),
  CountryLocalization("hu", "maďarčina", "Maďarsko"),
  CountryLocalization("is", "islandčina", "Island"),
  CountryLocalization("in", "nepálčina", "India"),
  CountryLocalization("id", "Indonesian", "Indonézia"),
  CountryLocalization("ir", "perzština", "Irán"),
  CountryLocalization("iq", "severné luri", "Irak"),
  CountryLocalization("ie", "angličtina", "Írsko"),
  CountryLocalization("im", "mančina", "Ostrov Man"),
  CountryLocalization("il", "angličtina", "Izrael"),
  CountryLocalization("it", "nemčina", "Taliansko"),
  CountryLocalization("jm", "angličtina", "Jamajka"),
  CountryLocalization("jp", "japončina", "Japonsko"),
  CountryLocalization("je", "angličtina", "Jersey"),
  CountryLocalization("jo", "arabčina", "Jordánsko"),
  CountryLocalization("kz", "kazaština", "Kazachstan"),
  CountryLocalization("ke", "somálčina", "Keňa"),
  CountryLocalization("ki", "angličtina", "Kiribati"),
  CountryLocalization("xk", "srbčina", "Kosovo"),
  CountryLocalization("kw", "arabčina", "Kuvajt"),
  CountryLocalization("kg", "ruština", "Kirgizsko"),
  CountryLocalization("la", "laoština", "Laos"),
  CountryLocalization("lv", "lotyština", "Lotyšsko"),
  CountryLocalization("lb", "arabčina", "Libanon"),
  CountryLocalization("ls", "angličtina", "Lesotho"),
  CountryLocalization("lr", "angličtina", "Libéria"),
  CountryLocalization("ly", "arabčina", "Líbya"),
  CountryLocalization("li", "nemčina (švajčiarska)", "Lichtenštajnsko"),
  CountryLocalization("lt", "litovčina", "Litva"),
  CountryLocalization("lu", "luxemburčina", "Luxembursko"),
  CountryLocalization("mo", "portugalčina", "Macao – OAO Číny"),
  CountryLocalization("mk", "albánčina", "Macedónsko"),
  CountryLocalization("mg", "francúzština", "Madagaskar"),
  CountryLocalization("mw", "angličtina", "Malawi"),
  CountryLocalization("my", "tamilčina", "Malajzia"),
  CountryLocalization("ml", "francúzština", "Mali"),
  CountryLocalization("mt", "angličtina", "Malta"),
  CountryLocalization("mh", "angličtina", "Marshallove ostrovy"),
  CountryLocalization("mq", "francúzština", "Martinik"),
  CountryLocalization("mr", "arabčina", "Mauritánia"),
  CountryLocalization("mu", "maurícijská kreolčina", "Maurícius"),
  CountryLocalization("yt", "francúzština", "Mayotte"),
  CountryLocalization("mx", "španielčina", "Mexiko"),
  CountryLocalization("fm", "angličtina", "Mikronézia"),
  CountryLocalization("md", "ruština", "Moldavsko"),
  CountryLocalization("mc", "francúzština", "Monako"),
  CountryLocalization("mn", "mongolčina", "Mongolsko"),
  CountryLocalization("me", "srbčina", "Čierna Hora"),
  CountryLocalization("ms", "angličtina", "Montserrat"),
  CountryLocalization("ma", "stredomarocká tuaregčina", "Maroko"),
  CountryLocalization("mz", "makua-meetto", "Mozambik"),
  CountryLocalization("mm", "barmčina", "Mjanmarsko"),
  CountryLocalization("na", "angličtina", "Namíbia"),
  CountryLocalization("nr", "angličtina", "Nauru"),
  CountryLocalization("np", "nepálčina", "Nepál"),
  CountryLocalization("nl", "angličtina", "Holandsko"),
  CountryLocalization("nc", "francúzština", "Nová Kaledónia"),
  CountryLocalization("nz", "angličtina", "Nový Zéland"),
  CountryLocalization("ni", "španielčina", "Nikaragua"),
  CountryLocalization("ne", "hauština", "Niger"),
  CountryLocalization("ng", "hauština", "Nigéria"),
  CountryLocalization("nu", "angličtina", "Niue"),
  CountryLocalization("nf", "angličtina", "Norfolk"),
  CountryLocalization("kp", "kórejčina", "Severná Kórea"),
  CountryLocalization("mp", "angličtina", "Severné Mariány"),
  CountryLocalization("no", "severná saamčina", "Nórsko"),
  CountryLocalization("om", "arabčina", "Omán"),
  CountryLocalization("pk", "angličtina", "Pakistan"),
  CountryLocalization("pw", "angličtina", "Palau"),
  CountryLocalization("ps", "arabčina", "Palestínske územia"),
  CountryLocalization("pa", "španielčina", "Panama"),
  CountryLocalization("pg", "angličtina", "Papua-Nová Guinea"),
  CountryLocalization("py", "španielčina", "Paraguaj"),
  CountryLocalization("pe", "španielčina", "Peru"),
  CountryLocalization("ph", "filipínčina", "Filipíny"),
  CountryLocalization("pn", "angličtina", "Pitcairnove ostrovy"),
  CountryLocalization("pl", "poľština", "Poľsko"),
  CountryLocalization("pt", "portugalčina", "Portugalsko"),
  CountryLocalization("pr", "angličtina", "Portoriko"),
  CountryLocalization("qa", "arabčina", "Katar"),
  CountryLocalization("ro", "rumunčina", "Rumunsko"),
  CountryLocalization("ru", "tatárčina", "Rusko"),
  CountryLocalization("rw", "angličtina", "Rwanda"),
  CountryLocalization("re", "francúzština", "Réunion"),
  CountryLocalization("ws", "angličtina", "Samoa"),
  CountryLocalization("sm", "taliančina", "San Maríno"),
  CountryLocalization("sa", "arabčina", "Saudská Arábia"),
  CountryLocalization("sn", "francúzština", "Senegal"),
  CountryLocalization("rs", "srbčina", "Srbsko"),
  CountryLocalization("cs", "srbčina", "Serbia and Montenegro"),
  CountryLocalization("sc", "francúzština", "Seychely"),
  CountryLocalization("sl", "angličtina", "Sierra Leone"),
  CountryLocalization("sg", "tamilčina", "Singapur"),
  CountryLocalization("sx", "angličtina", "Svätý Martin (hol.)"),
  CountryLocalization("sk", "slovenčina", "Slovensko"),
  CountryLocalization("si", "slovinčina", "Slovinsko"),
  CountryLocalization("sb", "angličtina", "Šalamúnove ostrovy"),
  CountryLocalization("so", "arabčina", "Somálsko"),
  CountryLocalization("za", "angličtina", "Južná Afrika"),
  CountryLocalization("kr", "kórejčina", "Južná Kórea"),
  CountryLocalization("ss", "nuer", "Južný Sudán"),
  CountryLocalization("es", "španielčina", "Španielsko"),
  CountryLocalization("lk", "tamilčina", "Srí Lanka"),
  CountryLocalization("bl", "francúzština", "Svätý Bartolomej"),
  CountryLocalization("sh", "angličtina", "Svätá Helena"),
  CountryLocalization("kn", "angličtina", "Svätý Krištof a Nevis"),
  CountryLocalization("lc", "angličtina", "Svätá Lucia"),
  CountryLocalization("mf", "francúzština", "Svätý Martin (fr.)"),
  CountryLocalization("pm", "francúzština", "Saint Pierre a Miquelon"),
  CountryLocalization("vc", "angličtina", "Svätý Vincent a Grenadíny"),
  CountryLocalization("sd", "arabčina", "Sudán"),
  CountryLocalization("sr", "holandčina", "Surinam"),
  CountryLocalization("sj", "nórčina (bokmal)", "Svalbard a Jan Mayen"),
  CountryLocalization("sz", "angličtina", "Svazijsko"),
  CountryLocalization("se", "švédčina", "Švédsko"),
  CountryLocalization("ch", "nemčina (švajčiarska)", "Švajčiarsko"),
  CountryLocalization("sy", "arabčina", "Sýria"),
  CountryLocalization("st", "portugalčina", "Svätý Tomáš a Princov ostrov"),
  CountryLocalization("tw", "čínština", "Taiwan"),
  CountryLocalization("tj", "tadžičtina", "Tadžikistan"),
  CountryLocalization("tz", "makonde", "Tanzánia"),
  CountryLocalization("th", "thajčina", "Thajsko"),
  CountryLocalization("tl", "portugalčina", "Východný Timor"),
  CountryLocalization("tg", "francúzština", "Togo"),
  CountryLocalization("tk", "angličtina", "Tokelau"),
  CountryLocalization("to", "tongčina", "Tonga"),
  CountryLocalization("tt", "angličtina", "Trinidad a Tobago"),
  CountryLocalization("tn", "francúzština", "Tunisko"),
  CountryLocalization("tr", "turečtina", "Turecko"),
  CountryLocalization("tm", "turkménčina", "Turkménsko"),
  CountryLocalization("tc", "angličtina", "Turks a Caicos"),
  CountryLocalization("tv", "angličtina", "Tuvalu"),
  CountryLocalization("um", "angličtina", "Menšie odľahlé ostrovy USA"),
  CountryLocalization("vi", "angličtina", "Americké Panenské ostrovy"),
  CountryLocalization("ug", "swahilčina", "Uganda"),
  CountryLocalization("ua", "ukrajinčina", "Ukrajina"),
  CountryLocalization("ae", "arabčina", "Spojené arabské emiráty"),
  CountryLocalization("gb", "angličtina", "Spojené kráľovstvo"),
  CountryLocalization("us", "lakotčina", "Spojené štáty"),
  CountryLocalization("uy", "španielčina", "Uruguaj"),
  CountryLocalization("uz", "uzbečtina", "Uzbekistan"),
  CountryLocalization("vu", "francúzština", "Vanuatu"),
  CountryLocalization("va", "taliančina", "Vatikán"),
  CountryLocalization("ve", "španielčina", "Venezuela"),
  CountryLocalization("vn", "vietnamčina", "Vietnam"),
  CountryLocalization("wf", "francúzština", "Wallis a Futuna"),
  CountryLocalization("eh", "arabčina", "Západná Sahara"),
  CountryLocalization("ye", "arabčina", "Jemen"),
  CountryLocalization("zm", "angličtina", "Zambia"),
  CountryLocalization("zw", "severná ndebelčina", "Zimbabwe"),
  CountryLocalization("ax", "švédčina", "Alandy"),
)
