/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot.atlas.extended

import dev.teogor.xenoglot.atlas.CountryLocalization
import kotlin.collections.List

/**
 * Holds the internal list of country-language mappings used for lookups within the package for
 * language code ms.
 *
 * This property contains a hardcoded list of [CountryLocalization] objects, each representing
 * a country and its associated official languages. This list is used by [CountryLanguageRegistry]
 * to provide access to country-language data and should not be modified directly.
 *
 * @see CountryLocalization
 * @see CountryLanguageRegistry
 */
internal val _countryLanguageMappings_ms: List<CountryLocalization> = listOf(
  CountryLocalization("af", "Parsi", "Afghanistan"),
  CountryLocalization("al", "Albania", "Albania"),
  CountryLocalization("dz", "Perancis", "Algeria"),
  CountryLocalization("as", "Inggeris", "Samoa Amerika"),
  CountryLocalization("ad", "Catalonia", "Andorra"),
  CountryLocalization("ao", "Lingala", "Angola"),
  CountryLocalization("ai", "Inggeris", "Anguilla"),
  CountryLocalization("ag", "Inggeris", "Antigua dan Barbuda"),
  CountryLocalization("ar", "Sepanyol", "Argentina"),
  CountryLocalization("am", "Armenia", "Armenia"),
  CountryLocalization("aw", "Belanda", "Aruba"),
  CountryLocalization("au", "Inggeris", "Australia"),
  CountryLocalization("at", "Inggeris", "Austria"),
  CountryLocalization("az", "Azerbaijan", "Azerbaijan"),
  CountryLocalization("bs", "Inggeris", "Bahamas"),
  CountryLocalization("bh", "Arab", "Bahrain"),
  CountryLocalization("bd", "Benggala", "Bangladesh"),
  CountryLocalization("bb", "Inggeris", "Barbados"),
  CountryLocalization("by", "Belarus", "Belarus"),
  CountryLocalization("be", "Perancis", "Belgium"),
  CountryLocalization("bz", "Inggeris", "Belize"),
  CountryLocalization("bj", "Perancis", "Benin"),
  CountryLocalization("bm", "Inggeris", "Bermuda"),
  CountryLocalization("bt", "Dzongkha", "Bhutan"),
  CountryLocalization("bo", "Sepanyol", "Bolivia"),
  CountryLocalization("ba", "Bosnia", "Bosnia dan Herzegovina"),
  CountryLocalization("bw", "Inggeris", "Botswana"),
  CountryLocalization("br", "Portugis", "Brazil"),
  CountryLocalization("io", "Inggeris", "Wilayah Lautan Hindi British"),
  CountryLocalization("vg", "Inggeris", "Kepulauan Virgin British"),
  CountryLocalization("bn", "Melayu", "Brunei"),
  CountryLocalization("bg", "Bulgaria", "Bulgaria"),
  CountryLocalization("bf", "Perancis", "Burkina Faso"),
  CountryLocalization("bi", "Perancis", "Burundi"),
  CountryLocalization("kh", "Khmer", "Kemboja"),
  CountryLocalization("cm", "Basaa", "Cameroon"),
  CountryLocalization("ca", "Perancis", "Kanada"),
  CountryLocalization("ic", "Sepanyol", "Kepulauan Canary"),
  CountryLocalization("cv", "Kabuverdianu", "Cape Verde"),
  CountryLocalization("bq", "Belanda", "Belanda Caribbean"),
  CountryLocalization("ky", "Inggeris", "Kepulauan Cayman"),
  CountryLocalization("cf", "Lingala", "Republik Afrika Tengah"),
  CountryLocalization("ea", "Sepanyol", "Ceuta dan Melilla"),
  CountryLocalization("td", "Arab", "Chad"),
  CountryLocalization("cl", "Sepanyol", "Chile"),
  CountryLocalization("cn", "Tibet", "China"),
  CountryLocalization("cx", "Inggeris", "Pulau Krismas"),
  CountryLocalization("cc", "Inggeris", "Kepulauan Cocos (Keeling)"),
  CountryLocalization("co", "Sepanyol", "Colombia"),
  CountryLocalization("km", "Arab", "Comoros"),
  CountryLocalization("cg", "Lingala", "Congo - Brazzaville"),
  CountryLocalization("cd", "Swahili", "Congo - Kinshasa"),
  CountryLocalization("ck", "Inggeris", "Kepulauan Cook"),
  CountryLocalization("cr", "Sepanyol", "Costa Rica"),
  CountryLocalization("hr", "Croatia", "Croatia"),
  CountryLocalization("cu", "Sepanyol", "Cuba"),
  CountryLocalization("cw", "Belanda", "Curacao"),
  CountryLocalization("cy", "Inggeris", "Cyprus"),
  CountryLocalization("cz", "Czech", "Czechia"),
  CountryLocalization("ci", "Perancis", "Cote d’Ivoire"),
  CountryLocalization("dk", "Inggeris", "Denmark"),
  CountryLocalization("dg", "Inggeris", "Diego Garcia"),
  CountryLocalization("dj", "Perancis", "Djibouti"),
  CountryLocalization("dm", "Inggeris", "Dominica"),
  CountryLocalization("do", "Sepanyol", "Republik Dominica"),
  CountryLocalization("ec", "Quechua", "Ecuador"),
  CountryLocalization("eg", "Arab", "Mesir"),
  CountryLocalization("sv", "Sepanyol", "El Salvador"),
  CountryLocalization("gq", "Sepanyol", "Guinea Khatulistiwa"),
  CountryLocalization("er", "Tigrinya", "Eritrea"),
  CountryLocalization("ee", "Estonia", "Estonia"),
  CountryLocalization("et", "Amharic", "Ethiopia"),
  CountryLocalization("fk", "Inggeris", "Kepulauan Falkland"),
  CountryLocalization("fo", "Faroe", "Kepulauan Faroe"),
  CountryLocalization("fj", "Inggeris", "Fiji"),
  CountryLocalization("fi", "Sweden", "Finland"),
  CountryLocalization("fr", "Jerman Switzerland", "Perancis"),
  CountryLocalization("gf", "Perancis", "Guiana Perancis"),
  CountryLocalization("pf", "Perancis", "Polinesia Perancis"),
  CountryLocalization("ga", "Perancis", "Gabon"),
  CountryLocalization("gm", "Inggeris", "Gambia"),
  CountryLocalization("ge", "Ossete", "Georgia"),
  CountryLocalization("de", "Sorbian Rendah", "Jerman"),
  CountryLocalization("gh", "Inggeris", "Ghana"),
  CountryLocalization("gi", "Inggeris", "Gibraltar"),
  CountryLocalization("gr", "Greek", "Greece"),
  CountryLocalization("gl", "Kalaallisut", "Greenland"),
  CountryLocalization("gd", "Inggeris", "Grenada"),
  CountryLocalization("gp", "Perancis", "Guadeloupe"),
  CountryLocalization("gu", "Inggeris", "Guam"),
  CountryLocalization("gt", "Sepanyol", "Guatemala"),
  CountryLocalization("gg", "Inggeris", "Guernsey"),
  CountryLocalization("gn", "Perancis", "Guinea"),
  CountryLocalization("gw", "Portugis", "Guinea Bissau"),
  CountryLocalization("gy", "Inggeris", "Guyana"),
  CountryLocalization("ht", "Perancis", "Haiti"),
  CountryLocalization("hn", "Sepanyol", "Honduras"),
  CountryLocalization("hk", "Cina", "Hong Kong SAR China"),
  CountryLocalization("hu", "Hungary", "Hungary"),
  CountryLocalization("is", "Iceland", "Iceland"),
  CountryLocalization("in", "Nepal", "India"),
  CountryLocalization("id", "Indonesian", "Indonesia"),
  CountryLocalization("ir", "Parsi", "Iran"),
  CountryLocalization("iq", "Luri Utara", "Iraq"),
  CountryLocalization("ie", "Inggeris", "Ireland"),
  CountryLocalization("im", "Manx", "Isle of Man"),
  CountryLocalization("il", "Inggeris", "Israel"),
  CountryLocalization("it", "Jerman", "Itali"),
  CountryLocalization("jm", "Inggeris", "Jamaica"),
  CountryLocalization("jp", "Jepun", "Jepun"),
  CountryLocalization("je", "Inggeris", "Jersey"),
  CountryLocalization("jo", "Arab", "Jordan"),
  CountryLocalization("kz", "Kazakhstan", "Kazakhstan"),
  CountryLocalization("ke", "Somali", "Kenya"),
  CountryLocalization("ki", "Inggeris", "Kiribati"),
  CountryLocalization("xk", "Serbia", "Kosovo"),
  CountryLocalization("kw", "Arab", "Kuwait"),
  CountryLocalization("kg", "Rusia", "Kyrgyzstan"),
  CountryLocalization("la", "Laos", "Laos"),
  CountryLocalization("lv", "Latvia", "Latvia"),
  CountryLocalization("lb", "Arab", "Lubnan"),
  CountryLocalization("ls", "Inggeris", "Lesotho"),
  CountryLocalization("lr", "Inggeris", "Liberia"),
  CountryLocalization("ly", "Arab", "Libya"),
  CountryLocalization("li", "Jerman Switzerland", "Liechtenstein"),
  CountryLocalization("lt", "Lithuania", "Lithuania"),
  CountryLocalization("lu", "Luxembourg", "Luxembourg"),
  CountryLocalization("mo", "Portugis", "Macau SAR China"),
  CountryLocalization("mk", "Albania", "Macedonia"),
  CountryLocalization("mg", "Perancis", "Madagaskar"),
  CountryLocalization("mw", "Inggeris", "Malawi"),
  CountryLocalization("my", "Tamil", "Malaysia"),
  CountryLocalization("ml", "Perancis", "Mali"),
  CountryLocalization("mt", "Inggeris", "Malta"),
  CountryLocalization("mh", "Inggeris", "Kepulauan Marshall"),
  CountryLocalization("mq", "Perancis", "Martinique"),
  CountryLocalization("mr", "Arab", "Mauritania"),
  CountryLocalization("mu", "Morisyen", "Mauritius"),
  CountryLocalization("yt", "Perancis", "Mayotte"),
  CountryLocalization("mx", "Sepanyol", "Mexico"),
  CountryLocalization("fm", "Inggeris", "Micronesia"),
  CountryLocalization("md", "Rusia", "Moldova"),
  CountryLocalization("mc", "Perancis", "Monaco"),
  CountryLocalization("mn", "Mongolia", "Mongolia"),
  CountryLocalization("me", "Serbia", "Montenegro"),
  CountryLocalization("ms", "Inggeris", "Montserrat"),
  CountryLocalization("ma", "Tamazight Atlas Tengah", "Maghribi"),
  CountryLocalization("mz", "Makhuwa-Meetto", "Mozambique"),
  CountryLocalization("mm", "Burma", "Myanmar (Burma)"),
  CountryLocalization("na", "Inggeris", "Namibia"),
  CountryLocalization("nr", "Inggeris", "Nauru"),
  CountryLocalization("np", "Nepal", "Nepal"),
  CountryLocalization("nl", "Inggeris", "Belanda"),
  CountryLocalization("nc", "Perancis", "New Caledonia"),
  CountryLocalization("nz", "Inggeris", "New Zealand"),
  CountryLocalization("ni", "Sepanyol", "Nicaragua"),
  CountryLocalization("ne", "Hausa", "Niger"),
  CountryLocalization("ng", "Hausa", "Nigeria"),
  CountryLocalization("nu", "Inggeris", "Niue"),
  CountryLocalization("nf", "Inggeris", "Pulau Norfolk"),
  CountryLocalization("kp", "Korea", "Korea Utara"),
  CountryLocalization("mp", "Inggeris", "Kepulauan Mariana Utara"),
  CountryLocalization("no", "Sami Utara", "Norway"),
  CountryLocalization("om", "Arab", "Oman"),
  CountryLocalization("pk", "Inggeris", "Pakistan"),
  CountryLocalization("pw", "Inggeris", "Palau"),
  CountryLocalization("ps", "Arab", "Wilayah Palestin"),
  CountryLocalization("pa", "Sepanyol", "Panama"),
  CountryLocalization("pg", "Inggeris", "Papua New Guinea"),
  CountryLocalization("py", "Sepanyol", "Paraguay"),
  CountryLocalization("pe", "Sepanyol", "Peru"),
  CountryLocalization("ph", "Filipina", "Filipina"),
  CountryLocalization("pn", "Inggeris", "Kepulauan Pitcairn"),
  CountryLocalization("pl", "Poland", "Poland"),
  CountryLocalization("pt", "Portugis", "Portugal"),
  CountryLocalization("pr", "Inggeris", "Puerto Rico"),
  CountryLocalization("qa", "Arab", "Qatar"),
  CountryLocalization("ro", "Romania", "Romania"),
  CountryLocalization("ru", "Tatar", "Rusia"),
  CountryLocalization("rw", "Inggeris", "Rwanda"),
  CountryLocalization("re", "Perancis", "Reunion"),
  CountryLocalization("ws", "Inggeris", "Samoa"),
  CountryLocalization("sm", "Itali", "San Marino"),
  CountryLocalization("sa", "Arab", "Arab Saudi"),
  CountryLocalization("sn", "Perancis", "Senegal"),
  CountryLocalization("rs", "Serbia", "Serbia"),
  CountryLocalization("cs", "Serbia", "Serbia and Montenegro"),
  CountryLocalization("sc", "Perancis", "Seychelles"),
  CountryLocalization("sl", "Inggeris", "Sierra Leone"),
  CountryLocalization("sg", "Tamil", "Singapura"),
  CountryLocalization("sx", "Inggeris", "Sint Maarten"),
  CountryLocalization("sk", "Slovak", "Slovakia"),
  CountryLocalization("si", "Slovenia", "Slovenia"),
  CountryLocalization("sb", "Inggeris", "Kepulauan Solomon"),
  CountryLocalization("so", "Arab", "Somalia"),
  CountryLocalization("za", "Inggeris", "Afrika Selatan"),
  CountryLocalization("kr", "Korea", "Korea Selatan"),
  CountryLocalization("ss", "Nuer", "Sudan Selatan"),
  CountryLocalization("es", "Sepanyol", "Sepanyol"),
  CountryLocalization("lk", "Tamil", "Sri Lanka"),
  CountryLocalization("bl", "Perancis", "Saint Barthélemy"),
  CountryLocalization("sh", "Inggeris", "Saint Helena"),
  CountryLocalization("kn", "Inggeris", "Saint Kitts dan Nevis"),
  CountryLocalization("lc", "Inggeris", "Saint Lucia"),
  CountryLocalization("mf", "Perancis", "Saint Martin"),
  CountryLocalization("pm", "Perancis", "Saint Pierre dan Miquelon"),
  CountryLocalization("vc", "Inggeris", "Saint Vincent dan Grenadines"),
  CountryLocalization("sd", "Arab", "Sudan"),
  CountryLocalization("sr", "Belanda", "Surinam"),
  CountryLocalization("sj", "Bokmål Norway", "Svalbard dan Jan Mayen"),
  CountryLocalization("sz", "Inggeris", "Swaziland"),
  CountryLocalization("se", "Sweden", "Sweden"),
  CountryLocalization("ch", "Jerman Switzerland", "Switzerland"),
  CountryLocalization("sy", "Arab", "Syria"),
  CountryLocalization("st", "Portugis", "Sao Tome dan Principe"),
  CountryLocalization("tw", "Cina", "Taiwan"),
  CountryLocalization("tj", "Tajik", "Tajikistan"),
  CountryLocalization("tz", "Makonde", "Tanzania"),
  CountryLocalization("th", "Thai", "Thailand"),
  CountryLocalization("tl", "Portugis", "Timor-Leste"),
  CountryLocalization("tg", "Perancis", "Togo"),
  CountryLocalization("tk", "Inggeris", "Tokelau"),
  CountryLocalization("to", "Tonga", "Tonga"),
  CountryLocalization("tt", "Inggeris", "Trinidad dan Tobago"),
  CountryLocalization("tn", "Perancis", "Tunisia"),
  CountryLocalization("tr", "Turki", "Turki"),
  CountryLocalization("tm", "Turkmen", "Turkmenistan"),
  CountryLocalization("tc", "Inggeris", "Kepulauan Turks dan Caicos"),
  CountryLocalization("tv", "Inggeris", "Tuvalu"),
  CountryLocalization("um", "Inggeris", "Kepulauan Terpencil A.S."),
  CountryLocalization("vi", "Inggeris", "Kepulauan Virgin A.S."),
  CountryLocalization("ug", "Swahili", "Uganda"),
  CountryLocalization("ua", "Ukraine", "Ukraine"),
  CountryLocalization("ae", "Arab", "Emiriah Arab Bersatu"),
  CountryLocalization("gb", "Inggeris", "United Kingdom"),
  CountryLocalization("us", "Lakota", "Amerika Syarikat"),
  CountryLocalization("uy", "Sepanyol", "Uruguay"),
  CountryLocalization("uz", "Uzbekistan", "Uzbekistan"),
  CountryLocalization("vu", "Perancis", "Vanuatu"),
  CountryLocalization("va", "Itali", "Kota Vatican"),
  CountryLocalization("ve", "Sepanyol", "Venezuela"),
  CountryLocalization("vn", "Vietnam", "Vietnam"),
  CountryLocalization("wf", "Perancis", "Wallis dan Futuna"),
  CountryLocalization("eh", "Arab", "Sahara Barat"),
  CountryLocalization("ye", "Arab", "Yaman"),
  CountryLocalization("zm", "Inggeris", "Zambia"),
  CountryLocalization("zw", "Ndebele Utara", "Zimbabwe"),
  CountryLocalization("ax", "Sweden", "Kepulauan Aland"),
)
