/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot.atlas.extended

import dev.teogor.xenoglot.atlas.CountryLocalization
import kotlin.collections.List

/**
 * Holds the internal list of country-language mappings used for lookups within the package for
 * language code fa.
 *
 * This property contains a hardcoded list of [CountryLocalization] objects, each representing
 * a country and its associated official languages. This list is used by [CountryLanguageRegistry]
 * to provide access to country-language data and should not be modified directly.
 *
 * @see CountryLocalization
 * @see CountryLanguageRegistry
 */
internal val _countryLanguageMappings_fa: List<CountryLocalization> = listOf(
  CountryLocalization("af", "فارسی", "افغانستان"),
  CountryLocalization("al", "البانیایی", "البانیا"),
  CountryLocalization("dz", "فرانسوی", "الجزایر"),
  CountryLocalization("as", "انگلیسی", "ساموآی امریکا"),
  CountryLocalization("ad", "کاتالان", "اندورا"),
  CountryLocalization("ao", "لینگالا", "انگولا"),
  CountryLocalization("ai", "انگلیسی", "آنگویلا"),
  CountryLocalization("ag", "انگلیسی", "انتیگوا و باربودا"),
  CountryLocalization("ar", "هسپانوی", "ارجنتاین"),
  CountryLocalization("am", "ارمنی", "ارمنستان"),
  CountryLocalization("aw", "هالندی", "آروبا"),
  CountryLocalization("au", "انگلیسی", "آسترالیا"),
  CountryLocalization("at", "انگلیسی", "اتریش"),
  CountryLocalization("az", "آذربایجانی", "جمهوری آذربایجان"),
  CountryLocalization("bs", "انگلیسی", "بهاماس"),
  CountryLocalization("bh", "عربی", "بحرین"),
  CountryLocalization("bd", "بنگالی", "بنگله‌دیش"),
  CountryLocalization("bb", "انگلیسی", "باربادوس"),
  CountryLocalization("by", "بلاروسی", "بلاروس"),
  CountryLocalization("be", "فرانسوی", "بلجیم"),
  CountryLocalization("bz", "انگلیسی", "بلیز"),
  CountryLocalization("bj", "فرانسوی", "بنین"),
  CountryLocalization("bm", "انگلیسی", "برمودا"),
  CountryLocalization("bt", "جونخایی", "بوتان"),
  CountryLocalization("bo", "هسپانوی", "بولیویا"),
  CountryLocalization("ba", "بوسنیایی", "بوسنیا و هرزه‌گوینا"),
  CountryLocalization("bw", "انگلیسی", "بوتسوانا"),
  CountryLocalization("br", "پرتگالی", "برازیل"),
  CountryLocalization("io", "انگلیسی", "قلمرو بریتانیا در اقیانوس هند"),
  CountryLocalization("vg", "انگلیسی", "جزایر ویرجین بریتانیا"),
  CountryLocalization("bn", "مالایی", "برونی"),
  CountryLocalization("bg", "بلغاری", "بلغاریا"),
  CountryLocalization("bf", "فرانسوی", "بورکینافاسو"),
  CountryLocalization("bi", "فرانسوی", "بوروندی"),
  CountryLocalization("kh", "خمری", "کمپوچیا"),
  CountryLocalization("cm", "باسایی", "کامرون"),
  CountryLocalization("ca", "فرانسوی", "کانادا"),
  CountryLocalization("ic", "هسپانوی", "جزایر قناری"),
  CountryLocalization("cv", "کابووردیانو", "کیپ‌ورد"),
  CountryLocalization("bq", "هالندی", "جزایر کارائیب هلند"),
  CountryLocalization("ky", "انگلیسی", "جزایر کِیمن"),
  CountryLocalization("cf", "لینگالا", "جمهوری افریقای مرکزی"),
  CountryLocalization("ea", "هسپانوی", "سبته و ملیله"),
  CountryLocalization("td", "عربی", "چاد"),
  CountryLocalization("cl", "هسپانوی", "چلی"),
  CountryLocalization("cn", "تبتی", "چین"),
  CountryLocalization("cx", "انگلیسی", "جزیرهٔ کریسمس"),
  CountryLocalization("cc", "انگلیسی", "جزایر کوکوس"),
  CountryLocalization("co", "هسپانوی", "کولمبیا"),
  CountryLocalization("km", "عربی", "کومورو"),
  CountryLocalization("cg", "لینگالا", "کانگو - برازویل"),
  CountryLocalization("cd", "سواحلی", "کانگو - کینشاسا"),
  CountryLocalization("ck", "انگلیسی", "جزایر کوک"),
  CountryLocalization("cr", "هسپانوی", "کاستریکا"),
  CountryLocalization("hr", "کروشیایی", "کروشیا"),
  CountryLocalization("cu", "هسپانوی", "کیوبا"),
  CountryLocalization("cw", "هالندی", "کوراسائو"),
  CountryLocalization("cy", "انگلیسی", "قبرس"),
  CountryLocalization("cz", "چکی", "جمهوری چک"),
  CountryLocalization("ci", "فرانسوی", "ساحل عاج"),
  CountryLocalization("dk", "انگلیسی", "دنمارک"),
  CountryLocalization("dg", "انگلیسی", "دیه‌گو گارسیا"),
  CountryLocalization("dj", "فرانسوی", "جیبوتی"),
  CountryLocalization("dm", "انگلیسی", "دومینیکا"),
  CountryLocalization("do", "هسپانوی", "جمهوری دومینیکن"),
  CountryLocalization("ec", "کچوایی", "اکوادور"),
  CountryLocalization("eg", "عربی", "مصر"),
  CountryLocalization("sv", "هسپانوی", "السلوادور"),
  CountryLocalization("gq", "هسپانوی", "گینیا استوایی"),
  CountryLocalization("er", "تیگرینیایی", "اریتریا"),
  CountryLocalization("ee", "استونیایی", "استونیا"),
  CountryLocalization("et", "امهری", "ایتوپیا"),
  CountryLocalization("fk", "انگلیسی", "جزایر فالکلند"),
  CountryLocalization("fo", "فارویی", "جزایر فارو"),
  CountryLocalization("fj", "انگلیسی", "فیجی"),
  CountryLocalization("fi", "سویدنی", "فنلند"),
  CountryLocalization("fr", "آلمانی سوئیسی", "فرانسه"),
  CountryLocalization("gf", "فرانسوی", "گویان فرانسه"),
  CountryLocalization("pf", "فرانسوی", "پلی‌نزی فرانسه"),
  CountryLocalization("ga", "فرانسوی", "گابن"),
  CountryLocalization("gm", "انگلیسی", "گامبیا"),
  CountryLocalization("ge", "آسی", "گرجستان"),
  CountryLocalization("de", "صُربی سفلی", "آلمان"),
  CountryLocalization("gh", "انگلیسی", "گانا"),
  CountryLocalization("gi", "انگلیسی", "جبل‌الطارق"),
  CountryLocalization("gr", "یونانی", "یونان"),
  CountryLocalization("gl", "گرینلندی", "گرینلند"),
  CountryLocalization("gd", "انگلیسی", "گرینادا"),
  CountryLocalization("gp", "فرانسوی", "گوادلوپ"),
  CountryLocalization("gu", "انگلیسی", "گوام"),
  CountryLocalization("gt", "هسپانوی", "گواتیمالا"),
  CountryLocalization("gg", "انگلیسی", "گرنزی"),
  CountryLocalization("gn", "فرانسوی", "گینیا"),
  CountryLocalization("gw", "پرتگالی", "گینیا بیسائو"),
  CountryLocalization("gy", "انگلیسی", "گیانا"),
  CountryLocalization("ht", "فرانسوی", "هایتی"),
  CountryLocalization("hn", "هسپانوی", "هاندوراس"),
  CountryLocalization("hk", "چینی", "هنگ‌کنگ، ناحیهٔ ویژهٔ حکومتی چین"),
  CountryLocalization("hu", "مجاری", "مجارستان"),
  CountryLocalization("is", "آیسلندی", "آیسلند"),
  CountryLocalization("in", "نیپالی", "هند"),
  CountryLocalization("id", "Indonesian", "اندونیزیا"),
  CountryLocalization("ir", "فارسی", "ایران"),
  CountryLocalization("iq", "لری شمالی", "عراق"),
  CountryLocalization("ie", "انگلیسی", "آیرلند"),
  CountryLocalization("im", "مانی", "جزیرهٔ من"),
  CountryLocalization("il", "انگلیسی", "اسرائیل"),
  CountryLocalization("it", "آلمانی", "ایتالیا"),
  CountryLocalization("jm", "انگلیسی", "جامائیکا"),
  CountryLocalization("jp", "جاپانی", "جاپان"),
  CountryLocalization("je", "انگلیسی", "جرزی"),
  CountryLocalization("jo", "عربی", "اردن"),
  CountryLocalization("kz", "قزاقی", "قزاقستان"),
  CountryLocalization("ke", "سومالیایی", "کینیا"),
  CountryLocalization("ki", "انگلیسی", "کیریباتی"),
  CountryLocalization("xk", "صربی", "کوسوا"),
  CountryLocalization("kw", "عربی", "کویت"),
  CountryLocalization("kg", "روسی", "قرغزستان"),
  CountryLocalization("la", "لائوسی", "لائوس"),
  CountryLocalization("lv", "لتونیایی", "لاتویا"),
  CountryLocalization("lb", "عربی", "لبنان"),
  CountryLocalization("ls", "انگلیسی", "لیسوتو"),
  CountryLocalization("lr", "انگلیسی", "لیبریا"),
  CountryLocalization("ly", "عربی", "لیبیا"),
  CountryLocalization("li", "آلمانی سوئیسی", "لیختن‌اشتاین"),
  CountryLocalization("lt", "لیتوانیایی", "لتوانیا"),
  CountryLocalization("lu", "لوگزامبورگی", "لوکزامبورگ"),
  CountryLocalization("mo", "پرتگالی", "ماکائو، ناحیهٔ ویژهٔ حکومتی چین"),
  CountryLocalization("mk", "البانیایی", "مقدونیه"),
  CountryLocalization("mg", "فرانسوی", "مادغاسکر"),
  CountryLocalization("mw", "انگلیسی", "مالاوی"),
  CountryLocalization("my", "تامیلی", "مالیزیا"),
  CountryLocalization("ml", "فرانسوی", "مالی"),
  CountryLocalization("mt", "انگلیسی", "مالتا"),
  CountryLocalization("mh", "انگلیسی", "جزایر مارشال"),
  CountryLocalization("mq", "فرانسوی", "مارتینیک"),
  CountryLocalization("mr", "عربی", "موریتانیا"),
  CountryLocalization("mu", "موریسین", "موریس"),
  CountryLocalization("yt", "فرانسوی", "مایوت"),
  CountryLocalization("mx", "هسپانوی", "مکسیکو"),
  CountryLocalization("fm", "انگلیسی", "میکرونزیا"),
  CountryLocalization("md", "روسی", "مولداوی"),
  CountryLocalization("mc", "فرانسوی", "موناکو"),
  CountryLocalization("mn", "مغلی", "منگولیا"),
  CountryLocalization("me", "صربی", "مونته‌نگرو"),
  CountryLocalization("ms", "انگلیسی", "مونت‌سرات"),
  CountryLocalization("ma", "آمازیغی اطلس مرکزی", "مراکش"),
  CountryLocalization("mz", "ماکوا متو", "موزمبیق"),
  CountryLocalization("mm", "برمه‌ای", "میانمار (برمه)"),
  CountryLocalization("na", "انگلیسی", "نامیبیا"),
  CountryLocalization("nr", "انگلیسی", "نائورو"),
  CountryLocalization("np", "نیپالی", "نیپال"),
  CountryLocalization("nl", "انگلیسی", "هالند"),
  CountryLocalization("nc", "فرانسوی", "کالدونیای جدید"),
  CountryLocalization("nz", "انگلیسی", "زیلاند جدید"),
  CountryLocalization("ni", "هسپانوی", "نیکاراگوا"),
  CountryLocalization("ne", "هوسیایی", "نایجر"),
  CountryLocalization("ng", "هوسیایی", "نیجریا"),
  CountryLocalization("nu", "انگلیسی", "نیوئه"),
  CountryLocalization("nf", "انگلیسی", "جزیرهٔ نورفولک"),
  CountryLocalization("kp", "کوریایی", "کوریای شمالی"),
  CountryLocalization("mp", "انگلیسی", "جزایر ماریانای شمالی"),
  CountryLocalization("no", "سامی شمالی", "ناروی"),
  CountryLocalization("om", "عربی", "عمان"),
  CountryLocalization("pk", "انگلیسی", "پاکستان"),
  CountryLocalization("pw", "انگلیسی", "پالائو"),
  CountryLocalization("ps", "عربی", "سرزمین‌های فلسطینی"),
  CountryLocalization("pa", "هسپانوی", "پانامه"),
  CountryLocalization("pg", "انگلیسی", "پاپوا نیو گینیا"),
  CountryLocalization("py", "هسپانوی", "پاراگوای"),
  CountryLocalization("pe", "هسپانوی", "پیرو"),
  CountryLocalization("ph", "فیلیپینی", "فیلیپین"),
  CountryLocalization("pn", "انگلیسی", "جزایر پیت‌کرن"),
  CountryLocalization("pl", "پولندی", "پولند"),
  CountryLocalization("pt", "پرتگالی", "پرتگال"),
  CountryLocalization("pr", "انگلیسی", "پورتوریکو"),
  CountryLocalization("qa", "عربی", "قطر"),
  CountryLocalization("ro", "رومانیایی", "رومانیا"),
  CountryLocalization("ru", "تاتاری", "روسیه"),
  CountryLocalization("rw", "انگلیسی", "روآندا"),
  CountryLocalization("re", "فرانسوی", "رئونیون"),
  CountryLocalization("ws", "انگلیسی", "ساموآ"),
  CountryLocalization("sm", "ایتالوی", "سان‌مارینو"),
  CountryLocalization("sa", "عربی", "عربستان سعودی"),
  CountryLocalization("sn", "فرانسوی", "سینیگال"),
  CountryLocalization("rs", "صربی", "صربستان"),
  CountryLocalization("cs", "صربی", "Serbia and Montenegro"),
  CountryLocalization("sc", "فرانسوی", "سیشل"),
  CountryLocalization("sl", "انگلیسی", "سیرالیون"),
  CountryLocalization("sg", "تامیلی", "سینگاپور"),
  CountryLocalization("sx", "انگلیسی", "سنت مارتن"),
  CountryLocalization("sk", "اسلواکی", "سلواکیا"),
  CountryLocalization("si", "اسلوونیایی", "سلونیا"),
  CountryLocalization("sb", "انگلیسی", "جزایر سلیمان"),
  CountryLocalization("so", "عربی", "سومالیه"),
  CountryLocalization("za", "انگلیسی", "افریقای جنوبی"),
  CountryLocalization("kr", "کوریایی", "کوریای جنوبی"),
  CountryLocalization("ss", "نویر", "سودان جنوبی"),
  CountryLocalization("es", "هسپانوی", "هسپانیه"),
  CountryLocalization("lk", "تامیلی", "سریلانکا"),
  CountryLocalization("bl", "فرانسوی", "سن بارتلمی"),
  CountryLocalization("sh", "انگلیسی", "سنت هلن"),
  CountryLocalization("kn", "انگلیسی", "سنت کیتس و نویس"),
  CountryLocalization("lc", "انگلیسی", "سنت لوسیا"),
  CountryLocalization("mf", "فرانسوی", "سنت مارتین"),
  CountryLocalization("pm", "فرانسوی", "سن پیر و میکلن"),
  CountryLocalization("vc", "انگلیسی", "سنت وینسنت و گرنادین‌ها"),
  CountryLocalization("sd", "عربی", "سودان"),
  CountryLocalization("sr", "هالندی", "سورینام"),
  CountryLocalization("sj", "نروژی بوک‌مُل", "اسوالبارد و جان‌ماین"),
  CountryLocalization("sz", "انگلیسی", "سوازیلند"),
  CountryLocalization("se", "سویدنی", "سویدن"),
  CountryLocalization("ch", "آلمانی سوئیسی", "سویس"),
  CountryLocalization("sy", "عربی", "سوریه"),
  CountryLocalization("st", "پرتگالی", "سائوتومه و پرینسیپ"),
  CountryLocalization("tw", "چینی", "تایوان"),
  CountryLocalization("tj", "تاجکی", "تاجکستان"),
  CountryLocalization("tz", "ماکونده", "تانزانیا"),
  CountryLocalization("th", "تایلندی", "تایلند"),
  CountryLocalization("tl", "پرتگالی", "تیمور-لسته"),
  CountryLocalization("tg", "فرانسوی", "توگو"),
  CountryLocalization("tk", "انگلیسی", "توکلائو"),
  CountryLocalization("to", "تونگایی", "تونگا"),
  CountryLocalization("tt", "انگلیسی", "ترینیداد و توباگو"),
  CountryLocalization("tn", "فرانسوی", "تونس"),
  CountryLocalization("tr", "ترکی استانبولی", "ترکیه"),
  CountryLocalization("tm", "ترکمنی", "ترکمنستان"),
  CountryLocalization("tc", "انگلیسی", "جزایر تورکس و کایکوس"),
  CountryLocalization("tv", "انگلیسی", "تووالو"),
  CountryLocalization("um", "انگلیسی", "جزایر دورافتادهٔ ایالات متحده"),
  CountryLocalization("vi", "انگلیسی", "جزایر ویرجین ایالات متحده"),
  CountryLocalization("ug", "سواحلی", "یوگاندا"),
  CountryLocalization("ua", "اوکراینی", "اکراین"),
  CountryLocalization("ae", "عربی", "امارات متحدهٔ عربی"),
  CountryLocalization("gb", "انگلیسی", "بریتانیا"),
  CountryLocalization("us", "لاکوتا", "ایالات متحده"),
  CountryLocalization("uy", "هسپانوی", "یوروگوای"),
  CountryLocalization("uz", "ازبکی", "ازبکستان"),
  CountryLocalization("vu", "فرانسوی", "وانواتو"),
  CountryLocalization("va", "ایتالوی", "واتیکان"),
  CountryLocalization("ve", "هسپانوی", "ونزویلا"),
  CountryLocalization("vn", "ویتنامی", "ویتنام"),
  CountryLocalization("wf", "فرانسوی", "والیس و فوتونا"),
  CountryLocalization("eh", "عربی", "صحرای غربی"),
  CountryLocalization("ye", "عربی", "یمن"),
  CountryLocalization("zm", "انگلیسی", "زامبیا"),
  CountryLocalization("zw", "انده‌بله‌ای شمالی", "زیمبابوی"),
  CountryLocalization("ax", "سویدنی", "جزایر آلاند"),
)
