/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot.atlas.extended

import dev.teogor.xenoglot.atlas.CountryLocalization
import kotlin.collections.List

/**
 * Holds the internal list of country-language mappings used for lookups within the package for
 * language code bo.
 *
 * This property contains a hardcoded list of [CountryLocalization] objects, each representing
 * a country and its associated official languages. This list is used by [CountryLanguageRegistry]
 * to provide access to country-language data and should not be modified directly.
 *
 * @see CountryLocalization
 * @see CountryLanguageRegistry
 */
internal val _countryLanguageMappings_bo: List<CountryLocalization> = listOf(
  CountryLocalization("af", "Persian", "Afghanistan"),
  CountryLocalization("al", "Albanian", "Albania"),
  CountryLocalization("dz", "French", "Algeria"),
  CountryLocalization("as", "དབྱིན་ཇིའི་སྐད།", "American Samoa"),
  CountryLocalization("ad", "Catalan", "Andorra"),
  CountryLocalization("ao", "Lingala", "Angola"),
  CountryLocalization("ai", "དབྱིན་ཇིའི་སྐད།", "Anguilla"),
  CountryLocalization("ag", "དབྱིན་ཇིའི་སྐད།", "Antigua & Barbuda"),
  CountryLocalization("ar", "Spanish", "Argentina"),
  CountryLocalization("am", "Armenian", "Armenia"),
  CountryLocalization("aw", "Dutch", "Aruba"),
  CountryLocalization("au", "དབྱིན་ཇིའི་སྐད།", "Australia"),
  CountryLocalization("at", "དབྱིན་ཇིའི་སྐད།", "Austria"),
  CountryLocalization("az", "Azerbaijani", "Azerbaijan"),
  CountryLocalization("bs", "དབྱིན་ཇིའི་སྐད།", "Bahamas"),
  CountryLocalization("bh", "Arabic", "Bahrain"),
  CountryLocalization("bd", "Bangla", "Bangladesh"),
  CountryLocalization("bb", "དབྱིན་ཇིའི་སྐད།", "Barbados"),
  CountryLocalization("by", "Belarusian", "Belarus"),
  CountryLocalization("be", "French", "Belgium"),
  CountryLocalization("bz", "དབྱིན་ཇིའི་སྐད།", "Belize"),
  CountryLocalization("bj", "French", "Benin"),
  CountryLocalization("bm", "དབྱིན་ཇིའི་སྐད།", "Bermuda"),
  CountryLocalization("bt", "རྫོང་ཁ", "Bhutan"),
  CountryLocalization("bo", "Spanish", "Bolivia"),
  CountryLocalization("ba", "Bosnian", "Bosnia & Herzegovina"),
  CountryLocalization("bw", "དབྱིན་ཇིའི་སྐད།", "Botswana"),
  CountryLocalization("br", "Portuguese", "Brazil"),
  CountryLocalization("io", "དབྱིན་ཇིའི་སྐད།", "British Indian Ocean Territory"),
  CountryLocalization("vg", "དབྱིན་ཇིའི་སྐད།", "British Virgin Islands"),
  CountryLocalization("bn", "Malay", "Brunei"),
  CountryLocalization("bg", "Bulgarian", "Bulgaria"),
  CountryLocalization("bf", "French", "Burkina Faso"),
  CountryLocalization("bi", "French", "Burundi"),
  CountryLocalization("kh", "Khmer", "Cambodia"),
  CountryLocalization("cm", "Basaa", "Cameroon"),
  CountryLocalization("ca", "French", "Canada"),
  CountryLocalization("ic", "Spanish", "IC"),
  CountryLocalization("cv", "kea", "Cape Verde"),
  CountryLocalization("bq", "Dutch", "Caribbean Netherlands"),
  CountryLocalization("ky", "དབྱིན་ཇིའི་སྐད།", "Cayman Islands"),
  CountryLocalization("cf", "Lingala", "Central African Republic"),
  CountryLocalization("ea", "Spanish", "EA"),
  CountryLocalization("td", "Arabic", "Chad"),
  CountryLocalization("cl", "Spanish", "Chile"),
  CountryLocalization("cn", "བོད་སྐད་", "རྒྱ་ནག"),
  CountryLocalization("cx", "དབྱིན་ཇིའི་སྐད།", "Christmas Island"),
  CountryLocalization("cc", "དབྱིན་ཇིའི་སྐད།", "Cocos (Keeling) Islands"),
  CountryLocalization("co", "Spanish", "Colombia"),
  CountryLocalization("km", "Arabic", "Comoros"),
  CountryLocalization("cg", "Lingala", "Congo - Brazzaville"),
  CountryLocalization("cd", "Swahili", "Congo - Kinshasa"),
  CountryLocalization("ck", "དབྱིན་ཇིའི་སྐད།", "Cook Islands"),
  CountryLocalization("cr", "Spanish", "Costa Rica"),
  CountryLocalization("hr", "Croatian", "Croatia"),
  CountryLocalization("cu", "Spanish", "Cuba"),
  CountryLocalization("cw", "Dutch", "Curaçao"),
  CountryLocalization("cy", "དབྱིན་ཇིའི་སྐད།", "Cyprus"),
  CountryLocalization("cz", "Czech", "Czechia"),
  CountryLocalization("ci", "French", "Côte d’Ivoire"),
  CountryLocalization("dk", "དབྱིན་ཇིའི་སྐད།", "Denmark"),
  CountryLocalization("dg", "དབྱིན་ཇིའི་སྐད།", "DG"),
  CountryLocalization("dj", "French", "Djibouti"),
  CountryLocalization("dm", "དབྱིན་ཇིའི་སྐད།", "Dominica"),
  CountryLocalization("do", "Spanish", "Dominican Republic"),
  CountryLocalization("ec", "Quechua", "Ecuador"),
  CountryLocalization("eg", "Arabic", "Egypt"),
  CountryLocalization("sv", "Spanish", "El Salvador"),
  CountryLocalization("gq", "Spanish", "Equatorial Guinea"),
  CountryLocalization("er", "Tigrinya", "Eritrea"),
  CountryLocalization("ee", "Estonian", "Estonia"),
  CountryLocalization("et", "Amharic", "Ethiopia"),
  CountryLocalization("fk", "དབྱིན་ཇིའི་སྐད།", "Falkland Islands"),
  CountryLocalization("fo", "Faroese", "Faroe Islands"),
  CountryLocalization("fj", "དབྱིན་ཇིའི་སྐད།", "Fiji"),
  CountryLocalization("fi", "Swedish", "Finland"),
  CountryLocalization("fr", "Swiss German", "France"),
  CountryLocalization("gf", "French", "French Guiana"),
  CountryLocalization("pf", "French", "French Polynesia"),
  CountryLocalization("ga", "French", "Gabon"),
  CountryLocalization("gm", "དབྱིན་ཇིའི་སྐད།", "Gambia"),
  CountryLocalization("ge", "Ossetic", "Georgia"),
  CountryLocalization("de", "Lower Sorbian", "འཇར་མན་"),
  CountryLocalization("gh", "དབྱིན་ཇིའི་སྐད།", "Ghana"),
  CountryLocalization("gi", "དབྱིན་ཇིའི་སྐད།", "Gibraltar"),
  CountryLocalization("gr", "Greek", "Greece"),
  CountryLocalization("gl", "Kalaallisut", "Greenland"),
  CountryLocalization("gd", "དབྱིན་ཇིའི་སྐད།", "Grenada"),
  CountryLocalization("gp", "French", "Guadeloupe"),
  CountryLocalization("gu", "དབྱིན་ཇིའི་སྐད།", "Guam"),
  CountryLocalization("gt", "Spanish", "Guatemala"),
  CountryLocalization("gg", "དབྱིན་ཇིའི་སྐད།", "Guernsey"),
  CountryLocalization("gn", "French", "Guinea"),
  CountryLocalization("gw", "Portuguese", "Guinea-Bissau"),
  CountryLocalization("gy", "དབྱིན་ཇིའི་སྐད།", "Guyana"),
  CountryLocalization("ht", "French", "Haiti"),
  CountryLocalization("hn", "Spanish", "Honduras"),
  CountryLocalization("hk", "རྒྱ་སྐད་", "Hong Kong SAR China"),
  CountryLocalization("hu", "Hungarian", "Hungary"),
  CountryLocalization("is", "Icelandic", "Iceland"),
  CountryLocalization("in", "ནེ་པ་ལི", "རྒྱ་གར་"),
  CountryLocalization("id", "Indonesian", "Indonesia"),
  CountryLocalization("ir", "Persian", "Iran"),
  CountryLocalization("iq", "lrc", "Iraq"),
  CountryLocalization("ie", "དབྱིན་ཇིའི་སྐད།", "Ireland"),
  CountryLocalization("im", "Manx", "Isle of Man"),
  CountryLocalization("il", "དབྱིན་ཇིའི་སྐད།", "Israel"),
  CountryLocalization("it", "German", "ཨི་ཀྲར་ལི་"),
  CountryLocalization("jm", "དབྱིན་ཇིའི་སྐད།", "Jamaica"),
  CountryLocalization("jp", "ཉི་ཧོང་སྐད་", "ཉི་ཧོང་"),
  CountryLocalization("je", "དབྱིན་ཇིའི་སྐད།", "Jersey"),
  CountryLocalization("jo", "Arabic", "Jordan"),
  CountryLocalization("kz", "Kazakh", "Kazakhstan"),
  CountryLocalization("ke", "Somali", "Kenya"),
  CountryLocalization("ki", "དབྱིན་ཇིའི་སྐད།", "Kiribati"),
  CountryLocalization("xk", "Serbian", "XK"),
  CountryLocalization("kw", "Arabic", "Kuwait"),
  CountryLocalization("kg", "ཨུ་རུ་སུ་སྐད་", "Kyrgyzstan"),
  CountryLocalization("la", "Lao", "Laos"),
  CountryLocalization("lv", "Latvian", "Latvia"),
  CountryLocalization("lb", "Arabic", "Lebanon"),
  CountryLocalization("ls", "དབྱིན་ཇིའི་སྐད།", "Lesotho"),
  CountryLocalization("lr", "དབྱིན་ཇིའི་སྐད།", "Liberia"),
  CountryLocalization("ly", "Arabic", "Libya"),
  CountryLocalization("li", "Swiss German", "Liechtenstein"),
  CountryLocalization("lt", "Lithuanian", "Lithuania"),
  CountryLocalization("lu", "Luxembourgish", "Luxembourg"),
  CountryLocalization("mo", "Portuguese", "Macao SAR China"),
  CountryLocalization("mk", "Albanian", "North Macedonia"),
  CountryLocalization("mg", "French", "Madagascar"),
  CountryLocalization("mw", "དབྱིན་ཇིའི་སྐད།", "Malawi"),
  CountryLocalization("my", "Tamil", "Malaysia"),
  CountryLocalization("ml", "French", "Mali"),
  CountryLocalization("mt", "དབྱིན་ཇིའི་སྐད།", "Malta"),
  CountryLocalization("mh", "དབྱིན་ཇིའི་སྐད།", "Marshall Islands"),
  CountryLocalization("mq", "French", "Martinique"),
  CountryLocalization("mr", "Arabic", "Mauritania"),
  CountryLocalization("mu", "mfe", "Mauritius"),
  CountryLocalization("yt", "French", "Mayotte"),
  CountryLocalization("mx", "Spanish", "Mexico"),
  CountryLocalization("fm", "དབྱིན་ཇིའི་སྐད།", "Micronesia"),
  CountryLocalization("md", "ཨུ་རུ་སུ་སྐད་", "Moldova"),
  CountryLocalization("mc", "French", "Monaco"),
  CountryLocalization("mn", "Mongolian", "Mongolia"),
  CountryLocalization("me", "Serbian", "Montenegro"),
  CountryLocalization("ms", "དབྱིན་ཇིའི་སྐད།", "Montserrat"),
  CountryLocalization("ma", "tzm", "Morocco"),
  CountryLocalization("mz", "mgh", "Mozambique"),
  CountryLocalization("mm", "Burmese", "Myanmar (Burma)"),
  CountryLocalization("na", "དབྱིན་ཇིའི་སྐད།", "Namibia"),
  CountryLocalization("nr", "དབྱིན་ཇིའི་སྐད།", "Nauru"),
  CountryLocalization("np", "ནེ་པ་ལི", "བལ་ཡུལ་"),
  CountryLocalization("nl", "དབྱིན་ཇིའི་སྐད།", "Netherlands"),
  CountryLocalization("nc", "French", "New Caledonia"),
  CountryLocalization("nz", "དབྱིན་ཇིའི་སྐད།", "New Zealand"),
  CountryLocalization("ni", "Spanish", "Nicaragua"),
  CountryLocalization("ne", "Hausa", "Niger"),
  CountryLocalization("ng", "Hausa", "Nigeria"),
  CountryLocalization("nu", "དབྱིན་ཇིའི་སྐད།", "Niue"),
  CountryLocalization("nf", "དབྱིན་ཇིའི་སྐད།", "Norfolk Island"),
  CountryLocalization("kp", "Korean", "North Korea"),
  CountryLocalization("mp", "དབྱིན་ཇིའི་སྐད།", "Northern Mariana Islands"),
  CountryLocalization("no", "Northern Sami", "Norway"),
  CountryLocalization("om", "Arabic", "Oman"),
  CountryLocalization("pk", "དབྱིན་ཇིའི་སྐད།", "Pakistan"),
  CountryLocalization("pw", "དབྱིན་ཇིའི་སྐད།", "Palau"),
  CountryLocalization("ps", "Arabic", "Palestinian Territories"),
  CountryLocalization("pa", "Spanish", "Panama"),
  CountryLocalization("pg", "དབྱིན་ཇིའི་སྐད།", "Papua New Guinea"),
  CountryLocalization("py", "Spanish", "Paraguay"),
  CountryLocalization("pe", "Spanish", "Peru"),
  CountryLocalization("ph", "Filipino", "Philippines"),
  CountryLocalization("pn", "དབྱིན་ཇིའི་སྐད།", "Pitcairn Islands"),
  CountryLocalization("pl", "Polish", "Poland"),
  CountryLocalization("pt", "Portuguese", "Portugal"),
  CountryLocalization("pr", "དབྱིན་ཇིའི་སྐད།", "Puerto Rico"),
  CountryLocalization("qa", "Arabic", "Qatar"),
  CountryLocalization("ro", "Romanian", "Romania"),
  CountryLocalization("ru", "Tatar", "ཨུ་རུ་སུ་"),
  CountryLocalization("rw", "དབྱིན་ཇིའི་སྐད།", "Rwanda"),
  CountryLocalization("re", "French", "Réunion"),
  CountryLocalization("ws", "དབྱིན་ཇིའི་སྐད།", "Samoa"),
  CountryLocalization("sm", "Italian", "San Marino"),
  CountryLocalization("sa", "Arabic", "Saudi Arabia"),
  CountryLocalization("sn", "French", "Senegal"),
  CountryLocalization("rs", "Serbian", "Serbia"),
  CountryLocalization("cs", "Serbian", "Serbia and Montenegro"),
  CountryLocalization("sc", "French", "Seychelles"),
  CountryLocalization("sl", "དབྱིན་ཇིའི་སྐད།", "Sierra Leone"),
  CountryLocalization("sg", "Tamil", "Singapore"),
  CountryLocalization("sx", "དབྱིན་ཇིའི་སྐད།", "Sint Maarten"),
  CountryLocalization("sk", "Slovak", "Slovakia"),
  CountryLocalization("si", "Slovenian", "Slovenia"),
  CountryLocalization("sb", "དབྱིན་ཇིའི་སྐད།", "Solomon Islands"),
  CountryLocalization("so", "Arabic", "Somalia"),
  CountryLocalization("za", "དབྱིན་ཇིའི་སྐད།", "South Africa"),
  CountryLocalization("kr", "Korean", "ལྷོ་ཀོ་རི་ཡ།"),
  CountryLocalization("ss", "nus", "South Sudan"),
  CountryLocalization("es", "Spanish", "Spain"),
  CountryLocalization("lk", "Tamil", "Sri Lanka"),
  CountryLocalization("bl", "French", "St. Barthélemy"),
  CountryLocalization("sh", "དབྱིན་ཇིའི་སྐད།", "St. Helena"),
  CountryLocalization("kn", "དབྱིན་ཇིའི་སྐད།", "St. Kitts & Nevis"),
  CountryLocalization("lc", "དབྱིན་ཇིའི་སྐད།", "St. Lucia"),
  CountryLocalization("mf", "French", "St. Martin"),
  CountryLocalization("pm", "French", "St. Pierre & Miquelon"),
  CountryLocalization("vc", "དབྱིན་ཇིའི་སྐད།", "St. Vincent & Grenadines"),
  CountryLocalization("sd", "Arabic", "Sudan"),
  CountryLocalization("sr", "Dutch", "Suriname"),
  CountryLocalization("sj", "Norwegian Bokmål", "Svalbard & Jan Mayen"),
  CountryLocalization("sz", "དབྱིན་ཇིའི་སྐད།", "Eswatini"),
  CountryLocalization("se", "Swedish", "Sweden"),
  CountryLocalization("ch", "Swiss German", "Switzerland"),
  CountryLocalization("sy", "Arabic", "Syria"),
  CountryLocalization("st", "Portuguese", "São Tomé & Príncipe"),
  CountryLocalization("tw", "རྒྱ་སྐད་", "Taiwan"),
  CountryLocalization("tj", "Tajik", "Tajikistan"),
  CountryLocalization("tz", "kde", "Tanzania"),
  CountryLocalization("th", "Thai", "Thailand"),
  CountryLocalization("tl", "Portuguese", "Timor-Leste"),
  CountryLocalization("tg", "French", "Togo"),
  CountryLocalization("tk", "དབྱིན་ཇིའི་སྐད།", "Tokelau"),
  CountryLocalization("to", "Tongan", "Tonga"),
  CountryLocalization("tt", "དབྱིན་ཇིའི་སྐད།", "Trinidad & Tobago"),
  CountryLocalization("tn", "French", "Tunisia"),
  CountryLocalization("tr", "Turkish", "Turkey"),
  CountryLocalization("tm", "Turkmen", "Turkmenistan"),
  CountryLocalization("tc", "དབྱིན་ཇིའི་སྐད།", "Turks & Caicos Islands"),
  CountryLocalization("tv", "དབྱིན་ཇིའི་སྐད།", "Tuvalu"),
  CountryLocalization("um", "དབྱིན་ཇིའི་སྐད།", "U.S. Outlying Islands"),
  CountryLocalization("vi", "དབྱིན་ཇིའི་སྐད།", "U.S. Virgin Islands"),
  CountryLocalization("ug", "Swahili", "Uganda"),
  CountryLocalization("ua", "Ukrainian", "Ukraine"),
  CountryLocalization("ae", "Arabic", "United Arab Emirates"),
  CountryLocalization("gb", "དབྱིན་ཇིའི་སྐད།", "དབྱིན་ཇི་"),
  CountryLocalization("us", "lkt", "ཨ་མེ་རི་ཀ།"),
  CountryLocalization("uy", "Spanish", "Uruguay"),
  CountryLocalization("uz", "Uzbek", "Uzbekistan"),
  CountryLocalization("vu", "French", "Vanuatu"),
  CountryLocalization("va", "Italian", "Vatican City"),
  CountryLocalization("ve", "Spanish", "Venezuela"),
  CountryLocalization("vn", "Vietnamese", "Vietnam"),
  CountryLocalization("wf", "French", "Wallis & Futuna"),
  CountryLocalization("eh", "Arabic", "Western Sahara"),
  CountryLocalization("ye", "Arabic", "Yemen"),
  CountryLocalization("zm", "དབྱིན་ཇིའི་སྐད།", "Zambia"),
  CountryLocalization("zw", "North Ndebele", "Zimbabwe"),
  CountryLocalization("ax", "Swedish", "Åland Islands"),
)
