/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot.atlas.extended

import dev.teogor.xenoglot.atlas.CountryLocalization
import kotlin.collections.List

/**
 * Holds the internal list of country-language mappings used for lookups within the package for
 * language code qu.
 *
 * This property contains a hardcoded list of [CountryLocalization] objects, each representing
 * a country and its associated official languages. This list is used by [CountryLanguageRegistry]
 * to provide access to country-language data and should not be modified directly.
 *
 * @see CountryLocalization
 * @see CountryLanguageRegistry
 */
internal val _countryLanguageMappings_qu: List<CountryLocalization> = listOf(
  CountryLocalization("af", "Persa Simi", "Afganistán"),
  CountryLocalization("al", "Albanes Simi", "Albania"),
  CountryLocalization("dz", "Frances Simi", "Argelia"),
  CountryLocalization("as", "Ingles Simi", "Samoa Americana"),
  CountryLocalization("ad", "Catalan Simi", "Andorra"),
  CountryLocalization("ao", "Lingala", "Angola"),
  CountryLocalization("ai", "Ingles Simi", "Anguilla"),
  CountryLocalization("ag", "Ingles Simi", "Antigua & Barbuda"),
  CountryLocalization("ar", "Español Simi", "Argentina"),
  CountryLocalization("am", "Armenio Simi", "Armenia"),
  CountryLocalization("aw", "Neerlandes Simi", "Aruba"),
  CountryLocalization("au", "Ingles Simi", "Australia"),
  CountryLocalization("at", "Ingles Simi", "Austria"),
  CountryLocalization("az", "Azerbaiyano Simi", "Azerbaiyán"),
  CountryLocalization("bs", "Ingles Simi", "Bahamas"),
  CountryLocalization("bh", "Arabe Simi", "Baréin"),
  CountryLocalization("bd", "Bangla Simi", "Bangladesh"),
  CountryLocalization("bb", "Ingles Simi", "Barbados"),
  CountryLocalization("by", "Bielorruso Simi", "Belarús"),
  CountryLocalization("be", "Frances Simi", "Bélgica"),
  CountryLocalization("bz", "Ingles Simi", "Belize"),
  CountryLocalization("bj", "Frances Simi", "Benín"),
  CountryLocalization("bm", "Ingles Simi", "Bermuda"),
  CountryLocalization("bt", "Dzongkha", "Bután"),
  CountryLocalization("bo", "Español Simi", "Bolivia"),
  CountryLocalization("ba", "Bosnio Simi", "Bosnia & Herzegovina"),
  CountryLocalization("bw", "Ingles Simi", "Botsuana"),
  CountryLocalization("br", "Portugues Simi", "Brasil"),
  CountryLocalization("io", "Ingles Simi", "British Indian Ocean Territory"),
  CountryLocalization("vg", "Ingles Simi", "British Virgin Islands"),
  CountryLocalization("bn", "Malayo Simi", "Brunéi"),
  CountryLocalization("bg", "Bulgaro Simi", "Bulgaria"),
  CountryLocalization("bf", "Frances Simi", "Burkina Faso"),
  CountryLocalization("bi", "Frances Simi", "Burundi"),
  CountryLocalization("kh", "Khmer Simi", "Camboya"),
  CountryLocalization("cm", "Basaa", "Camerún"),
  CountryLocalization("ca", "Frances Simi", "Canada"),
  CountryLocalization("ic", "Español Simi", "IC"),
  CountryLocalization("cv", "kea", "Cape Verde"),
  CountryLocalization("bq", "Neerlandes Simi", "Bonaire"),
  CountryLocalization("ky", "Ingles Simi", "Cayman Islands"),
  CountryLocalization("cf", "Lingala", "Central African Republic"),
  CountryLocalization("ea", "Español Simi", "EA"),
  CountryLocalization("td", "Arabe Simi", "Chad"),
  CountryLocalization("cl", "Español Simi", "Chile"),
  CountryLocalization("cn", "Tibetano Simi", "China"),
  CountryLocalization("cx", "Ingles Simi", "Isla Christmas"),
  CountryLocalization("cc", "Ingles Simi", "Islas Cocos"),
  CountryLocalization("co", "Español Simi", "Colombia"),
  CountryLocalization("km", "Arabe Simi", "Comoras"),
  CountryLocalization("cg", "Lingala", "Congo"),
  CountryLocalization("cd", "Suajili Simi", "Congo (RDC)"),
  CountryLocalization("ck", "Ingles Simi", "Cook Islands"),
  CountryLocalization("cr", "Español Simi", "Costa Rica"),
  CountryLocalization("hr", "Croata Simi", "Croacia"),
  CountryLocalization("cu", "Español Simi", "Cuba"),
  CountryLocalization("cw", "Neerlandes Simi", "Curazao"),
  CountryLocalization("cy", "Ingles Simi", "Chipre"),
  CountryLocalization("cz", "Checo Simi", "Czechia"),
  CountryLocalization("ci", "Frances Simi", "Côte d’Ivoire"),
  CountryLocalization("dk", "Ingles Simi", "Dinamarca"),
  CountryLocalization("dg", "Ingles Simi", "DG"),
  CountryLocalization("dj", "Frances Simi", "Yibuti"),
  CountryLocalization("dm", "Ingles Simi", "Dominica"),
  CountryLocalization("do", "Español Simi", "Dominican Republic"),
  CountryLocalization("ec", "Runasimi", "Ecuador"),
  CountryLocalization("eg", "Arabe Simi", "Egipto"),
  CountryLocalization("sv", "Español Simi", "El Salvador"),
  CountryLocalization("gq", "Español Simi", "Guinea Ecuatorial"),
  CountryLocalization("er", "Tigriña Simi", "Eritrea"),
  CountryLocalization("ee", "Estonio Simi", "Estonia"),
  CountryLocalization("et", "Amarico Simi", "Etiopía"),
  CountryLocalization("fk", "Ingles Simi", "Falkland Islands"),
  CountryLocalization("fo", "Feroes Simi", "Faroe Islands"),
  CountryLocalization("fj", "Ingles Simi", "Fiyi"),
  CountryLocalization("fi", "Sueco Simi", "Finlandia"),
  CountryLocalization("fr", "Alsaciano Simi", "Francia"),
  CountryLocalization("gf", "Frances Simi", "French Guiana"),
  CountryLocalization("pf", "Frances Simi", "Polinesia Francesa"),
  CountryLocalization("ga", "Frances Simi", "Gabón"),
  CountryLocalization("gm", "Ingles Simi", "Gambia"),
  CountryLocalization("ge", "Ossetic", "Georgia"),
  CountryLocalization("de", "Bajo Sorbio Simi", "Alemania"),
  CountryLocalization("gh", "Ingles Simi", "Ghana"),
  CountryLocalization("gi", "Ingles Simi", "Gibraltar"),
  CountryLocalization("gr", "Griego Simi", "Grecia"),
  CountryLocalization("gl", "Groenlandes Simi", "Greenland"),
  CountryLocalization("gd", "Ingles Simi", "Grenada"),
  CountryLocalization("gp", "Frances Simi", "Guadeloupe"),
  CountryLocalization("gu", "Ingles Simi", "Guam"),
  CountryLocalization("gt", "Español Simi", "Guatemala"),
  CountryLocalization("gg", "Ingles Simi", "Guernesey"),
  CountryLocalization("gn", "Frances Simi", "Guinea"),
  CountryLocalization("gw", "Portugues Simi", "Guinea-Bisáu"),
  CountryLocalization("gy", "Ingles Simi", "Guyana"),
  CountryLocalization("ht", "Frances Simi", "Haití"),
  CountryLocalization("hn", "Español Simi", "Honduras"),
  CountryLocalization("hk", "Chino Simi", "Hong Kong (RAE)"),
  CountryLocalization("hu", "Hungaro Simi", "Hungary"),
  CountryLocalization("is", "Islandes Simi", "Islandia"),
  CountryLocalization("in", "Nepali Simi", "India"),
  CountryLocalization("id", "Indonesian", "Indonesia"),
  CountryLocalization("ir", "Persa Simi", "Irán"),
  CountryLocalization("iq", "lrc", "Irak"),
  CountryLocalization("ie", "Ingles Simi", "Ireland"),
  CountryLocalization("im", "Manx", "Isle of Man"),
  CountryLocalization("il", "Ingles Simi", "Israel"),
  CountryLocalization("it", "Aleman Simi", "Italia"),
  CountryLocalization("jm", "Ingles Simi", "Jamaica"),
  CountryLocalization("jp", "Japones Simi", "Japan"),
  CountryLocalization("je", "Ingles Simi", "Jersey"),
  CountryLocalization("jo", "Arabe Simi", "Jordania"),
  CountryLocalization("kz", "Kazajo Simi", "Kazajistán"),
  CountryLocalization("ke", "Somali", "Kenia"),
  CountryLocalization("ki", "Ingles Simi", "Kiribati"),
  CountryLocalization("xk", "Serbio Simi", "XK"),
  CountryLocalization("kw", "Arabe Simi", "Kuwait"),
  CountryLocalization("kg", "Ruso Simi", "Kirguistán"),
  CountryLocalization("la", "Lao Simi", "Laos"),
  CountryLocalization("lv", "Leton Simi", "Letonia"),
  CountryLocalization("lb", "Arabe Simi", "Líbano"),
  CountryLocalization("ls", "Ingles Simi", "Lesoto"),
  CountryLocalization("lr", "Ingles Simi", "Liberia"),
  CountryLocalization("ly", "Arabe Simi", "Libya"),
  CountryLocalization("li", "Alsaciano Simi", "Liechtenstein"),
  CountryLocalization("lt", "Lituano Simi", "Lituania"),
  CountryLocalization("lu", "Luxemburgues Simi", "Luxemburgo"),
  CountryLocalization("mo", "Portugues Simi", "Macao RAE"),
  CountryLocalization("mk", "Albanes Simi", "ERY Macedonia"),
  CountryLocalization("mg", "Frances Simi", "Madagascar"),
  CountryLocalization("mw", "Ingles Simi", "Malawi"),
  CountryLocalization("my", "Tamil Simi", "Malaysia"),
  CountryLocalization("ml", "Frances Simi", "Malí"),
  CountryLocalization("mt", "Ingles Simi", "Malta"),
  CountryLocalization("mh", "Ingles Simi", "Islas Marshall"),
  CountryLocalization("mq", "Frances Simi", "Martinique"),
  CountryLocalization("mr", "Arabe Simi", "Mauritania"),
  CountryLocalization("mu", "mfe", "Mauricio"),
  CountryLocalization("yt", "Frances Simi", "Mayotte"),
  CountryLocalization("mx", "Español Simi", "México"),
  CountryLocalization("fm", "Ingles Simi", "Micronesia"),
  CountryLocalization("md", "Ruso Simi", "Moldova"),
  CountryLocalization("mc", "Frances Simi", "Mónaco"),
  CountryLocalization("mn", "Mongol Simi", "Mongolia"),
  CountryLocalization("me", "Serbio Simi", "Montenegro"),
  CountryLocalization("ms", "Ingles Simi", "Montserrat"),
  CountryLocalization("ma", "tzm", "Marruecos"),
  CountryLocalization("mz", "mgh", "Mozambique"),
  CountryLocalization("mm", "Burmese", "Myanmar"),
  CountryLocalization("na", "Ingles Simi", "Namibia"),
  CountryLocalization("nr", "Ingles Simi", "Nauru"),
  CountryLocalization("np", "Nepali Simi", "Nepal"),
  CountryLocalization("nl", "Ingles Simi", "Países Bajos"),
  CountryLocalization("nc", "Frances Simi", "Nueva Caledonia"),
  CountryLocalization("nz", "Ingles Simi", "New Zealand"),
  CountryLocalization("ni", "Español Simi", "Nicaragua"),
  CountryLocalization("ne", "Hausa Simi", "Níger"),
  CountryLocalization("ng", "Hausa Simi", "Nigeria"),
  CountryLocalization("nu", "Ingles Simi", "Niue"),
  CountryLocalization("nf", "Ingles Simi", "Isla Norfolk"),
  CountryLocalization("kp", "Coreano Simi", "Corea del Norte"),
  CountryLocalization("mp", "Ingles Simi", "Islas Marianas del Norte"),
  CountryLocalization("no", "Chincha Sami Simi", "Noruega"),
  CountryLocalization("om", "Arabe Simi", "Omán"),
  CountryLocalization("pk", "Ingles Simi", "Pakistán"),
  CountryLocalization("pw", "Ingles Simi", "Palaos"),
  CountryLocalization("ps", "Arabe Simi", "Palestina Kamachikuq"),
  CountryLocalization("pa", "Español Simi", "Panamá"),
  CountryLocalization("pg", "Ingles Simi", "Papúa Nueva Guinea"),
  CountryLocalization("py", "Español Simi", "Paraguay"),
  CountryLocalization("pe", "Español Simi", "Perú"),
  CountryLocalization("ph", "Filipino Simi", "Filipinas"),
  CountryLocalization("pn", "Ingles Simi", "Islas Pitcairn"),
  CountryLocalization("pl", "Polaco Simi", "Polonia"),
  CountryLocalization("pt", "Portugues Simi", "Portugal"),
  CountryLocalization("pr", "Ingles Simi", "Puerto Rico"),
  CountryLocalization("qa", "Arabe Simi", "Qatar"),
  CountryLocalization("ro", "Rumano Simi", "Romania"),
  CountryLocalization("ru", "Tartaro Simi", "Rusia"),
  CountryLocalization("rw", "Ingles Simi", "Ruanda"),
  CountryLocalization("re", "Frances Simi", "Réunion"),
  CountryLocalization("ws", "Ingles Simi", "Samoa"),
  CountryLocalization("sm", "Italiano Simi", "San Marino"),
  CountryLocalization("sa", "Arabe Simi", "Arabia Saudí"),
  CountryLocalization("sn", "Frances Simi", "Senegal"),
  CountryLocalization("rs", "Serbio Simi", "Serbia"),
  CountryLocalization("cs", "Serbio Simi", "Serbia and Montenegro"),
  CountryLocalization("sc", "Frances Simi", "Seychelles"),
  CountryLocalization("sl", "Ingles Simi", "Sierra Leona"),
  CountryLocalization("sg", "Tamil Simi", "Singapur"),
  CountryLocalization("sx", "Ingles Simi", "Sint Maarten"),
  CountryLocalization("sk", "Eslovaco Simi", "Eslovaquia"),
  CountryLocalization("si", "Esloveno Simi", "Eslovenia"),
  CountryLocalization("sb", "Ingles Simi", "Solomon Islands"),
  CountryLocalization("so", "Arabe Simi", "Somalia"),
  CountryLocalization("za", "Ingles Simi", "Sudáfrica"),
  CountryLocalization("kr", "Coreano Simi", "Corea del Sur"),
  CountryLocalization("ss", "nus", "Sudán del Sur"),
  CountryLocalization("es", "Español Simi", "España"),
  CountryLocalization("lk", "Tamil Simi", "Sri Lanka"),
  CountryLocalization("bl", "Frances Simi", "St. Barthélemy"),
  CountryLocalization("sh", "Ingles Simi", "St. Helena"),
  CountryLocalization("kn", "Ingles Simi", "San Cristóbal y Nieves"),
  CountryLocalization("lc", "Ingles Simi", "St. Lucia"),
  CountryLocalization("mf", "Frances Simi", "San Martín"),
  CountryLocalization("pm", "Frances Simi", "San Pedro y Miquelón"),
  CountryLocalization("vc", "Ingles Simi", "St. Vincent & Grenadines"),
  CountryLocalization("sd", "Arabe Simi", "Sudán"),
  CountryLocalization("sr", "Neerlandes Simi", "Surinam"),
  CountryLocalization("sj", "Norwegian Bokmål", "Svalbard & Jan Mayen"),
  CountryLocalization("sz", "Ingles Simi", "Suazilandia"),
  CountryLocalization("se", "Sueco Simi", "Suecia"),
  CountryLocalization("ch", "Alsaciano Simi", "Suiza"),
  CountryLocalization("sy", "Arabe Simi", "Siria"),
  CountryLocalization("st", "Portugues Simi", "Santo Tomé y Príncipe"),
  CountryLocalization("tw", "Chino Simi", "Taiwan"),
  CountryLocalization("tj", "Tayiko Simi", "Tayikistán"),
  CountryLocalization("tz", "kde", "Tanzania"),
  CountryLocalization("th", "Tailandes Simi", "Tailandia"),
  CountryLocalization("tl", "Portugues Simi", "Timor-Leste"),
  CountryLocalization("tg", "Frances Simi", "Togo"),
  CountryLocalization("tk", "Ingles Simi", "Tokelau"),
  CountryLocalization("to", "Tongan", "Tonga"),
  CountryLocalization("tt", "Ingles Simi", "Trinidad y Tobago"),
  CountryLocalization("tn", "Frances Simi", "Túnez"),
  CountryLocalization("tr", "Turco Simi", "Turquía"),
  CountryLocalization("tm", "Turcomano Simi", "Turkmenistan"),
  CountryLocalization("tc", "Ingles Simi", "Turks & Caicos Islands"),
  CountryLocalization("tv", "Ingles Simi", "Tuvalu"),
  CountryLocalization("um", "Ingles Simi", "Islas menores alejadas de los EE.UU."),
  CountryLocalization("vi", "Ingles Simi", "EE.UU. Islas Vírgenes"),
  CountryLocalization("ug", "Suajili Simi", "Uganda"),
  CountryLocalization("ua", "Ucraniano Simi", "Ukraine"),
  CountryLocalization("ae", "Arabe Simi", "United Arab Emirates"),
  CountryLocalization("gb", "Ingles Simi", "Reino Unido"),
  CountryLocalization("us", "lkt", "Estados Unidos"),
  CountryLocalization("uy", "Español Simi", "Uruguay"),
  CountryLocalization("uz", "Uzbeko Simi", "Uzbekistán"),
  CountryLocalization("vu", "Frances Simi", "Vanuatu"),
  CountryLocalization("va", "Italiano Simi", "Santa Sede (Ciudad del Vaticano)"),
  CountryLocalization("ve", "Español Simi", "Venezuela"),
  CountryLocalization("vn", "Vietnamita Simi", "Vietnam"),
  CountryLocalization("wf", "Frances Simi", "Wallis y Futuna"),
  CountryLocalization("eh", "Arabe Simi", "Western Sahara"),
  CountryLocalization("ye", "Arabe Simi", "Yemen"),
  CountryLocalization("zm", "Ingles Simi", "Zambia"),
  CountryLocalization("zw", "North Ndebele", "Zimbabue"),
  CountryLocalization("ax", "Sueco Simi", "Åland Islands"),
)
