/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot.atlas.extended

import dev.teogor.xenoglot.atlas.CountryLocalization
import kotlin.collections.List

/**
 * Holds the internal list of country-language mappings used for lookups within the package for
 * language code sv.
 *
 * This property contains a hardcoded list of [CountryLocalization] objects, each representing
 * a country and its associated official languages. This list is used by [CountryLanguageRegistry]
 * to provide access to country-language data and should not be modified directly.
 *
 * @see CountryLocalization
 * @see CountryLanguageRegistry
 */
internal val _countryLanguageMappings_sv: List<CountryLocalization> = listOf(
  CountryLocalization("af", "persiska", "Afghanistan"),
  CountryLocalization("al", "albanska", "Albanien"),
  CountryLocalization("dz", "franska", "Algeriet"),
  CountryLocalization("as", "engelska", "Amerikanska Samoa"),
  CountryLocalization("ad", "katalanska", "Andorra"),
  CountryLocalization("ao", "lingala", "Angola"),
  CountryLocalization("ai", "engelska", "Anguilla"),
  CountryLocalization("ag", "engelska", "Antigua och Barbuda"),
  CountryLocalization("ar", "spanska", "Argentina"),
  CountryLocalization("am", "armeniska", "Armenien"),
  CountryLocalization("aw", "nederländska", "Aruba"),
  CountryLocalization("au", "engelska", "Australien"),
  CountryLocalization("at", "engelska", "Österrike"),
  CountryLocalization("az", "azerbajdzjanska", "Azerbajdzjan"),
  CountryLocalization("bs", "engelska", "Bahamas"),
  CountryLocalization("bh", "arabiska", "Bahrain"),
  CountryLocalization("bd", "bengali", "Bangladesh"),
  CountryLocalization("bb", "engelska", "Barbados"),
  CountryLocalization("by", "vitryska", "Vitryssland"),
  CountryLocalization("be", "franska", "Belgien"),
  CountryLocalization("bz", "engelska", "Belize"),
  CountryLocalization("bj", "franska", "Benin"),
  CountryLocalization("bm", "engelska", "Bermuda"),
  CountryLocalization("bt", "dzongkha", "Bhutan"),
  CountryLocalization("bo", "spanska", "Bolivia"),
  CountryLocalization("ba", "bosniska", "Bosnien och Hercegovina"),
  CountryLocalization("bw", "engelska", "Botswana"),
  CountryLocalization("br", "portugisiska", "Brasilien"),
  CountryLocalization("io", "engelska", "Brittiska territoriet i Indiska oceanen"),
  CountryLocalization("vg", "engelska", "Brittiska Jungfruöarna"),
  CountryLocalization("bn", "malajiska", "Brunei"),
  CountryLocalization("bg", "bulgariska", "Bulgarien"),
  CountryLocalization("bf", "franska", "Burkina Faso"),
  CountryLocalization("bi", "franska", "Burundi"),
  CountryLocalization("kh", "kambodjanska", "Kambodja"),
  CountryLocalization("cm", "basa", "Kamerun"),
  CountryLocalization("ca", "franska", "Kanada"),
  CountryLocalization("ic", "spanska", "Kanarieöarna"),
  CountryLocalization("cv", "kapverdiska", "Kap Verde"),
  CountryLocalization("bq", "nederländska", "Karibiska Nederländerna"),
  CountryLocalization("ky", "engelska", "Caymanöarna"),
  CountryLocalization("cf", "lingala", "Centralafrikanska republiken"),
  CountryLocalization("ea", "spanska", "Ceuta och Melilla"),
  CountryLocalization("td", "arabiska", "Tchad"),
  CountryLocalization("cl", "spanska", "Chile"),
  CountryLocalization("cn", "tibetanska", "Kina"),
  CountryLocalization("cx", "engelska", "Julön"),
  CountryLocalization("cc", "engelska", "Kokosöarna"),
  CountryLocalization("co", "spanska", "Colombia"),
  CountryLocalization("km", "arabiska", "Komorerna"),
  CountryLocalization("cg", "lingala", "Kongo-Brazzaville"),
  CountryLocalization("cd", "swahili", "Kongo-Kinshasa"),
  CountryLocalization("ck", "engelska", "Cooköarna"),
  CountryLocalization("cr", "spanska", "Costa Rica"),
  CountryLocalization("hr", "kroatiska", "Kroatien"),
  CountryLocalization("cu", "spanska", "Kuba"),
  CountryLocalization("cw", "nederländska", "Curaçao"),
  CountryLocalization("cy", "engelska", "Cypern"),
  CountryLocalization("cz", "tjeckiska", "Tjeckien"),
  CountryLocalization("ci", "franska", "Elfenbenskusten"),
  CountryLocalization("dk", "engelska", "Danmark"),
  CountryLocalization("dg", "engelska", "Diego Garcia"),
  CountryLocalization("dj", "franska", "Djibouti"),
  CountryLocalization("dm", "engelska", "Dominica"),
  CountryLocalization("do", "spanska", "Dominikanska republiken"),
  CountryLocalization("ec", "quechua", "Ecuador"),
  CountryLocalization("eg", "arabiska", "Egypten"),
  CountryLocalization("sv", "spanska", "El Salvador"),
  CountryLocalization("gq", "spanska", "Ekvatorialguinea"),
  CountryLocalization("er", "tigrinja", "Eritrea"),
  CountryLocalization("ee", "estniska", "Estland"),
  CountryLocalization("et", "amhariska", "Etiopien"),
  CountryLocalization("fk", "engelska", "Falklandsöarna"),
  CountryLocalization("fo", "färöiska", "Färöarna"),
  CountryLocalization("fj", "engelska", "Fiji"),
  CountryLocalization("fi", "svenska", "Finland"),
  CountryLocalization("fr", "schweizertyska", "Frankrike"),
  CountryLocalization("gf", "franska", "Franska Guyana"),
  CountryLocalization("pf", "franska", "Franska Polynesien"),
  CountryLocalization("ga", "franska", "Gabon"),
  CountryLocalization("gm", "engelska", "Gambia"),
  CountryLocalization("ge", "ossetiska", "Georgien"),
  CountryLocalization("de", "lågsorbiska", "Tyskland"),
  CountryLocalization("gh", "engelska", "Ghana"),
  CountryLocalization("gi", "engelska", "Gibraltar"),
  CountryLocalization("gr", "grekiska", "Grekland"),
  CountryLocalization("gl", "grönländska", "Grönland"),
  CountryLocalization("gd", "engelska", "Grenada"),
  CountryLocalization("gp", "franska", "Guadeloupe"),
  CountryLocalization("gu", "engelska", "Guam"),
  CountryLocalization("gt", "spanska", "Guatemala"),
  CountryLocalization("gg", "engelska", "Guernsey"),
  CountryLocalization("gn", "franska", "Guinea"),
  CountryLocalization("gw", "portugisiska", "Guinea-Bissau"),
  CountryLocalization("gy", "engelska", "Guyana"),
  CountryLocalization("ht", "franska", "Haiti"),
  CountryLocalization("hn", "spanska", "Honduras"),
  CountryLocalization("hk", "kinesiska", "Hongkong"),
  CountryLocalization("hu", "ungerska", "Ungern"),
  CountryLocalization("is", "isländska", "Island"),
  CountryLocalization("in", "nepalesiska", "Indien"),
  CountryLocalization("id", "indonesiska", "Indonesien"),
  CountryLocalization("ir", "persiska", "Iran"),
  CountryLocalization("iq", "nordluri", "Irak"),
  CountryLocalization("ie", "engelska", "Irland"),
  CountryLocalization("im", "manx", "Isle of Man"),
  CountryLocalization("il", "engelska", "Israel"),
  CountryLocalization("it", "tyska", "Italien"),
  CountryLocalization("jm", "engelska", "Jamaica"),
  CountryLocalization("jp", "japanska", "Japan"),
  CountryLocalization("je", "engelska", "Jersey"),
  CountryLocalization("jo", "arabiska", "Jordanien"),
  CountryLocalization("kz", "kazakiska", "Kazakstan"),
  CountryLocalization("ke", "somaliska", "Kenya"),
  CountryLocalization("ki", "engelska", "Kiribati"),
  CountryLocalization("xk", "serbiska", "Kosovo"),
  CountryLocalization("kw", "arabiska", "Kuwait"),
  CountryLocalization("kg", "ryska", "Kirgizistan"),
  CountryLocalization("la", "laotiska", "Laos"),
  CountryLocalization("lv", "lettiska", "Lettland"),
  CountryLocalization("lb", "arabiska", "Libanon"),
  CountryLocalization("ls", "engelska", "Lesotho"),
  CountryLocalization("lr", "engelska", "Liberia"),
  CountryLocalization("ly", "arabiska", "Libyen"),
  CountryLocalization("li", "schweizertyska", "Liechtenstein"),
  CountryLocalization("lt", "litauiska", "Litauen"),
  CountryLocalization("lu", "luxemburgiska", "Luxemburg"),
  CountryLocalization("mo", "portugisiska", "Macao"),
  CountryLocalization("mk", "albanska", "Makedonien"),
  CountryLocalization("mg", "franska", "Madagaskar"),
  CountryLocalization("mw", "engelska", "Malawi"),
  CountryLocalization("my", "tamil", "Malaysia"),
  CountryLocalization("ml", "franska", "Mali"),
  CountryLocalization("mt", "engelska", "Malta"),
  CountryLocalization("mh", "engelska", "Marshallöarna"),
  CountryLocalization("mq", "franska", "Martinique"),
  CountryLocalization("mr", "arabiska", "Mauretanien"),
  CountryLocalization("mu", "mauritansk kreol", "Mauritius"),
  CountryLocalization("yt", "franska", "Mayotte"),
  CountryLocalization("mx", "spanska", "Mexiko"),
  CountryLocalization("fm", "engelska", "Mikronesien"),
  CountryLocalization("md", "ryska", "Moldavien"),
  CountryLocalization("mc", "franska", "Monaco"),
  CountryLocalization("mn", "mongoliska", "Mongoliet"),
  CountryLocalization("me", "serbiska", "Montenegro"),
  CountryLocalization("ms", "engelska", "Montserrat"),
  CountryLocalization("ma", "centralmarockansk tamazight", "Marocko"),
  CountryLocalization("mz", "makhuwa-meetto", "Moçambique"),
  CountryLocalization("mm", "burmesiska", "Myanmar (Burma)"),
  CountryLocalization("na", "engelska", "Namibia"),
  CountryLocalization("nr", "engelska", "Nauru"),
  CountryLocalization("np", "nepalesiska", "Nepal"),
  CountryLocalization("nl", "engelska", "Nederländerna"),
  CountryLocalization("nc", "franska", "Nya Kaledonien"),
  CountryLocalization("nz", "engelska", "Nya Zeeland"),
  CountryLocalization("ni", "spanska", "Nicaragua"),
  CountryLocalization("ne", "hausa", "Niger"),
  CountryLocalization("ng", "hausa", "Nigeria"),
  CountryLocalization("nu", "engelska", "Niue"),
  CountryLocalization("nf", "engelska", "Norfolkön"),
  CountryLocalization("kp", "koreanska", "Nordkorea"),
  CountryLocalization("mp", "engelska", "Nordmarianerna"),
  CountryLocalization("no", "nordsamiska", "Norge"),
  CountryLocalization("om", "arabiska", "Oman"),
  CountryLocalization("pk", "engelska", "Pakistan"),
  CountryLocalization("pw", "engelska", "Palau"),
  CountryLocalization("ps", "arabiska", "Palestinska territorierna"),
  CountryLocalization("pa", "spanska", "Panama"),
  CountryLocalization("pg", "engelska", "Papua Nya Guinea"),
  CountryLocalization("py", "spanska", "Paraguay"),
  CountryLocalization("pe", "spanska", "Peru"),
  CountryLocalization("ph", "filippinska", "Filippinerna"),
  CountryLocalization("pn", "engelska", "Pitcairnöarna"),
  CountryLocalization("pl", "polska", "Polen"),
  CountryLocalization("pt", "portugisiska", "Portugal"),
  CountryLocalization("pr", "engelska", "Puerto Rico"),
  CountryLocalization("qa", "arabiska", "Qatar"),
  CountryLocalization("ro", "rumänska", "Rumänien"),
  CountryLocalization("ru", "tatariska", "Ryssland"),
  CountryLocalization("rw", "engelska", "Rwanda"),
  CountryLocalization("re", "franska", "Réunion"),
  CountryLocalization("ws", "engelska", "Samoa"),
  CountryLocalization("sm", "italienska", "San Marino"),
  CountryLocalization("sa", "arabiska", "Saudiarabien"),
  CountryLocalization("sn", "franska", "Senegal"),
  CountryLocalization("rs", "serbiska", "Serbien"),
  CountryLocalization("cs", "serbiska", "Serbien och Montenegro"),
  CountryLocalization("sc", "franska", "Seychellerna"),
  CountryLocalization("sl", "engelska", "Sierra Leone"),
  CountryLocalization("sg", "tamil", "Singapore"),
  CountryLocalization("sx", "engelska", "Sint Maarten"),
  CountryLocalization("sk", "slovakiska", "Slovakien"),
  CountryLocalization("si", "slovenska", "Slovenien"),
  CountryLocalization("sb", "engelska", "Salomonöarna"),
  CountryLocalization("so", "arabiska", "Somalia"),
  CountryLocalization("za", "engelska", "Sydafrika"),
  CountryLocalization("kr", "koreanska", "Sydkorea"),
  CountryLocalization("ss", "nuer", "Sydsudan"),
  CountryLocalization("es", "spanska", "Spanien"),
  CountryLocalization("lk", "tamil", "Sri Lanka"),
  CountryLocalization("bl", "franska", "S:t Barthélemy"),
  CountryLocalization("sh", "engelska", "S:t Helena"),
  CountryLocalization("kn", "engelska", "S:t Kitts och Nevis"),
  CountryLocalization("lc", "engelska", "S:t Lucia"),
  CountryLocalization("mf", "franska", "Saint-Martin"),
  CountryLocalization("pm", "franska", "S:t Pierre och Miquelon"),
  CountryLocalization("vc", "engelska", "S:t Vincent och Grenadinerna"),
  CountryLocalization("sd", "arabiska", "Sudan"),
  CountryLocalization("sr", "nederländska", "Surinam"),
  CountryLocalization("sj", "norskt bokmål", "Svalbard och Jan Mayen"),
  CountryLocalization("sz", "engelska", "Swaziland"),
  CountryLocalization("se", "svenska", "Sverige"),
  CountryLocalization("ch", "schweizertyska", "Schweiz"),
  CountryLocalization("sy", "arabiska", "Syrien"),
  CountryLocalization("st", "portugisiska", "São Tomé och Príncipe"),
  CountryLocalization("tw", "kinesiska", "Taiwan"),
  CountryLocalization("tj", "tadzjikiska", "Tadzjikistan"),
  CountryLocalization("tz", "makonde", "Tanzania"),
  CountryLocalization("th", "thailändska", "Thailand"),
  CountryLocalization("tl", "portugisiska", "Östtimor"),
  CountryLocalization("tg", "franska", "Togo"),
  CountryLocalization("tk", "engelska", "Tokelau"),
  CountryLocalization("to", "tonganska", "Tonga"),
  CountryLocalization("tt", "engelska", "Trinidad och Tobago"),
  CountryLocalization("tn", "franska", "Tunisien"),
  CountryLocalization("tr", "turkiska", "Turkiet"),
  CountryLocalization("tm", "turkmeniska", "Turkmenistan"),
  CountryLocalization("tc", "engelska", "Turks- och Caicosöarna"),
  CountryLocalization("tv", "engelska", "Tuvalu"),
  CountryLocalization("um", "engelska", "USA:s yttre öar"),
  CountryLocalization("vi", "engelska", "Amerikanska Jungfruöarna"),
  CountryLocalization("ug", "swahili", "Uganda"),
  CountryLocalization("ua", "ukrainska", "Ukraina"),
  CountryLocalization("ae", "arabiska", "Förenade Arabemiraten"),
  CountryLocalization("gb", "engelska", "Storbritannien"),
  CountryLocalization("us", "lakota", "USA"),
  CountryLocalization("uy", "spanska", "Uruguay"),
  CountryLocalization("uz", "uzbekiska", "Uzbekistan"),
  CountryLocalization("vu", "franska", "Vanuatu"),
  CountryLocalization("va", "italienska", "Vatikanstaten"),
  CountryLocalization("ve", "spanska", "Venezuela"),
  CountryLocalization("vn", "vietnamesiska", "Vietnam"),
  CountryLocalization("wf", "franska", "Wallis- och Futunaöarna"),
  CountryLocalization("eh", "arabiska", "Västsahara"),
  CountryLocalization("ye", "arabiska", "Jemen"),
  CountryLocalization("zm", "engelska", "Zambia"),
  CountryLocalization("zw", "nordndebele", "Zimbabwe"),
  CountryLocalization("ax", "svenska", "Åland"),
)
