/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot.atlas.extended

import dev.teogor.xenoglot.atlas.CountryLocalization
import kotlin.collections.List

/**
 * Holds the internal list of country-language mappings used for lookups within the package for
 * language code tt.
 *
 * This property contains a hardcoded list of [CountryLocalization] objects, each representing
 * a country and its associated official languages. This list is used by [CountryLanguageRegistry]
 * to provide access to country-language data and should not be modified directly.
 *
 * @see CountryLocalization
 * @see CountryLanguageRegistry
 */
internal val _countryLanguageMappings_tt: List<CountryLocalization> = listOf(
  CountryLocalization("af", "фарсы", "Әфганстан"),
  CountryLocalization("al", "албан", "Албания"),
  CountryLocalization("dz", "француз", "Алжир"),
  CountryLocalization("as", "инглиз", "Америка Самоасы"),
  CountryLocalization("ad", "каталан", "Андорра"),
  CountryLocalization("ao", "Lingala", "Ангола"),
  CountryLocalization("ai", "инглиз", "Ангилья"),
  CountryLocalization("ag", "инглиз", "Антигуа һәм Барбуда"),
  CountryLocalization("ar", "испан", "Аргентина"),
  CountryLocalization("am", "әрмән", "Әрмәнстан"),
  CountryLocalization("aw", "голланд", "Аруба"),
  CountryLocalization("au", "инглиз", "Австралия"),
  CountryLocalization("at", "инглиз", "Австрия"),
  CountryLocalization("az", "әзәрбайҗан", "Әзәрбайҗан"),
  CountryLocalization("bs", "инглиз", "Багам утраулары"),
  CountryLocalization("bh", "гарәп", "Бәхрәйн"),
  CountryLocalization("bd", "бенгали", "Бангладеш"),
  CountryLocalization("bb", "инглиз", "Барбадос"),
  CountryLocalization("by", "белорус", "Беларусь"),
  CountryLocalization("be", "француз", "Бельгия"),
  CountryLocalization("bz", "инглиз", "Белиз"),
  CountryLocalization("bj", "француз", "Бенин"),
  CountryLocalization("bm", "инглиз", "Бермуд утраулары"),
  CountryLocalization("bt", "дзонг-кха", "Бутан"),
  CountryLocalization("bo", "испан", "Боливия"),
  CountryLocalization("ba", "босния", "Босния һәм Герцеговина"),
  CountryLocalization("bw", "инглиз", "Ботсвана"),
  CountryLocalization("br", "португал", "Бразилия"),
  CountryLocalization("io", "инглиз", "Британиянең Һинд Океанындагы Территориясе"),
  CountryLocalization("vg", "инглиз", "Британия Виргин утраулары"),
  CountryLocalization("bn", "малай", "Бруней"),
  CountryLocalization("bg", "болгар", "Болгария"),
  CountryLocalization("bf", "француз", "Буркина-Фасо"),
  CountryLocalization("bi", "француз", "Бурунди"),
  CountryLocalization("kh", "кхмер", "Камбоджа"),
  CountryLocalization("cm", "Basaa", "Камерун"),
  CountryLocalization("ca", "француз", "Канада"),
  CountryLocalization("ic", "испан", "IC"),
  CountryLocalization("cv", "kea", "Кабо-Верде"),
  CountryLocalization("bq", "голланд", "Caribbean Netherlands"),
  CountryLocalization("ky", "инглиз", "Кайман утраулары"),
  CountryLocalization("cf", "Lingala", "Үзәк Африка Республикасы"),
  CountryLocalization("ea", "испан", "EA"),
  CountryLocalization("td", "гарәп", "Чад"),
  CountryLocalization("cl", "испан", "Чили"),
  CountryLocalization("cn", "тибет", "Кытай"),
  CountryLocalization("cx", "инглиз", "Раштуа утравы"),
  CountryLocalization("cc", "инглиз", "Кокос (Килинг) утраулары"),
  CountryLocalization("co", "испан", "Колумбия"),
  CountryLocalization("km", "гарәп", "Комор утраулары"),
  CountryLocalization("cg", "Lingala", "Congo - Brazzaville"),
  CountryLocalization("cd", "Swahili", "Congo - Kinshasa"),
  CountryLocalization("ck", "инглиз", "Кук утраулары"),
  CountryLocalization("cr", "испан", "Коста-Рика"),
  CountryLocalization("hr", "хорват", "Хорватия"),
  CountryLocalization("cu", "испан", "Куба"),
  CountryLocalization("cw", "голланд", "Кюрасао"),
  CountryLocalization("cy", "инглиз", "Кипр"),
  CountryLocalization("cz", "чех", "Чехия Республикасы"),
  CountryLocalization("ci", "француз", "Кот-д’Ивуар"),
  CountryLocalization("dk", "инглиз", "Дания"),
  CountryLocalization("dg", "инглиз", "DG"),
  CountryLocalization("dj", "француз", "Җибүти"),
  CountryLocalization("dm", "инглиз", "Доминика"),
  CountryLocalization("do", "испан", "Доминикана Республикасы"),
  CountryLocalization("ec", "кечуа", "Эквадор"),
  CountryLocalization("eg", "гарәп", "Мисыр"),
  CountryLocalization("sv", "испан", "Сальвадор"),
  CountryLocalization("gq", "испан", "Экваториаль Гвинея"),
  CountryLocalization("er", "тигринья", "Эритрея"),
  CountryLocalization("ee", "эстон", "Эстония"),
  CountryLocalization("et", "амхар", "Эфиопия"),
  CountryLocalization("fk", "инглиз", "Фолкленд утраулары"),
  CountryLocalization("fo", "фарер", "Фарер утраулары"),
  CountryLocalization("fj", "инглиз", "Фиджи"),
  CountryLocalization("fi", "швед", "Финляндия"),
  CountryLocalization("fr", "Swiss German", "Франция"),
  CountryLocalization("gf", "француз", "Француз Гвианасы"),
  CountryLocalization("pf", "француз", "Француз Полинезиясе"),
  CountryLocalization("ga", "француз", "Габон"),
  CountryLocalization("gm", "инглиз", "Гамбия"),
  CountryLocalization("ge", "Ossetic", "Грузия"),
  CountryLocalization("de", "түбән сорб", "Германия"),
  CountryLocalization("gh", "инглиз", "Гана"),
  CountryLocalization("gi", "инглиз", "Гибралтар"),
  CountryLocalization("gr", "грек", "Греция"),
  CountryLocalization("gl", "Kalaallisut", "Гренландия"),
  CountryLocalization("gd", "инглиз", "Гренада"),
  CountryLocalization("gp", "француз", "Гваделупа"),
  CountryLocalization("gu", "инглиз", "Гуам"),
  CountryLocalization("gt", "испан", "Гватемала"),
  CountryLocalization("gg", "инглиз", "Гернси"),
  CountryLocalization("gn", "француз", "Гвинея"),
  CountryLocalization("gw", "португал", "Гвинея-Бисау"),
  CountryLocalization("gy", "инглиз", "Гайана"),
  CountryLocalization("ht", "француз", "Гаити"),
  CountryLocalization("hn", "испан", "Гондурас"),
  CountryLocalization(
    "hk",
    "кытай (тәрҗемә киңәше: аерым алганда, мандарин кытайчасы)",
    "Гонконг Махсус Идарәле Төбәге",
  ),
  CountryLocalization("hu", "венгр", "Венгрия"),
  CountryLocalization("is", "исланд", "Исландия"),
  CountryLocalization("in", "непали", "Индия"),
  CountryLocalization("id", "Indonesian", "Индонезия"),
  CountryLocalization("ir", "фарсы", "Иран"),
  CountryLocalization("iq", "lrc", "Гыйрак"),
  CountryLocalization("ie", "инглиз", "Ирландия"),
  CountryLocalization("im", "Manx", "Мэн утравы"),
  CountryLocalization("il", "инглиз", "Израиль"),
  CountryLocalization("it", "алман", "Италия"),
  CountryLocalization("jm", "инглиз", "Ямайка"),
  CountryLocalization("jp", "япон", "Япония"),
  CountryLocalization("je", "инглиз", "Джерси"),
  CountryLocalization("jo", "гарәп", "Иордания"),
  CountryLocalization("kz", "казакъ", "Казахстан"),
  CountryLocalization("ke", "сомали", "Кения"),
  CountryLocalization("ki", "инглиз", "Кирибати"),
  CountryLocalization("xk", "серб", "Косово"),
  CountryLocalization("kw", "гарәп", "Күвәйт"),
  CountryLocalization("kg", "рус", "Кыргызстан"),
  CountryLocalization("la", "лаос", "Лаос"),
  CountryLocalization("lv", "латыш", "Латвия"),
  CountryLocalization("lb", "гарәп", "Ливан"),
  CountryLocalization("ls", "инглиз", "Лесото"),
  CountryLocalization("lr", "инглиз", "Либерия"),
  CountryLocalization("ly", "гарәп", "Ливия"),
  CountryLocalization("li", "Swiss German", "Лихтенштейн"),
  CountryLocalization("lt", "литва", "Литва"),
  CountryLocalization("lu", "люксембург", "Люксембург"),
  CountryLocalization("mo", "португал", "Макао Махсус Идарәле Төбәге"),
  CountryLocalization("mk", "албан", "North Macedonia"),
  CountryLocalization("mg", "француз", "Мадагаскар"),
  CountryLocalization("mw", "инглиз", "Малави"),
  CountryLocalization("my", "тамил", "Малайзия"),
  CountryLocalization("ml", "француз", "Мали"),
  CountryLocalization("mt", "инглиз", "Мальта"),
  CountryLocalization("mh", "инглиз", "Маршалл утраулары"),
  CountryLocalization("mq", "француз", "Мартиника"),
  CountryLocalization("mr", "гарәп", "Мавритания"),
  CountryLocalization("mu", "mfe", "Маврикий"),
  CountryLocalization("yt", "француз", "Майотта"),
  CountryLocalization("mx", "испан", "Мексика"),
  CountryLocalization("fm", "инглиз", "Микронезия"),
  CountryLocalization("md", "рус", "Молдова"),
  CountryLocalization("mc", "француз", "Монако"),
  CountryLocalization("mn", "монгол", "Монголия"),
  CountryLocalization("me", "серб", "Черногория"),
  CountryLocalization("ms", "инглиз", "Монтсеррат"),
  CountryLocalization("ma", "үзәк атлас тамазигт", "Марокко"),
  CountryLocalization("mz", "mgh", "Мозамбик"),
  CountryLocalization("mm", "бирма", "Myanmar (Burma)"),
  CountryLocalization("na", "инглиз", "Намибия"),
  CountryLocalization("nr", "инглиз", "Науру"),
  CountryLocalization("np", "непали", "Непал"),
  CountryLocalization("nl", "инглиз", "Нидерланд"),
  CountryLocalization("nc", "француз", "Яңа Каледония"),
  CountryLocalization("nz", "инглиз", "Яңа Зеландия"),
  CountryLocalization("ni", "испан", "Никарагуа"),
  CountryLocalization("ne", "хауса", "Нигер"),
  CountryLocalization("ng", "хауса", "Нигерия"),
  CountryLocalization("nu", "инглиз", "Ниуэ"),
  CountryLocalization("nf", "инглиз", "Норфолк утравы"),
  CountryLocalization("kp", "корея", "Төньяк Корея"),
  CountryLocalization("mp", "инглиз", "Төньяк Мариана утраулары"),
  CountryLocalization("no", "төньяк саам", "Норвегия"),
  CountryLocalization("om", "гарәп", "Оман"),
  CountryLocalization("pk", "инглиз", "Пакистан"),
  CountryLocalization("pw", "инглиз", "Палау"),
  CountryLocalization("ps", "гарәп", "Palestinian Territories"),
  CountryLocalization("pa", "испан", "Панама"),
  CountryLocalization("pg", "инглиз", "Папуа - Яңа Гвинея"),
  CountryLocalization("py", "испан", "Парагвай"),
  CountryLocalization("pe", "испан", "Перу"),
  CountryLocalization("ph", "филиппин", "Филиппин"),
  CountryLocalization("pn", "инглиз", "Питкэрн утраулары"),
  CountryLocalization("pl", "поляк", "Польша"),
  CountryLocalization("pt", "португал", "Португалия"),
  CountryLocalization("pr", "инглиз", "Пуэрто-Рико"),
  CountryLocalization("qa", "гарәп", "Катар"),
  CountryLocalization("ro", "румын", "Румыния"),
  CountryLocalization("ru", "татар", "Россия"),
  CountryLocalization("rw", "инглиз", "Руанда"),
  CountryLocalization("re", "француз", "Реюньон"),
  CountryLocalization("ws", "инглиз", "Самоа"),
  CountryLocalization("sm", "итальян", "Сан-Марино"),
  CountryLocalization("sa", "гарәп", "Согуд Гарәбстаны"),
  CountryLocalization("sn", "француз", "Сенегал"),
  CountryLocalization("rs", "серб", "Сербия"),
  CountryLocalization("cs", "серб", "Serbia and Montenegro"),
  CountryLocalization("sc", "француз", "Сейшел утраулары"),
  CountryLocalization("sl", "инглиз", "Сьерра-Леоне"),
  CountryLocalization("sg", "тамил", "Сингапур"),
  CountryLocalization("sx", "инглиз", "Синт-Мартен"),
  CountryLocalization("sk", "словак", "Словакия"),
  CountryLocalization("si", "словен", "Словения"),
  CountryLocalization("sb", "инглиз", "Сөләйман утраулары"),
  CountryLocalization("so", "гарәп", "Сомали"),
  CountryLocalization("za", "инглиз", "Көньяк Африка"),
  CountryLocalization("kr", "корея", "South Korea"),
  CountryLocalization("ss", "nus", "Көньяк Судан"),
  CountryLocalization("es", "испан", "Испания"),
  CountryLocalization("lk", "тамил", "Шри-Ланка"),
  CountryLocalization("bl", "француз", "Сен-Бартельми"),
  CountryLocalization("sh", "инглиз", "St. Helena"),
  CountryLocalization("kn", "инглиз", "Сент-Китс һәм Невис"),
  CountryLocalization("lc", "инглиз", "Сент-Люсия"),
  CountryLocalization("mf", "француз", "Сент-Мартин"),
  CountryLocalization("pm", "француз", "Сен-Пьер һәм Микелон"),
  CountryLocalization("vc", "инглиз", "Сент-Винсент һәм Гренадин"),
  CountryLocalization("sd", "гарәп", "Судан"),
  CountryLocalization("sr", "голланд", "Суринам"),
  CountryLocalization("sj", "Norwegian Bokmål", "Шпицберген һәм Ян-Майен"),
  CountryLocalization("sz", "инглиз", "Свазиленд"),
  CountryLocalization("se", "швед", "Швеция"),
  CountryLocalization("ch", "Swiss German", "Швейцария"),
  CountryLocalization("sy", "гарәп", "Сүрия"),
  CountryLocalization("st", "португал", "Сан-Томе һәм Принсипи"),
  CountryLocalization("tw", "кытай (тәрҗемә киңәше: аерым алганда, мандарин кытайчасы)", "Тайвань"),
  CountryLocalization("tj", "таҗик", "Таҗикстан"),
  CountryLocalization("tz", "kde", "Танзания"),
  CountryLocalization("th", "тай", "Тайланд"),
  CountryLocalization("tl", "португал", "Тимор-Лесте"),
  CountryLocalization("tg", "француз", "Того"),
  CountryLocalization("tk", "инглиз", "Токелау"),
  CountryLocalization("to", "тонга", "Тонга"),
  CountryLocalization("tt", "инглиз", "Тринидад һәм Тобаго"),
  CountryLocalization("tn", "француз", "Тунис"),
  CountryLocalization("tr", "төрек", "Төркия"),
  CountryLocalization("tm", "төрекмән", "Төркмәнстан"),
  CountryLocalization("tc", "инглиз", "Теркс һәм Кайкос утраулары"),
  CountryLocalization("tv", "инглиз", "Тувалу"),
  CountryLocalization("um", "инглиз", "АКШ Кече Читтәге утраулары"),
  CountryLocalization("vi", "инглиз", "АКШ Виргин утраулары"),
  CountryLocalization("ug", "Swahili", "Уганда"),
  CountryLocalization("ua", "украин", "Украина"),
  CountryLocalization("ae", "гарәп", "Берләшкән Гарәп Әмирлекләре"),
  CountryLocalization("gb", "инглиз", "Бөекбритания"),
  CountryLocalization("us", "lkt", "АКШ"),
  CountryLocalization("uy", "испан", "Уругвай"),
  CountryLocalization("uz", "үзбәк", "Үзбәкстан"),
  CountryLocalization("vu", "француз", "Вануату"),
  CountryLocalization("va", "итальян", "Vatican City"),
  CountryLocalization("ve", "испан", "Венесуэла"),
  CountryLocalization("vn", "вьетнам", "Вьетнам"),
  CountryLocalization("wf", "француз", "Уоллис һәм Футуна"),
  CountryLocalization("eh", "гарәп", "Western Sahara"),
  CountryLocalization("ye", "гарәп", "Йәмән"),
  CountryLocalization("zm", "инглиз", "Замбия"),
  CountryLocalization("zw", "North Ndebele", "Зимбабве"),
  CountryLocalization("ax", "швед", "Аланд утраулары"),
)
