/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot.atlas.extended

import dev.teogor.xenoglot.atlas.CountryLocalization
import kotlin.collections.List

/**
 * Holds the internal list of country-language mappings used for lookups within the package for
 * language code es.
 *
 * This property contains a hardcoded list of [CountryLocalization] objects, each representing
 * a country and its associated official languages. This list is used by [CountryLanguageRegistry]
 * to provide access to country-language data and should not be modified directly.
 *
 * @see CountryLocalization
 * @see CountryLanguageRegistry
 */
internal val _countryLanguageMappings_es: List<CountryLocalization> = listOf(
  CountryLocalization("af", "persa", "Afganistán"),
  CountryLocalization("al", "albanés", "Albania"),
  CountryLocalization("dz", "francés", "Argelia"),
  CountryLocalization("as", "inglés", "Samoa Americana"),
  CountryLocalization("ad", "catalán", "Andorra"),
  CountryLocalization("ao", "lingala", "Angola"),
  CountryLocalization("ai", "inglés", "Anguila"),
  CountryLocalization("ag", "inglés", "Antigua y Barbuda"),
  CountryLocalization("ar", "español", "Argentina"),
  CountryLocalization("am", "armenio", "Armenia"),
  CountryLocalization("aw", "neerlandés", "Aruba"),
  CountryLocalization("au", "inglés", "Australia"),
  CountryLocalization("at", "inglés", "Austria"),
  CountryLocalization("az", "azerbaiyano", "Azerbaiyán"),
  CountryLocalization("bs", "inglés", "Bahamas"),
  CountryLocalization("bh", "árabe", "Baréin"),
  CountryLocalization("bd", "bengalí", "Bangladés"),
  CountryLocalization("bb", "inglés", "Barbados"),
  CountryLocalization("by", "bielorruso", "Bielorrusia"),
  CountryLocalization("be", "francés", "Bélgica"),
  CountryLocalization("bz", "inglés", "Belice"),
  CountryLocalization("bj", "francés", "Benín"),
  CountryLocalization("bm", "inglés", "Bermudas"),
  CountryLocalization("bt", "dzongkha", "Bután"),
  CountryLocalization("bo", "español", "Bolivia"),
  CountryLocalization("ba", "bosnio", "Bosnia y Herzegovina"),
  CountryLocalization("bw", "inglés", "Botsuana"),
  CountryLocalization("br", "portugués", "Brasil"),
  CountryLocalization("io", "inglés", "Territorio Británico del Océano Índico"),
  CountryLocalization("vg", "inglés", "Islas Vírgenes Británicas"),
  CountryLocalization("bn", "malayo", "Brunéi"),
  CountryLocalization("bg", "búlgaro", "Bulgaria"),
  CountryLocalization("bf", "francés", "Burkina Faso"),
  CountryLocalization("bi", "francés", "Burundi"),
  CountryLocalization("kh", "jemer", "Camboya"),
  CountryLocalization("cm", "basaa", "Camerún"),
  CountryLocalization("ca", "francés", "Canadá"),
  CountryLocalization("ic", "español", "Islas Canarias"),
  CountryLocalization("cv", "criollo caboverdiano", "Cabo Verde"),
  CountryLocalization("bq", "neerlandés", "Caribe neerlandés"),
  CountryLocalization("ky", "inglés", "Islas Caimán"),
  CountryLocalization("cf", "lingala", "República Centroafricana"),
  CountryLocalization("ea", "español", "Ceuta y Melilla"),
  CountryLocalization("td", "árabe", "Chad"),
  CountryLocalization("cl", "español", "Chile"),
  CountryLocalization("cn", "tibetano", "China"),
  CountryLocalization("cx", "inglés", "Isla de Navidad"),
  CountryLocalization("cc", "inglés", "Islas Cocos"),
  CountryLocalization("co", "español", "Colombia"),
  CountryLocalization("km", "árabe", "Comoras"),
  CountryLocalization("cg", "lingala", "República del Congo"),
  CountryLocalization("cd", "suajili", "República Democrática del Congo"),
  CountryLocalization("ck", "inglés", "Islas Cook"),
  CountryLocalization("cr", "español", "Costa Rica"),
  CountryLocalization("hr", "croata", "Croacia"),
  CountryLocalization("cu", "español", "Cuba"),
  CountryLocalization("cw", "neerlandés", "Curazao"),
  CountryLocalization("cy", "inglés", "Chipre"),
  CountryLocalization("cz", "checo", "Chequia"),
  CountryLocalization("ci", "francés", "Costa de Marfil"),
  CountryLocalization("dk", "inglés", "Dinamarca"),
  CountryLocalization("dg", "inglés", "Diego García"),
  CountryLocalization("dj", "francés", "Yibuti"),
  CountryLocalization("dm", "inglés", "Dominica"),
  CountryLocalization("do", "español", "República Dominicana"),
  CountryLocalization("ec", "quechua", "Ecuador"),
  CountryLocalization("eg", "árabe", "Egipto"),
  CountryLocalization("sv", "español", "El Salvador"),
  CountryLocalization("gq", "español", "Guinea Ecuatorial"),
  CountryLocalization("er", "tigriña", "Eritrea"),
  CountryLocalization("ee", "estonio", "Estonia"),
  CountryLocalization("et", "amárico", "Etiopía"),
  CountryLocalization("fk", "inglés", "Islas Malvinas"),
  CountryLocalization("fo", "feroés", "Islas Feroe"),
  CountryLocalization("fj", "inglés", "Fiyi"),
  CountryLocalization("fi", "sueco", "Finlandia"),
  CountryLocalization("fr", "alemán suizo", "Francia"),
  CountryLocalization("gf", "francés", "Guayana Francesa"),
  CountryLocalization("pf", "francés", "Polinesia Francesa"),
  CountryLocalization("ga", "francés", "Gabón"),
  CountryLocalization("gm", "inglés", "Gambia"),
  CountryLocalization("ge", "osético", "Georgia"),
  CountryLocalization("de", "bajo sorbio", "Alemania"),
  CountryLocalization("gh", "inglés", "Ghana"),
  CountryLocalization("gi", "inglés", "Gibraltar"),
  CountryLocalization("gr", "griego", "Grecia"),
  CountryLocalization("gl", "groenlandés", "Groenlandia"),
  CountryLocalization("gd", "inglés", "Granada"),
  CountryLocalization("gp", "francés", "Guadalupe"),
  CountryLocalization("gu", "inglés", "Guam"),
  CountryLocalization("gt", "español", "Guatemala"),
  CountryLocalization("gg", "inglés", "Guernesey"),
  CountryLocalization("gn", "francés", "Guinea"),
  CountryLocalization("gw", "portugués", "Guinea-Bisáu"),
  CountryLocalization("gy", "inglés", "Guyana"),
  CountryLocalization("ht", "francés", "Haití"),
  CountryLocalization("hn", "español", "Honduras"),
  CountryLocalization("hk", "chino", "RAE de Hong Kong (China)"),
  CountryLocalization("hu", "húngaro", "Hungría"),
  CountryLocalization("is", "islandés", "Islandia"),
  CountryLocalization("in", "nepalí", "India"),
  CountryLocalization("id", "indonesio", "Indonesia"),
  CountryLocalization("ir", "persa", "Irán"),
  CountryLocalization("iq", "lorí septentrional", "Irak"),
  CountryLocalization("ie", "inglés", "Irlanda"),
  CountryLocalization("im", "manés", "Isla de Man"),
  CountryLocalization("il", "inglés", "Israel"),
  CountryLocalization("it", "alemán", "Italia"),
  CountryLocalization("jm", "inglés", "Jamaica"),
  CountryLocalization("jp", "japonés", "Japón"),
  CountryLocalization("je", "inglés", "Jersey"),
  CountryLocalization("jo", "árabe", "Jordania"),
  CountryLocalization("kz", "kazajo", "Kazajistán"),
  CountryLocalization("ke", "somalí", "Kenia"),
  CountryLocalization("ki", "inglés", "Kiribati"),
  CountryLocalization("xk", "serbio", "Kosovo"),
  CountryLocalization("kw", "árabe", "Kuwait"),
  CountryLocalization("kg", "ruso", "Kirguistán"),
  CountryLocalization("la", "lao", "Laos"),
  CountryLocalization("lv", "letón", "Letonia"),
  CountryLocalization("lb", "árabe", "Líbano"),
  CountryLocalization("ls", "inglés", "Lesoto"),
  CountryLocalization("lr", "inglés", "Liberia"),
  CountryLocalization("ly", "árabe", "Libia"),
  CountryLocalization("li", "alemán suizo", "Liechtenstein"),
  CountryLocalization("lt", "lituano", "Lituania"),
  CountryLocalization("lu", "luxemburgués", "Luxemburgo"),
  CountryLocalization("mo", "portugués", "RAE de Macao (China)"),
  CountryLocalization("mk", "albanés", "Macedonia"),
  CountryLocalization("mg", "francés", "Madagascar"),
  CountryLocalization("mw", "inglés", "Malaui"),
  CountryLocalization("my", "tamil", "Malasia"),
  CountryLocalization("ml", "francés", "Mali"),
  CountryLocalization("mt", "inglés", "Malta"),
  CountryLocalization("mh", "inglés", "Islas Marshall"),
  CountryLocalization("mq", "francés", "Martinica"),
  CountryLocalization("mr", "árabe", "Mauritania"),
  CountryLocalization("mu", "criollo mauriciano", "Mauricio"),
  CountryLocalization("yt", "francés", "Mayotte"),
  CountryLocalization("mx", "español", "México"),
  CountryLocalization("fm", "inglés", "Micronesia"),
  CountryLocalization("md", "ruso", "Moldavia"),
  CountryLocalization("mc", "francés", "Mónaco"),
  CountryLocalization("mn", "mongol", "Mongolia"),
  CountryLocalization("me", "serbio", "Montenegro"),
  CountryLocalization("ms", "inglés", "Montserrat"),
  CountryLocalization("ma", "tamazight del Marruecos Central", "Marruecos"),
  CountryLocalization("mz", "makhuwa-meetto", "Mozambique"),
  CountryLocalization("mm", "birmano", "Myanmar (Birmania)"),
  CountryLocalization("na", "inglés", "Namibia"),
  CountryLocalization("nr", "inglés", "Nauru"),
  CountryLocalization("np", "nepalí", "Nepal"),
  CountryLocalization("nl", "inglés", "Países Bajos"),
  CountryLocalization("nc", "francés", "Nueva Caledonia"),
  CountryLocalization("nz", "inglés", "Nueva Zelanda"),
  CountryLocalization("ni", "español", "Nicaragua"),
  CountryLocalization("ne", "hausa", "Níger"),
  CountryLocalization("ng", "hausa", "Nigeria"),
  CountryLocalization("nu", "inglés", "Niue"),
  CountryLocalization("nf", "inglés", "Isla Norfolk"),
  CountryLocalization("kp", "coreano", "Corea del Norte"),
  CountryLocalization("mp", "inglés", "Islas Marianas del Norte"),
  CountryLocalization("no", "sami septentrional", "Noruega"),
  CountryLocalization("om", "árabe", "Omán"),
  CountryLocalization("pk", "inglés", "Pakistán"),
  CountryLocalization("pw", "inglés", "Palaos"),
  CountryLocalization("ps", "árabe", "Territorios Palestinos"),
  CountryLocalization("pa", "español", "Panamá"),
  CountryLocalization("pg", "inglés", "Papúa Nueva Guinea"),
  CountryLocalization("py", "español", "Paraguay"),
  CountryLocalization("pe", "español", "Perú"),
  CountryLocalization("ph", "filipino", "Filipinas"),
  CountryLocalization("pn", "inglés", "Islas Pitcairn"),
  CountryLocalization("pl", "polaco", "Polonia"),
  CountryLocalization("pt", "portugués", "Portugal"),
  CountryLocalization("pr", "inglés", "Puerto Rico"),
  CountryLocalization("qa", "árabe", "Catar"),
  CountryLocalization("ro", "rumano", "Rumanía"),
  CountryLocalization("ru", "tártaro", "Rusia"),
  CountryLocalization("rw", "inglés", "Ruanda"),
  CountryLocalization("re", "francés", "Reunión"),
  CountryLocalization("ws", "inglés", "Samoa"),
  CountryLocalization("sm", "italiano", "San Marino"),
  CountryLocalization("sa", "árabe", "Arabia Saudí"),
  CountryLocalization("sn", "francés", "Senegal"),
  CountryLocalization("rs", "serbio", "Serbia"),
  CountryLocalization("cs", "serbio", "Serbia y Montenegro"),
  CountryLocalization("sc", "francés", "Seychelles"),
  CountryLocalization("sl", "inglés", "Sierra Leona"),
  CountryLocalization("sg", "tamil", "Singapur"),
  CountryLocalization("sx", "inglés", "Sint Maarten"),
  CountryLocalization("sk", "eslovaco", "Eslovaquia"),
  CountryLocalization("si", "esloveno", "Eslovenia"),
  CountryLocalization("sb", "inglés", "Islas Salomón"),
  CountryLocalization("so", "árabe", "Somalia"),
  CountryLocalization("za", "inglés", "Sudáfrica"),
  CountryLocalization("kr", "coreano", "Corea del Sur"),
  CountryLocalization("ss", "nuer", "Sudán del Sur"),
  CountryLocalization("es", "español", "España"),
  CountryLocalization("lk", "tamil", "Sri Lanka"),
  CountryLocalization("bl", "francés", "San Bartolomé"),
  CountryLocalization("sh", "inglés", "Santa Elena"),
  CountryLocalization("kn", "inglés", "San Cristóbal y Nieves"),
  CountryLocalization("lc", "inglés", "Santa Lucía"),
  CountryLocalization("mf", "francés", "San Martín"),
  CountryLocalization("pm", "francés", "San Pedro y Miquelón"),
  CountryLocalization("vc", "inglés", "San Vicente y las Granadinas"),
  CountryLocalization("sd", "árabe", "Sudán"),
  CountryLocalization("sr", "neerlandés", "Surinam"),
  CountryLocalization("sj", "noruego bokmal", "Svalbard y Jan Mayen"),
  CountryLocalization("sz", "inglés", "Suazilandia"),
  CountryLocalization("se", "sueco", "Suecia"),
  CountryLocalization("ch", "alemán suizo", "Suiza"),
  CountryLocalization("sy", "árabe", "Siria"),
  CountryLocalization("st", "portugués", "Santo Tomé y Príncipe"),
  CountryLocalization("tw", "chino", "Taiwán"),
  CountryLocalization("tj", "tayiko", "Tayikistán"),
  CountryLocalization("tz", "makonde", "Tanzania"),
  CountryLocalization("th", "tailandés", "Tailandia"),
  CountryLocalization("tl", "portugués", "Timor-Leste"),
  CountryLocalization("tg", "francés", "Togo"),
  CountryLocalization("tk", "inglés", "Tokelau"),
  CountryLocalization("to", "tongano", "Tonga"),
  CountryLocalization("tt", "inglés", "Trinidad y Tobago"),
  CountryLocalization("tn", "francés", "Túnez"),
  CountryLocalization("tr", "turco", "Turquía"),
  CountryLocalization("tm", "turcomano", "Turkmenistán"),
  CountryLocalization("tc", "inglés", "Islas Turcas y Caicos"),
  CountryLocalization("tv", "inglés", "Tuvalu"),
  CountryLocalization("um", "inglés", "Islas menores alejadas de EE. UU."),
  CountryLocalization("vi", "inglés", "Islas Vírgenes de EE. UU."),
  CountryLocalization("ug", "suajili", "Uganda"),
  CountryLocalization("ua", "ucraniano", "Ucrania"),
  CountryLocalization("ae", "árabe", "Emiratos Árabes Unidos"),
  CountryLocalization("gb", "inglés", "Reino Unido"),
  CountryLocalization("us", "lakota", "Estados Unidos"),
  CountryLocalization("uy", "español", "Uruguay"),
  CountryLocalization("uz", "uzbeko", "Uzbekistán"),
  CountryLocalization("vu", "francés", "Vanuatu"),
  CountryLocalization("va", "italiano", "Ciudad del Vaticano"),
  CountryLocalization("ve", "español", "Venezuela"),
  CountryLocalization("vn", "vietnamita", "Vietnam"),
  CountryLocalization("wf", "francés", "Wallis y Futuna"),
  CountryLocalization("eh", "árabe", "Sáhara Occidental"),
  CountryLocalization("ye", "árabe", "Yemen"),
  CountryLocalization("zm", "inglés", "Zambia"),
  CountryLocalization("zw", "ndebele septentrional", "Zimbabue"),
  CountryLocalization("ax", "sueco", "Islas Åland"),
)
