/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot.atlas.extended

import dev.teogor.xenoglot.atlas.CountryLocalization
import kotlin.collections.List

/**
 * Holds the internal list of country-language mappings used for lookups within the package for
 * language code lo.
 *
 * This property contains a hardcoded list of [CountryLocalization] objects, each representing
 * a country and its associated official languages. This list is used by [CountryLanguageRegistry]
 * to provide access to country-language data and should not be modified directly.
 *
 * @see CountryLocalization
 * @see CountryLanguageRegistry
 */
internal val _countryLanguageMappings_lo: List<CountryLocalization> = listOf(
  CountryLocalization("af", "ເປີຊຽນ", "ອາຟການິດສະຖານ"),
  CountryLocalization("al", "ອານບານຽນ", "ແອວເບເນຍ"),
  CountryLocalization("dz", "ຝຣັ່ງ", "ອັລຈິເຣຍ"),
  CountryLocalization("as", "ອັງກິດ", "ອາເມຣິກາ ຊາມົວ"),
  CountryLocalization("ad", "ຄາຕາລານ", "ອັນດໍຣາ"),
  CountryLocalization("ao", "ລິງກາລາ", "ແອງໂກລາ"),
  CountryLocalization("ai", "ອັງກິດ", "ແອນກຸຍລາ"),
  CountryLocalization("ag", "ອັງກິດ", "ແອນທິກົວ ແລະ ບາບູດາ"),
  CountryLocalization("ar", "ສະແປນນິຊ", "ອາເຈນທິນາ"),
  CountryLocalization("am", "ອາເມນຽນ", "ອາເມເນຍ"),
  CountryLocalization("aw", "ດັຊ", "ອາຣູບາ"),
  CountryLocalization("au", "ອັງກິດ", "ອອສເຕຣເລຍ"),
  CountryLocalization("at", "ອັງກິດ", "ອອສເທຣຍ"),
  CountryLocalization("az", "ອາເຊີໄບຈານິ", "ອາເຊີໄບຈານ"),
  CountryLocalization("bs", "ອັງກິດ", "ບາຮາມາສ"),
  CountryLocalization("bh", "ອາຣັບ", "ບາເຣນ"),
  CountryLocalization("bd", "ເບັງກາລີ", "ບັງກະລາເທດ"),
  CountryLocalization("bb", "ອັງກິດ", "ບາບາໂດສ"),
  CountryLocalization("by", "ເບລາຣັສຊຽນ", "ເບວບາຣຸສ"),
  CountryLocalization("be", "ຝຣັ່ງ", "ເບວຢຽມ"),
  CountryLocalization("bz", "ອັງກິດ", "ເບລີຊ"),
  CountryLocalization("bj", "ຝຣັ່ງ", "ເບນິນ"),
  CountryLocalization("bm", "ອັງກິດ", "ເບີມິວດາ"),
  CountryLocalization("bt", "ດີຊອງຄາ", "ພູຖານ"),
  CountryLocalization("bo", "ສະແປນນິຊ", "ໂບລິເວຍ"),
  CountryLocalization("ba", "ບອສນຽນ", "ບອດສະເນຍ ແລະ ແຮສໂກວີນາ"),
  CountryLocalization("bw", "ອັງກິດ", "ບອດສະວານາ"),
  CountryLocalization("br", "ປອກຕຸຍກິສ", "ບຣາຊິວ"),
  CountryLocalization("io", "ອັງກິດ", "ເຂດແດນອັງກິດໃນມະຫາສະມຸດອິນເດຍ"),
  CountryLocalization("vg", "ອັງກິດ", "ໝູ່ເກາະ ເວີຈິນຂອງອັງກິດ"),
  CountryLocalization("bn", "ມາເລ", "ບຣູໄນ"),
  CountryLocalization("bg", "ບັງກາຣຽນ", "ບັງກາເຣຍ"),
  CountryLocalization("bf", "ຝຣັ່ງ", "ເບີກິນາ ຟາໂຊ"),
  CountryLocalization("bi", "ຝຣັ່ງ", "ບູຣຸນດິ"),
  CountryLocalization("kh", "ຂະເໝນ", "ກຳປູເຈຍ"),
  CountryLocalization("cm", "ບາຊາ", "ຄາເມຣູນ"),
  CountryLocalization("ca", "ຝຣັ່ງ", "ແຄນາດາ"),
  CountryLocalization("ic", "ສະແປນນິຊ", "ໝູ່ເກາະຄານາຣີ"),
  CountryLocalization("cv", "ຄາເວີເດຍນູ", "ເຄບ ເວີດ"),
  CountryLocalization("bq", "ດັຊ", "ຄາຣິບບຽນ ເນເທີແລນ"),
  CountryLocalization("ky", "ອັງກິດ", "ໝູ່ເກາະ ເຄແມນ"),
  CountryLocalization("cf", "ລິງກາລາ", "ສາທາລະນະລັດອາຟຣິກາກາງ"),
  CountryLocalization("ea", "ສະແປນນິຊ", "ເຊວຕາ ແລະເມລິນລາ"),
  CountryLocalization("td", "ອາຣັບ", "ຊາດ"),
  CountryLocalization("cl", "ສະແປນນິຊ", "ຊິລີ"),
  CountryLocalization("cn", "ທິເບທັນ", "ຈີນ"),
  CountryLocalization("cx", "ອັງກິດ", "ເກາະຄຣິສມາດ"),
  CountryLocalization("cc", "ອັງກິດ", "ຫມູ່ເກາະໂກໂກສ"),
  CountryLocalization("co", "ສະແປນນິຊ", "ໂຄລົມເບຍ"),
  CountryLocalization("km", "ອາຣັບ", "ໂຄໂມໂຣສ"),
  CountryLocalization("cg", "ລິງກາລາ", "ຄອງໂກ - ບຣາຊາວິວ"),
  CountryLocalization("cd", "ຊວາຮີລິ", "ຄອງໂກ - ຄິນຊາຊາ"),
  CountryLocalization("ck", "ອັງກິດ", "ໝູ່ເກາະຄຸກ"),
  CountryLocalization("cr", "ສະແປນນິຊ", "ໂຄສຕາ ຣິກາ"),
  CountryLocalization("hr", "ໂຄຣເອທຽນ", "ໂຄຣເອເທຍ"),
  CountryLocalization("cu", "ສະແປນນິຊ", "ຄິວບາ"),
  CountryLocalization("cw", "ດັຊ", "ຄູຣາຊາວ"),
  CountryLocalization("cy", "ອັງກິດ", "ໄຊປຣັສ"),
  CountryLocalization("cz", "ເຊກ", "ເຊັກເຊຍ"),
  CountryLocalization("ci", "ຝຣັ່ງ", "ໂຄຕີ ວົວ"),
  CountryLocalization("dk", "ອັງກິດ", "ເດນມາກ"),
  CountryLocalization("dg", "ອັງກິດ", "ດິເອໂກ ກາເຊຍ"),
  CountryLocalization("dj", "ຝຣັ່ງ", "ຈິບູຕິ"),
  CountryLocalization("dm", "ອັງກິດ", "ໂດມີນິຄາ"),
  CountryLocalization("do", "ສະແປນນິຊ", "ສາທາລະນະລັດ ໂດມິນິກັນ"),
  CountryLocalization("ec", "ຄີຊົວ", "ເອກວາດໍ"),
  CountryLocalization("eg", "ອາຣັບ", "ອີຢິບ"),
  CountryLocalization("sv", "ສະແປນນິຊ", "ເອວ ຊໍວາດໍ"),
  CountryLocalization("gq", "ສະແປນນິຊ", "ເອຄົວໂທຣຽວ ກີນີ"),
  CountryLocalization("er", "ຕິກຣິນຢາ", "ເອຣິເທຣຍ"),
  CountryLocalization("ee", "ເອສໂຕນຽນ", "ເອສໂຕເນຍ"),
  CountryLocalization("et", "ອຳຮາຣິກ", "ອີທິໂອເປຍ"),
  CountryLocalization("fk", "ອັງກິດ", "ຫມູ່ເກາະຟອກແລນ"),
  CountryLocalization("fo", "ຟາໂຣສ", "ຫມູ່ເກາະແຟໂຣ"),
  CountryLocalization("fj", "ອັງກິດ", "ຟິຈິ"),
  CountryLocalization("fi", "ສະວີດິຊ", "ຟິນແລນ"),
  CountryLocalization("fr", "ສະວິສ ເຈີແມນ", "ຝຣັ່ງ"),
  CountryLocalization("gf", "ຝຣັ່ງ", "ເຟຣນຊ໌ ກຸຍອານາ"),
  CountryLocalization("pf", "ຝຣັ່ງ", "ເຟຣນຊ໌ ໂພລິນີເຊຍ"),
  CountryLocalization("ga", "ຝຣັ່ງ", "ກາບອນ"),
  CountryLocalization("gm", "ອັງກິດ", "ສາທາລະນະລັດແກມເບຍ"),
  CountryLocalization("ge", "ອອດເຊຕິກ", "ຈໍເຈຍ"),
  CountryLocalization("de", "ຊໍບຽນຕໍ່ກວ່າ", "ເຢຍລະມັນ"),
  CountryLocalization("gh", "ອັງກິດ", "ການາ"),
  CountryLocalization("gi", "ອັງກິດ", "ຈິບບຣອນທາ"),
  CountryLocalization("gr", "ກຣີກ", "ກຣີຊ"),
  CountryLocalization("gl", "ກຣີນແລນລິດ", "ກຣີນແລນ"),
  CountryLocalization("gd", "ອັງກິດ", "ເກຣເນດາ"),
  CountryLocalization("gp", "ຝຣັ່ງ", "ກົວດາລູບ"),
  CountryLocalization("gu", "ອັງກິດ", "ກວາມ"),
  CountryLocalization("gt", "ສະແປນນິຊ", "ກົວເທມາລາ"),
  CountryLocalization("gg", "ອັງກິດ", "ເກີນຊີ"),
  CountryLocalization("gn", "ຝຣັ່ງ", "ກິນີ"),
  CountryLocalization("gw", "ປອກຕຸຍກິສ", "ກິນີ-ບິສເຊົາ"),
  CountryLocalization("gy", "ອັງກິດ", "ກາຍຢານາ"),
  CountryLocalization("ht", "ຝຣັ່ງ", "ໄຮຕິ"),
  CountryLocalization("hn", "ສະແປນນິຊ", "ຮອນດູຣັສ"),
  CountryLocalization("hk", "ຈີນ", "ຮົງກົງ ເຂດປົກຄອງພິເສດ ຈີນ"),
  CountryLocalization("hu", "ຮັງກາຣຽນ", "ຮັງກາຣີ"),
  CountryLocalization("is", "ໄອສແລນດິກ", "ໄອສແລນ"),
  CountryLocalization("in", "ເນປາລີ", "ອິນເດຍ"),
  CountryLocalization("id", "Indonesian", "ອິນໂດເນເຊຍ"),
  CountryLocalization("ir", "ເປີຊຽນ", "ອີຣານ"),
  CountryLocalization("iq", "ລູຣິ ທາງຕອນເໜືອ", "ອີຣັກ"),
  CountryLocalization("ie", "ອັງກິດ", "ໄອແລນ"),
  CountryLocalization("im", "ແມງຊ໌", "ເອວ ອອບ ແມນ"),
  CountryLocalization("il", "ອັງກິດ", "ອິສຣາເອວ"),
  CountryLocalization("it", "ເຢຍລະມັນ", "ອິຕາລີ"),
  CountryLocalization("jm", "ອັງກິດ", "ຈາໄມຄາ"),
  CountryLocalization("jp", "ຍີ່ປຸ່ນ", "ຍີ່ປຸ່ນ"),
  CountryLocalization("je", "ອັງກິດ", "ເຈີຊີ"),
  CountryLocalization("jo", "ອາຣັບ", "ຈໍແດນ"),
  CountryLocalization("kz", "ຄາຊັກ", "ຄາຊັກສະຖານ"),
  CountryLocalization("ke", "ໂຊມາລີ", "ເຄນຢາ"),
  CountryLocalization("ki", "ອັງກິດ", "ຄິຣິບາທິ"),
  CountryLocalization("xk", "ເຊີບຽນ", "ໂຄໂຊໂວ"),
  CountryLocalization("kw", "ອາຣັບ", "ກູເວດ"),
  CountryLocalization("kg", "ລັດເຊຍ", "ຄຽກກິດສະຖານ"),
  CountryLocalization("la", "ລາວ", "ລາວ"),
  CountryLocalization("lv", "ລັດວຽນ", "ລັດເວຍ"),
  CountryLocalization("lb", "ອາຣັບ", "ເລບານອນ"),
  CountryLocalization("ls", "ອັງກິດ", "ເລໂຊໂທ"),
  CountryLocalization("lr", "ອັງກິດ", "ລິເບີເຣຍ"),
  CountryLocalization("ly", "ອາຣັບ", "ລິເບຍ"),
  CountryLocalization("li", "ສະວິສ ເຈີແມນ", "ລິດເທນສະຕາຍ"),
  CountryLocalization("lt", "ລິທົວນຽນ", "ລິທົວເນຍ"),
  CountryLocalization("lu", "ລັກເຊມບວກກິຊ", "ລຸກແຊມເບີກ"),
  CountryLocalization("mo", "ປອກຕຸຍກິສ", "ມາກາວ ເຂດປົກຄອງພິເສດ ຈີນ"),
  CountryLocalization("mk", "ອານບານຽນ", "ແມຊິໂດເນຍ"),
  CountryLocalization("mg", "ຝຣັ່ງ", "ມາດາກາສະກາ"),
  CountryLocalization("mw", "ອັງກິດ", "ມາລາວີ"),
  CountryLocalization("my", "ທາມິລ", "ມາເລເຊຍ"),
  CountryLocalization("ml", "ຝຣັ່ງ", "ມາລີ"),
  CountryLocalization("mt", "ອັງກິດ", "ມອນທາ"),
  CountryLocalization("mh", "ອັງກິດ", "ຫມູ່ເກາະມາແຊວ"),
  CountryLocalization("mq", "ຝຣັ່ງ", "ມາຕິນີກ"),
  CountryLocalization("mr", "ອາຣັບ", "ມົວຣິເທເນຍ"),
  CountryLocalization("mu", "ມໍຣິສເຢນ", "ມົວຣິຊຽສ"),
  CountryLocalization("yt", "ຝຣັ່ງ", "ມາຢັອດ"),
  CountryLocalization("mx", "ສະແປນນິຊ", "ເມັກຊິໂກ"),
  CountryLocalization("fm", "ອັງກິດ", "ໄມໂຄຣນີເຊຍ"),
  CountryLocalization("md", "ລັດເຊຍ", "ໂມນໂດວາ"),
  CountryLocalization("mc", "ຝຣັ່ງ", "ໂມນາໂຄ"),
  CountryLocalization("mn", "ມອງໂກເລຍ", "ມອງໂກເລຍ"),
  CountryLocalization("me", "ເຊີບຽນ", "ມອນເຕເນໂກຣ"),
  CountryLocalization("ms", "ອັງກິດ", "ມອນເຊີຣາດ"),
  CountryLocalization("ma", "ອັດລາສ ທາມາຊີກ ກາງ", "ໂມຣັອກໂຄ"),
  CountryLocalization("mz", "ມາຄູວາ-ມີດໂຕ", "ໂມແຊມບິກ"),
  CountryLocalization("mm", "ມຽນມາ", "ມຽນມາ (ເບີມາ)"),
  CountryLocalization("na", "ອັງກິດ", "ນາມີເບຍ"),
  CountryLocalization("nr", "ອັງກິດ", "ນາອູຣູ"),
  CountryLocalization("np", "ເນປາລີ", "ເນປານ"),
  CountryLocalization("nl", "ອັງກິດ", "ເນເທີແລນ"),
  CountryLocalization("nc", "ຝຣັ່ງ", "ນິວ ຄາເລໂດເນຍ"),
  CountryLocalization("nz", "ອັງກິດ", "ນິວຊີແລນ"),
  CountryLocalization("ni", "ສະແປນນິຊ", "ນິກຄາຣາກົວ"),
  CountryLocalization("ne", "ເຮົາຊາ", "ນິເຈີ"),
  CountryLocalization("ng", "ເຮົາຊາ", "ໄນຈີເຣຍ"),
  CountryLocalization("nu", "ອັງກິດ", "ນີອູເອ"),
  CountryLocalization("nf", "ອັງກິດ", "ເກາະນໍໂຟກ"),
  CountryLocalization("kp", "ເກົາຫລີ", "ເກົາຫລີເໜືອ"),
  CountryLocalization("mp", "ອັງກິດ", "ຫມູ່ເກາະມາແຊວຕອນເຫນືອ"),
  CountryLocalization("no", "ຊາມິເໜືອ", "ນໍເວ"),
  CountryLocalization("om", "ອາຣັບ", "ໂອມານ"),
  CountryLocalization("pk", "ອັງກິດ", "ປາກິດສະຖານ"),
  CountryLocalization("pw", "ອັງກິດ", "ປາລາວ"),
  CountryLocalization("ps", "ອາຣັບ", "ດິນແດນ ປາເລສຕິນຽນ"),
  CountryLocalization("pa", "ສະແປນນິຊ", "ພານາມາ"),
  CountryLocalization("pg", "ອັງກິດ", "ປາປົວນິວກີນີ"),
  CountryLocalization("py", "ສະແປນນິຊ", "ພາຣາກວຍ"),
  CountryLocalization("pe", "ສະແປນນິຊ", "ເປຣູ"),
  CountryLocalization("ph", "ຟີລິປີໂນ", "ຟິລິບປິນ"),
  CountryLocalization("pn", "ອັງກິດ", "ໝູ່ເກາະພິດແຄນ"),
  CountryLocalization("pl", "ໂປລິຊ", "ໂປແລນ"),
  CountryLocalization("pt", "ປອກຕຸຍກິສ", "ພອລທູໂກ"),
  CountryLocalization("pr", "ອັງກິດ", "ເພືອໂຕ ຣິໂກ"),
  CountryLocalization("qa", "ອາຣັບ", "ກາຕາ"),
  CountryLocalization("ro", "ໂຣແມນຽນ", "ໂຣແມເນຍ"),
  CountryLocalization("ru", "ທາທາ", "ຣັດເຊຍ"),
  CountryLocalization("rw", "ອັງກິດ", "ຣວັນດາ"),
  CountryLocalization("re", "ຝຣັ່ງ", "ເຣອູນິຍົງ"),
  CountryLocalization("ws", "ອັງກິດ", "ຊາມົວ"),
  CountryLocalization("sm", "ອິຕາລຽນ", "ແຊນ ມາຣິໂນ"),
  CountryLocalization("sa", "ອາຣັບ", "ຊາອຸດິ ອາຣາເບຍ"),
  CountryLocalization("sn", "ຝຣັ່ງ", "ເຊນີໂກລ"),
  CountryLocalization("rs", "ເຊີບຽນ", "ເຊີເບຍ"),
  CountryLocalization("cs", "ເຊີບຽນ", "Serbia and Montenegro"),
  CountryLocalization("sc", "ຝຣັ່ງ", "ເຊເຊວເລສ"),
  CountryLocalization("sl", "ອັງກິດ", "ເຊຍຣາ ລີໂອນ"),
  CountryLocalization("sg", "ທາມິລ", "ສິງກະໂປ"),
  CountryLocalization("sx", "ອັງກິດ", "ຊິນ ມາເທັນ"),
  CountryLocalization("sk", "ສະໂລແວັກ", "ສະໂລວາເກຍ"),
  CountryLocalization("si", "ສະໂລເວນຽນ", "ສະໂລເວເນຍ"),
  CountryLocalization("sb", "ອັງກິດ", "ຫມູ່ເກາະໂຊໂລມອນ"),
  CountryLocalization("so", "ອາຣັບ", "ໂຊມາເລຍ"),
  CountryLocalization("za", "ອັງກິດ", "ອາຟຣິກາໃຕ້"),
  CountryLocalization("kr", "ເກົາຫລີ", "ເກົາຫລີໃຕ້"),
  CountryLocalization("ss", "ເນີ", "ຊູດານໃຕ້"),
  CountryLocalization("es", "ສະແປນນິຊ", "ສະເປນ"),
  CountryLocalization("lk", "ທາມິລ", "ສີລັງກາ"),
  CountryLocalization("bl", "ຝຣັ່ງ", "ເຊນ ບາເທເລມີ"),
  CountryLocalization("sh", "ອັງກິດ", "ເຊນ ເຮເລນາ"),
  CountryLocalization("kn", "ອັງກິດ", "ເຊນ ຄິດ ແລະ ເນວິສ"),
  CountryLocalization("lc", "ອັງກິດ", "ເຊນ ລູເຊຍ"),
  CountryLocalization("mf", "ຝຣັ່ງ", "ເຊນ ມາທິນ"),
  CountryLocalization("pm", "ຝຣັ່ງ", "ເຊນ ປີແອ ມິເກວລອນ"),
  CountryLocalization("vc", "ອັງກິດ", "ເຊນ ວິນເຊນ ແລະ ເກຣເນດິນ"),
  CountryLocalization("sd", "ອາຣັບ", "ຊູດານ"),
  CountryLocalization("sr", "ດັຊ", "ຊູຣິນາມ"),
  CountryLocalization("sj", "ນໍເວຈຽນ ບັອກມອລ", "ສະວາບາ ແລະ ແຢນ ມາເຢນ"),
  CountryLocalization("sz", "ອັງກິດ", "ສະວາຊິແລນ"),
  CountryLocalization("se", "ສະວີດິຊ", "ສະວີເດັນ"),
  CountryLocalization("ch", "ສະວິສ ເຈີແມນ", "ສະວິດເຊີແລນ"),
  CountryLocalization("sy", "ອາຣັບ", "ຊີເຣຍ"),
  CountryLocalization("st", "ປອກຕຸຍກິສ", "ເຊົາທູເມ ແລະ ພຣິນຊິບ"),
  CountryLocalization("tw", "ຈີນ", "ໄຕ້ຫວັນ"),
  CountryLocalization("tj", "ທາຈິກ", "ທາຈິກິດສະຖານ"),
  CountryLocalization("tz", "ມາຄອນເດ", "ທານຊາເນຍ"),
  CountryLocalization("th", "ໄທ", "ໄທ"),
  CountryLocalization("tl", "ປອກຕຸຍກິສ", "ທິມໍ-ເລສເຕ"),
  CountryLocalization("tg", "ຝຣັ່ງ", "ໂຕໂກ"),
  CountryLocalization("tk", "ອັງກິດ", "ໂຕເກເລົາ"),
  CountryLocalization("to", "ທອງການ", "ທອງກາ"),
  CountryLocalization("tt", "ອັງກິດ", "ທຣິນິແດດ ແລະ ໂທແບໂກ"),
  CountryLocalization("tn", "ຝຣັ່ງ", "ຕູນິເຊຍ"),
  CountryLocalization("tr", "ເທີຄິຊ", "ເທີຄີ"),
  CountryLocalization("tm", "ເທີກເມັນ", "ເທີກເມນິສະຖານ"),
  CountryLocalization("tc", "ອັງກິດ", "ໝູ່ເກາະ ເທີກ ແລະ ໄຄໂຄສ"),
  CountryLocalization("tv", "ອັງກິດ", "ຕູວາລູ"),
  CountryLocalization("um", "ອັງກິດ", "ໝູ່ເກາະຮອບນອກຂອງສະຫະລັດຯ"),
  CountryLocalization("vi", "ອັງກິດ", "ໝູ່ເກາະ ເວີຈິນ ຂອງສະຫະລັດ"),
  CountryLocalization("ug", "ຊວາຮີລິ", "ອູການດາ"),
  CountryLocalization("ua", "ຢູເຄຣນຽນ", "ຢູເຄຣນ"),
  CountryLocalization("ae", "ອາຣັບ", "ສະຫະລັດອາຣັບເອມິເຣດ"),
  CountryLocalization("gb", "ອັງກິດ", "ສະຫະລາດຊະອະນາຈັກ"),
  CountryLocalization("us", "ລາໂກຕາ", "ສະຫະລັດ"),
  CountryLocalization("uy", "ສະແປນນິຊ", "ອູຣຸກວຍ"),
  CountryLocalization("uz", "ອຸສເບກ", "ອຸສເບກິສະຖານ"),
  CountryLocalization("vu", "ຝຣັ່ງ", "ວານົວຕູ"),
  CountryLocalization("va", "ອິຕາລຽນ", "ນະຄອນ ວາຕິກັນ"),
  CountryLocalization("ve", "ສະແປນນິຊ", "ເວເນຊູເອລາ"),
  CountryLocalization("vn", "ຫວຽດນາມ", "ຫວຽດນາມ"),
  CountryLocalization("wf", "ຝຣັ່ງ", "ວາລລິສ ແລະ ຟູຕູນາ"),
  CountryLocalization("eh", "ອາຣັບ", "ຊາຮາຣາຕາເວັນຕົກ"),
  CountryLocalization("ye", "ອາຣັບ", "ເຢເມນ"),
  CountryLocalization("zm", "ອັງກິດ", "ແຊມເບຍ"),
  CountryLocalization("zw", "ເອັນເດເບເລເໜືອ", "ຊິມບັບເວ"),
  CountryLocalization("ax", "ສະວີດິຊ", "ຫມູ່ເກາະໂອລັນ"),
)
