/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot.atlas.extended

import dev.teogor.xenoglot.atlas.CountryLocalization
import kotlin.collections.List

/**
 * Holds the internal list of country-language mappings used for lookups within the package for
 * language code et.
 *
 * This property contains a hardcoded list of [CountryLocalization] objects, each representing
 * a country and its associated official languages. This list is used by [CountryLanguageRegistry]
 * to provide access to country-language data and should not be modified directly.
 *
 * @see CountryLocalization
 * @see CountryLanguageRegistry
 */
internal val _countryLanguageMappings_et: List<CountryLocalization> = listOf(
  CountryLocalization("af", "pärsia", "Afganistan"),
  CountryLocalization("al", "albaania", "Albaania"),
  CountryLocalization("dz", "prantsuse", "Alžeeria"),
  CountryLocalization("as", "inglise", "Ameerika Samoa"),
  CountryLocalization("ad", "katalaani", "Andorra"),
  CountryLocalization("ao", "lingala", "Angola"),
  CountryLocalization("ai", "inglise", "Anguilla"),
  CountryLocalization("ag", "inglise", "Antigua ja Barbuda"),
  CountryLocalization("ar", "hispaania", "Argentina"),
  CountryLocalization("am", "armeenia", "Armeenia"),
  CountryLocalization("aw", "hollandi", "Aruba"),
  CountryLocalization("au", "inglise", "Austraalia"),
  CountryLocalization("at", "inglise", "Austria"),
  CountryLocalization("az", "aserbaidžaani", "Aserbaidžaan"),
  CountryLocalization("bs", "inglise", "Bahama"),
  CountryLocalization("bh", "araabia", "Bahrein"),
  CountryLocalization("bd", "bengali", "Bangladesh"),
  CountryLocalization("bb", "inglise", "Barbados"),
  CountryLocalization("by", "valgevene", "Valgevene"),
  CountryLocalization("be", "prantsuse", "Belgia"),
  CountryLocalization("bz", "inglise", "Belize"),
  CountryLocalization("bj", "prantsuse", "Benin"),
  CountryLocalization("bm", "inglise", "Bermuda"),
  CountryLocalization("bt", "dzongkha", "Bhutan"),
  CountryLocalization("bo", "hispaania", "Boliivia"),
  CountryLocalization("ba", "bosnia", "Bosnia ja Hertsegoviina"),
  CountryLocalization("bw", "inglise", "Botswana"),
  CountryLocalization("br", "portugali", "Brasiilia"),
  CountryLocalization("io", "inglise", "Briti India ookeani ala"),
  CountryLocalization("vg", "inglise", "Briti Neitsisaared"),
  CountryLocalization("bn", "malai", "Brunei"),
  CountryLocalization("bg", "bulgaaria", "Bulgaaria"),
  CountryLocalization("bf", "prantsuse", "Burkina Faso"),
  CountryLocalization("bi", "prantsuse", "Burundi"),
  CountryLocalization("kh", "khmeeri", "Kambodža"),
  CountryLocalization("cm", "basaa", "Kamerun"),
  CountryLocalization("ca", "prantsuse", "Kanada"),
  CountryLocalization("ic", "hispaania", "Kanaari saared"),
  CountryLocalization("cv", "kabuverdianu", "Roheneemesaared"),
  CountryLocalization("bq", "hollandi", "Hollandi Kariibi mere saared"),
  CountryLocalization("ky", "inglise", "Kaimanisaared"),
  CountryLocalization("cf", "lingala", "Kesk-Aafrika Vabariik"),
  CountryLocalization("ea", "hispaania", "Ceuta ja Melilla"),
  CountryLocalization("td", "araabia", "Tšaad"),
  CountryLocalization("cl", "hispaania", "Tšiili"),
  CountryLocalization("cn", "tiibeti", "Hiina"),
  CountryLocalization("cx", "inglise", "Jõulusaar"),
  CountryLocalization("cc", "inglise", "Kookossaared"),
  CountryLocalization("co", "hispaania", "Colombia"),
  CountryLocalization("km", "araabia", "Komoorid"),
  CountryLocalization("cg", "lingala", "Kongo Vabariik"),
  CountryLocalization("cd", "suahiili", "Kongo DV"),
  CountryLocalization("ck", "inglise", "Cooki saared"),
  CountryLocalization("cr", "hispaania", "Costa Rica"),
  CountryLocalization("hr", "horvaadi", "Horvaatia"),
  CountryLocalization("cu", "hispaania", "Kuuba"),
  CountryLocalization("cw", "hollandi", "Curaçao"),
  CountryLocalization("cy", "inglise", "Küpros"),
  CountryLocalization("cz", "tšehhi", "Tšehhi"),
  CountryLocalization("ci", "prantsuse", "Côte d’Ivoire"),
  CountryLocalization("dk", "inglise", "Taani"),
  CountryLocalization("dg", "inglise", "Diego Garcia"),
  CountryLocalization("dj", "prantsuse", "Djibouti"),
  CountryLocalization("dm", "inglise", "Dominica"),
  CountryLocalization("do", "hispaania", "Dominikaani Vabariik"),
  CountryLocalization("ec", "ketšua", "Ecuador"),
  CountryLocalization("eg", "araabia", "Egiptus"),
  CountryLocalization("sv", "hispaania", "El Salvador"),
  CountryLocalization("gq", "hispaania", "Ekvatoriaal-Guinea"),
  CountryLocalization("er", "tigrinja", "Eritrea"),
  CountryLocalization("ee", "eesti", "Eesti"),
  CountryLocalization("et", "amhara", "Etioopia"),
  CountryLocalization("fk", "inglise", "Falklandi saared"),
  CountryLocalization("fo", "fääri", "Fääri saared"),
  CountryLocalization("fj", "inglise", "Fidži"),
  CountryLocalization("fi", "rootsi", "Soome"),
  CountryLocalization("fr", "šveitsisaksa", "Prantsusmaa"),
  CountryLocalization("gf", "prantsuse", "Prantsuse Guajaana"),
  CountryLocalization("pf", "prantsuse", "Prantsuse Polüneesia"),
  CountryLocalization("ga", "prantsuse", "Gabon"),
  CountryLocalization("gm", "inglise", "Gambia"),
  CountryLocalization("ge", "osseedi", "Gruusia"),
  CountryLocalization("de", "alamsorbi", "Saksamaa"),
  CountryLocalization("gh", "inglise", "Ghana"),
  CountryLocalization("gi", "inglise", "Gibraltar"),
  CountryLocalization("gr", "kreeka", "Kreeka"),
  CountryLocalization("gl", "grööni", "Gröönimaa"),
  CountryLocalization("gd", "inglise", "Grenada"),
  CountryLocalization("gp", "prantsuse", "Guadeloupe"),
  CountryLocalization("gu", "inglise", "Guam"),
  CountryLocalization("gt", "hispaania", "Guatemala"),
  CountryLocalization("gg", "inglise", "Guernsey"),
  CountryLocalization("gn", "prantsuse", "Guinea"),
  CountryLocalization("gw", "portugali", "Guinea-Bissau"),
  CountryLocalization("gy", "inglise", "Guyana"),
  CountryLocalization("ht", "prantsuse", "Haiti"),
  CountryLocalization("hn", "hispaania", "Honduras"),
  CountryLocalization("hk", "hiina", "Hongkongi erihalduspiirkond"),
  CountryLocalization("hu", "ungari", "Ungari"),
  CountryLocalization("is", "islandi", "Island"),
  CountryLocalization("in", "nepali", "India"),
  CountryLocalization("id", "Indonesian", "Indoneesia"),
  CountryLocalization("ir", "pärsia", "Iraan"),
  CountryLocalization("iq", "põhjaluri", "Iraak"),
  CountryLocalization("ie", "inglise", "Iirimaa"),
  CountryLocalization("im", "mänksi", "Mani saar"),
  CountryLocalization("il", "inglise", "Iisrael"),
  CountryLocalization("it", "saksa", "Itaalia"),
  CountryLocalization("jm", "inglise", "Jamaica"),
  CountryLocalization("jp", "jaapani", "Jaapan"),
  CountryLocalization("je", "inglise", "Jersey"),
  CountryLocalization("jo", "araabia", "Jordaania"),
  CountryLocalization("kz", "kasahhi", "Kasahstan"),
  CountryLocalization("ke", "somaali", "Keenia"),
  CountryLocalization("ki", "inglise", "Kiribati"),
  CountryLocalization("xk", "serbia", "Kosovo"),
  CountryLocalization("kw", "araabia", "Kuveit"),
  CountryLocalization("kg", "vene", "Kõrgõzstan"),
  CountryLocalization("la", "lao", "Laos"),
  CountryLocalization("lv", "läti", "Läti"),
  CountryLocalization("lb", "araabia", "Liibanon"),
  CountryLocalization("ls", "inglise", "Lesotho"),
  CountryLocalization("lr", "inglise", "Libeeria"),
  CountryLocalization("ly", "araabia", "Liibüa"),
  CountryLocalization("li", "šveitsisaksa", "Liechtenstein"),
  CountryLocalization("lt", "leedu", "Leedu"),
  CountryLocalization("lu", "letseburgi", "Luksemburg"),
  CountryLocalization("mo", "portugali", "Macau erihalduspiirkond"),
  CountryLocalization("mk", "albaania", "Makedoonia"),
  CountryLocalization("mg", "prantsuse", "Madagaskar"),
  CountryLocalization("mw", "inglise", "Malawi"),
  CountryLocalization("my", "tamili", "Malaisia"),
  CountryLocalization("ml", "prantsuse", "Mali"),
  CountryLocalization("mt", "inglise", "Malta"),
  CountryLocalization("mh", "inglise", "Marshalli Saared"),
  CountryLocalization("mq", "prantsuse", "Martinique"),
  CountryLocalization("mr", "araabia", "Mauritaania"),
  CountryLocalization("mu", "Mauritiuse kreoolkeel", "Mauritius"),
  CountryLocalization("yt", "prantsuse", "Mayotte"),
  CountryLocalization("mx", "hispaania", "Mehhiko"),
  CountryLocalization("fm", "inglise", "Mikroneesia"),
  CountryLocalization("md", "vene", "Moldova"),
  CountryLocalization("mc", "prantsuse", "Monaco"),
  CountryLocalization("mn", "mongoli", "Mongoolia"),
  CountryLocalization("me", "serbia", "Montenegro"),
  CountryLocalization("ms", "inglise", "Montserrat"),
  CountryLocalization("ma", "tamasikti", "Maroko"),
  CountryLocalization("mz", "makhuwa-meetto", "Mosambiik"),
  CountryLocalization("mm", "birma", "Myanmar (Birma)"),
  CountryLocalization("na", "inglise", "Namiibia"),
  CountryLocalization("nr", "inglise", "Nauru"),
  CountryLocalization("np", "nepali", "Nepal"),
  CountryLocalization("nl", "inglise", "Holland"),
  CountryLocalization("nc", "prantsuse", "Uus-Kaledoonia"),
  CountryLocalization("nz", "inglise", "Uus-Meremaa"),
  CountryLocalization("ni", "hispaania", "Nicaragua"),
  CountryLocalization("ne", "hausa", "Niger"),
  CountryLocalization("ng", "hausa", "Nigeeria"),
  CountryLocalization("nu", "inglise", "Niue"),
  CountryLocalization("nf", "inglise", "Norfolk"),
  CountryLocalization("kp", "korea", "Põhja-Korea"),
  CountryLocalization("mp", "inglise", "Põhja-Mariaanid"),
  CountryLocalization("no", "põhjasaami", "Norra"),
  CountryLocalization("om", "araabia", "Omaan"),
  CountryLocalization("pk", "inglise", "Pakistan"),
  CountryLocalization("pw", "inglise", "Belau"),
  CountryLocalization("ps", "araabia", "Palestiina alad"),
  CountryLocalization("pa", "hispaania", "Panama"),
  CountryLocalization("pg", "inglise", "Paapua Uus-Guinea"),
  CountryLocalization("py", "hispaania", "Paraguay"),
  CountryLocalization("pe", "hispaania", "Peruu"),
  CountryLocalization("ph", "filipiini", "Filipiinid"),
  CountryLocalization("pn", "inglise", "Pitcairni saared"),
  CountryLocalization("pl", "poola", "Poola"),
  CountryLocalization("pt", "portugali", "Portugal"),
  CountryLocalization("pr", "inglise", "Puerto Rico"),
  CountryLocalization("qa", "araabia", "Katar"),
  CountryLocalization("ro", "rumeenia", "Rumeenia"),
  CountryLocalization("ru", "tatari", "Venemaa"),
  CountryLocalization("rw", "inglise", "Rwanda"),
  CountryLocalization("re", "prantsuse", "Réunion"),
  CountryLocalization("ws", "inglise", "Samoa"),
  CountryLocalization("sm", "itaalia", "San Marino"),
  CountryLocalization("sa", "araabia", "Saudi Araabia"),
  CountryLocalization("sn", "prantsuse", "Senegal"),
  CountryLocalization("rs", "serbia", "Serbia"),
  CountryLocalization("cs", "serbia", "Serbia and Montenegro"),
  CountryLocalization("sc", "prantsuse", "Seišellid"),
  CountryLocalization("sl", "inglise", "Sierra Leone"),
  CountryLocalization("sg", "tamili", "Singapur"),
  CountryLocalization("sx", "inglise", "Sint Maarten"),
  CountryLocalization("sk", "slovaki", "Slovakkia"),
  CountryLocalization("si", "sloveeni", "Sloveenia"),
  CountryLocalization("sb", "inglise", "Saalomoni Saared"),
  CountryLocalization("so", "araabia", "Somaalia"),
  CountryLocalization("za", "inglise", "Lõuna-Aafrika Vabariik"),
  CountryLocalization("kr", "korea", "Lõuna-Korea"),
  CountryLocalization("ss", "nueri", "Lõuna-Sudaan"),
  CountryLocalization("es", "hispaania", "Hispaania"),
  CountryLocalization("lk", "tamili", "Sri Lanka"),
  CountryLocalization("bl", "prantsuse", "Saint-Barthélemy"),
  CountryLocalization("sh", "inglise", "Saint Helena"),
  CountryLocalization("kn", "inglise", "Saint Kitts ja Nevis"),
  CountryLocalization("lc", "inglise", "Saint Lucia"),
  CountryLocalization("mf", "prantsuse", "Saint-Martin"),
  CountryLocalization("pm", "prantsuse", "Saint-Pierre ja Miquelon"),
  CountryLocalization("vc", "inglise", "Saint Vincent ja Grenadiinid"),
  CountryLocalization("sd", "araabia", "Sudaan"),
  CountryLocalization("sr", "hollandi", "Suriname"),
  CountryLocalization("sj", "norra bokmål", "Svalbard ja Jan Mayen"),
  CountryLocalization("sz", "inglise", "Svaasimaa"),
  CountryLocalization("se", "rootsi", "Rootsi"),
  CountryLocalization("ch", "šveitsisaksa", "Šveits"),
  CountryLocalization("sy", "araabia", "Süüria"),
  CountryLocalization("st", "portugali", "São Tomé ja Príncipe"),
  CountryLocalization("tw", "hiina", "Taiwan"),
  CountryLocalization("tj", "tadžiki", "Tadžikistan"),
  CountryLocalization("tz", "makonde", "Tansaania"),
  CountryLocalization("th", "tai", "Tai"),
  CountryLocalization("tl", "portugali", "Ida-Timor"),
  CountryLocalization("tg", "prantsuse", "Togo"),
  CountryLocalization("tk", "inglise", "Tokelau"),
  CountryLocalization("to", "tonga", "Tonga"),
  CountryLocalization("tt", "inglise", "Trinidad ja Tobago"),
  CountryLocalization("tn", "prantsuse", "Tuneesia"),
  CountryLocalization("tr", "türgi", "Türgi"),
  CountryLocalization("tm", "türkmeeni", "Türkmenistan"),
  CountryLocalization("tc", "inglise", "Turks ja Caicos"),
  CountryLocalization("tv", "inglise", "Tuvalu"),
  CountryLocalization("um", "inglise", "Ühendriikide hajasaared"),
  CountryLocalization("vi", "inglise", "USA Neitsisaared"),
  CountryLocalization("ug", "suahiili", "Uganda"),
  CountryLocalization("ua", "ukraina", "Ukraina"),
  CountryLocalization("ae", "araabia", "Araabia Ühendemiraadid"),
  CountryLocalization("gb", "inglise", "Suurbritannia"),
  CountryLocalization("us", "lakota", "Ameerika Ühendriigid"),
  CountryLocalization("uy", "hispaania", "Uruguay"),
  CountryLocalization("uz", "usbeki", "Usbekistan"),
  CountryLocalization("vu", "prantsuse", "Vanuatu"),
  CountryLocalization("va", "itaalia", "Vatikan"),
  CountryLocalization("ve", "hispaania", "Venezuela"),
  CountryLocalization("vn", "vietnami", "Vietnam"),
  CountryLocalization("wf", "prantsuse", "Wallis ja Futuna"),
  CountryLocalization("eh", "araabia", "Lääne-Sahara"),
  CountryLocalization("ye", "araabia", "Jeemen"),
  CountryLocalization("zm", "inglise", "Sambia"),
  CountryLocalization("zw", "põhjandebele", "Zimbabwe"),
  CountryLocalization("ax", "rootsi", "Ahvenamaa"),
)
