/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot.atlas.extended

import dev.teogor.xenoglot.atlas.CountryLocalization
import kotlin.collections.List

/**
 * Holds the internal list of country-language mappings used for lookups within the package for
 * language code nd.
 *
 * This property contains a hardcoded list of [CountryLocalization] objects, each representing
 * a country and its associated official languages. This list is used by [CountryLanguageRegistry]
 * to provide access to country-language data and should not be modified directly.
 *
 * @see CountryLocalization
 * @see CountryLanguageRegistry
 */
internal val _countryLanguageMappings_nd: List<CountryLocalization> = listOf(
  CountryLocalization("af", "isi-Pheshiyani", "Afghanistan"),
  CountryLocalization("al", "Albanian", "Albania"),
  CountryLocalization("dz", "isi-Fulentshi", "Aljeriya"),
  CountryLocalization("as", "isi-Ngisi", "Samoa ye Amelika"),
  CountryLocalization("ad", "Catalan", "Andora"),
  CountryLocalization("ao", "Lingala", "Angola"),
  CountryLocalization("ai", "isi-Ngisi", "Anguilla"),
  CountryLocalization("ag", "isi-Ngisi", "Antigua le Barbuda"),
  CountryLocalization("ar", "isi-Sipeyini", "Ajentina"),
  CountryLocalization("am", "Armenian", "Armenia"),
  CountryLocalization("aw", "isi-Dutch", "Arubha"),
  CountryLocalization("au", "isi-Ngisi", "Australia"),
  CountryLocalization("at", "isi-Ngisi", "Austria"),
  CountryLocalization("az", "Azerbaijani", "Azerbaijan"),
  CountryLocalization("bs", "isi-Ngisi", "Bhahamas"),
  CountryLocalization("bh", "isi-Alabhu", "Bhahareni"),
  CountryLocalization("bd", "isi-Bhengali", "Bhangiladeshi"),
  CountryLocalization("bb", "isi-Ngisi", "Bhabhadosi"),
  CountryLocalization("by", "isi-Bhelarashiyani", "Bhelarusi"),
  CountryLocalization("be", "isi-Fulentshi", "Bhelgium"),
  CountryLocalization("bz", "isi-Ngisi", "Bhelize"),
  CountryLocalization("bj", "isi-Fulentshi", "Bhenini"),
  CountryLocalization("bm", "isi-Ngisi", "Bhemuda"),
  CountryLocalization("bt", "Dzongkha", "Bhutani"),
  CountryLocalization("bo", "isi-Sipeyini", "Bholiviya"),
  CountryLocalization("ba", "Bosnian", "Bhosnia le Herzegovina"),
  CountryLocalization("bw", "isi-Ngisi", "Botswana"),
  CountryLocalization("br", "isi-Potukezi", "Brazili"),
  CountryLocalization("io", "isi-Ngisi", "British Indian Ocean Territory"),
  CountryLocalization("vg", "isi-Ngisi", "British Virgin Islands"),
  CountryLocalization("bn", "isi-Malayi", "Brunei"),
  CountryLocalization("bg", "isi-Bulgaria", "Bhulgariya"),
  CountryLocalization("bf", "isi-Fulentshi", "Bhukina Faso"),
  CountryLocalization("bi", "isi-Fulentshi", "Bhurundi"),
  CountryLocalization("kh", "isi-Khambodiya", "Cambodia"),
  CountryLocalization("cm", "Basaa", "Khameruni"),
  CountryLocalization("ca", "isi-Fulentshi", "Khanada"),
  CountryLocalization("ic", "isi-Sipeyini", "IC"),
  CountryLocalization("cv", "kea", "Cape Verde Islands"),
  CountryLocalization("bq", "isi-Dutch", "Caribbean Netherlands"),
  CountryLocalization("ky", "isi-Ngisi", "Cayman Islands"),
  CountryLocalization("cf", "Lingala", "Central African Republic"),
  CountryLocalization("ea", "isi-Sipeyini", "EA"),
  CountryLocalization("td", "isi-Alabhu", "Chadi"),
  CountryLocalization("cl", "isi-Sipeyini", "Chile"),
  CountryLocalization("cn", "Tibetan", "China"),
  CountryLocalization("cx", "isi-Ngisi", "Christmas Island"),
  CountryLocalization("cc", "isi-Ngisi", "Cocos (Keeling) Islands"),
  CountryLocalization("co", "isi-Sipeyini", "Kholombiya"),
  CountryLocalization("km", "isi-Alabhu", "Khomoro"),
  CountryLocalization("cg", "Lingala", "Khongo"),
  CountryLocalization("cd", "Swahili", "Democratic Republic of the Congo"),
  CountryLocalization("ck", "isi-Ngisi", "Cook Islands"),
  CountryLocalization("cr", "isi-Sipeyini", "Khosta Rikha"),
  CountryLocalization("hr", "Croatian", "Croatia"),
  CountryLocalization("cu", "isi-Sipeyini", "Cuba"),
  CountryLocalization("cw", "isi-Dutch", "Curaçao"),
  CountryLocalization("cy", "isi-Ngisi", "Cyprus"),
  CountryLocalization("cz", "isi-Czech", "Czech Republic"),
  CountryLocalization("ci", "isi-Fulentshi", "Ivory Coast"),
  CountryLocalization("dk", "isi-Ngisi", "Denmakhi"),
  CountryLocalization("dg", "isi-Ngisi", "DG"),
  CountryLocalization("dj", "isi-Fulentshi", "Djibouti"),
  CountryLocalization("dm", "isi-Ngisi", "Dominikha"),
  CountryLocalization("do", "isi-Sipeyini", "Dominican Republic"),
  CountryLocalization("ec", "Quechua", "Ecuador"),
  CountryLocalization("eg", "isi-Alabhu", "Egypt"),
  CountryLocalization("sv", "isi-Sipeyini", "El Salvador"),
  CountryLocalization("gq", "isi-Sipeyini", "Equatorial Guinea"),
  CountryLocalization("er", "Tigrinya", "Eritrea"),
  CountryLocalization("ee", "Estonian", "Estonia"),
  CountryLocalization("et", "isi-Amaharikhi", "Ethiopia"),
  CountryLocalization("fk", "isi-Ngisi", "Falkland Islands"),
  CountryLocalization("fo", "Faroese", "Faroe Islands"),
  CountryLocalization("fj", "isi-Ngisi", "Fiji"),
  CountryLocalization("fi", "isi-Swidishi", "Finland"),
  CountryLocalization("fr", "Swiss German", "Furansi"),
  CountryLocalization("gf", "isi-Fulentshi", "Gwiyana ye Furansi"),
  CountryLocalization("pf", "isi-Fulentshi", "Pholinesiya ye Fulansi"),
  CountryLocalization("ga", "isi-Fulentshi", "Gabhoni"),
  CountryLocalization("gm", "isi-Ngisi", "Gambiya"),
  CountryLocalization("ge", "Ossetic", "Georgia"),
  CountryLocalization("de", "Lower Sorbian", "Germany"),
  CountryLocalization("gh", "isi-Ngisi", "Ghana"),
  CountryLocalization("gi", "isi-Ngisi", "Gibraltar"),
  CountryLocalization("gr", "isi-Giliki", "Greece"),
  CountryLocalization("gl", "Kalaallisut", "Greenland"),
  CountryLocalization("gd", "isi-Ngisi", "Grenada"),
  CountryLocalization("gp", "isi-Fulentshi", "Guadeloupe"),
  CountryLocalization("gu", "isi-Ngisi", "Guam"),
  CountryLocalization("gt", "isi-Sipeyini", "Guatemala"),
  CountryLocalization("gg", "isi-Ngisi", "Guernsey"),
  CountryLocalization("gn", "isi-Fulentshi", "Guinea"),
  CountryLocalization("gw", "isi-Potukezi", "Guinea-Bissau"),
  CountryLocalization("gy", "isi-Ngisi", "Guyana"),
  CountryLocalization("ht", "isi-Fulentshi", "Hayiti"),
  CountryLocalization("hn", "isi-Sipeyini", "Honduras"),
  CountryLocalization("hk", "isi-China", "Hong Kong SAR China"),
  CountryLocalization("hu", "isi-Hangari", "Hungary"),
  CountryLocalization("is", "Icelandic", "Iceland"),
  CountryLocalization("in", "isi-Nepali", "Indiya"),
  CountryLocalization("id", "Indonesian", "Indonesiya"),
  CountryLocalization("ir", "isi-Pheshiyani", "Iran"),
  CountryLocalization("iq", "lrc", "Iraki"),
  CountryLocalization("ie", "isi-Ngisi", "Ireland"),
  CountryLocalization("im", "Manx", "Isle of Man"),
  CountryLocalization("il", "isi-Ngisi", "Isuraeli"),
  CountryLocalization("it", "isi-Jalimani", "Itali"),
  CountryLocalization("jm", "isi-Ngisi", "Jamaica"),
  CountryLocalization("jp", "isi-Japhani", "Japan"),
  CountryLocalization("je", "isi-Ngisi", "Jersey"),
  CountryLocalization("jo", "isi-Alabhu", "Jodani"),
  CountryLocalization("kz", "Kazakh", "Kazakhstan"),
  CountryLocalization("ke", "isi-Somali", "Khenya"),
  CountryLocalization("ki", "isi-Ngisi", "Khiribati"),
  CountryLocalization("xk", "Serbian", "XK"),
  CountryLocalization("kw", "isi-Alabhu", "Khuweiti"),
  CountryLocalization("kg", "isi-Rashiya", "Kyrgyzstan"),
  CountryLocalization("la", "Lao", "Laos"),
  CountryLocalization("lv", "Latvian", "Latvia"),
  CountryLocalization("lb", "isi-Alabhu", "Lebhanoni"),
  CountryLocalization("ls", "isi-Ngisi", "Lesotho"),
  CountryLocalization("lr", "isi-Ngisi", "Libheriya"),
  CountryLocalization("ly", "isi-Alabhu", "Libhiya"),
  CountryLocalization("li", "Swiss German", "Liechtenstein"),
  CountryLocalization("lt", "Lithuanian", "Lithuania"),
  CountryLocalization("lu", "Luxembourgish", "Luxembourg"),
  CountryLocalization("mo", "isi-Potukezi", "Macao SAR China"),
  CountryLocalization("mk", "Albanian", "Macedonia"),
  CountryLocalization("mg", "isi-Fulentshi", "Madagaska"),
  CountryLocalization("mw", "isi-Ngisi", "Malawi"),
  CountryLocalization("my", "isi-Thamil", "Malezhiya"),
  CountryLocalization("ml", "isi-Fulentshi", "Mali"),
  CountryLocalization("mt", "isi-Ngisi", "Malta"),
  CountryLocalization("mh", "isi-Ngisi", "Marshall Islands"),
  CountryLocalization("mq", "isi-Fulentshi", "Martinique"),
  CountryLocalization("mr", "isi-Alabhu", "Mauritania"),
  CountryLocalization("mu", "mfe", "Mauritius"),
  CountryLocalization("yt", "isi-Fulentshi", "Mayotte"),
  CountryLocalization("mx", "isi-Sipeyini", "Meksikho"),
  CountryLocalization("fm", "isi-Ngisi", "Micronesia"),
  CountryLocalization("md", "isi-Rashiya", "Moldova"),
  CountryLocalization("mc", "isi-Fulentshi", "Monakho"),
  CountryLocalization("mn", "Mongolian", "Mongolia"),
  CountryLocalization("me", "Serbian", "Montenegro"),
  CountryLocalization("ms", "isi-Ngisi", "Montserrat"),
  CountryLocalization("ma", "tzm", "Morokho"),
  CountryLocalization("mz", "mgh", "Mozambique"),
  CountryLocalization("mm", "isi-Burma", "Myanmar"),
  CountryLocalization("na", "isi-Ngisi", "Namibhiya"),
  CountryLocalization("nr", "isi-Ngisi", "Nauru"),
  CountryLocalization("np", "isi-Nepali", "Nephali"),
  CountryLocalization("nl", "isi-Ngisi", "Netherlands"),
  CountryLocalization("nc", "isi-Fulentshi", "New Caledonia"),
  CountryLocalization("nz", "isi-Ngisi", "New Zealand"),
  CountryLocalization("ni", "isi-Sipeyini", "Nicaragua"),
  CountryLocalization("ne", "isi-Hausa", "Niger"),
  CountryLocalization("ng", "isi-Hausa", "Nigeriya"),
  CountryLocalization("nu", "isi-Ngisi", "Niue"),
  CountryLocalization("nf", "isi-Ngisi", "Norfolk Island"),
  CountryLocalization("kp", "isi-Koriya", "North Korea"),
  CountryLocalization("mp", "isi-Ngisi", "Northern Mariana Islands"),
  CountryLocalization("no", "Northern Sami", "Noweyi"),
  CountryLocalization("om", "isi-Alabhu", "Omani"),
  CountryLocalization("pk", "isi-Ngisi", "Phakistani"),
  CountryLocalization("pw", "isi-Ngisi", "Palau"),
  CountryLocalization("ps", "isi-Alabhu", "Palestinian West Bank and Gaza"),
  CountryLocalization("pa", "isi-Sipeyini", "Panama"),
  CountryLocalization("pg", "isi-Ngisi", "Papua New Guinea"),
  CountryLocalization("py", "isi-Sipeyini", "Paraguay"),
  CountryLocalization("pe", "isi-Sipeyini", "Pheru"),
  CountryLocalization("ph", "Filipino", "Philippines"),
  CountryLocalization("pn", "isi-Ngisi", "Pitcairn"),
  CountryLocalization("pl", "isi-Pholoshi", "Pholandi"),
  CountryLocalization("pt", "isi-Potukezi", "Portugal"),
  CountryLocalization("pr", "isi-Ngisi", "Puerto Rico"),
  CountryLocalization("qa", "isi-Alabhu", "Kathari"),
  CountryLocalization("ro", "isi-Romani", "Romania"),
  CountryLocalization("ru", "Tatar", "Rashiya"),
  CountryLocalization("rw", "isi-Ngisi", "Ruwanda"),
  CountryLocalization("re", "isi-Fulentshi", "Réunion"),
  CountryLocalization("ws", "isi-Ngisi", "Samowa"),
  CountryLocalization("sm", "isi-Italiano", "San Marino"),
  CountryLocalization("sa", "isi-Alabhu", "Saudi Arabia"),
  CountryLocalization("sn", "isi-Fulentshi", "Senegali"),
  CountryLocalization("rs", "Serbian", "Serbia"),
  CountryLocalization("cs", "Serbian", "Serbia and Montenegro"),
  CountryLocalization("sc", "isi-Fulentshi", "Seychelles"),
  CountryLocalization("sl", "isi-Ngisi", "Sierra Leone"),
  CountryLocalization("sg", "isi-Thamil", "Singapore"),
  CountryLocalization("sx", "isi-Ngisi", "Sint Maarten"),
  CountryLocalization("sk", "Slovak", "Slovakia"),
  CountryLocalization("si", "Slovenian", "Slovenia"),
  CountryLocalization("sb", "isi-Ngisi", "Solomon Islands"),
  CountryLocalization("so", "isi-Alabhu", "Somaliya"),
  CountryLocalization("za", "isi-Ngisi", "Mzansi ye Afrika"),
  CountryLocalization("kr", "isi-Koriya", "South Korea"),
  CountryLocalization("ss", "nus", "South Sudan"),
  CountryLocalization("es", "isi-Sipeyini", "Spain"),
  CountryLocalization("lk", "isi-Thamil", "Sri Lanka"),
  CountryLocalization("bl", "isi-Fulentshi", "St. Barthélemy"),
  CountryLocalization("sh", "isi-Ngisi", "Saint Helena"),
  CountryLocalization("kn", "isi-Ngisi", "Saint Kitts and Nevis"),
  CountryLocalization("lc", "isi-Ngisi", "Saint Lucia"),
  CountryLocalization("mf", "isi-Fulentshi", "St. Martin"),
  CountryLocalization("pm", "isi-Fulentshi", "Saint Pierre and Miquelon"),
  CountryLocalization("vc", "isi-Ngisi", "Saint Vincent and the Grenadines"),
  CountryLocalization("sd", "isi-Alabhu", "Sudani"),
  CountryLocalization("sr", "isi-Dutch", "Suriname"),
  CountryLocalization("sj", "Norwegian Bokmål", "Svalbard & Jan Mayen"),
  CountryLocalization("sz", "isi-Ngisi", "Swaziland"),
  CountryLocalization("se", "isi-Swidishi", "Sweden"),
  CountryLocalization("ch", "Swiss German", "Switzerland"),
  CountryLocalization("sy", "isi-Alabhu", "Syria"),
  CountryLocalization("st", "isi-Potukezi", "São Tomé and Príncipe"),
  CountryLocalization("tw", "isi-China", "Thayiwani"),
  CountryLocalization("tj", "Tajik", "Tajikistan"),
  CountryLocalization("tz", "kde", "Tanzaniya"),
  CountryLocalization("th", "isi-Thayi", "Thayilandi"),
  CountryLocalization("tl", "isi-Potukezi", "East Timor"),
  CountryLocalization("tg", "isi-Fulentshi", "Thogo"),
  CountryLocalization("tk", "isi-Ngisi", "Thokelawu"),
  CountryLocalization("to", "Tongan", "Thonga"),
  CountryLocalization("tt", "isi-Ngisi", "Trinidad le Tobago"),
  CountryLocalization("tn", "isi-Fulentshi", "Tunisiya"),
  CountryLocalization("tr", "isi-Thekishi", "Thekhi"),
  CountryLocalization("tm", "Turkmen", "Turkmenistan"),
  CountryLocalization("tc", "isi-Ngisi", "Turks and Caicos Islands"),
  CountryLocalization("tv", "isi-Ngisi", "Thuvalu"),
  CountryLocalization("um", "isi-Ngisi", "U.S. Outlying Islands"),
  CountryLocalization("vi", "isi-Ngisi", "U.S. Virgin Islands"),
  CountryLocalization("ug", "Swahili", "Uganda"),
  CountryLocalization("ua", "isi-Ukrain", "Yukreini"),
  CountryLocalization("ae", "isi-Alabhu", "United Arab Emirates"),
  CountryLocalization("gb", "isi-Ngisi", "United Kingdom"),
  CountryLocalization("us", "lkt", "Amelika"),
  CountryLocalization("uy", "isi-Sipeyini", "Yurugwai"),
  CountryLocalization("uz", "Uzbek", "Uzbekistan"),
  CountryLocalization("vu", "isi-Fulentshi", "Vhanuatu"),
  CountryLocalization("va", "isi-Italiano", "Vatican State"),
  CountryLocalization("ve", "isi-Sipeyini", "Venezuela"),
  CountryLocalization("vn", "isi-Vietnamese", "Vietnam"),
  CountryLocalization("wf", "isi-Fulentshi", "Wallis and Futuna"),
  CountryLocalization("eh", "isi-Alabhu", "Western Sahara"),
  CountryLocalization("ye", "isi-Alabhu", "Yemeni"),
  CountryLocalization("zm", "isi-Ngisi", "Zambiya"),
  CountryLocalization("zw", "isiNdebele", "Zimbabwe"),
  CountryLocalization("ax", "isi-Swidishi", "Åland Islands"),
)
