/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot.atlas.extended

import dev.teogor.xenoglot.atlas.CountryLocalization
import kotlin.collections.List

/**
 * Holds the internal list of country-language mappings used for lookups within the package for
 * language code bn.
 *
 * This property contains a hardcoded list of [CountryLocalization] objects, each representing
 * a country and its associated official languages. This list is used by [CountryLanguageRegistry]
 * to provide access to country-language data and should not be modified directly.
 *
 * @see CountryLocalization
 * @see CountryLanguageRegistry
 */
internal val _countryLanguageMappings_bn: List<CountryLocalization> = listOf(
  CountryLocalization("af", "ফার্সি", "আফগানিস্তান"),
  CountryLocalization("al", "আলবেনীয়", "আলবেনিয়া"),
  CountryLocalization("dz", "ফরাসি", "আলজেরিয়া"),
  CountryLocalization("as", "ইংরেজি", "আমেরিকান সামোয়া"),
  CountryLocalization("ad", "কাতালান", "আন্ডোরা"),
  CountryLocalization("ao", "লিঙ্গালা", "অ্যাঙ্গোলা"),
  CountryLocalization("ai", "ইংরেজি", "এ্যাঙ্গুইলা"),
  CountryLocalization("ag", "ইংরেজি", "অ্যান্টিগুয়া ও বারবুডা"),
  CountryLocalization("ar", "স্প্যানিশ", "আর্জেন্টিনা"),
  CountryLocalization("am", "আর্মেনিয়", "আর্মেনিয়া"),
  CountryLocalization("aw", "ডাচ", "আরুবা"),
  CountryLocalization("au", "ইংরেজি", "অস্ট্রেলিয়া"),
  CountryLocalization("at", "ইংরেজি", "অস্ট্রিয়া"),
  CountryLocalization("az", "আজারবাইজানী", "আজারবাইজান"),
  CountryLocalization("bs", "ইংরেজি", "বাহামা দ্বীপপুঞ্জ"),
  CountryLocalization("bh", "আরবী", "বাহরাইন"),
  CountryLocalization("bd", "বাংলা", "বাংলাদেশ"),
  CountryLocalization("bb", "ইংরেজি", "বারবাদোস"),
  CountryLocalization("by", "বেলারুশিয়", "বেলারুশ"),
  CountryLocalization("be", "ফরাসি", "বেলজিয়াম"),
  CountryLocalization("bz", "ইংরেজি", "বেলিজ"),
  CountryLocalization("bj", "ফরাসি", "বেনিন"),
  CountryLocalization("bm", "ইংরেজি", "বারমুডা"),
  CountryLocalization("bt", "জোঙ্গা", "ভুটান"),
  CountryLocalization("bo", "স্প্যানিশ", "বলিভিয়া"),
  CountryLocalization("ba", "বসনীয়ান", "বসনিয়া ও হার্জেগোভিনা"),
  CountryLocalization("bw", "ইংরেজি", "বতসোয়ানা"),
  CountryLocalization("br", "পর্তুগীজ", "ব্রাজিল"),
  CountryLocalization("io", "ইংরেজি", "ব্রিটিশ ভারত মহাসাগরীয় অঞ্চল"),
  CountryLocalization("vg", "ইংরেজি", "ব্রিটিশ ভার্জিন দ্বীপপুঞ্জ"),
  CountryLocalization("bn", "মালয়", "ব্রুনেই"),
  CountryLocalization("bg", "বুলগেরিয়", "বুলগেরিয়া"),
  CountryLocalization("bf", "ফরাসি", "বুরকিনা ফাসো"),
  CountryLocalization("bi", "ফরাসি", "বুরুন্ডি"),
  CountryLocalization("kh", "খমের", "কম্বোডিয়া"),
  CountryLocalization("cm", "বাসা", "ক্যামেরুন"),
  CountryLocalization("ca", "ফরাসি", "কানাডা"),
  CountryLocalization("ic", "স্প্যানিশ", "ক্যানারি দ্বীপপুঞ্জ"),
  CountryLocalization("cv", "কাবুভারদিয়ানু", "কেপভার্দে"),
  CountryLocalization("bq", "ডাচ", "ক্যারিবিয়ান নেদারল্যান্ডস"),
  CountryLocalization("ky", "ইংরেজি", "কেম্যান দ্বীপপুঞ্জ"),
  CountryLocalization("cf", "লিঙ্গালা", "মধ্য আফ্রিকার প্রজাতন্ত্র"),
  CountryLocalization("ea", "স্প্যানিশ", "কুউটা এবং মেলিলা"),
  CountryLocalization("td", "আরবী", "চাদ"),
  CountryLocalization("cl", "স্প্যানিশ", "চিলি"),
  CountryLocalization("cn", "তিব্বতি", "চীন"),
  CountryLocalization("cx", "ইংরেজি", "ক্রিসমাস দ্বীপ"),
  CountryLocalization("cc", "ইংরেজি", "কোকোস (কিলিং) দ্বীপপুঞ্জ"),
  CountryLocalization("co", "স্প্যানিশ", "কলম্বিয়া"),
  CountryLocalization("km", "আরবী", "কমোরোস"),
  CountryLocalization("cg", "লিঙ্গালা", "কঙ্গো - ব্রাজাভিল"),
  CountryLocalization("cd", "সোয়াহিলি", "কঙ্গো-কিনশাসা"),
  CountryLocalization("ck", "ইংরেজি", "কুক দ্বীপপুঞ্জ"),
  CountryLocalization("cr", "স্প্যানিশ", "কোস্টারিকা"),
  CountryLocalization("hr", "ক্রোয়েশীয়", "ক্রোয়েশিয়া"),
  CountryLocalization("cu", "স্প্যানিশ", "কিউবা"),
  CountryLocalization("cw", "ডাচ", "কুরাসাও"),
  CountryLocalization("cy", "ইংরেজি", "সাইপ্রাস"),
  CountryLocalization("cz", "চেক", "চেচিয়া"),
  CountryLocalization("ci", "ফরাসি", "কোত দিভোয়ার"),
  CountryLocalization("dk", "ইংরেজি", "ডেনমার্ক"),
  CountryLocalization("dg", "ইংরেজি", "দিয়েগো গার্সিয়া"),
  CountryLocalization("dj", "ফরাসি", "জিবুতি"),
  CountryLocalization("dm", "ইংরেজি", "ডোমিনিকা"),
  CountryLocalization("do", "স্প্যানিশ", "ডোমেনিকান প্রজাতন্ত্র"),
  CountryLocalization("ec", "কেচুয়া", "ইকুয়েডর"),
  CountryLocalization("eg", "আরবী", "মিশর"),
  CountryLocalization("sv", "স্প্যানিশ", "এল সালভেদর"),
  CountryLocalization("gq", "স্প্যানিশ", "নিরক্ষীয় গিনি"),
  CountryLocalization("er", "তিগরিনিয়া", "ইরিত্রিয়া"),
  CountryLocalization("ee", "এস্তোনীয়", "এস্তোনিয়া"),
  CountryLocalization("et", "আমহারিক", "ইথিওপিয়া"),
  CountryLocalization("fk", "ইংরেজি", "ফকল্যান্ড দ্বীপপুঞ্জ"),
  CountryLocalization("fo", "ফারোস", "ফ্যারও দ্বীপপুঞ্জ"),
  CountryLocalization("fj", "ইংরেজি", "ফিজি"),
  CountryLocalization("fi", "সুইডিশ", "ফিনল্যান্ড"),
  CountryLocalization("fr", "সুইস জার্মান", "ফ্রান্স"),
  CountryLocalization("gf", "ফরাসি", "ফরাসী গায়ানা"),
  CountryLocalization("pf", "ফরাসি", "ফরাসী পলিনেশিয়া"),
  CountryLocalization("ga", "ফরাসি", "গ্যাবন"),
  CountryLocalization("gm", "ইংরেজি", "গাম্বিয়া"),
  CountryLocalization("ge", "ওসেটিক", "জর্জিয়া"),
  CountryLocalization("de", "নিম্নতর সোর্বিয়ান", "জার্মানি"),
  CountryLocalization("gh", "ইংরেজি", "ঘানা"),
  CountryLocalization("gi", "ইংরেজি", "জিব্রাল্টার"),
  CountryLocalization("gr", "গ্রিক", "গ্রীস"),
  CountryLocalization("gl", "ক্যালাল্লিসুট", "গ্রীনল্যান্ড"),
  CountryLocalization("gd", "ইংরেজি", "গ্রেনাডা"),
  CountryLocalization("gp", "ফরাসি", "গুয়াদেলৌপ"),
  CountryLocalization("gu", "ইংরেজি", "গুয়াম"),
  CountryLocalization("gt", "স্প্যানিশ", "গুয়াতেমালা"),
  CountryLocalization("gg", "ইংরেজি", "গুয়ার্নসি"),
  CountryLocalization("gn", "ফরাসি", "গিনি"),
  CountryLocalization("gw", "পর্তুগীজ", "গিনি-বিসাউ"),
  CountryLocalization("gy", "ইংরেজি", "গিয়ানা"),
  CountryLocalization("ht", "ফরাসি", "হাইতি"),
  CountryLocalization("hn", "স্প্যানিশ", "হন্ডুরাস"),
  CountryLocalization("hk", "চীনা", "হংকং এসএআর চীনা"),
  CountryLocalization("hu", "হাঙ্গেরীয়", "হাঙ্গেরি"),
  CountryLocalization("is", "আইসল্যান্ডীয়", "আইসল্যান্ড"),
  CountryLocalization("in", "নেপালী", "ভারত"),
  CountryLocalization("id", "Indonesian", "ইন্দোনেশিয়া"),
  CountryLocalization("ir", "ফার্সি", "ইরান"),
  CountryLocalization("iq", "উত্তর লুরি", "ইরাক"),
  CountryLocalization("ie", "ইংরেজি", "আয়ারল্যান্ড"),
  CountryLocalization("im", "ম্যাঙ্কস", "আইল অফ ম্যান"),
  CountryLocalization("il", "ইংরেজি", "ইজরায়েল"),
  CountryLocalization("it", "জার্মান", "ইতালি"),
  CountryLocalization("jm", "ইংরেজি", "জামাইকা"),
  CountryLocalization("jp", "জাপানি", "জাপান"),
  CountryLocalization("je", "ইংরেজি", "জার্সি"),
  CountryLocalization("jo", "আরবী", "জর্ডন"),
  CountryLocalization("kz", "কাজাখ", "কাজাখস্তান"),
  CountryLocalization("ke", "সোমালি", "কেনিয়া"),
  CountryLocalization("ki", "ইংরেজি", "কিরিবাতি"),
  CountryLocalization("xk", "সার্বীয়", "কসোভো"),
  CountryLocalization("kw", "আরবী", "কুয়েত"),
  CountryLocalization("kg", "রুশ", "কিরগিজিস্তান"),
  CountryLocalization("la", "লাও", "লাওস"),
  CountryLocalization("lv", "লাত্‌ভীয়", "লাত্ভিয়া"),
  CountryLocalization("lb", "আরবী", "লেবানন"),
  CountryLocalization("ls", "ইংরেজি", "লেসোথো"),
  CountryLocalization("lr", "ইংরেজি", "লাইবেরিয়া"),
  CountryLocalization("ly", "আরবী", "লিবিয়া"),
  CountryLocalization("li", "সুইস জার্মান", "লিচেনস্টেইন"),
  CountryLocalization("lt", "লিথুয়েনীয়", "লিথুয়ানিয়া"),
  CountryLocalization("lu", "লুক্সেমবার্গীয়", "লাক্সেমবার্গ"),
  CountryLocalization("mo", "পর্তুগীজ", "ম্যাকাও এসএআর চীনা"),
  CountryLocalization("mk", "আলবেনীয়", "ম্যাসাডোনিয়া"),
  CountryLocalization("mg", "ফরাসি", "মাদাগাস্কার"),
  CountryLocalization("mw", "ইংরেজি", "মালাউই"),
  CountryLocalization("my", "তামিল", "মালয়েশিয়া"),
  CountryLocalization("ml", "ফরাসি", "মালি"),
  CountryLocalization("mt", "ইংরেজি", "মাল্টা"),
  CountryLocalization("mh", "ইংরেজি", "মার্শাল দ্বীপপুঞ্জ"),
  CountryLocalization("mq", "ফরাসি", "মার্টিনিক"),
  CountryLocalization("mr", "আরবী", "মরিতানিয়া"),
  CountryLocalization("mu", "মরিসিয়ান", "মরিশাস"),
  CountryLocalization("yt", "ফরাসি", "মায়োত্তে"),
  CountryLocalization("mx", "স্প্যানিশ", "মেক্সিকো"),
  CountryLocalization("fm", "ইংরেজি", "মাইক্রোনেশিয়া"),
  CountryLocalization("md", "রুশ", "মোল্দাভিয়া"),
  CountryLocalization("mc", "ফরাসি", "মোনাকো"),
  CountryLocalization("mn", "মঙ্গোলিয়", "মঙ্গোলিয়া"),
  CountryLocalization("me", "সার্বীয়", "মন্টিনিগ্রো"),
  CountryLocalization("ms", "ইংরেজি", "মন্টসেরাট"),
  CountryLocalization("ma", "সেন্ট্রাল আটলাস তামাজিগাত", "মোরক্কো"),
  CountryLocalization("mz", "মাখুয়া-মেত্তো", "মোজাম্বিক"),
  CountryLocalization("mm", "বর্মি", "মায়ানমার (বার্মা)"),
  CountryLocalization("na", "ইংরেজি", "নামিবিয়া"),
  CountryLocalization("nr", "ইংরেজি", "নাউরু"),
  CountryLocalization("np", "নেপালী", "নেপাল"),
  CountryLocalization("nl", "ইংরেজি", "নেদারল্যান্ডস"),
  CountryLocalization("nc", "ফরাসি", "নিউ ক্যালেডোনিয়া"),
  CountryLocalization("nz", "ইংরেজি", "নিউজিল্যান্ড"),
  CountryLocalization("ni", "স্প্যানিশ", "নিকারাগুয়া"),
  CountryLocalization("ne", "হাউসা", "নাইজার"),
  CountryLocalization("ng", "হাউসা", "নাইজেরিয়া"),
  CountryLocalization("nu", "ইংরেজি", "নিউয়ে"),
  CountryLocalization("nf", "ইংরেজি", "নরফোক দ্বীপ"),
  CountryLocalization("kp", "কোরিয়ান", "উত্তর কোরিয়া"),
  CountryLocalization("mp", "ইংরেজি", "উত্তরাঞ্চলীয় মারিয়ানা দ্বীপপুঞ্জ"),
  CountryLocalization("no", "উত্তরাঞ্চলীয় সামি", "নরওয়ে"),
  CountryLocalization("om", "আরবী", "ওমান"),
  CountryLocalization("pk", "ইংরেজি", "পাকিস্তান"),
  CountryLocalization("pw", "ইংরেজি", "পালাউ"),
  CountryLocalization("ps", "আরবী", "প্যালেস্টাইনের অঞ্চলসমূহ"),
  CountryLocalization("pa", "স্প্যানিশ", "পানামা"),
  CountryLocalization("pg", "ইংরেজি", "পাপুয়া নিউ গিনি"),
  CountryLocalization("py", "স্প্যানিশ", "প্যারাগুয়ে"),
  CountryLocalization("pe", "স্প্যানিশ", "পেরু"),
  CountryLocalization("ph", "ফিলিপিনো", "ফিলিপাইন"),
  CountryLocalization("pn", "ইংরেজি", "পিটকেয়ার্ন দ্বীপপুঞ্জ"),
  CountryLocalization("pl", "পোলিশ", "পোল্যান্ড"),
  CountryLocalization("pt", "পর্তুগীজ", "পর্তুগাল"),
  CountryLocalization("pr", "ইংরেজি", "পুয়ের্তো রিকো"),
  CountryLocalization("qa", "আরবী", "কাতার"),
  CountryLocalization("ro", "রোমানীয়", "রোমানিয়া"),
  CountryLocalization("ru", "তাতার", "রাশিয়া"),
  CountryLocalization("rw", "ইংরেজি", "রুয়ান্ডা"),
  CountryLocalization("re", "ফরাসি", "রিইউনিয়ন"),
  CountryLocalization("ws", "ইংরেজি", "সামোয়া"),
  CountryLocalization("sm", "ইতালিয়", "সান মারিনো"),
  CountryLocalization("sa", "আরবী", "সৌদি আরব"),
  CountryLocalization("sn", "ফরাসি", "সেনেগাল"),
  CountryLocalization("rs", "সার্বীয়", "সার্বিয়া"),
  CountryLocalization("cs", "সার্বীয়", "Serbia and Montenegro"),
  CountryLocalization("sc", "ফরাসি", "সিসিলি"),
  CountryLocalization("sl", "ইংরেজি", "সিয়েরা লিওন"),
  CountryLocalization("sg", "তামিল", "সিঙ্গাপুর"),
  CountryLocalization("sx", "ইংরেজি", "সিন্ট মার্টেন"),
  CountryLocalization("sk", "স্লোভাক", "স্লোভাকিয়া"),
  CountryLocalization("si", "স্লোভেনীয়", "স্লোভানিয়া"),
  CountryLocalization("sb", "ইংরেজি", "সলোমন দ্বীপপুঞ্জ"),
  CountryLocalization("so", "আরবী", "সোমালিয়া"),
  CountryLocalization("za", "ইংরেজি", "দক্ষিণ আফ্রিকা"),
  CountryLocalization("kr", "কোরিয়ান", "দক্ষিণ কোরিয়া"),
  CountryLocalization("ss", "নুয়ার", "দক্ষিণ সুদান"),
  CountryLocalization("es", "স্প্যানিশ", "স্পেন"),
  CountryLocalization("lk", "তামিল", "শ্রীলঙ্কা"),
  CountryLocalization("bl", "ফরাসি", "সেন্ট বারথেলিমি"),
  CountryLocalization("sh", "ইংরেজি", "সেন্ট হেলেনা"),
  CountryLocalization("kn", "ইংরেজি", "সেন্ট কিটস ও নেভিস"),
  CountryLocalization("lc", "ইংরেজি", "সেন্ট লুসিয়া"),
  CountryLocalization("mf", "ফরাসি", "সেন্ট মার্টিন"),
  CountryLocalization("pm", "ফরাসি", "সেন্ট পিয়ের ও মিকুয়েলন"),
  CountryLocalization("vc", "ইংরেজি", "সেন্ট ভিনসেন্ট ও গ্রেনাডিনস"),
  CountryLocalization("sd", "আরবী", "সুদান"),
  CountryLocalization("sr", "ডাচ", "সুরিনাম"),
  CountryLocalization("sj", "নরওয়েজিয়ান বোকমাল", "স্বালবার্ড ও জান মেয়েন"),
  CountryLocalization("sz", "ইংরেজি", "সোয়াজিল্যান্ড"),
  CountryLocalization("se", "সুইডিশ", "সুইডেন"),
  CountryLocalization("ch", "সুইস জার্মান", "সুইজারল্যান্ড"),
  CountryLocalization("sy", "আরবী", "সিরিয়া"),
  CountryLocalization("st", "পর্তুগীজ", "সাওটোমা ও প্রিন্সিপি"),
  CountryLocalization("tw", "চীনা", "তাইওয়ান"),
  CountryLocalization("tj", "তাজিক", "তাজিকিস্তান"),
  CountryLocalization("tz", "মাকোন্দে", "তাঞ্জানিয়া"),
  CountryLocalization("th", "থাই", "থাইল্যান্ড"),
  CountryLocalization("tl", "পর্তুগীজ", "তিমুর-লেস্তে"),
  CountryLocalization("tg", "ফরাসি", "টোগো"),
  CountryLocalization("tk", "ইংরেজি", "টোকেলাউ"),
  CountryLocalization("to", "টোঙ্গান", "টোঙ্গা"),
  CountryLocalization("tt", "ইংরেজি", "ত্রিনিনাদ ও টোব্যাগো"),
  CountryLocalization("tn", "ফরাসি", "তিউনিসিয়া"),
  CountryLocalization("tr", "তুর্কী", "তুরস্ক"),
  CountryLocalization("tm", "তুর্কমেনী", "তুর্কমেনিস্তান"),
  CountryLocalization("tc", "ইংরেজি", "তুর্কস ও কাইকোস দ্বীপপুঞ্জ"),
  CountryLocalization("tv", "ইংরেজি", "টুভালু"),
  CountryLocalization("um", "ইংরেজি", "যুক্তরাষ্ট্রের পার্শ্ববর্তী দ্বীপপুঞ্জ"),
  CountryLocalization("vi", "ইংরেজি", "মার্কিন যুক্তরাষ্ট্রের ভার্জিন দ্বীপপুঞ্জ"),
  CountryLocalization("ug", "সোয়াহিলি", "উগান্ডা"),
  CountryLocalization("ua", "ইউক্রেনীয়", "ইউক্রেন"),
  CountryLocalization("ae", "আরবী", "সংযুক্ত আরব আমিরাত"),
  CountryLocalization("gb", "ইংরেজি", "যুক্তরাজ্য"),
  CountryLocalization("us", "লাকোটা", "মার্কিন যুক্তরাষ্ট্র"),
  CountryLocalization("uy", "স্প্যানিশ", "উরুগুয়ে"),
  CountryLocalization("uz", "উজবেকীয়", "উজবেকিস্তান"),
  CountryLocalization("vu", "ফরাসি", "ভানুয়াটু"),
  CountryLocalization("va", "ইতালিয়", "ভ্যাটিকান সিটি"),
  CountryLocalization("ve", "স্প্যানিশ", "ভেনেজুয়েলা"),
  CountryLocalization("vn", "ভিয়েতনামী", "ভিয়েতনাম"),
  CountryLocalization("wf", "ফরাসি", "ওয়ালিস ও ফুটুনা"),
  CountryLocalization("eh", "আরবী", "পশ্চিম সাহারা"),
  CountryLocalization("ye", "আরবী", "ইয়েমেন"),
  CountryLocalization("zm", "ইংরেজি", "জাম্বিয়া"),
  CountryLocalization("zw", "উত্তর এন্দেবিলি", "জিম্বাবোয়ে"),
  CountryLocalization("ax", "সুইডিশ", "আলান্ড দ্বীপপুঞ্জ"),
)
