/*
 * Copyright 2024 teogor (Teodor Grigor)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.teogor.xenoglot.atlas.extended

import dev.teogor.xenoglot.atlas.CountryLocalization
import kotlin.collections.List

/**
 * Holds the internal list of country-language mappings used for lookups within the package for
 * language code bs.
 *
 * This property contains a hardcoded list of [CountryLocalization] objects, each representing
 * a country and its associated official languages. This list is used by [CountryLanguageRegistry]
 * to provide access to country-language data and should not be modified directly.
 *
 * @see CountryLocalization
 * @see CountryLanguageRegistry
 */
internal val _countryLanguageMappings_bs: List<CountryLocalization> = listOf(
  CountryLocalization("af", "perzijski", "Afganistan"),
  CountryLocalization("al", "albanski", "Albanija"),
  CountryLocalization("dz", "francuski", "Alžir"),
  CountryLocalization("as", "engleski", "Američka Samoa"),
  CountryLocalization("ad", "katalonski", "Andora"),
  CountryLocalization("ao", "lingala", "Angola"),
  CountryLocalization("ai", "engleski", "Angvila"),
  CountryLocalization("ag", "engleski", "Antigva i Barbuda"),
  CountryLocalization("ar", "španski", "Argentina"),
  CountryLocalization("am", "armenski", "Armenija"),
  CountryLocalization("aw", "holandski", "Aruba"),
  CountryLocalization("au", "engleski", "Australija"),
  CountryLocalization("at", "engleski", "Austrija"),
  CountryLocalization("az", "azerbejdžanski", "Azerbejdžan"),
  CountryLocalization("bs", "engleski", "Bahami"),
  CountryLocalization("bh", "arapski", "Bahrein"),
  CountryLocalization("bd", "bengalski", "Bangladeš"),
  CountryLocalization("bb", "engleski", "Barbados"),
  CountryLocalization("by", "bjeloruski", "Bjelorusija"),
  CountryLocalization("be", "francuski", "Belgija"),
  CountryLocalization("bz", "engleski", "Belize"),
  CountryLocalization("bj", "francuski", "Benin"),
  CountryLocalization("bm", "engleski", "Bermuda"),
  CountryLocalization("bt", "džonga", "Butan"),
  CountryLocalization("bo", "španski", "Bolivija"),
  CountryLocalization("ba", "bosanski", "Bosna i Hercegovina"),
  CountryLocalization("bw", "engleski", "Bocvana"),
  CountryLocalization("br", "portugalski", "Brazil"),
  CountryLocalization("io", "engleski", "Britanska Teritorija u Indijskom Okeanu"),
  CountryLocalization("vg", "engleski", "Britanska Djevičanska ostrva"),
  CountryLocalization("bn", "malajski", "Brunej"),
  CountryLocalization("bg", "bugarski", "Bugarska"),
  CountryLocalization("bf", "francuski", "Burkina Faso"),
  CountryLocalization("bi", "francuski", "Burundi"),
  CountryLocalization("kh", "kmerski", "Kambodža"),
  CountryLocalization("cm", "basa", "Kamerun"),
  CountryLocalization("ca", "francuski", "Kanada"),
  CountryLocalization("ic", "španski", "Kanarska ostrva"),
  CountryLocalization("cv", "zelenortski", "Kape Verde"),
  CountryLocalization("bq", "holandski", "Karipska Holandija"),
  CountryLocalization("ky", "engleski", "Kajmanska ostrva"),
  CountryLocalization("cf", "lingala", "Centralnoafrička Republika"),
  CountryLocalization("ea", "španski", "Seuta i Melilja"),
  CountryLocalization("td", "arapski", "Čad"),
  CountryLocalization("cl", "španski", "Čile"),
  CountryLocalization("cn", "tibetanski", "Kina"),
  CountryLocalization("cx", "engleski", "Božićno ostrvo"),
  CountryLocalization("cc", "engleski", "Kokosova (Keelingova) ostrva"),
  CountryLocalization("co", "španski", "Kolumbija"),
  CountryLocalization("km", "arapski", "Komori"),
  CountryLocalization("cg", "lingala", "Kongo"),
  CountryLocalization("cd", "svahili", "Demokratska Republika Kongo"),
  CountryLocalization("ck", "engleski", "Kukova ostrva"),
  CountryLocalization("cr", "španski", "Kostarika"),
  CountryLocalization("hr", "hrvatski", "Hrvatska"),
  CountryLocalization("cu", "španski", "Kuba"),
  CountryLocalization("cw", "holandski", "Kurasao"),
  CountryLocalization("cy", "engleski", "Kipar"),
  CountryLocalization("cz", "češki", "Češka"),
  CountryLocalization("ci", "francuski", "Obala Slonovače"),
  CountryLocalization("dk", "engleski", "Danska"),
  CountryLocalization("dg", "engleski", "Dijego Garsija"),
  CountryLocalization("dj", "francuski", "Džibuti"),
  CountryLocalization("dm", "engleski", "Dominika"),
  CountryLocalization("do", "španski", "Dominikanska Republika"),
  CountryLocalization("ec", "kečua", "Ekvador"),
  CountryLocalization("eg", "arapski", "Egipat"),
  CountryLocalization("sv", "španski", "Salvador"),
  CountryLocalization("gq", "španski", "Ekvatorijalna Gvineja"),
  CountryLocalization("er", "tigrinja", "Eritreja"),
  CountryLocalization("ee", "estonski", "Estonija"),
  CountryLocalization("et", "amharski", "Etiopija"),
  CountryLocalization("fk", "engleski", "Folklandska ostrva"),
  CountryLocalization("fo", "farski", "Farska ostrva"),
  CountryLocalization("fj", "engleski", "Fidži"),
  CountryLocalization("fi", "švedski", "Finska"),
  CountryLocalization("fr", "njemački (Švicarska)", "Francuska"),
  CountryLocalization("gf", "francuski", "Francuska Gvajana"),
  CountryLocalization("pf", "francuski", "Francuska Polinezija"),
  CountryLocalization("ga", "francuski", "Gabon"),
  CountryLocalization("gm", "engleski", "Gambija"),
  CountryLocalization("ge", "osetski", "Gruzija"),
  CountryLocalization("de", "donjolužičkosrpski", "Njemačka"),
  CountryLocalization("gh", "engleski", "Gana"),
  CountryLocalization("gi", "engleski", "Gibraltar"),
  CountryLocalization("gr", "grčki", "Grčka"),
  CountryLocalization("gl", "kalalisutski", "Grenland"),
  CountryLocalization("gd", "engleski", "Grenada"),
  CountryLocalization("gp", "francuski", "Gvadalupe"),
  CountryLocalization("gu", "engleski", "Guam"),
  CountryLocalization("gt", "španski", "Gvatemala"),
  CountryLocalization("gg", "engleski", "Gernzi"),
  CountryLocalization("gn", "francuski", "Gvineja"),
  CountryLocalization("gw", "portugalski", "Gvineja-Bisao"),
  CountryLocalization("gy", "engleski", "Gvajana"),
  CountryLocalization("ht", "francuski", "Haiti"),
  CountryLocalization("hn", "španski", "Honduras"),
  CountryLocalization("hk", "kineski", "Hong Kong (SAR Kina)"),
  CountryLocalization("hu", "mađarski", "Mađarska"),
  CountryLocalization("is", "islandski", "Island"),
  CountryLocalization("in", "nepalski", "Indija"),
  CountryLocalization("id", "Indonesian", "Indonezija"),
  CountryLocalization("ir", "perzijski", "Iran"),
  CountryLocalization("iq", "sjeverni luri", "Irak"),
  CountryLocalization("ie", "engleski", "Irska"),
  CountryLocalization("im", "manks", "Ostrvo Man"),
  CountryLocalization("il", "engleski", "Izrael"),
  CountryLocalization("it", "njemački", "Italija"),
  CountryLocalization("jm", "engleski", "Jamajka"),
  CountryLocalization("jp", "japanski", "Japan"),
  CountryLocalization("je", "engleski", "Jersey"),
  CountryLocalization("jo", "arapski", "Jordan"),
  CountryLocalization("kz", "kazaški", "Kazahstan"),
  CountryLocalization("ke", "somalski", "Kenija"),
  CountryLocalization("ki", "engleski", "Kiribati"),
  CountryLocalization("xk", "srpski", "Kosovo"),
  CountryLocalization("kw", "arapski", "Kuvajt"),
  CountryLocalization("kg", "ruski", "Kirgistan"),
  CountryLocalization("la", "laoski", "Laos"),
  CountryLocalization("lv", "latvijski", "Latvija"),
  CountryLocalization("lb", "arapski", "Liban"),
  CountryLocalization("ls", "engleski", "Lesoto"),
  CountryLocalization("lr", "engleski", "Liberija"),
  CountryLocalization("ly", "arapski", "Libija"),
  CountryLocalization("li", "njemački (Švicarska)", "Lihtenštajn"),
  CountryLocalization("lt", "litvanski", "Litvanija"),
  CountryLocalization("lu", "luksemburški", "Luksemburg"),
  CountryLocalization("mo", "portugalski", "Makao (SAR Kina)"),
  CountryLocalization("mk", "albanski", "Makedonija"),
  CountryLocalization("mg", "francuski", "Madagaskar"),
  CountryLocalization("mw", "engleski", "Malavi"),
  CountryLocalization("my", "tamilski", "Malezija"),
  CountryLocalization("ml", "francuski", "Mali"),
  CountryLocalization("mt", "engleski", "Malta"),
  CountryLocalization("mh", "engleski", "Maršalova ostrva"),
  CountryLocalization("mq", "francuski", "Martinik"),
  CountryLocalization("mr", "arapski", "Mauritanija"),
  CountryLocalization("mu", "mauricijski kreolski", "Mauricijus"),
  CountryLocalization("yt", "francuski", "Majote"),
  CountryLocalization("mx", "španski", "Meksiko"),
  CountryLocalization("fm", "engleski", "Mikronezija"),
  CountryLocalization("md", "ruski", "Moldavija"),
  CountryLocalization("mc", "francuski", "Monako"),
  CountryLocalization("mn", "mongolski", "Mongolija"),
  CountryLocalization("me", "srpski", "Crna Gora"),
  CountryLocalization("ms", "engleski", "Monserat"),
  CountryLocalization("ma", "centralnoatlaski tamazigt", "Maroko"),
  CountryLocalization("mz", "makuva-meto", "Mozambik"),
  CountryLocalization("mm", "burmanski", "Mjanmar"),
  CountryLocalization("na", "engleski", "Namibija"),
  CountryLocalization("nr", "engleski", "Nauru"),
  CountryLocalization("np", "nepalski", "Nepal"),
  CountryLocalization("nl", "engleski", "Holandija"),
  CountryLocalization("nc", "francuski", "Nova Kaledonija"),
  CountryLocalization("nz", "engleski", "Novi Zeland"),
  CountryLocalization("ni", "španski", "Nikaragva"),
  CountryLocalization("ne", "hausa", "Niger"),
  CountryLocalization("ng", "hausa", "Nigerija"),
  CountryLocalization("nu", "engleski", "Niue"),
  CountryLocalization("nf", "engleski", "Ostrvo Norfolk"),
  CountryLocalization("kp", "korejski", "Sjeverna Koreja"),
  CountryLocalization("mp", "engleski", "Sjeverna Marijanska ostrva"),
  CountryLocalization("no", "sjeverni sami", "Norveška"),
  CountryLocalization("om", "arapski", "Oman"),
  CountryLocalization("pk", "engleski", "Pakistan"),
  CountryLocalization("pw", "engleski", "Palau"),
  CountryLocalization("ps", "arapski", "Palestinska Teritorija"),
  CountryLocalization("pa", "španski", "Panama"),
  CountryLocalization("pg", "engleski", "Papua Nova Gvineja"),
  CountryLocalization("py", "španski", "Paragvaj"),
  CountryLocalization("pe", "španski", "Peru"),
  CountryLocalization("ph", "filipino", "Filipini"),
  CountryLocalization("pn", "engleski", "Pitkernska Ostrva"),
  CountryLocalization("pl", "poljski", "Poljska"),
  CountryLocalization("pt", "portugalski", "Portugal"),
  CountryLocalization("pr", "engleski", "Porto Riko"),
  CountryLocalization("qa", "arapski", "Katar"),
  CountryLocalization("ro", "rumunski", "Rumunija"),
  CountryLocalization("ru", "tatarski", "Rusija"),
  CountryLocalization("rw", "engleski", "Ruanda"),
  CountryLocalization("re", "francuski", "Reunion"),
  CountryLocalization("ws", "engleski", "Samoa"),
  CountryLocalization("sm", "talijanski", "San Marino"),
  CountryLocalization("sa", "arapski", "Saudijska Arabija"),
  CountryLocalization("sn", "francuski", "Senegal"),
  CountryLocalization("rs", "srpski", "Srbija"),
  CountryLocalization("cs", "srpski", "Serbia and Montenegro"),
  CountryLocalization("sc", "francuski", "Sejšeli"),
  CountryLocalization("sl", "engleski", "Sijera Leone"),
  CountryLocalization("sg", "tamilski", "Singapur"),
  CountryLocalization("sx", "engleski", "Sint Marten"),
  CountryLocalization("sk", "slovački", "Slovačka"),
  CountryLocalization("si", "slovenski", "Slovenija"),
  CountryLocalization("sb", "engleski", "Solomonska Ostrva"),
  CountryLocalization("so", "arapski", "Somalija"),
  CountryLocalization("za", "engleski", "Južnoafrička Republika"),
  CountryLocalization("kr", "korejski", "Južna Koreja"),
  CountryLocalization("ss", "nuer", "Južni Sudan"),
  CountryLocalization("es", "španski", "Španija"),
  CountryLocalization("lk", "tamilski", "Šri Lanka"),
  CountryLocalization("bl", "francuski", "Sveti Bartolomej"),
  CountryLocalization("sh", "engleski", "Sveta Helena"),
  CountryLocalization("kn", "engleski", "Sveti Kits i Nevis"),
  CountryLocalization("lc", "engleski", "Sveta Lucija"),
  CountryLocalization("mf", "francuski", "Sveti Martin"),
  CountryLocalization("pm", "francuski", "Sveti Petar i Mikelon"),
  CountryLocalization("vc", "engleski", "Sveti Vinsent i Grenadin"),
  CountryLocalization("sd", "arapski", "Sudan"),
  CountryLocalization("sr", "holandski", "Surinam"),
  CountryLocalization("sj", "norveški (Bokmal)", "Svalbard i Jan Majen"),
  CountryLocalization("sz", "engleski", "Svazilend"),
  CountryLocalization("se", "švedski", "Švedska"),
  CountryLocalization("ch", "njemački (Švicarska)", "Švicarska"),
  CountryLocalization("sy", "arapski", "Sirija"),
  CountryLocalization("st", "portugalski", "Sao Tome i Principe"),
  CountryLocalization("tw", "kineski", "Tajvan"),
  CountryLocalization("tj", "tadžički", "Tadžikistan"),
  CountryLocalization("tz", "makonde", "Tanzanija"),
  CountryLocalization("th", "tajlandski", "Tajland"),
  CountryLocalization("tl", "portugalski", "Istočni Timor"),
  CountryLocalization("tg", "francuski", "Togo"),
  CountryLocalization("tk", "engleski", "Tokelau"),
  CountryLocalization("to", "tonganski", "Tonga"),
  CountryLocalization("tt", "engleski", "Trinidad i Tobago"),
  CountryLocalization("tn", "francuski", "Tunis"),
  CountryLocalization("tr", "turski", "Turska"),
  CountryLocalization("tm", "turkmenski", "Turkmenistan"),
  CountryLocalization("tc", "engleski", "Ostrva Turks i Kaikos"),
  CountryLocalization("tv", "engleski", "Tuvalu"),
  CountryLocalization("um", "engleski", "Američka Vanjska Ostrva"),
  CountryLocalization("vi", "engleski", "Američka Djevičanska ostrva"),
  CountryLocalization("ug", "svahili", "Uganda"),
  CountryLocalization("ua", "ukrajinski", "Ukrajina"),
  CountryLocalization("ae", "arapski", "Ujedinjeni Arapski Emirati"),
  CountryLocalization("gb", "engleski", "Velika Britanija"),
  CountryLocalization("us", "lakota", "Sjedinjene Američke Države"),
  CountryLocalization("uy", "španski", "Urugvaj"),
  CountryLocalization("uz", "uzbečki", "Uzbekistan"),
  CountryLocalization("vu", "francuski", "Vanuatu"),
  CountryLocalization("va", "talijanski", "Vatikan"),
  CountryLocalization("ve", "španski", "Venecuela"),
  CountryLocalization("vn", "vijetnamski", "Vijetnam"),
  CountryLocalization("wf", "francuski", "Ostrva Valis i Futuna"),
  CountryLocalization("eh", "arapski", "Zapadna Sahara"),
  CountryLocalization("ye", "arapski", "Jemen"),
  CountryLocalization("zm", "engleski", "Zambija"),
  CountryLocalization("zw", "sjeverni ndebele", "Zimbabve"),
  CountryLocalization("ax", "švedski", "Olandska ostrva"),
)
